### ISSUE TITLE
JRUBY-5283 Thread specs fail sporadically on Travis

### ISSUE THREAD

**Issue by BanzaiMan** [jruby/jruby#1011]
See:
https://travis-ci.org/jruby/jruby/jobs/11307141#L544
https://travis-ci.org/jruby/jruby/jobs/11307142#L573

http://bugs.jruby.org/5283

These pass on my local machines, but they tend to fail with high probability on Travis. I am not sure why. Maybe it is Linux-specific, but I haven't tested it.

**Comment by kares** [comment]
and its back after almost 4y :wilted_flower:
