### ISSUE TITLE
ThreadGroup of Threads for Fibers is incorrect

### ISSUE THREAD

**Issue by halorgium** [jruby/jruby#1016]
This might be related to the issue with `Thread.current` being incorrect inside a `Fiber`. 
Is this an internal detail?

[Repro](https://gist.github.com/halorgium/c38e15e9d13adb2306c8)

/cc http://jira.codehaus.org/browse/JRUBY-7081

**Comment by kares** [comment]
should be fixed with: https://github.com/jruby/jruby/issues/4920 (in JRuby >= 9.1.16.0)
