### ISSUE TITLE
Slowdown when enabling invokedynamic for YAML + ActiveRecord example

### ISSUE THREAD

**Issue by donv** [jruby/jruby#1023]
Given the example for issue #1005 for equal settings just enabling invokedynamic the performance is halved (run time is doubled).

The core of the example is reading and parsing a YAML file and storing records in ActiveRecord using DerbyDB (JavaDB).

Performance should be equal or better with invokedynamic enabled.

**Comment by enebo** [comment]
@headius @donv this is 3+ years old and indy and our runtimes have changed a lot.  @donv is there a way you can check to see if this is still an issue?

**Comment by donv** [comment]
Hi!

Sorry for the late reply.  Still 1000 messages behind on the JRuby mailing list 😄 .

Since this issue is so old, and the world has changed so much, I will close this issue.

I will open a new issue if I try InDy in the future.  All our production systems run without InDy.
