### ISSUE TITLE
Regarding slow bootup time jruby 1.7.4 + redhat 64bit + 17.0..40 java

### ISSUE THREAD

**Issue by abhishek0** [jruby/jruby#1025]
I have been facing this problem since I started off with jruby. I used the bundled jdk which ships with redhat. On my development machine, Fedora, server and everything loads normally. But on production redhat machine, the bootup time for server is forever.

I thought that using openjdk might be the issue so I started using oracle jdk 
Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) 64-Bit Server VM (build 24.0-b56, mixed mode)

But now I am seeing the error libjffi-1.2.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
and it takes even longer

I have looked into this issue https://github.com/jruby/jruby/issues/626 but I don't know how to resolve this. 
Please help

**Comment by enebo** [comment]
This works in 9k and we will never fix this in 1.7.x as it is winding down....resolving.
