### ISSUE TITLE
Process#spawn doesn't return the child pid on *nix.

### ISSUE THREAD

**Issue by ragaskar** [jruby/jruby#1033]
Similar to this old ticket for popen, popen4: http://jira.codehaus.org/browse/JRUBY-4908

Process.spawn creates two processes, a bin/sh -c and a corresponding child jruby/java process. The pid returned is for the former, killing the pid doesn't necessarily result in the child shutting down. 

The pid is as expected under OSX (eg, there's no shell process, we get the java process, and it kills correctly). 

For now we're working around this by using popen, but wondering if whatever fix was added to popen needs to also be added to Process#spawn.

**Comment by AlexWayfer** [comment]
What about `spawn 'ruby command.rb', pgroup: true`?

**Comment by headius** [comment]
This is very old and almost certainly not valid anymore. If spawn was not actually returning the child pid, we'd have a lot more things broken. We've also completely overhauled the Process subsystem multiple times since this issue was filed, and the original JIRA issue is no longer accessible.

If there are any ongoing problems with Process or `spawn`, please open new issues.

**Comment by byteit101** [comment]
This is still valid and subspawn needs to deal with this case too, so re-opening and assigning to me
```
jruby-9.4.0.0 :001 > p spawn 'ruby -e \'p [$$, :child]\''
1418394
 => 1418394 
jruby-9.4.0.0 :002 > [1418395, :child]
```

**Comment by headius** [comment]
Is there something different on Linux for this then? Here's JRuby 10-snapshot on my MacOS system:

```
irb(main):001> p spawn 'ruby -e \'p [$$, :child]\''
2264
=> 2264
irb(main):002> [2264, :child]
```

**Comment by headius** [comment]
We discussed on Matrix and this actually was fixed with the big port of popen logic I did some time ago. Additional work is needed in subspawn (the new path forward for process launching on JRuby) but it is indeed working properly in JRuby's built-in process logic.

**Comment by ragaskar** [comment]
wow, kudos to you all for taking the time to look into a ten year old issue and provide a resolution, I feel like most people would have just written it off and closed it as "stale". Thanks for all your work on Jruby!
