### ISSUE TITLE
require_relative != require in jars on windows

### ISSUE THREAD

**Issue by byteit101** [jruby/jruby#1083]
If you have a ruby app in a jar on windows, and require the same file via both require_relative and require, you get the file loaded twice as `require_relative` loads `file:C:/foo.jar!/file.rb` while `require` loads `file:/C:/foo.jar!/file.rb`

Original test case: https://github.com/jruby/jrubyfx/blob/master/samples/fxml/Demo.rb  and go to file > create jar (may take awhile...) and save the jar somewhere. then run the jar, and you get const overrides because several files are loaded twice, such as 
`jrubyfx/utils/common_converters.rb`
from 
`jrubyfx/core_ext/drag_event.rb:17 require`
and
`jrubyfx/utils/common_utils.rb:17 require_relative`

**Comment by headius** [comment]
No follow-up since 2013 so this may very well be working now. If it is not, it will likely work properly after #5764.
