### ISSUE TITLE
Make FFI into a default gem

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1085]
JRuby currently ships FFI in the box, but there's a number of files that could be moved into the regular gem and versioned separately.

**Comment by edipofederle** [comment]
@headius this is related with https://github.com/headius/jnr-ffi ?

**Comment by headius** [comment]
@edipofederle Actually this is done! We migrated 9.3 to using the FFI gem (with our extension still shipped in JRuby) and all the .rb files now come from the gem. We later did the same for 9.2 in the 9.2.20 release, so I'll mark it fixed in that one (grr why don't you let me set multiple milestones, GitHub?)

**Comment by headius** [comment]
This was done in 9.2.20.0.
