### ISSUE TITLE
JRuby 1.7.5 doesn't handle wildcards during gem install anymore (on Windows)

### ISSUE THREAD

**Issue by chuckremes** [jruby/jruby#1093]
When running JRuby 1.7.4 on Windows, one can move into a directory that contains a gem file (e.g. somegem-1.0.0.gem) and install it without using the entire name:

```
jruby -S gem install *.gem
```
or
```
jruby -S gem install somegem*.gem
```

Under 1.7.5, these commands now return:

ERROR: Could not find a valid gem '*.gem' (>= 0) in any repository.

To work, the entire name must now be handed off to the gem command:

```
jruby -S gem install somegem-1.0.0.gem
```

**Comment by enebo** [comment]
This second problem mentioned in this issue is because we are not properly handling quotes or wildcards like a normal windows application would.  MRI does this processing.  We have a more modern issue open on this (I promise) but I am not going to hunt for it.
