### ISSUE TITLE
JRuby 1.7.5 issues with Rails Console on Windows

### ISSUE THREAD

**Issue by avinmathew** [jruby/jruby#1096]
I just tried updating to JRuby 1.7.5 but found that Rails Console on Windows has the following issues:
- There is no console prompt by default. I had to add `IRB.conf[:PROMPT_MODE] = :SIMPLE` to my `.irbrc`. This isn't required under 1.7.4.
- The first command does not echo back to terminal. Subsequent commands are fine and echo properly.
- Typing `exit` and pressing enter doesn't immediately return to the terminal prompt and I have to press enter again to do so.
- Tab completion isn't working. However, it does work with standard IRB now.

I noticed that `Switch to inspect mode` is outputted during the load process. This isn't there under 1.7.4.

I'm using Java 1.7.0_25 and Rails 3.2.14. The problems occur in Command Prompt, PowerShell and Git Bash.

**Comment by eliaszica** [comment]
+1

Gitbash: git version 2.9.3.windows.1
JRuby: jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.74-b02 on 1.8.0_74-b02 +jit [mswin32-x86_64]

**Comment by headius** [comment]
This can't still be an issue, right? @enebo Do you try Rails console when you verify 1.7 releases on Windows?

**Comment by hathawad** [comment]
I haven't seen this issue on `1.7.25` windows

**Comment by headius** [comment]
@hathawad Thanks! 👍
