### ISSUE TITLE
IO.pipe

### ISSUE THREAD

**Issue by route** [jruby/jruby#1097]
This code works properly on MRI
``` ruby
def test_closing_write_end_of_pipe
  r, w = IO.pipe

  stdout = STDOUT.dup
  stdout.autoclose = false
  $stdout = w
  STDOUT.reopen(w)

  pid = Process.spawn('sleep 3 && echo "cat"')
  w.close

  STDOUT.reopen(stdout)
  $stdout = STDOUT

  r.read
end
```
At the end we will see the output of subprocess. We don't need write end of pipe in our process so we can freely close it. But for jruby the output is an empty string.

**Comment by rtyler** [comment]
I'm wondering if this issue should be closed or not

**Comment by headius** [comment]
This does work in 9k on platforms where it's supported (not Windows). It will never work like MRI in the 1.7.x line. So we'll call it fixed in 9k.pre1.

**Comment by route** [comment]
Thank you guys! I should definitely check out 9k!
