### ISSUE TITLE
Re-port IO#reopen logic

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1107]
Our reopen logic is pretty disgusting, and is one of the few areas of IO that has not gotten re-ported from MRI. This bug is to do a re-port and make logic match up.

I have a commit going in shortly for #1104 that starts this process in order to fix some unusual reopen scenarios, but there's more work to do. The work needed is in both the reopen logic and in the libc-equivalents it calls.

**Comment by kares** [comment]
sounds like this has been done as part of 9K's magnificent IO revamp, right :dango: ?
