### ISSUE TITLE
Enumerable#sort_by raises wrong error for incomparable items

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1113]
For #1105 I explored the logic for when elements in an Enumerable do not compare. On both JRuby and MRI, this results in an error, but the error is different: JRuby raises TypeError (trying to convert the false comparable result to an int) and MRI raises ArgumentError.

It's a minor difference, but it should be fixed.

```
$ jruby -e "[5,4,3,2,1,0].sort_by {|i| next nil if i == 3; i}"
TypeError: no implicit conversion from nil to integer
  sort_by at org/jruby/RubyEnumerable.java:479
   (root) at -e:1

$ rvm ruby-head do ruby -e "[5,4,3,2,1,0].sort_by {|i| next nil if i == 3; i}"
-e:1:in `sort_by': comparison of NilClass with 2 failed (ArgumentError)
    from -e:1:in `<main>'
```

**Comment by kares** [comment]
both 1.7.24 and 9.0.5 now behave as expected : 
```
ArgumentError: comparison of NilClass with 4 failed
  sort_by at org/jruby/RubyEnumerable.java:525
    <top> at -e:1
```
