### ISSUE TITLE
uninitialized constant Krypt::ASN1::BOOLEAN

### ISSUE THREAD

**Issue by atambo** [jruby/jruby#1119]
I get the following exception when trying to boot a rails app with jruby-openssl 0.9.2 on jruby 1.7.4 or jruby 1.7.5 using warbler. But if I use jruby-openssl 0.8.8 things are fine.

Stacktrace:
https://gist.github.com/atambo/6941849

Maybe this is somewhat related to: https://github.com/jruby/jruby/issues/1071

**Comment by kares** [comment]
has been fixed for a while now (by @mkristian) ... Warbler also has support to handle .jar copying to WEB-INF/lib in a way that is easier with class-loaders.
