### ISSUE TITLE
Question about upgrading from 1.6.x to 1.7.x

### ISSUE THREAD

**Issue by seanguo** [jruby/jruby#1130]
Not sure if this is the right place to ask questions. We recently updated from JRuby 1.6.2 to 1.7.4, but got a big memory usage incrementation. 
We use the embedded JRruby engine and the JSR223 API. We use eval to evaluate the script and pass some global variables to the script using ScriptContext.

Has any default behavior been changed for the JRruby 1.7.x?

**Comment by kares** [comment]
closing as this is no longer relevant :)
