### ISSUE TITLE
1.7.5 gemspec ignoring already installed gem and downloads another version

### ISSUE THREAD

**Issue by cdenneen** [jruby/jruby#1144]
logstash.gemspec requires cabin 0.5.0
logstash.gemspec requires ftw 0.0.36
ftw.gemspec requires cabin >0

When building with 1.7.4 all works fine and 0.5.0 is installed
When building with 1.7.5 0.5.0 is installed and then for ftw 0.6.1 (latest cabin) is installed. Then conflict arises using grok filter which depends on cabin:

```
     Gem::LoadError:
       Unable to activate jls-grok-0.10.11, because cabin-0.6.1 conflicts with cabin (~> 0.5.0)
```
Looks like something changed in 1.7.5 which is causing the 0.6.1 to accidentally get downloaded rather than realizing 0.5.0 was already downloaded and meets requirement of >0

**Comment by rtyler** [comment]
@cdenneen is this still an issue or can we go ahead and close this out?

**Comment by cdenneen** [comment]
I haven't looked at this in a while so can close.
