### ISSUE TITLE
chmod inside of File block fails to create file

### ISSUE THREAD

**Issue by jkutner** [jruby/jruby#1149]
While looking at a CI failure on the rubyzip gem, I found that an error
was generated from a line like this:

```
File.open("data/generated/empty_chmod640.txt", "w") { |f| f.chmod(0640) }
```

The error was: 

```
RuntimeError: No such file or directory - data/generated/empty_chmod640.txt
```

I haven't been able to isolate the issue, but it can easily be reproduced from the rubyzip test suite like so:

```
$ git clone git@github.com:rubyzip/rubyzip.git
$ cd rubyzip
$ git checkout cb6e628fb27b3785527945068e01fcc3fa8d8654
$ bundle install
$ bundle exec rake
...
  adding: data/file2.txt (deflated 79%)
deleting: data/file2.txt
    zip warning: zip file empty
RuntimeError: No such file or directory - data/generated/empty_chmod640.txt
...
```

The test suite fails to create it's fixtures because of this line (which is the same as the one shown at the top of the issue):
https://github.com/rubyzip/rubyzip/blob/cb6e628fb27b3785527945068e01fcc3fa8d8654/test/gentestfiles.rb#L96

**Comment by enebo** [comment]
@jkutner @headius I do not see this on MacOS.  Is this specific to Linux?  On 9k, I know we do some native calls now but even with native disabled I am not seeing an issue.

**Comment by jkutner** [comment]
@enebo no, this was definitely on MacOS, so maybe it went away.

**Comment by enebo** [comment]
Well optimistically calling this resolved then!
