### ISSUE TITLE
JFFI Validation Fails on Install

### ISSUE THREAD

**Issue by vindir** [jruby/jruby#1155]
Installing both 1.7.5 and 1.7.6 on CentOS 6.3 brings up a failure to validate libs currently and segfaults ld.so during the install.  Error details are all in the gist below.

ld.so libjffi segfault:  https://gist.github.com/vindir/7ab5ab3305c329ff8c85

**Comment by enebo** [comment]
No update in 2+ years.  Please re-open if there is any new info on this issue...
