### ISSUE TITLE
Pry on 1.7.5,1.7.6 - can't stop listing

### ISSUE THREAD

**Issue by lowang** [jruby/jruby#1158]
After an upgrade I've got a problem using pry, it starts ok but if a long list is inspected it says "<page break> --- Press enter to continue ( q<enter> to break ) --- <page break>" so just q + [enter] or ^c would do the trick. That was right till 1.7.5, now I've got: 

```
<page break> --- Press enter to continue ( q<enter> to break ) --- <page break>
q^Mq^M^C^M^C^M^C^M^C^M^C^M^C^M^C^M^C^M^C^M^C^M^C^M^C^M^C^M^C^M^C^M^M^M^M^M^M^M^M^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^M^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^M^M^M^M^M^M^M^M^M^M^M^M
```

To reproduce:
```
$ gem install pry
$ pry
[1] pry(main)> a = (0..1000).to_a
```
Note: ^Z works as expected. I've got this on OSX with jruby 1.7.5 & 1.7.6 via RVM & pry 0.9.12.2 on 
Java(TM) SE Runtime Environment (build 1.7.0_25-b15) Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode) and Debian with jruby 1.7.5 via tarball on Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) Server VM (build 24.0-b56, mixed mode)

In jruby-1.7.4 everything works correctly both on osx & debian.

**Comment by mvdamme** [comment]
I've just had the same issue with JRuby 1.7.19, so I guess the underlying issue hasn't been fixed yet.
`ruby -v` gives me the following output:
`jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on OpenJDK 64-Bit Server VM 1.6.0_34-b34 +jit [linux-amd64]`

**Comment by enebo** [comment]
I am abandoning fixing this for 1.7.x but it is still present for 9.x.  I am guessing it is still our library dependency not doing something we expect.

**Comment by headius** [comment]
Let's go with the more recent bug for `^C` not working in IRB anymore: #3721.
