### ISSUE TITLE
ScriptingContainer.runScriptlet(PathType.CLASSPATH, filename) should throw a FileNotFoundException

### ISSUE THREAD

**Issue by elcubo** [jruby/jruby#1160]
Example:
```java
scriptingContainer.runScriptlet(PathType.CLASSPATH, "missing_file.rb");
```

This runs and returns null even if the file doesn't exist.

**Comment by kares** [comment]
that is just an optional parameter that servers as a hint with back-traces (more like a `__FILE__` - you can not assume it's always pointing to an existing file) doing a check would likely surprise break a lot of users

**Comment by abonas** [comment]
@kares I ran into this as well, and the other PathType options do alert the user that the file is not found, while the CLASSPATH type just doesn't return any indication to user and it looks like the script ran with "null" which is misleading. So I would ask to consider reopening this issue, I think it's  confusing and also not consistent behavior across different PathType options.
