### ISSUE TITLE
FFI issue on Windows

### ISSUE THREAD

**Issue by keeguon** [jruby/jruby#1166]
Hey,

A few days ago I left a message on the dev mailing list saying I had the following issue: <https://gist.github.com/Keeguon/2c034c9f91cc42d5004c> when generating executables WAR through Warble using jRuby 1.7.4 but using either 1.7.5 (as seen in the log) or 1.7.6 versions of the `jruby-jars` gem and trying to run them on Windows.

Tuesday, @headius got back to me saying it was probably related to the win32 implementation of `resolv.rb` and that I should file an issue here so that's it :). I'm available to discuss this with more details if necessary.

Cheers.

**Comment by enebo** [comment]
I am only resolving since have no new info for 3 years.  Resolving but re-open if you still see this issue.
