### ISSUE TITLE
binding.pry or debugger call from rails contoller leads to .IncompatibleClassChangeError

### ISSUE THREAD

**Issue by dre-hh** [jruby/jruby#1175]
Pry and Debugger do work, when calling a simple Ruby script. Also can enter pry from
rails console and if pry-rails installed rails console boots into pry session by default. But when calling binding.pry or debugger call from rails contoller, following error occurs: 

java.lang.IncompatibleClassChangeError: Found class jline.Terminal, but interface was expected
    at jline.TerminalFactory.create(TerminalFactory.java:101)

Jruby Version:
jruby 1.7.6 (1.9.3p392) 2013-10-22 6004147 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_45-b18 [darwin-x86_64]

rails (4.0.0)
pry (0.9.12.2)
pry-rails (0.3.2)
ruby-debug (0.10.4)
ruby-debug-base (0.10.4 java)

**Comment by scepticulous** [comment]
I wonder why this issue is closed. The same error happends with jruby 9k with debugger, pry and any other debugging tool that requires readline/jline

**Comment by aviflax** [comment]
Sorry to revive an old thread, but I’m having the same problem trying to use pry with 9.1.5.0. Anyone have any tips?

**Comment by aviflax** [comment]
Ah, never mind — I followed the link @mkristian shared above to https://github.com/pry/pry/issues/1144#issuecomment-37256713 and that solved it for me. Thanks @mkristian!

**Comment by karthik3i** [comment]
Hi All,
Debugger is not working, i'm using the following configuration. really i'm upset on this, Please help me.
-- jruby9.1.8.0
-- I installed ruby-debug

**Comment by aviflax** [comment]
@karthik3i try the workaround described in this comment: https://github.com/pry/pry/issues/1144#issuecomment-37256713
