### ISSUE TITLE
Jruby - Potential jruby-openssl-0.9.4 bug

### ISSUE THREAD

**Issue by raisin** [jruby/jruby#1185]
Using jruby-1.6.7 or jruby-1.6.7.1, I get the following warnings and a `Too many redirects` error when running bundle update.

/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PKCS1_PADDING
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant SSLV23_PADDING                                                                                                                               
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NO_PADDING                                                                                                                                   
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PKCS1_OAEP_PADDING                                                                                                                           
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant UNIVERSAL_TAG_NAME                                                                                                                           
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant EOC                                                                                                                                          
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant BOOLEAN                                                                                                                                      
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant INTEGER                                                                                                                                      
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant BIT_STRING                                                                                                                                   
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OCTET_STRING                                                                                                                                 
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NULL                                                                                                                                         
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OBJECT                                                                                                                                       
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OBJECT_DESCRIPTOR                                                                                                                            
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant EXTERNAL                                                                                                                                     
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant REAL                                                                                                                                         
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant ENUMERATED                                                                                                                                   
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant EMBEDDED_PDV                                                                                                                                 
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant UTF8STRING                                                                                                                                   
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant RELATIVE_OID                                                                                                                                 
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant SEQUENCE                                                                                                                                     
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant SET                                                                                                                                          
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NUMERICSTRING                                                                                                                                
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PRINTABLESTRING                                                                                                                              
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant T61STRING                                                                                                                                    
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant VIDEOTEXSTRING                                                                                                                               
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant IA5STRING                                                                                                                                    
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant UTCTIME                                                                                                                                      
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant GENERALIZEDTIME                                                                                                                              
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant GRAPHICSTRING                                                                                                                                
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant ISO64STRING                                                                                                                                  
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant GENERALSTRING                                                                                                                                
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant UNIVERSALSTRING                                                                                                                              
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant CHARACTER_STRING                                                                                                                             
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant BMPSTRING                                                                                                                                    
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant COMPAT                                                                                                                                       
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant RFC2253                                                                                                                                      
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant ONELINE                                                                                                                                      
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant MULTILINE                                                                                                                                    
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant DEFAULT_OBJECT_TYPE                                                                                                                          
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OBJECT_TYPE_TEMPLATE                                                                                                                         
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_OK                                                                                                                                         
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_UNABLE_TO_GET_ISSUER_CERT                                                                                                              
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_UNABLE_TO_GET_CRL
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CERT_SIGNATURE_FAILURE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CRL_SIGNATURE_FAILURE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CERT_NOT_YET_VALID
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CERT_HAS_EXPIRED
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CRL_NOT_YET_VALID
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CRL_HAS_EXPIRED
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_OUT_OF_MEM
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_SELF_SIGNED_CERT_IN_CHAIN
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CERT_CHAIN_TOO_LONG
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CERT_REVOKED
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_INVALID_CA
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_PATH_LENGTH_EXCEEDED
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_INVALID_PURPOSE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CERT_UNTRUSTED
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_CERT_REJECTED
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_SUBJECT_ISSUER_MISMATCH
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_AKID_SKID_MISMATCH
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_AKID_ISSUER_SERIAL_MISMATCH
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_KEYUSAGE_NO_CERTSIGN
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_ERR_APPLICATION_VERIFICATION
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_FLAG_CRL_CHECK
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant V_FLAG_CRL_CHECK_ALL
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PURPOSE_SSL_CLIENT
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PURPOSE_SSL_SERVER
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PURPOSE_NS_SSL_SERVER
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PURPOSE_SMIME_SIGN
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PURPOSE_SMIME_ENCRYPT
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PURPOSE_CRL_SIGN
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PURPOSE_ANY
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant PURPOSE_OCSP_HELPER
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant TRUST_COMPAT
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant TRUST_SSL_CLIENT
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant TRUST_SSL_SERVER
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant TRUST_EMAIL
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant TRUST_OBJECT_SIGN
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant TRUST_OCSP_SIGN
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant TRUST_OCSP_REQUEST
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant DEFAULT_CERT_AREA
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant DEFAULT_CERT_DIR
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant DEFAULT_CERT_FILE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant DEFAULT_CERT_DIR_ENV
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant DEFAULT_CERT_FILE_ENV
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant DEFAULT_PRIVATE_DIR
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant Signer
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant TEXT
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NOCERTS
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NOSIGS
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NOCHAIN
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NOINTERN
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NOVERIFY
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant DETACHED
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant BINARY
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NOATTR
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant NOSMIMECAP
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant VERIFY_NONE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant VERIFY_PEER
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant VERIFY_FAIL_IF_NO_PEER_CERT
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant VERIFY_CLIENT_ONCE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_ALL
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_NO_TICKET
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_SINGLE_ECDH_USE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_SINGLE_DH_USE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_EPHEMERAL_RSA
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_CIPHER_SERVER_PREFERENCE
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_TLS_ROLLBACK_BUG
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_NO_SSLv2
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_NO_SSLv3
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_NO_TLSv1
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_PKCS1_CHECK_1
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_PKCS1_CHECK_2
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_NETSCAPE_CA_DN_BUG
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OP_NETSCAPE_DEMO_CIPHER_CHANGE_BUG
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant VERSION
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OPENSSL_VERSION
/home/tofubean/.rvm/gems/jruby-1.6.7@global/gems/jruby-openssl-0.9.4/lib/jopenssl/load.rb:15 warning: already initialized constant OPENSSL_VERSION_NUMBER
Fetching source index from http://rubygems.org/
Resolving dependencies...
Too many redirects

The Gemfile I used is the following:

source 'http://rubygems.org'
gem 'sinatra', '~> 1.2.6'
gem 'uuid', '~> 2.3.3'
gem 'sequel', '~> 3.27.0'
gem 'active_support', '~> 3.0.0'
gem 'bcrypt-ruby', '~> 3.0.1'

**Comment by kares** [comment]
should work with **0.9.6** (no krypt dependency) ... it's compatible with ancient JRubies such as **1.6.8**
