### ISSUE TITLE
JRuby 1.7.6 / ARM / Raspberry PI / Raspbian / OpenJDK ArgumentError

### ISSUE THREAD

**Issue by jhstatewide** [jruby/jruby#1188]
Testing out JRuby 1.7.6 on Raspberry pi. Even simple test programs fail to execute:

root@raspberrypi:~# jruby -v
jruby 1.7.6 (1.9.3p392) 2013-10-22 6004147 on OpenJDK Zero VM 1.7.0_25-b30 [linux-arm]

root@raspberrypi:~# cat hello.rb 
puts "hello world"

root@raspberrypi:~# jruby hello.rb 
ArgumentError: cannot import class `java.lang.reflect.Modifier' as `Modifier'
        java_import at file:/usr/local/rvm/rubies/jruby-1.7.6/lib/jruby.jar!/jruby/java/core_ext/object.rb:63
                map at org/jruby/RubyArray.java:2413
        java_import at file:/usr/local/rvm/rubies/jruby-1.7.6/lib/jruby.jar!/jruby/java/core_ext/object.rb:22
  ModifierShortcuts at file:/usr/local/rvm/rubies/jruby-1.7.6/lib/jruby.jar!/jruby/java/java_ext/java.lang.rb:73
             (root) at file:/usr/local/rvm/rubies/jruby-1.7.6/lib/jruby.jar!/jruby/java/java_ext/java.lang.rb:72
            require at org/jruby/RubyKernel.java:1082
             (root) at file:/usr/local/rvm/rubies/jruby-1.7.6/lib/jruby.jar!/jruby/java/java_ext.rb:1
            require at org/jruby/RubyKernel.java:1082
             (root) at file:/usr/local/rvm/rubies/jruby-1.7.6/lib/jruby.jar!/jruby/java/java_ext.rb:3

**Comment by enebo** [comment]
Due to length of time with no more information and my last comment where I was able to run JRuby (with jffi unpackaging workarounds) I am closing.  Please re-open if this is still an issue.
