### ISSUE TITLE
jruby-openssl: strange behavior ( forced reconnection ) with 2+ dependent gems.

### ISSUE THREAD

**Issue by digitalextremist** [jruby/jruby#1197]
Having trouble troubleshooting this, but I have two gems in place which depend on `jruby-openssl`, built into `jRuby 1.7.6` since its cool like that.

One gem is [Reel](http://github.com/celluloid/reel) via `SSLServer` and the other is [xmpp4r](https://github.com/xmpp4r/xmpp4r).

Here comes the mysterious part. Everything is fine, even though both have SSL sockets open at any given moment, until I do a code reload. `xmpp4r` has a constant connection and `reel` is waiting for connections or responding to a request. When I do a code reload, I notice `xmpp4r` perform a forced reconnect.

The code reloader is basically this: `load file` with `file` being the path to a file recently modified. Neither `xmpp4r` nor `reel` code is being reloaded, and no other associated code is being reloaded either. Nothing at all related to SSL is being touched whatsoever, except that the code reload operation is supposed to be announced via XMPP immediately ( which therefore never happens, since `xmpp4r` is in a disconnected state in the moments immediately following a code reload.

Based on accidentally acquired diagnostic data gleaned from `--profile`, it seems to be happening somewhere associated with `SSLSocket#sysread`

Please let me know what I can add to this issue to help debug the situation.

I cannot post a repro without serious difficulty, but I have a private repository which ( may cause spontaneous suicide to occur in a variety of cases, but ) I could grant access to, provided I've worked with the coder before and I get assurance of code staying private. This is not a mission critical situation and in fact only applies to my development environment(s), so it's pretty low priority but noteworthy.

**Comment by kares** [comment]
think we shall optimistically close this one (its vague - hard to reproduce).
@digitalextremist if needed (still relevant) please give it a go with latest jruby-openssl and maybe even 9K
