### ISSUE TITLE
backticks potential issue

### ISSUE THREAD

**Issue by mrbrdo** [jruby/jruby#1206]
I've encountered a problem with the ruby-git gem which could be related to JRuby and backticks.

More information: https://github.com/schacon/ruby-git/issues/110

At the moment I cannot spare time to go into hardcore debugging. The issue occured for me in production, where I ran my script using **nohup** (I think this is very relevant). Command: `nohup bundle exec ruby $RUBY_SCRIPT 0<&- &> "$OUT_FILE" &`. The issue did not occur when simply running `bundle exec ruby $RUBY_SCRIPT`. So it must be related with nohup or the IO redirection.

As a sidenote I was using ssh-agent also, with a ssh key in a custom path (with ssh-add), and cloning a private repository. But this is probably not related.

**Comment by rtyler** [comment]
@mrbrdo would it be possible for you to list what commands are actually being run in backticks by the ruby script?

**Comment by enebo** [comment]
No feedback in 3+ years.  Resolving as invalid.  Reopen (and re-test with 9.x instead of 1.7.x since 1.7 will be EOLd soon).
