### ISSUE TITLE
Net::HTTP returns empty response body for HTTPS requests in 2.0 mode

### ISSUE THREAD

**Issue by rykov** [jruby/jruby#1216]
Gemfury customers are reporting problems using the service with jRuby in Ruby 2.0 mode.  We've tracked it down to an odd issue where Net::HTTP returns a successful response, but `response.body` returns an empty string for `https://` requests.

Here's a test program to reproduce:

```
require "net/https"

uri = URI.parse("https://rubygems.org/")
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true

request = Net::HTTP::Get.new(uri.request_uri)
response = http.request(request)
puts "#{response.code} - #{response.body.size}"
```

And the output (tested in 1.7.5 and 1.7.6):

```
$ jruby -S ./test.rb
200 - 9188
$ jruby --2.0 -S ./test.rb 
200 - 0
```

**Comment by simi** [comment]
Hello @enebo. This is problem for 1.7.18 (2.0 version) again. Any chance to get it fixed?

I can fix this temporary with this diff:

```diff
diff --git a/lib/ruby/stdlib/net/http/response.rb b/lib/ruby/stdlib/net/http/response.rb
index b073169..59e856d 100644
--- a/lib/ruby/stdlib/net/http/response.rb
+++ b/lib/ruby/stdlib/net/http/response.rb
@@ -374,9 +374,7 @@ class Net::HTTPResponse
         dest.force_encoding(Encoding::ASCII_8BIT)
       end
       block = proc do |compressed_chunk|
-        @inflate.inflate(compressed_chunk) do |chunk|
-          dest << chunk
-        end
+        dest <<@inflate.inflate(compressed_chunk)
       end
 
       Net::ReadAdapter.new(block)
```

```
$ ruby -v
jruby 1.7.18 (2.0.0p598) 2014-12-22 625381c on OpenJDK 64-Bit Server VM 1.7.0_45-mockbuild_2013_10_16_17_51-b00 +jit [linux-amd64]
```

I've found https://github.com/jruby/jruby/commit/2cbe7e52a7e6a8e43a2066007547ad520b8623b7 also. Is there any chance to get that released in 1.7.x series?

I tried `jruby-openssl` `0.9.5` and `0.9.6`.

Script to reproduce:

```
$ jruby -ropen-uri -ropenssl -e 'p open("https://www.seznam.cz").size'
0
```

Workaround without mokeypatch:

```
$ jruby -ropen-uri -ropenssl -e 'p open("https://www.seznam.cz", {"accept-encoding" => "gzip;q=0,deflate,sdch"}).size'
62042
```

**Comment by headius** [comment]
Well this is an interesting question. Officially, 2.0 mode on JRuby 1.7 is not supported, which means we won't expend any committer effort to maintain it. But we'll happily accept patches from the community that backport 2.0 behaviors from master, so long as they don't impact 1.8 and 1.9 modes.

@simi Wanna try your hand at patching the jruby-1_7 branch?

**Comment by headius** [comment]
@simi Sorry for the delay getting back to you...

The patch in 2cbe7e5 is the right thing to port, and for guarding the behavior you could use something like `if (!runtime.is2_0() && block.isGiven()) { ERROR }`, or you could just not bother and we'll sort that out.

**Comment by simi** [comment]
I would like to help @headius. Thanks for info. I'll try to prepare PR.

**Comment by headius** [comment]
@simi Simple fix would be to include the stdlib files we need from 2.0 into the stdlib 2.0 location.

The 2.0 stdlib files are under lib/ruby/2.0.

We use a forked ruby/ruby repository at jruby/ruby to manage our tweaks to stdlib. See the jruby-ruby* branches there.

In JRuby, under tools, you will see ruby scripts `sync_ruby` and `*globals`. The latter files provide lists of what we copy out of our fork when updating stdlib.

So...figure out which files we need, modify the `globals` file for 2.0 to copy them, and run the script to update 2.0 stdlib from our forked branch.

Simple enough?

**Comment by simi** [comment]
I think this will not work @headius since there's is problem with JRuby 1.7 (experimental Ruby 2.0 mode) ZLib implementation. The fix mentioned in https://github.com/jruby/jruby/issues/1216#issuecomment-68843212 is just monkey patch (probably changing expected behaviour, but it works for me) and not part of Ruby 2.0 stdlib.

Also I don't think it is good idea to polute `JZlibInflate.java` with `if (!runtime.is2_0() && block.isGiven()) { ERROR }` checks.

I can wait for JRuby 9000 if I'm right.

**Comment by headius** [comment]
Oops, I'm sorry...I lost context on what changes were actually needed.

The changes you describe (is2_0 checks) would be acceptable as a user patch for 1.7. Obviously they would not be needed on JRuby master.

Of course, if you can wait for JRuby 9k (and start testing with it right now), that would be excellent too :-)

**Comment by joshuap** [comment]
Hey all, I was just curious if anyone was still planning on patching this. We use compressed responses at Honeybadger and this is preventing our gem from functioning properly for some customers. I totally understand the unsupported argument, though. If someone *does* have a way to quickly patch it for 1.7 I'd happily buy them a coffee or beer. :)

**Comment by headius** [comment]
@joshuap You are running JRuby 1.7 in 2.0 mode?

Patching this bit of behavior for 1.7 may or may not be a lot of work. I suspect it wouldn't be a ton just to get blocks working, and we already have the functionality implemented on master so we can copy and guard it for 2.0 mode.

I'd love to hear if your application has problems running on 9k though. JRuby 1.7's support for 2.0 features is weak and not expected to improve without a lot of external-contributor help.

**Comment by joshuap** [comment]
@headius I haven't heard of anyone having issues on 9k, although a lot of are customers are on MRI, of course (as are we). I'll enable 9k for our gem test suite on travis sometime. I'll also direct anyone I find who is experiencing this to this issue so that they can hopefully weigh in.

**Comment by aryeh-looker** [comment]
For what it's worth, I ran into this issue under JRuby9k. Upgrading to the latest version of `jruby-openssl` (0.9.17) resolved the issue. I also noticed that the patch mentioned (i.e. https://github.com/jruby/jruby/commit/b561183f6e9723e3759ddf1284b35c5500149192) is _not_ in the JRuby9k `net/http` standard library — probably this is on purpose. But just wanted to point it out.

**Comment by sumitmah** [comment]
I'm also facing the same issue `jruby 9.1.2.0 (2.3.0)` will try upgrading `jruby-openssl`

**Comment by sumitmah** [comment]
I'm already on the `jruby-openssl (0.9.17)`
