### ISSUE TITLE
Forcing jruby-complete to execute a command.

### ISSUE THREAD

**Issue by blerins** [jruby/jruby#1218]
Hello!

I'm having some troubles with jruby-complete in environements with rbenv.

``` Shell
$ echo $PATH
/home/blerins/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ java -Djruby.debug.scriptResolution=true -jar target/lib/jruby-complete.jar -S gem install bundler
Found: /home/blerins/.rbenv/shims/gem
SyntaxError: /home/blerins/.rbenv/shims/gem:3: syntax error, unexpected tSTRING_BEG

[ -n "$RBENV_DEBUG" ] && set -x
     ^
$ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ java -Djruby.debug.scriptResolution=true -jar target/lib/jruby-complete.jar -S gem install bundler
Successfully installed bundler-1.3.5
1 gem installed
```

As seen at: https://github.com/jruby/jruby/blob/823e68938eac61a731153775538185ae4df5fe5a/core/src/main/java/org/jruby/util/cli/ArgumentProcessor.java#L495

JRuby always tries to find the script first, I was wondering if there is any possibility to force Jruby to ejecute a command.

related: sstephenson/rbenv#467

Thanks!

**Comment by mkristian** [comment]
fixed via fcec818c
