### ISSUE TITLE
JDK8 provides its own List#sort, Map#replace, and Map#merge

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1249]
We have been providing monkey-patched List#sort, Map#replace, and Map#merge, but they now conflict with the ones from JDK8. For example, sort:

public void sort(Comparator<? super E> c)

We add a sort to list that just turns a passed block into a Comparator. Because Ruby does not do overloads, only the one-argument version in ArrayList is seen, which causes our tests to fail like so:

```
  1) Error:
test_list(TestJavaExtension):
ArgumentError: wrong number of arguments (0 for 1)
    test/test_java_extension.rb:66:in `test_list'
```

**Comment by mdedetrich** [comment]
Needed to use the @colinsurprenant workaround for https://github.com/mdedetrich/java-premailer-wrapper and can confirm that for my case it at least works

**Comment by kares** [comment]
was thinking about a support solution for users running into these while doing https://github.com/jruby/jruby/pull/3802 ... if all methods are native its pretty easy for JRuby to setup different names that would not conflict. users would than alias those when a ruby_ version is preferred in Ruby land e.g. : 
```ruby
java.util.ArrayList.class_eval { alias_method :sort, :ruby_sort }
java.util.HashMap.class_eval { alias merge, ruby_merge; alias replace ruby_replace }
 ```
needs to be done for every List/Map impl but that should be understandable, if its too much of an annoyance we can push it further ...

also, not really a Java 8 conflict but still confusing : 
```ruby
jruby-1.7.24 :001 > java.util.ArrayList.new.first
 => nil 
jruby-1.7.24 :002 > java.util.LinkedList.new.first
Java::JavaUtil::NoSuchElementException: 
	from java.util.LinkedList.getFirst(java/util/LinkedList.java:244)
	from java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	from RUBY.evaluate((irb):2)
```
... feels like `java.util.LinkedList.class_eval { alias_method :first, :ruby_first }` would also come handy!
