### ISSUE TITLE
__FILE__ is broken with -Djruby.compile.mode=FORCE when mixing forward and backward slashes

### ISSUE THREAD

**Issue by perlun** [jruby/jruby#1256]
This one took me quite some time to analyze but I now believe I have a pretty good idea of the problem.

**Scenario**:

* Create a subfolder called `foo`.
* Create a file called foo.rb with the following content:

````
puts "In foo.rb, __FILE__ is #{__FILE__}"

require './foo/bar/baz.rb'
````

* Create a subfolder of foo, called `bar`, in which the `baz.rb` is created with the following content:

````
puts "In baz.rb, __FILE__ is #{__FILE__}"
````

* Run the following command (this one has been using `jruby-complete`, don't know yet if it affects other variants also):

````
java -Djruby.compile.mode=FORCE -jar jruby-complete-1.7.6.jar c:\path\to\your\folder\foo/foo.rb
````

Expected output:

````
In foo.rb, __FILE__ is c:\path\to\your\folder\foo/foo.rb
In baz.rb, __FILE__ is c:\path\to\your\folderfoo/bar/baz.rb
````

Note that in the second line, there is a missing slash between `folder` and `foo`, causing all kinds of weird side effects.

Now, re-run without `-Djruby.compile.mode=FORCE`, and you'll see this:

````
In foo.rb, __FILE__ is c:\path\to\your\folder\foo/foo.rb
In baz.rb, __FILE__ is c:/path/to/your/folder/foo/bar/baz.rb
````

Note how the path is now correct, and not only that - all the slashes are now translated to forward slashes!

Why is this? How can `jruby.compile.mode` affect this? :smile:

As noted, this has been verified with JRuby 1.7.6. I haven't tested with 1.7.8 but I find it quite likely that it's present there also.

**Comment by perlun** [comment]
Let's kill this one now, it's age-old.

**Comment by headius** [comment]
Does it work now? I'm guessing it happened because we always normalize to /
internally, and the compiler is written at least partly in Ruby.
