### ISSUE TITLE
Unable to load EllipticalCurve EC class from JRuby's OpenSSL library

### ISSUE THREAD

**Issue by michaelgpearce** [jruby/jruby#1261]
I hope this is the right place to report this bug (i think it is!).

The class OpenSSL::PKey::EC does not load on JRuby version 1.7.8.  The library loads with the same commands in MRI version 1.9.3p125 and 2.0.0p195.

```bash
~/myprojects/test $ jruby --version
jruby 1.7.8 (1.9.3p392) 2013-11-14 0ce429e on Java HotSpot(TM) 64-Bit Server VM 1.6.0_65-b14-462-11M4609 [darwin-x86_64]
~/myprojects/test $ bundle show jruby-openssl
/Users/test/.rvm/gems/jruby-1.7.8@global/gems/jruby-openssl-0.9.4
~/myprojects/test $ bundle exec irb
```
```ruby
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0> ::OpenSSL::PKey::EC.new("secp256k1")
NameError: uninitialized constant OpenSSL::PKey::EC
	from org/jruby/RubyModule.java:2686:in `const_missing'
	from (irb):2:in `evaluate'
	from org/jruby/RubyKernel.java:1123:in `eval'
	from org/jruby/RubyKernel.java:1519:in `loop'
	from org/jruby/RubyKernel.java:1284:in `catch'
	from org/jruby/RubyKernel.java:1284:in `catch'
	from /Users/test/.rvm/rubies/jruby-1.7.8/bin/irb:13:in `(root)'
```

In MRI:
```ruby
1.9.3p125 :001 > require 'openssl'
 => true 
1.9.3p125 :002 > ::OpenSSL::PKey::EC.new("secp256k1")
 => #<OpenSSL::PKey::EC:0x007f91e31d9670> 
```

**Comment by rtyler** [comment]
FWIW this issue is still present in JRuby 9k, I'm going to add the beginner label to this issue and maybe somebody can use @michaelgpearce's code as a launching point to implementing this behavior

**Comment by p0indexter** [comment]
Still seeing this issue in jRuby 9.0.5.0

**Comment by headius** [comment]
@kares @mkristian: We've had a request to finally address this in the JRuby 9.1 timeframe. What do you think?

https://twitter.com/bdusauso/status/709448399809069056

**Comment by kares** [comment]
tried the above script before and I did not put this in since it was quite uncomplete. not sure how much works but it failed my attempts.

**Comment by headius** [comment]
Moving this to jruby/jruby-openssl#90

**Comment by mohamedhafez** [comment]
just posted a $100 bounty with bountysource.com on the new issue at jruby/jruby-openssl#90, if anyone is interested in working on it, or contributing to the bounty:)
