### ISSUE TITLE
RegexpError with look-behind

### ISSUE THREAD

**Issue by LFDM** [jruby/jruby#1269]
jruby (tested with 1.7.5 and 1.7.8) goes down when confronted with a lookbehind that includes another anchor.

SyntaxError: (RegexpError) invalid pattern in look-behind: /(?<=\bfoo)bar./

**Comment by enebo** [comment]
This appears to have been merged into a later version of Joni since I no longer see a syntax error for lookbehind syntax.  Resolving.
