### ISSUE TITLE
Time.at broken for huge timestamps

### ISSUE THREAD

**Issue by grddev** [jruby/jruby#1304]
The behaviour of `Time.at` is inconsistent in MRI and JRuby.

``` ruby
# jruby 1.7.6
Time.at(2**59) # => 146140482-04-24 17:36:27 +0200
Time.at(2**60) # => -292275055-05-16 17:59:16 +0112
Time.at(2**61) # => 1970-01-01 01:00:00 +0100
Time.at(2**63) # RangeError: bignum too big to convert into `long'
```

``` ruby
# mri 1.9.3-p327
Time.at(2**59) # => 18267316009-03-08 07:58:08 +0100
Time.at(2**60) # => 36534630048-05-13 15:56:16 +0200
Time.at(2**61) # => 73069258126-09-25 05:52:32 +0200
Time.at(2**63) # => 292277026596-12-04 16:30:08 +0100
```

Since JRuby uses joda-time, which represents times using a signed long of milliseconds, it is impossible to represents `Time`s larger than roughly `(2**63-1)/1000` seconds.

It is not clear to me whether adding support for this in JRuby would be worthwhile, I would argue that raising a specific exception for timestamps beyond the limit would be a lot better than the above seemingly random behaviour.

**Comment by rtyler** [comment]
With JRuby 9k this issue exists, with an additional exception:

```
[15] pry(main)> Time.at(2**59)
=> 146140482-04-24 08:36:27 -0700
[16] pry(main)> Time.at(2**60)
RangeError: Adding time zone offset caused overflow
from org/jruby/RubyTime.java:1053:in `at'
[17] pry(main)> Time.at(2**61)
=> 1969-12-31 16:00:00 -0800
[18] pry(main)> Time.at(2**63)
RangeError: bignum too big to convert into `long'
from org/jruby/RubyTime.java:1027:in `at'
[19] pry(main)> 
```

**Comment by enebo** [comment]
It is a compatibility difference but one I do not see anyone hitting in real life and our hands are tied by joda time not working for unlimited precision.  So I think WONTFIX :|
