### ISSUE TITLE
Incorrect address for unsigned integers with ffi

### ISSUE THREAD

**Issue by djberg96** [jruby/jruby#1315]
It seems that when using JRuby and ffi it returns an incorrect value for the address of an unsigned integer:

```
# Should be (1 << FFI::Platform::ADDRESS_SIZE) - 1
FFI::Pointer.new(-1).address # Returns -1 instead of correct value
```

This came up when trying to define INVALID_HANDLE_VALUE on Windows which internally is defined using a cast:

```
// 0xFFFFFFFF on 32 bit systems, 0xFFFFFFFFFFFFFFFF on 64 bit systems
INVALID_HANDLE_VALUE = (DWORD)-1;
```

I realize JRuby isn't big on addresses in general, but here I think we can simulate casting a negative int here to match C's behavior.

Originally reported on the ffi project, but was told to report it here.

**Comment by tduehr** [comment]
This is solved by:

```java
address && Platform.getPlatform().addressMask()
```

The only question is where do we perform that? at initialization? on `#address`? both?
@enebo @headius comments?

**Comment by djberg96** [comment]
Still happening as of 9.0.5.0.

**Comment by tduehr** [comment]
I'm not sure this can be fixed on 64bit systems. Since Java doesn't have unsigned integer types, I think we'd have to change the API to return a BigInteger to get `0xFFFFFFFFFFFFFFFF` as a positive value.

**Comment by djberg96** [comment]
@tduehr Any update?

**Comment by djberg96** [comment]
@enebo @headius @tduehr Still happening as of 9.1.12.

**Comment by djberg96** [comment]
Looks like it's dead, just cleaning up my queue.
