### ISSUE TITLE
$stdout.tty? is false for jruby 1.7.9 sub-processes

### ISSUE THREAD

**Issue by postmodern** [jruby/jruby#1332]
I noticed that rspec would not print coloured output, nor would my other ANSI coloured logging methods. This was due to `$stdout.tty?` being false, but only in jruby sub-processes.
### Steps to Reproduce
1. jruby -e 'p $stdout.tty?'
2. echo 'system "jruby", "-e", "p $stdout.tty?"' > test.rb
3. jruby test.rb
### Expected Output

```
true
true
```
### Actual Output

```
true
false
```

**Comment by enebo** [comment]
This works in 9k and we will never fix this in 1.7.x as it is winding down....resolving.
