### ISSUE TITLE
Case-insensitive pattern match fails on Linux, but not Windows

### ISSUE THREAD

**Issue by scrobbleme** [jruby/jruby#1340]
Hi, this is similar to #335 

On Windows it is working fine (As I expect it), on Linux it fails, as match returns nil:

    file = 'Grey_s_Anatomy_Die_jungen_Aerzte_13.12.11_02-10_sixx_40_TVOON_DE.mpg.HQ.avi.otrkey.share-online'
    pattern=/(.*)_(\d\d).(\d\d).(\d\d)_(\d\d)-(\d\d)_(\w+)_(\d+)_TVOON_DE\.(.*)\.[a-zA-Z0-9]+\.(torrent|uploadhero|share-online)/i
    
    file.match(pattern) -> nil

The following pattern works on Linux too:

    /(.*)_(\d\d).(\d\d).(\d\d)_(\d\d)-(\d\d)_(\w+)_(\d+)_TVOON_DE\.(.*)\.[a-zA-Z0-9]+\.(torrent|uploadhero|share\-online)/i    

JRuby: 1.7.9
Java version "1.7.0_25"
Java(TM) SE Runtime Environment (build 1.7.0_25-b15)

**Comment by kares** [comment]
working as expected on >= 1.7.22
