### ISSUE TITLE
Discrepancy with MRI: assigning to a sequence of variables

### ISSUE THREAD

**Issue by philipmw** [jruby/jruby#1347]
Simplest test case:

```
a,b = nil
```

Output of JRuby 1.7.9: `=> [nil]`
Output of MRI 1.8.7 and 2.0.0p247: `=> nil`

Some consequences:
- Code executes differently between JRuby and MRI:

```
case
  when (a,b = function_returning_nil())
    puts "jruby"
  else
    puts "mri"
end
```

(Thanks to @luisantonioa for helping find the simplest test case for issue.)

EDIT: Moved a parser issue originally reported in this bug to #1353.

**Comment by enebo** [comment]
This works in 9k and we will never fix this in 1.7.x as it is winding down (only one last point release until EOL)....resolving as WONTFIX.
