### ISSUE TITLE
jruby interprets first line comment as possible shebang code

### ISSUE THREAD

**Issue by betarelease** [jruby/jruby#1350]
Hi, 
We came across this the other day. Our ruby file(incidentally in our rails/initializers) had a comment on how to use that initializer. But the comment started on the first line and read similar to 

```
# To use this do
# ABClassName.turnOn= true
................
..........
```

This caused one of the jruby runtimes to fail with the message 'Cannot load ABClassName' which was clearly available and loaded already.

We were able to fix this issue by doing the following
(essentially by making the first line a non-parsable string)

```
# -----------------------------
# To use this do
# ABClassName.turnOn= true
................
..........
```

Possibly Jruby expects shebang kind of statements(#! /usr/bin/ruby) for interpretation on the first line and having anything else just confuses it.

-Hope this helps and is fixed.

Thanks
Sudhindra

**Comment by enebo** [comment]
No feedback in a few years...marking invalid.  Please re-open if you have more info...
