### ISSUE TITLE
Different parser handling of masgn in if condition

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1353]
This may or may not be worth fixing, but it was brought up as part of #1347.

The following code behaves rather oddly across JRuby and MRI versions:

```
if (a,b = function_returning_nil())
  puts "hello"
end
```

MRI 1.8.7, 1.9.3, 2.0.0, and 2.1.0 all produce a SyntaxError in IRB but only a warning when running the code directly.

JRuby in 1.8 mode produces the SyntaxError in IRB _and_ when running the code directly. JRuby in 1.9 mode does not produce the error or the warning in either IRB or when running the code directly. JRuby master (2.1 mode only) behaves the same as JRuby in 1.9 mode.

This seems pretty trivial and may not be worth fixing, since JRuby actually seems more correct than MRI when JRuby runs in 1.9 and 2.1 modes.

**Comment by enebo** [comment]
This works in 9k and we will never fix this in 1.7.x as it is winding down (only one last point release until EOL)....resolving as WONTFIX.
