### ISSUE TITLE
System.setProperty("org.jruby.embed.compat.version", "RUBY1_8") does not work

### ISSUE THREAD

**Issue by pintubigfoot** [jruby/jruby#1365]
#### Verified with jruby 1.7.9, the JSR223 does not set the compat version properly.

This is what I have tried:

```java
// Setting the compat version to 1.8
System.setProperty("org.jruby.embed.compat.version", "RUBY1_8");  
ScriptEngineManager manager = new ScriptEngineManager();
ScriptEngine engine = manager.getEngineByName("jruby");
engine.eval("require \"irb\" ; IRB.start");
```

When I run it, it shows RUBY_VERSION is still 1.9
```irb
irb(main):009:0> puts RUBY_VERSION
1.9.3       # --------> compat version is still 1.9
=> nil
irb(main):010:0> puts JRUBY_VERSION
1.7.9
=> nil
```

#### org.jruby.embed.util.SystemPropertyCatcher (line 170):

```java
    public static void setConfiguration(ScriptingContainer container) {
        LocalContextProvider provider = container.getProvider();
        RubyInstanceConfig config = provider.getRubyInstanceConfig();
        String s = SafePropertyAccessor.getProperty(PropertyName.COMPILEMODE.toString());
        if (s != null) {
            if ("jit".equalsIgnoreCase(s)) {
                config.setCompileMode(CompileMode.JIT);
            } else if ("force".equalsIgnoreCase(s)) {
                config.setCompileMode(CompileMode.FORCE);
            } else {
                config.setCompileMode(CompileMode.OFF);
            }
        }
        s = SafePropertyAccessor.getProperty(PropertyName.COMPATVERSION.toString());
        if (s != null) { 
            //================================================
            //  JSR223 is bypassing all version except 1.9 
            //================================================
            if (isRuby19(s)) { 
                config.setCompatVersion(CompatVersion.RUBY1_9);
            } 
        }
    }
```

Thank you.

**Comment by inger** [comment]
I ran into this now too using 1.7.20.1. (2 years after the problem occurred first).
This makes 1.8 mode practically unusable using JSR223.

The only workaround I found is:
* use LocalContextScope.SINGLETON
* before creating the JSR223 ScriptEngine: do this:
ScriptingContainer dummySingletonJruby = new ScriptingContainer(LocalContextScope.SINGLETON);
        dummySingletonJruby.setCompatVersion(CompatVersion.RUBY1_8);
* after this, the jsr one will pick up the already configured 1.8 engine..

**Comment by kares** [comment]
this seems as a left-over from the time JRuby switched to 1.9 mode being the default (since 1.7.x) ... should be easy to fix. also please be aware that COMPAT_VERSION currently makes no sense in 9K (its 2_2 only)

**Comment by kares** [comment]
should be ready for 1.7.22 ... you can try the **jruby-1_7** branch

**Comment by inger** [comment]
Great, thank you!

**Comment by inger** [comment]
BTW-  I know this awfully off-topic - but is there any new mailing list up&running yet (codehaus replacement) Thanks

**Comment by kares** [comment]
http://jruby.org/community is updated with the new mailing list already (jruby@ruby-lang.org)
