### ISSUE TITLE
Need to error for unsupported keywords

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1368]
Here's two new tests failing for this behavior. I think it was added recently:

```
  4) Failure:
TestArray#test_sample [/Users/headius/projects/jruby/test/mri/ruby/test_array.rb:2179]:
ArgumentError expected but nothing was raised.

  5) Failure:
TestArray#test_shuffle [/Users/headius/projects/jruby/test/mri/ruby/test_array.rb:2099]:
ArgumentError expected but nothing was raised.
```

**Comment by enebo** [comment]
Dir.open missing optional second keyword argument #4495 is for the last case reported in this bug.  We just flat out don't support kwarg options for Dir.open at all...
