### ISSUE TITLE
gzip issue with jruby and Rack::ETag

### ISSUE THREAD

**Issue by jillesvangurp** [jruby/jruby#1371]
A few months ago I reported this issue against rack:

https://github.com/rack/rack/issues/571 (gzip issue with jruby and Rack::ETag)

It seems the problem may be with the way jruby is implementing gzip compression, which apparently is is doing some strange reuse of objects internally.

The bug report above includes a test case to reproduce and some analysis by @srawlins

In short the problem appears to be that rack's etag handler is concatenating parts that are rightfully assumed to be immutable but that are actually being modified in jruby's gzip implementation. Since this seems to be a jruby bug, the issue was closed a few days on the rack side.

**Comment by r6p** [comment]
We just hit this bug too, is there a fix?

**Comment by enebo** [comment]
Fixed by PR #3421.
