### ISSUE TITLE
Kernel#caller from arglist is missing a stack frame

### ISSUE THREAD

**Issue by lgierth** [jruby/jruby#1376]
The spec below (from promise.rb's suite) failed because it asserted the exact position of a stack frame within the backtrace. This broke because, when calling `Kernel#caller` from a method's arglist (i.e. `def fulfill(value = nil, backtrace = caller)`, JRuby doesn't include that method's stack frame in the backtrace. I worked around that by moving the call into the method's body: https://github.com/lgierth/promise.rb/commit/a3374fa73ca24cdb4ca843249bc43f774130d481

```
1) Promise#reject sets the backtrace
     Failure/Error: .to include(__FILE__ + ':' + (__LINE__ - 2).to_s)
       expected "/home/travis/.rvm/gems/jruby-1.7.8-d19/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:114:in `instance_eval'" to include "/home/travis/build/lgierth/promise.rb/spec/promise_spec.rb:387"
     # ./spec/promise_spec.rb:389:in `(root)'
```

**Comment by MSNexploder** [comment]
Looks like this is now working just as expected.

```ruby
require 'pp'

def foo(backtrace = caller)
  pp backtrace
end

def bar(bactrace = nil)
  backtrace ||= caller
  pp backtrace
end

def baz
  foo
  bar
end

baz
```

Output:
```
ruby -v
=> jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.91-b14 on 1.8.0_91-b14 [darwin-x86_64]

ruby test.rb
=> ["test.rb:13:in `baz'", "test.rb:17:in `<top>'"]
=> ["test.rb:14:in `baz'", "test.rb:17:in `<top>'"]
```

**Comment by lgierth** [comment]
Hey thanks for checking!

cc @dylanahsmith there might be code to be updated somewhere in promise.rb :)
