### ISSUE TITLE
in csv.rb automatically discover row separator may break unicode charactor

### ISSUE THREAD

**Issue by joey-he8x** [jruby/jruby#1386]
lib/ruby/1.9/csv.rb
line 2051: sample = @io.gets(nil, 1024)
  may break a valid unicode character and raise a `ArgumentError: invalid byte sequence in UTF-8 at line 2058`.

that will happen when execute CSV.open

A probably work around is adding "rescue ArgumentError" at line 2078, at the tail of the rescues list.

**Comment by joey-he8x** [comment]
I didn't backup the example, so I'm affraid it is not easy to provide it again or to verify its existence in master.
But the problem seems clear to me if your read the specific line in src that I pointed out in the post.

**Comment by enebo** [comment]
No data and not enough time to spelunk here.  Hopefully it is actually fixed in 9k since we have not have any reported m17n bugs in quite a while and 1.7.x is reaching EOL.
