### ISSUE TITLE
IncompatibleClassChangeError on loading new version of Sikuli

### ISSUE THREAD

**Issue by mauricioszabo** [jruby/jruby#1387]
I need to use the newest version of Sikuli on a project, but I'm getting a error on this  simple script:

``` ruby
require 'sikuli-ide'
Java::RunSKL.new.run
```

```
[debug] SikuliX: []
[error] script stopped with error in line 96
[error] java.lang.IncompatibleClassChangeError ( java.lang.IncompatibleClassChangeError: Found class com.kenai.jffi.InvocationBuffer, but interface was expected )
```

I noticed that both JRuby and Sikuli uses JFFI, but JRuby's version is outdated. I _think_ that maybe updating it would be enough, but I don't know of a simple way to do it, if possible.

**Comment by enebo** [comment]
We have update jffi multiple times since then and I see no sikuli-ide gem so I am not sure what I would need to install to test this.

**Comment by mauricioszabo** [comment]
Sikuli IDE is a jar... anyway, it's too far on the past and I solved not using JRuby at all. Thanks anyway.
