### ISSUE TITLE
JRuby Profiler example code doesn't print header or footer

### ISSUE THREAD

**Issue by justfalter** [jruby/jruby#1394]
The example code provided on the [wiki page for profiling](https://github.com/jruby/jruby/wiki/Profiling-jruby) will not print the header or footer for the chosen printer. 

The code in question:

```
profile_printer = JRuby::Profiler::GraphProfilePrinter.new(profile_data)
profile_printer.printProfile(STDOUT)
```

This is especially important with ProfilePrinter implementations like HtmlProfilePrinter, which need to insert a proper header and footer in order for the resultant document to render properly. 

I would recommend that the example code provided on the wiki page provide a more complete example, such as:

```
profile_printer = JRuby::Profiler::HtmlProfilePrinter.new(profile_data)
ps = java.io.PrintStream.new(STDOUT.to_outputstream)
printer.printHeader(ps)
printer.printProfile(ps)
printer.printFooter(ps)
```

It's easy to compare the two by running the following code, and then diffing profile_missing.html with profile.html:

```
printer = JRuby::Profiler::HtmlProfilePrinter.new(result)
File.open("profile_missing.html", "w") do |fio|
  printer.printProfile(fio)
end

File.open("profile.html", "w") do |fio|
  ps = java.io.PrintStream.new(fio.to_outputstream)
  printer.printHeader(ps)
  printer.printProfile(ps)
  printer.printFooter(ps)
end
```

**Comment by enebo** [comment]
Updated wiki.. closing.
