### ISSUE TITLE
Backticks don't give exception for nonexistant command

### ISSUE THREAD

**Issue by shawnjgoff** [jruby/jruby#1396]
MRI raises an ENOENT exception when using backtics with a nonexistant command. Jruby 1.7.8 on JRE 1.7.0_45 returns an empty string.

**Comment by jsvd** [comment]
On a further note, jruby-1.7.19 still has this behavior, and while in MacOSX/Linux + JDK7/8 a non existant command returns "", the same jruby version on Windows will properly raise an exception:

```
irb(main):002:0> `command_that_doesnt_exist`
Errno::ENOENT: No such file or directory - command_that_doesnt_exist
        from file:/C:/logstash-1.5.0-rc3/vendor/jruby/lib/jruby.jar!/jruby/kerne
l/jruby/process_manager.rb:24:in ``'
        from file:/C:/logstash-1.5.0-rc3/vendor/jruby/lib/jruby.jar!/jruby/kerne
l/jruby/process_manager.rb:49:in ``'
        from (irb):2:in `evaluate'
```

The behaviour in both environments should be consistent (and ideally also between JRuby and MRI).

**Comment by headius** [comment]
Works correctly in JRuby 9k but still broken on jruby-1_7 branch as of today.

**Comment by headius** [comment]
So this is a bit gnarly. The logic for ` lives in process_manager.rb and is implemented in Ruby using Java integration. It calls into LaunchConfig to check if we should use sh for the backtick, which returns true *unconditionally* when not running on Windows. That causes it to use sh, which doesn't find the command, but stderr appears not to be hooked up.

Note that MRI is a bit inconsistent here too...if you have a bad command with any shell characters nearby, it will switch to running with sh and NOT raise any error:

```
[] ~/projects/ruby $ rvm ruby-1.9 do ruby -e '`boop $FOO`; puts "ok!"'
sh: boop: command not found
ok!
```

**Comment by headius** [comment]
This should be fixed now. I duplicated logic from popen that does similar bin checking.
