### ISSUE TITLE
ConcurrentMutationException when synchronizing on a mutex

### ISSUE THREAD

**Issue by benlangfeld** [jruby/jruby#1397]
Examples:
- https://travis-ci.org/adhearsion/punchblock/jobs/16754234
- https://gist.github.com/benlangfeld/391a7fadef08053cb1fa

I have no further details at this time, but just wanted to get this filed quickly incase it triggered an idea.

**Comment by enebo** [comment]
Nothing more concrete to act upon and quite a bit of time passed.
