### ISSUE TITLE
SecureRandom performance could be better

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1405]
Our SecureRandom in 1.7.10 (from securerandom.rb) was implemented using Java integration calling out to java.security.SecureRandom. It constructed a new instance each time.

In 09b169a6cd047c6d4d49104a37cf30a723c2bb36, I moved the meat of the logic (#random_bytes) into Java code, which roughly doubled performance on my machine, bringing it close to MRI.

@bbrowning and @nirvdrum discovered a JVM property that, when passed, sets SecureRandom to use /dev/urandom or /dev/random, which improves performance further: java.security.egd=/dev/random. On my system, this again doubles performance, but the format appears to vary across JVMs.

Finally, I made a modification that constructs a SecureRandom per thread, avoiding synchronization contention, and started to move other methods into Java starting with #hex. This brought about the best performance so far, but I have not committed this change because I'm unsure about saving the SecureRandom per thread and whether that does something "bad" as far as the security of its results.

We need to evaluate all these options and come up with a good balance of security and performance, since it seems that SecureRandom is hit very heavily by frameworks like Rails.

Performance with per-thread SecureRandom and the Java property across JVMs on OS X: https://gist.github.com/headius/8428930

Patch to use a SecureRandom per thread and make #hex native: https://gist.github.com/headius/8429206

**Comment by headius** [comment]
Ok, waking this one up again...

There are still outstanding reports of blocking or slow behavior using SecureRandom, like nats-io/ruby-nats#123 and [this comment](https://github.com/jruby/jruby/issues/3351#issuecomment-190393752) by @cheald.

It seems we're still not using whatever is equivalent to MRI, since as far as I know MRI does not get reports of entropy-starved blocking behaviors.

So...anyone still seeing this problem that can help us explore solutions? @cheald @trinode @digitalextremist @tarcieri @wallyqs

**Comment by cheald** [comment]
I haven't seen it lately since I've added entropy daemons to my standard saltstack on new machines, but it might be possible to replicate it on a fresh VM. I'll run some experiments on AWS VMs.

**Comment by cheald** [comment]
I'm unable to replicate the issue in a fresh VM here. Amazon Linux, no entropy daemon. I'm keeping the entropy pool drained:

````
# cat /dev/random > /dev/null &
# cat /proc/sys/kernel/random/entropy_avail
4
````

Then installed JRuby and benchmarked SecureRandom:
```
jruby-9.1.2.0 :009 > File.read("/proc/sys/kernel/random/entropy_avail").strip
 => "0"
jruby-9.1.2.0 :010 > Benchmark.bm {|x| x.report("uuid") { 1_000_000.times { SecureRandom.uuid } } }
       user     system      total        real
uuid  0.480000   0.020000   0.500000 (  0.507049)
```

Despite the system being entropy-starved, it had no problem creating UUIDs. My previous issue may have been something other than SecureRandom. I don't recall the circumstances other than trying to re-establish my dev environment after a fresh OS install.

**Comment by headius** [comment]
@cheald Ok, thanks for following up. Hopefully if there's still an issue, someone else can reproduce it for us. Of course, I hope there's no longer still an issue :-)

**Comment by tarcieri** [comment]
For what it's worth, here's what I netted out on for JRuby support in the `sysrandom` gem:

https://github.com/cryptosphere/sysrandom/blob/master/lib/sysrandom.rb#L17

**Comment by wallyqs** [comment]
Running an entropy daemon (`haveged`) as @cheald suggests does seem to reduce the time a lot locally and mitigate the issue. Issue seems to be more pronounced though in a Travis build environment without it for example at least for me, where calling something like `SecureRandom.hex(13)` the first time can take several minutes (subsequents being ok...): https://travis-ci.org/wallyqs/ruby-nats/builds/148795654

**Comment by headius** [comment]
We had another report of problems today.

I have pushed to master a config property jruby.preferred.prng that can be used to select from the available PRNG in the JDK. On my system (OS X, OracleJDK 8u92) and on the reporter's Linux, the available PRNG are NativePRNG, SHA1PRNG, NativePRNGBlocking, NativePRNGNonBlocking. By default, we try to use SHA1PRNG since we *believed* it consumes the least entropy.

To get that list on your system, run this:

```ruby
Java::sun.security.jca.Providers.getProviderList.providers.each do |p|
  p.services.each do |s|
    puts s.algorithm if s.type == "SecureRandom"
  end
end
```

**Comment by headius** [comment]
Note that NativePRNGNonBlocking is new in Java 8. That's what's being used for @tarcieri's workaround [above](https://github.com/jruby/jruby/issues/1405#issuecomment-236487691).

@tarcieri That is working well for you?

**Comment by headius** [comment]
I didn't really show how to use the property... it's `-Djruby.preferred.prng=<NAME>` passed to Java or `-Xpreferred.prng=<NAME>` passed to the `jruby` command.

I've kicked off a build for 9.1.3.0-SNAPSHOT on http://ci.jruby.org. Should be ready soon.

**Comment by tarcieri** [comment]
Haven't had complaints yet, but I'm curious how it would work in some of the scenarios where people are having problems.

**Comment by headius** [comment]
Given the reports we're getting about SecureRandom blocking for sometimes many seconds, I've done another commit to try the following providers in turn:

1. jruby.preferred.prng, which now defaults to NativePRNGNonBlocking
2. SHA1PRNG
3. Whatever JDK would have picked by default

I've kicked off another build for http://ci.jruby.org.

**Comment by headius** [comment]
Another discussion of SecureRandom: https://tersesystems.com/2015/12/17/the-right-way-to-use-securerandom/

**Comment by y8** [comment]
@tarcieri we are running absolutely everything in Docker. Few months ago we've spotted that our CI builds are starting to increase on busy hours. Initially we thought that it's caused by memory constraints on build agents, but couple days ago we suddenly hit an issue when our Rails apps are failed to boot in production in 5 minutes initialization window defined by healthcheck. We were unable to reproduce this problem on developer machines, so it was clear that something wrong with a deployment environment.

After investigation I found out that boot process stuck on this [call](https://github.com/rails/sprockets/blob/9db6aa1c8bec0c445c58d2783d7166f7c44a58f0/lib/sprockets/manifest_utils.rb#L24):  

```ruby
  def generate_manifest_path
      ".sprockets-manifest-#{SecureRandom.hex(16)}.json"
  end
```

We checked metrics from Prometheus node_exporter and found out that our entropy pool is completely dry ;)

![vnk](https://cloud.githubusercontent.com/assets/80930/17490298/7a5eda5a-5da2-11e6-834b-43c685ae5e26.png)

We've deployed `haveged` on all hosts (you can clearly see that moment on the graph) and suddenly our pull-request build time went from 10-15 min to just 2-5 min and full build-time from 30 min to 10 min:

![vod](https://cloud.githubusercontent.com/assets/80930/17490499/60ceb514-5da3-11e6-9646-b77eb21158a6.png)
 
I have no idea who is responsible for the pool exhaustion, I suspect that might have something to do with Ranchers' IPSec networking, because it's the only common thing on all hosts, and you can see that we have pretty much the same exhaustion pattern on all hosts, even they don't run anything jruby-ish.

So no wonder that @headius heard stories about 30 minutes rails boot times :)

**Comment by headius** [comment]
@y8 If you are able to test my change in production, hopefully the nonblocking PRNG will be the solution to all our problems :-) We are starting to stabilize for 9.1.3.0, so let us know when you're able to confirm.

**Comment by headius** [comment]
Well I'm going to optimistically call this good. On Java 8, we will attempt to use the NativePRNGNonBlocking. If that's not available, or on other platforms, we will try to use the SHA1PRNG. After that we just let the JDK decide.

If someone's still able to see entropy starvation with JRuby 9.1.3.0 (master right now), please let us know ASAP.
