### ISSUE TITLE
jopenssl/load - Unable to deploy on jBoss 7.1.1.Final using jRuby 1.7.10

### ISSUE THREAD

**Issue by lightswitch05** [jruby/jruby#1413]
Error:

    org.jruby.rack.RackInitializationException: load error: jopenssl/load -- java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERBoolean
	from org/jruby/RubyKernel.java:1083:in `require'
	from classpath:/META-INF/jruby.home/lib/ruby/shared/openssl.rb:1:in `(root)'
    ...

[**See entire log file**](https://gist.github.com/lightswitch05/8479394#file-server-log)

- Versions
  - **jruby 1.7.10** (1.9.3p392) 2014-01-09 c4ecd6b on Java HotSpot(TM) 64-Bit Server VM 1.7.0_45-b18 [linux-amd64]
  - Java
    - java version "1.7.0_45"
    - Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
    - Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
  - JBoss AS 7.1.1.Final
  - Warbler version 1.4.0
  - Rails 4.1.0.beta1
  - Bundler version 1.5.2

- Steps to reproduce
  1. rails new testapp -T
  2. cd testapp
  3. warble
  4. copy testapp.war to the deployment dir of JBOSS and wait for it to
deploy
  5. visit <whateverurl>/testapp

**Comment by kares** [comment]
is this still an issue with JRuby >= **1.7.16** (+ jruby-openssl 0.9.6) or can we close this one ?
