### ISSUE TITLE
LoadError: no such file to load -- /config/boot

### ISSUE THREAD

**Issue by swapsjd** [jruby/jruby#1420]
Hi,
I am trying to setup 'Rearview' to connect to hosted graphite, which requires jruby.
Am using JRuby 1.7.5. With the execution of setup script of 'Rearview' I get this error:

LoadError: no such file to load -- /config/boot
           require at org/jruby/RubyKernel.java:1082
           require at /usr/local/rvm/rubies/jruby-1.7.5/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
  require_relative at file:/usr/local/rvm/rubies/jruby-1.7.5/lib/jruby.jar!/jruby/kernel19/kernel.rb:21
            (root) at bin/rails:11

Could you help me solve this issue ?

**Comment by enebo** [comment]
No info to go on...Re-open if you have more information.
