### ISSUE TITLE
GzipReader#mtime gives the wrong time

### ISSUE THREAD

**Issue by DavidEGrayson** [jruby/jruby#1422]
`GzipReader#mtime` always just returns the timestamp of the time that the object was created instead of an actual modification time read from the GZip header.

Here is some example code that reproduces this issue:

``` ruby
require 'zlib'
require 'stringio'
io = StringIO.new "\x1f\x8b\x08\x00\x44\x33\x22\x11\x00\xff\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00"
r = Zlib::GzipReader.new(io)
puts "%x" % r.mtime
```

When I run this program with MRI 2.0.0, it correctly prints "11223344".  When I run it with JRuby I get the current timestamp.

Here is shell output showing what version of JRuby I am running and the incorrect output:

```
$ jruby -v && jruby test.rb
jruby 1.7.10 (1.9.3p392) 2014-01-09 c4ecd6b on Java HotSpot(TM) 64-Bit Server VM 1.7.0_45-b18 [Windows 8-amd64]
52dc9f31
```

When I looked, I couldn't see any code in the GzipReader class that actually grabs the modification time from jzlib and stores it.

I would have simply fixed this and submitted a pull request, but jzlib _also_ has a bug in it preventing it from reporting the modification time correctly.  We need to wait for https://github.com/ymnk/jzlib/pull/13 to be handled before I can fix JRuby.

**Comment by DavidEGrayson** [comment]
I tested this again today with MRI 2.2.0-p0 and JRuby 9.0.0.0-pre1, and nothing has changed so the bug is still there.

**Comment by DavidEGrayson** [comment]
I tested it again and this bug is still present in JRuby 9.0.0.0.

**Comment by enebo** [comment]
@DavidEGrayson it appears the jzlib issues has been resolved.  Care you make a PR for this?

**Comment by DavidEGrayson** [comment]
OK, I tried making a PR but I got stuck when I tried to upgrade jzlib to the latest version.  They fixed their issue in commit https://github.com/ymnk/jzlib/commit/1a5fb101cebe1b762cfe0ac74cd85ed3045919ea on Januray 2014 but they have not released a new version since 1.1.3 in October 2013.  So I am not sure if `pom.rb` can fetch jzlib from GitHub or if there is a better way to upgrade it.

I notice that you seem to have a pure Ruby implementation of the Zlib stuff in `lib/ruby/stdlib/ffi/platform/zlib.rb.ffi`.  Maybe you could switch to that instead of jzlib, or start maintaining your own fork of jzlib?

**Comment by DavidEGrayson** [comment]
For what it's worth, you can see the work I did in this branch to add a test and fix the JRuby java code:

https://github.com/DavidEGrayson/jruby/tree/pr_zlib_mtime

**Comment by DavidEGrayson** [comment]
Cool.  Feel free to cherry-pick my commit from 6 years ago working on this stuff and adding a test for it:

https://github.com/DavidEGrayson/jruby/commit/f6b6f2c5015fba72cace84e3e8b7a017537a7c31

**Comment by headius** [comment]
@DavidEGrayson Great! I will pick that commit to get the test.
