### ISSUE TITLE
Problem accessing methods of package protected classes. 

### ISSUE THREAD

**Issue by AlBundy33** [jruby/jruby#1444]
See here: http://jira.codehaus.org/plugins/servlet/mobile#issue/JRUBY-6087

**Comment by kares** [comment]
working fine on JRuby 9K (not sure about JRuby 1.7.x - which at this point isn't supported anyway)
```
JRuby6087Test.testOverloadedMethod()
hello Al
hello this works
hello this works not
JRuby6087Test.testNewMethod()
hello Al
bye bye
bye bye
```
