### ISSUE TITLE
AddCallProtocol unconditionally forces frame

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1456]
I see that push/pop of binding are omitted when local variables are not needed across calls, but push/pop of frame appear to be emitted all the time:

For code "def foo(a); p a; end" we get the following instrs:

```
  0	push_frame
  1	check_arity(1, 0, -1)
  2	%t_a_1 = recv_pre_reqd_arg(0)
  3	thread_poll
  4	line_num(0)
  5	%v_0 = call_1o(FUNCTIONAL, 'p', %self, [%t_a_1]){1O}
  6	pop_frame
  7	return(%v_0)
  8	[DEAD]%v_3 = recv_jruby_exc
  9	[DEAD]pop_frame
  10	[DEAD]throw(%v_3)
```

I guess this reflects a lack of awareness about frame fields in IR right now.

/cc @subbuss @enebo

**Comment by enebo** [comment]
Fixed a long time ago.
