### ISSUE TITLE
Memory Leak in Jruby 1.7.10?

### ISSUE THREAD

**Issue by malletto** [jruby/jruby#1465]
So I have a bare bones rails app (just rails new testapp), here is my gemfile:

source 'https://rubygems.org'
gem 'rails', '3.2.16'
gem 'activerecord-jdbcmysql-adapter', '1.3.3'
gem 'jruby-rack', '1.1.13.3'
gem 'jruby-jars', '1.7.10'
gem 'jruby-openssl', '0.9.4', :require => false
gem 'warbler', '1.4.0'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyrhino'
  gem 'uglifier', '>= 1.0.3'
end

Java 1.7.0_25

Creating an executable war file with:

RAILS_ENV=production bundle exec warble executable war

Fire it off with

java -jar testapp.war

With jruby 1.7.3 the server starts without any problems.  With jruby 1.7.10 i get a 

Exception in thread "JRuby-Rack-App-Init-2" java.lang.OutOfMemoryError: Java heap space

So i increased my java memory:
export JAVA_OPTS="${JAVA_OPTS} -XX:MaxPermSize=1024m -XX:PermSize=512m -Xmx4096m -Xms512m"

Start the server again, takes 5 minutes before it fires another out of memory error.  Now this is a simple test app, nothing added except gems, log4j and warbler.  I would think something this simple should not be throwing memory errors?

**Comment by kares** [comment]
no response for a long time
