### ISSUE TITLE
`.jrubyrc` not picked up from current directory

### ISSUE THREAD

**Issue by jrhorn424** [jruby/jruby#1482]
In order to get 1.7.9 to pickup ruby 1.9.3, I put the following in my project directory:

```
# .jrubyrc
compat.version=1.9
```

Invoking `jruby -v` reported ruby 2.0, whereas copying the same file to the `$HOME` directory resutls in `jruby -v` reporting 1.9.

**Comment by kares** [comment]
closing this JRuby 1.7.x report as there's been no response in a long time
