### ISSUE TITLE
Fixnum does not allow overloading the case keyword implementation using ===

### ISSUE THREAD

**Issue by stephenlam** [jruby/jruby#1486]
I'm trying to redefine #===.

``` ruby
class Fixnum
  def === other
    true
  end
end
```

Here is the test case:

``` ruby
case 4
  when 3
     puts "YES"
  else
     puts "NO"
end
```

On MRI 2.0.0-p0 this works and prints "YES". I tested on Jruby 1.7.3 and 1.7.10 and they both printed "NO". I need this feature to be able to support a simpler syntax in my code (of course, the example above is overly simplified and does not reflect my end use case).

Note that calling 3 === 4 DOES return true for both Ruby and JRuby. However, the "case" statement does not use the redefined #=== method for Fixnum's. So far I have only seen this issue with Fixnum's; I know that String works without issues. You may wish to test this on other classes as well (e.g. Numeric's and Integer's).

EDIT: corrected typo. (MRI prints "YES" and Jruby prints "NO" instead of the other way around.)

**Comment by enebo** [comment]
We generally like to be compatible but this is one of those corners we do not want to put any effort into it unless there is a good use case.  The performance benefits of not supporting this right now outweighs the impl cost of supporting an uncommon feature...
