### ISSUE TITLE
Reduce locking in x509 store

### ISSUE THREAD

**Issue by nirvdrum** [jruby/jruby#1493]
When using Excon to make HTTPS calls I noticed a lot of blocking in initializing the SSL certificates.  In particular, each new connection calls `OpenSSL::X509::Store.new`.  The locking seems to predominately occur in `org.jruby.ext.openssl.x509store.Store.addCertificate`.  Since the same, default certificates are being used, perhaps a cheap way out is to cache that store.

A reproduction case is:

```
require 'excon'

# Call once so the hostname gets cached once, otherwise you might deadlock.
Excon.get('https://google.com/')

threads = []

100.times do
  threads << Thread.new do
    Excon.get('https://google.com/')
  end
end

threads.each(&:join)
```

If you look at the stack dump for that, you'll see a lot of blocked threads.

**Comment by kares** [comment]
no longer an issue with jruby-openssl >= 0.9.10 (locking has been avoided in Store#addCertificate)
