### ISSUE TITLE
Socket::Constants incorrect on Windows

### ISSUE THREAD

**Issue by stakach** [jruby/jruby#1509]
```
irb(main):001:0> require 'socket'
=> true
irb(main):002:0> Socket::Constants::AF_INET
=> 4
irb(main):003:0> Socket::Constants::AF_INET6
=> 33
irb(main):004:0> RUBY_DESCRIPTION
=> "jruby 1.7.10 (1.9.3p392) 2014-01-09 c4ecd6b on Java HotSpot(TM) Client VM 1.7.0_07-b10 [Windows 7-x86]"
irb(main):005:0>
```

According to [MSDN](http://msdn.microsoft.com/en-us/library/windows/desktop/ms737530%28v=vs.85%29.aspx) values should be
- Socket::Constants::AF_INET == 2
- Socket::Constants::AF_INET6 == 23

**Comment by ahorek** [comment]
ping @enebo 

https://github.com/jnr/jnr-constants/pull/31

**Comment by enebo** [comment]
@ahorek I merged that I and I guess we will need to run a script to populate for next jnr-constant release but I see we hard-coded numbers in that commit above.  Maybe we can get more updated for AF_INET and AF_INET6 are generated?  Or is that not in jnr-constant?

**Comment by ahorek** [comment]
@enebo thanks
it would be great if you could review jnr-constants pull requests
especially these two should be ready
https://github.com/jnr/jnr-constants/pull/30
https://github.com/jnr/jnr-constants/pull/28

after that we have to run the generation script for all platforms and commit generated files separately. Sounds good?

**Comment by ahorek** [comment]
https://github.com/cotag/libuv/commit/22e0ed6419ddf26e7fa261fc2a28c4057a8cb05a no, this one isn't in jnr-constant repository. It was a workaround for https://github.com/cotag/libuv

jnr/jnr-constants#31 will fix it properly

**Comment by headius** [comment]
I've merged all mentioned PRs for jnr-constants. There's no changes when regenerating for MacOS.

**Comment by ahorek** [comment]
@headius it's ready to review. I fixed tests and added constants for freebsd, windows, linux and solaris, but I don't have any macos, aix and openbsd running.

**Comment by headius** [comment]
Hmm... I ran those commands too and didn't get anything new. I'll try again.

**Comment by headius** [comment]
Looks like some failures in Errno we'll have to look into.
