### ISSUE TITLE
Regex matching when using .*\b triggers ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by brianstien** [jruby/jruby#1537]
To reproduce run ``` ruby -e '/foo.*\b/ =~ "foo"' ```

I was able to reproduce this error in JRuby 1.7.8, 1.7.10, and 1.7.11.  It only occurs when the regex contains includes the pattern ``` .*\b ```

**Comment by kares** [comment]
verified it works on 1.7.24 as well as 9.0.5.0
