### ISSUE TITLE
Logger slower than MRI

### ISSUE THREAD

**Issue by nirvdrum** [jruby/jruby#1567]
I was trying to measure logging overhead for Cassandra client gem recently and decided to compare the closest thing I could get to a no-op logger in JRuby and MRI.

Code:

```
require 'benchmark/ips'
require 'logger'

logger = ::Logger.new('/dev/null')

Benchmark.ips do |x|
  x.report('debug') { logger.debug {} }
end
```

JRuby 1.7.11:

```
Ruby 1.7.11

Calculating -------------------------------------
              debug      2312 i/100ms
-------------------------------------------------
              debug      30308.9 (±3.9%) i/s -     152592 in   5.043000s
```

MRI 2.1.1:

```
MRI 2.1.1

Calculating -------------------------------------
              debug     6342 i/100ms
-------------------------------------------------
              debug     67615.3 (±2.8%) i/s -     342468 in   5.069185s
```

While not the most scientific way to compare, MRI is roughly twice as fast as JRuby.  I haven't profiled anything yet.  I just wanted to file this for now so it doesn't get lost.

**Comment by enebo** [comment]
One both MacOS and Fedora25 I see MRI about 15% faster than us but definitely not 2x slower.  I am using Java 8 though.  I know we tried to figure this out but your env seems like an anomoly in this report (although I would have loved it if we had been able to figure this out).
