### ISSUE TITLE
jrubyc and __FILE__

### ISSUE THREAD

**Issue by areman** [jruby/jruby#1576]
I'm playing with jrubyc. I like to test if the pre compilation of the ruby source can speed up the loading of my jruby application.
I'm running jruby 1.7.11 with java 1.7.0_10 on Windows XP

I created a simple file
**c:\tmp\lib\andre.rb**
```ruby
filename = File.join( File.dirname(__FILE__), File.basename(__FILE__) )
puts filename
```
Running 
**jruby andre.rb**
prints
**./andre.rb**
But when I compile the rb file
**jruby -S jrubyc --target c:\tmp\out --verbose andre.rb**
and running
**java -cp c:\ruby\jruby-1.7.11\lib\jruby.jar;c:\tmp\out andre**
prints
**file:/C:/tmp/out/andre.class**

* The file path of the compiled version is absolute
* The compiled version contains the protocol

I think it's a bug, the behavior should be the same.

Thanks,
André

**Comment by mkristian** [comment]
I see
```
$ ../bin/jruby andre.class 
./andre.class
```
with the current master. closing - please feel free to reopen if you think there is still bug.
