### ISSUE TITLE
jit.codeCache doesn't work

### ISSUE THREAD

**Issue by areman** [jruby/jruby#1585]
Hello,

I'm using **jruby 1.7.11 (1.9.3p392) 2014-02-24 86339bb on Java HotSpot(TM) Client VM 1.7.0_10-b18 [Windows XP-x86]**

I run 
**jruby -Xcompile.mode=FORCE -Xjit.debug=true -Xjit.codeCache=c:\tmp test.rb**
and many 

```
... Ruby: no jitted code in classloader for ...
... JITCompiler: writing jitted code to to ...
```

will be printed. And in the rerun the same, but the cached files exists in the directory.
I looked into the source and I found that the **JRubyClassLoader** is used to load the cached classes. But I can't find the location in the code where the **codeCache** directory is added to the **JRubyClassLoader**.
After I patched the getJRubyClassLoader method in the Ruby class, and add the code cache directory to the Classloader, everything works fine for me.

``` ruby
public synchronized JRubyClassLoader getJRubyClassLoader() {
    // FIXME: Get rid of laziness and handle restricted access elsewhere
    if (!Ruby.isSecurityRestricted() && jrubyClassLoader == null) {
        jrubyClassLoader = new JRubyClassLoader(config.getLoader());

        // if jit code cache is used, we need to add the cache directory to the classpath
        // so the previously generated class files can be reused.
        if( config.JIT_CODE_CACHE != null && !config.JIT_CODE_CACHE.trim().isEmpty() ) {
            File file = new File( config.JIT_CODE_CACHE );

            if( file.exists() == false || file.isDirectory() == false ) {
                getWarnings().warning("The jit.codeCache '" + config.JIT_CODE_CACHE + "' directory doesn't exit.");
            } else {
                try {
                    URL url = file.toURI().toURL();
                    jrubyClassLoader.addURL( url );
                } catch (MalformedURLException e) {
                    getWarnings().warning("Unable to add the jit.codeCache '" + config.JIT_CODE_CACHE + "' directory to the classpath." + e.getMessage());
                }
            }
        }
    }

    return jrubyClassLoader;
}   
```

Maybe this is an possible patch for the Ruby class.

Thanks,
André

**Comment by MSNexploder** [comment]
I guess this one can be closed.
"jit.codeCache" is deprecated in 9k and (as far as I can see) does nothing nowadays.

**Comment by kares** [comment]
@headius @enebo for 9.2 we shall move options that do nothing from being printed on `--properties` ?

**Comment by headius** [comment]
We did actually deprecate and move jit.codeCache out of --properties at some point, so I think this is resolved.

I'm auditing the other properties now and will push a PR for review.

**Comment by headius** [comment]
Seems it was deprecated at least by July 25, 2015, which puts it roughly around 9.0.1.0 timeframe.

449377cf55576e08cc679843e6cc7782454f532d
