### ISSUE TITLE
"gem install bundler" fails using 2.0 or 2.1 mode

### ISSUE THREAD

**Issue by donv** [jruby/jruby#1595]
Hi!

`gem install bundler` fails:

```
$ rvm use jruby
Using /Users/uwe/.rvm/gems/jruby-1.7.11
$ ruby --version
jruby 1.7.11 (1.9.3p392) 2014-02-24 86339bb on Java HotSpot(TM) 64-Bit Server VM 1.7.0_51-b13 [darwin-x86_64]
$ gem install bundler
Successfully installed bundler-1.6.0
1 gem installed
$ ruby --1.9 -S gem install bundler
Successfully installed bundler-1.6.0
1 gem installed
$ ruby --2.0 -S gem install bundler
ERROR:  While executing gem ... (ArgumentError)
    marshal data too short
$ rvm use jruby-head
Using /Users/uwe/.rvm/gems/jruby-head
$ ruby --version
jruby 9000.dev (2.1.2) 2014-03-29 6035ded on Java HotSpot(TM) 64-Bit Server VM 1.7.0_51-b13 [darwin-x86_64]
$ gem install bundler
ERROR:  While executing gem ... (ArgumentError)
    marshal data too short
```

Other rubies work OK, including JRuby in 1.9.3 mode:

```
$ rvm use 2.1.1
Using /Users/uwe/.rvm/gems/ruby-2.1.1
$ ruby --version
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
$ gem install bundler
Fetching: bundler-1.6.0.gem (100%)
Successfully installed bundler-1.6.0
1 gem installed
$ rvm use 2.0.0
Using /Users/uwe/.rvm/gems/ruby-2.0.0-p451
$ ruby --version
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-darwin12.5.0]
$ gem install bundler
Fetching: bundler-1.6.0.gem (100%)
Successfully installed bundler-1.6.0
1 gem installed
$ rvm use 1.9.3
Using /Users/uwe/.rvm/gems/ruby-1.9.3-p545
$ ruby --version
ruby 1.9.3p545 (2014-02-24 revision 45159) [x86_64-darwin13.1.0]
$ gem install bundler
Fetching: bundler-1.6.0.gem (100%)
Successfully installed bundler-1.6.0
1 gem installed
```

**Comment by ncuesta** [comment]
I know it's been a long time since this issue was closed, but I'm getting the same `marshall data too short` on a fresh install of `jruby-1.7.18`. I'm not getting such error when running the same `gem install` command with jruby in `1.9` mode.

```bash
$ ruby --1.9 -v
jruby 1.7.18 (1.9.3p551) 2014-12-22 625381c on Java HotSpot(TM) 64-Bit Server VM 1.7.0_55-b13 [darwin-x86_64]
$ ruby --1.9 -S gem install bundler
Successfully installed bundler-1.7.12
1 gem installed

$ ruby --2.0 -v
jruby 1.7.18 (2.0.0p598) 2014-12-22 625381c on Java HotSpot(TM) 64-Bit Server VM 1.7.0_55-b13 [darwin-x86_64]
$ ruby --2.0 -S gem install bundler
ERROR:  While executing gem ... (ArgumentError)
    marshal data too short
```

BTW I'm using rbenv 0.4.0, if that affects anything.

Thanks in advance

**Comment by just3ws** [comment]
Hi, I'm getting this as well. 

- RVM 1.26.9
- RubyGems 2.4.5
- OS X 10.10.1 (14B25)
- jruby 1.7.18 (2.0.0p598) 2014-12-22 625381c on Java HotSpot(TM) 64-Bit Server VM 1.7.0_51-b13 +jit [darwin-x86_64]
- ~/.jrubyrc                                                                                                                                                                                

        cext.enabled=true
        compat.version=2.0

- java -version                                                                                                                                                                                 
        java version "1.7.0_51"
       Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
        Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

When I `gem update`...

        $ gem update --verbose                                                                                                                                                                          
        Updating installed gems
        GET https://api.rubygems.org/specs.4.8.gz
        302 Moved Temporarily
        GET https://s3.amazonaws.com/production.s3.rubygems.org/specs.4.8.gz
        304 Not Modified
        Updating bundler
        HEAD https://api.rubygems.org/api/v1/dependencies
        200 OK
        GET https://api.rubygems.org/api/v1/dependencies?gems=bundler
        200 OK
        ERROR:  While executing gem ... (ArgumentError)
            marshal data too short

**Comment by n0nick** [comment]
I have the same issue.

```
$ jruby -v
jruby 1.7.19 2015-01-29 20786bd on OpenJDK 64-Bit Server VM 1.7.0-google-v6-83024847-77620724 [linux-amd64]
```

Doing `$ jruby --1.9 -S gem install bundler` mitigated this for now. I was able to continue with `bundle install` and install other gems.

**Comment by kikorb** [comment]
I have the same issue here using jruby-1.7.9 and ruby-version 2.0
I know the support for 2.0 is experimental but it will be nice to have the patch everywhere so we don't have to do --1.9 -S everytime we find this issue

**Comment by g3d** [comment]
```
> ruby -v                                                                                                
jruby 1.7.20 (2.0.0p598) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13 +jit [darwin-x86_64]

> сat .jrubyrc
compat.version=2.0

> gem install bundler
ERROR:  While executing gem ... (ArgumentError)
    marshal data too short
```

**Comment by splattael** [comment]
I've ran into a similar issue.

Applying the patch 89ef3e9f691c2c5d6a56ab775225526b3b309206 to `.rvm/rubies/jruby-1.7.20/lib/ruby/2.0/net/http/response.rb` fixed it for me.

It's strange that 89ef3e9f691c2c5d6a56ab775225526b3b309206 did not make it into `1.7.20` although it's from April 2014 (`1.7.12`).

**Comment by mjc** [comment]
This definitely still exists and 89ef3e9 didn't get applied.

**Comment by voondo** [comment]
Same issue here.

**Comment by astjohn** [comment]
This issue was a huge pain to track down for us when all of a sudden our http response bodies became blank. We switched to 2.0 mode due to a dependency from another gem... Still present in 1.7.20 and (1.7.20.1). I guess we just hope 9000 will be fine?

**Comment by splattael** [comment]
This error still exists in jruby 1.7.21.
After applying the patch from 89ef3e9 it works again.

@enebo @headius I think this issue should be re-opened as 89ef3e9 somehow did not make it into `lib/ruby/2.0/net/http/response.rb` of 1.7.21.

**Comment by mkristian** [comment]
@splattael reapplied the patch
