### ISSUE TITLE
$! not always being saved/restored in JRuby runtime when Ruby exceptions are handled

### ISSUE THREAD

**Issue by subbuss** [jruby/jruby#1601]
Several classes in the JRuby runtime are catching Ruby exceptions. Those should save the old value of $! and restore them after the exception is handled. A quick grep revealed at the following files that need investigation and possible fixup. I've fixed up RubyFileTest.java in commit d10eadecef0b8a1e5c51d570982ade4d0529ec6d

[subbu@earth ir] grep -l 'catch (RaiseExcep' ../*
../Main.java
../RubyBasicObject.java
../RubyComparable.java
../RubyConverter.java
../RubyEnumerable.java
../RubyEnumerator.java
../RubyFile.java
../RubyFileTest.java
../RubyIO.java
../Ruby.java
../RubyKernel.java
../RubyNumeric.java
../RubyRange.java
../RubyRegexp.java

**Comment by subbuss** [comment]
Reopening so we can audit code and confirm everything is good.

**Comment by kares** [comment]
has been open for 2+y ... just did a quick audit and all seems well. maybe the time has come to close? :wink:

**Comment by headius** [comment]
@kares 👍
