### ISSUE TITLE
Symbol eql? returning false incorrectly

### ISSUE THREAD

**Issue by chriseppstein** [jruby/jruby#1610]
I've got the following ruby code:

``` ruby
puts "#{key.inspect} == #{type.inspect}. hashes: #{key.hash}/#{type.hash} types: #{key.class}/#{type.class} =?= #{key == type} | eql? #{key.eql?(type)}. #{key.to_s.bytes.to_a.inspect}  #{type.to_s.bytes.to_a.inspect}"
```

Which produces the following output:

```
:uri == :uri. hashes: 971699949/971699949 types: Symbol/Symbol =?= true | eql? false. [117, 114, 105]  [117, 114, 105]
```

Note that `eql?` is returning false for these two values. when everything else points to them being the exact same symbol. The symbols in question are defined in two different ruby files but both are part of the same ruby gem. the `key` symbol was declared in a class context while the `type` symbol was referenced in an instance context.

Running against jruby-complete-1.7.11.jar.

This jar file can reproduce the issue:
https://github.com/chriseppstein/misc/blob/master/junkdrawer/class_loader_importer_test.jar

with the following command:

```
java -cp jruby-complete-1.7.11.jar:class_loader_importer_test.jar ClassLoaderImporterTest
```

**Comment by headius** [comment]
We've had a lot of changes in the past three years and no followup after last suggestion. Closing.
