### ISSUE TITLE
Possible incompatibility with inherited and super

### ISSUE THREAD

**Issue by beerlington** [jruby/jruby#1635]
Someone [opened an issue](https://github.com/beerlington/classy_enum/issues/36) on a gem I maintain and I've narrowed it down to what appears to be an inconsistency between JRuby and MRI.

When running my gem's specs in MRI 2.1 (or anything 1.8.7+), [this super line](https://github.com/beerlington/classy_enum/blob/master/lib/classy_enum/base.rb#L72) just calls `inherited` as expected. With JRuby 1.7.12, the super line calls whatever method is [dynamically defined above](https://github.com/beerlington/classy_enum/blob/master/lib/classy_enum/base.rb#L43-L61), and then calls `inherited`. I confirmed this by placing `puts __method__` right above `super`. That seems like an issue with JRuby since my understanding of `super` is that it should only be calling whatever the current method is (inherited), but on the superclass.

It's probably an edge case, but I figured I'd report it since it does seem to be an inconsistency between the two APIs.

**Comment by kares** [comment]
verified this works (script from https://github.com/beerlington/classy_enum/issues/36) under 9.1.8.0 (classy_enum 3.4.0, AS/AR 3.2.8)
