### ISSUE TITLE
Cannot call a Java method whose parameter is RubyArray when it is overloaded

### ISSUE THREAD

**Issue by Omegas7** [jruby/jruby#1643]
Have a Java method that accepts a RubyArray parameter. If you call it, it works fine. But then, if you overload that method with another with a different parameter, you won't be able to call the RubyArray one:

``` java
    import javax.script.*;

    import org.jruby.RubyArray;

    public class Main {
        public static void main(String[] args) throws ScriptException, NoSuchMethodException {
            Main app = new Main();
        }
        public Main() throws ScriptException, NoSuchMethodException {
            ScriptEngine jruby = new ScriptEngineManager().getEngineByName("jruby");
            jruby.eval("include Java;\n" + "def start(main) main.test([1,2,3]); end");
            Invocable invocable = (Invocable)jruby;
            invocable.invokeFunction("start",this);
        }
        public void test(int x) {
            System.out.println(x);
        }
        public void test(RubyArray array) {
            System.out.println(array);
        }
    }
```

If you run that code, JRuby will tell you that there are no methods for the parameter RubyArray, and then it will mention that there are two overloads available: (int) and (RubyArray), which doesn't make any sense.

JRuby 1.7.11 building with Java SE 6 on Eclipse Kepler for Mac.

**Comment by kares** [comment]
the resolution logic deal with Java types (and their mappings to Ruby types) but having the 'native' Ruby types recognized might be useful as well ... let's see how that goes.
