### ISSUE TITLE
`com.headius.invokebinder.InvalidTransformException` when using code loaded at runtime.

### ISSUE THREAD

**Issue by digitalextremist** [jruby/jruby#1658]
Here is a gist of a massive stacktrace I encounter from time to time @headius:
- https://gist.github.com/digitalextremist/01cf34d6b9ebae3c1ef6

Basically the situation is, I use code-reloading frequently on development and testing environment, using this style:

```
load <file>
```

Unpredictably, I get a stacktrace like the above if a section of code changes. I then need to hard-reset ( cold-start ) my application ( defeating the purpose of warm-reloading code ). I imagine mappings JIT/InvokeDynamic has to where methods are change, which for some reason do not get updated as new code is loaded and replaces old references.

This is not a critical issue for most people I would think, but it does hurt development. I've noticed this in `1.7.9`, `1.7.11` and now `1.7.12` but those are the only recent versions I've used. It might be in others but I cannot duplicate the issue to be sure, other than run for long periods and do something magical I am unaware of.

Thanks for everything jRuby guys.

**Comment by kylev** [comment]
I get something very similar to this (though not exactly) when using Rails 4.0.12 under JRuby 1.7.11 and Oracle JDK 1.8. The last mention of actual ruby code is from ActiveRecord's read.rb:

```ruby
        def define_method_attribute(name)
          safe_name = name.unpack('h*').first
          generated_attribute_methods::AttrNames.set_name_cache safe_name, name

          generated_attribute_methods.module_eval <<-STR, __FILE__, __LINE__ + 1
            def __temp__#{safe_name}
              read_attribute(AttrNames::ATTR_#{safe_name}) { |n| missing_attribute(n, caller) }
            end
            alias_method #{name.inspect}, :__temp__#{safe_name}
            undef_method :__temp__#{safe_name}
          STR
        end
```

**Comment by headius** [comment]
Can anyone still having this issue test JRuby 1.7.18 and 9000 and let us know if it still exists?

**Comment by digitalextremist** [comment]
Yes, I'm still getting it with `1.7.18@headius. I'll get a new dump of the exception tonight or so, since I seem to get it on a regular basis.

**Comment by headius** [comment]
And try to get a dump with -Xbacktrace.style=raw, which will show all the Java/JVM lines. Thank you!

FWIW, 9k has completely rewritten indy support, so hopefully this should not happen there.

**Comment by digitalextremist** [comment]
Here's a new backtrace, no `raw` yet @headius:

* https://gist.github.com/digitalextremist/997c1d66b2f62396b62d

**Comment by remofritzsche** [comment]
Any update on this? Experiencing the same issue.

**Comment by kaldrenon** [comment]
Seem to be experiencing something similar. Slightly different trace: https://gist.github.com/kaldrenon/f9b26c555f416b5f6ea4

Let me know if it's unrelated and I'll make it a different issue. `jruby 1.7.13`

**Comment by headius** [comment]
All code that uses invokedynamic has been completely rewritten since this bug was filed. In addition we run several test suites with invokedynamic enabled, and have not seen this error in many years.

If you run into this issue on a supported version of JRuby, please open a new bug.

**Comment by digitalextremist** [comment]
Thank you @headius, understood //
