### ISSUE TITLE
Can't run script with -S option using the complete jar

### ISSUE THREAD

**Issue by areman** [jruby/jruby#1678]
Hello,

java -cp **jruby-complete-1.6.8.jar** org.jruby.Main -S gem list 
works fine. But
java -cp **jruby-complete-1.7.12.jar** org.jruby.Main -S gem list 
failed.
**jruby: No such file or directory -- gem (LoadError)**

is it a bug or must I use another way to invoke the included scripts ?

**Comment by kares** [comment]
**java -jar -Djruby.cli.debug=true target/jruby-complete-9.2.1.0-SNAPSHOT.jar -S gem list**

```
*** LOCAL GEMS ***

bundler (1.16.1)
bundler-unload (1.0.2)
cmath (default: 1.0.0)
csv (default: 1.0.0)
executable-hooks (1.3.2)
fileutils (default: 1.1.0)
gem-wrappers (1.4.0)
ipaddr (default: 1.2.0)
jar-dependencies (default: 0.3.12)
jruby-launcher (1.1.4 java)
jruby-openssl (default: 0.10.0 java, 0.9.21 java)
jruby-readline (default: 1.2.2 java)
json (default: 2.1.0 java)
psych (default: 3.0.2 java)
rake (12.3.0)
rake-ant (default: 1.0.4)
rdoc (default: 6.0.1)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
scanf (default: 1.0.0)
webrick (default: 1.4.2)
```

... working well these days
