### ISSUE TITLE
Can't type anything at pry's prompt using Cygwin and JRuby.

### ISSUE THREAD

**Issue by stewartmatheson** [jruby/jruby#1680]
Jruby 1.7.12
Cygwin
Windows 7

How to reproduce: Add a break point to your code anywhere then run your code. Pry will stop the execution where it should and render whereami with no issue. At this stage typing commands does not show any characters at the prompt. Pry seems to be ignoring any keyboard input. All that can be done form this point is to press Ctrl-C to exit out of pry. Once exited command input resumes working normally.

**Comment by amitz** [comment]
+1. 
Windows 7, Ruby 1.9.3p545 and MSys2 (which is based on Cygwin).

**Comment by kares** [comment]
pry is working fine under 1.7.25 (EOL) and also JRuby 9.1.8.0 ... not sure about the Windows though.
