### ISSUE TITLE
Identity of delegator is wrong

### ISSUE THREAD

**Issue by samuil** [jruby/jruby#1710]
```
class Xxx < SimpleDelegator
  def initialize(str)
    super(str)
  end

  def eql?(other)
    to_s.eql? other.to_s
  end
end

a, b = Xxx.new('str'), Xxx.new('str')
[a,b].uniq.count #=> 2 # (should be 1)
{a => 1}[b] #=> nil # (should be 1)
```

For some reason classes that are inherited from `SimpleDelegator`, `DelegateClass()` and probably `Delegator` at all are not having their identity checked properly. Defining `eql?` and `hash` methods directly on those classes is not working either.

Problem can be narrowed to delegation, as creating classes that are not using `Delegator` are working correctly when `eql?` and `hash` methods are redefined.

**Comment by MSNexploder** [comment]
This can be closed. Works as expected using 9.1.9.0 (and 1.7.21):
```
a, b = Xxx.new('str'), Xxx.new('str')
[a,b].uniq.count #=> 1
{a => 1}[b] #=> 1
```

**Comment by headius** [comment]
Woot!
