### ISSUE TITLE
thread.object_id with fibers (due AR's connection pooling)

### ISSUE THREAD

**Issue by kares** [jruby/jruby#1717]
MRI (in 2.x) does return the same `object_id` for `Thread.current` inside a `Fiber` ... this is not how JRuby behaves (even on master). it's quite important esp. due the fact that Rails uses `Thread.current.object_id` as it's key to store/resolve DB connections thread-locally using a pool ... they seem to not be doing anything about it - thus decided to re-report the issue here https://github.com/rails/rails/issues/7746

Rails might switch to using `thread_variable_xxx` but this is also not currently available on JRuby (2.x mode) - which might be another approach to handle this right for structures such as thread mapped connection pools. MRI 2.1 samples :

``` ruby
Thread.new {
  Thread.current[:foo] = "bar"
  p [Thread.current.object_id, Thread.current[:foo]]

  Fiber.new {
    p [Thread.current.object_id, Thread.current[:foo]]
  }.resume
}.join
```

```
[23336800, "bar"]
[23336800, nil]
```

```
Thread.new {
  Thread.current.thread_variable_set :foo, "bar"
  p [Thread.current.object_id, Thread.current.thread_variable_get(:foo)]

  Fiber.new {
    p [Thread.current.object_id, Thread.current.thread_variable_get(:foo)]
  }.resume
}.join
```

```
[23281980, "bar"]
[23281980, "bar"]
```

**Comment by chuckremes** [comment]
This bug is still causing some headaches. See [issue 2 in `ruby-io` for detail](https://github.com/chuckremes/ruby-io/issues/2).

**Comment by headius** [comment]
Same issue as #1806. Root issue is that Thread.current in a Fiber is not really the parent thread but the Fiber's thread. Many synchronization mechanisms depend on these being the same, so simply changing it is not easy.
