### ISSUE TITLE
how to install gem using jruby on windows

### ISSUE THREAD

**Issue by SaiVardhan** [jruby/jruby#1721]
I have tried with this command

jruby -S gem install  rails
It shows like this
  ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNREFUS
ED: Connection refused - Connection refused (https://rubygems.org/latest_specs.4
.8.gz)

can anyone help on this...

**Comment by MSNexploder** [comment]
Can confirm, works as expected using 9.1.9.0 on Windows 7 (x64)
