### ISSUE TITLE
9000 embedding tests broken+disabled

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#1734]
I had to disable many embedding tests BSF, JSR223, RedBridge.  There are several things which need to be resolved before these can be reenabled:
1. We have an incomplete JIT and definitely cannot FORCE
2. compiled code in embedding APIs cache Node and not what IRBuilds
3. live top-level scope sharing is broken (IR will replace the scope it pushes -- item 2 should be part of this fix)

Some more notes as I was looking at this.  We have an IRTranslator which has an execute().  Instead of this (or in addition) probably want either a special *Method or some opaque structure which is the result of a build() method (could also be named compile()).  The opaque structure could then have the execute of IRTranslator and an execute where we specify the live variable values.

**Comment by kares** [comment]
... and 3y later - let's https://github.com/jruby/jruby/commit/686a861d561a9529f5f615483dd8ba107d8c9c25 :gun:
