### ISSUE TITLE
JRuby does not refer to TLS 1.1 the same way as MRI

### ISSUE THREAD

**Issue by aetherknight** [jruby/jruby#1735]
JRuby 1.7.12, as well as the current tip of JRuby's master branch, supports setting the ssl protocol version to TLS 1.1. However, it does not refer to the protocol in the same way that MRI's OpenSSL library does.

MRI 2.0 and later refer to TLS 1.1 and TLS 1.2 as :TLSv1_1 and :TLSv1_2, respectively. MRI 1.9.3 does not support either of these, but JRuby supports TLS 1.1 as :"TLSv1.1", requiring different symbols/strings to refer to TLS 1.1 depending on the chosen Ruby implementation.

An easy fix would be for JRuby support both `:TLSv1_1` and `:"TLSv1.1"`.

Split off of https://github.com/jruby/jruby/issues/1733

### Expected behavior
```
$ ruby --version
ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-darwin12.5.0]

$ ruby -ropenssl -e 'p OpenSSL::SSL::SSLContext.new.ssl_version=:"TLSv1_1"'
:TLSv1_1
```

### Observed behavior
```
$ jruby -ropenssl -e 'p OpenSSL::SSL::SSLContext.new.ssl_version=:"TLSv1_1"'
OpenSSL::SSL::SSLError: unknown SSL method `TLSv1_1'.
  ssl_version= at org/jruby/ext/openssl/SSLContext.java:355
        (root) at -e:1

$ jruby -ropenssl -e 'p OpenSSL::SSL::SSLContext.new.ssl_version=:"TLSv1.1"'
:"TLSv1.1"
```

**Comment by kares** [comment]
fixed on jruby-openssl **0.9.7** ... `TLSv1_1` can be set (there's likely still an issue with the resolved cipher list being a bit small, please refer to https://github.com/jruby/jruby/issues/2194)
