### ISSUE TITLE
JRuby does not support all SSL/TLS versions supported by Java

### ISSUE THREAD

**Issue by aetherknight** [jruby/jruby#1737]
Java 7 added TLS 1.1 and TLS 1.2 support, and JRuby already supports TLS 1.1 if it is available (although MRI 1.9.3 only supports SSLv3 and TLSv1). However, JRuby does not yet support TLS 1.2.

* http://docs.oracle.com/javase/7/docs/technotes/guides/security/enhancements-7.html

```
$ jruby -ropenssl -e 'p OpenSSL::SSL::SSLContext.new.ssl_version=:"TLSv1"'
:TLSv1

$ jruby -ropenssl -e 'p OpenSSL::SSL::SSLContext.new.ssl_version=:"TLSv1.1"'
:"TLSv1.1"

$ jruby -ropenssl -e 'p OpenSSL::SSL::SSLContext.new.ssl_version=:"TLSv1.2"'
OpenSSL::SSL::SSLError: unknown SSL method `TLSv1.2'.
  ssl_version= at org/jruby/ext/openssl/SSLContext.java:355
        (root) at -e:1

$ jruby -ropenssl -e 'p OpenSSL::SSL::SSLContext.new.ssl_version=:"TLSv1_2"'
OpenSSL::SSL::SSLError: unknown SSL method `TLSv1_2'.
  ssl_version= at org/jruby/ext/openssl/SSLContext.java:355
        (root) at -e:1
```

Split off of https://github.com/jruby/jruby/issues/1733

Note that https://github.com/jruby/jruby/issues/1735 was also filed regarding how to refer to newer TLS protocol versions.

**Comment by kares** [comment]
setting `OpenSSL::SSL::SSLContext.new.ssl_version=:"TLSv1_2"'` works in **0.9.7** (on Java 7+)
