### ISSUE TITLE
Unsupported platform: unknown-linux (ppc64le)

### ISSUE THREAD

**Issue by mbruzek** [jruby/jruby#1753]
It appears the POWER8 architecture (ppc64le) is not supported by jruby.  

I am trying to get logstash (which uses jruby) to run on Linux using Power PC hardware. When I run logstash I get the error "Unsupported platform: unknown-linux"

I am using the OpenJDK version 1.7.0_55
ubuntu@ubuntu-power-machine-1:~$ java -version
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1)
OpenJDK 64-Bit Zero VM (build 24.51-b03, interpreted mode)

The kernel is 3.18.0 and the Power architecture is ppc64le (little endian).
ubuntu@ubuntu-power-machine-1:~$ uname -a
Linux ubuntu-power-machine-1 3.13.0-8-generic #28-Ubuntu SMP Mon Feb 17 08:22:39 UTC 2014 ppc64le ppc64le ppc64le GNU/Linux

You can see the jruby stack trace when running the logstash command:

ubuntu@ubuntu-power-machine-1:~$ /opt/logstash/bin/logstash
LoadError: Unsupported platform: unknown-linux
require at org/jruby/RubyKernel.java:1085
require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
(root) at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/ffi/ffi.rb:69
require at org/jruby/RubyKernel.java:1085
(root) at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
require at org/jruby/RubyKernel.java:1085
(root) at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/ffi.rb:1
(root) at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
require at org/jruby/RubyKernel.java:1085
LibC at /opt/logstash/lib/logstash/util/prctl.rb:4
(root) at /opt/logstash/lib/logstash/util/prctl.rb:3
main at /opt/logstash/lib/logstash/runner.rb:79
(root) at /opt/logstash/lib/logstash/runner.rb:215

**Comment by gustavotemple** [comment]
@mbruzek, can you retest, please? thanks

**Comment by kares** [comment]
this can now be closed since https://github.com/jruby/jruby/pull/2812 is merged (will be in 1.7.20)
