### ISSUE TITLE
JRuby 1.7.11 (bundled with LogStash v. 1.4.1) fails on FreeBSD 10.0 with NotImplementedError: stat.st_dev unsupported or native support failed to load

### ISSUE THREAD

**Issue by emcrisostomo** [jruby/jruby#1754]
JRuby 1.7.11 fails on FreeBSD 10.0 with `NotImplementedError: stat.st_dev unsupported or native support failed to load`. This version is bundled with LogStash v. 1.4.1 and I haven't tried others. However, since this is a long standing issue (as explained below), I guess other JRuby versions might be affected.

The complete error dumped to the console is the following:

```
NotImplementedError: stat.st_dev unsupported or native support failed to load
       dev_major at org/jruby/RubyFileStat.java:190
  _discover_file at /opt/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/filewatch-0.5.1/lib/filewatch/watch.rb:140
            each at org/jruby/RubyArray.java:1613
  _discover_file at /opt/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/filewatch-0.5.1/lib/filewatch/watch.rb:122
           watch at /opt/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/filewatch-0.5.1/lib/filewatch/watch.rb:34
            tail at /opt/logstash-1.4.1/vendor/bundle/jruby/1.9/gems/filewatch-0.5.1/lib/filewatch/tail.rb:58
             run at /opt/logstash-1.4.1/lib/logstash/inputs/file.rb:130
            each at org/jruby/RubyArray.java:1613
             run at /opt/logstash-1.4.1/lib/logstash/inputs/file.rb:130
     inputworker at /opt/logstash-1.4.1/lib/logstash/pipeline.rb:163
     start_input at /opt/logstash-1.4.1/lib/logstash/pipeline.rb:157
```

This error can be reproduced in FreeBSD 10.0. I initially opened [one issue][i1819] on LogStash's issue tracker (very similar to [another one][i665] affecting Solaris) but it seems a JRuby issue instead.

[i665]: https://logstash.jira.com/browse/LOGSTASH-665
[i1819]: https://logstash.jira.com/browse/LOGSTASH-1819

Thank you very much for looking into this.

Cheers,
-- Enrico

**Comment by emcrisostomo** [comment]
Hi all,

the PR fixing this issue [has been merged][pr] into `jnr-ffi` upstream.

[pr]: https://github.com/jnr/jnr-ffi/pull/26

**Comment by mkristian** [comment]
thanx for the follow up

let's keep it open until we get jnr-ffi released and used by jruby

**Comment by kryten68** [comment]
Hi,

I'm seeing pretty much exactly this error on SunOS 5.8 on sparc using Logstash 1.4.3.
With:
java version "1.6.0_41"
Java(TM) SE Runtime Environment (build 1.6.0_41-b02)
Java HotSpot(TM) Server VM (build 20.14-b01, mixed mode) 

The full error is below. Could anyone shed any light on this error and how to resolve it? I arrived here as the error appears to be a very close match.

Thanks
Stuart

// ERROR MESSAGE//
NotImplementedError: stat.st_dev unsupported or native support failed to load
       dev_major at org/jruby/RubyFileStat.java:190
  _discover_file at /home/sitescope/logstash/logstash-1.4.3.dev-modified/lib/filewatch/watch.rb:150
            each at org/jruby/RubyArray.java:1613
  _discover_file at /home/sitescope/logstash/logstash-1.4.3.dev-modified/lib/filewatch/watch.rb:132
           watch at /home/sitescope/logstash/logstash-1.4.3.dev-modified/lib/filewatch/watch.rb:38
            tail at /home/sitescope/logstash/logstash-1.4.3.dev-modified/lib/filewatch/tail.rb:67
             run at /home/sitescope/logstash/logstash-1.4.3.dev-modified/lib/logstash/inputs/file.rb:130
            each at org/jruby/RubyArray.java:1613
             run at /home/sitescope/logstash/logstash-1.4.3.dev-modified/lib/logstash/inputs/file.rb:130
     inputworker at /home/sitescope/logstash/logstash-1.4.3.dev-modified/lib/logstash/pipeline.rb:163
     start_input at /home/sitescope/logstash/logstash-1.4.3.dev-modified/lib/logstash/pipeline.rb:157
+---------------------------------------------------------+
| An unexpected error occurred. This is probably a bug.   |
| You can find help with this problem in a few places:    |
|                                                         |
| * chat: #logstash IRC channel on freenode irc.          |
|     IRC via the web: http://goo.gl/TI4Ro                |
| * email: logstash-users@googlegroups.com                |
| * bug system: https://logstash.jira.com/                |
|                                                         |
+---------------------------------------------------------+
The error reported is:
  Bad file number - Bad file descriptor

**Comment by emcrisostomo** [comment]
Hi @kryten68, if you are curious, have a look at jnr/jnr-ffi#26: at least on FreeBSD jnr-ffi is choking on an ld script (beginning with a comment) and it incorrectly reports it as a broken binary.

Patching jnr-ffi is easy (it's just a regular expression to fix) but then you have to substitute the recompiled Java class into the JRuby JAR bundled with Logstash.

Chances are the same thing is happening on Solaris: check the library that it's trying to open and see if it's an ld script.

The FreeBSD port Makefile has the code to patch the Logstash distribution: you can use that code and, until JRuby bundles the patched jnr-ffi and until this new JRuby version ends into Logstash, you can use my [jnr-ffi][jnr-ffi-fork] fork.

[jnr-ffi-fork]: https://github.com/emcrisostomo/jnr-ffi

**Comment by mkristian** [comment]
closing since  jnr/jnr-ffi#26 is part of jnr-ffi-2.0.2

@kryten68 could file an issue for solaris - can not help due to lack of access to Solaris - maybe you can prepare a PR which is definitely welcome ;)

**Comment by uhammec** [comment]
Having the precisely same problem on Solaris 5.9 with logstash-1.4.2.

Logstash is doing `stat = File::Stat.new(file)` and needs the inode number returned.  Is there any different call that can be used to get the inode number?
