### ISSUE TITLE
Nanosecond precision when subtracting Time objects

### ISSUE THREAD

**Issue by robin850** [jruby/jruby#1771]
Hello,

When using `Time#-` passing a `Time` object, the precision is inconsistent with what MRI returns. In the following example, the nanosecond precision (9 decimals) should be used but for a strange reason, the number of digits is greater than 9. Looking at the code, this [condition](https://github.com/jruby/jruby/blob/60442ef0cdc7fadf7ede5dba93507c9a12f295a3/core/src/main/java/org/jruby/RubyTime.java#L580) is met ; thus, the `opMinus` method is triggered so [this line](https://github.com/jruby/jruby/blob/60442ef0cdc7fadf7ede5dba93507c9a12f295a3/core/src/main/java/org/jruby/RubyTime.java#L568) is as well but the number of digits returned is not the expected one:

``` ruby
>> time1 = Time.utc(2000, 1, 2, 23, 59, 59, Rational(999999999, 1000));
>> time2 = Time.utc(2000, 1, 2, 0, 0, 0, Rational(1, 1000));

>> (time1.nsec - time2.nsec) / 1000000000.0
=> 0.999999998 # Expected result
>> diff = time1 - time2;
>> diff - diff.floor
=> 0.9999999979918357
```

This has been tested with JRuby 1.7.13. A RubySpec should be added [here](https://github.com/rubinius/rubinius/pull/3071) ; even if the problem is not exactly the same, the spec should fit.

Have a nice day.

**Comment by rjnienaber** [comment]
The output seems to be identical for most current ruby versions:

```
ruby 1.9.3p550 (2014-10-27) [x86_64-darwin14.5.0]
0.999999998
0.9999999979918357

ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin14]
0.999999998
0.9999999979918357

ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
0.999999998
0.9999999979918357

jruby 1.7.24 (1.9.3p551) 2016-01-20 bd68d85 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_51-b16 +jit [darwin-x86_64]
0.999999998
0.9999999979918357

jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 +jit [darwin-x86_64]
0.999999998
0.9999999979918357
```
