### ISSUE TITLE
Time.now + bignum incorrect

### ISSUE THREAD

**Issue by joevandyk** [jruby/jruby#1779]
```
irb(main):061:0> Time.now + 7819128400
=> 2262-04-11 16:46:19 -0700

irb(main):062:0> Time.now + 7819128500
=> 1677-09-20 16:20:34 -0752 # time travel to past!
```

**Comment by rtyler** [comment]
I believe @joevandyk's analysis is correct and makes this bug still valid against JRuby 9.0.0.0

On MRI `Time.now + 78191284000` goes to the year 4493 whereas on my 9k/JDK8 install it goes to the year 2307.

That ain't right

**Comment by joevandyk** [comment]
thanks @headius !
