### ISSUE TITLE
I18n benchmark on JRuby from Elixir vs Ruby Showdown

### ISSUE THREAD

**Issue by ylluminate** [jruby/jruby#1781]
I noticed this:
http://littlelines.com/blog/2014/06/27/elixir-vs-ruby-showdown-part-one/

From that someone threw together a new implementation for Ruby as per:
https://gist.github.com/vjoel/a021e48b8752d0952dba

When I ran this on `jruby-head` I got the following results:
`$ jruby i18n-intern.rb`
```
                           user     system      total        real
string args           17.200000   0.540000  17.740000 ( 11.824000)
symbol args           10.460000   0.070000  10.530000 (  9.961000)
```

Which were little more than 2x slower than mri `2.1.2` on my system.

**Comment by rtyler** [comment]
Comparing JRuby 8k to MRI 2.15, 9k is faster on my machine. Regardless I don't know what objective of this ticket is. Please re-open if there's a fix or bug


Results fwiw;

MRI;
```
➜  1654  ruby i18n-intern.rb 
                           user     system      total        real
string args            4.410000   0.000000   4.410000 (  4.416974)
symbol args            3.900000   0.000000   3.900000 (  3.893375)
➜  1654  
```


JRuby 9.0.0.0/JDK8
```
➜  1654  ruby i18n-intern.rb 
                           user     system      total        real
string args            5.220000   0.040000   5.260000 (  3.704205)
symbol args            3.510000   0.010000   3.520000 (  2.928714)
➜  1654  
```
