### ISSUE TITLE
IO.select broken with output stream from Open3.popen3

### ISSUE THREAD

**Issue by mhoran** [jruby/jruby#1783]
`IO.select` does not wait for data to be readable, nor does it respect the timeout when reading from an output stream provided by `Open3.popen3'.

``` ruby
require 'open3'
path = "test.txt"
File.open(path, 'w') { |f| f.write('Z' * ARGV[0].to_i) }
STDOUT.write "Starting..."
Open3.popen3('cat', path) do |stdin, stdout, stderr|
  stdin.close
  while !stdout.eof? && IO.select([stdout], nil, nil, 1)
    stdout.read_nonblock 1
  end
end
```

This results in the following error on my Linux box, and Travis CI:

```
ruby -Xerrno.backtrace=true test.rb 1024
Starting...IO::EAGAINWaitReadable: Resource temporarily unavailable - 
  read_nonblock at org/jruby/RubyIO.java:2856
         (root) at test.rb:8
         popen3 at org/jruby/RubyIO.java:4433
         popen3 at /home/mhoran/.rbenv/versions/jruby-1.7.10/lib/ruby/1.9/open3.rb:74
         (root) at test.rb:5
```

If I first pipe the output of `stderr` to the write end of an `IO.pipe`, the program works as expected:

``` ruby
require 'open3'
path = "test.txt"
File.open(path, 'w') { |f| f.write('Z' * ARGV[0].to_i) }
STDOUT.write "Starting..."
Open3.popen3('cat', path) do |stdin, stdout, stderr|
  stdin.close
  read, write = IO.pipe
  Thread.new { IO.copy_stream(stdout, write); write.close }
  while !read.eof? && IO.select([read], nil, nil, 1)
    read.read_nonblock 1
  end
end
```

In actual usage, I'm just using `IO.select` to determine if there's content ready to be read, along with a timeout to ensure that the application quits if data is not available. However, there seems to be a fundamental issue with output forwarding given `IO.pipe` works as expected.

**Comment by kares** [comment]
works fine in 9K (checked >= 9.1.7.0), JRuby 1.7.x is EOL ... likely won't fix there.
