### ISSUE TITLE
DeadCodeElimination does not see into method ensures

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1786]
For this code:

```ruby
def foo
  osync = @sync
  p osync
  return self
ensure
  @sync = osync
end
```

DCE appears to be wiping out necessary initialization of "osync" that I'm doing in my EnsureTempsAssigned pass.

Here's the IR before DCE, with assignments intact:

```
Instructions:
BB [1:LBL_5:-1]
	%t_osync_2 = nil
	%v_0 = nil
BB [2:LBL_6:-1]
	%self = recv_self
	check_arity(0, 0, -1, false, -1)
	%t_%block_1 = recv_closure
	thread_poll
BB [3:LBL_0:-1]
	line_num(1)
	%t_osync_2 = get_field(%self, @sync)
	line_num(2)
	noresult_call(FUNCTIONAL, 'p', %self, [%t_osync_2])
	line_num(3)
	%v_0 = copy(%self)
BB [4:LBL_4:-1]
	line_num(5)
	put_field(%self, @sync) = %t_osync_2
	return(%v_0)
BB [5:LBL_3:-1]
	%v_0 = recv_jruby_exc
	line_num(5)
	put_field(%self, @sync) = %t_osync_2
	throw(%v_0)
BB [8:LBL_7:-1]
	return(nil)
```

And here it is after:

```
Instructions:
BB [1:LBL_5:-1]
BB [2:LBL_6:-1]
	%self = recv_self
	check_arity(0, 0, -1, false, -1)
	thread_poll
BB [3:LBL_0:-1]
	line_num(1)
	%t_osync_2 = get_field(%self, @sync)
	line_num(2)
	noresult_call(FUNCTIONAL, 'p', %self, [%t_osync_2])
	line_num(3)
	%v_0 = copy(%self)
BB [4:LBL_4:-1]
	line_num(5)
	put_field(%self, @sync) = %t_osync_2
	return(%v_0)
BB [5:LBL_3:-1]
	%v_0 = recv_jruby_exc
	line_num(5)
	put_field(%self, @sync) = %t_osync_2
	throw(%v_0)
BB [8:LBL_7:-1]
	return(nil)
```

This blocks JIT because I have no way to ensure I'm initializing all JVM locals (mapped to IR temp vars) at the IR level.

**Comment by enebo** [comment]
Marking for 9k but we now do nil inits now after we run DCE.  The problem has been mitigated but it would be nice to solve this in a more robust way. (probably not 9k initial release issue)

**Comment by subbuss** [comment]
I am going to close this and open a new issue that is about handling the nil initialization problem more generally. Now that ensure tmp vars are assigned pass runs at the end just before ir -> bytecode compilation, it handles JVM semantics of having the necessary inits.

That said, we need a generic solution that ensures that all local/tmps are assigned - this will also let us get rid of the return lookup-var OR return nil pattern in DynamicScope, interpreter, and jit.
