### ISSUE TITLE
Fiber#alive? regression in 1.7.11

### ISSUE THREAD

**Issue by judofyr** [jruby/jruby#1789]
``` ruby
require 'fiber'

fiber = Fiber.new do
  Fiber.yield
end

fiber.resume while fiber.alive?
```

This works fine in MRI and JRuby 1.7.10. Output in 1.7.11:

```
FiberError: dead fiber called
  resume at org/jruby/ext/fiber/ThreadFiber.java:57
  (root) at bug.rb:7
```

This breaks template streaming in Rails. See slim-template/slim#514.

**Comment by enebo** [comment]
This seems to be workign in 9.x.  1.7.x is EOL and this will not get fixed.  Marking WONTFIX
