### ISSUE TITLE
Reserve IR interpreter temp vars from thread-local pool

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1794]
This is an experimental patch to avoid allocating Object[] space for temp vars in the IR interpreter on every entry into a method.

The logic here is simple: ThreadContext contains a large pre-allocated Object[] array, and instead of allocating a new array, Interpreter requests a chunk of that. The proper starting offset is propagated along with the array reference.

This does not immediately seem to help interpreter performance; however, I believe this will become important as we remove other major source of allocation like framing and scopes.

Patch is here: https://gist.github.com/headius/fad70bf08a1ebc96dc68

I'm playing with some other modifications to get IR interpreter performance a bit higher.

cc @subbuss @enebo

**Comment by enebo** [comment]
We know we can do this and may at some point but I am closing out things to reduce what we need to pay attention for for release.
