### ISSUE TITLE
Time#zone using Time#local

### ISSUE THREAD

**Issue by robin850** [jruby/jruby#1795]
Hello,

We've discovered an inconsistency of JRuby with MRI when dealing with time zones. The behavior is kind of weird on MRI anyway but we wanted with @febuiles to bring a discussion around this. `Time.local` supports ten parameters for historical reasons (when dealing with `#to_a` for instance) but the passed time zone is ignored and MRI and Rubinius returns the current time zone:

``` ruby
>> time = Time.local(0, 30, 1, 30, 10, 2005, 0, 0, false, 'US/Eastern');

>> RUBY_ENGINE
=> "ruby"
>> time.zone
=> "CEST" # In my case

>> RUBY_ENGINE
=> "rbx"
>> time.zone
=> "CEST"
```

However, JRuby has a sightly different behavior that isn't the same between JRuby 1.7.12 and 1.7.13:

``` ruby
>> JRUBY_VERSION
=> "1.7.12"
>> time.zone
=> nil

>> JRUBY_VERSION
=> "1.7.13"
>> time.zone
=> "EDT"
```

The returned time zone is wrong anyway because EDT stands for "Eastern Daylight Time" while `false` has been passed as the ninth parameter (i.e. isdst).

To bring JRuby in line with MRI and Rubinius, [these lines](https://github.com/jruby/jruby/blob/60442ef0cdc7fadf7ede5dba93507c9a12f295a3/core/src/main/java/org/jruby/RubyTime.java#L1200-L1209) should not be reached when we are calling `Time#local`.

Have a nice day!

**Comment by nielspetersen** [comment]
This issue is part of the current issue (14th) of the RubyIssues. https://rubyissues.ongoodbits.com/. :gem:

**Comment by headius** [comment]
This is still broken on current JRuby master:
```
$ jruby -ve "p Time.local(0, 30, 1, 30, 10, 2005, 0, 0, false, 'US/Eastern').zone"
jruby 9.1.0.0-SNAPSHOT (2.3.0) 2016-02-13 8136dd9 Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [darwin-x86_64]
"EDT"
```

**Comment by headius** [comment]
Ok, I think I have a lead.

I think the problem here is that the given time and date are right at the DT/ST boundary for 2005 in that time zone.

In 2005, DST transition occured on October 30 at 2AM. You gave a time of 1:30AM, which for this case would require us to negotiated which side of the DST boundary we are on. I believe it's picking EDT because it sees the time is before 2AM, and therefore pre-transition.

We build up the time starting with all zeros and UTC and add in the month, day, hour, minute, etc, and then eventually apply the time zone. There's some logic related to the isDST parameter that appears to try to negotiate which side of the DT/ST boundary we are on, but passing true does not seem to affect anything. 1:30AM always comes out as EDT, and 2:30AM always comes out as EST.

I modified our code to use the isdst the same way MRI does, flopping the pre/post-transition flag, and I was able to get it to do EST and EDT predictably. Of course this isn't correct, since MRI just ignores the given time zone entirely.

And removing our time zone argument handling broke a bunch of other things.

**Comment by headius** [comment]
Here's the diff. The first part is removing our TZ arg processing, and the second part is using isdst like MRI does to decide the DT/ST boundary.

```diff
diff --git a/core/src/main/java/org/jruby/RubyTime.java b/core/src/main/java/org/jruby/RubyTime.java
index 9afc81c..8497fc7 100644
--- a/core/src/main/java/org/jruby/RubyTime.java
+++ b/core/src/main/java/org/jruby/RubyTime.java
@@ -1368,16 +1368,6 @@ public class RubyTime extends RubyObject {
         DateTimeZone dtz;
         if (gmt) {
             dtz = DateTimeZone.UTC;
-        } else if (args.length == 10 && args[9] instanceof RubyString) {
-            if (utcOffset) {
-                dtz = getTimeZoneFromUtcOffset(runtime, args[9]);
-                setTzRelative = true;
-            } else {
-                dtz = getTimeZoneFromString(runtime, args[9].toString());
-            }
-        } else if (args.length == 10 && args[9].respondsTo("to_int")) {
-            IRubyObject offsetInt = args[9].callMethod(runtime.getCurrentContext(), "to_int");
-            dtz = getTimeZone(runtime, ((RubyNumeric) offsetInt).getLongValue());
         } else {
             dtz = getLocalTimeZone(runtime);
         }
@@ -1485,15 +1475,17 @@ public class RubyTime extends RubyObject {
             dt = dt.withZoneRetainFields(dtz);
 
             // If we're at a DST boundary, we need to choose the correct side of the boundary
-            if (isDst) {
-                final DateTime beforeDstBoundary = dt.withEarlierOffsetAtOverlap();
-                final DateTime afterDstBoundary = dt.withLaterOffsetAtOverlap();
+            final DateTime beforeDstBoundary = dt.withEarlierOffsetAtOverlap();
+            final DateTime afterDstBoundary = dt.withLaterOffsetAtOverlap();
 
-                final int offsetBeforeBoundary = dtz.getOffset(beforeDstBoundary);
-                final int offsetAfterBoundary = dtz.getOffset(afterDstBoundary);
+            final int offsetBeforeBoundary = dtz.getOffset(beforeDstBoundary);
+            final int offsetAfterBoundary = dtz.getOffset(afterDstBoundary);
 
-                // If the time is during DST, we need to pick the time with the highest offset
+            // If the time is during DST, we need to pick the time with the highest offset
+            if (isDst) {
                 dt = offsetBeforeBoundary > offsetAfterBoundary ? beforeDstBoundary : afterDstBoundary;
+            } else {
+                dt = offsetBeforeBoundary > offsetAfterBoundary ? afterDstBoundary : beforeDstBoundary;
             }
         } catch (org.joda.time.IllegalFieldValueException e) {
             throw runtime.newArgumentError("time out of range");
```

**Comment by headius** [comment]
Revisited this to try to finish it for 9.1.3.0, but the proposed patch above breaks a number of specs. Back to the drawing board...and punting to 9.1.4.0.

**Comment by headius** [comment]
No new reports on this as far as I can tell and it's edge-casey behavior not on roadmap at present. Detargeting.
