### ISSUE TITLE
 Digest#== throws TypeError when testing against nil (ruby bug #9913)

### ISSUE THREAD

**Issue by malakai97** [jruby/jruby#1798]
Reposting here; forgive me if this is redundant.  

See: http://bugs.ruby-lang.org/issues/9913

present in: ruby -v: jruby 1.7.10 (1.9.3p392) 2014-01-09 c4ecd6b on OpenJDK 64-Bit Server VM 1.7.0_55-b14 [linux-amd64]

**Comment by kares** [comment]
this is behaving in 9.1.7.0 correctly.
