### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by DAddYE** [jruby/jruby#1804]
I already tweeted about it with @headius, and I already opened an [issue on MRI](https://bugs.ruby-lang.org/issues/9999) as well.

However I think jruby will benefit much more of type checks than MRI since I'm pretty sure will help to (out)perform (without caveats) MRI.

I would love to have on jruby a **strong** type signature, in a typescript or dart fashion.

I also think the awesome @headius could find a way to type check our code at AOT (as in dart).

As syntax I purpose something like:

``` rb
# For methods
def connect(r <- Stream, c <- Client) ->  Fiber
# or
def connect(Stream r, Client c) -> Fiber # quite sure this will make some reduce problems in the grammar
# or reuse options arguments (tricky but possible for the compiler to understand if is an option or a type)
def connect(r: Stream, c: Client) -> Fiber

# and for vars

z = [1,2,3,4] # derived
x: []int = z # typechecked

# Hash
z = { a: 1, b: 2, c: 3}
x: [Symbol]int = z

# Normal
x: String = q
```

Thoughts?

**Comment by ndbroadbent** [comment]
Hello! I was just wondering if there has been any new developments in this area, especially after the mass adoption of TypeScript, and with the release of Sorbet.

I’m very tempted to move my application to JRuby, and I think type annotations would be a really good fit! Type errors are still the number one cause of bugs in my application.

Would it be possible to open this issue again and maybe start a new discussion? Or would there be a better place to chat about this?

**Comment by chrisseaton** [comment]
Why do you need JRuby to do anything? You can already run Sorbet on applications that you're going to run on JRuby can't you?

**Comment by ndbroadbent** [comment]
Yeah [it looks like it's possible to use Sorbet with JRuby](https://github.com/sorbet/sorbet/issues/1216).

But I was wondering if JRuby might be able to do some more interesting things with these type annotations, such as:

- Automatically generate Sorbet type definitions for any Java libraries
- Use the type annotations in the compiler to generate efficient bytecode

It would be amazing if we could get a huge performance boost just by writing a subset of Ruby and declaring a few `String` and `Int64` annotations.

**Comment by chrisseaton** [comment]
Yes there's been discussions about using the type annotations for performance and I think some people are already experimenting.

I want to try it myself in my implementation of Ruby, TruffleRuby, but I am guessing the performance benefit won't be quite as dramatic as many people hope - JRuby and other optimising Ruby implementations already know many of these types, and the guards they use to enforce them, which is the bit you could remove based on the static annotations, are pretty lightweight. But still worth trying.

**Comment by enebo** [comment]
Beyond what @chrisseaton says, static types may help in reducing warmup time since we would potentially depend less on profiled optimizations to gain the same/similar performance.

Personally, I fear the notion that static typing will become a subset of Ruby.  It will lead to gems writing in terms of types at the public API layer which will marginalize the duck-typing aspect of Ruby.  At least this is my prediction looking at languages like Groovy.
