### ISSUE TITLE
Issues testing OAEPadding on Jruby 1.7.11

### ISSUE THREAD

**Issue by derryos** [jruby/jruby#1819]
I'm using OAEP padding as part of some decryption/encryption steps -
specifically using: /ECB/OAEPWithSHA1AndMGF1Padding

Testing encryption/decryption via standard ruby 1.9.3 and openssl 0.9.8e
works as expected. We don't explicitly name the above padding - we pass
OpenSSL::PKey::RSA::PKCS1_OAEP_PADDING (padding parameter 4) to openssl's
RSA decryption methods and it works correctly.

When repeating the same test via JRuby 1.7.11 + 1.9.3, we saw padding
failures and after some debugging, linked it to the fact that the default
JRuby padding associated with padding parameter 4 (
https://github.com/jruby/jruby/blob/master/ext/openssl/src/main/java/org/jruby/ext/openssl/PKeyRSA.java#L443
)
is actually the same algorithm but with MD5 vs SHA1 as the digest algorithm.

Modifying that file and changing MD5->SHA1 fixed our issues. Is there a
reason why this is the case? I'm trying to understand why the behaviour is
different between standard ruby and JRuby.

**Comment by SteveAquino** [comment]
:+1: Having this exact same problem, resulting in the following error:

```
OpenSSL::PKey::RSAError: data hash wrong
	from org/jruby/ext/openssl/PKeyRSA.java:467:in `private_decrypt'
```

Doesn't look like OAEPWithSHA1AndMGF1Padding is supported.  Duplicating the exact same code but passing the correct algorithm works, but it would be nice to use the packaged library.

**Comment by kares** [comment]
could we have a failing piece of .rb (RSA-key) related code, please - so we can make sure its tested

**Comment by kares** [comment]
calling it a day since https://github.com/jruby/jruby-openssl/pull/54
