### ISSUE TITLE
Error installing Gems in jruby 1.7.13 (Windows 7x64)

### ISSUE THREAD

**Issue by fxgallego** [jruby/jruby#1821]
After just finished installed with the windows installer + jre x64
jruby -v shows 
jruby 1.7.13 (1.9.3p392) 2014-06-24 43f133c on Java HotSpot(TM) 64-Bit Server VM
1.7.0_07-b10 [Windows 7-amd64]

jruby -S gem install rails
ERROR: Loading command: install (OpenSSL::X509::StoreError)
setting default path failed: null
ERROR: While executing gem ... (NoMethodError)
undefined method `invoke_with_build_args' for nil:NilClass

**Comment by samyrabdo** [comment]
I have no works to say thank you fxgallego...
