### ISSUE TITLE
RbConfig::CONFIG is missing entry for vendordir (and some related entries based off this)

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#1826]
Current version of rubygems does not run without this (though they will be making a small workaround for us for the time being).  Might as well audit some other keys in here since we seem to be missing lots of keys.  The specific one causing problems is:

``` text
"vendordir"=>"/Users/enebo/Developer/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/vendor_ruby"
```

**Comment by kares** [comment]
@enebo do you feel like this is still relevant or a 1.7 piece to be closed?

**Comment by kares** [comment]
I mean still no `RbConfig::CONFIG['vendordir']` but not one complains thus no problem :)

**Comment by headius** [comment]
Example of enabling `vendordir` and friends using the Java properties we added.

```
$ jruby -J-Dvendor.dir.general=../jruby/lib -e "puts RbConfig::CONFIG['vendordir']"
../jruby/lib/ruby/stdlib/vendor_ruby
```

It seems to mess something up if you point it at an empty dir, though:

```
$ jruby -J-Dvendor.dir.general=/tmp -e "puts RbConfig::CONFIG['vendordir']"
NameError: uninitialized constant RbConfig
  const_missing at org/jruby/RubyModule.java:3411
         <main> at -e:1
```

We added the property because some JRuby distributors wanted a vendor dir, so I think we can call this one done a long time ago.
