### ISSUE TITLE
IO.select not interruptable by Timeout::timeout

### ISSUE THREAD

**Issue by mhoran** [jruby/jruby#1831]
I an attempt to use non-blocking IO to work around the same issue for `IO#gets`, I  discovered that `IO.select` cannot be interrupted by `Timeout::timeout`.

I expected the following to work:

``` ruby
read, write = IO.pipe
Timeout::timeout(1) do
  IO.select([read])
end
```

So long as the read end of the pipe receives no data, and is not closed, this will block forever.

I found that the following results in the desired behavior:

``` ruby
read, write = IO.pipe
Timeout::timeout(1) do
  Thread.new { IO.select([read]) }.join
end
```

Ideally, `Timeout::timeout` would not block for `IO#gets` or `IO.select`. I've implemented this workaround in [capybara-webkit](https://github.com/thoughtbot/capybara-webkit) but would prefer a proper solution.

**Comment by MSNexploder** [comment]
This works as expected in 9.1.9.0 (and 1.7.21):
```
read, write = IO.pipe
Timeout::timeout(1) do
  IO.select([read])
end

# => "Timeout::Error: execution expired" after one second
```

**Comment by headius** [comment]
Thank you!
