### ISSUE TITLE
[jruby-1_7] Two failing tests in test/test_command_line_switches.rb

### ISSUE THREAD

**Issue by donv** [jruby/jruby#1849]
These hang:

test_dash_little_v_version_verbose_T_taint_d_debug_K_kcode_r_require_b_benchmarks_a_splitsinput_I_loadpath_C_cwd_F_delimeter_J_javaprop_18

test_dash_little_v_version_verbose_T_taint_d_debug_K_kcode_r_require_b_benchmarks_a_splitsinput_I_loadpath_C_cwd_F_delimeter_J_javaprop_19

I have no idea why, yet.  Help wanted.

**Comment by kares** [comment]
since 1.7.x has EOLed .. let's call this one a day, shall we :fallen_leaf:
