### ISSUE TITLE
type casting not working with sleep

### ISSUE THREAD

**Issue by gucki** [jruby/jruby#1856]
Using MRI and Rails 4.1.0 `sleep(1.second)` works as expected. With jruby-1.7.13 it fails with

    E, [2014-07-25T11:53:19.401000 #40493] ERROR -- : can't convert ActiveSupport::Durationinto time interval
    E, [2014-07-25T11:53:19.401000 #40493] ERROR -- : org/jruby/RubyKernel.java:809:in `sleep'

**Comment by rtyler** [comment]
This has since been fixed in 1.7.21 and then regressed again in JRuby 9k :P

```
[13] pry(main)> RUBY_VERSION
=> "1.9.3"
[14] pry(main)> sleep 2.seconds
=> 2
[15] pry(main)> 
```

```
[2] pry(main)> RUBY_VERSION
=> "2.2.0"
[3] pry(main)> sleep 3.seconds
TypeError: can't convert ActiveSupport::Durationinto time interval
from org/jruby/RubyKernel.java:659:in `sleep'
[4] pry(main)> 
```

Checking the latest HEAD of master since I *swear* @headius already fixed this though

**Comment by headius** [comment]
What a weird thing to have broken in 9k.

**Comment by rtyler** [comment]
I'm going to close this now, since this is fixed in 9k. My previous snippet was from a pre-release version of JRuby 9k (pre1 iirc), but I've grabbed the latest RVM and installed 9k gold master super A++ edition:

```
[1] pry(main)> require 'active_support/all'
=> true
[2] pry(main)> 1.minute
=> 60 seconds
[3] pry(main)> sleep 2.seconds
=> 2
[4] pry(main)> JRUBY_VERSION
=> "9.0.0.0"
[5] pry(main)> RUBY_VERSION
=> "2.2.2"
[6] pry(main)> 
```
