### ISSUE TITLE
Choose strategy for using Java 7 classes vs. Ruboto

### ISSUE THREAD

**Issue by donv** [jruby/jruby#1863]
Master currently fails on Android with the following exception:

```
W/System.err( 9139): Caused by: java.lang.NoClassDefFoundError: java.nio.channels.SeekableByteChannel
W/System.err( 9139):    at org.jruby.util.io.ChannelFD.initChannelTypes(ChannelFD.java:132)
W/System.err( 9139):    at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:32)
W/System.err( 9139):    at org.jruby.util.io.OpenFile.setChannel(OpenFile.java:189)
W/System.err( 9139):    at org.jruby.RubyIO.prepIO(RubyIO.java:234)
W/System.err( 9139):    at org.jruby.RubyIO.prepStdio(RubyIO.java:187)
W/System.err( 9139):    at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:193)
W/System.err( 9139):    at org.jruby.Ruby.init(Ruby.java:1248)
W/System.err( 9139):    at org.jruby.Ruby.newInstance(Ruby.java:316)
```

While parts of `java.nio` is included on Android, it seems java.nio.channels.SeekableByteChannel is not:

http://developer.android.com/reference/java/nio/channels/package-summary.html

While I am sure we all want the fastest possible desktop/server JRuby, I would hate for JRuby 1.7.x to be the last JRuby to run on Android.

Dalvik and ART do offer JNI, there is Linux below, and we can relocate Java classes like SeekableByteChannel to "user space" packages like `jruby.java.nio.channels.SeekableByteChannel`.

What do you think?

**Comment by kares** [comment]
this is defunct by now, 9.2 only supports Java 8 and Android has also caught up with Java
