### ISSUE TITLE
uniform resource loading on servlet container

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#1865]
currently there are loading issue with that special servlet container or with this special servlet container. but I step back then ALL them have well defined way to load resource.

``` java
Thread.currentThread.getContextClassLoader.getResource
```

once this is supported by JRuby and it works for 5 different servlet containers it should work for the 6 one as well. and it should be no difference whether the classloader works on unexploded and packed war file or whether the container unpacks it somewhere.

it needs a slightly different packing as warbler does right now: embed everything into **WEB-INF/classes** since that is the root of the classloader.

since JRuby already has it's own pseudo protocol (i.e. it is not a registered protocol inside the JVM): classpath
now you only need to add classpath: to ruby LOAD_PATH and to the Gem.paths.path (or use GEM_PATH env) and probably some ruby frameworks need to have the current working directory set to classpath: as well.

having this in place other self contained java archives will probably work as well. some plugin frameworks might require to the classloader which contains JRuby itself instead of the currentThread contextClassloader.

**Comment by kares** [comment]
@mkristian sounds like you did all of this ... or is it still a task pending?

**Comment by mkristian** [comment]
@kares no pending tasks unless classloader errors pop up somewhere ;)
closing
