### ISSUE TITLE
Allow access to Java inner classes with corresponding private Ruby methods

### ISSUE THREAD

**Issue by donv** [jruby/jruby#1871]
Hi!

Given the following Java class:

```java
public final class ClassWithAttr {
    public static final class attr {
        public static final int value = 42;
    }
    public static final class id {
        public static final int value = 42;
    }
}
```

it should be possible to access the inner class ```attr``` using the syntax ```ClassWithAttr.attr```.  This works for ```ClassWithAttr.id```, and you can get to the field using ```ClassWithAttr.id.value```.  This should work for ```ClassWithAttr.id.value``` as well, but currently fails with an exception:

```
$ rvm use jruby
Using /Users/uwe/.rvm/gems/jruby-1.7.13
$ javac ClassWithAttr.java 
$ irb
jruby-1.7.13 :001 > Java::ClassWithAttr.id.value
 => 42 
jruby-1.7.13 :002 > Java::ClassWithAttr.attr.value
NoMethodError: private method `attr' called for Java::Default::ClassWithAttr:Class
	from (irb):2:in `evaluate'
	from org/jruby/RubyKernel.java:1101:in `eval'
	from org/jruby/RubyKernel.java:1501:in `loop'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from /Users/uwe/.rvm/rubies/jruby-1.7.13/bin/irb:13:in `(root)'
```

As a side note, on Ruboto we get a slightly different error message (https://github.com/ruboto/ruboto/issues/654):

```
(NoMethodError) undefined method `attr' for Java::Android::R:Class
```

**Comment by kares** [comment]
wondered where's that `attr` method coming from - initially thought its some internal of Java integration.
... but its a valid Module method (`attr_reader` alias): http://ruby-doc.org/core-2.3.0/Module.html#method-i-attr ... thus this won't fix, workaround: `Module.send :remove_method, :attr`
