### ISSUE TITLE
Array#delete_if - no size update

### ISSUE THREAD

**Issue by regfaker** [jruby/jruby#1877]
jruby-1.7.6 [ x86_64 ]   (using rvm)

a=[1,2,3,4]
a.delete_if { |e|  puts a.size; e % 2 == 0 }

4
4
4
4
 => [1, 3] 

End result ok - array elements were deleted, but size was not updated during delete_if iterations and it should be.
If I run this in ruby-1.9.3-p484 [ x86_64 ]:
4
4
3
3
 => [1, 3]

**Comment by rtyler** [comment]
This is behaving properly as of JRuby 9k

```
[11] pry(main)> JRUBY_VERSION
=> "9.0.0.0"
[12] pry(main)> a=[1,2,3,4]
=> [1, 2, 3, 4]
[13] pry(main)> a.delete_if { |e| puts a.size; e % 2 == 0 }
4
4
3
3
=> [1, 3]
[14] pry(main)> 
```
