### ISSUE TITLE
DateTime.strptime does not work right

### ISSUE THREAD

**Issue by josephcrim** [jruby/jruby#1884]
Tested this on jruby-1.7.13 and jruby-1.7.12

DateTime.strptime returns incorrect values:

$ cat date.rb 
require 'date'
date = "05/19/2014 10:58:59"
puts DateTime.strptime(date, "%m/%d/%Y %H:%M:%s")

$ rbenv versions
  system
  2.0.0-p353
  2.1.1
  jruby-1.7.12
- jruby-1.7.13 (set by RBENV_VERSION environment variable)

$ ruby date.rb 
1970-01-01T00:00:59+00:00

$ rbenv shell jruby-1.7.12
$ ruby date.rb 
1970-01-01T00:00:59+00:00

$ rbenv shell 2.0.0-p353
$ ruby date.rb 
2014-05-19T10:58:00+00:00

**Comment by chi6rag** [comment]
what is the reason of having reqrire_frags and complete_frags methods in jruby/lib/ruby/stdlib/date.rb
