### ISSUE TITLE
OpenSSL::X509::Store doesn't implement the add_path method

### ISSUE THREAD

**Issue by jwinter** [jruby/jruby#1886]
OpenSSL::X509::Store#add_path is unimplemented in JRuby 1.7.13. Store#add_path is a method that accepts a single String argument, a path to a directory full of SSL certs. It adds all the SSL certs it finds in that directory to the store.

MRI implementation is here (if that helps):
https://github.com/ruby/ruby/blob/trunk/ext/openssl/ossl_x509store.c#L238

Current workaround is to create a single .pem file with all of my certs and use Store#add_cert instead.

I hit this issue when using a directory for the value :ssl_ca_cert in my .gemrc like:

```
:ssl_ca_cert: /path/to-directory/of/ssl-certs/
```

**Comment by kares** [comment]
this has been added since (at some point around jruby-openssl 0.9.12 or so)
