### ISSUE TITLE
install failure with 1.7.13 or jruby-head on rvm 1.25.28

### ISSUE THREAD

**Issue by MilesRoberts** [jruby/jruby#1916]
not sure if this needs to be opened here or with RVM. if RVM please let me know.

There has been an error while checking out branch master.  
Halting the installation.
Copying from repo to src path...
jruby-head - #mvn....................
Error running 'mvn',
showing last 15 lines of /path/to/rvm/.rvm/log/1408661753_jruby-head/mvn.log
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:51.400s
[INFO] Finished at: Thu Aug 21 18:57:47 EDT 2014
[INFO] Final Memory: 42M/257M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.tesla.polyglot:tesla-polyglot-maven-plugin:0.1.1:execute (install_gems) on project jruby-lib: Execution install_gems of goal io.tesla.polyglot:tesla-polyglot-maven-plugin:0.1.1:execute failed: java.lang.NoClassDefFoundError: Could not initialize class jnr.enxio.channels.Native$SingletonHolder -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jruby-lib

**Comment by rtyler** [comment]
I've verified that this issue has been fixed in more recent releases of JRuby 1.7.x

On a RHEL7 EC2 image with JRuby 1.7.13 I can repro the issue (with glibc.i686 installed):

```
[ec2-user@ip-172-30-0-231 ~]$ ruby -e "puts JRUBY_VERSION; puts Java::jnr.unixsocket.Native.libsocket"
1.7.13
NativeLibrary.java:87:in `loadNativeLibraries': java.lang.UnsatisfiedLinkError: /usr/lib/libc.so.6: wrong ELF class: ELFCLASS32
	from NativeLibrary.java:70:in `getNativeLibraries'
```

With JRuby 1.7.19, this same command returns:

```
[ec2-user@ip-172-30-0-231 ~]$ ruby -e "puts JRUBY_VERSION; puts Java::jnr.unixsocket.Native.libsocket"
1.7.19
jnr.unixsocket.Native$LibC$jnr$ffi$0@6bbd4880
```
