### ISSUE TITLE
New exceptions being raised in java thread

### ISSUE THREAD

**Issue by monkstone** [jruby/jruby#1917]
Sorry for my limited ability to investigate this issue. But using jruby-head with ruby-processing, I am getting this very terse error message with many sketches (some run fine):-
Exception: org.jruby.exceptions.RaiseException thrown from the UncaughtExceptionHandler in thread "Animation Thread"
Now I expect the "Animation Thread" refers to the processing (java) animation thread, but why such exceptions are being raised with jruby-head, when there was no such problem with jruby-1.7.13, I have no idea.

SNAPSHOT (2.1.2) 2014-08-20 8fb3b63 Java HotSpot(TM) 64-Bit Server VM 25.20-b15 on 1.8.0_20-ea-b15 [linux-amd64]

**Comment by monkstone** [comment]
### Update and summary
The majority of ruby processing sketches fail with following exception when run with jruby-9.0.0.0-SNAPSHOT

`Exception: org.jruby.exceptions.RaiseException thrown from the UncaughtExceptionHandler in thread "Animation Thread"`

Last tested with jruby 9.0.0.0-SNAPSHOT (2.2.0p0) 2015-01-06 ca55072 Java HotSpot(TM) 64-Bit Server VM 24.72-b04 on 1.7.0_72-b14 +jit [linux-amd64]

Interestingly sketches run fine when run in ruby-processing watch mode see preceeding comment.

**Comment by subbuss** [comment]
Also adding @enebo .. We'll try to take another look soon. But good to hear that there has been some progress on this at least! :-)

**Comment by subbuss** [comment]
Random thought .. Wonder if this is related to https://github.com/jruby/jruby/issues/2416

**Comment by enebo** [comment]
@subbuss hmmm that is a good thought.  We either might be raising the old thing somewhere and IR is not catching it or we are raising the new thing and the old catches are not catchnig that?

**Comment by subbuss** [comment]
More the latter ... along the lines of commit 10540e2ba80f7f05e9cb5874d8172fddd729a080 .. wonder if there is something needed for thread as well. That said, the exception that monkstone is reporting is not a break/return jump exception but a org.jruby.exceptions.RaiseException .. so my comment above could be a red herring as well.

**Comment by subbuss** [comment]
I cloned the app and ran it, and looks like the I/O streams have been closed .. so even adding "p 1" as the first statement of draw in grey_circles.rb throws the same exception. So, here is an even more reduced test case that bombs:
```ruby
require_relative 'lib/ribiprocessing'

class GreyCircles < Ribiprocessing::SimpleApp
  def draw
    p "here"
  end
end
    
GreyCircles.new title: 'Oh so many circles'
```

**Comment by monkstone** [comment]
JUst to be sure I ran equivalent in ruby-processing
```ruby
draw
  p 1
end
```
When sketch is run `rp5 run test.rb` I get 5 '1' printed followed by crash:-

`Exception: org.jruby.exceptions.RaiseException thrown from the UncaughtExceptionHandler in thread "Animation Thread"`

Sketch runs fine with  `rp5 watch test.rb` with a continuous stream of '1' printed

So for whatever reasons error is not trggered in watch mode (or can be recovered?)

**Comment by headius** [comment]
Sorry this one escaped my attention.

The trigger for the exception you're seeing is that the stdio streams get shut down when the main script ends. In MRI, regardless of what is happening in the rest of the runtime, main script exit means process terminates. We can't necessarily force all threads to die to emulate this, but we do tear down the current runtime at that point. The closed streams are then used by your script and an exception is raised.

I added a "gets" to the bottom of your grey_circles.rb script and it runs correctly.

So this is a bit of a conundrum. JRuby 1.7 and lower did not close stdio streams, mostly because we did not fully implement MRI's stdio lifecycle (among many other IO-related changes in 9k). The close we do is actually fake...we disconnect the stdio stream from our RubyIO object and mark the RubyIO as closed. I'm not sure what we lose if we *don't* do this fake closing, but I'll try to recall why I've stuck to my guns and kept it in place.

Short-term workaround for you would be to make sure the main script does not terminate before the other threads.

**Comment by headius** [comment]
I feel like we need to do something to address this. There's potentially a lot of user code out there that starts up normal Java threads, perhaps indirectly (e.g. message pumps and thread pools), and all such code will start to see stdio shut down.

I'm leaning toward keeping the current behavior intact but allowing you to call something to disable the automatic teardown we do, along the lines of `JRuby.teardown = false`. This would not be backward compatible but it would essentially fix this problem. It's then up to you to tear down the runtime yourself whenever "program exit" actually happens.

**Comment by monkstone** [comment]
I'm sure that ruby-processing could live with that sort of fix, but it may not be so happy for other edge cases.

**Comment by headius** [comment]
Actually I may have a good fix.

When the main script exits, we run Ruby.tearDown as described above. This goes through exit hooks and finalizable objects and makes sure they run.

However, stdio streams are marked as "prep" in MRI, which basically means we're not supposed to autoclose them. We have logic to avoid killing the descriptor when you *explicitly* close a "prep" stream, but we do not have logic to prevent all close-related state changes when that stream shuts down via a finalizer.

I believe that is a bug.

When finalizer runs, whether it is in response to Ruby teardown or in response to a dereferenced, GC-triggered finalization, the autoclose flag should still apply.

```diff
diff --git a/core/src/main/java/org/jruby/util/io/OpenFile.java b/core/src/main/java/org/jruby/util/io/OpenFile.java
index 746c6c7..eafcb6b 100644
--- a/core/src/main/java/org/jruby/util/io/OpenFile.java
+++ b/core/src/main/java/org/jruby/util/io/OpenFile.java
@@ -829,7 +829,7 @@ public class OpenFile implements Finalizable {
     };
 
     public void finalize() {
-        if (fd != null) finalize(runtime.getCurrentContext(), true);
+        if (fd != null && isAutoclose()) finalize(runtime.getCurrentContext(), true);
     }
 
     public void finalize(ThreadContext context, boolean noraise) {
```

I'm testing this locally now, and both your script and our tests seem to like it.

**Comment by monkstone** [comment]
I can confirm ruby-processing sketches now run OK with an installed jruby (jruby 9.0.0.0-SNAPSHOT (2.2.0p0) 2015-01-12 28d5c59 Java HotSpot(TM) 64-Bit Server VM 25.25-b02 on 1.8.0_25-b17 +jit [linux-amd64] I'm a using update-alternatives on Mint to control jruby version) yet to confirm with jruby-complete, that last time I tested seemed to be missing 'psych' gem.
