### ISSUE TITLE
crash during launch debug with netbeans-7.4 and jruby-1.7.13

### ISSUE THREAD

**Issue by innovTech** [jruby/jruby#1922]
I want to debug a very simple ruby script to read a file with csv library. It runs correctly in command line or launched by netbeans, without error or warning.
When launched by netbeans with debug mode, an exception occur before script launched:
Fast Debugger (ruby-debug-ide 0.4.22, ruby-debug-base 0.10.3.2) listens on 127.0.0.1:47070
7144: Exception in DebugThread loop: Bad file descriptor - Bad file descriptor
Backtrace:
org/jruby/RubyIO.java:2099:in `close'
  from: C:/jruby/jruby-1.7/lib/ruby/gems/shared/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/interface.rb:44:in`close'
  from: C:/jruby/jruby-1.7/lib/ruby/gems/shared/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide/ide_processor.rb:103:in `process_commands'
  from: C:/jruby/jruby-1.7/lib/ruby/gems/shared/gems/ruby-debug-ide-0.4.22/lib/ruby-debug-ide.rb:122:in`start_control'
  from: org/jruby/RubyProc.java:290:in `call'
  from: org/jruby/RubyProc.java:228:in`call'

The PC is under Windows 7 SP1, without firewall, with JAVA JDK-1.7U60_x86, jruby-1.7.13, netbeans-7.4 with plugin "ruby and rails" Version: 0.111. 
I installed in jruby, gems: ruby-debug (0.10.4), ruby-debug-base (0.10.4 java), ruby-debug-ide (0.4.22).

**Comment by kares** [comment]
sorry this got lost but since JRuby 1.7.x is EOL this really won't fix.
if anyone lands here please provide a (new) detailed report and make sure you're using latest JRuby.
