### ISSUE TITLE
jruby can't use it's own java classes

### ISSUE THREAD

**Issue by guai** [jruby/jruby#1925]
#jruby 1.7.13
```ruby
require 'jruby'
JRuby.runtime.defineReadonlyVariable('$var', proxied_java_object, Java::org.jruby.internal.runtime.GlobalVariable::Scope::GLOBAL)
```
This does not work. JRuby always tries to unwrap `proxied_java_object` to the core object even when `IRubyObject` is needed by itself.
It seems ConcreteJavaProxy#toJava should also check this condition:
```java
else if(type.isAssignableFrom(getClass())) {
			return this;
		}
```

**Comment by Lan5432** [comment]
Excuse me, but what's "proxied_java_object" supposed to be?

**Comment by guai** [comment]
It's the jruby's proxy object which wraps some java object. `proxied_java_object` implements `IRubyObject`.
And It can't be passed to method which expects `IRubyObject` param, because jruby first tries to unwrap the target java object out of it and pass it as argument.
