### ISSUE TITLE
Symlinks in load path should remain unexpanded in LOADED_FEATURES

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1941]
This is related to #1940.

When a load path contains an entry with an embedded symlink, JRuby will canonicalize LOADED_FEATURES entries through that symlink. This can lead to issues similar to bundler/bundler#3164, though that specific issue appears to be fixed by avoiding canonicalization of **FILE** (#1940).

We should try to iron out exactly how and when MRI expands absolute paths and canonicalizes through symlinks for JRuby 1.7.16, so we can put this to rest. We also need tests or specs for all permutations, because both MRI's suite and RubySpec are weak here.

**Comment by camlow325** [comment]
@headius Sorry for the late reply back on this one.  Unfortunately, the fix applied in JRuby 1.7.18 didn't appear to address the Puppet require reloading issue that I'd mentioned earlier in this thread.  I submitted a new issue, #2477, with a more specific example to demonstrate the issue.
