### ISSUE TITLE
bundle install --deployment doesn't include ffi

### ISSUE THREAD

**Issue by hawknewton** [jruby/jruby#1946]
Versions after 1.7.12 don't include ffi in vendor/bundle when `bundle --deployment` is run.  This means deployables that include ffi created by <=1.7.12 are not compatible with >1.7.12 runtimes.

I've created a repo illustrating the issue in greater detail [here](https://github.com/hawknewton/jruby-bundler-ffi-bug).

**Comment by kares** [comment]
defunct issue, default gems is handling these case
