### ISSUE TITLE
Strange issue with symbols

### ISSUE THREAD

**Issue by unyo** [jruby/jruby#1964]
Made an application with Sinatra, and running using MRI Ruby and JRuby. The below code works in MRI Ruby but not in JRuby. Does Ruby / JRuby handle symbol case differently? (erb :product_List vs :product_list).

If this is a non-issue, please feel free to close. I just noticed something strange when switching between two versions of ruby so I'm filing a report.

    get "/digital-signage" do
        @page_title = "Digital Signage"
        @division = Division.get('digital-signage')
        erb :product_List
    end
    # Product Lists - Generic
    get "/interactive-tv" do
        @page_title = "Interactive TV"
        @division = Division.get('interactive-tv')
        erb :product_list
    end

**Comment by rtyler** [comment]
@unyo I'm not sure I understand the issue you're having well enough. Can you provide a small sample app or a more complete reproduction case?

**Comment by unyo** [comment]
This issue no longer seems to occur
