### ISSUE TITLE
Error when raising to a BigDecimal 

### ISSUE THREAD

**Issue by benwoody** [jruby/jruby#1967]
When raising a FixNum to a BigDecimal, the operation errors claiming it expects a FixNum.

#### Repro:
Tested using `jruby 1.7.15 (1.9.3p392)`
```ruby
require 'bigdecimal/math'
a = BigDecimal(1.2, 2)
2 ** a
```

#### Output:
```ruby
TypeError: wrong argument type BigDecimal (expected Fixnum)
	from org/jruby/ext/bigdecimal/RubyBigDecimal.java:851:in `**'
	from org/jruby/RubyFixnum.java:723:in `**'
	from (irb):9:in `evaluate'
	from org/jruby/RubyKernel.java:1101:in `eval'
	from org/jruby/RubyKernel.java:1501:in `loop'
	from org/jruby/RubyKernel.java:1264:in `catch'
	from org/jruby/RubyKernel.java:1264:in `catch'
```

#### Expectations:
In MRI, this seems to be handled correctly, regardless of the type being raised. I would expect a BigDecimal to be returned from the equation.

**Comment by kares** [comment]
removed the incorrect failures (under >= 1.9) and implemented a helper that handles the [float remainder of the exponent using Java double arithmetics](https://github.com/jruby/jruby/commit/5c5b5cb3e24f507b4a03f1e67ea99b1307c3e85e) ... it's not as precise as e.g. in the integer exponent case but we're close and it's better than not raising and returning something unexpectedly inaccurate here ...
