### ISSUE TITLE
uninitialized constant OpenSSL::SSL::Session

### ISSUE THREAD

**Issue by rkh** [jruby/jruby#197]
When running `net-http-persistent` on SSL, without running into the [verification issue](https://github.com/jruby/jruby/issues/189), we run into `uninitialized constant OpenSSL::SSL::Session`

**Comment by kares** [comment]
this old beast is now also tracked at https://github.com/jruby/jruby-openssl/issues/26 ... for reference

**Comment by erichandsmith** [comment]
Successfully tested kares' [955f15a](https://github.com/jruby/jruby-openssl/commit/955f15ada23651f9a01cd2bf7be26e621611d903) jruby-openssl commit with persistent.rb.
