### ISSUE TITLE
1.7.14+ imposes intrusive jar-dependencies gem 

### ISSUE THREAD

**Issue by dekellum** [jruby/jruby#1974]
I was under the impression that the "default" gems shipped with the jruby distro where intented to still be opt-in, in the sense that a `require` or bundle dependency was needed to load them   This does not appear to be the case with the new "jar-dependencies" gem added as default in 1.7.14: I have no references to it in my projects but it appears to be injecting and running at least Gem.post_install hooks that are causing me some trouble (which I will elaborate in specific bugs.)  It may also be hooking into bundler?

This has me a bit disappointed because 1.7.14 should just be for bug fixes over 1.7.13.  Here you have made seemingly significant feature additions which have real and potentially more negative consequences.  #1965 and #1942 appear to demonstrate this already.

Can you offer a workaround for the 1.7.14 and 1.7.15 releases to disable this "default" jar-dependencies gem extension behavior at install and/or runtime?  I haven't found a way. I've been trying to delete various files listed in the jar-dependencies-0.0.9.gemspec to no avail.

We are unable to benefit from the other 1.7.14 and 1.7.15 bug fixes given this regression. The right thing to do from a release management perspective would be to back these associated jar-dependences changes out and release a 1.7.16 without them.  Uphold some modicum of semantic versioning and release this in a new feature release, e.g. 1.8.0 if you don't need to get cute with "9000".

**Comment by dekellum** [comment]
...add #3074 and #3078 to list of unintended regressions and consequences of jar dependencies. In the #3078 case at least, JARS_SKIP was not an available workaround to disable this extension.

**Comment by kares** [comment]
we might need to have the "hard" dependency  in jruby-openssl on by default to avoid bc.jar collisions ... these are quite annoying: https://github.com/jruby/jruby-openssl/issues/74 ... and there's no other way around them. 
please follow up on the issue and let us know if recent jar-dependencies is still causing you troubles. thanks.
