### ISSUE TITLE
Wrong number of reported lines in Coverage API

### ISSUE THREAD

**Issue by donv** [jruby/jruby#1981]
JRuby does not report commented and blank lines in the coverage api.  This leads to noisy and unreliable coverage reports.

Code used to reproduce:

```ruby
require 'coverage'
file_name = File.expand_path('dummy.rb')
File.write(file_name, "# Comment\n\n")
puts "Line count: #{File.readlines(file_name).size}"
Coverage.start
require file_name.chomp('.rb')
result = Coverage.result
puts "Coverage: #{result}"
puts "Coverage: #{result[file_name].size}"
```

MRI reports 2 lines, and JRuby fails to report the file at all.  JRuby should report 2 lines in the given file.

```
$ rvm use ruby
Using ~/.rvm/gems/ruby-2.1.2
$ ruby lines.rb 
Line count: 2
Coverage: {"/Users/uwe/workspace/TelenorGS/TelenorGS/dummy.rb"=>[nil, nil]}
Coverage: 2
$ rvm use jruby
Using /Users/uwe/.rvm/gems/jruby-1.7.15
$ ruby lines.rb 
Line count: 2
lines.rb:5 warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
Coverage: {}
NoMethodError: undefined method `size' for nil:NilClass
  (root) at lines.rb:9
```

Related issues:

* https://github.com/jruby/jruby/issues/1196
* https://jira.codehaus.org/browse/JRUBY-7118

**Comment by deivid-rodriguez** [comment]
Hi, has there been any progress here? I see the milestone has been modified to `9.0.0.0`.

Big thanks!

**Comment by deivid-rodriguez** [comment]
Ooops, the milestone was actually removed... so I guess I shouldn't expect this in `9.0.0.0`, right?

**Comment by donv** [comment]
Maybe this can be looked at for JRuby 9.1.0.0 ?

**Comment by enebo** [comment]
Ok I looked a few more minutes on this.  So one new piece of data is that TracePoint events DO NOT have anything to do with how simple_cov keeps track of this as:

```ruby
file_name = File.expand_path('dummy.rb')
File.write(file_name, "# Comment\n\n")
puts "Line count: #{File.readlines(file_name).size}"

trace = TracePoint.new() do |tp|
  puts "LINE: #{tp.path}:#{tp.lineno} - #{tp.event}" if tp.path =~ /#{file_name}/
end

trace.enable
require file_name.chomp('.rb')
```
will return no events at all for the empty file.  If you add a call or some actual code into the file then you see events.  So it is probably doing something else like perhaps using __SCRIPT_LINES__ or possibly something with loaded features to reparse the file somehow?  I guess looking at simple_cov support would be next.

**Comment by enebo** [comment]
heh...coverage:

```ruby
file_name = File.expand_path('dummy.rb')
File.write(file_name, "# Comment\n\nhash\n\n")
puts "Line count: #{File.readlines(file_name).size}"

require 'coverage'

Coverage.start
require file_name.chomp('.rb')
p Coverage.result
```

So it appears if we have code we create the result array.   This result array is nearly right, but there seems to be two related issues:

if I have code with no code and only empty lines (e.g. comments or whitespace) like '# c\n\n\n' then JRuby will return nothing at all.  Like the file does not exist.

If we have code but have trailing empty lines then the hash entry is made but the trailing lines are never added to the list.

**Comment by enebo** [comment]
@donv is going to look at adding some specs for this in ruby/spec.  The commit explains the base issue and how it was addressed.
