### ISSUE TITLE
Lambda converted to block treats 'return' like it's a proc

### ISSUE THREAD

**Issue by adz** [jruby/jruby#1985]
```
def test
  [1].map(&lambda{ |n| return -1 })
end
```

Calling #test will return [-1] in mri where-as jruby will return -1.  This seems to occur when converting a lambda to a block (the return now leaves the method not the lambda).

**Comment by kares** [comment]
```
jruby-1.7.24 :009 > def test
jruby-1.7.24 :010?>     [1].map(&lambda{ |n| return -1 })
jruby-1.7.24 :011?>   end
 => nil 
jruby-1.7.24 :012 > test
 => -1 

jruby-9.0.5.0 :001 > def test
jruby-9.0.5.0 :002?>     [1].map(&lambda{ |n| return -1 })
jruby-9.0.5.0 :003?>   end
 => :test 
jruby-9.0.5.0 :004 > test
 => [-1] 
```

**Comment by enebo** [comment]
Added info this bug is that 1.8 mode should return -1 and 1.9+ returns [-1].

**Comment by enebo** [comment]
Works on 9k.  1.7.x is EOL and this will not get fixed.  Marking WONTFIX

**Comment by Nakilon** [comment]
Marking WASNTFIXEDINTIME

**Comment by enebo** [comment]
@Nakilon well we did fix in one version of JRuby just not the older one.  Keep it classy now.  We can only support so much at a time...
