### ISSUE TITLE
SSL: ca_path not honored

### ISSUE THREAD

**Issue by tomekw** [jruby/jruby#2010]
Hi!

I've a web service over HTTPS with self-signed SSL certificate on CentOS 6.5. I can't connect to it securely when providing `ca_path` parameter with net/http and JRuby 1.7.16 (works with MRI Ruby 2.1.2):

``` ruby
require 'net/http'
require 'net/https'
require 'uri'

# Standard path on RedHat systems
ca_path = '/etc/pki/tls/certs'
url = URI.parse 'https://api.example.com'

http = Net::HTTP.new(url.host, url.port)
http.set_debug_output $stderr
http.use_ssl = (url.scheme == 'https')
if (File.directory?(ca_path) && http.use_ssl?)
  http.ca_path = ca_path
  http.verify_mode = OpenSSL::SSL::VERIFY_PEER
  http.verify_depth = 5
else
  http.verify_mode = OpenSSL::SSL::VERIFY_NONE
end
request = Net::HTTP::Get.new(url.path)
response = http.request(request)

puts response.inspect
```

Result:

```
certificate verify failed
```

It works when providing `ca_file = '/etc/pki/tls/certs/ca-bundle.crt'` instead (but adding self-signed certificates to the bundle is a bad idea...)

**Comment by kares** [comment]
this seems resolved, sorry for the delay!
