### ISSUE TITLE
Fibers should not be resumable across threads

### ISSUE THREAD

**Issue by headius** [jruby/jruby#202]
We do not properly prevent fibers from being resumed across threads. Here's a user-provided example:

https://gist.github.com/2889369

We produce "double resume" errors when we should produce "across threads" error.

Here's an attempt at a patch that does not appear to solve the problem: https://gist.github.com/2890071

**Comment by MSNexploder** [comment]
1.7.20 and 9.0.0.0.pre both produce correct "across threads" errors.

**Comment by headius** [comment]
Thanks for finding this one :-)
