### ISSUE TITLE
jruby 1.7.10 raises unexpected arity error (1 for 0) when creating a java.math.BigDecimal

### ISSUE THREAD

**Issue by peter-ryan** [jruby/jruby#2039]
When using the oracle enhanced adapter I ran into the following issue:

    ArgumentError: wrong number of arguments (1 for 0)
    activerecord-oracle_enhanced-adapter-1.4.2/lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb:426:in `ruby_to_java_value'
    activerecord-oracle_enhanced-adapter-1.4.2/lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb:313:in `bind_param'
    activerecord-oracle_enhanced-adapter-1.4.2/lib/active_record/connection_adapters/oracle_enhanced_adapter.rb:718:in `exec_insert'

Take a look at the [oracle enhanced adapters code](https://github.com/rsim/oracle-enhanced/blob/v1.4.2/lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb#L411-L439) but the exception is thrown from [here](https://github.com/rsim/oracle-enhanced/blob/v1.4.2/lib/active_record/connection_adapters/oracle_enhanced_jdbc_connection.rb#L426):

    java.math.BigDecimal.new(value.to_s)

`value.to_s` satisfies a `when String` test and takes no arguments.
`java.math.BigDecimal.new` does have 1 argument constructors.

This exception has occurred once in a production environment and has not been reproducible. This function is being passed a string and a symbol (in this particular case the string "114.0" and a symbol :decimal). Most of the time it works exactly as expected and creates a BigDecimal.

The error does not make any sense. Since the exception appears to originate from jruby and not java it seems like this must be a jruby bug although I have no idea what could be causing it. The code being run has not made any modification to String or java.math.BigDecimal

Our specific environment:

* jdk1.7.0_51
* jruby-1.7.10

**Comment by kares** [comment]
greetings, this is very likely related to Java integration's concurrent proxy class initialization ... which has been much improved in 1.7.20 and errors such as these are no longer expected. 
however if you do seem to reproduce with 1.7.20 (or later), please do let us know. thank you!
