### ISSUE TITLE
`bundle exec rake` is returning 1 in jruby-head

### ISSUE THREAD

**Issue by locks** [jruby/jruby#2044]
I'm testing one of my gems in *jruby-head* and it's failing. You can see it on Travis here: https://travis-ci.org/self-ml/selfml/jobs/37888329

**Comment by rtyler** [comment]
`jruby-head` means something different at different times, and in fact it looks like [jruby-head is now passing on this repo](https://travis-ci.org/self-ml/selfml/jobs/52988490) so I'm not entirely sure what the bug to fix is here.


Please re-open if you find a more specific failure scenario that we can triage
