### ISSUE TITLE
Use ExactMath for overflow

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#2056]
I was surprised to see that JRuby isn't using `ExactMath` anywhere. I believe these will be intrinsified in Java 8 u40 (http://openjdk.java.net/jeps/196) on behalf of Nashorn. They could replace your current bit testing methods to get a real `jo`.

**Comment by chrisseaton** [comment]
@headius I think you mentioned in a conference talk that you'd done this now?

**Comment by headius** [comment]
Yup, thanks for the ping.
