### ISSUE TITLE
Optional args that self-reference must resolve

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2124]
See https://bugs.ruby-lang.org/issues/9593

The cases in question are in mri/ruby/test_syntax and look basically like this:

```ruby
def foo(var = var) ...
def foo(var: defined?(var)) ...
```

...and so on. This will likely require parser changes. I am excluding test_keyword_self_reference and test_optional_self_reference now.

Note that test_keyword_self_reference actually triggers a Java exception inside IR:

```
TestSyntax#test_keyword_self_reference:
Java::JavaLang::ClassCastException: org.jruby.ir.operands.UndefinedValue cannot be cast to org.jruby.RubyBasicObject
    org.jruby.runtime.callsite.CachingCallSite.getClass(CachingCallSite.java:401)
    org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:125)
    org.jruby.ir.interpreter.Interpreter.processCall(Interpreter.java:360)
    org.jruby.ir.interpreter.Interpreter.interpret(Interpreter.java:595)
    org.jruby.ir.interpreter.Interpreter.INTERPRET_METHOD(Interpreter.java:697)
    org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:116)
    org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:255)
    org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
    org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
```

**Comment by headius** [comment]
Coming back to this, I don't think it's an IR issue (at least, it's not anymore)...I think it's a parsing issue.

If the RHS in `def foo(var = var)` parsed properly, as a local variable load, IR should fall in line and compile it just fine.

**Comment by enebo** [comment]
I should have commented on this a long time ago but minimal case for this is 'var = var'.  Opt arg is unrelated here.  This is something I have always considered as a bug in MRI so I never fixed it but perhaps I should...

**Comment by enebo** [comment]
I am removing 1.7 as support item here as I am starting to wind down on very unlikely to ever be fixed issues.  This has been fixed a while on 9000. Closing.
