### ISSUE TITLE
Failure to reject invalid float forms with proper message

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2126]
I believe this is a recent change. This case from mri/ruby/test_syntax should pass:

``` ruby
  def test_unexpected_fraction
    msg = /unexpected fraction/
    assert_syntax_error("0x0.0", msg)
    assert_syntax_error("0b0.0", msg)
    assert_syntax_error("0d0.0", msg)
    assert_syntax_error("0o0.0", msg)
    assert_syntax_error("0.0.0", msg)
  end
```

We do reject the first form, but our error message is wrong ("SyntaxError: -e:1: no .<digit> floating literal anymore; put 0 before dot"). I'm not sure about the others.

**Comment by enebo** [comment]
This appears to be have been resolved a while ago.
