### ISSUE TITLE
TestParse#test_named_capture_conflict

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2147]
Here's the failures:

```
[4130/5912] TestParse#test_named_capture_conflict = 0.00 s                                 
 36) Failure:
TestParse#test_named_capture_conflict [/Users/headius/projects/jruby/test/mri/ruby/test_parse.rb:870]:
Expected: /named capture conflict/
  Actual: "".
```

And here's the MRI commit for the *tests* at least: ruby/ruby@5129155a253293e96cacb83da0803aa1130e815e

I did not see the commit where they added these warnings. It could have been a long time ago, and they just started testing it recently.

**Comment by enebo** [comment]
Made new issue for the unused variable which surprisingly is much more work since it require use/def accounting.
