### ISSUE TITLE
BigMath.log fails MRI 2.2 tests

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2148]
The most recent tests from MRI trunk (2.2) fail on JRuby's BigMath.log with the following error:

```
  1) Error:
TestBigMath#test_log:
Math::DomainError: Math::DomainError
    file:/Users/headius/projects/jruby/lib/jruby.jar!/jruby/bigdecimal.rb:24:in `log'
    /Users/headius/projects/jruby/test/mri/bigdecimal/test_bigmath.rb:72:in `(root)'
    /Users/headius/projects/jruby/test/mri/bigdecimal/test_bigmath.rb:70:in `test_log'
```

The test can be run like this to reproduce:

```
jruby test/mri/runner.rb bigdecimal/test_bigmath.rb -n test_log
```

I will exclude this failure and reference this bug. We do have many other failures currently excluded; at some point we should make an effort to fix these :-\

It's possible some pass and no longer need to be excluded. I have not audited them in a while.

**Comment by kares** [comment]
expected to be fixed at #3221
