### ISSUE TITLE
Dir#glob does not return files with proper cases

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2150]
This appears to be a test for case-insensitive, case-preserving filesystems like HFS (non-case-sensitive mode), FAT32, NTFS and so on. We do not return the files with the proper case. This may be a simple fix, like absolutizing the filenames before we return them or something similar.

``` ruby
  def test_glob_cases
    feature5994 = "[ruby-core:42469] [Feature #5994]"
    feature5994 << "\nDir.glob should return the filename with actual cases on the filesystem"
    Dir.chdir(File.join(@root, "a")) do
      open("FileWithCases", "w") {}
      return unless File.exist?("filewithcases")
      assert_equal(%w"FileWithCases", Dir.glob("filewithcases"), feature5994)
    end
    Dir.chdir(File.join(@root, "c")) do
      open("FileWithCases", "w") {}
      mode = File.stat(".").mode
      begin
        File.chmod(mode & ~0444, ".")
        return if mode == File.stat(".").mode
        assert_equal(%w"filewithcases", Dir.glob("filewithcases"), feature5994)
      ensure
        File.chmod(mode, ".")
      end
    end
  end
```

Failure:

```
TestDir#test_glob_cases [/Users/headius/projects/jruby/test/mri/ruby/test_dir.rb:238]:
[ruby-core:42469] [Feature #5994]
Dir.glob should return the filename with actual cases on the filesystem.
<["FileWithCases"]> expected but was
<["filewithcases"]>.
```

Test can be run with `jruby test/mri/runner.rb ruby/test_dir.rb -n test_glob_cases`

**Comment by groddeck** [comment]
@kelcecil - took me a minute to figure that out also, but check out the lines in each section beginning with ```return```.  These ensure that different parts of the test only apply to certain filesystem types.

In the first section, a file named ```FileWithCases``` is created, and then ```return unless File.exist?("filewithcases")``` will skip this test unless the filesystem says that, yes, a file with that name does exist.  If ```File.exist?``` returns true for the all-lowercase name, even though the file was created with camel-case, we have verified that we are on a case-insensitive, case-preserving filesystem type, and proceed.

In the next section, to be honest, I don't understand how the check works, but, it appears to check whether an attempt to change the file mode of the current directory results in a change or not.  If the mode is preserved after the attempt, the test halts: ```return if mode == File.stat(".").mode``` . I assume this somehow determines if this is the type of filesystem where the following assertion should hold.  In this scenario, searching for files matching the glob pattern is supposed to return a list of files that *doesn't respect the case of the original file name*.  In other words, this type of filesystem is case-insensitive, and also NON-case-preserving, in contrast to the fs type scenario in the first section of this test case, above.

Clearly, both assertions cannot be true, and so the apparent intent of this case is to only allow any applicable assertion to be evaluated, given the filesystem type that the test suite is being executed on.

Again, I'm not 100% certain of how it works or why, but I'm fairly certain this is meant to check for different behaviors on different systems.

**Comment by edipofederle** [comment]
@enebo can we close this one?

**Comment by enebo** [comment]
Yep forgot to do this.
