### ISSUE TITLE
Frozen string literal should be a new object if String#freeze is redefined

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2156]
I added "foo".freeze support recently, but I did not put in a check if String#freeze has been overridden. That leads to a failure in this test from ruby/test_optimization.rb:

``` ruby
  def test_string_freeze
    assert_equal "foo", "foo".freeze
    assert_redefine_method('String', 'freeze', 'assert_nil "foo".freeze')
  end
```

I consider this a beginner bug for the interpreter, but a bit more JVM smarts will be required to fix the compiler.

**Comment by hd719** [comment]
Hello there! I am new to open source and I would like to contribute to this project.

**Comment by headius** [comment]
Also affects new `String#-@` optimization in 2.5.

**Comment by headius** [comment]
@PurityLake This will probably require some minor changes to the IR compiler (IRBuilder) to produce an instruction rather than an operand. The existing logic compiles this as a FrozenString operand which should not (must not?) have side effects like actually calling `String#freeze`.

Since this form is somewhat archaic now and most users have switched to using the frozen-string pragma, I think it would be best to compile this as a new instruction or a CallInstr subtype that either makes the dynamic call to `freeze` or directly returns the frozen string object (which should still be cached).

@enebo Thoughts here?

**Comment by headius** [comment]
The option added in #6894 is the workaround for this, in that it turns off the `"foo".freeze` compile-time optimization. No further work is planned here.
