### ISSUE TITLE
Hash inspection not working as in MRI for sprintf %p

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2161]
The test that's failing in mri/ruby/test_sprintf.rb:

``` ruby
  def test_hash
    options = {:capture=>/\d+/}
    assert_equal("with options {:capture=>/\\d+/}", sprintf("with options %p" % options))
  end
```

The failure:

```
ArgumentError: positional args mixed with named args
    org/jruby/RubyString.java:1221:in `%'
    /Users/headius/projects/jruby/test/mri/ruby/test_sprintf.rb:173:in `test_hash'
```

We do have code that raises this error around Sprintf.java:154 in Sprintf::Args#next, but I was not able to figure out the equivalent code in MRI (it doesn't seem to be there in the GETNEXTARG macro in sprintf.c nor in the logic for `case 'p'` in the main switch) nor does the test itself indicate where/when the change to sprintf was actually made.

**Comment by uchagani** [comment]
This is still failing as of jruby 9.0.5.0 (2.2.3).

**Comment by denyago** [comment]
This is still failing as of jruby 9.1.7.0 (2.3.1) 😿

**Comment by enebo** [comment]
Added test to spec in e66f6385da ... I think @eregon will still merge this back upstream?

**Comment by headius** [comment]
@enebo That's a good question. @eregon: Do we need to take over upstreaming our ruby/spec changes?

**Comment by eregon** [comment]
@enebo @headius I can keep doing it, no worries.
It's convenient since I merge from all repos and then update them all.
I did the last merge about 2 weeks ago.
I might ask your help for tagging new failures if it's not trivial though :)
