### ISSUE TITLE
Truffle: Kill all other threads when the main thread exists

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#2165]
Truffle currently has Java semantics where if the main thread exits, other threads just continue to run. We need the Ruby semantics where the main thread exiting will kill other threads. See the implementation of `Thread#kill` (in the `ThreadNodes` class) for a way to do this without any overhead.

**Comment by eregon** [comment]
This was fixed by my commit 491618f1c16c691a68c18cafe01a7b134b966eac.
