### ISSUE TITLE
Timeout broken when stuck in EPOLL_WAIT

### ISSUE THREAD

**Issue by cheald** [jruby/jruby#2171]
0695f3aa2c3d47ec2c46d67bf2793aab9c896219 broke something such that the `test_readpartial` tests no longer pass; they hang indefinitely as the Timeout block seems to not fire. jstack shows the process is in EPOLL_WAIT.

**Comment by kares** [comment]
*test/mri/ruby/test_io.rb*'s **test_readpartial** is running fine these days on CI
