### ISSUE TITLE
A lot of files without "_spec.rb" suffix in the spec directory exist.

### ISSUE THREAD

**Issue by k77ch7** [jruby/jruby#2174]
A lot of files without "_spec.rb" suffix in the *spec* directory exist. These files don't run at travis-ci. For example, *GH-1446_line_number_in_warnings.rb* don’t run in the "spec:regression" task. The cause of this is the definition of the pattern in the *rakelib/rspec.rb*.
https://github.com/jruby/jruby/blob/master/rakelib/rspec.rake#L52

**Comment by headius** [comment]
Fixed the last two files mentioned in c3d9dea.
