### ISSUE TITLE
Input problems when calling system()

### ISSUE THREAD

**Issue by danjo830** [jruby/jruby#2189]
There seems to be problems with the method Kernel#system.
For example, when running this in ruby the user is prompted for a password for the Administrator user in the console, before opening a new command prompt:
`system("runas /user:Administrator cmd")`
Jruby prints the password prompt but does not wait for any input.

Another example:
`system("set /p pathName=Enter Input:")`
For this Jruby waits for input, but the entered text is not shown until enter is pressed. Then a second press on enter is required to continue.

I've tried this on Windows 8 with JRuby 1.7.16.1

**Comment by kares** [comment]
unfortunately, seems this got left behind ... 
but since JRuby 1.7.x has EOL-ed anyone landing here please try latest JRuby 9K with a fresh report.
