### ISSUE TITLE
test/jruby/test_file.rb fails but passes when run in complete test-suite

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#2190]
looks like the test_require_from_jar_url_with_spaces_in_load_path uses some script names from some other tests or so.

this fails
```
bin/jruby test/jruby/test_file.rb 
```
but this succeeds:
```
ant test-extended
```
or the equivalent on master branch.

the failing bit is something which the new loadService does provide. it may or may not be a regression of the big loadService refactoring.

**Comment by kares** [comment]
believe these were ironed out at some point - closing as no longer a valid issue.
