### ISSUE TITLE
OpenSSL::SSL::SSLSocket + IO::select hangs sometimes

### ISSUE THREAD

**Issue by jordansissel** [jruby/jruby#2195]
Under MRI, the following code will result in fetching https://www.google.com/. The last two lines are "0" and blank (chunked transfer encoding over http).

However, under JRuby (tested JRuby 1.7.16.1 and 1.7.9), this hangs.

Under MRI, it successfully reads the full HTTP request and the last line output (bytes read) is 52460. However, under JRuby, it hangs in IO::select after about the 30th iteration, but is nondeterministic in behavior (though the nondeterminism may be due to Google's webservers varying its responses and variations in TCP timing).

Jruby last output example:

```
29: 39149
30: 40542
31: 41935
```

In general, JRuby gets about 30 or 31 iterations (IO::select + sysread), and around 38kb-40kb of data before the next IO::select blocks forever.

If I change the timeout in IO::select to be 1 second instead of nil, the IO::select will time out after 1 second _AND_ the next sysread() will give me data.

Full code:

``` ruby
require "socket"
require "openssl"

s = TCPSocket.new("www.google.com", 443)
o = OpenSSL::SSL::SSLSocket.new(s)
o.connect

o.write("GET / HTTP/1.1\r\n")
o.write("Host: www.google.com\r\n")
o.write("\r\n")
o.flush()

bytes = 0
count = 0
data = ""
while true
  count += 1
  r, w, e = IO.select([o], nil, nil, nil)
  data <<  o.sysread(16384)
  puts "#{count}: #{data.bytesize}"
  # Chunked encoding break
  break if data =~ /0\r\n\r\n$/m
end
```

**Comment by driskell** [comment]
@jordansissel Hello! This is fairly old but I was researching non-blocking.
I think in your test though it is likely wanting to write due to a key exchange, which can sometimes happen in the middle of a read. So you should `IO.select([o], [o], nil, nil)` just to be sure.

**Comment by jordansissel** [comment]
@driskell yeah I remember that being necessary when using OpenSSL from C, but in C we're doing select on the fd, not the openssl object as we are in Ruby, so I"m not sure - you might be totally right! :P

It's been a while, so my memory is fuzzy. I'll revisit this soon :P

**Comment by kares** [comment]
`IO.select([o], [o], nil, nil)` like a charm and original `select` also completes after a while
