### ISSUE TITLE
Yaml containing escaped single quote fails to parse, works under MRI

### ISSUE THREAD

**Issue by camertron** [jruby/jruby#2199]
Running JRuby in ruby 2.0 mode:

```
$> require 'yaml'
$> YAML.load('"foo\\\'bar"')
Psych::SyntaxError: (<unknown>): found unknown escape character '(39) while scanning a double-quoted scalar at line 1 column 6
```

Running MRI 2.0:

```
$> require 'yaml'
$> YAML.load('"foo\\\'bar"')
=> "foo'bar"
```

**Comment by headius** [comment]
Guess it's not a YAML 1.1 thing, since Ruby 2.3.2 handles it fine.

**Comment by headius** [comment]
Reported to SnakeYAML here: https://bitbucket.org/asomov/snakeyaml/issues/350/failure-to-parse-escaped-single-quote-in-a

**Comment by asomov** [comment]
According to the YAML 1.1 spec the \'  is not a valid escape sequence
http://yaml.org/spec/1.1/#id872840
I did not quite catch how it works in MRI.

**Comment by asomov** [comment]
What is the bug tracker for  MRI 2.0 to report a bug while parsing YAML ?

**Comment by headius** [comment]
Closing in favor of #4847.
