### ISSUE TITLE
?? instead of chars like á,é,ő,ű etc. in irb

### ISSUE THREAD

**Issue by Allanon29** [jruby/jruby#2204]
Hi Guys,

I need to be able to show the chars in the title properly in irb however right now it displays only ?? instead. 
OS: Centos 7, but the same thing happens on Centos 6.5
The encoding of the OS is set to hu_HU.utf8 
I also tried to encoding external, and encoding internal in .jrubyrc to UTF-8 and 8859-2 but the issue is still the same.
I tried ruby 2.1.5 and this issue is not present there. It shows the chars properly. 

Is this a bug?

**Comment by headius** [comment]
No followup since 2016, but likely fixed by @enebo's symbol work last year. Calling it invalid, since there were other more specific bugs also fixed by that work.
