### ISSUE TITLE
poor error message when unable to create parent class

### ISSUE THREAD

**Issue by rdp** [jruby/jruby#2243]
ex:
install ubuntu, install default-jre-headless

run this:

https://gist.github.com/rdp/b25a0483c196c856c33a

require 'java'

class A < javax.swing.JFrame

def initialize _args
super(_args)
end
end

A.new 

expected output:

Java::JavaAwt::HeadlessException exception (which is generated with a straight javax.swing.JFrame.new call)

current output:

jruby  ArgumentError: Constructor invocation failed: null

it's like the real error message is being masked.

possibly not a high prio, but thought I'd mention it.

**Comment by kares** [comment]
gist version runs fine on 9K (exits), while your piece here fails as expected with a
```
ArgumentError: wrong number of arguments (0 for 1)
```
... which is expected since the argument is not provided.

assuming this is resolved with the updated JI overload method matching, for 1.7.x is won't fix.
