### ISSUE TITLE
hangs on regexp match

### ISSUE THREAD

**Issue by guai** [jruby/jruby#2246]
jruby 1.7.13, 1.7.16.1
win 8
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

This regexp hangs when trying to match contents of this file https://www.dropbox.com/s/5r87ytz7cr0bkqh/PollerConfigurationProvider.ru?dl=0

``` ruby
text = File.open(file, 'r:utf-8') { |f| f.read }
text =~ /^\s*methods (:\w+[\s\S]+?^\s*:nothing => '')/im
```

As you can see it wont match. `nothing => ''` in regexp vs `:nothing => %{}` in the file. When I change to `:nothing => ''` in the file, then regexp matches fine. But when does not match, it hangs.
jvisualvm shows that it does something inside org.joni.ByteCodeMachine#matchAt method

**Comment by guai** [comment]
It hangs forever not seconds not minutes. So Its really a bug.
Any code that accepts regexes from user code can be made fall

**Comment by enebo** [comment]
Yes, but with the right regexp I believe I can make any engine run forever (which in truth is not forever but a really really really long time).  Joni has an internal bytecode format so it may be possible to put in a stop if you have run n instructions, but that is not really a solution for someone running a very long regexp intentionally.
