### ISSUE TITLE
Add unlimited strength cryptography to JRuby Rails template

### ISSUE THREAD

**Issue by donv** [jruby/jruby#2251]
Rails will not start under JRuby with Java 8 unless you either download and add some JARs from a ZIP (from Oracle) file or add the following initializer:

```ruby
if RUBY_PLATFORM == 'java' # Allows the application to work with other Rubies if not JRuby
  require 'java'
  java_import 'java.lang.ClassNotFoundException'

  begin
    security_class = java.lang.Class.for_name('javax.crypto.JceSecurity')
    restricted_field = security_class.get_declared_field('isRestricted')
    restricted_field.accessible = true
    restricted_field.set nil, false
  rescue ClassNotFoundException => e
    # Handle Mac Java, etc not having this configuration setting
    $stderr.print "Java told me: #{e}n"
  end
end
```

Adding the initializer should be done by the JRuby Rails template.

**Comment by headius** [comment]
I personally would love to do this in JRuby's own bootstrap code, but I have to wonder what sort of trouble we'd get into explicitly routing around the crypto restrictions. DMCA?

**Comment by headius** [comment]
Well this might answer my question: https://twitter.com/xranby/status/590944882564456448

@enebo I vote we add this hack to our boot logic for both JRuby 1.7 and 9k.

**Comment by nirvdrum** [comment]
For historical note, I believe this came up before and sidetracked for whatever reason.  @mkristian wrote a simple gem to work around the problem:

https://rubygems.org/gems/unlimited-strength-crypto

**Comment by kares** [comment]
JRuby has been handling this for a while now (as well as recently https://github.com/jruby/jruby/issues/4101)
