### ISSUE TITLE
Investigate using Jenkins for pull request testing

### ISSUE THREAD

**Issue by rtyler** [jruby/jruby#2263]
[Using the Redhat Jenkins Enterprise](https://projectodd.ci.cloudbees.com/view/JRuby/) we should investigate using Jenkins for pull request testing on multiple platforms to see whether we can get more reliable results than what we're seeing in Travis

**Comment by kares** [comment]
hehe ... @rtyler its time to get things done :trollface: :hear_no_evil:

**Comment by kares** [comment]
dead-duck

**Comment by rtyler** [comment]
quack. thanks for closing @kares
