### ISSUE TITLE
TypeError during DB migration with jruby-head on travis-logs

### ISSUE THREAD

**Issue by BanzaiMan** [jruby/jruby#2267]
https://travis-ci.org/travis-ci/travis-logs/jobs/42786675#L188

```
TypeError: class or module required for rescue clause. Found: %undefined
```

Looks like it is using sequel 4.0.0. (See [`Gemfile.lock`](https://github.com/travis-ci/travis-logs/blob/05a38c8/Gemfile.lock).)

**Comment by kares** [comment]
seems like this has since been addressed. feel free to re-open if I am by any chance wrong here ...
