### ISSUE TITLE
[Jruby-9k] Java::JavaLang::StackOverflowError when running bundle install

### ISSUE THREAD

**Issue by electrical** [jruby/jruby#2272]
With the logstash project we are trying out Jruby-9.0.0.0
One of our tasks is failing with the latest available build.

Version: jruby 9.0.0.0.dev-SNAPSHOT (2.2.0p0) 2014-11-18 0cfdfe5
Trace: https://gist.github.com/electrical/ad1917c0469c7dee3b68

Repo steps:
1. rbenv/rvm set to jruby snapshot
2. git clone https://github.com/elasticsearch/logstash
3. `USE_RUBY=1 rake bootstrap` in the logstash project

**Comment by enebo** [comment]
@electrical Is this still the same instructions?  I can run this on my machine now but I see a 1.7.20 DL so I think you may have worked around this internally somehow...

**Comment by electrical** [comment]
Hi @enebo Its something we tried out ages ago but in the meantime updated jruby 9k and haven't seen these issues anymore.
Completely forgot to close this, sorry about that :-)

**Comment by enebo** [comment]
@electrical  np.  Just reviewing things still marks for 9k.
