### ISSUE TITLE
RubyGems 2.4.5 Upgrade Triggers Bug in Java Extension Loading

### ISSUE THREAD

**Issue by bbrowning** [jruby/jruby#2336]
RubyGems 2.4.5 has some new logic that sometimes (but not always - depends on what's already loaded or not) expands require statements to absolute paths before passing them on to the original require.

Depending on the state of things, it's possible for a require statement to hit this line of code in RubyGems - https://github.com/rubygems/rubygems/blob/v2.4.5/lib/rubygems/core_ext/kernel_require.rb#L69. That code expands the thing being required to an absolute path before handing it off to the original require logic.

So, when a .jar is required via an absolute path, the logic in ClassExtensionLibrary at https://github.com/jruby/jruby/blob/613673ae6ee2076c93264daad6d99826221352d9/core/src/main/java/org/jruby/runtime/load/ClassExtensionLibrary.java#L67 ends up creating the wrong package name and thus cannot load the *Service class for the Java extension. The searchName string passed to ClassExtensionLibrary's tryFind ends up looking something like "/path/to/nokogiri/nokogiri.jar" and it converts that to the class path.to.nokogiri.NokogiriService, which obviously can't be found.

Here's a gist that demonstrates this problem against JRuby 1.7.18-SNAPSHOT - https://gist.github.com/bbrowning/cda2606bd26683ea4831

**Comment by enebo** [comment]
This is still causing double loads and I reverted from 1.7.19.

**Comment by mkristian** [comment]
@enebo do you remember where/how you did see those double loads ?

**Comment by headius** [comment]
This has been fixed more betterer in recent weeks and RG 2.4.5+ seems to work well now.
