### ISSUE TITLE
Is there a way to declare `java_field` with interface type?

### ISSUE THREAD

**Issue by vladson** [jruby/jruby#2337]
Trying to do as following:
  ```
    class A
       java_field 'java.util.List clients'
    end
```

And getting `TypeError: cannot convert instance of class org.jruby.RubyModule to class java.lang.Class`
As far as I managed to understand, it is due to InterfaceJavaProxy.
In my example I managed to get rid of declaring interface type, but it may be needed anyway. Maybe I can help? Where should I start digging?

**Comment by rtyler** [comment]
This works in JRuby 9.0.0.0, at least with the code provided. If you still experience an issue with 9k, please re-open this ticket with some more details so we can help :)

```
[10] pry(main)> class A    
[10] pry(main)*   java_field 'java.util.List clients'       
[10] pry(main)* end      
=> nil
[11] pry(main)> JRUBY_VERSION
=> "9.0.0.0"
[12] pry(main)> 
```
