### ISSUE TITLE
Cannot run rubygems on windows

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#2346]
```text
C:\opt\jruby>bin\jruby -S gem list
LoadError: no such file to load -- rubygems
  require at org/jruby/RubyKernel.java:1027
   (root) at C:/opt/jruby/bin/jgem:8
     load at org/jruby/RubyKernel.java:1046
   (root) at C:/opt/jruby/bin/gem:4
```

**Comment by ahorek** [comment]
jruby 9.0.0.0-SNAPSHOT (2.2.0p0) 2015-01-05 6e85813 Java H
er VM 25.25-b02 on 1.8.0_25-b18 +jit [Windows 8.1-amd64]

NotImplementedError: open unsupported or native support failed to load
           read at org/jruby/RubyIO.java:3574
           load at C:/moje/projekty/jruby/jruby/lib/ruby/stdlib/rubygems/specifi
cation.rb:1037
      each_spec at C:/moje/projekty/jruby/jruby/lib/ruby/stdlib/rubygems/specifi
cation.rb:739
   each_gemspec at C:/moje/projekty/jruby/jruby/lib/ruby/stdlib/rubygems/specifi
cation.rb:725
           each at org/jruby/RubyArray.java:1567
   each_gemspec at C:/moje/projekty/jruby/jruby/lib/ruby/stdlib/rubygems/specifi
cation.rb:724
           each at org/jruby/RubyArray.java:1567
   each_gemspec at C:/moje/projekty/jruby/jruby/lib/ruby/stdlib/rubygems/specifi
cation.rb:723
      each_spec at C:/moje/projekty/jruby/jruby/lib/ruby/stdlib/rubygems/specifi
cation.rb:738
  load_defaults at C:/moje/projekty/jruby/jruby/lib/ruby/stdlib/rubygems/specifi
cation.rb:772
         (root) at C:/moje/projekty/jruby/jruby/lib/ruby/stdlib/rubygems.rb:1233

        require at org/jruby/RubyKernel.java:954
         (root) at file:/C:/moje/projekty/jruby/jruby/lib/jruby.jar!/jruby/kerne
l/rubygems.rb:1
           load at org/jruby/RubyKernel.java:969
         (root) at file:/C:/moje/projekty/jruby/jruby/lib/jruby.jar!/jruby/kerne
l/rubygems.rb:4

**Comment by headius** [comment]
Looks good in commits leading up to a2ef35f.
