### ISSUE TITLE
Java exceptions do not propagate out of Thread#join

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2354]
From http://jira.codehaus.org/browse/JRUBY-7129

Joining a thread that died from a normal Ruby error will kill the parent thread, as expected.  The "should not be here" text is never printed:

```
$ jruby -e "Thread.new{raise 'error'}.join; puts 'should not be here'"
RuntimeError: error
  (root) at -e:1
```

However, if the thread died from a raw Java error, joining the thread only prints a trace, and the "should not be here" text is printed.

```
rcrogers@proc1-ss1.dev:~/statsheet$ jruby -e "Thread.new{a = []; loop{a << 'word'}}.join; puts 'should not be here'"
Exception in thread "RubyThread-1: -e:1" java.lang.OutOfMemoryError: Java heap space
    at org.jruby.RubyString.newStringShared(RubyString.java:571)
    [...]
    at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:98)
    at java.lang.Thread.run(Thread.java:679)
should not be here
```

Still fails on 1.7 and 9k heads.

**Comment by rtyler** [comment]
I'm pretty sure I've experienced this behavior when working with native Java libraries, going to see if I can convince @mkristian to fix it :D

**Comment by andreaseger** [comment]
Any update on this? I can still see this happening and causing weird issues

**Comment by headius** [comment]
This turned out to be easier to fix than it used to be, so I went ahead with it. Java exceptions that bubble out of Ruby threads will now behave like Ruby threads as regards Thread#join, Thread#value, and other exception-aware methods of Thread.
