### ISSUE TITLE
NULL handling inconsistent with Ruby

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2357]
From http://jira.codehaus.org/browse/JRUBY-6247

NULL handling in filenames is inconsistent with Ruby, which exposes JRuby apps to NULL injection attacks:

```
$ echo 'require "uri"; p File.new(URI.decode("/etc/hosts%00"), "r").gets'|ruby
-:1:in `initialize': string contains null byte (ArgumentError)
	from -:1:in `new'
	from -:1:in `<main>'

$ echo 'require "uri"; p File.new(URI.decode("/etc/hosts%00"), "r").gets'|./jruby
"127.0.0.1\tlocalhost\n"
```

**Comment by lumeet** [comment]
Didn't notice this one before but it seems to fixed by #2583, too.

**Comment by enebo** [comment]
@lumeet I guess to solve this we need fixes for jruby-1_7 as well.

**Comment by mkristian** [comment]
f41b6d9e38741292a3b274be54b1686b1dc4bd5d cherry-picks #2583 into jruby-1_7 and adds missing bits from StringSupport from master.
