### ISSUE TITLE
How to run jruby-tests in java? 

### ISSUE THREAD

**Issue by AlBundy33** [jruby/jruby#2358]
``` jruby
require 'test/unit'
class SimpleTest < Test::Unit::TestCase
  def test_simple
    assert(false,"oh no....")
  end
end
```

If I run my rb-file on commandline with ruby.exe the TestCase is executed.
But if I run the script in java via JRubyEngineFactory().getScriptEngine() nothing happens.
Is there a way to automatically run the TestCase?

**Comment by kares** [comment]
its an architectural problem of how test libraries work when you simply run a .rb file ...
they tend to load all tests and `at_exit` actually perform the run (test/unit, minitest do this). 
thus you would need to initiate a teardown if you're expecting to run them (or trigger the `run` manually).
