### ISSUE TITLE
String#to_i slower than MRI when trailing garbage

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2360]
From http://jira.codehaus.org/browse/JRUBY-5620

The rough perf numbers reported toward the end of that bug show that only the trailing-garbage case of String#to_i still runs slower than other impls, and it does so due to a wasted BigInteger along the way. I file it here because it is still an issue and probably can be improved pretty easily.

The benchmark from that bug is still valid, but may have updates in the Rubinius repository.

**Comment by Who828** [comment]
Looking into it.

**Comment by headius** [comment]
Fixed by #2464.
