### ISSUE TITLE
Kernel.load(..., true) --> scope problem

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2374]
From http://jira.codehaus.org/browse/JRUBY-6738

Early versions of MRI 1.9.2 had a "scope" problem when Kernel.load was used with a "true" second parameter. I reported it as

```
http://bugs.ruby-lang.org/issues/1982
```

JRuby seem to fail in the same way (both in 1.8 and 1.9 mode). I attach a script showing the problem. JRuby reports:

```
$ jruby -e 'load "helloworld.rb", true' 
NameError: uninitialized constant #<Module:0x4a005364>::HelloWorld::Hello
  const_missing at org/jruby/RubyModule.java:2715
            say at /Users/johan/proj/rcons-stuff/rcons-cpp/helloworld.rb:17
         (root) at /Users/johan/proj/rcons-stuff/rcons-cpp/helloworld.rb:21
           load at org/jruby/RubyKernel.java:1017
         (root) at -e:1
```

but if run with the second paramter set to "false" it works better:

```
$ jruby -e 'load "helloworld.rb", false'
Hello
World
```

I think it should have worked in the first case too.

**Comment by MSNexploder** [comment]
Works as expected using 9.1.10.0:

```
jruby -e 'load "helloworld.rb", true'
Hello
World
```

```
jruby -e 'load "helloworld.rb", false'
Hello
World
```
