### ISSUE TITLE
JRuby subclass cannot call super with arguments if parent constructor is varargs

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2375]
From http://jira.codehaus.org/browse/JRUBY-6656. See that issue for attached reproduction files.

I subclass a Java class that has a varargs constructor in JRuby, the JRuby class attempts to call super(a,b) to invoke the superclasses constructor and this fails with:
ArgumentError: wrong number of arguments for constructor
  initialize at varargsctor.rb:6
      (root) at varargsctor.rb:11
Invoking super(nil) works, but super() and super(a,b) fail.
Sample Java class and JRuby subclass attached.

**Comment by kares** [comment]
landed on **jruby-1_7** as https://github.com/jruby/jruby/commit/03ed29a90879244a0989c43338dc8233aa7f3ec7 and https://github.com/jruby/jruby/commit/5fa2cb144e53dd6d4532f3b8ea1446515ce9a49b ... in a nutshell we now mark the generated proxy var-arg constructors with an annotation so we can resolve them wrapping an underlying var-arg invocation
