### ISSUE TITLE
Can't break a thread by raising exception from main thread if there is "readline" in thread

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2383]
From http://jira.codehaus.org/browse/JRUBY-5723. Problem with using jline for readline. May be time to look at an alternative readline backend.

Hi,

Normally, I can raise exception in some thread from main/other thread by some_thread.raise() and then rescue it in that above mentioned thread. This is useful when we need to break execution of some_thread on some event.
In jruby there is a problem if some_thread have readline method and waiting for input. It stucks in readline until it receives \n. 
This works ok under ruby-mri (both 1.8.7 and 1.9.2).
For example, I want to close from another thread some connection threads in GServer's implementation on some events. That connection threads are stuck in waiting input (readline) and can't close connection until io timeout.
I applied a test file, which you can run under jruby (and you will see that it's stuck and you have to press ENTER to exit) and ruby-mri where it exits automatically.

Regards,
Dilshod

**Comment by colinsurprenant** [comment]
we are also facing this situation in logstash see elastic/logstash#1769 in particular when reading stdin. my assessment is that doing blocking read on stdin in a thread in Java NIO is just non-interruptible, and stdio in general is not selectable in Java NIO and `IO.select([$stdin], nil, nil, 0)` in JRuby will not work as intended...

**Comment by headius** [comment]
I'd like to hear how rb-readline works for folks under JRuby. It depended on features we couldn't support in JRuby 1.7.19 (like having real file descriptors and tty access for stdio) but it may work well under JRuby 9k (which has rewritten IO to use more native functionality).

**Comment by headius** [comment]
FWIW, IO.select and friends should all work well against stdio streams in JRuby 9k.

**Comment by colinsurprenant** [comment]
nice, I will give it a spin in 9k and report back.

**Comment by e2** [comment]
I thought an `ioctl` like this would also work on JRuby, but the ioctl is never sent:

```ruby
require 'readline'

th = Thread.new { Readline.readline.inspect }

TIOCSTI=0x00005412

Thread.new do
  sleep 2
  File.new(`tty`.chomp).ioctl(TIOCSTI, "\x04")
  STDERR.puts "sent!" # never gets here
end

th.join.inspect # hangs here
STDERR.puts "Never gets here... ;("
```

**Comment by headius** [comment]
I don't think we've done a fully-native implementation of ioctl yet, but it probably wouldn't be difficult to add to https://github.com/jnr/jnr-posix.

**Comment by colinsurprenant** [comment]
FYI, as a workaround to get an interruptible stdin (to hopefully integrate in the logstash stdin input plugin, see  elastic/logstash#1769) I've created this gem https://github.com/colinsurprenant/jruby-stdin-channel - works with Java 8.

**Comment by perlun** [comment]
Is this still active on JRuby 9k?

**Comment by headius** [comment]
This issue has kinda strayed from the original report, which was that readline blocked interrupts due to the way that jline (our underlying readline library) handles console IO. If there are other issues with interrupting stdio that are NOT related to readline, they should be opened as separate issues (if they haven't been already).

readline is still a problem, because we still depend on jline. rb-readline has been tested and works reasonably well with JRuby 9k provided you [patch it a bit](https://github.com/jruby/jruby/issues/3721#issuecomment-245608240).

See #3721 and #4141 for other terminal issues with our jline-based readline.

**Comment by nbekirov** [comment]
Hello!

I was wondering if this code reproduces the same issue (or should I open a new one):

```ruby
begin
  IO.pipe do |r, w|
    Thread.new { IO.copy_stream(r, StringIO.new, 4) }

    puts 'Raising...'
    sleep 0.1
    raise 'Something went wrong!' # Hangs here
  end
rescue => e
  puts "Error message is '#{e.message}'" # Never gets here
end
```

Expected:
```bash
$ rvm use ruby-2.4.4
Using /Users/nikolay.bekirov/.rvm/gems/ruby-2.4.4

$ ruby test.rb
Raising...
Error message is 'Something went wrong!'
```

Actual (script does not terminate):
```bash
$ rvm use jruby-9.2.11.0
Using /Users/nikolay.bekirov/.rvm/gems/jruby-9.2.11.0

$ ruby test.rb
Raising...
```

Please advise.

**Comment by headius** [comment]
@nbekirov I think this is a different issue, probably blocking while trying to flush the pipes before close. I suspect our `IO.copy_stream` logic is not doing the actual IO calls in an interruptible way, so everything gets stuck.

Please open a separate issue!

**Comment by headius** [comment]
Time to close this. We no longer use readline in the typical cases, preferring new IRB with reline. Since that rig uses normal Ruby IO, this issue is no longer present.

Under jline, on platforms where we can't support reline (none right now really) users will have to accept that the IO calls are not interruptible.
