### ISSUE TITLE
Kernel.system does not utilize tailing arguments in 1.9 mode

### ISSUE THREAD

**Issue by rjnienaber** [jruby/jruby#2389]
From: http://jira.codehaus.org/browse/JRUBY-5707. Decent error message is displayed in JRuby 1.7.18 but `ConcurrencyError` is raised in JRuby 9000.

I attempted to call Kernel.system with tailing arguments in 1.9 mode, but Kernel.system only returned nil.

Steps to reproduce:
jruby --1.9 -S irb

``` ruby
system('ls', '-la', :out => ['log.txt','w'])
```

Expected result:
The log.txt file would be created.

Actual result:
nil is returned and log.txt is not created.

Documentation for tailing arguments: http://rubydoc.info/stdlib/core/1.9.2/frames

**Comment by kares** [comment]
has been resolved in 9K : 
```
kares@sputnik:~/workspace/oss/jruby$ irb
jruby-9.1.15.0 :001 > system('ls', '-la', :out => ['log.txt','w'])
 => true 
jruby-9.1.15.0 :002 > puts `cat log.txt`
total 16188
drwxr-xr-x 27 kares kares  401408 Mar  1 15:16 .
drwxr-xr-x 89 kares kares    4096 Feb 24 10:17 ..
...
```
