### ISSUE TITLE
BigDecimal can be provoked into a big infinite loop

### ISSUE THREAD

**Issue by rjnienaber** [jruby/jruby#2390]
From: http://jira.codehaus.org/browse/JRUBY-3887. `OutOfMemoryError` on 1.7.18 and JRuby 9000 also fails to pass the test.

The attached file tests that the BigDecimal security fix has been applied (to the MRI interpreter). MRI returns almost immediately. JRuby appears to go into an infinite loop.

/opt/jruby/bin/jruby bigdecimal_segfault_fix_test.rb
Loaded suite test/unit/bigdecimal_segfault_fix_test
Started
... never terminates.

**Comment by kares** [comment]
unfortunately the JIRA links no longer work ... if anyone can provide the attached files tests here, pls do.

**Comment by headius** [comment]
The files are lost to time and space, unfortunately. We did patch around recent BigDecial parsing bugs that affected the JVM, MRI, and other runtimes, so hopefully we got this one.
