### ISSUE TITLE
Setup a SecurityManager from JRuby

### ISSUE THREAD

**Issue by rjnienaber** [jruby/jruby#2395]
From: http://jira.codehaus.org/browse/JRUBY-5582. Fails on JRuby 1.7.18 but appears to work on JRuby 9000.

when I attempt to install a SecurityManager from JRuby it fails.

if I understand correctly the problem is that while the java proxy is being generated for the 

checkPermission call it triggers another checkPermission call ...
posted this on the forum bot got no answer http://www.ruby-forum.com/topic/1245322
the failing sample code (including the stack trace) is available here: https://gist.github.com/862023

``` ruby
require 'java'

class JRubySecurityManager < java.lang.SecurityManager
  def checkPermission( perm )
    puts perm.inspect
  end
end

java.lang.System.setSecurityManager( JRubySecurityManager.new )
```

**Comment by enebo** [comment]
1.7.x is EOL and this will not get fixed.  Marking WONTFIX
