### ISSUE TITLE
File.join generates corrupted Windows-31J String on Windows

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2400]
From http://jira.codehaus.org/browse/JRUBY-7131

The original bug report did not have a good reproduction, so we'll need a Windows machine and we'll need to figure out how to type Unicode into a terminal to reproduce this.

I'm going to pessimistically guess it's still broken, but for now this bug is a placeholder until we can confirm that.

**Comment by ahorek** [comment]
IRB in Java window displays correct characters, but original windows console is ascii only
???/??? instead of 日本語/日本語

**Comment by headius** [comment]
My environment seems screwy and won't display multibyte chars in Command Prompt, but it does appear to join the filenames correctly. Can someone reproduce the File.join problem and show me:

* a git repo with a reproduction file
* a session log showing the failure OR a short video showing the failure

**Comment by enebo** [comment]
Multiple years with no repro.  Closing.  fwiw continued work on appveyor test runs are straightening out some of these issues over time but without a repro I don't know if this is one or not.

**Comment by ahorek** [comment]
@enbo I think it was already fixed in 9000 by https://github.com/jruby/jruby/issues/3871 - it shoud be closed, thanks
