### ISSUE TITLE
NoMethodError: undefined method `include' for A:Class

### ISSUE THREAD

**Issue by tobiassvn** [jruby/jruby#2408]
Nested includes with a `Module.included` in between spread over multiple files throws a `NoMethodError`. This is on the latest 9.0.0.0 SNAPSHOT installed with ruby-build.

Example:

File `a.rb`:

```ruby
require_relative 'b'
 
class A
  include B
end
```

File `b.rb`:

```ruby
module C
end
 
module B
  def self.included(klass)
    klass.include C
  end
end
```

Output:

```
$ ruby ./a.rb
NoMethodError: undefined method `include' for A:Class
  method_missing at org/jruby/RubyBasicObject.java:1600
        included at /home/toby/jruby-bug/b.rb:6
         include at org/jruby/RubyModule.java:2220
           A_0_1 at ./a.rb:7
      __script__ at ./a.rb:6
```

However, if the modules in file `b.rb` are defined in the same file `a.rb` everything works fine. Both ways work in MRI.

**Comment by headius** [comment]
I think this is a simple visibility problem: https://github.com/ruby/ruby/commit/26766ee89c31b16be74803c08cb0d2de2d2fc58e
