### ISSUE TITLE
Convert Splat operand into BuildSplatInstr

### ISSUE THREAD

**Issue by subbuss** [jruby/jruby#2409]
Splat operands are being generated in two contexts: call arguments and splats that show up in ruby code. For the latter, we need to use a BuildSplatInstr since these splats could throw exceptions if to_ary or to_a calls fails. Operands aren't supposed to be throwing exceptions.

So, we can use the current Splat operand for scenarios that won't throw exceptions (call args currently, but actual splats in future when we can determine they will succeed), and use BuildSplatInstr for the other splat use scenarios.

**Comment by headius** [comment]
I'm fine doing JIT fixes necessary for this. Is that just a matter of handling BuildSplatInstr?

**Comment by subbuss** [comment]
I thought I already handled BuildSplatInstr and the new Splat operand .. but I might have missed other uses of the old Splat or maybe there is some special-case handling that I overlooked.
