### ISSUE TITLE
Etc.systmpdir path separator on Windows

### ISSUE THREAD

**Issue by djberg96** [jruby/jruby#2431]
jruby 1.7.18 (1.9.3p551) 2014-12-22 625381c on Java HotSpot(TM) Client VM 1.7.0_71-b14 +jit [Windows 7-x86]

There's a path separator difference between JRuby and MRI for Etc.systmpdir:

```
# JRuby
irb(main):001:0> Etc.systmpdir
=> "C:\\Users\\djberge\\AppData\\Local\\Temp\\"

# MRI
irb(main):001:0> Etc.systmpdir
=> "C:/Users/djberge/AppData/Local/temp"
```

It doesn't bother me either way, but I'm guessing you want to convert to forward slashes to match MRI, and be consistent with Etc.sysconfdir, which does return forward slashes.

**Comment by headius** [comment]
Low priority unless it's causing something to break.

**Comment by djberg96** [comment]
Nope, no breakage here. Definitely low priority.

**Comment by kares** [comment]
this might actually be no longer relevant with JRuby 9K // maybe @MSNexploder can confirm this one

**Comment by MSNexploder** [comment]
Still contains backslashes in 9.1.9.0

```
irb(main):001:0> Etc.systmpdir
=> "C:\\Users\\STEFAN~1\\AppData\\Local\\Temp\\"
```

**Comment by djberg96** [comment]
Closing, stale.
