### ISSUE TITLE
Multiple assignment in conditionals possible

### ISSUE THREAD

**Issue by endofunky** [jruby/jruby#2433]
However, it shouldn't be, according to MRI.

Example:

``` ruby
foo = [1,2]

if (a, b = foo)
  puts a
  puts b
end
```

MRI:

```
% ruby ./t.rb
./t.rb:6: multiple assignment in conditional
```

JRuby 9k:

```
% ruby ./t.rb
1
2
```

**Comment by enebo** [comment]
Pretty amazing.  We have always worked and MRI has always raised this error.  @tobiassvn if you would like to go the extra mile you could open an issue at ruby-lang and ask if this should be made to work.  I guess my only guess would be that this must always evaluate to true so it makes no sense to have it in a conditional? but they do not restrict other things so it may be worth raising?

It should not be very hard to detect an masgn in the ifexpr part of the AST if we do need to fix this.

**Comment by tobiassvn** [comment]
It seems like it's already been discussed there. Quite recently actually:

https://bugs.ruby-lang.org/issues/10450

There is also an open issue proposing to change the current syntax error to a warning:

https://bugs.ruby-lang.org/issues/10617

**Comment by enebo** [comment]
@tobiassvn yeah that is what I meant when I said it always evaluated true (re Matz comment).  In any case, we will do whatever they determine in 10617.  For older version compatibility we will just add the error check

**Comment by headius** [comment]
We match CRuby's warning for this now, based on the end result of https://bugs.ruby-lang.org/issues/10617.
