### ISSUE TITLE
OpenSSL::SSL::SSLSocket#cipher different than MRI

### ISSUE THREAD

**Issue by jordansissel** [jruby/jruby#2436]
MRI's docs say `OpenSSL::SSL::SSLSocket#cipher` (http://ruby-doc.org/stdlib-1.9.3/libdoc/openssl/rdoc/OpenSSL/SSL/SSLSocket.html#method-i-cipher)

> cipher => [name, version, bits, alg_bits] 

Under MRI 2.1.4, this returns  something like the docs say:
`["ECDHE-RSA-AES128-GCM-SHA256", "TLSv1/SSLv3", 128, 128]`

Under JRuby 1.7.17, this returns a single string (not array w/ 4 elements): `SSL_RSA_WITH_RC4_128_SHA`

**Comment by headius** [comment]
Interesting. I'm curious...are you using those other bits for something?

I think you should re-file this at jruby/jruby-openssl. We're trying to maintain it as a separate project.
