### ISSUE TITLE
Lambda with arity -2 can be called with three arguments in 9K

### ISSUE THREAD

**Issue by iconara** [jruby/jruby#2441]
This code fails with `ArgumentError` in MRI (at least since 1.9.3) and JRuby 1.7, but not in JRuby 9K:

```ruby
lambda { |a, b=nil| }.call(1, 2, 3)
```

In JRuby 9K (and MRI 1.8.7 I believe) the block is run with 1 and 2 as the values of `a` and `b`, the 3 is discarded.

**Comment by headius** [comment]
I have to ask...how does this affect you?

**Comment by iconara** [comment]
It's mostly an inconsistency that I accidentally caught when a test started failing.

It's [a test](https://github.com/iconara/ione/blob/master/spec/ione/future_spec.rb#L286-L297) for [a piece of code](https://github.com/iconara/ione/blob/master/lib/ione/future.rb#L707-L723) that tries to figure out how many arguments it can pass to a listener (which can be a block, a lambda, a method, or anything callable). When the arity is -2 it can't really know how many are ok to pass so it just tries to call the method. In 9K the listener is called, but in previous versions of JRuby and in MRI there's an `ArgumentError`.

If I could choose I'd like all Rubies to work like 9K, but I thought I'd report it since it's an inconsistency with MRI.

**Comment by iconara** [comment]
The reason why I'm doing the arity checking at all is for backwards compatibility. A previous version called the listeners with other arguments.

**Comment by enebo** [comment]
I would like to see this solved before we entertain call protocol changes in IR for blocks which will not happen for 9k.0 but still we should fully nail all semantics of blocks down before trying to tackle it.

**Comment by headius** [comment]
Ok...this is likely a (reasonably) simple problem with arity-checking in lambdas. We'll get it fixed up, because there's other logic that depends on lambdas enforcing arity strictly.

cc @enebo @subbuss

**Comment by headius** [comment]
My concern with this is that lambdas have *always* raised arity errors, and if they aren't now we've got a significant behavioral difference. It's a difference most people won't see, but I don't like it anyway.

**Comment by headius** [comment]
Fixed in commits today including b6d996db3101289c9f8c432790e773151e4e1a08 and 7e82e91c7301011769bb02b90c813f5ce3e1f3e3.
