### ISSUE TITLE
Release 9k Preview

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2445]
This bug will collect release notes and tasks for the 9k preview release we really ought to get out :-)

Here's what I estimate we need:

- [x] Items for release notes (bug list will be included)
- [x] A list of caveats and features we know are permanently or temporarily broken. For example, AOT (may not be done for 9k.pre), known performance issues (new runtime/JIT).
- [ ] Updating online content for the new version. jruby.org, for example, still says "1.8 and 1.9 compatible"
- [x] Basic functionality working on Windows (maybe not perfect, but ideally at least Rails)

**Comment by cmichon** [comment]
If #2429 (showstopper) is not fixed prior to the 9k preview release, Windows should not be part of the preview release and this should be in the release notes.

**Comment by headius** [comment]
@cmichon At the moment we do *want* Windows to work for the release, but we're limited in what we can do to get there. Only @enebo has a Windows dev machine to use, though I have some Windows licenses on the way to remedy that.

Thanks for pointing it out.

**Comment by cmichon** [comment]
I can provide feedbacks on regular basis with a custom test suite.

How can I find all recent daily snapshots? I would need all of them, not
just the latest CI build.

**Comment by headius** [comment]
Commits leading up to a2ef35f have gotten Windows working well enough to install rails, generate and scaffold an app and serve it successfully. I'm sure there will be other issues, but that's a lot working.

**Comment by cmichon** [comment]
yes today's CI snapshot confirms the original issue is gone.

Yet, installing the gem awesome_print gave this interesting output:

> jgem ins awesome_print
Fetching: awesome_print-1.6.1.gem (100%)
Successfully installed awesome_print-1.6.1
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - stty

> grep -lr stty . (inside jruby-9.0.0.0-SNAPSHOT)
./bin/jruby
./bin/jruby.bash
./lib/ruby/stdlib/io/console.rb
./lib/ruby/stdlib/rake/application.rb
./lib/ruby/stdlib/rubygems/user_interaction.rb

Bound to happen: no stty in Windows...

Looking at io/console.rb, it seems the code fails on Windows and it behaves
as if stty is present on the system... I'll look more into it tomorrow.


On Wed, Jan 14, 2015 at 8:23 PM, Charles Oliver Nutter <
notifications@github.com> wrote:

> Commits leading up to a2ef35f
> <https://github.com/jruby/jruby/commit/a2ef35fc2df914539546c5a01dd89c68a9afce2b>
> have gotten Windows working well enough to install rails, generate and
> scaffold an app and serve it successfully. I'm sure there will be other
> issues, but that's a lot working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jruby/jruby/issues/2445#issuecomment-69974762>.
>



-- 
Christian

**Comment by headius** [comment]
@cmichon Huh yeah, that should work. I took a bare JRuby clone all the way to a running Rails app, which involved a lot of RubyGems (which loads io/console). Let me know what you see and file a bug if you can narrow something down.

**Comment by enebo** [comment]
@headius you have cygwin or mingw commands in your path?  The code path for io/console.rb looks like windows will follow the else and try to execute `stty -a`

**Comment by headius** [comment]
@enebo It's possible, but it would have had to come in with the git command. I started from a bare Windows 2012 server. I don't think so, because even simple things like `ls` didn't work but git did.

**Comment by headius** [comment]
At @enebo's suggestion, I audited core class method definitions in JRuby and MRI. I added a bunch of small ones that were missing, deleted some, moved some, and changed visibility on some. The remaining (coarse-grained) items are here:

* Enumerator#feed, #next_values, #prev_values missing
* Hash#any? and Array#any? optimization missing
* ObjectSpace::WeakMap#each and Enumerable inclusion
* ObjectSpace::count_objects unimplemented
* Process::daemon unimplemented
* Process::exec missing (is this just Kernel#exec?)
* Process::getsid unimplemented
* Process::setproctitle
* RubyVM namespace
* Thread#handle_interrupt is not yet fully functional

@who828 and I added a bunch of missing methods and removed some others in commits today.

Looking pretty good :-)

**Comment by headius** [comment]
Oops, @who828 added Array#any? and Hash#any? so I'll update my comment above.

**Comment by headius** [comment]
FYI, current plan is pre1 release on Monday.

**Comment by headius** [comment]
@chrisseaton I heard you're traveling today, but please comment on the bug with any details about JRuby+Truffle in pre1.

**Comment by headius** [comment]
I've started a wiki page for the release notes: https://github.com/jruby/jruby/wiki/JRuby-9.0.0.0.pre1-Release-Notes

**Comment by chrisseaton** [comment]
I've added a few sentences on Truffle. It basically says normal users shouldn't even attempt to run their applications on it.

Truffle is blocked on #2466, but @mkristian is already looking at it. We'll freeze Truffle development and start double checking to make sure it's ready for release on Monday.

**Comment by chrisseaton** [comment]
Truffle is ready to go, apart from @mkristian thinks we need to put Truffle into Maven Central as all JRuby dependencies are supposed to be available there (#2474). I can look into that on Monday when the relevant people are around.

**Comment by Who828** [comment]
@headius  I think you meant peek_values, not prev_values for Enumerator. (prev_values doesn't exists in MRI).

**Comment by headius** [comment]
@Who828 You're right, I'll fix that.

**Comment by enebo** [comment]
It is out!
