### ISSUE TITLE
No #define_method on main object

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#2449]
This works on MRI, but not sure why

```ruby
define_method :bar do
end
```

Where does it get `define_method` from? Works on MRI 2.2, Rbx 2.1.4, but not on JRuby 1.7 or master.

**Comment by cremno** [comment]
It isn't `Module#define_method`, it's directly defined on top self/main object (for some reason). 

https://github.com/ruby/ruby/blob/6b6ba319ea4a5afe445bad918a214b7d5691fd7c/proc.c#L2779-L2780
https://bugs.ruby-lang.org/issues/6609

**Comment by headius** [comment]
@cremno Good find, thank you!
