### ISSUE TITLE
GC Symbol

### ISSUE THREAD

**Issue by jodosha** [jruby/jruby#2450]
Hello, do you have plans to support the new introduced feature in MRI regarding collectable symbols?

In order to protect applications from DoS attacks, we are forced to whitelist inputs, convert their keys to strings and to provide facilities we use tricks like "indifferent access". This adds both development and runtime overhead.

I'm asking this specifically for Lotus. Supporting multiple Ruby VMs, with a different set of behaviors across versions is becoming really hard for us.

Thank you in advance.

**Comment by kares** [comment]
it's done on master (for 9k) ... see details at https://github.com/jruby/jruby/issues/2350

**Comment by joneslee85** [comment]
@kares Do you have ETA of the release?

**Comment by headius** [comment]
We thought we might be ready to preview 9k last week, but got sidetracked on some issues. Hopefully this week. Final would then hopefully come about a month later.

**Comment by jodosha** [comment]
@headius @kares Thanks for the quick reply. BTW what's the best way to ask you questions? IRC?
I felt because I opened this issue here. :)
