### ISSUE TITLE
IO#each_line hangs when its 

### ISSUE THREAD

**Issue by JoshCheek** [jruby/jruby#2461]
Script below hangs. I don't expect this behaviour, but I do test it to make sure it handles it gracefully, but it's locking up the test suite.

```ruby
# cat f.rb
read, write = IO.pipe
Thread.new do
  sleep 1
  read.close
end
read.each_line { |line| line }

# ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin13.0]

# ruby f.rb
f.rb:6:in `each_line': stream closed (IOError)
	from f.rb:6:in `<main>'

# chruby jruby
# ruby -v
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_51-b13 +jit [darwin-x86_64]

# ruby f.rb
....
```

**Comment by headius** [comment]
Works like in MRI on 9k.

On 1.7.x it appears that both threads are trying to acquire the same lock. each_line probably locks once around the whole operation while the other thread attempts to lock it on entry to read. However IO#close *should* trigger blocking threads to wake up, as in 9k...even if they're inside a synchronized bit of code.

May be possible to change the granularity of the locking or fix the interrupt.

**Comment by headius** [comment]
Correction: it is ChannelStream.getline that's synchronized and leading to the lock contention. So it's not locking around the whole loop, but it is locking while it waits for the next line.

**Comment by headius** [comment]
So it's a bit trickier to fix. The getline logic in 1.7 does not use any selector (just calls blocking read), so it doesn't have an easily-interruptible call (interrupting a blocking read on JVM closes that stream).

This may be a problem too large to solve given the way 1.7's IO is implemented, especially given that 9k appears to do it right.

**Comment by headius** [comment]
Going to call this fixed for 9k.

**Comment by JoshCheek** [comment]
Thanks for looking into it :)
