### ISSUE TITLE
Build a new pass that ensures that ruby locals / IR tmps are initialized 

### ISSUE THREAD

**Issue by subbuss** [jruby/jruby#2465]
So, in the snippet below, x is not initialized on all paths.

```ruby
def foo
  x = 1 if bar
  p x
end
```

So, this requires JRuby to return nil if a local var look fails. We can get rid of those if the IR can introduce necessarily initializations on all code paths. This will simply DynamicScope var looks and also eliminate conditionals in variable retrieves (see https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ir/operands/TemporaryLocalVariable.java#L48-L61)

**Comment by subbuss** [comment]
I added the AddMissingInitsPass for this. However, we are not ready to get rid of the null check in DynamicScope var lookups since we have the interpreter that runs in startup mode where no passes have run. So, that would require a specialized implementation of DynamicScope for the JIT and the interpreter where the former would be vastly simplified without the null checks. That is a different beast and I am inclined to close this ticket and maybe a different ticket for using an optimized version of DynamicScope without null checks? /cc @headius @enebo ..

**Comment by headius** [comment]
@subbuss That does sound like a good idea. If Full/JIT could allocate DynamicScope instances that don't do need to do null checks, it would help reduce code size and complexity, potentially letting more stuff inline and optimize. This could also be combined with dynamically generating DynamicScope subclasses that have exactly the right number of variables, so we're never allocating an array to hold them.

So yes, :+1: to opening a new issue for smarter DynamicScope null checking.

**Comment by enebo** [comment]
@subbuss @headius we could make dynamicscope only for startup interp and have default not null check.  The only requirement is full interp would need to run this pass as well.   So I am advocating removing the checks on current type and adding special one only for startup as the oddball.

**Comment by enebo** [comment]
Err I should add why I want this as well.  If we want to test all passes usable and testable via full interp then I think we need to have full interp act as closely to JIT as we can internally.

**Comment by subbuss** [comment]
@enebo sure makes sense of making the startup interp be the exceptional case. @headius will create a new issue later today and close this one.

**Comment by subbuss** [comment]
Created #4167.
