### ISSUE TITLE
NoMethodError "join", with Padrino and Warbler

### ISSUE THREAD

**Issue by rkelly34** [jruby/jruby#2467]
From version 1.7.16 on, I've been getting a generic Error 500, with details NoMethodError "Join" on string.
Originally found in 1.7.18, I could not get it to work correctly until going back to 1.7.15
The application is a Padrino application, warbled (tested both 1.4.0, and 1.4.4), and hosted using Tomcat.

**Comment by enebo** [comment]
This much info is not super likely enough for us to go on unless something really obvious sticks out in commits between 1.7.15 and 1.7.16.  Any chance you can localize what object is raising this NoMethodError?

**Comment by enebo** [comment]
@rkelly34 any chance to narrow this down any more?

**Comment by headius** [comment]
Bumping to 1.7.21 since we've had no input from reporter.

**Comment by kares** [comment]
time to close as invalid since we waited for feedback for more than 6 months now
