### ISSUE TITLE
Avoid loading classes not present on Android

### ISSUE THREAD

**Issue by donv** [jruby/jruby#2471]
Currently there is a har load path from org.jruby.Ruby to java.lang.invoke.MethodHandles which is not present on Android.  We ned to avoid this load path when the compiler is disabled.

```
W/dalvikvm( 3569): Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lorg/jruby/compiler/JITCompiler;
E/RUBOTO  ( 3569): Exception starting JRuby
E/RUBOTO  ( 3569): java.lang.reflect.InvocationTargetException
W/System.err( 3569): java.lang.reflect.InvocationTargetException
W/System.err( 3569):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 3569):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 3569):    at org.ruboto.JRubyAdapter.setUpJRuby(JRubyAdapter.java:261)
W/System.err( 3569):    at org.ruboto.JRubyAdapter.setUpJRuby(JRubyAdapter.java:123)
W/System.err( 3569):    at org.ruboto.test.InstrumentationTestRunner$1.run(InstrumentationTestRunner.java:49)
W/System.err( 3569):    at java.lang.Thread.run(Thread.java:841)
W/System.err( 3569): Caused by: java.lang.NoClassDefFoundError: java.lang.invoke.MethodHandles
W/System.err( 3569):    at org.jruby.compiler.JITCompiler.<clinit>(JITCompiler.java:177)
W/System.err( 3569):    at org.jruby.Ruby.<init>(Ruby.java:246)
W/System.err( 3569):    at org.jruby.Ruby.newInstance(Ruby.java:327)
W/System.err( 3569):    ... 6 more
```

**Comment by donv** [comment]
Tried adding ```jsr292-mock-1.1.jar``` to satisfy class loading, but it barfs on building the apk:

```
    [apply] trouble processing "java/lang/ClassValue.class":
    [apply] 
    [apply] Ill-advised or mistaken usage of a core class (java.* or javax.*)
    [apply] when not building a core library.
```

**Comment by donv** [comment]
When running with ```--core-libray``` and the ```jsr292-mock-1.1.jar```, the app builds, but fails during runtime:

```
W/System.err( 4250): Caused by: java.lang.UnsupportedOperationException
W/System.err( 4250): 	at java.lang.invoke.MethodHandles.publicLookup(MethodHandles.java)
W/System.err( 4250): 	at org.jruby.compiler.JITCompiler.<clinit>(JITCompiler.java:177)
W/System.err( 4250): 	... 8 more
```

**Comment by donv** [comment]
@enebo We should avoid loading the JITCompiler class and the jsr292 classes when the compiler is disabled.  Any idea how best to do that?

**Comment by enebo** [comment]
in Ruby.init the instance is created.  You can just check RubyInstanceConfig for compiler mode and if it is OFF then don't construct JITCompiler.

**Comment by enebo** [comment]
If someone wants to add the code to make JIT conditional they can but we will not hold up pre1 for this since I am guessing there has been no 9k evaluation recently based on the inability to work around the JIT classs.   Moving forward and next 9k release (pre2,rc1,...) will hopefully be working well enough.

**Comment by donv** [comment]
OK, time has passed.  @enebo @headius Any tips on how to do this?  Add some interface and load implementation by reflection?

**Comment by headius** [comment]
This is no longer relevant since Android now supports invokedynamic and method handles.
