### ISSUE TITLE
truffle artifacts are not on maven central and we have a release repo in jruby-parent.pom

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#2474]
this actually is a follow up to #2466

currently the regular maven artifact 'org.jruby:jruby-core' does not work since it depends on truffle artifacts which are NOT on maven central.

the release repo for the truffle in jruby-parent.pom is a no way, we can not deploy such artifact via sonatype since maven central should stay self contained.

**Comment by mkristian** [comment]
@chrisseaton right now we can release jruby with truffle as is

**Comment by chrisseaton** [comment]
Yeah - we'll see what we need to do to get on Maven Central. JRuby goes via Sonatype, right? How does it do that?

**Comment by headius** [comment]
@chrisseaton This guide should give you all you need to know to get an organization/groupId/artifactId using Sonatype's OSS support: http://central.sonatype.org/pages/ossrh-guide.html

This is the same setup all our JRuby-related artifacts use.

**Comment by headius** [comment]
This has been mitigated by temporarily pushing a truffle artifact on com.headius groupid. We'll revert back to the Oracle jars once they've been pushed to maven central.

**Comment by headius** [comment]
Truffle is in maven central now.
