### ISSUE TITLE
Truffle: Understand and reduce impact of Truffle on the distribution size

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#2475]
We would like to understand what the impact of Truffle is on the distribution size, and what we can do to reduce it.

I'll keep a log of notes here on progress.

**Comment by chrisseaton** [comment]
Branch: master
Commit: b66ac36

jruby-core-9.0.0.0.pre1.jar: 15.1MB
jruby-core-9.0.0.0.pre1.jar uncompressed: 31.8MB

org.jruby.truffle uncompressed: 18.4MB
Truffle core files uncompressed: 150KB (trivial, so we'll ignore from this point on)

Truffle makes up 58% of the uncompressed core jar.

**Comment by mkristian** [comment]
spliting jruby-core into two parts: one with only org.jruby.truffle.** and the other all the rest.

* 8.1M jruby-core-9.0.0.0.pre1-onlytruffle.jar
* 6.1M jruby-core-9.0.0.0.pre1-notruffle.jar

**Comment by chrisseaton** [comment]
Branch: truffle-head (using next release of Truffle with new DSL layout and unboxing disabled)
Commit: f097640

jruby-core-9.0.0.0.pre1.jar: 12.3MB
jruby-core-9.0.0.0.pre1.jar uncompressed: 26.2MB

org.jruby.truffle uncompressed: 11.8MB
Truffle core files uncompressed: 150KB (trivial, so we'll ignore from this point on)

Truffle makes up 45% of the uncompressed core jar.

So we've reduced Truffle by 36% in the next version.

**Comment by chrisseaton** [comment]
With the release of Truffle 0.7 the jruby-truffle JAR is now just 7MB, and that's with core library completeness going from 4% to 78%. I don't think archive size is an issue any more.
