### ISSUE TITLE
Keyword arguments arity issue

### ISSUE THREAD

**Issue by emboss** [jruby/jruby#2480]
Probably related to #2320. I get similar results with lambda keyword arguments and keyword arguments passed as a Hash instead of passing them explicitly.

```shell
$ jruby -v
jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-18 746583b Java HotSpot(TM) 64-Bit Server VM 25.25-b02 on 1.8.0_25-b17 +jit [linux-amd64]
```

```ruby
l = lambda  { |a:| a }
l.call(a: 1) # wrong number of arguments (1 for 0)
l.arity # 0 (1 in MRI 2.2.0p0)
```
After some debugging, I found out that in `RubyBlock#prepareArgs` the arity is checked on the `Signature`'s arity object (a "Fixed0"), but keyword args would only be considered in `Signature#checkArity`.

Not sure if this is related or a different issue:

```ruby
def m(a:, b:); a + b; end
args = { a: 1, b: 2 }
m(args) # ArgumentError: missing keyword: a
method(:m).arity # 0 (1 in MRI 2.2.0p0)

**Comment by enebo** [comment]
In your second m(args) snippet I see no argument error but the arity is 0 like you reported.  Can you confirm that?

**Comment by enebo** [comment]
Commit 2025534e876f655ea00daff9d0251a0d072e800d solves the ArgumentError in your first snippet but does not fix your arity issue.  Going to look at arity tests in MRI and see what we have tagged out.

**Comment by emboss** [comment]
Awesome, thank you! About the second example, it's weird. I was running this in irb, when I tried again it worked. But I found a script that reproduces it deterministically on my machine:

```ruby
def f(a:, b:); end
args = { a: 1, b: 1 }
f(args) # nil, first invocation works
f(args) # ArgumentError: Missing keyword :a
```

It's only the second call that fails.

**Comment by enebo** [comment]
AHA.  So for this example we will track it at #2015 and for the arity cases we will use this issue.
