### ISSUE TITLE
Long generated filenames in Truffle code prevent compilation on some systems

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#2483]
For example #2479 

This should be fixed in Truffle 0.7 in a couple of weeks max. Try the `truffle-u` branch as an alternative workaround.

**Comment by nirvdrum** [comment]
I've confirmed this is working on my system.  It's a bit tricky because you could still have problems with a deeply nested hierarchy.  I have my stuff rooted at `/home/nirvdrum/dev/workspaces/jruby`.  Any directory shorter should be fine.
