### ISSUE TITLE
Proc.parameters return an empty array

### ISSUE THREAD

**Issue by blanquer** [jruby/jruby#2489]
Invoking the .parameters method of a Proc seems to return an empty array, rather than the parameters definition.

Repro steps:
```ruby
p = Proc.new do |arg1: |
  puts arg1
end
   
puts "Params: #{p.parameters.inspect}"
```

Using ruby 2.2.0: (and it is the same for 2.1.x)
```
Params: [[:keyreq, :arg1]]
```

Using Jruby-head (ruby9000) as of today:
```
Params: []
```

**Comment by enebo** [comment]
Yeah sorry we knew about this one from some tagged out tests in MRI but we will make sure we get this for pre2.
