### ISSUE TITLE
Cleanup tags

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#2490]
A few git tags seem to be user errors or unintended.
One can see them at https://github.com/jruby/jruby/tags.
Notably `localhead`, `last-success`, `hudson-whatever`, `list` and `Dirty-hackish-mkmf`.
Can we delete them?

**Comment by headius** [comment]
I'll do a tag and branch sweep today.

**Comment by headius** [comment]
Did not get to tag/branch sweep today :-D

**Comment by eregon** [comment]
@headius Could you have a quick look at this?

**Comment by headius** [comment]
Tags have been swept and gone back to bad again since, but this issue is old and stale.

I have done some work recently on master to make it easier/safer to untag, specifically by adding the RbConfig `host_os` name as a tag so we don't delete tags that are for other platforms and by adding the more descriptive `hangs` tag rather than the confusing `critical` tag, so we have a clear place to mark hanging specs. However pretty much all tags need to be audited to use better tagging, so this is an ongoing process.

**Comment by eregon** [comment]
This issue was about `git` tags, such as https://github.com/jruby/jruby/releases/tag/localhead and others which seem stale.
There are still there, but I don't really mind much.

I think your reply is about MSpec tags. Sounds like nice improvements, and
https://github.com/jruby/jruby/blob/f8de5157d128e8e59a1e32654ed0497192b6b2a4/spec/jruby.mspec#L92
is a nice idea for generic OS tags.
Let me know when you think it's worth re-running a [Ruby Spec Suite Compatibility Report](https://eregon.me/blog/2020/06/27/ruby-spec-compatibility-report.html).

**Comment by headius** [comment]
I have removed the old meaningless git tags.

I have also removed the old "graalvm" tags since they have no relevance here anymore and live on in the TruffleRuby repository. The refs those tags pointed at are provided below:

```
commit 31979422e923fa641069e008a70d247ee31ce3a3 (tag: graalvm-0.11)
Author: Chris Seaton <chris.seaton@oracle.com>
Date:   Wed Mar 30 13:30:41 2016 +0100

    [Truffle] Remove tagging compatibility mode.

commit f1c4782d27288d58edb8456b8923791644017230 (tag: graal-vm-0.12)
Merge: 9f1d7611f6 005ec3d542
Author: Kevin Menard <kevin.j.menard@oracle.com>
Date:   Fri May 27 09:06:44 2016 -0400

    Merge branch 'master' into truffle-head

commit 170c9ae6104449363f6ee1632cc57401de410429 (tag: graal-vm-0.12-build-pack-compat)
Author: Christian Meier <meier.kristian@gmail.com>
Date:   Fri May 27 15:11:54 2016 +0200

    [build] do not use ant in ./core anymore

commit d42997f0102d63a0b72a3d01a686d71f3c991ccf (tag: graal-vm-0.13)
Author: Chris Seaton <chris.seaton@oracle.com>
Date:   Wed Jun 29 17:28:58 2016 +0100

    [Truffle] Don't change the environ in mx.

commit d2f2fcf8ca86918a1a599fb93fbbc507c2261fe8 (tag: graal-vm-0.14)
Author: Benoit Daloze <eregontp@gmail.com>
Date:   Tue Jul 26 18:33:30 2016 +0200

    [Truffle] Do not use the build pack on truffle-head as it won't contain the latest truffle.

commit 10c6b6e6ddf8a837d64d46006654136fdc0d6f39 (tag: graal-vm-0.15)
Merge: 6af2b33eca 09accaa3f6
Author: Chris Seaton <chris.seaton@oracle.com>
Date:   Mon Aug 1 22:37:50 2016 +0100

    Merge branch 'master' into truffle-head
    
    # Conflicts:
    #       ci.hocon
    #       truffle/src/main/java/org/jruby/truffle/language/DataNode.java

commit dd4076bda89cb417fe55116ce54aec723b74335f (tag: graal-vm-0.16)
Author: Benoit Daloze <eregontp@gmail.com>
Date:   Thu Aug 25 11:44:14 2016 +0200

    [Truffle] PolyglotEngine no longer throws IOException.

commit c0f8c56ddbd6f08859f671fe1ed6d1aa5ba70637 (tag: graal-vm-0.17)
Author: Benoit Daloze <eregontp@gmail.com>
Date:   Wed Sep 28 11:27:04 2016 +0200

    [Truffle] Assume that Graal is automatically set up if RUBY_BIN is set.

commit 8a74a73dc016205bc13c2d843a88fd10dfac22d8 (tag: graal-vm-0.18)
Author: Kevin Menard <kevin.j.menard@oracle.com>
Date:   Wed Oct 26 20:14:40 2016 -0400

    [Truffle] Add missing boundary.

commit 00938d2f71b3c6440f706170425e8eeda278a1e9 (tag: graal-vm-0.19)
Author: Kevin Menard <kevin.j.menard@oracle.com>
Date:   Mon Nov 28 14:02:26 2016 -0500

    [Truffle] Consolidated support code for AOT image.
```
