### ISSUE TITLE
Open3 fails with varying signals on 9.0.0.0.pre1

### ISSUE THREAD

**Issue by philr** [jruby/jruby#2494]
I am using `jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-21 ac0d512 OpenJDK 64-Bit Server VM 24.65-b04 on 1.7.0_65-b32 +jit [linux-amd64]`.

I am executing processes using Open3. Instead of receiving the expected exit status, I am instead seeing a signal raised:

```ruby
jruby-head :002 > Open3.popen3('ruby', '-e', 'exit true') {|i,o,e,t| t.value}
 => #<Process::Status: pid 21796 signal 36> 
jruby-head :003 > Open3.popen3('ruby', '-e', 'exit true') {|i,o,e,t| t.value}
 => #<Process::Status: pid 21817 signal 57> 
```
The signal number increases by about 22 with each execution before wrapping around at around 127.

With JRuby 1.7.18, I get the expected result:

```ruby
jruby-1.7.18 :002 > Open3.popen3('ruby', '-e', 'exit true') {|i,o,e,t| t.value}
 => #<Process::Status: pid=18784,exited(0)> 
```

The `capture3` method fails in the same way:

```ruby
jruby-head :004 > Open3.capture3('ruby', '-e', 'i=STDIN.read; print i+"o"; STDOUT.flush; STDERR.print i+"e"', :stdin_data=>"i")
 => ["io", "ie", #<Process::Status: pid 21839 signal 79>] 
```

The above examples are based on code from [`test/mri/test_open3.rb`](https://github.com/jruby/jruby/blob/master/test/mri/test_open3.rb). If I run `test/mri/test_open3.rb`, I get [16 test failures](https://gist.github.com/philr/e995ec1fdbc657377ff5).

**Comment by headius** [comment]
Seems specific to how open3 is doing its subprocess launching. If I use `system` the exit statuc looks right:

```
~/projects/jruby $ jruby -ropen3 -e "5.times { p Open3.popen3('ruby', '-e', 'exit true') {|i,o,e,t| t.value} }"
#<Process::Status: pid 36648 signal 40>
#<Process::Status: pid 36662 signal 54>
#<Process::Status: pid 36676 signal 68>
#<Process::Status: pid 36692 signal 84>
#<Process::Status: pid 36706 signal 98>

~/projects/jruby $ jruby -ropen3 -e "5.times { system('ruby', '-e', 'exit true'); p \$? }"
#<Process::Status: pid 36729 exit 0>
#<Process::Status: pid 36743 exit 0>
#<Process::Status: pid 36757 exit 0>
#<Process::Status: pid 36771 exit 0>
#<Process::Status: pid 36785 exit 0>
```

**Comment by headius** [comment]
Problem is in Process.detach...it's not using the right value for exit code:

```
$ jruby -e "process = spawn('ruby', '-e', 'exit true'); thread = Process.detach(process); p thread.value"
#<Process::Status: pid 37181 signal 61>
```

**Comment by headius** [comment]
Please confirm with JRuby master. Thanks for the report...this fix made a bunch of other tests start passing too.

**Comment by philr** [comment]
I can confirm that this is now fixed. Thank you @headius.
