### ISSUE TITLE
IO.popen cannot run 'date' on Windows 7

### ISSUE THREAD

**Issue by kingspider1971** [jruby/jruby#2505]
dateProc = IO.popen("date", 'w+')
dateProc.puts "\n"
dateProc.close_write
s2 = dateProc.gets
puts s2

Execution Result: 
D:\ruby\jruby-1.7.18\bin\jruby.exe --1.9 -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) D:/ruby/projects/test1/test/test1.rb
IOError: Cannot run program "date" (in directory "D:\ruby\projects\test1\test"): CreateProcess error=2, ?????????
   popen at org/jruby/RubyIO.java:4345
  (root) at D:/ruby/projects/test1/test/test1.rb:1
    load at org/jruby/RubyKernel.java:1087
  (root) at -e:1

**Comment by headius** [comment]
This works ok in 9k. I believe the "date" command is not an executable but a cmd.exe subcommand. 9k must be handling that and 1.7 is not.

**Comment by headius** [comment]
Nevermind, it turns out I had a date.exe in the path for 9k. We are not handling this right on either branch.

**Comment by headius** [comment]
Ok, so it turns out we had the right logic for non-popen spawns (system, backticks) and I was able to add it to popen. It's probably not the cleanest fix but it appears to work right.

Should be fixed in 1.7.20 and 9k.pre2.
