### ISSUE TITLE
load error: jopenssl/load in jruby 9.0.0.0.pre1

### ISSUE THREAD

**Issue by raskhadafi** [jruby/jruby#2507]
On my osx with jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) 64-Bit Server VM 25.5-b02 on 1.8.0_05-b13 +jit [darwin-x86_64]

Used gem: airbrake

I get:

```
LoadError: load error: jopenssl/load -- java.lang.SecurityException: class "org.bouncycastle.asn1.ASN1Primitive"'s signer information does not match signer information of other classes in the same package
  require at org/jruby/RubyKernel.java:954
   (root) at /Mobiles/107446/.rvm/rubies/jruby-9.0.0.0.pre1/lib/ruby/stdlib/openssl.rb:1
  require at org/jruby/RubyKernel.java:954
   (root) at /Mobiles/107446/.rvm/rubies/jruby-9.0.0.0.pre1/lib/ruby/stdlib/net/https.rb:1
  require at org/jruby/RubyKernel.java:954
   (root) at /Mobiles/107446/.rvm/rubies/jruby-9.0.0.0.pre1/lib/ruby/stdlib/net/https.rb:22
  require at org/jruby/RubyKernel.java:954
   (root) at /Mobiles/107446/.rvm/gems/jruby-9.0.0.0.pre1@pdf_box/gems/airbrake-4.1.0/lib/airbrake.rb:1
  require at org/jruby/RubyKernel.java:954
   (root) at /Mobiles/107446/.rvm/gems/jruby-9.0.0.0.pre1@pdf_box/gems/airbrake-4.1.0/lib/airbrake.rb:12
  require at org/jruby/RubyKernel.java:954
```

**Comment by mkristian** [comment]
this probably has two reasons: one it the reversed classloader hierarchy of jruby-9.0.0.0.pre1 and second that you probably have BC in your extension classloader (i.e. BC is part of your java installation)

the first part will be reverted to what we have in jruby-1_7 in 9.0.0.0.pre2

**Comment by raskhadafi** [comment]
Thanks for your immediate answer!

For BC should I use the lastest version? Thanks in advance for your help.

**Comment by mkristian** [comment]
either remove it from your jdk installation if that is possible or
use jdk15on-1.49 which comes with jruby-9.0.0.0.pre1 (which still could
create problems with the current release)

**Comment by kares** [comment]
@raskhadafi any chance to confirm if this is still an issue with 9K-pre2 ?
