### ISSUE TITLE
keyword arguments incompatibilities

### ISSUE THREAD

**Issue by blanquer** [jruby/jruby#2512]
There are a couple of things that I'm seeing that still don't match the MRI behavior on method keyword arguments.

One is the arity, which returns different results ( but I believe that this might already be tracked in https://github.com/jruby/jruby/issues/2480 ?)

The other one is the definition of the keyword types "required" vs. not . For example, required arguments are not reported as such in the .parameters call.

Here's a quick snippet that shows both things, and the difference in results:

```ruby
class Foo
  def self.test( arg1: "default" , arg2: )
    puts "arg1: #{arg1.inspect}"
  end
end

m = Foo.method(:test)
puts "PARAMS: #{m.parameters.inspect}"
puts "ARITY: #{m.arity}"
```

```shell
bug:~ $ rvm 2.2.0
bug:~ $ ruby /tmp/test.rb
PARAMS: [[:keyreq, :arg2], [:key, :arg1]]
ARITY: 1
bug:~ $ rvm jruby-head
bug:~ $ ruby /tmp/test.rb
PARAMS: [[:key, :arg1], [:key, :arg2]]
ARITY: 0

```

**Comment by Who828** [comment]
Hey, thanks for reporting the bug!
I have fixed parsing bit, so it identifies keyreq correctly but I still need to work on the arity part of the bug.

**Comment by enebo** [comment]
Recent commits has solved remaining issue with this snippet (e.g. arity being reported as wrong).
