### ISSUE TITLE
Is there a way to clean the source directory completely?

### ISSUE THREAD

**Issue by nomadium** [jruby/jruby#2529]
https://github.com/jruby/jruby/blob/master/BUILDING.md documents how to build jruby from source and it works OK.

However, I'm unable to find a way to clean the build the directory to restore it as it looked when was just cloned from the repo.

I tried several commands from the BUILDING guide but all of them leave and bunch of files in the directory. I tried:

* ```mvn clean install -Pjruby-jars```
* ```mvn -Pclean```
* ```jruby -S rmvn -Pclean```

Am I doing something wrong?

This is the output of ```mvn --version```:

```
miguel@nina:~/packages/jruby/$ mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_75, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-4-amd64", arch: "amd64", family: "unix"
```

Thanks.

**Comment by mkristian** [comment]
git clean -dfx

since maven build does not clean up certain files in lib/ruby/gems/shared
(which is wanted) and there are probably a few other places (which is more
like bug).

**Comment by nomadium** [comment]
Thanks, I was hoping that I could do the clean up with maven but that works OK.
