### ISSUE TITLE
psych gem should be default gem

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#2531]
there is this psych gem: https://github.com/tenderlove/psych/tree/jruby

* since it is not a default gem rubygems loading will ALLWAYS load the psych files from lib/ruby/stdlib (unless there is something special for psych)

* since I switched back to the old classloader parent first preference the snakeyaml.jar from the psych gem will be loaded into the JrubyClassloader but never be used since we bundle snakeyaml with jruby itself.

for me this psych should be an default gem to fix those two problems

**Comment by mkristian** [comment]
this is kind of 'egg or hen' problem:

https://github.com/mkristian/psych/tree/jruby-build

can build the gem but needs a jruby WITHOUT builtin psych to run the tests ! this jruby with psych as 
default needs the a gem from the above branch - started this with

https://github.com/jruby/jruby/tree/test-psych

**Comment by monkstone** [comment]
Since recent builds jruby 9.0.0.0-SNAPSHOT (2.2.0p0) 2015-02-27 5166bff OpenJDK 64-Bit Server VM 25.31-b07 on 1.8.0_31-b13 +jit [linux-amd64]
I am getting NameError: uninitialized constant Psych::Parser

**Comment by mkristian** [comment]
@monkstone could you tell me what exactly you are running. travis runs OK including psych tests.

**Comment by monkstone** [comment]
```ruby
require 'psych'

RP_CONFIG = Psych.load_file("/home/tux/.rp5rc")
p RP_CONFIG
```
where `.rp5rc` is
```ruby
---
PROCESSING_ROOT: "/home/tux/processing-3.0a5"
JRUBY: true
X_OFF: 50
Y_OFF: 20
```
prints
```bash
{"PROCESSING_ROOT"=>"/home/tux/processing-3.0a5", "JRUBY"=>true, "X_OFF"=>50, "Y_OFF"=>20} 
``` 
jruby-1.9
error with jruby-9000
```bash
NameError: uninitialized constant Psych::Parser
  const_missing at org/jruby/RubyModule.java:2937
         (root) at /home/tux/.gem/ruby/2.2.0/gems/psych-2.0.13/lib/psych/nodes/stream.rb:12
        require at org/jruby/RubyKernel.java:966
         (root) at /home/tux/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
        require at /home/tux/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
        require at org/jruby/RubyKernel.java:966
         (root) at /home/tux/.gem/ruby/2.2.0/gems/psych-2.0.13/lib/psych/nodes.rb:2
         (root) at /home/tux/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
        require at org/jruby/RubyKernel.java:966
        require at /home/tux/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
     __script__ at yaml_test.rb:1
```

**Comment by mkristian** [comment]
sorry for the late reply:

psych has native extension and you are using mri gems with native extension with jruby.

default gems will be ignored if there is regular gem is installed, i.e. jruby-9k starts using your psych-2.0.13 gem which you installed with MRI and this one does not work with JRuby.

a common GEM_HOME is OK, but at least separate it between MRI and JRuby.

**Comment by mkristian** [comment]
after a second thought - there is nothing we can do from the jruby side of things.
