### ISSUE TITLE
BigDecimal does not coerce properly during division

### ISSUE THREAD

**Issue by undefinedvalue** [jruby/jruby#2538]
BigDecimal raises an error when trying to divide by a non-numeric value, even if it defines #coerce. This is inconsistent with other numeric types and with the other operators in BigDecimal, which properly coerce the value.

Trivial example that reproduces the problem:
```ruby
class MyNum
  def *(other)
    33
  end

  def /(other)
    99
  end

  def coerce(other)
    [MyNum.new, self]
  end
end
```
```
> 10.to_d * MyNum.new
33
> 10.0 / MyNum.new
99
> 10.0.to_d / MyNum.new
MyNum can't be coerced into BigDecimal
```

**Comment by rtyler** [comment]
@undefinedvalue Can you tell us what version of JRuby you're executing this test case on?

**Comment by undefinedvalue** [comment]
1.7.10

**Comment by enebo** [comment]
Confirmed on both 1.7 branch and master.  1.9+ from a compay standpoint.  Added missing code from original report so it is easier to reproduce below:

```ruby
require 'bigdecimal'
require 'bigdecimal/util'

class MyNum
  def *(other)
    33
  end

  def /(other)
    99
  end

  def coerce(other)
    [MyNum.new, self]
  end
end

p 10.to_d * MyNum.new
p 10.0 / MyNum.new
p 10.0.to_d / MyNum.new
```

**Comment by philipmw** [comment]
Going from JRuby 1.7.10 to 1.7.11, subtraction breaks. In 1.7.11, both subtraction and division give `TypeError: MyNum can't be coerced into BigDecimal`, while multiplication and addition work.

**Comment by kares** [comment]
`*` and `/` should coerce fine since https://github.com/jruby/jruby/commit/8c2b5f587df4d8453eb60ef1b48cacd9431f9bc2
