### ISSUE TITLE
Incorrect error message when BigDecimal fails to coerce during comparison

### ISSUE THREAD

**Issue by undefinedvalue** [jruby/jruby#2539]
When attempting to compare a BigDecimal to an object that does not implement #coerce, the error message incorrectly indicates that the object is nil and the message has a typo.

```
> 10.to_d < "foo"
nil could not be coerced to BigDecmil
```
("BigDecmil" is a typo in the code)
https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/bigdecimal/RubyBigDecimal.java#L944

A correct message might be: "String can't be coerced into BigDecimal"

**Comment by kares** [comment]
fixed with https://github.com/jruby/jruby/commit/0ab74b735763fee50c407e184afb4a49376f5078 ... thanks for the report
