### ISSUE TITLE
Defining a top-level/main run method overrides Runnable.run

### ISSUE THREAD

**Issue by ajitgeorge** [jruby/jruby#2542]
at least in interop with `java.lang.Thread`, as the following code demonstrates:

```
def run 
  puts 'in def run'
  # super # invoking super allows the thread blocks to run 
end 

latch = java.util.concurrent.CountDownLatch.new(2)
t1 = java.lang.Thread.new { puts 'executing t1'; latch.count_down }
t2 = java.lang.Thread.new { puts 'executing t2'; latch.count_down }

t1.start
t2.start

success = latch.await(1, java.util.concurrent.TimeUnit::SECONDS) 
puts success ? 'succeeded' : 'failed'
exit (success ? 0 : 1)
```

I'm seeing this behavior on all JRuby 1.7 versions up to 1.7.18 as well as
1.6.8, using Oracle JDK 1.7.0_72.

The problem doesn't occur with Ruby threads, probably because no implicit `Runnable` is created.

Note that the `test-unit` gem [defines `run`](https://github.com/test-unit/test-unit/blame/master/lib/test-unit.rb) in such a way that only the first thread block never executes.

A workaround is to `undef run` right after requiring `test-unit`.

**Comment by MSNexploder** [comment]
Same issue on master (7951249519)

**Comment by kares** [comment]
its no longer the case with JRuby 9K due generate interface methods being bound directly
