### ISSUE TITLE
Dir.foreach does not allow encoding

### ISSUE THREAD

**Issue by djberg96** [jruby/jruby#2547]
jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) Client VM 24.51-b03 on 1.7.0_51-b13 +jit [Windows 7-x86]

MRI allows Dir.foreach to accept an encoding, but it seems JRuby does not:

    enc = Encoding::UTF_16LE
    p Dir.foreach(Dir.pwd)
    p Dir.foreach(Dir.pwd, encoding: enc) # ArgumentError with JRuby

~~However, see https://bugs.ruby-lang.org/issues/10815 as well.~~

**Comment by djberg96** [comment]
Ok, it seems I didn't understand the function prototype, so I've updated the example.

**Comment by headius** [comment]
Easy one to add...marking as beginner.
