### ISSUE TITLE
Move Fiber from ext to core

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#2548]
`Fiber` used to be an extension module that needed to be explicitly required, but now it's always included. Perhaps it should be moved from `ext` into the top level? Are there other modules which used to be extensions but are now are core and should be moved, now that we're focusing on 2.x?

**Comment by kares** [comment]
**thread.rb** and related (`Mutex` `Queue`) also **monitor.rb** are pre-loaded on MRI 2.x, yet they are not "officially" part of Ruby's core classes. it might be related to `require 'rubygems'` out-of-the-box ...

in the past (between 1.6 and 1.7) `RubyBigDecimal.class` was moved into the *ext* package, which kind of give a hard time to (the minority of) developers such as myself in supporting gems with native extensions (e.g. AR-JDBC) ... just so I can finally say it out loud :)

**Comment by chrisseaton** [comment]
I'm not sure what you're saying then - are you saying don't do it as it's not actually correct, or do it because it's better than they're part of the public API?

**Comment by kares** [comment]
it seems not correct but if it is to be done please consider doing it in a "Java-compatible" way - keeping a deprecated class on the original place that gets extended on the new one ...

**Comment by kares** [comment]
in MRI 2.5 `require 'fiber'` gets a `true` indicating that it isn't always loaded these days. same in JRuby 9.x
