### ISSUE TITLE
JRuby 1.7.11 not working in Windows 7 Enterprise version

### ISSUE THREAD

**Issue by ambirag** [jruby/jruby#2555]
JRuby 1.7.11
Window 7 Enterprise
Service Pack 1
64 bit OS
When JRuby bin is set to the PATH and any command that starts with jruby -S fails with the error given below. This is severely blocking us from moving our cucumber/watir-webdriver automation to JRuby.
This is perfectly working fine on Mac, Win2k3, Win2k8.

D:\dev\trunk\ui\test\cucumber>jruby -S gem install bundler -f -v 1.3.5
NameError: undefined local variable or method `??' for main:Object
  (root) at D:/dev/trunk/buildtools/jruby/1.7.11/lib/ruby/shared/rubygems/specification.rb:1
  require at org/jruby/RubyKernel.java:1085
  (root) at D:/dev/trunk/buildtools/jruby/1.7.11/lib/ruby/shared/rubygems.rb:1
      Gem at D:/dev/trunk/buildtools/jruby/1.7.11/lib/ruby/shared/rubygems.rb:1161
  require at org/jruby/RubyKernel.java:1085
  (root) at D:/dev/trunk/buildtools/jruby/1.7.11/lib/ruby/shared/rubygems.rb:114
    load at org/jruby/RubyKernel.java:1101
  (root) at file:/D:/dev/trunk/buildtools/jruby/1.7.11/lib/jruby.jar!/jruby/kernel19/rubygems.rb:1

**Comment by headius** [comment]
Can you test with a more recent JRuby version? We periodically verify JRuby on Windows and simple things like gem install should definitely be working.

**Comment by enebo** [comment]
I used all of 1.7.x on 64 bit win 7 for a majority of my testing.  I am guessing this was an env issue of some kind.  Since 1.7.x is EOL I am closing this.
