### ISSUE TITLE
File::Stat.file? behaves different with CRuby

### ISSUE THREAD

**Issue by islue** [jruby/jruby#2556]
$ cat stat.rb
f = File.open('access_log', 'w')
system 'mv', 'access_log', 'accesslog.1'
puts "f.stat.file? #{f.stat.file?}"

$ rvm use ruby-1.9.3-p392
$ ruby stat.rb 
f.stat.file? true

$ rvm use jruby-1.7.19
$ ruby stat.rb 
Errno::ENOENT: No such file or directory - access_log
    stat at org/jruby/RubyFile.java:471
  (root) at stat.rb:3

Is there any other way to determine if a moved file is a _file_?

**Comment by enebo** [comment]
This works on 9k and 1.7.x is EOL so we will never fix it there.  Resolving as WONTFIX.
