### ISSUE TITLE
RubyArray#flatten! uses `respond_to?` unlike the original [lotus]

### ISSUE THREAD

**Issue by PragTob** [jruby/jruby#2563]
Noticed while running through [`lotus/controller`](https://github.com/lotus/controller) for JRuby compatibility. 

On a fairly recent master master (updated an hour ago or so) the following behaviour is observable:

jruby-head:
```ruby
jruby-head :003 > [BasicObject.new].flatten!
NoMethodError: undefined method `respond_to?' for #<BasicObject:0x7c24d3f1>
	from org/jruby/RubyArray.java:2841:in `flatten!'
	from (irb):3:in `evaluate'
	from org/jruby/RubyKernel.java:1000:in `eval'
	from org/jruby/RubyKernel.java:1310:in `loop'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from org/jruby/RubyKernel.java:1120:in `catch'
	from /home/tobi/.rvm/rubies/jruby-head/bin/irb:13:in `__script__'
```

vs. 2.2.0:

```ruby
2.2.0 :006 > [BasicObject.new].flatten!
 => nil
```

This makes a spec in lotus/controller fail. 

This seems reasonably easy to fix - time is scarce as always but I'd love to give this a shot this weekend (will hopefully get to it) - but I gotta setup the whole JRuby project first, we'll see :) However, anyone - don't let that stop you! :)

On a larger scale, though - it seems like almost nothing should use `respond_to?` as a `BasicObject` might not have that.

Cheers,
Tobi

**Comment by lucasallan** [comment]
Hi @PragTob 
Any progress on this?

**Comment by PragTob** [comment]
Hey @lucasallan - no unfortunately not, no time. I'd still love to get my hands on this but no guarantees and even if I really pushed it would happen at the easter weekend at the earlies.

**Comment by lucasallan** [comment]
@PragTob no worries, let us know if you need any help.

**Comment by headius** [comment]
I'm sure this is just blindly dispatching to respond_to? rather than checking if it exists first. Will compare with MRI.

**Comment by deepj** [comment]
The problem lies in Lotus::Kernel.Array.
https://github.com/lotus/controller/blob/master/lib/lotus/controller/configuration.rb#L393

@headius you can isolate it via this test:

```
git clone git@github.com:lotus/controller.git
cd controller
bundle
ruby -Itest test/configuration_test.rb --name 'test_0003_raises an error if the given mime type cannot be coerced into string'
```
