### ISSUE TITLE
minitest/autorun raises on jruby9000

### ISSUE THREAD

**Issue by jrochkind** [jruby/jruby#2573]
~~~bash
$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~precise1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
$ javac -version
javac 1.7.0_75
$ ruby --version
jruby: warning: unknown property jruby.cext.enabled
jruby 9.0.0.0-SNAPSHOT (2.2.0p0) 2015-02-05 c804f97 OpenJDK 64-Bit Server VM 24.75-b04 on 1.7.0_75-b13 +jit [linux-amd64]
~~~

    require 'minitest/autorun'

in source seems to result in:

~~~
LoadError: load error: minitest -- java.lang.ClassCastException: java.lang.String cannot be cast to org.jruby.runtime.builtin.IRubyObject

require at org/jruby/RubyKernel.java:964
(root) at /home/travis/.rvm/gems/jruby-head/gems/minitest-5.5.1/lib/minitest/autorun.rb:8
require at org/jruby/RubyKernel.java:964
(root) at /home/travis/build/traject-project/traject/test/test_helper.rb:1
require at org/jruby/RubyKernel.java:964
(root) at /home/travis/build/traject-project/traject/test/test_helper.rb:2
~~~

This is just from travis output I haven't debugged further than that, but my test_helper.rb:2 is `require 'minitest/autorun'`.

**Comment by jrochkind** [comment]
(Also I dunno what's with `jruby: warning: unknown property jruby.cext.enabled`, that's appearing multiple times in travis output, but that's a different issue, and just a warning)

**Comment by jrochkind** [comment]
Also each line of stack trace reported by Travis has a bunch (90?) chars of `space` at the beginning of the line, which I had to edit out to paste in here readably. Different issue again, of course.

**Comment by jrochkind** [comment]
Weirdly, this did not happen again on second try. Something weird with travis jruby-head setup, or since it's getting 'head' perhaps there was another commit which resolved a mistake. Anyway, I think this can be closed.

**Comment by subbuss** [comment]
Please see discussion on #2491 and try on latest master, and can you confirm that this problem is fixed for you? Please reopen if not.

**Comment by jrochkind** [comment]
Thanks. For the record, for me my tests failed with above error output on c804f97 but were passing again next time travis ran, using a5fedf5.  I don't know what was up other than that.
