### ISSUE TITLE
JRuby 9.0.0.0.pre1 - uninitialized constant DATA

### ISSUE THREAD

**Issue by Ryccoo** [jruby/jruby#2575]
I could not find if this was reported before so I want to ask if DATA is missing on purpose or its a bug ?

Jruby 1.6.8 and 1.7.12 contain DATA constant but JRuby 9.0.0.0.pre1 end with:

<pre>
NameError: uninitialized constant DATA
  const_missing at org/jruby/RubyModule.java:2935
     __script__ at bm_app_erb.rb:7
</pre>

Source of bm_app_erb.rb can be found at [http://rubybench-rycco.rhcloud.com/implementations/bm_app_erb](http://rubybench-rycco.rhcloud.com/implementations/bm_app_erb)

**Comment by peperomeu** [comment]
In jruby 9.0.1.0 this error still exists.

If I execute this program
```Ruby
#coding: utf-8

DATA.each { |l| puts l }

__END__
ONE
TWO
THREE
```
it works with Ruby MRI, but not with jRuby.

    NameError: uninitialized constant DATA
      const_missing at org/jruby/RubyModule.java:3166
              <top> at test_data.rb:3

The version I've installed:

    jruby 9.0.1.0 (2.2.2) 2015-09-02 583f336 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b15 +jit [Windows 7-amd64]

    ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]

**Comment by kares** [comment]
```
ONE
TWO
THREE
```

output under *jruby 9.1.9.0 (2.3.3) 2017-05-15 28aa830 Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 +jit [linux-x86_64]*
