### ISSUE TITLE
JavaSupport refactoring API (byte-code) incompatibility with extensions

### ISSUE THREAD

**Issue by kares** [jruby/jruby#2585]
on 9K (recently - not in preview1) `JavaSupport` was changed from class to interface, such change for extension APIs is hard to support without re-compiling ... esp. hard to target 1.7 and 9K at the same time.

sample failure seen on travis-ci : 

```
 Java::JavaLang::IncompatibleClassChangeError: Found interface org.jruby.javasupport.JavaSupport, but class was expected
arjdbc.jdbc.DriverWrapper.loadDriver(DriverWrapper.java:77)
arjdbc.jdbc.DriverWrapper.<init>(DriverWrapper.java:49)
arjdbc.jdbc.RubyJdbcConnection.newDriverWrapper(RubyJdbcConnection.java:1709)
arjdbc.jdbc.RubyJdbcConnection.setDriverFactory(RubyJdbcConnection.java:1702)
arjdbc.jdbc.RubyJdbcConnection.setupConnectionFactory(RubyJdbcConnection.java:1813)
arjdbc.jdbc.RubyJdbcConnection.doInitialize(RubyJdbcConnection.java:512)
arjdbc.jdbc.RubyJdbcConnection.initialize(RubyJdbcConnection.java:504)
```
... coming from a simple: `runtime.getJavaSupport().loadJavaClassVerbose(name);`

such call is likely also in JRuby-OpenSSL that I know of (besides AR-JDBC), not sure for other extensions out there ... just wanted to let you guys know - as far as I see it's mostly [due mocking/truffle](https://github.com/jruby/jruby/commit/b4b70cd7caf8961bb84c3a3f031b7aec83d8f7a1)

**Comment by chrisseaton** [comment]
Yes this is to support AOT compilation of JRuby. I can do it with an abstract class as well though.

**Comment by kares** [comment]
@chrisseaton that would be a win-win ... thanks!

**Comment by kares** [comment]
compatibility restored at https://github.com/jruby/jruby/commit/bf8a55a707f23decad1d5fbb36336108b58a9010 ... thanks!
