### ISSUE TITLE
Setup a Windows CI (appveyor)

### ISSUE THREAD

**Issue by PragTob** [jruby/jruby#2590]
As Charlie and I learned at FOSDEM there is a free for open source Windows CI system called [appveyor](https://ci.appveyor.com) - I believe it'd be very beneficial to set up JRuby specs to run there.

I haven't had too much luck setting up shoes4 specs to run there yet (sometimes they run, sometimes they don't.. possibly related to #1614) - seems like a worthwhile task.

**Comment by rtyler** [comment]
@headius We talked about this at JRubyConf EU as it would turn out. This might be solved with @colinsurprenant and @elastic's help though.

**Comment by PragTob** [comment]
Would it be? :) I have to get back to my attempts to running shoes4 with appveyor, I did that during JRubyConf.EU but as it turned out it would still sometimes time out, most interestingly `gem install bundler` would then take forever (as in over 30 minutes) leading to a timeout. That seemed to be sort of a known problem, but they worked around it through pre installing bundler on the installed ruby, which doesn't help me much (installing JRuby from scratch).

On my todo: open an issue with appveyor.

**Comment by rtyler** [comment]
@PragTob FWIW JRuby/Gradle is tested just fine on Appveyor, so maybe it's time to switch shoes :-P

**Comment by PragTob** [comment]
@rtyler I started the effort months ago when I opened this issue, hasn't worked :( Now I opened an issue at appveyor and wait for their response... it's really the `gem install bundler` part so you don't seem to have it in your fancy groovy land ;P

**Comment by headius** [comment]
We set up an appveyor long ago, and then an Azure Pipelines CI rig, and now most of the other CI systems support Windows. As part of our next big Windows push, we'll add more CI runs there. This is stale, so I'm closing it.
