### ISSUE TITLE
RailsGirls Summer of Code 2015

### ISSUE THREAD

**Issue by BanzaiMan** [jruby/jruby#2607]
RailsGirls Summer of Code is looking for projects. http://railsgirlssummerofcode.org/guide/projects/

Any interest in getting involved?

(Aside: Are we going for GSoC this year? If so, is there conflict besides mentor time constraints?)

**Comment by enebo** [comment]
@BanzaiMan we have applied as an organization for GSoC and I can see some entries for Ruby's organization for JRuby.

**Comment by enebo** [comment]
@BanzaiMan No comment about whether there are enough mentors to go around and also do this or not.  Just letting you know that we applied :)

**Comment by headius** [comment]
I think it would be great to do RailsGirls this year! We may need to see if we're accepted, so we're not spreading too thin (I think this was Tom's concern) but we have a lot of interesting project ideas :-)

@BanzaiMan Perhaps after this week (GSoC org submissions have to be in by Friday) we should start looking into RGSoC?

**Comment by BanzaiMan** [comment]
@headius Sounds good to me!

**Comment by enebo** [comment]
I didn't mean to express concern I was just pointing out what other potential similar activities may be happening.  We didn't even get accepted for GSoC last year so I feel it is too soon to fret over too many slots.  With that said we need to start rounding up mentors...

**Comment by BanzaiMan** [comment]
OK, so let's talk about RGSoC.

Start with http://railsgirlssummerofcode.org/guide/projects/ and once we can commit to it, submit to https://github.com/rails-girls-summer-of-code/projects.

**Comment by BanzaiMan** [comment]
Sorry, this did not happen.
