### ISSUE TITLE
build improvements

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#2612]
just added a small wiki page to explain all the build a bit - from maven point of view

https://github.com/jruby/jruby/wiki/JRuby-Build----Some-Inside-Info

and found a few things which needs improvements:
- mave jruby-core:complete into its own artifact and make it an osgi bundle
- move jruby-stdlib into lib/
- use artifacts instead of lib/jruby.jar and lib/jruby-truffle.jar
- use test/check_versions.sh to check artifact size to detect "packaging errors" which blow up the archive size

@enebo @headius the wiki page is (mainly) meant for you before considering writing a bash script to build the distribution files ;)

**Comment by kares** [comment]
sounds like most of this is done, or is anything else really needed @mkristian ?

**Comment by mkristian** [comment]
all done :)
