### ISSUE TITLE
Object.const_get behaves differently from other implementations

### ISSUE THREAD

**Issue by commel** [jruby/jruby#2635]
This issue is a result from an error i encountered when adding kramdown to my rails app using JRuby 9.0.0.0-pre1 -> https://github.com/gettalong/kramdown/pull/228

Expected behavior:
```ruby
irb(main):001:0> Object.const_get('::String')
String
```

this works this way on the C-implementations.

Currently on JRuby 9.0.0.0-pre1
``` ruby
irb(main):001:0> Object.const_get('::String')
NameError: wrong constant name ::String
	from org/jruby/RubyModule.java:2863:in `const_get
```

**Comment by headius** [comment]
Weird...I thought for sure we fixed this.

**Comment by arlandism** [comment]
I think I found the problem here. I'll have a patch ready soon.

**Comment by nirvdrum** [comment]
This sounds oddly similar to #2090.

**Comment by kares** [comment]
https://github.com/jruby/jruby/issues/2739 is now on master
