### ISSUE TITLE
Truffle - Compile Error until when break in case statement

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2654]
This fails with the following error in Truffle but not in jruby or ruby 2.2
```ruby
       
       x = 0
       until x > 5
          test = "test"
          case
          when test == "hello"
             break unless test == "foo"
             puts "hello"
          when test == "te"
            if test == "false"
              raise "foo"
            end
            break
          else
            puts "else"
          end
          x += 1
      end
```
Error output
```
jruby: using Default Truffle Runtime
whenbreak.rb:13: Invalid break
whenbreak.rb: compile error (SyntaxError)
```
Expected output
```
else
else
else
else
else
else
```

**Comment by chrisseaton** [comment]
I didn't know you could do that!

This is likely an error in the translator, but I'm not sure what off the top of my head. It's strange that it's a syntax error though - as we run the same parser as JRuby and you say it works there.

**Comment by bjfish** [comment]
https://github.com/jruby/jruby/blob/4c1566b1dca7ee6488d3d2da6a2ed6163c36edde/truffle/src/main/java/org/jruby/truffle/translator/BodyTranslator.java#L352
while works fine
