### ISSUE TITLE
Jar-globbing test does not update mtime on CloudBees

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2655]
For whatever reason, the "Dir globs (Dir.glob and Dir.[]) respects jar content filesystem changes" spec added by @ratnikov does not see mtime update when running on CloudBees. See an example failure [here](https://projectodd.ci.cloudbees.com/view/JRuby/job/jruby-master-spec-ji/745/console); the timestamps are clearly the same even with a 5s delay and successful "zip" archive modification.

This same spec passes on Travis, which is also Linux. @enebo theorized there might be some filesystem quirks at play on CloudBees, but I have not investigated that.

Will commit shortly to disable this spec until we can figure out what's up with the 'Bees.

**Comment by kares** [comment]
re-enabled and pended on CloudBees only ... https://github.com/jruby/jruby/commit/3950c0962ffe256e34a9139ff1f25d007657c805#diff-fddfbb9687989d3b1dad1c62387a81a7R99
