### ISSUE TITLE
Homepage: Broken Link

### ISSUE THREAD

**Issue by gottlike** [jruby/jruby#2668]
I just noticed that the link to the JRuby 9000 release blog post is broken:

![screen](https://cloud.githubusercontent.com/assets/278766/6552897/1661e64a-c64b-11e4-995f-1aa0a8aa3843.png)

Someone linked to `/2014/` instead of `/2015/`...

**Comment by headius** [comment]
Will fix!

**Comment by headius** [comment]
Fixed in jruby/jruby.github.io@bb652431805e997d1f40615abe9102ecebd570fe
