### ISSUE TITLE
move RubyDate and joda-time into "extension" gem

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#2691]
a brief look into the code looks like it is possible to move all the code which uses joda-time into a gem which we can use in the same manner as jruby-readline.

advantage:
- you can decide on the joda-time version via jar-dependencies or jbundler or manually. so your required java libraries can decide which joda-time version to use without fiddling with classpath of jruby itself (kind of difficult with rvm and rbenv)
- reversing classloader.delegate will not produce errors regarding joda-time since all joda classes used by jruby living inside jrubyclassloader

disadvantage:
- extra gem

this is just an attempt to improve usefulness of this classloader.delegate and improve the overall classloader setup. other places are
- https://github.com/sparklemotion/nokogiri/pull/1212 which still needs some code changes
- https://github.com/jruby/jruby/issues/2587 - not sure what happens here, need to investigate and did not see the issue earlier

**Comment by nirvdrum** [comment]
Allowing arbitrary versions of joda to be used sounds like a bad idea.  We can't make any guarantees about compatibility with versions other than the one we support and I'd hate to see our support policy broaden to whatever version of joda.  If there's a classpath conflict, I suggest we shade joda and rename the package.

**Comment by mkristian** [comment]
joda classes are part of the jruby API so shading breaks any binary
compatibility. and this is actually the reason why the idea will probably
not work, you need joda to compile your code against jruby.

but for info it is easy to use another version of joda with the jruby maven
artifact, you might not even know that you are doing - or you ruby code
uses a library depending on joda (via jbundler) and you just use the joda
coming from jruby.

I can tell the same story with snakeyaml and give you a gem which depends
on an embedded snakeyaml but will "silently" not use the embedded jar. well
with the psych gem in 9k.pre2 this is history and that is where the idea
came from.

**Comment by kares** [comment]
with 9.2 only supporting Java 8 we could have been moving towards getting rid of joda-time.
of course due it being part of the API its not as simple.
am hoping providing Java 8 alternatives in the APIs such as RubyTime (and maybe doing deprecations).
anyway, I believe this issue is now pretty much defunct ...
