### ISSUE TITLE
Hash#inspect differs from MRI Ruby 2.2.1; This problem occurs if Hash has double-quoted UTF8 symbol key.

### ISSUE THREAD

**Issue by k77ch7** [jruby/jruby#2713]
The following test.rb differs from MRI Ruby 2.2.1 on JRuby master. 

test.rb
```
# encoding: utf-8
h = { "Ãa1": true }
p h
```

MRI Ruby 2.2.1
```
$ ruby ~/development/test.rb
{:Ãa1=>true}
```

JRuby master
```
$ jruby ~/development/test.rb
{:"Ãa1"=>true}
```

My env
```
jruby 9.0.0.0-SNAPSHOT (2.2.1) 2015-03-17 c9a5cca Java HotSpot(TM) 64-Bit Server VM 25.5-b02 on 1.8.0_05-b13 +jit [darwin-x86_64]
 ```

**Comment by enebo** [comment]
We (you) can fix this but I find MRI's output to be strange.  You would think their output on inspect would be valid Ruby syntax?  Makes me wonder if this is our bug or theirs?

**Comment by k77ch7** [comment]
I thought wrong.  I think that this cause is Symbol#inspect rather than Hash#inspect.
The following symbol_test.rb differs from MRI Ruby. The different result occurs in the case of UTF8 string symbol.

symbol_test.rb
```
# encoding: utf-8

p :"Ãa1".inspect
p :"a1".inspect
p :"1".inspect
```

MRI Ruby 1.9.3, 2.0.0, 2.1.4 and 2.2,1
```
$ ruby ~/development/symbol_test.rb
":Ãa1"
":a1"
":\"1\""
```

JRuby master and 1.7.19
```
$ jruby ~/development/symbol_test.rb
":\"Ãa1\""
":a1"
":\"1\""
```
