### ISSUE TITLE
how do I install with Jars? Re: "deprecated. use instead jars/installer" message

### ISSUE THREAD

**Issue by aplatypus** [jruby/jruby#2726]
Hi,

I came here from the thread_safe gem project, both projects are emitting the message:

    "deprecated. use instead jars/installer"

There's nothing fancy going on, apart from me using JRuby 9.0.0 at this point. The install commands:

*    jruby -S gem  install  jruby-jars
*    jruby -S gem install  addressable
*    jruby -S gem install thread_safe
*    jruby -S gem install concurrent-ruby

Produce this as output:

      jruby -S gem install addressable
      Fetching: addressable-2.3.7.gem (100%)
      deprecated. use instead jars/installer
      Successfully installed addressable-2.3.7
      1 gem installed

then 

      jruby -S gem  install  jruby-jars
      Fetching: jruby-jars-1.7.19.gem (100%)
      deprecated. use instead jars/installer
      Successfully installed jruby-jars-1.7.19
      1 gem installed

then

      jruby -S gem  install  thread_safe
      deprecated. use instead jars/installer
      Successfully installed thread_safe-0.3.5-java
      1 gem installed

and

      jruby -S gem  install  concurrent-ruby
      Fetching: concurrent-ruby-0.8.0-java.gem (100%)
      deprecated. use instead jars/installer
      Successfully installed concurrent-ruby-0.8.0-java
      1 gem installed

I'm unclear on where this message fits or how to 'resolve' this warning. A search of thread_safe and concurrent-ruby haven't revealed any specific instruction or comments.

What is the solution?

     JRuby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab 
     Java HotSpot(TM) 64-Bit Server VM 25.25-b02 on 1.8.0_25-b18 +jit 
     [Windows 7-amd64]

**Comment by mkristian** [comment]
I see, it just pops up the moment you have the jar-dependencies-0.2.0

will remove this message with the next release - not intended to confuse
users ;)

downgrade to jar-dependencies-0.1.8

**Comment by aplatypus** [comment]
@mkristian  - Thanks for that.  Yes it is very confusing because it often comes up in the middle of another Gem or dependencies, etc.
