### ISSUE TITLE
Regression in loading Java classes with upper case package names

### ISSUE THREAD

**Issue by donv** [jruby/jruby#2742]
Hi all!

It looks like we have a regression in loading Java classes with upper case package names.  Works fine in JRuby 1.7.19, but fails with JRuby 1.7 head:

```
$ cat org/TestApp/TestClass.java
package org.TestApp;

public class TestClass {
    public static void hello() {
        System.out.println("Hello!");
    }
}

$ javac org/TestApp/TestClass.java

$ rvm use jruby
Using /Users/uwe/.rvm/gems/jruby-1.7.19

$ ruby -J-Djruby.ji.upper.case.package.name.allowed=true -S irb
jruby-1.7.19 :001 > Java::org.TestApp.TestClass.hello
Hello!
 => nil 
jruby-1.7.19 :002 > exit

$ rvm use jruby-17-head
Using /Users/uwe/.rvm/gems/jruby-17-head

$ ruby -J-Djruby.ji.upper.case.package.name.allowed=true -S irb
jruby-17-head :001 > Java::org.TestApp.TestClass.hello
NameError: missing class name (`org.TestApp')
	from org/jruby/javasupport/JavaUtilities.java:54:in `get_proxy_or_package_under_package'
	from file:/Users/uwe/.rvm/rubies/jruby-17-head/lib/jruby.jar!/jruby/java/java_package_module_template.rb:14:in `method_missing'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1107:in `eval'
	from org/jruby/RubyKernel.java:1507:in `loop'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from /Users/uwe/.rvm/rubies/jruby-17-head/bin/jirb:13:in `(root)'
jruby-17-head :002 > RUBY_DESCRIPTION
 => "jruby 1.7.20-SNAPSHOT (1.9.3p551) 2015-03-22 e66cbd5 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13 +jit [darwin-x86_64]" 
```

**Comment by donv** [comment]
Can anyone confirm this issue, or is it just me?

**Comment by kares** [comment]
@donv will look into it ... just bare with me for a while :)

**Comment by donv** [comment]
Thanks @kares !

**Comment by donv** [comment]
Hi @kares !

Thanks for the fix.  The initial test case is now working with JRuby commandline, but I still have a failing test case in Ruboto, the one that initiated my report.

The test case is simple and fails consistently in my local work space, but succeeds in travis-ci.  I will investigate a bit more and come back to you.

**Comment by kares** [comment]
OK, thanks for the feedback @donv ... please be sure to let me know if there's any regression ...

for me running `test:jruby19` with `ji.upper.case.package.name.allowed=true` still shows one failure but that one pretty sure failed previously.I hoped for your case to be covered with the added test ;(

**Comment by donv** [comment]
Hi @kares !

It now looks like everything is OK.  I am not sure what changed, but my tests are green.

Consider this fixed.  I'll report if there is a regression.
