### ISSUE TITLE
Syntax error with file that has OK syntax with MRI 2.2

### ISSUE THREAD

**Issue by madis** [jruby/jruby#2744]
The exception ```SyntaxError in /Users/madis/.rvm/gems/jruby-9.0.0.0.pre1/gems/hairtrigger-0.2.12/lib/hair_trigger/builder.rb:468: syntax error, unexpected tLABEL_END``` occured when a dependency I am using was tried to get loaded by **jruby-9.0.0.0.pre**. When checking with **MRI 2.2.0** syntax was considered ok:
```
curl https://raw.githubusercontent.com/jenseng/hair_trigger/0e4c937ad9e1ed48797d1e376d241bdc61dfa140/lib/hair_trigger/builder.rb | ruby -c
```

Line reported to be erroneous: https://github.com/jenseng/hair_trigger/blob/0e4c937ad9e1ed48797d1e376d241bdc61dfa140/lib/hair_trigger/builder.rb#L468

**Comment by headius** [comment]
A reduced case:

```ruby
cond ? x + ')': ''
```

The parser seems to think the `')':` is a hash label rather than being separate tokens `')'` and ':' (for the ternary).

Parser bug for @enebo.
