### ISSUE TITLE
Support RUBY_ENGINE_VERSION

### ISSUE THREAD

**Issue by postmodern** [jruby/jruby#2746]
Rubinius has added support for `RUBY_ENGINE_VERSION` to help ruby switchers distinguish between the ruby version (1.9.3) and the implementation version (1.7.9). I think JRuby would also benefit from exposing this constant.

**Comment by postmodern** [comment]
See also https://github.com/postmodern/chruby/pull/329

**Comment by havenwood** [comment]
It would be really nice to have a cross-implementation, standard way of checking the `JRUBY_VERSION` equivalent. :+1:

**Comment by headius** [comment]
Seems like a good idea to me...RUBY_ENGINE + RUBY_ENGINE_VERSION is like JVM's java.vm.name and java.vm.version.

**Comment by enebo** [comment]
I did not notice this was created yesterday and made my own this morning (and then fixed it): #2751

Closing as dup.
