### ISSUE TITLE
RubyGems of JRuby1.7.19 is v2.4.5 (should be v2.1.9)

### ISSUE THREAD

**Issue by yousuketto** [jruby/jruby#2748]
I am using jruby of jruby-bin-1.7.19.zip.
JRuby 1.7.19 is using Rubygems v2.4.5.
```
C:\workspace\sandbox>jruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13 +jit [Windows 7-amd64]

C:\workspace\sandbox>gem -v
io/console not supported; tty will not be manipulated
2.4.5
```
but, rubygems of jruby1.7.19 should be v2.1.9.
https://github.com/jruby/jruby/blob/1.7.19/lib/ruby/shared/rubygems.rb#L11

in addition, I think this is cause outputting #1614 log.
https://github.com/rubygems/rubygems/blob/v2.4.5/lib/rubygems/user_interaction.rb#L7-L10

**Comment by headius** [comment]
We need to fix JRuby 1.7 to work properly with RG 2.4.5, which will involve fixes like those for #2788 and the jar file extension service fixes committed to master.

**Comment by headius** [comment]
FWIW, RG 2.4.5 should be working fine on master.

**Comment by headius** [comment]
RG 2.4.6 has been installed for 1.7 and appears to be passing all tests (including some from end-users).
