### ISSUE TITLE
Ruby ENV variables differing from Java ENV variables (Rails)

### ISSUE THREAD

**Issue by nguyent** [jruby/jruby#2760]
I have a rails app adding an environment variable in one of the initializers like so:

`ENV['TZ'] = 'UTC'`

When I start the application the ENV variable appears in Ruby, but not in the Java module.

### without passing in ENV variable

```ruby
$ rvm list
=> jruby-1.7.13 [ x86_64 ]

$ bundle exec rails c
pry(main)> Java::java.lang.System.getenv['TZ']
=> nil
pry(main)> ENV['TZ']
=> "UTC"
pry(main)> ENV.keys - Java::java.lang.System.getenv.keys
=> ["BUNDLE_ORIG_MANPATH", "TZ"]
```

### passing in ENV variable

```ruby
$ rvm list
=> jruby-1.7.13 [ x86_64 ]

$ TZ=UTC bundle exec rails c
pry(main)> Java::java.lang.System.getenv['TZ']
=> "UTC"
pry(main)> ENV['TZ']
=> "UTC"
pry(main)> ENV.keys - Java::java.lang.System.getenv.keys
=> ["BUNDLE_ORIG_MANPATH"]
```

I found this ticket here: https://jira.codehaus.org/browse/JRUBY-1579 , but it still seems to be an unresolved issue. I saw Jay's comment about the inability to promote ENV variables from inside the JRuby process, and wanted to know if this is still the case. 

If so, it might be easier to have capistrano supply the ENV variable, but it would be nice to be able to do this in code.

**Comment by mkristian** [comment]
the code snippet looks OK to me.

I am quite sure that you can not change environment variables java sees via ```java.lang.System.getenv```

then JVM can run several JRuby runtimes. suppose one runtime sets ```ENV['TZ'] = 'UTC'``` and the other sets ```ENV['TZ'] = 'GMT'``` and both runtimes uses the underlying ```java.lang.System.getenv```

**Comment by nguyent** [comment]
That makes sense, thanks for responding.
