### ISSUE TITLE
IO.copy_stream doesn't rewind the destination

### ISSUE THREAD

**Issue by janko-m** [jruby/jruby#2762]
I mean, I wouldn't normally expect that `IO.copy_stream` would rewind the destination, but MRI does it, and we're currently relying on that behaviour in Refile (although we will add the rewind now). Just to help you to be the closest to MRI :)

```rb
# MRI 2.2.0
require "stringio"
require "tempfile"
file = Tempfile.new('foo')
IO.copy_stream(StringIO.new('foo'), file)
file.eof? #=> false (it's on the beginning)
```

```rb
# JRuby 9.0.0.0.pre1
require "stringio"
require "tempfile"
file = Tempfile.new('foo')
IO.copy_stream(StringIO.new('foo'), file)
file.eof? #=> true
```

**Comment by headius** [comment]
Thanks for the report!

**Comment by headius** [comment]
This looks like a bug in MRI, probably when using copy_stream with Tempfile. Here it is with a normal file, showing that it definitely does not rewind:

```
$ rvm ruby-2.2 do ruby -e "f1 = File.open('pom.xml'); f2 = File.open('tmp.txt', 'r+'); IO.copy_stream(f1, f2); p f2.eof?, f2.pos"
true
24619
```

I believe this is actually a bug in MRI.

**Comment by headius** [comment]
Filed as https://bugs.ruby-lang.org/issues/11015 so we'll see what MRI says.

**Comment by janko-m** [comment]
They seem to have fixed it. Thanks!
