### ISSUE TITLE
[Truffle] Private method error

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2770]
I am getting the following error with this sample code below. I apologize if this is something we haven't implemented yet. I was not sure.

Code:
```ruby
module Example

  class << Example

    private
  
    def append_features(mod)
      puts "Hello"
      super
    end
  
  end

end

class Example2
  include Example
end 

puts "Done"
```
Error:
```
rang.rb:17:in `include': private method `append_features' called for org.jruby.truffle.runtime.core.RubyClass@19d6ba35(Module) (NoMethodError)
	from rang.rb:17:in `Example2'
	from rang.rb:16:in `<main>'
```

Expected output (jruby, ruby):
``` 
Hello
Done
```

**Comment by bjfish** [comment]
@chrisseaton this error was from rubysl-singleton , so that library might work now

**Comment by bjfish** [comment]
Oops,I just remembered there is     undef_method  there too which i comented out.

**Comment by chrisseaton** [comment]
There seem to be quite a few issues preventing `singleton` from working at the moment - no specs passed straight away.
