### ISSUE TITLE
unknown type of %string

### ISSUE THREAD

**Issue by inawlaljar** [jruby/jruby#2771]
Hi, 

Have noticed that if I write s = %i(a, b, c), jruby throws an error. 

irb
s = %i(a, b, c)

Or use doorkeeper gem and run the rails s on development machine. 

What is the work around? 

Cheers,
Raj

**Comment by headius** [comment]
I believe this was added after Ruby 1.9.3, so it is not supported in JRuby 1.7.x. It does work in JRuby 9000.
