### ISSUE TITLE
Missing stop function in JRuby main

### ISSUE THREAD

**Issue by torsten-liermann** [jruby/jruby#2774]
Hi, (sorry, no english)

when starting from my java code a jruby application (like logstash) via instantiating org.jruby.Main and call run(....), I'm missing the part stop(). Is there a clean way to stop the "Main", to, for example, redeploy the enclosing application  trouble-free (terminating jruby child thread and so on)?

Thanks, Torsten!

**Comment by headius** [comment]
No applications should be using Main to launch JRuby instances, unless they're actually running JRuby as the only application on that JVM. Running through Main only does teardown on completion and does JVM-damaging things like taking over stdio and doing hard process exits.

If you want to have an embedded JRuby, we strongly recommend the use of ScriptingContainer. If you must go deeper with your integration, use Ruby.newInstance methods to get your own JRuby runtime. See the wiki for examples of embedding JRuby.

Have fun!
