### ISSUE TITLE
Undefined group option during parse of mri/test_regexp.rb

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2777]
The following regexp does not parse/compile: `/\A((x)|(y))(?(2)y|x)\z/`

Here's the error it produces:

```
[] ~/projects/jruby $ jruby -c test/mri/ruby/test_regexp.rb 
SyntaxError in (RegexpError) undefined group option: /\A((x)|(y))(?(2)y|x)\z/
```

As you can see this prevents test_regexp.rb from running. It has not been running for over a year (excluded from test:mri run) and we should really fix this for 9k final.

**Comment by lopex** [comment]
Onigmo merge: https://github.com/ruby/ruby/commit/0424e152c684a85f4b0691f1e84aec203115333d

**Comment by lopex** [comment]
Implemented in https://github.com/jruby/joni/commit/8d413933ea52fe6634994b1c80460b139326ceb8, conditionals specific tests pending...

**Comment by headius** [comment]
Working on getting test_regexp going now, and then I'll resolve this.

**Comment by headius** [comment]
joni 2.1.6-SNAPSHOT has been deployed.
