### ISSUE TITLE
[Truffle] Expected Absolute Value for Fixnum

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2781]
Code Example:
```ruby
puts (-2**63).abs
```

Expected:
```
9223372036854775808
```
Actual
```
-9223372036854775808
```

**Comment by chrisseaton** [comment]
This is caused by `FixnumNodes.AbsNode` not checking for overflow.

**Comment by bjfish** [comment]
@chrisseaton I could try to fix this if you haven't started on it

**Comment by chrisseaton** [comment]
Go for it.
