### ISSUE TITLE
rindex() fails on strings read from binary files

### ISSUE THREAD

**Issue by e2** [jruby/jruby#2784]
Fails on jruby-head, works on jruby-1.7.19

```ruby
IO.write("data", ":/c")

data = File.open("data", "rb").readlines.first.split(':').last     # => "/c"

result = data.rindex("c")   # => should be 1, but is nil on jruby-head

fail "expected 1, got: #{result.inspect}" unless result == 1
```

Expected: no failure
Actual: failure on jruby-head (because `rindex` returns nil)

JRuby: jruby 9.0.0.0-SNAPSHOT (2.2.1) 2015-03-30 8d7c1b1 OpenJDK 64-Bit Server VM 24.75-b04 on 1.7.0_75-b13 +jit [linux-amd64]

**Comment by headius** [comment]
Appears to work after my recent encoding fixes, which included a rewrite (ported from MRI) of String#rindex. We'll call this fixed, but please test updated jruby-head and let us know if you see any further issues.

**Comment by e2** [comment]
Sure - will do. And thanks so much @headius for all your work!
