### ISSUE TITLE
`loop` allocates needless memory

### ISSUE THREAD

**Issue by ecin** [jruby/jruby#2785]
Version: `jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.7.0_72-b14 +jit [darwin-x86_64]`

Also reproducible on Java 8 (`1.8.0 b25-b17`).

Using `loop` seems to allocate needless memory when compared to `while true`:

```ruby
require "java"
require "jruby"

thread = Thread.new { loop { } }
native_thread = JRuby.reference(thread).native_thread

thread_bean = java.lang.management.ManagementFactory.thread_mx_bean
loop { puts thread_bean.get_thread_allocated_bytes([native_thread.id].to_java(:long))[0]; sleep 1 }
# outputs ever increasing number
```

`Thread.new { while true; end }` does not cause the same unexpected memory allocation.

**Comment by headius** [comment]
Both JRuby 1.7 and 9k do have some allocation for every block invocation, usually to box arguments into an array used by our block argument logic to assign local variables. However, this particular case seems like it shouldn't need to allocate anything; the block is created once, and it receives no arguments.

**Comment by headius** [comment]
Hmm...I am confused. I do not see this allocation happening when I run your script with JRuby 1.7.19 and 9k (master):

```
[] ~/projects/jruby $ jruby -v blah.rb
jruby 9.0.0.0-SNAPSHOT (2.2.1) 2015-03-30 31451d2 Java HotSpot(TM) 64-Bit Server VM 25.40-b23 on 1.8.0_40-ea-b19 +jit [darwin-x86_64]
18032
21272
21272
21272
21272
21272
21272
21272
21272
21272
^C
[] ~/projects/jruby $ rvm jruby-1.7.19 do jruby -v blah.rb
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-ea-b19 +jit [darwin-x86_64]
38968
41744
41744
41744
41744
41744
41744
41744
41744
41744
^C
```

We need from you:

* Your results from running this script
* Do a run with -J-Xrunhprof:depth=0 (JVM flag for profiling allocations). You'll get a file called java.hprof.txt whenever you Control-C the process. At the bottom is a histogram of allocated objects; look for the top 10-20 lines and report them to us.

**Comment by headius** [comment]
You may also be running this in the interpreter. Do you have the --dev flag or -X-C flag set for your JRuby runs?

**Comment by nirvdrum** [comment]
@ecin Any update?

**Comment by headius** [comment]
Closing because I don't believe this is really an issue and the reporter seems to have gone away.
