### ISSUE TITLE
Jruby to use upcoming jnr-ffi release to have ppc64le TypeAliases

### ISSUE THREAD

**Issue by ayappanec** [jruby/jruby#2790]
Recently jnr-ffi master branch is updated with ppc64le specific TypeAliases. Older versions don't have ppc64le specific TypeAliases due to which we are not above to invoke hbase shell in ppc64le.

[ayappan@soe07-vm3 bin]$ ./hbase shell
include_class is deprecated. Use java_import.
include_class is deprecated. Use java_import.
include_class is deprecated. Use java_import.
Apr 01, 2015 6:09:35 AM jnr.ffi.provider.jffi.NativeRuntime buildNativeTypeAliases
SEVERE: failed to load type aliases: java.lang.ClassNotFoundException: jnr.ffi.provider.jffi.platform.unknown.linux.TypeAliases
NoMethodError: undefined method `getTerminal' for Java::Jline::Terminal:Module
  refresh_width at /home/ayappan/hbase/hbase-shell/src/main/ruby/shell/formatter.rb:33
     initialize at /home/ayappan/hbase/hbase-shell/src/main/ruby/shell/formatter.rb:46
         (root) at /home/ayappan/hbase/bin/../bin/hirb.rb:128

So jruby has to pickup the upcoming jnr-ffi version to have ppc64le support

**Comment by headius** [comment]
@ayappanec I have been away from JNR stuff for a bit...what's the status of the ppc64le support? Have you managed to sort out remaining issues to get it to load and work?

**Comment by ayappanec** [comment]
@headius As of today, i remember three issues made jruby not able to get loaded and working in ppc64le First issue, missing of libjffi binaries is resolved. Second is this TypeAliases issue here. One more issue is the missing types.conf ( https://github.com/jruby/jruby/pull/1897 ). This is fixed in master branch but not in jruby-1_7 branch. It's good that we have the fix in jruby-1_7 branch as well.

**Comment by headius** [comment]
I'm spinning releases as we speak to get this all into 1.7.20. If anyone interested can verify that PPC64[LE] are working on jruby-1_7 branch, I'd _really_ appreciate that.

**Comment by headius** [comment]
Done deal! jffi, jnr-ffi, jnr-posix, jnr-constants, jnr-enxio, and jnr-unixsocket have all been released, and JRuby master and jruby-1_7 branches updated to use them.
