### ISSUE TITLE
FreeBSD TestPTY#test_commandline fails

### ISSUE THREAD

**Issue by bgalbrecht** [jruby/jruby#2793]
On FreeBSD 10.1 release, after building jruby 9.0.0.0, running 
bin/jruby -S rake test:mri
I get the following error:
[4359/6445] TestPTY#test_commandline = 0.00 s                                              
  2) Error:
TestPTY#test_commandline:
NoMethodError: private method `spawn' called for PTY:Module
    /usr/home/bruce/jruby-dev/jruby/test/mri/test_pty.rb:42:in `test_commandline'

**Comment by bgalbrecht** [comment]
bin/jruby -v
jruby 9.0.0.0-SNAPSHOT (2.2.1) 2015-04-01 dc85f30 OpenJDK 64-Bit Server VM 24.76-b04 on 1.7.0_76-b13 +jit [FreeBSD-amd64]

**Comment by bgalbrecht** [comment]
I can't tell about openbsd, but netbsd, freebsd, and dragonflybsd all have forkpty in libutil.  The libutil check in lib/ruby/stdlib/pty.rb is wrong.  When I changed the logic to 
 if FFI::Platform.linux? || (FFI::Platform.bsd? && ! not FFI::Platform.mac?)
it worked on FreeBSD, but I have no access to a mac to validate for it.

**Comment by bgalbrecht** [comment]
In looking at the 1.7.x branches, I see the code is wrong there also.

**Comment by headius** [comment]
The fix looks good. I will apply it to both 1.7 and master. Thank you!
