### ISSUE TITLE
Load/require logic lacks path caching and indexing found in MRI

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2794]
MRI has a number of caches and indexes that improve the performance of load/require searching. We lack most of those caches, or have poor implementations of them.

The two key bits I know of:
- The entries in the load path are made into absolute paths and held in a separate index used for file resolution.
- The resolved requires are absolutized for LOADED_FEATURES and a mapping is maintained between the require name and the absolute name. This index is updated whenever LOADED_FEATURES is seen to have changed.

We need to implement our loading logic so that it performs similar mappings, both to improve lookup performance and to better match MRI behavior with regards to full paths.

This may push to post-9k since it does not fix any known compatibility issues.

**Comment by mkristian** [comment]
```
jruby -e '$LOAD_PATH.each { |d| print d; puts File.exists?( d ) }'
```
shows two non-existing directories on the default load_path (only one for jruby-1.7.x). 

this index should take into account that load_path entries do not exist ?!

**Comment by headius** [comment]
What the...ok, those aren't even valid paths. Something's off.

**Comment by headius** [comment]
Oops, I thought the true/false were part of the path.

But yeah, there's no reason to add paths that don't even exist.

**Comment by headius** [comment]
Circling back to the two non-existent paths:

site_ruby turns out to be very important, as RubyGems uses it to know where to insert gem libs into the load path. Whether it exists or not, we need it there for RG.

The other path was our old "shared" stdlib dir that doesn't exist now, so I removed it.

**Comment by headius** [comment]
Here's what I came up with: https://gist.github.com/headius/94511fa81a28733787f0

The logic in resetLastErrorPreamble/Postamble is duplicated from buildEnsureNode. Both buildEnsureNode and buildRescueNode (the top-level versions) put this pre/post logic around the entire begin+rescue+etc.

There are a few issues, obviously:

* @subbuss had been working to make $! resetting happen exactly where it needed to, but in this case that would have required doing it for every RescueBody. This returns us to a single big try/finally around the whole of rescue/ensure logic.
* There are places where we restore $! that are obviated by this change.
* It adds another BB and another exception region.

This is deeper into IR than I've gone before, so I'd like some comments and review on this. I will push a PR to see if it passes (it passed what I tried locally and fixes the original issue).

**Comment by headius** [comment]
I'm also seeing a lot of this when I run with -d... I think we've got some problems with circular require logic or we're simply warning too much:

```
/Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - /Users/headius/projects/jruby/lib/ruby/stdlib/ant/ant.rb
                      require at org/jruby/RubyKernel.java:941
                      require at /Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
                        <top> at /Users/headius/projects/jruby/lib/ruby/stdlib/ant/target.rb:2
                      require at org/jruby/RubyKernel.java:941
                      require at /Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
                        <top> at /Users/headius/projects/jruby/lib/ruby/stdlib/ant/ant.rb:1
                      require at org/jruby/RubyKernel.java:941
                      require at /Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
                        <top> at /Users/headius/projects/jruby/lib/ruby/stdlib/ant/ant.rb:10
                      require at org/jruby/RubyKernel.java:941
                      require at /Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
                        <top> at /Users/headius/projects/jruby/lib/ruby/stdlib/ant.rb:1
                         load at org/jruby/RubyKernel.java:959
                       (root) at /Users/headius/projects/jruby/lib/ruby/stdlib/ant.rb:64
                       (root) at /Users/headius/projects/jruby/rakelib/commands.rake:1
                       (root) at /Users/headius/projects/jruby/rakelib/commands.rake:3
                       (root) at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/rake_module.rb:1
       block in load_rakefile at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/rake_module.rb:28
                         load at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/default_loader.rb:10
                 load_imports at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:767
   block in raw_load_rakefile at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:697
                load_rakefile at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:94
  standard_exception_handling at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:176
                        <top> at /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:93
                         load at org/jruby/RubyKernel.java:959
                        <top> at /Users/headius/projects/jruby/bin/rake:23
```

**Comment by headius** [comment]
This was not supposed to be closed. Bad commit.

**Comment by headius** [comment]
From #408, the original MRI bug for this feature was in http://bugs.ruby-lang.org/issues/5767

**Comment by headius** [comment]
The pain...the pain of reading CRuby code. But this is close. PR coming soon.

**Comment by headius** [comment]
Work continues on this but it will move to 9.2.8. The basic caching logic has been translated from MRI but it's poorly-adapted to Java and JRuby. I will rewrite it before submitting a PR.

**Comment by headius** [comment]
Most of this logic was "ported" in #5764. There may be additional improvements possible.
