### ISSUE TITLE
[Truffle] Error in extending Module

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2804]
Example Code
```ruby

module Module1

  def self.extend_object(cl)
    super
    cl.bind(self)
  end

  def bind(cl)
    self.module_eval %[
      def self.included(mod)
        mod.extend Module1
      end
    ]
  end

  def Raise(err = nil, *rest)
    puts "Raise"
  end

end

module Module2
  extend Module1
end

class Example
  include Module2

  def raise_error
    Example.Raise
  end

end

Example.new.send(:raise_error)
```
Error
```
matrix.rb:31:in `method_missing': undefined method `Raise' for Class (NoMethodError)
	from matrix.rb:31:in `raise_error'
	from matrix.rb:36:in `send'
	from matrix.rb:36:in `<main>'
```
Expected (ruby,jruby)
```
Raise
```
Example is used in stdlib matrix

**Comment by chrisseaton** [comment]
A smaller test case is

```ruby
module Module1

  def self.extend_object(cl)
    puts 'here'
  end

end

module Module2
  extend Module1
end
```

The problem is that we implement `extend` as doing the actual extension, where it should call `extend_object`, which does it.

There are loads of methods like this - `included` is another example - that we need to implement.

**Comment by bjfish** [comment]
TODO untag failing matrix specs once this is ready e2d3abd9538ea5440544acb72448ace0bfe7943f

**Comment by bjfish** [comment]
Singleton should work once we have `extend_object`. Current failing example:
```ruby
module Example
  
  class << Example

    private

    undef_method :extend_object

  end

end

```

**Comment by chrisseaton** [comment]
@eregon please take a look since you know the module system better than most

**Comment by eregon** [comment]
This should probably use `extended` and the `module_eval` seems unnecessary, but we have to support these semantics anyway.
I'll have a quick look tomorrow.

**Comment by eregon** [comment]
Fixed.

**Comment by eregon** [comment]
Also untagged matrix in e2c64c6, thanks for you work!

**Comment by bjfish** [comment]
@eregon :+1: thanks!
