### ISSUE TITLE
jgem jruby-9000 not recognised as ~> 2.0.0

### ISSUE THREAD

**Issue by monkstone** [jruby/jruby#2813]
When trying to install a local gem with jgem (jruby-9000) with requirement for at least 2.0.0 ruby version install fails not reqd version level. However jruby -S gem for same gem works fine.

**Comment by headius** [comment]
Could you tell us what gem it is? JRuby 9000 should report RUBY_VERSION as 2.2 and pass any 2.0.0 requirements easily.

**Comment by monkstone** [comment]
The gem was one of my own jruby_art, but it is available as from rubygems `gem install jruby-art --pre`. To be clear I was using both jruby and jgem from the build directory (fully qualified path to jruby 9000).
`jgem --version` 2.1.9
`jruby --version` jruby 9.0.0.0-SNAPSHOT (2.2.1) 2015-04-15 7e4e64f OpenJDK 64-Bit Server VM 25.40-b23 on 1.8.0_40-b20 +jit [linux-amd64]

**Comment by headius** [comment]
The following appears to work correctly on master (to be 9k.rc2) so I'm going to call this fixed. This code mimics RubyGems' own logic for checking Ruby versions.

If you still have the problem, please provide a gem that fails to install against JRuby master (or 9k.rc1) so we can reproduce the issue.

```
$ jruby -e "p Gem::Requirement.create('>=2.0.0').satisfied_by? Gem.ruby_version"
true
```

**Comment by monkstone** [comment]
@headius confirmed as fixed on latest Snapshot
