### ISSUE TITLE
UnboundMethod#parameters for an assignment method wrongly returns blank array

### ISSUE THREAD

**Issue by myronmarston** [jruby/jruby#2816]
```
➜  rspec-mocks git:(master) ✗ chruby 2.1
➜  rspec-mocks git:(master) ✗ ruby -v -e 'puts Class.new { attr_accessor :foo }.instance_method(:foo=).parameters.inspect'
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin12.0]
[[:req]]
➜  rspec-mocks git:(master) ✗ chruby jruby
➜  rspec-mocks git:(master) ✗ ruby -v -e 'puts Class.new { attr_accessor :foo }.instance_method(:foo=).parameters.inspect'
jruby 1.7.8 (1.9.3p392) 2013-11-14 0ce429e on Java HotSpot(TM) 64-Bit Server VM 1.6.0_65-b14-462-11M4609 [darwin-x86_64]
[]
```

rspec-mocks relies upon `parameters` for verifying doubles to ensure the method signature of the real object supports the provided arguments, and it's not working properly for assignment methods on JRuby due to this bug (see rspec/rspec-mocks#919).

**Comment by nirvdrum** [comment]
I don't have much to add to this, but wanted to note that it's still a problem in 1.7.19.

**Comment by myronmarston** [comment]
It also looks like it's not a problem with manually defined `def foo=`:

```
➜  rspec-core git:(master) ✗ ruby -v -e 'puts Class.new { def foo=(v); @foo = v; end }.instance_method(:foo=).parameters.inspect'
jruby 1.7.8 (1.9.3p392) 2013-11-14 0ce429e on Java HotSpot(TM) 64-Bit Server VM 1.6.0_65-b14-462-11M4609 [darwin-x86_64]
[[:req, :v]]
```

So apparently it's only a problem with `attr_accessor` and `attr_writer`-generated methods.

**Comment by enebo** [comment]
I fixed thereported problem but I noticed this uncovered a class of potential methods where we are not properly reporting back parameter data.  I opened up #2817 to track that.  Tests should follow with that issue as well.

**Comment by myronmarston** [comment]
Thanks for the prompt fix, @enebo!

**Comment by doozr** [comment]
Excellent news, thanks @enebo
