### ISSUE TITLE
Bad nonlocal return with re-wrapped define_method block

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2833]
This example should print out `:here` but it does not, because the non-local return in the define_method block causes the `test` method to return early.

```ruby
class Foo
  def define(name, &block)
    class << self; self; end.send(:define_method, name, block)
  end
 
  def define2(name, &block)
    define(name, &block)
  end
 
  def test
    define(:foo) { return 1 }
    call_foo
    puts :here
  end
 
  def call_foo
    foo
  end
end
 
Foo.new.test
```

This is causing mocha's test suite to bail out prematurely.

**Comment by enebo** [comment]
Changing this method from:

```ruby
  def define(name, &block)
    class << self; self; end.send(:define_method, name, block)
  end
```

to

```ruby
  def define(name, &block)
    class << self; self; end.send(:define_method, name, &block)
  end
```
Makes this code work.  So procizilation is breaking this somehow.

**Comment by enebo** [comment]
Reduced case:
```ruby
a = proc { return 1 }
define_method(:foo, a)
p foo
```

**Comment by enebo** [comment]
This seemingly is not an IR bug but one where we did not convert the incoming proc into a lambda.  I am not 100% sure how this changes the flow control nature of the problem but I saw no reason why we should be obeying proc rules for a block which now the body of a method.  Nothing failed with this change.
