### ISSUE TITLE
[Truffle] Method not added during instance_eval for MRI Test Excludes

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2838]
Example
```ruby
class TestBase64
end
klass = TestBase64
klass.instance_eval do
              def exclude(name, reason)
                puts "excluding #{name}"
              end
end
klass.class_eval 'exclude :test_decode64, "needs investigation"'
```
Expected
```
ruby exclude.rb 
excluding test_decode64
```
Actual
```
~/Documents/jruby-mine/bin/jruby -X+T exclude.rb 
(eval):1:in `method_missing': undefined method `exclude' for TestBase64:Class (NoMethodError)
	from (eval):1:in `<main>'
	from exclude.rb:9:in `<main>'

```

**Comment by eregon** [comment]
Known issue, it is very difficult to find the proper class to define in this kind of context.
Workaround: use `def klass.exclude(name, reason)` here.

**Comment by bjfish** [comment]
I'm using the workaround locally but won't be able to make the change to the minitest/unit.rb

**Comment by eregon** [comment]
I could potentially ask to make the change in ruby/ruby.

**Comment by eregon** [comment]
I committed a workaround in ff7a1d0605083ade1f21c540c2e96a87cf75df81.
I'll close this as we have specs to remind ourselves we don't do well on instance_eval on modules yet.
