### ISSUE TITLE
Date#next_year difference behvior with MRI

### ISSUE THREAD

**Issue by gazay** [jruby/jruby#2867]
> bug from AS rails tests

Seems to related to https://github.com/jruby/jruby/issues/1769

```ruby
# jruby master
irb(main):002:0> require 'date'
=> true
irb(main):003:0> Date.new(1581,10,10).next_year
=> #<Date: 1582-10-20 ((2299166j,0s,0n),+0s,2299161j)>

# ruby 2.2.2
irb(main):002:0> require 'date'
=> true
irb(main):003:0> Date.new(1581,10,10).next_year
=> #<Date: 1582-10-04 ((2299160j,0s,0n),+0s,2299161j)>
```

**Comment by headius** [comment]
This could be simple so I'm marking for beginners.

**Comment by raeoks** [comment]
It seems like a good bug to get started.
@eregon had already posted a solution at #1769, but he also mentioned that it's likely to be fairly slow.
@headius Let me know if you something like that in mind.

**Comment by headius** [comment]
I'm not concerned about the performance if we can get a fix in for this for JRuby 9k RC2. @eregon or @raeoks, can you make a PR so we can wrap this up?

**Comment by eregon** [comment]
I'll let @raeoks take care of it since he already worked on adding tests/specs.

**Comment by eregon** [comment]
Fixed by #3157 and #3091.

**Comment by eregon** [comment]
Thanks @raeoks for your contribution and the specs!

**Comment by raeoks** [comment]
@eregon It's been a pleasure to work on JRuby. Next I'll move on to another `beginner` bug.
