### ISSUE TITLE
BigDecimal can not be copied

### ISSUE THREAD

**Issue by gazay** [jruby/jruby#2868]
> bug from rails tests

Missed `initialize_copy` for BigDecimal.

```ruby
require 'bigdecimal'
BigDecimal.new(1).dup
```

MRI 2.2.2 output:
```ruby
#<BigDecimal:7fdd1d01c910,'0.1E1',9(27)>
```

Jruby output:
```
TypeError: can't copy BigDecimal
	from org/jruby/RubyNumeric.java:584:in `initialize_copy'
	from org/jruby/RubyKernel.java:1883:in `initialize_dup'
	from org/jruby/RubyKernel.java:1913:in `dup'
	from (irb):8:in `<eval>'
	from org/jruby/RubyKernel.java:1005:in `eval'
	from org/jruby/RubyKernel.java:1315:in `loop'
	from org/jruby/RubyKernel.java:1125:in `catch'
	from org/jruby/RubyKernel.java:1125:in `catch'
	from /Users/alex/code/opensource/jruby/bin/irb:13:in `<top>'
```

Failing test in ActiveSupport:
https://github.com/rails/rails/blob/master/activesupport/test/core_ext/object/duplicable_test.rb#L21
This code testing `Object` extension here: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/duplicable.rb#L81

Backtrace:
```
DuplicableTest#test_duplicable:
TypeError: can't copy BigDecimal
    org/jruby/RubyNumeric.java:584:in `initialize_copy'
    org/jruby/RubyKernel.java:1883:in `initialize_dup'
    org/jruby/RubyKernel.java:1913:in `dup'
    rails/activesupport/test/core_ext/object/duplicable_test.rb:22:in `block in test_duplicable'
    rails/activesupport/lib/active_support/test_case.rb:82:in `assert_nothing_raised'
    rails/activesupport/test/core_ext/object/duplicable_test.rb:22:in `block in test_duplicable'
    org/jruby/RubyArray.java:1571:in `each'
    rails/activesupport/test/core_ext/object/duplicable_test.rb:20:in `test_duplicable'
```

Re-run test from `activesupport` directory with: `ruby -w -Itest test/core_ext/object/duplicable_test.rb -n test_duplicable`

**Comment by headius** [comment]
Could you include the Rails test failure on these issues too? That will let us track it back to an original test for confirmation.

**Comment by gazay** [comment]
updated

**Comment by headius** [comment]
Looks like this was changed in MRI around 2011. They eliminated the custom `.new` and replaced it with a standard allocate+initialize: https://github.com/ruby/ruby/commit/f9a4d571

The same flip in JRuby should not be too difficult.
