### ISSUE TITLE
Class not found exception on ppc64le

### ISSUE THREAD

**Issue by lbianc** [jruby/jruby#2873]
I'm building jruby with all fix for ppc64le and there is still a SEVERE message (see below).

@headius I couldn't find from where it is coming, seems it is using jruby 1.7.12, which has not support for ppc64le, probably from there. 
Is there something that we could do?

```
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby Lib Setup 9.0.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for rubygems:atomic:gem:1.1.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jruby-stdlib ---
[INFO]
[INFO] --- tesla-polyglot-maven-plugin:0.1.1:execute (install_gems) @ jruby-stdlib ---
Apr 24, 2015 3:53:31 PM jnr.ffi.provider.jffi.NativeRuntime buildNativeTypeAliases
SEVERE: failed to load type aliases: java.lang.ClassNotFoundException: jnr.ffi.provider.jffi.platform.unknown.linux.TypeAliases
using jruby 1.7.12
install gems unless already installed

--- gem jruby-readline-1.0 ---
```

**Comment by headius** [comment]
Hmm, still not picking up the platform right.

**Comment by lbianc** [comment]
The SEVERE message is being shown due the use of tesla-polyglot-maven-plugin version 0.1.1, which depends of jruby version 1.7.12. As this JRuby version has not ppc64 support, it will show the message, so we have a cycle dependency.
tesla-polyglot-maven-plugin (0.1.1) seems to no be using ffi (because the build would break) and it's used during the build to read pom files written in Ruby.
This issue will be fixed only when tesla-polyglot-maven-plugin update its jruby dependency to a version that supports ppc64 and the JRuby dependency of tesla-polyglot-maven-plugin version be updated as well.

**Comment by mkristian** [comment]
to upgrade this tesla-polyglot-maven-plugin can be done. but to understand @lbianc the build works and the actual SEVERE comes from jruby-1.7.12 which is used the ruby scripts.

**Comment by headius** [comment]
@mkristian Can we update tesla-polyglot-maven-plugin to use 1.7.20 now, since that should work ok with ppc64?

**Comment by mkristian** [comment]
keep it open until the thing got released

**Comment by mkristian** [comment]
fixed with using the new polygot-maven
