### ISSUE TITLE
java_send will not invoke a method taking a CharSequence

### ISSUE THREAD

**Issue by cshupp1** [jruby/jruby#2881]
Consider the following  in irb:
````    
a = java.lang.StringBuilder.new
a.java_send :append, [java.lang.String], "I am Here\n"
puts a
````
yields *I am Here* as expected.

````
a.java_send :append, [java.lang.CharSequence], "I am not here!\n"
a.java_send :append, [java.lang.CharSequence], "I am not here!\n".to_java
````

both yield
````
TypeError: cannot convert instance of class org.jruby.RubyModule to class java.lang.Class
        from org/jruby/java/proxies/JavaProxy.java:347:in `java_send'
        from (irb):76:in `evaluate'
        from org/jruby/RubyKernel.java:1107:in `eval'
        from org/jruby/RubyKernel.java:1507:in `loop'
        from org/jruby/RubyKernel.java:1270:in `catch'
        from org/jruby/RubyKernel.java:1270:in `catch'
        from C:/jruby-1.7.18/bin/jirb:13:in `(root)'
````
Lets get extreme and open Ruby's String as follows:

````
class String
  include java.lang.CharSequence

  def charAt(index)
    self.to_java.charAt(index)
  end

  def length
    self.to_java.length
  end

  def subSequence(start, endPoint)
    self.to_java.subSequence(start, endPoint)
  end

  def toString
    self.to_java.toString()
  end

end
````

The code **"SomeString".toString** behaves as expected now, but:
````
 a.java_send :append, [java.lang.CharSequence], "Some String"
TypeError: cannot convert instance of class org.jruby.RubyModule to class java.lang.Class
        from org/jruby/java/proxies/JavaProxy.java:347:in `java_send'
        from (irb):81:in `evaluate'
        from org/jruby/RubyKernel.java:1107:in `eval'
        from org/jruby/RubyKernel.java:1507:in `loop'
        from org/jruby/RubyKernel.java:1270:in `catch'
        from org/jruby/RubyKernel.java:1270:in `catch'
        from C:/jruby-1.7.18/bin/jirb:13:in `(root)'
````

Still fails :-(

BTW:
````
irb(main):083:0> RUBY_VERSION
=> "1.9.3"
irb(main):084:0> JRUBY_VERSION
=> "1.7.18"
irb(main):085:0>
````

**Comment by headius** [comment]
I will be fixing this (or have fixed it) for JRuby 1.7.20, but for interfaces you need to add .java_class so we pass the class through. The modules we set up for interfaces do not automatically coerce to java.lang.Class (yet).

**Comment by headius** [comment]
Oh, I just saw @kares took a stab at this...but perhaps it is not finished?

**Comment by kares** [comment]
@headius yeah, was trying to get a base :green_apple: travis-ci to make sure I test properly ... and it finally is!

the [fix](https://github.com/jruby/jruby/commit/33453c2a127eb07818d802e3695e1d7ae1335056) here is to add `toJava` code on the *RubyModule* ... similar as the one that exists on *RubyClass* so that proxy (interface) modules convert correctly. all seems well and it seems it was not left out intentionally but forgotten (no test/spec code with `java_send` using an iface), a similar issue #638 existed for a while

**Comment by cshupp1** [comment]
Question for you guys...

The fix seems to imply that my "getting extreme" and opening Ruby's string class to mixin CharSequence will be required. Is this the case, or is Ruby's String going to be coercible to a CharSequence?

**Comment by kares** [comment]
@cshupp1 it won't be required just take a look at the commit there's a piece of your [problematic code](https://github.com/kares/jruby/commit/ed48823834d59b0414044949641afff1b21a4862#diff-90dcc0a6e23903da532325e9fd1d32c8R31)

**Comment by cshupp1** [comment]
I see it!  Thanks!
