### ISSUE TITLE
[Truffle] Failing Installation from latest tar.gz  , Graal version error 

### ISSUE THREAD

**Issue by Alis-lang** [jruby/jruby#2893]
Getting this error from following file http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-master+graal-macosx-x86_64-bin.tar.gz   
Anotheruser confirmed of same error

Parks-MacBook-Air:~ Lud$ tar -zxf jruby-dist-master+graal-macosx-x86_64-bin.tar.gz
Parks-MacBook-Air:~ Lud$ jruby-master/bin/jruby -X+T -e 'puts Truffle.graal?'
ArgumentProcessor.java:726:in `checkGraalVersion': java.lang.RuntimeException: This version of JRuby is built against Graal 0.7 but you are using it with version 0.6 - either update Graal or use with (-J)-original to disable Graal and ignore this error
	from ArgumentProcessor.java:378:in `processArgument'
	from ArgumentProcessor.java:104:in `processArguments'
	from ArgumentProcessor.java:97:in `processArguments'
	from RubyInstanceConfig.java:161:in `processArguments'
	from Main.java:225:in `run'
	from Main.java:198:in `main'

**Comment by chrisseaton** [comment]
This should be fixed by 8adab0c383252fe49026c8414e25457027cd9d1e - rebuilding the nightlies now.
