### ISSUE TITLE
rvm Jruby+Graal installation is failing 

### ISSUE THREAD

**Issue by Alis-lang** [jruby/jruby#2895]
from copy and pasting the lines in https://github.com/jruby/jruby/wiki/Truffle#rvm
it gives out errors as following

Parks-MacBook-Air:~ Lud$ rvm mount -r http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-master+graal-macosx-x86_64-bin.tar.gz -n jruby-dev-graal
http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-master+graal-macosx-x86_64-bin.tar.gz - #configure
jruby-dev-graal - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  107M  100  107M    0     0   798k      0  0:02:18  0:02:18 --:--:--  745k
Downloaded archive checksum did not match, archive was removed!
If you wish to continue with not matching download add '--verify-downloads 2' after the command.

Downloading http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-master+graal-macosx-x86_64-bin.tar.gz failed.

**Comment by Alis-lang** [comment]
adding --verify-downloads 2 after the command lets me thru installaion success, but i'd still want it to be solved ;)

**Comment by chrisseaton** [comment]
Now that there are regular releases of JRuby 9 with Truffle in it, we're going to recommend using those and installing GraalVM from another source.

https://github.com/jruby/jruby/wiki/Truffle-FAQ#how-do-i-get-jrubytruffle
