### ISSUE TITLE
Jruby+Graal installation brings gem installation error

### ISSUE THREAD

**Issue by Alis-lang** [jruby/jruby#2898]
Parks-MacBook-Air:alice Lud$ rvm use jruby-dev-graal
Using /Users/Lud/.rvm/gems/jruby-dev-graal
Parks-MacBook-Air:alice Lud$ gem install sequel
ERROR:  Loading command: install (OpenSSL::X509::StoreError)
	setting default path failed: the trustAnchors parameter must be non-empty
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

after https://github.com/jruby/jruby/wiki/Truffle#rvm installation method, gem installation isn't successful where 'gem install' in ruby-2.2.2 and jruby-1.7.19 are working fine

**Comment by chrisseaton** [comment]
Sorry - gems aren't going to work for a while. Neither is OpenSSL. Basically you are at least 6 months away from being able to gem install anything and expect it to work.

**Comment by Alis-lang** [comment]
6 month is very short for me to wait for such awesomeness, its ok! 
sorry distracting you

**Comment by Sdogruyol** [comment]
Same here :smile: Thanks @chrisseaton :+1:

**Comment by nirvdrum** [comment]
I'm seeing this in the JRuby+Truffle builds when Truffle isn't being activated.  It suggests there might be a general packaging problem.

**Comment by nirvdrum** [comment]
It looks like the bundled graal is lacking whatever files jruby-openssl needs to boot.

**Comment by masterkain** [comment]
issue still present

**Comment by nirvdrum** [comment]
@masterkain What version of Graal are you using? GraalVM should have the necessary certificates now. However, gem installation still isn't going to work.

**Comment by dux** [comment]
issue still present, installed on osx via rvm

`jruby 9.0.5.0-SNAPSHOT (2.2.3) 2015-12-22 36276d3 OpenJDK 64-Bit Server VM 25.40-b25-internal-graal-0.7 on 1.8.0-internal-b128 +jit [darwin-x86_64]`

**Comment by chrisseaton** [comment]
@dux yes we still haven't implemented support for gems.
