### ISSUE TITLE
require 'ripper' yields const already init warnings

### ISSUE THREAD

**Issue by cpuguy83** [jruby/jruby#2904]
When trying to `require ripper` on jruby 9k-pre2 we get these warnings:

```
/opt/jruby/lib/ruby/stdlib/ripper/core.rb:13: warning: already initialized constant SCANNER_EVENT_TABLE
/opt/jruby/lib/ruby/stdlib/ripper/core.rb:13: warning: already initialized constant PARSER_EVENT_TABLE
/opt/jruby/lib/ruby/stdlib/ripper/core.rb:13: warning: already initialized constant Version
/opt/jruby/lib/ruby/stdlib/ripper/core.rb:13: warning: already initialized constant SCRIPT_LINES__
```

Looking at the referenced `core.rb`, the only thing I can see is that before doing anything it's requiring ripper.jar... so I'm assuming that these constants are being defined in there.

**Comment by enebo** [comment]
Hmmm, apparently I added the right mojo in the ripper.jar for it to load itself.  @headius can you commit this ripper.rb change to MRI upstream?

**Comment by headius** [comment]
Updated our stdlib in https://github.com/jruby/ruby/commit/a0951c651a44c33ced2daba2e612dcbb1d9f2797
