### ISSUE TITLE
[Truffle] Undefining a method causes respond_to? to break

### ISSUE THREAD

**Issue by nirvdrum** [jruby/jruby#2915]
When we undefine a method it causes Truffle's `respond_to?` logic to fail.  `respond_to?` is implemented to return false if a method lookup fails, but if the lookup succeeds but is marked as undefined, Truffle raises an exception instead.

A small reproduction case:

```
class Wrapper
  def x
  end

  def y
    p respond_to?(:x)

    singleton_class.send(:undef_method, :x)

    p respond_to?(:x)
  end
end

Wrapper.new.y
```

And running in MRI:

```
> ruby -v undefined.rb 
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
true
false
```

Running in JRuby+Truffle:

```
> bin/jruby -X+T -v undefined.rb 
jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-05-04 af42d09 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [linux-amd64]
true
undefined.rb:10:in `respond_to?': undefined method `x' for Wrapper (NoMethodError)
	from undefined.rb:10:in `y'
	from undefined.rb:14:in `<main>'
```

The raise originates in:

https://github.com/jruby/jruby/blob/55376a00175725027e941df3bdcd5414a0904408/truffle/src/main/java/org/jruby/truffle/nodes/dispatch/DispatchNode.java#L96-L98

**Comment by chrisseaton** [comment]
Fixed in 55b57d5824181078862bdbed7afac8163f3bd8e2
