### ISSUE TITLE
Method#parameters doesn't annotate required parameters correctly

### ISSUE THREAD

**Issue by nirvdrum** [jruby/jruby#2918]
JRuby 9.0.0.0 incorrectly reports required parameters as "rest" in Method#parameters.

```
> ruby -v -e 'def m(x); end; p method(:m).parameters'
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
[[:req, :x]]
```

```
> bin/jruby -v -e 'def m(x); end; p method(:m).parameters'
jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-05-08 c957028 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [linux-amd64]
[[:rest, :x]]
```

**Comment by nirvdrum** [comment]
I haven't looked, but's probably shared logic with Proc#parameters.  That suffers from the same problem.

**Comment by headius** [comment]
JIT bug:

```
$ rvm jruby-9.0.0.0.pre2 do ruby -X-C -e 'def m(x); end; p method(:m).parameters'
[[:req, :x]]
```

Signature.decode/encode are probably busted.

**Comment by nirvdrum** [comment]
I need to remember to check both.  I guess that JITs fairly quickly now then.

**Comment by headius** [comment]
The -e or target script always compile completely before executing unless you pass -X-C.
