### ISSUE TITLE
check_permissions

### ISSUE THREAD

**Issue by kengsrengtang** [jruby/jruby#2932]
gems/gems/netrc-0.10.2/lib/netrc.rb:44:in `check_permissions' exception without handler

**Comment by mkristian** [comment]
any more info: which jruby version ? how can I reproduce this error ?

**Comment by kengsrengtang** [comment]
Jruby-1.7.20, deployed on websphere !!

**Comment by kares** [comment]
report has been very vague. and 1.7.x is now EOL, @kengsrengtang if you still happen to experience the issue please fill up a better report for us. if you can not give a way to reproduce at least a description would come handy. include as much details as you can think of :wink:
