### ISSUE TITLE
Module#const_get may return incomplete class

### ISSUE THREAD

**Issue by yousuketto** [jruby/jruby#2945]
I've encountered when executing ActiveResource::Base.find_or_create_resource_for.
https://github.com/rails/activeresource/blob/v4.0.0/lib/active_resource/base.rb#L1501-L1520
`name` method of *incomplete class* return nil.

**simple reproduction**
```ruby
# example.rb
module Xxx
  class << self
    def find_or_create(klass_name)
      self.const_get(klass_name)
    rescue NameError => e
      self.const_set(klass_name, Class.new)
    end
  end
end

ths = []
200.times do |name|
  100.times do |index|
    t = Thread.new(index.to_s, name.to_s) do |i, n|
      klass_name = "Yyy#{n}"
      yyy = Xxx.find_or_create(klass_name)
      unless yyy.name
        print "hit!! #{klass_name}.name == nil\n"
      end
    end
    ths << t
  end
end
ths.each(&:join)
```
```bash
$ jruby -v
jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +jit [darwin-x86_64]
$ jruby example.rb 
example.rb:6 warning: already initialized constant Yyy6
example.rb:6 warning: already initialized constant Yyy6
example.rb:6 warning: already initialized constant Yyy10
example.rb:6 warning: already initialized constant Yyy11
example.rb:6 warning: already initialized constant Yyy11
...
example.rb:6 warning: already initialized constant Yyy84
example.rb:6 warning: already initialized constant Yyy84
hit!! Yyy85.name == nil
example.rb:6 warning: already initialized constant Yyy92
example.rb:6 warning: already initialized constant Yyy93
...
```

**Comment by kares** [comment]
this is all fine on JRuby's end - you should not expect your code to not print warnings since it's not thread-safe ... JRuby simply can not "know" that : 
```ruby
    def find_or_create(klass_name)
      self.const_get(klass_name)
    rescue NameError => e
      self.const_set(klass_name, Class.new)
    end
```
is intended to be somehow "atomic" ... would report this on Rails as their code assumes MRI (gil)

**Comment by yousuketto** [comment]
Sorry, I'm weak in English.

I don't think that warning message is a problem.

Yyy85 was executed ``name`` method, and returned ``nil``.
```
hit!! Yyy85.name == nil
```
Therefore, Yyy85 was **incomplete state**.
It is a problem that **I could get this class of incomplete state**.

I think cause that's the order of processing.
1. Class object was registered in the constant table.
    - https://github.com/jruby/jruby/blob/1.7.20/core/src/main/java/org/jruby/RubyModule.java#L3153
2. Constant name was registred.
    - https://github.com/jruby/jruby/blob/1.7.20/core/src/main/java/org/jruby/RubyModule.java#L3159-L3165

**Comment by kares** [comment]
oh sorry, I missed that completely .. yes the `name` is an issue (I've actually run into that as well in JI)

**Comment by headius** [comment]
This is not fixable in JRuby.

MRI determines name in a very peculiar way: when it has not yet been set for a given class, it __walks every class in the system accessible via Object__ and uses that to build the name.

This has some severe performance implications that most people don't know about: https://bugs.ruby-lang.org/issues/11119

Needless to say, we won't be implementing #name that way. Instead, we use the usually-ok logic of assigning name when the class is first set to a constant. This behavior you see in Rails is exploting a very strange edge case, and it won't work under JRuby or Rubinius.

**Comment by headius** [comment]
We may be able to mitigate this by setting the name before we assign the constant...I think that would be reasonable and be a closer approximation of MRI's behavior.
