### ISSUE TITLE
Windows JRE builds missing for 1.7.20

### ISSUE THREAD

**Issue by davemitchell** [jruby/jruby#2953]
There appear to be no runtime-included builds for windows with the latest 1.7.20 release.  For instance, https://s3.amazonaws.com/jruby.org/downloads/1.7.20/jruby_windows_x64_jre_1_7_20.exe is missing while the version for previous builds (1.7.19, 1.7.18, etc) all exist.  What this an oversight?

**Comment by chrisseaton** [comment]
There was a discussion about not producing them anymore, but I wasn't sure there was a conclusion.

I think there were two concerns being discussed - distributing old versions of the JRE is a security risk, and distributing (exporting?) crypto was also a concern.

**Comment by headius** [comment]
I think we decided to drop the JRE builds (cc @enebo). Do you still need them? We figured that us distributing the JRE was just asking for some kind of trouble (security fixes, redistribution legal hassles, crypto export, other stuff).
