### ISSUE TITLE
add enforcer plugin to ensure we have only released dependencies on release

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#2970]
since their are problems with 9k.pre2 release which seems to be OK on maven-central but the tagged version on git has pom.xml with SNAPSHOT dependencies which makes it very difficult to build the release from this tag.

the maven-enforcer-plugin can be configured to fail so ensure the moment you switch to a release version of jruby then ALL the dependencies need to be released versions as well.

**Comment by eregon** [comment]
Would it be possible to load this plugin only when releasing?
My concern is just that Eclipse keeps reporting warning because it does not know how to deal with this plugin.

**Comment by mkristian** [comment]
@eregon should be possible to restrict the use to pom.xml with release versions in it
