### ISSUE TITLE
String interpolation issue

### ISSUE THREAD

**Issue by benjaminpmeier** [jruby/jruby#2971]
I made a ruby file with the following contents:
regex = /[#$]/
puts "Successfully parsed regex"

benjamm.desktop% ruby regex_test.rb
Successfully parsed regex

benjamm.desktop% jruby regex_test.rb
SyntaxError: regex_test.rb:1: syntax error, unexpected null
regex = /[#$]/

I am using JRuby version:
jruby 1.7.11 (1.9.3p392) 2015-04-17 fffffff on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +indy [linux-amd64]

**Comment by mkristian** [comment]
it works with jruby-1.7.20
