### ISSUE TITLE
jruby-head Travis run blows up with java.lang.NullPointerException's

### ISSUE THREAD

**Issue by dgutov** [jruby/jruby#2978]
See here: https://travis-ci.org/dgutov/robe/jobs/63719495

For comparison, here are the results for the same code when run with `jruby-19mode`: https://travis-ci.org/dgutov/robe/jobs/60779784

The code is not pretty, but at least the project is in public access.

**Comment by headius** [comment]
Hmm, fascinating. My quick guess would be that there's some logic involving reopening or duping streams that's not working properly. This will need to be fixed for 9k final.

**Comment by dgutov** [comment]
I still see this from time to time, even when the build shows no other serious failures: https://travis-ci.org/dgutov/robe/jobs/72230551

**Comment by kares** [comment]
no to be seen on latest [jruby-head build](https://travis-ci.org/dgutov/robe/jobs/303217103), let's call it a day :)
