### ISSUE TITLE
Socket.pair is not implemented

### ISSUE THREAD

**Issue by ojab** [jruby/jruby#2984]
```ruby
require 'socket'
foo, bar = Socket.pair(:UNIX, :STREAM, 0)
```
leads to 
```
NoMethodError: undefined method `pair' for Socket:Class
  method_missing at org/jruby/RubyBasicObject.java:1598
           <top> at /tmp/socket.rb:3
```
on `jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-05-22 ac104e7 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]`

**Comment by headius** [comment]
We do have UnixSocket.pair...are there any other socket types for which Socket.pair works?

**Comment by headius** [comment]
I think we can implement this simply enough for UNIX, but the other socket types will be a bit more difficult (we don't use native calls for them and the JDK socket classes don't have "pair" capability).

**Comment by ojab** [comment]
MRI also supports pair only for UNIX sockets (other fails with Errno::EOPNOTSUPP), but it can be called not only using `UNIXSocket.pair`, but  also using `Socket.pair(:UNIX, :type, :protocol)`.
So there is only Socket.pair/Socket.socketpair methods missing.

**Comment by headius** [comment]
@ojab thanks for looking into that. I also noticed that BSD socketpair(2) only supports UNIX as well. So we'll implement it to just call UNIXSocket.pair and error for other types.
