### ISSUE TITLE
Error while using socket class

### ISSUE THREAD

**Issue by aabed** [jruby/jruby#2997]
jruby-1.7.19 :001 > require "socket"
 => true 
jruby-1.7.19 :002 > Socket::Option.bool(:INET, :SOCKET, :KEEPALIVE,true)
ArgumentError: wrong number of arguments calling `bool` (4 for 1)
	from (irb):2:in `evaluate'
	from org/jruby/RubyKernel.java:1107:in `eval'
	from org/jruby/RubyKernel.java:1507:in `loop'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from /usr/local/rvm/rubies/jruby-1.7.19/bin/irb:13:in `(root)'

**Comment by headius** [comment]
It looks like Socket::Option is only partially implemented. The `bool` method and several others don't actually do anything.

**Comment by aabed** [comment]
any suggested solutions ?

**Comment by headius** [comment]
Well...someone needs to implement it :-) Unfortunately it's a little gnarly...it represents low-level socket structures that don't really have an equivalent on the JVM.
