### ISSUE TITLE
splats with non-array like values

### ISSUE THREAD

**Issue by ahawkins** [jruby/jruby#3007]
I came across this code trying out some of my thrift related things on jruby 9000. Here's the relevant source: https://github.com/apache/thrift/blob/master/lib/rb/lib/thrift/types.rb#L46-68

Now for the offending source.

```ruby
klasses = String
[*klasses]
````

On MRI 2.2: `[String]`

On JRuby 9000:

```
irb(main):005:0> klasses = String
=> String
irb(main):006:0> [*klasses]
NoMethodError: undefined method `to_a' for String:Class
        from org/jruby/RubyBasicObject.java:1606:in `method_missing'
        from (irb):6:in `<eval>'
        from org/jruby/RubyKernel.java:1005:in `eval'
        from org/jruby/RubyKernel.java:1315:in `loop'
        from org/jruby/RubyKernel.java:1125:in `catch'
        from org/jruby/RubyKernel.java:1125:in `catch'
        from /Users/ahawkins/.rbenv/versions/jruby-9.0.0.0.pre2/bin/irb:13:in `<top>'
```

I have no idea what the intended behavior is, if this is a weird MRI thing or a missing method in jRuby.

**Comment by enebo** [comment]
Yeah this is wacky.   most classes core or user-defined fail here.

**Comment by ahawkins** [comment]
@enebo awesome work, will verify again when RC1 is out.
