### ISSUE TITLE
Module#included is private when called with super

### ISSUE THREAD

**Issue by ahawkins** [jruby/jruby#3008]
I came across this issue when trying out one of my libraries on jruby 9000 pre2. The relevant source code is here: https://github.com/Saltside/thrift-base64-ruby/blob/master/lib/thrift/base64.rb#L22-51

Note the comment about using `prepend` and `included`. The code fails on 9000.pre2 like so:

```
NoMethodError: private method `included' called for Thrift::Struct:Module
          included at /usr/local/bundle/gems/thrift-base64-0.1.1/lib/thrift/base64.rb:35
           include at org/jruby/RubyModule.java:2408
```

I could remove my work around and use `included` like normal, but it seems strange that a method would change scope when invoked with `super`.

This is easily to replicate. Clone that library and run the tests on 9000.pre2.

**Comment by headius** [comment]
Interesting. Will have a look.

**Comment by headius** [comment]
Simple reproduction:

```ruby
module A
  def included(base)
    super
  end
end

module B
  class << self
    prepend A
  end
end

class C
  include B
end
```

**Comment by headius** [comment]
This logic in `IRRuntimeHelpers.unresolvedSuper` seems to be responsible for the method_missing call. I'm not sure why we are checking prepended in this way:

```java
        if (method.isUndefined() || (superClass.isPrepended() && (method.isImplementedBy(self.getType())))) {
            rVal = Helpers.callMethodMissing(context, self, method.getVisibility(), methodName, CallType.SUPER, args, block);
        } else {
```

**Comment by ahawkins** [comment]
@headius awesome work, will verify again when RC1 is out.
