### ISSUE TITLE
LocalJumpError: yield called out of block in JRuby 9.0.0.0.pre2

### ISSUE THREAD

**Issue by judofyr** [jruby/jruby#3009]
We got this bug report in Tilt (https://gith/ub.com/rtomayko/tilt/issues/235#issuecomment-107020136) by @TobiG77. I think this is a bug in JRuby?

> I can reliably reproduce this with jruby-9.0.0.0.pre2 with aws-sdk v2.0.47.
>
>MRI (2.2.2) and jruby-1.7.19 both work fine.
>
>```
irb(main):035:0> object = s3.bucket(ENV['AWS_BUCKET']).object('hello-world/hello-world.tar.gz')
=> #<Aws::S3::Object bucket_name="xyz", key="hello-world/hello-world.tar.gz">
irb(main):036:0> object.upload_file('./hello-world.tar.gz')
LocalJumpError: yield called out of block
        from org/jruby/RubyProc.java:303:in `call'
        from org/jruby/RubyYielder.java:101:in `yield'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/model/shapes.rb:252:in `block in members'
        from org/jruby/RubyArray.java:2308:in `map'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/model/shapes.rb:251:in `block in members'
        from org/jruby/RubyProc.java:303:in `call'
        from org/jruby/RubyGenerator.java:102:in `each'
        from org/jruby/RubyEnumerator.java:300:in `each'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/model/shapes.rb:282:in `index_members_by_location_name'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/model/shapes.rb:275:in `member_by_location_name'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/endpoint.rb:54:in `block in apply_path_params'
        from org/jruby/RubyString.java:2409:in `gsub'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/endpoint.rb:47:in `apply_path_params'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/endpoint.rb:38:in `build_endpoint'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/endpoint.rb:30:in `call'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/param_validation.rb:22:in `call'
... 1 levels...
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/response_target.rb:18:in `call'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/client/request.rb:70:in `send_request'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-core-2.0.47/lib/seahorse/client/base.rb:216:in `block in create_multipart_upload'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:42:in `initiate_upload'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/services/s3/multipart_file_uploader.rb:33:in `upload'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/services/s3/file_uploader.rb:32:in `upload'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/lib/ruby/gems/shared/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/services/s3/object.rb:102:in `upload_file'
        from (irb):36:in `<eval>'
        from org/jruby/RubyKernel.java:1005:in `eval'
        from org/jruby/RubyKernel.java:1315:in `loop'
        from org/jruby/RubyKernel.java:1125:in `catch'
        from org/jruby/RubyKernel.java:1125:in `catch'
        from /home/developer/.rbenv/versions/jruby-9.0.0.0.pre2/bin/irb:13:in `<top>'irb(main):037:0> 
irb(main):038:0* 
```

**Comment by headius** [comment]
Looking into this.

**Comment by TobiG77** [comment]
If it's any help, I've played around with the aws-sdk v2. as per: https://ruby.awsblog.com/post/Tx1K43Z7KXHM5D5/Uploading-Files-to-Amazon-S3

**Comment by dblock** [comment]
See https://github.com/LTe/grape-rabl that would/is still failing in this way.

**Comment by enebo** [comment]
@dblock It is possible 1.7 and 9k have the same problem (localjumperror has been due to lots of issues) but could you open your grape-rabl issue as a new one?  Even if they are the same underlying problem the impls are so different wrt to non-local flow control and they will end up as completely different fixes (plus this also works a little nicer with github issues...yeah bonus!).

**Comment by headius** [comment]
Reproduction:

```ruby
def members
  Enumerator.new do |y|
    [1, 2, 3, 4].map do |n|
      y.yield([n, n], n)
    end
  end
end

def index_members_by_location_name
  members.each.with_object({}) do |(name, shape), hash|
    p [name, shape, hash]
  end
end

index_members_by_location_name
```

**Comment by headius** [comment]
Ahh I see the problem here.

The code in aws-sdk does `enum.each.with_object`, which is a little unusual. Our logic for `Enumerator#each` was not "enumeratorizing" when each is called with no block, so the null block propagated through to the Yielder, and then eventually was invoked. I'm fixing `Enumerator#each` to enumeratorize properly when no block is passed in, and it appears to fix the problem.

I call this an unusual form because generally if you have an Enumerable object, you'd just call `each_with_object` rather than `each.with_object`. The latter case apparently doesn't have much in the way of tests.

**Comment by dblock** [comment]
I tried to find a workaround for Rabl, but failed. You can see https://github.com/nesquena/rabl/issues/544 for details.

**Comment by headius** [comment]
I think I have the fix, after a bit of fiddling around.

**Comment by dblock** [comment]
@headius I would love an explanation of what's going on in Rabl with this and possibly a work-around so that works with all existing versions.
