### ISSUE TITLE
9k has different scoping behavior than MRI

### ISSUE THREAD

**Issue by zachpendleton** [jruby/jruby#3010]
Issue w/ test available here: https://gist.github.com/zachpendleton/e7f1352f4bd079daf288

If `attr_accessor` is called inside a protected or private method, the instance variables inherit the protected or private scope in 9k, but in MRI they inherit the scope of the call site.

**Comment by lephyrius** [comment]
:+1:  I think I got the same problem here.
https://github.com/jruby/jruby/issues/2886
But I couldn't create a nice testcase like u.

**Comment by headius** [comment]
Ah I see. Yes, method bodies should always default to public visibility, I believe.

**Comment by headius** [comment]
I see the issue... InterpretedIRMethod is always using that method's visibility when preparing the frame. It should just be left as the default public visibility. Fixing.
