### ISSUE TITLE
[Truffle] Kernel#send should be more transparent

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#3013]
Quite a few shared specs use `send` and expect it to be the same as if it was an actual literal call.
For instance, `spec/ruby/core/kernel/__callee___spec.rb`, `spec/ruby/core/module/private_spec.rb` and many others.

In MRI, `send` seems to not even appear in the backtrace:
```
$ ruby -e 'send :foo'
-e:1:in `<main>': undefined method `foo' for main:Object (NoMethodError)

compared to:
ruby -e 'spawn :foo'
-e:1:in `spawn': no implicit conversion of Symbol into String (TypeError)
	from -e:1:in `<main>'
```

I am not sure sure how we can handle this, but ideally we would not create any additional frame between a `send(:bla,1,2)` and `bla(1,2)`.

If we do not want to simulate that behavior, how could we reliably get the caller frame? Ignore frames which have `Kernel#send` for METHOD?

**Comment by chrisseaton** [comment]
Maybe we just need to hide the frame when we construct backtraces, and when we find the caller frame for other purposes?

**Comment by eregon** [comment]
I modified `RubyCallStack.getCallerMethod` to ignore send since all its callers would expect it.
Let's see if there are other cases where we should ignore `send`.

**Comment by chrisseaton** [comment]
Is this resolved for the issues you have? I'd rather not leave issues speculatively open that something might still be a problem for people in the future. If you don't have a test case it's not actionable and I'll close until we have one.

**Comment by eregon** [comment]
Yeah it seems OK for now as `getCallerMethod` does what we need and I did not meet new related problems.

**Comment by eregon** [comment]
I replaced most uses of `TruffleRuntime.getCallerFrame()` by the RubyCallStack version ignoring `send`. This should match better the semantics but of course is not exactly fast, like for `Kernel#binding`.

A nice way to fix this would be to pass the caller frame if the target method needs it
and just pass it along in `send`, effectively ignoring `send`'s frame.

**Comment by eregon** [comment]
The two remaining usages would work just fine with the RubyCallStack version as well, but in these cases ignoring send does not change anything.

**Comment by chrisseaton** [comment]
> A nice way to fix this would be to pass the caller frame if the target method needs it

Yes, we need to do this for another reason as well - `iterateFrames` is boundary, so we can't constant fold through it at the moment. This in turns stops us constant folding through things like `binding.local_variable_get`.
