### ISSUE TITLE
OutOfMemoryError in 9k on code with very large methods

### ISSUE THREAD

**Issue by bbrowning** [jruby/jruby#3016]
When running TorqueBox 4's rubocop task under JRuby 9k, we sometimes get an OutOfMemoryError. After some debugging on IRC, it looks like the very large `advance` method in the parser gems' `lib/parser/lexer.rb` is causing a non-fatal OOM in the JIT compiler which ends up backing up the JIT queue and eventually OOMing the entire application in a fatal way.

Here's a gist of the OOMs with jit logging enabled - https://gist.github.com/bbrowning/a3d4e9d9fe871b36b0e7

**Comment by bbrowning** [comment]
I mentioned this on IRC, but to make sure you see it this commit forgot to adjust `Constants.JIT_MAX_SIZE_LIMIT` from 30,000 down to a value of 2,000. Thus, unless I run with `-Xjit.maxsize=2000`, I still see the OOMs happening.

**Comment by enebo** [comment]
I adjusted this yesterday (note for posterity).
