### ISSUE TITLE
LoadError with 'compiled' ruby files with JRuby9000

### ISSUE THREAD

**Issue by MSNexploder** [jruby/jruby#3018]
Compiling any Ruby code into a class file and trying to load it afterwards leads to "LoadError: use `java_import' to load normal Java classes".

test.rb
```
puts 'hello world'
```

compiled and run with

```
jrubyc test.rb
ruby -e "load 'test.class'"
```

leads to

```
LoadError: use `java_import' to load normal Java classes: test
   load at org/jruby/RubyKernel.java:958
  <top> at -e:1
```

Happens in both 9.0.0.0.pre2 and current master (393e64f).

This essentially breaks warblers 'compiled' feature - which uses shims in order to transparently load the generated class files (https://github.com/jruby/warbler/issues/325).

**Comment by torcido** [comment]
I'm finding the same issue with 9.0.0.0.rc1 also. Your simple test case illustrates it well. It looks like you're using rvm or rbenv to launch jruby. I'm invoking it from jruby-complete.jar and getting the same result.

Trying to use "java_import" the ruby classes results in an error like:
> NameError: cannot load Java class test

Even if I rename the input file "Test.rb" with a capital "T", and it generates a java class called "Test", I still get the error:
> NameError: cannot load Java class Test

```
$ javap Test.class
Compiled from "Test.rb"
public class Test {
  public static void main(java.lang.String[]);
}
```

By the way, have you noticed how much cleaner the compiled classes are? Version 1.7.20 produces class files that look like this:
```
$ javap Test.class
Compiled from "Test.rb"
public class Test extends org.jruby.ast.executable.AbstractScript {
  public Test();
  public static org.jruby.runtime.builtin.IRubyObject __file__(Test, org.jruby.runtime.ThreadContext, org.jruby.runtime.builtin.IRubyObject, org.jruby.runtime.builtin.IRubyObject[], org.jruby.runtime.Block);
  public org.jruby.runtime.builtin.IRubyObject __file__(org.jruby.runtime.ThreadContext, org.jruby.runtime.builtin.IRubyObject, org.jruby.runtime.builtin.IRubyObject[], org.jruby.runtime.Block);
  public org.jruby.runtime.builtin.IRubyObject load(org.jruby.runtime.ThreadContext, org.jruby.runtime.builtin.IRubyObject, boolean);
  public static void main(java.lang.String[]);
}
```

**Comment by headius** [comment]
Ok, this is fixed now for RC2. There's one caveat, however...

In order to speed load times, we have removed .class from load searching by default. In order to have JRuby search for .class, you'll need to pass `-Xaot.loadClasses=true` to JRuby or `-Djruby.aot.loadClasses=true` to the JVM. This probably needs to change in warbler or jruby-rack somewhere (what do you think, @kares?)

**Comment by kares** [comment]
JRuby-Rack should be fine ... but Warbler might be affected by the *.class* loading change // cc @jkutner

**Comment by jkutner** [comment]
With a quick warbler test, it looks like this fixes the problem (without the `aot.loadClasses=true`). I'll investigate further to make sure that's right, but I don't expect any difficulty. Thanks @headius!

**Comment by amiracam** [comment]
I am bumping into this issue and I am packaging with warbler on 9.2.0.0
