### ISSUE TITLE
JRuby 1.7.20 error when requiring krypt/ossl

### ISSUE THREAD

**Issue by tbeauvais** [jruby/jruby#3024]
After switching to JRuby 1.7.20 one of our internal gems is failing because it does a require 'krypt/ossl'. I'm assuming it's not needed anymore since JRuby 1.7.20 bundles jruby-openssl 0.9.6, but it is a breaking change since this gem supports older version of JRuby.

**Comment by mkristian** [comment]
so jruby-openssl does not "use" krypt anymore and so jruby does not bundle
the krypt gems.

if you gem depends on krypt then you need to add krypt as a dependeny to
your gem.

a "require 'krypt/ossl'" was never needed - not sure why your gem does it !?

**Comment by tbeauvais** [comment]
I think it may have added the "require" because of this issue: https://github.com/jruby/jruby/issues/719

**Comment by mkristian** [comment]
you can add the krypt gem yourself to have your code working over different
jruby versions. but whether it is a regression or not I can not tell. I
know the set of default gem do change from ruby to ruby and from jruby to
jruby. I really do not know how bundler deals with those default gems
coming with a specific ruby.

**Comment by kares** [comment]
as @mkristian already suggested, krypt was really an "internal" gem to get PKCS5 support in OpenSSL

... thus we ended up having a lot of krypt code just to "emulate" 2 methods - we can not avoid users requiring files from default gems but best practice is to never assume any `require` outside the stdlib to work and have a gem dependency instead (what if a newer bundled krypt did not work with your internal gems - you would need to adjust the gem anyway for newer JRuby 1.7.x).
