### ISSUE TITLE
jruby: warning: unknown property jruby.export

### ISSUE THREAD

**Issue by monkstone** [jruby/jruby#3034]
I get this message when using jruby-9.0.0.0.pre2 and jruby-9.0.0.0.rc1 as installed jruby or as jruby-complete when running ruby-processing sketches.

**Comment by headius** [comment]
Sounds like it's trying to pass a JRuby argument that we don't support, and we just quietly ignored it before. This "jruby.export" property does not appear to exist in 1.7 either, but we don't error for invalid properties.

**Comment by headius** [comment]
See if you can figure out where "jruby.export" is coming from in processing.

**Comment by monkstone** [comment]
Thought it was bit odd when I could only reproduce on one of my setups, it is a leftover of a largely unsuccessfull experiment with drip. 
https://github.com/ninjudd/drip/wiki/JRuby
