### ISSUE TITLE
SyntaxError: test.rb:3: syntax error, unexpected kDO_BLOCK

### ISSUE THREAD

**Issue by mattparlane** [jruby/jruby#3039]
This gives the above error:

```ruby
class C
  private def f
    [].each do |i|
    end
  end
end
```

```jruby 9.0.0.0.rc1 (2.2.2) 2015-06-10 a0bf3b3 OpenJDK 64-Bit Server VM 25.45-b02 on 1.8.0_45-internal-b14 +jit [linux-amd64]```

**Comment by enebo** [comment]
I am going to treat this as a 9000-only issue and may go back and fix 1.9 parser later on jruby-1_7 but github issues does not handle multi-milestone issues (plus jruby-1_7 lexer is much different than 9k by this point).
