### ISSUE TITLE
Zlib::GzipReader.readbyte not implemented

### ISSUE THREAD

**Issue by BiraLookout** [jruby/jruby#3041]
GzipReader doesn't seem to implement readbyte, throwing NoMethodError when called.

**Comment by headius** [comment]
Looks like it's a trivial wrapper around getbyte.

**Comment by headius** [comment]
Looks like it was added in 1.9, so we should do this for JRuby 1.7.21 too.

**Comment by headius** [comment]
I noticed there's no tests for either `getbyte` or `readbyte`. Perhaps you'd help us out and add something to https://github.com/ruby/rubyspec?
