### ISSUE TITLE
Shellescaped utf-8 string misbehaving in backticks

### ISSUE THREAD

**Issue by mmustala** [jruby/jruby#3046]
Just tried my app with JRuby 9.0.0.0.rc1 and noticed that shellescape is returning utf-8 characters with a couple of backslashes in front of them. And because of this the escaped string does not work with the backticks.

This is almost the same situation as in https://github.com/jruby/jruby/issues/2258 but now I'm using shellescape to sanitize the input.

    #encoding: utf-8
    filename = "neliö" # Any string with multibyte chars should do
    File.write(filename, "content")
    mime = `file -b --mime #{filename.shellescape}`
    # => "ERROR: cannot open `neliÃ¶' (No such file or directory)\n"

In the 1.7 JRuby the shellescape was working without issues.

**Comment by mmustala** [comment]
The shellescape method seems to be the same in 1.7.20.1 and 9.0.0.0.rc1. So it must be the backticks that is behaving differently and not treating the backslashes correctly.

**Comment by headius** [comment]
Our shellwords library is identical to that in MRI, so I think you're right...the problem isn't in shellwords.

However, I was unable to reproduce your issue with my HEAD version of JRuby 9k. What platform are you on? Do you have an unusual system encoding (i.e. non-UTF-8)?

**Comment by mmustala** [comment]
I just installed jruby-head with rvm and tested that it reproduces. My test file content was:

```
#encoding: utf-8
require 'shellwords'

filename = "neliö" # Any string with multibyte chars should do
File.write(filename, "content")
mime = `file -b --mime #{filename.shellescape}`
puts mime
```

This will output `ERROR: cannot open `neliÃ¶' (No such file or directory)`

**Comment by headius** [comment]
Can you show me your LANG env var please? I ran on OS X and your script works ok.

**Comment by mmustala** [comment]
LANG=en_US.UTF-8

**Comment by headius** [comment]
Ok, I'll give it a shot on Linux and try to reproduce.
