### ISSUE TITLE
The Travis build should be split in a "build jruby" phase and the rest

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#3050]
Current travis configuration has a `travis_retry` around the whole maven command, which makes some failing builds last 3 times as long as they should.

Also, if building jruby fails, there is no much point in running the tests afterwards.
Should `./mnvw -Pbootstrap install` be in the `install` or `before_script` section?

**Comment by headius** [comment]
I originally added travis_retry around entire builds because maven dependency fetching was failing intermittently. If maven builds (the actual build part) have stabilized, it would be reasonable to reduce the scope of travis_retry.

**Comment by mkristian** [comment]
in other projects I do a ```mvn validate``` for the travis install script. maybe jruby could do a ```mvn install``` which basically just downloads and compiles the main parts (core + truffle + lib)

**Comment by headius** [comment]
I think we should do travis_retry just around the build itself and remove the test run from being retried. If there's flaky tests or specs we should address them or mask them.

**Comment by eregon** [comment]
@mkristian Could you try to move the build in `install:`?
I would do it myself but I am not sure what's -Dinvoker.skip=false is about or what kind of cleaning is desirable.

**Comment by mkristian** [comment]
will find some time tomorrow - there are other little build issue pending

**Comment by mkristian** [comment]
it looks like those "extended" maven tests crash the VM once in a while. the old retry did hide this

**Comment by eregon** [comment]
@mkristian Thanks!
