### ISSUE TITLE
[Truffle] $POSTMATCH not aliased

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#3051]
It looks like jruby's English.rb file comments out the aliases.

Example

``` ruby
require "English"
/^is/ =~ "isPermaLink"
puts "#{$'},#{$POSTMATCH}"
```

Expected

```
$ ruby alias.rb 
PermaLink,PermaLink
```

Actual

```
$ ~/Documents/jruby/bin/jruby -X+T alias.rb 
PermaLink,
```

**Comment by chrisseaton** [comment]
Is this blocking something major?

**Comment by bjfish** [comment]
@chrisseaton No, the RSS stdlib uses it.

**Comment by eregon** [comment]
aliasing of global variables is now implemented, but this example does not work for two reasons:
* jruby modified English.rb and commented the code, so we should use a vanilla version from MRI 2.3 instead.
* $~ and MatchData-related as well as $_ are special and currently frame and thread-local. Aliasing does not currently work for them.
