### ISSUE TITLE
upgrade jruby-openssl to 0.9.8 (as default gem)

### ISSUE THREAD

**Issue by kares** [jruby/jruby#3053]
~~for 1.7.21 or 9K.rc2 (which ever happens first)~~
for 1.7.22 or 9K.1.0 (which ever happens first)

... **0.9.8** [includes](https://github.com/jruby/jruby-openssl/releases/tag/v0.9.8) some improvements and bug fixes (at least one regression in 0.9.7)

**Comment by kares** [comment]
remaining failure on master with **0.9.8.dev** : https://travis-ci.org/jruby/jruby/builds/72430835

**Comment by mkristian** [comment]
https://travis-ci.org/jruby/jruby/jobs/72430858#L3412 is the problem that the prerelease is not used as default gem. though on other such integrity tests the same thing should go red (or you fixed it there ;)

just release the gem and all will be green again.

the tomcat error is a timing issue when tomcat shutsdown and probably some classloaders get closed before tomcat is finished (or so).

**Comment by kares** [comment]
this is now done and doing fine on master but jruby-1_7 seems to be having some sort of issues even with the released jruby-openssl **0.9.8** ... few test runs [seem to hang](https://travis-ci.org/jruby/jruby/jobs/73335711#L398) just like they did with the pre-release

**Comment by kares** [comment]
done a new release to handle a [regression](https://github.com/jruby/jruby-openssl/commit/ea6815f448cdf5a47e816f9f0fdc1ed3079c456e) and upgraded to **0.9.9**
