### ISSUE TITLE
Cannot delete file after requiring it on Windows in 9.0.0.0.rc1

### ISSUE THREAD

**Issue by jeremyevans** [jruby/jruby#3055]
Looks like this broke between pre1 and pre2:

```
D:\>C:\jruby-9.0.0.0.pre1\bin\jruby -e "File.open('a.rb', 'a'){}; require './a.rb'; File.delete('a.rb'); p 1"
1

D:\>C:\jruby-9.0.0.0.pre2\bin\jruby -e "File.open('a.rb', 'a'){}; require './a.rb'; File.delete('a.rb'); p 1"
Errno::EACCES: Permission denied - a.rb
  delete at org/jruby/RubyFile.java:1116
   <top> at -e:1

D:\>C:\jruby-9.0.0.0.rc1\bin\jruby -e "File.open('a.rb', 'a'){}; require './a.rb'; File.delete('a.rb'); p 1"
Errno::EACCES: Permission denied - a.rb
  delete at org/jruby/RubyFile.java:1116
   <top> at -e:1
```

It doesn't matter if the `a.rb` file already exists or if the process creates it, trying to delete it after requiring it raises the error.

Found by running Sequel's specs.

I didn't test on a *nix, but it's unlikely to be a problem there as *nix allows deletion of files that are in use.

**Comment by djberg96** [comment]
No problem on Windows 8 with MRI:

    PS C:\Users\Daniel> ruby -v
    ruby 2.0.0p645 (2015-04-13) [i386-mingw32]

    PS C:\Users\Daniel> ruby -e "File.open('a.rb', 'a'){}; require './a.rb'; File.delete('a.rb'); p 1"
    1

I don't know the implemenation details of require, but I wouldn't think it would retain a handle to the file once it was loaded.

**Comment by enebo** [comment]
Strange.  Lexer changed between those two but it should not retain a reference to anything which would retain a HANDLE.  Perhaps some IO fixes are hanging onto a handle in an IO table somewhere?  We do use IO.gets for a small amount of parsing now so it could ??? who knows...just brainstorming but thanks for heads up.

**Comment by djberg96** [comment]
@enebo can you point us to the IO.gets changes you're referring to?

**Comment by enebo** [comment]
@djberg96 org.jruby.lexer.GetsLexerSource

**Comment by djberg96** [comment]
I tried adding some explicit close calls in there, but then it complained about a closed stream, so I must have done it too soon.
