### ISSUE TITLE
Windows bin/*.bat files missing in 9.0.0.0.rc1

### ISSUE THREAD

**Issue by hathawad** [jruby/jruby#3059]
bin/gem.bat, bin/irb.bat, etc are all missing in the 64bit windows install for 9.0.0.0rc1

**Comment by enebo** [comment]
@mkristian Do you happen to know if you .bat generation changed in the last month or so?

**Comment by enebo** [comment]
This was done a few days ago and I verified that it is fixed in generated installers and bin dist.
