### ISSUE TITLE
Initializing hashes with Ruby 2.0+ string keys causes a syntax error if value is a literal

### ISSUE THREAD

**Issue by gabrielrotbart** [jruby/jruby#3068]
![screen shot 2015-06-19 at 1 59 59 pm](https://cloud.githubusercontent.com/assets/343879/8247060/fa5cc824-168c-11e5-81a7-47b99411f505.png)

Happy to write a failing spec if that helps.

**Comment by enebo** [comment]
This was fixed for 9.0.0.0.rc1.
