### ISSUE TITLE
popen3 doesn't work on Windows

### ISSUE THREAD

**Issue by yamam** [jruby/jruby#3075]
popen3 gets the following error on Windows.

```
$ jruby --version
jruby 9.0.0.0.rc1 (2.2.2) 2015-06-10 a0bf3b3 Java HotSpot(TM) Client VM 25.45-b02 on 1.8.0_45-b14 +jit [Windows 7-x86]

$jruby -r open3 -d -e 'Open3.popen3("notepad")'
io/console not supported; tty will not be manipulated
NotImplementedError: waitpid unsupported or native support failed to load
```

On jruby 1.7.x popen3 is implemented in RubyIO.java, and it works well.
Is there any way to use popen3 of RubyIO.java on jruby 9.0.0.0.rc1?

**Comment by headius** [comment]
Ahh, we will need to restore some code to use the older RubyIO.popen3 for popen3 on Windows until we're able to do a better job implementing Kernel#spawn there. Marking for RC2 and I'll look into it.

**Comment by headius** [comment]
I've committed the old open3.rb logic to work on Windows. This is not a perfect fix, but it should allow popen3 to work as well as it did in JRuby 1.7.x.

I'll file a separate issue to get full spawn support working on Windows.

**Comment by yamam** [comment]
Old  open3.rb (open3_windows.rb) uses IO::popen3. But, RubyIO::popen3 is sitll marked as Deprecated.
