### ISSUE TITLE
[Truffle] Double splat issue

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#3080]
Example
```ruby
def hello2(name = nil, **options)
  p name
  p options
end

hello2 'World'
```
Expected
```
$ ruby double.rb 
"World"
{}
```
Actual
```
$ ~/Documents/jruby/bin/jruby -X+T double.rb 
nil
{}
```

Example found here: https://dev.firmafon.dk/blog/drat-ruby-has-a-double-splat/

**Comment by chrisseaton** [comment]
Remind me to try this when all language specs as passing as I think it's covered there.

**Comment by bjfish** [comment]
@chrisseaton This double splat issue appears to be fixed now, thanks!
