### ISSUE TITLE
JavaLang::NullPointerException in RubySymbol.javaStringHashCode()

### ISSUE THREAD

**Issue by e2** [jruby/jruby#3086]
Happened on Travis here: https://travis-ci.org/guard/guard/jobs/68593045#L270

JRuby version: jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-06-27 e3ffe94 Java HotSpot(TM) 64-Bit Server VM 24.76-b04 on 1.7.0_76-b13 +jit [linux-amd64]

I couldn't find a duplicate issue. Meanwhile, I'll try and reproduce this locally.

Backtrace (extracted from above link):
```
     # org.jruby.RubySymbol.javaStringHashCode(RubySymbol.java:959)
     # org.jruby.RubySymbol.access$100(RubySymbol.java:76)
     # org.jruby.RubySymbol$SymbolTable.getSymbol(RubySymbol.java:690)
     # org.jruby.Ruby.newSymbol(Ruby.java:3508)
     # org.jruby.runtime.ArgumentType.toArrayForm(ArgumentType.java:53)
     # org.jruby.runtime.ArgumentDescriptor.toArrayForm(ArgumentDescriptor.java:40)
     # org.jruby.runtime.Helpers.argumentDescriptorsToParameters(Helpers.java:2513)
     # org.jruby.runtime.Helpers.methodToParameters(Helpers.java:2533)
     # org.jruby.RubyMethod.parameters(RubyMethod.java:294)
```

**Comment by e2** [comment]
Looks like it's still broken as of today:

Failure: https://travis-ci.org/guard/guard/jobs/69653719

Version: jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-07-04 dfdfb54 Java HotSpot(TM) 64-Bit Server VM 24.76-b04 on 1.7.0_76-b13 +jit [linux-amd64]

(@dfdfb54 - is HEAD at the moment)

Link to commit/source where it's crashing: https://github.com/jruby/jruby/blob/dfdfb542076b486125dc15c7e1f2510af9782686/core/src/main/java/org/jruby/RubySymbol.java#L961

**Comment by kares** [comment]
well, I only guessed what the guard spec is doing underneath so its possible I missed, thanks for verifying

**Comment by e2** [comment]
No prob. Let me know if I can shed some more light on this.

**Comment by headius** [comment]
Investigating.

**Comment by headius** [comment]
I've fixed where I think the problem was, added a regression spec, and bulletproofed the code leading to this NPE. It should be fine now, but let us know ASAP if it is not.
