### ISSUE TITLE
[Truffle] STDOUT is sync=true by default

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#3088]
This is just because Rubinius does it in common/io.rb `IO#setup`.
MRI and JRuby do not and "follow" standard UNIX programs having unbuffered STDERR, but buffered (by line on TTY, by block otherwise) STDOUT (at the `FILE*` level, see `setvbuf(3)`).
I am not sure what is best but this could potentially be a IO perf issue.

**Comment by chrisseaton** [comment]
Is there a RubySpec for this?

**Comment by eregon** [comment]
Not currently, I added them in https://github.com/ruby/rubyspec/commit/70b11404aa1f44e18b560d3d0de78ef827c1434e (will be merged in jruby later)
