### ISSUE TITLE
private method error in jruby-9.0.0.0.rc1

### ISSUE THREAD

**Issue by egadstar** [jruby/jruby#3123]
In my application, I'm using the active_interaction gem and the following works in MRI 2.2.2, JRuby 1.7.20, JRuby 9.pre1: https://gist.github.com/egadstar/6b33d76d8b3fc44733dc

In 9K.pre2 and 9K.rc1, I get the following when running the gist: 

NoMethodError: private method `foobar=' called for #<Bar::Foo:0x2488b073>
	from org/jruby/RubyKernel.java:1821:in `public_send'
	from /Users/egadstar/.rvm/gems/jruby-9.0.0.0.rc1/gems/active_interaction-2.0.1/lib/active_interaction/base.rb:225:in `block in populate_filters'
	from org/jruby/RubyHash.java:1342:in `each'
	from /Users/egadstar/.rvm/gems/jruby-9.0.0.0.rc1/gems/active_interaction-2.0.1/lib/active_interaction/base.rb:223:in `populate_filters'
	from /Users/egadstar/.rvm/gems/jruby-9.0.0.0.rc1/gems/active_interaction-2.0.1/lib/active_interaction/base.rb:215:in `process_inputs'
	from /Users/egadstar/.rvm/gems/jruby-9.0.0.0.rc1/gems/active_interaction-2.0.1/lib/active_interaction/base.rb:166:in `initialize'
	from /Users/egadstar/.rvm/gems/jruby-9.0.0.0.rc1/gems/active_interaction-2.0.1/lib/active_interaction/concerns/runnable.rb:108:in `new'
	from /Users/egadstar/.rvm/gems/jruby-9.0.0.0.rc1/gems/active_interaction-2.0.1/lib/active_interaction/concerns/runnable.rb:122:in `run'
	from (irb):2:in `<eval>'
	from org/jruby/RubyKernel.java:979:in `eval'
	from org/jruby/RubyKernel.java:1292:in `loop'
	from org/jruby/RubyKernel.java:1099:in `catch'
	from org/jruby/RubyKernel.java:1099:in `catch'

**Comment by headius** [comment]
The visibility for the `initialize_filter` method in active_interaction seems to be setting things up with private visibility. Investigating.

**Comment by headius** [comment]
I believe we already have a test for this, but we'll need to get the MixedModeIRMethod involved in those tests.
