### ISSUE TITLE
JAR files published on Maven Central are empty

### ISSUE THREAD

**Issue by lpellegr** [jruby/jruby#3130]
It seems that all JAR files published on Maven Central after end of January 2015 are empty (they contain a META-INF folder only).

You can check it by using the following URLs:  
  - http://goo.gl/9YIAzK
  - http://central.maven.org/maven2/org/jruby/jruby/

Is it normal? are artifacts published in another repository?

**Comment by mkristian** [comment]
this is how it is wanted. either just use the pom dependency which will have the actual jruby-core and jruby-stdlib as dependencies. or ignore the empty jar or use jruby-complete which is basically all the transitive dependencies of org.jruby:jruby combined into one fat-jar or uber-jar.

having the empty jar here makes it easier to declare jruby as dependency in the maven or gradle or ivy project. you are the first who got confused by this - sorry.

**Comment by lpellegr** [comment]
Thank you for the explanations.
