### ISSUE TITLE
expandPathInternal Windows compatibility

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#3132]
MRI: File.realpath 'c:/test' => 'c:/test'
jRuby: File.realpath 'c:/test' => 'C:\ \test' (tested on 1.7.19 and 9.0.0.0 rc2)

It causes problems in Rails applications, because Rails.root path is invalid.

https://github.com/jruby/jruby/blob/da5dad6a960425375a2921c54fccd55971250076/core/src/main/java/org/jruby/RubyFile.java#L1592

**Comment by headius** [comment]
You might test 1.7.21 but I don't expect it to be fixed there.

**Comment by ahorek** [comment]
* 1.7.21 same result

**Comment by ahorek** [comment]
https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyFile.java#L1632
```
=> realPath = JRubyFile.normalizeSeps(new File(realPath).getCanonicalPath());
```
