### ISSUE TITLE
jruby-9.0.0.0.rc2/lib/ruby/maven-home/bin/mvn not executable

### ISSUE THREAD

**Issue by annafw** [jruby/jruby#3134]
The file jruby-9.0.0.0.rc2/lib/ruby/maven-home/bin/mvn in the jruby 9000 rc2 release is not executable and it should be mode 755.

**Comment by headius** [comment]
Odd...I wonder why that's happening. Tagging @mkristian and @enebo.

**Comment by mkristian** [comment]
fixed via d451c159bb6ead123f6a647f6c5d3172c9e9c028
