### ISSUE TITLE
Provide sha256sums

### ISSUE THREAD

**Issue by BanzaiMan** [jruby/jruby#3135]
I'm duplicating https://github.com/jruby/jruby.github.io/issues/2, opened by @envygeeks for better visibility.

> Jekyll just started providing official JRuby support but we ran into a snag with our Docker images and our Deb's in that our build system requires Sha256sums to confirm a download, can you please start providing sha256sum's of your builds please?

**Comment by BanzaiMan** [comment]
(I disabled the issues on jruby/jruby.github.io, so the issue is no longer accessible.)

**Comment by headius** [comment]
I assume there's some maven magic we can use to do this automatically, but I was unable to find a nice plugin. I suppose since we use ruby-maven now we could just calculate them as part of the dist logic, eh @mkristian?

**Comment by mkristian** [comment]
I did google a bit and found:
http://nicoulaj.github.io/checksum-maven-plugin/index.html

this looks like we can add the sha256 digest to all artifacts on
maven-central.

but if it is just a thing for dist files which goes to jruby.org then I
would use a small script.

**Comment by envygeeks** [comment]
Sorry about posting it in the wrong spot, I had originally posted it here but moved it there because I thought it might be a website issue, thanks for moving it back and letting me know!

**Comment by enebo** [comment]
I think we can do this during post_process_artifacts task and use Ruby Digest for this.  We do not need this to push artifacts to maven so this is just for what we push to S3 right?

**Comment by mkristian** [comment]
to attach those checksums for maven-central is difficult. I added already something for binary zip and tar.gz but not for the source distributions. which again is less straight forward.

so I would appreciate to have all this be done in this 'post_process_artifacts' for S3 !

**Comment by enebo** [comment]
Next versions and these will get pushed to S3 and be reachable.  I do not have any immediate plans to add these to the web UI at this point since it would require some UI/CSS changes.  If that is important to anyone speak up now :)

**Comment by envygeeks** [comment]
It's semi-important to me but if you point me where to go, I'll be happy to pull request the changes, I don't expect you to do all the work because that would be unfair.

**Comment by enebo** [comment]
@envygeeks I am deluding myself...this is trivial...for someone I thought these were also on the nav bar.  They are on downloads page itself so I will just fix this when I release.  No PR Neccesary.
