### ISSUE TITLE
Hash#select! inconsistency with MRI when yielding only one argument

### ISSUE THREAD

**Issue by robin850** [jruby/jruby#3137]
Hello,

There's a tiny behavioral difference between MRI and JRuby regarding the `Hash#select!` method when there's only one argument passed to the method's block:

~~~ruby
>> h = {a: :b}

>> RUBY_ENGINE
=> "ruby"
>> h.select! { |k| p k }
:a

>> RUBY_ENGINE
=> "jruby"
>> h.select! { |k| p k }
[:a, :b]
~~~

The problem seems to be in [keep_ifCommon](https://github.com/jruby/jruby/blob/8020fee3500dda367b284a08efcb53407867a5d5/core/src/main/java/org/jruby/RubyHash.java#L1421) ; I tried to write a fix but I haven't been able to.

Have a nice day!

**Comment by kares** [comment]
you mean JRuby 1.7.x right? ... there's been a similar issue with [`take_while`](https://github.com/jruby/jruby/issues/2907)

**Comment by robin850** [comment]
@kares : Actually I did not test with 1.7, just with JRuby 9000

**Comment by kares** [comment]
quick test - 1.7.x behaves fine (compatibly with MRI 1.9.3) thus marking as 9K : 
```
jruby-1.7.20 :001 > h = {a: :b}
 => {:a=>:b} 
jruby-1.7.20 :002 > h.select! { |k| p k }
:a
```

**Comment by enebo** [comment]
This one is non-trivial to fix atm but it is pretty important so we will target this (along with several other block parameter bugs for first point release after release.

**Comment by enebo** [comment]
yieldSpecific with two args to a proc which receives one arg is broken atm but I changed these all to yieldArray.  I would try and fix yieldSpecific but we have a much larger task for blocks and it will get handled then.

**Comment by robin850** [comment]
Thanks for fixing this !
