### ISSUE TITLE
Gson gem fails to parse JSON on jruby9.0.0.0.rc1

### ISSUE THREAD

**Issue by r6p** [jruby/jruby#3139]
Cross-posting here in-case there is something valuable to fix in jruby 9K.

https://github.com/avsej/gson.rb/issues/7

**Comment by cheald** [comment]
It looks like RubyNumeric.str2fnum now expects a third "strict" parameter which isn't being passed by Gson. 1.7.20 has a [/2 version of the method](https://github.com/jruby/jruby/blob/1_7_20/core/src/main/java/org/jruby/RubyNumeric.java#L331-L333) that is missing in 9k.

**Comment by cheald** [comment]
This was broken in 2832da57cf5f255f531835ef2340c8376cae69a0
