### ISSUE TITLE
shift and rehash methods in Array and Hash

### ISSUE THREAD

**Issue by morallo** [jruby/jruby#3142]
Currently it throws a "NotImplementedError" in [MapJavaProxy.java](https://github.com/jruby/jruby/blob/1.7.20/core/src/main/java/org/jruby/java/proxies/MapJavaProxy.java#L190), and it is not defined in [ArrayJavaProxy.java](https://github.com/jruby/jruby/blob/1.7.20/core/src/main/java/org/jruby/java/proxies/ArrayJavaProxy.java)

However, the methods seem to be implemented in [RubyHash.java](https://github.com/jruby/jruby/blob/1.7.20/core/src/main/java/org/jruby/RubyHash.java#L1546) and [RubyArray.java](https://github.com/jruby/jruby/blob/1.7.20/core/src/main/java/org/jruby/RubyArray.java#L1200)

Is it a matter of connecting pipes, or am I missing something? Maybe the current implementation in RubyArray and RubyHash does not work?

**Comment by headius** [comment]
Java Maps do not support rehash, so that's why we raise NotImplementedError. I suppose we could just do nothing, since rehash is largely an invisible operation.

For Java arrays, shift has no meaning; they are fixed-size. I think in this case we need to preserve the NotImpl error.

**Comment by headius** [comment]
> For Java arrays, shift has no meaning; they are fixed-size. I think in this case we need to preserve the NotImpl error.

I mean we should leave it unimplemented. Java arrays are not like Ruby arrays. If you want a Ruby array, call to_a.

**Comment by headius** [comment]
May I ask why you are calling these methods against Java maps? Perhaps we can help you find an alternative, because at least in the case of `shift` I don't think we can do anything.

**Comment by headius** [comment]
I should point out that rehash *does* work when the particular Java Map supports it, but it doesn't exist for all Map impls:

```
[] ~/projects/jruby $ jruby -e "java.util.Hashtable.new.rehash"

[] ~/projects/jruby $ jruby -e "java.util.HashMap.new.rehash"
NotImplementedError: rehash method is not implemented in a Java Map backed object
  rehash at org/jruby/java/proxies/MapJavaProxy.java:310
   <top> at -e:1
```

**Comment by morallo** [comment]
I'm writing a custom plugin for [logstash](https://github.com/elastic/logstash/).
The events that I get when my code is called by the main application are Java maps.

If I use to_a, I'm afraid I will get a copy of the event, and won't be able to modify referenced map itself.

**Comment by headius** [comment]
Re maps: I can make rehash work, but there's no equivalent to shift for Java maps.

Re arrays: Java arrays have fixed size, so size-altering methods will never have an equivalent. Not really anything we can do about that :-\

**Comment by headius** [comment]
I've pushed the rehash change, and improved the shift error message. That's about all we can do, so I'm marking this fixed.

**Comment by morallo** [comment]
Ok, thx anyway!

**Comment by headius** [comment]
Oh, one last change I will do...if I mark the default rehash and shift as unimplemented, they should not show up in respond_to? checks.
