### ISSUE TITLE
Improve handling of $! in exception logic

### ISSUE THREAD

**Issue by headius** [jruby/jruby#315]
For #311, @subbuss wrote the following comment, which describes the work needed for this issue:

The reason -X+C doesn't have this bug is because I did not clean up the JIT to remove the $! hack as I did with -X-CIR and -X-C (See commit log note in 7c3f642). Curious why this example doesn't fail in -X-CIR mode since IR doesn't have the $! hack either. I do know that in IR mode, $! is saved and restored properly in IR-generated code, so maybe the clobbering in the runtime does not matter ... but just a guess.

The bigger issue that this bug exposes is that "$!" is a proxy for the errorInfo value in ThreadContext and so, $! can be modified indirectly by directly calling setErrorInfo. Ideally, in later commits, we should do the following:
- clean up the JIT to get rid of the $! hack as done for the AST interp in 20632af
- audit all uses of setErrorInfo to see if they clobber $! accidentally anywhere else.
- unify the globalVariables.set("$!", foo) and setErrorInfo(foo) paths so that we use one or the other uniformly, if feasible.

**Comment by enebo** [comment]
@subbuss I believe to fix this we just need to change the JIT to use same logic as RuntimeHelperCall.RESTORE_EXCEPTION_LOGIC?  @headius maybe we can do this for 9.2.x to get it off the books.

**Comment by subbuss** [comment]
Oh man .. . this feels like ancient history now .. :) I don't remember offhand.

**Comment by headius** [comment]
I'm not sure if this is still an issue...and after reading it a couple times I'm not actually sure how to reproduce this. Bumping to 9.2.1 but maybe it's not an issue anymore @enebo @subbuss?

**Comment by headius** [comment]
I'm going to kill this one. Exception handling has been reworked multiple times since this issue, and the JIT and interpreter should be doing the same logic at this point.

**Comment by headius** [comment]
I pushed a commit above that removes the related logic...because it doesn't appear to do anything anymore. The logic for JIT expected to see an IRubyObject that is also an instance of IRReturnJump or IRBreakJump. Such a beast does not exist in our codebase, so this code has not been executing for some time.
