### ISSUE TITLE
Add complete jar and other release artifacts to ci.jruby.org builds

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3154]
Subject says it all.

**Comment by donv** [comment]
The artifacts have been added to http://ci.jruby.org/, but the jruby-1_7 build is broken, so the artifacts are not published to S3.

https://projectodd.ci.cloudbees.com/view/JRuby/job/jruby-1.7-dist/

**Comment by headius** [comment]
The build has been fixed in 2e47b23 (which is pretty stupid...why are these versions not getting updated properly?).

**Comment by donv** [comment]
Thanks!
