### ISSUE TITLE
Different results for `to_h` and `to_hash` on `ENV`

### ISSUE THREAD

**Issue by dg-ratiodata** [jruby/jruby#3162]
Hi,

converting `ENV` to a `Hash` gives different results. It depends on which `to_`-method is used.

*MRI*

~~~ruby
ENV.object_id
# => 17981260
ENV.to_h.object_id
# => 22183040
ENV.to_hash.object_id
# => 22148380
~~~

*JRuby*

~~~ruby
ENV.object_id
# => 2042
ENV.to_h.object_id
# => 2042
ENV.to_hash.object_id
# => 2044
~~~

**Comment by maxmeyer** [comment]
The same is true for jruby 9000. 

~~~
irb(main):006:0> ENV.object_id
=> 2050
irb(main):007:0> ENV.to_h.object_id
=> 2050
irb(main):008:0> ENV.to_hash.object_id
=> 2052
~~~

~~~
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 OpenJDK 64-Bit Server VM 24.85-b03 on 1.7.0_85-b01 +jit [linux-amd64]
~~~

**Comment by maxmeyer** [comment]
Will there be a release for 1.7 and 9000 containing the fix?

**Comment by kares** [comment]
eventually yes but probably no rushing due this, please note that for **1.7.x** `ENV.to_hash` is already working as expected and `ENV.to_h` should actually not exists (up till Ruby 2.0) ... will be honoured (since 1.7.22)
