### ISSUE TITLE
dup on Range regression

### ISSUE THREAD

**Issue by etehtsea** [jruby/jruby#3163]
JRuby 9k final:

```
>> Range.new(0, 1000).dup
NameError: `initialize' called twice
	from org/jruby/RubyRange.java:247:in `initialize_copy'
	from org/jruby/RubyKernel.java:1860:in `initialize_dup'
	from org/jruby/RubyKernel.java:1898:in `dup'
```

JRuby 1.7.20.1:

```
>> Range.new(0,1000).dup
=> 0..1000
```

**Comment by cheald** [comment]
This was broken in the course of fixing an MRI test:

    def test_initialize_twice
      r = eval("1..2")
      assert_raise(NameError) { r.instance_eval { initialize 3, 4 } }
      assert_raise(NameError) { r.instance_eval { initialize_copy 3..4 } }
    end

And apparently `#dup` calls `initialize_copy`. I'll get into the MRI source and figure out what it's doing differently.
