### ISSUE TITLE
9k fail to compile ruby code of using multibyte char on Windows

### ISSUE THREAD

**Issue by yousuketto** [jruby/jruby#3175]
I have used jruby 9.0.0.0 on Windows.
9k fail to compile ruby code of using multibyte char.
I was comfirmed using `jrubyc` and `JRuby.compile_ir`, `warble compiled war`

- ex) use jrubyc
```ruby
# coding: utf-8
puts "あ"
```
```
C:\workspace>jrubyc target.rb
SyntaxError: target.rb:2: invalid multibyte char (UTF-8)
puts "???"

                                parse at file:/C:/workspace/jruby-9.0.0.0/lib/jruby.jar!/jruby/jruby.rb:66
                           compile_ir at file:/C:/workspace/jruby-9.0.0.0/lib/jruby.jar!/jruby/jruby.rb:78
  block in compile_files_with_options at C:/workspace/jruby-9.0.0.0/lib/ruby/stdlib/jruby/compiler.rb:159
                                 call at org/jruby/RubyProc.java:308
  block in compile_files_with_options at C:/workspace/jruby-9.0.0.0/lib/ruby/stdlib/jruby/compiler.rb:291
                                 each at org/jruby/RubyArray.java:1560
           compile_files_with_options at C:/workspace/jruby-9.0.0.0/lib/ruby/stdlib/jruby/compiler.rb:275
                         compile_argv at C:/workspace/jruby-9.0.0.0/lib/ruby/stdlib/jruby/compiler.rb:94
                                <top> at C:/workspace/jruby-9.0.0.0/bin/jrubyc:5
```

**Comment by enebo** [comment]
This does seem to be windows-specific in as much as I tried playing with JVM -Dfile.encoding and could not get MacOS to fail.

**Comment by enebo** [comment]
@yousuketto On my machine the utf-8 for 'a' in Hiragana does not show up as that symbol in either .rb or .class compiled.  On MacOS, with CP-1252 as my file.encoding it does show up correctly.  I think this has more to do with displaying output than JRuby improperly compiling this (it is possible we have a different bug with displaying this properly on windows though).  So I believe this is fixed.  At least I know I fixed 2 issues with jrubyc.

**Comment by yousuketto** [comment]
@enebo Thank you so much. I have been able to compile.
