### ISSUE TITLE
Encoding::UndefinedConversionError: Input length = 1

### ISSUE THREAD

**Issue by lkfken** [jruby/jruby#318]
SOURCE:
```
#coding: utf-8
string = %q{你好}

puts Encoding.default_external
puts string.encoding
File.open("test.xml", "w") do |f|
  f.write string
end
```

With jruby 1.7.0.RC1 (1.9.3p203) 2012-09-25 8e849de on Java HotSpot(TM) Client VM 1.6.0_35-b10 [Windows XP-x86], the output...
```
Windows-1252
UTF-8
Encoding::UndefinedConversionError: Input length = 1
   write at org/jruby/RubyIO.java:1401
  (root) at X:/ene/RubyScripts/1development/try_msword/app.rb:24
    open at org/jruby/RubyIO.java:1180
  (root) at X:/ene/RubyScripts/1development/try_msword/app.rb:23
    load at org/jruby/RubyKernel.java:1045
  (root) at -e:1

Process finished with exit code 1
```
With MRI ruby 1.9.3p125 (2012-02-16) [i386-mingw32], the output...
```
UTF-8
UTF-8

Process finished with exit code 0
```
Apparently, Encoding.default_external returns different values.
Also, I cannot write to a file if the string is UTF-8 under JRuby.  However, the same code works fine under MRI Ruby.

**Comment by rtyler** [comment]
This does appear to be fixed with JRuby 9k, @lkfken if you see that the example case is still broken with 9.0.0.0 please re-open this issue
