### ISSUE TITLE
IO.puts is not thread safe

### ISSUE THREAD

**Issue by samwgoldman** [jruby/jruby#3182]
I have some logging code that looks like this:

``` ruby
def log(line)
  io.puts(line)
  io.fsync
end
```

This code is called from multiple threads.

In production, I've noticed lines that there are lines that look like this: `"#{line1}#{line2}\n\n"`.

I looked into it, and it looks like `puts` might have a race condition between writing the line and writing the subsequent newline. See https://github.com/jruby/jruby/blob/0be4796b08f027c5cdf8c7400ca0563237db5031/core/src/main/java/org/jruby/RubyIO.java#L2526.

Some repro code:

``` ruby
require 'thread'
8.times.map do
  Thread.new do
    1000.times do
      $stdout.puts "line"
      $stdout.fsync
    end
  end
end.map(&:join)
```

To test:

`ruby puts.rb | grep lineline`

/cc @cheald

**Comment by Freaky** [comment]
MRI does exactly the same thing: https://github.com/ruby/ruby/blob/trunk/io.c#L7102

You've always had to do `io.write "line\n"` to avoid it.

**Comment by cheald** [comment]
As Freaky points out, MRI does indeed exhibit this interleaving behavior.

That said, I would argue the behavior is surprising and probably should be fixed in MRI, too!
