### ISSUE TITLE
jruby 9K + maven plugins no longer working

### ISSUE THREAD

**Issue by kares** [jruby/jruby#3184]
maybe due to Psych/RGs ... anyways it can not download rubygems packages from the proxy : 
```
[INFO] uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/psych.rb:229: warning: already initialized constant LIBYAML_VERSION

[INFO] ERROR:  While executing gem ... (Gem::Package::FormatError)

[INFO]     package is corrupt, exception while verifying: undefined method `path2class' for #<Psych::ClassLoader:0x54bdcfd3> (NoMethodError) in /home/travis/.m2/repository/rubygems/jar-dependencies/0.1.15/jar-dependencies-0.1.15.gem

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 01:18 min

[INFO] Finished at: 2015-07-24T20:46:54+00:00

[INFO] Final Memory: 16M/465M

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal de.saumya.mojo:gem-maven-plugin:1.0.10:initialize (default-initialize) on project jruby-openssl: Execution default-initialize of goal de.saumya.mojo:gem-maven-plugin:1.0.10:initialize failed: Java returned: 1 -> [Help 1]
```
... taken from the following job travis job: https://travis-ci.org/jruby/jruby-openssl/jobs/72473886

**Comment by jkutner** [comment]
ack, just hit this too :(

**Comment by enebo** [comment]
Is this something that can be fixed in a updated jruby-jars or do we fix it in 9.0.1.0 (I guess either way the fix will be in 9.0.1.0)?

**Comment by mkristian** [comment]
this happens when there is jruby-9k on bootclasspath and jruby-1.7.x on the classpath :(

adding the config addProjectClasspath = false will help to separate the jruby plugin from the project itself.

**Comment by kares** [comment]
this re-appeared last week on jruby-1_7 builds and was able to reproduce locally (for sure seemed not related to 9K being on class-path) ... but than went away the week after :) so calling it a close for now
