### ISSUE TITLE
PTY.spawn doesn't pass arguments

### ISSUE THREAD

**Issue by Freaky** [jruby/jruby#3185]
```
require 'pty'
r, w, pid = PTY.spawn('/usr/bin/yes', 'nope')
p r.gets # => "y\r\n"
```

Should return "nope\r\n".

**Comment by rtyler** [comment]
@Freaky what version of JRuby and JDK are you using?

And just as a sanity check, does MRI return `nope\r\n` like you expected?

**Comment by Freaky** [comment]
Reproduced on last night's build:

jruby 9.0.1.0-SNAPSHOT (2.2.2) 2015-08-01 faa1398 OpenJDK 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 +jit [FreeBSD-amd64]

Behaviour was identical in 9.0.0.0.  It also completely hung several times in a row attempting to reproduce it, presumably the same issue as #3020.

MRI 2.2.2 works as expected and I'm yet to see it hang.

**Comment by Freaky** [comment]
Oddly, the code *looks* like it should just work by replacing line 67:

    self.getpty("/bin/sh", "-c", args[0], &block)

With:

    self.getpty("/bin/sh", "-c", *args, &block)

build_args builds the array of string pointers from the full argument list to pass to execvp, and it evidently works for the first few arguments or it would never get beyond just calling /bin/sh with no arguments.

**Comment by Freaky** [comment]
Bah, that's just how $shell -c works isn't it.  Just needs a Shellwords.join, or a "$@" in the command command.

**Comment by Freaky** [comment]
I think this is a reasonable first-approximation of a partial fix:

    diff --git lib/ruby/stdlib/pty.rb lib/ruby/stdlib/pty.rb
    index a68e2b9..e44bb1e 100644
    --- lib/ruby/stdlib/pty.rb
    +++ lib/ruby/stdlib/pty.rb
    @@ -64,6 +64,10 @@ module PTY
         end
       end
       def self.spawn(*args, &block)
    -    self.getpty("/bin/sh", "-c", args[0], &block)
    +    if args.size > 1
    +      self.getpty(*args, &block)
    +    else
    +      self.getpty("/bin/sh", "-c", *args, &block)
    +    end
       end
    end

This allows MRI's test_pty.rb to actually complete occasionally, instead of always hanging on `test_commandline` due to spawning just `ruby` instead of `ruby -e "puts ..."`.

Still plenty missing, and still hangs for me more often than not, but it's better than spawning entirely the wrong command.

**Comment by enebo** [comment]
@Freaky yeah if you want to send a PR then we can give you credit for a partial fix at least?  If you want to work on this more and isolate more wrong behavior...we would love it :)

This code in MRI is in C and ours in is Ruby so seeing etc/pty/pty.c in MRI source probably will help in showing what else is wrong with our version.  In glancing at the C source I can see another mistake in that getpty and spawn are aliases so I believe sh logic should not only be in spawn (also handling of SHELL env var).

**Comment by Freaky** [comment]
Yep, I'll give it all a closer look when I get the chance.  I think the most important thing is getting it to stop hanging all the time - there's not much point in fixing the API structure if using it is going to hang jruby 60% of the time.

**Comment by Freaky** [comment]
OK, having had more of a chance to look at this, the whole thing boils down to fork being impossible to do safely.  This probably should have been left a NotImplementedError rather than giving people code that's just broken and only works occasionally by accident.

I think rewriting based around `openpty(3)` and `Process#spawn` is probably doable.

**Comment by Freaky** [comment]
https://github.com/Freaky/jruby/blob/fix-pty/lib/ruby/stdlib/pty.rb

Passes MRI's test suite.

**Comment by headius** [comment]
See #3020 for other pty problems. The pty library is currently a bit broken on JRuby and unlikely to be fixed soon because it needs to fork.

@Freaky Never saw your pty.rb...I'll have a look and maybe it will help.

**Comment by headius** [comment]
@Freaky Wow, I wish I'd have seen this a year ago. I'll pull it in!
