### ISSUE TITLE
jruby-1_7 merge failures on master

### ISSUE THREAD

**Issue by kares** [jruby/jruby#3188]
... probably something :wrench:  on my end NOT understanding the change-set enough :(

* `require_relative symlink2` failing for no apparent reason (maybe a 9K change - need to confirm)
  https://travis-ci.org/jruby/jruby/jobs/72657983#L3249-L3273

* newly added it test from https://github.com/jruby/jruby/commit/e6632c0a00fb7a43d9b8754573cb98102365cc12 ... fails (despite the relevant changes in)
  https://travis-ci.org/jruby/jruby/jobs/72657994#L4709-L4714

* the "main" hack from https://github.com/jruby/jruby/commit/917d0e7ddad7ddbc792a274ebed3b933b3b6453f seems to not work (just wasn't sure if it simply needs reverting) #3141
  https://travis-ci.org/jruby/jruby/jobs/72657995#L3745-L3753

@mkristian I know its an added time but please consider merging changes such as these from **jruby-1_7** *promptly* as if you re-call its not the first time and its quite hard for someone not understanding the branch diversions you did esp. `uri:classloader:/` magic + ITs

**Comment by mkristian** [comment]
@kares I wanted to do the merge first thing on monday. but you are right I will do merge things immediately the next time.

all those problems above seems to be on my plate.

**Comment by mkristian** [comment]
@kares I think I fixed all those little things beside the compiler https://travis-ci.org/jruby/jruby/jobs/72823180

NPE in reflect.Method :( not sure where this comes from

**Comment by kares** [comment]
@mkristian yes you did, thanks. I also maybe shouldn't have started merging on weekend.
the compiler spec was introduced (today) at https://github.com/jruby/jruby/commit/8f8081649a7ecb030b8da1b692ce425ce6edf908 ... left a comment there
