### ISSUE TITLE
Overiding Windows Path and 'hide' Ruby installation

### ISSUE THREAD

**Issue by Javix** [jruby/jruby#3190]
If you already have Ruby installed on a Windows PC before installing JRuby, JRuby will write its `bin` folder to the Path and precede the Ruby `bin` path. As a result, when running `gem list` to display just Ruby gems, you will get a JRuby gem list. To fix that, I had just to modify Windows path (environnement variables) and put Ruby `bin` just before the JRuby's one.

Reproduced on:
- Windows PC, Windows 7 Professional
- Installed Ruby version: `ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]`
- Installed JRuby versio: `jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 Java HotSpot(TM) 64-Bit Server VM 24.79-b02 on 1.7.0_79-b15 +jit [Windows 7-amd64]`

**Comment by kares** [comment]
really nothing to be done here. if you do the opposite (install JRuby first) than you end up with the same.
safest bet is to use -S and or a Ruby installation manager (believe there was something available for Win).
