### ISSUE TITLE
Trapping reserved signals doesn't print a meaningful message

### ISSUE THREAD

**Issue by kyrylo** [jruby/jruby#3208]
Let's trap a reserved signal:

```ruby
trap(:ILL) {}
```

Output from MRI:

```
ArgumentError: can't trap reserved signal: SIGILL
```

Output from JRuby 9.0.0.0

```
ArgumentError: malformed format string - %S
from org/jruby/RubyString.java:1168:in `%'
```

It seems like JRuby tries to print the error, but fails for some reason.

**Comment by Freaky** [comment]
Simple format string error from holding down shift too long:

     raise ArgumentError.new("can't trap reserved signal: SIG%S" % sig)
