### ISSUE TITLE
Inconsistent Dir.glob() behavior w/ Jars

### ISSUE THREAD

**Issue by drbobbeaty** [jruby/jruby#321]
## Set-up

The context is the [Configulations](https://github.com/leongersing/configulations) Gem and using it with a [Warbler](https://github.com/jruby/warbler) deployed jar and JRuby 1.7.0.RC1. The code traditionally looks like this:
```ruby
  app_config = Configulations.new(File.dirname(__FILE__) + '/../config')
```
assuming that this ruby file is in the `lib` directory parallel to the `config` directory with the files for Configulations.

Everything works **perfectly** on Mac OS X 10.7.5 (up to date) with the JRE 1.6.0_35. This includes running it as a jruby script as well as running it from the executable jar built by Warbler.

## The Problem

The deployment box is a linux CentOS 5 box, and under jruby 1.6.7.2 has been working just fine. The JRE on this box is:

    java version "1.7.0_05"
    Java(TM) SE Runtime Environment (build 1.7.0_05-b05)
    Java HotSpot(TM) 64-Bit Server VM (build 23.1-b03, mixed mode)

and when using the same Warbler-created jar that has been scp'ed to this machine, the application fails.

I've dug into the problem and it appears that the following is the core issue:
```ruby
def glob_config_files_at(dir)
  Dir.glob("#{dir}/*.{#{ext_glob_string}}")
end
```
where on Mac OS X 10.7.5/JRE 1.6.0_35 the `Dir.glob()` call comes back with the correct directory listing whether it's run as a jruby script (on the filesystem) or if it's run within a Warbler-created executable jar.

On the CentOS box, with the JRE 1.7.0_05 the return value with the executable jar is the empty array:

    []

## Comparison to JRuby 1.6.7.2

As I said, on 1.6.7.2 on the same CentOS box, this code works flawlessly.

## Conclusions?

I'm concerned that it _appears_ to be an effect in jruby 1.7.0.RC1 (because 1.6.7.2 is fine) but only when using the 1.7.0_05 JRE on CentOS (Mac OS X JRE 1.6.0_35 is fine). This is a pretty specific issue, then, and I didn't see anything in the bug reports like it.

**Comment by mkristian** [comment]
as the example of @lolindrath works with current master and jruby-1_7 branch is looks like fixed. closing
