### ISSUE TITLE
Add snapshot of "jruby-jars-*.gem" to the CI build

### ISSUE THREAD

**Issue by donv** [jruby/jruby#3213]
The last snapshot build of the ```jruby-jars``` gem should be downloadable from http://ci.jruby.org/ for both stable branches.

Ruboto tests need them to test JRuby changes continually.

How are these artifacts created?

**Comment by donv** [comment]
`jruby-jars`builds are now available from http://ci.jruby.org/ , but the build seems broken.

@mkristian has tried to fix it, but he does not have access to trigger a new build, so the development cycle is 24 hours (a bit slow) :)

Having fresh `jruby-jars` builds available helps catching JRuby bugs for embedded use like Ruboto earlier.

**Comment by donv** [comment]
This is the build that is failing:  https://projectodd.ci.cloudbees.com/view/JRuby/job/jruby-1.7-dist/

**Comment by donv** [comment]
@headius @enebo Maybe I and/or @mkristian could get access  to trigger JRuby ci builds?  Access to the build configuration would also be good.

**Comment by headius** [comment]
The build has been fixed in 2e47b23 (which is pretty stupid...why are these versions not getting updated properly?).

**Comment by donv** [comment]
Thanks!

**Comment by mkristian** [comment]
@headius I improved your patch a bit since the update of those versions are a manual sed script or so. c7ce772a4acc3257ebd96e2c8b26670e260a7170 not sure why the removal of the -SNAPSHOT is not needed anymore ?
