### ISSUE TITLE
Socket.unix and friends use missing Addrinfo features

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3229]
Reported on IRC...

Trying to use `Socket.unix("path")` fails with `IOError: path: Name or service not known`

This method and a few others like it are implemented using Addrinfo to produce the new socket. Since Addrinfo is not fully implemented on JRuby, there's some missing pieces here.

This affects at least JRuby 1.7 and may affect 9k, but I have not confirmed.

**Comment by etehtsea** [comment]
Issue remains in 9k:

```
>> require 'socket'; Socket::Addrinfo.unix('/Users/kes/Projects/redis/oxblood/tmp/redis-91928c35e0bd.sock')
(irb):1: warning: toplevel constant Addrinfo referenced by Socket::Addrinfo
IOError: /Users/kes/Projects/redis/oxblood/tmp/redis-91928c35e0bd.sock: unknown error
	from org/jruby/ext/socket/Addrinfo.java:119:in `initialize'
	from org/jruby/ext/socket/Addrinfo.java:245:in `unix'
	from (irb):1:in `<eval>'
	from org/jruby/RubyKernel.java:981:in `eval'
	from org/jruby/RubyKernel.java:1288:in `loop'
	from org/jruby/RubyKernel.java:1101:in `catch'
	from org/jruby/RubyKernel.java:1101:in `catch'
	from /Users/kes/.rbenv/versions/jruby-9.1.3.0-SNAPSHOT/bin/jirb:13:in `<top>'
```

```
>> require 'socket'; Socket::Addrinfo.unix('/Users/kes/Projects/redis/oxblood/tmp/redis-91928c35e0bd.sock')
(irb):1: warning: toplevel constant Addrinfo referenced by Socket::Addrinfo
=> #<Addrinfo: /Users/kes/Projects/redis/oxblood/tmp/redis-91928c35e0bd.sock SOCK_STREAM>
```

**Comment by enebo** [comment]
@etehtsea the second example working is MRI demonstrating it should work?  Or was it a typo showing what your PR does in that UnixSocket.new works?

**Comment by etehtsea** [comment]
@enebo sorry, forgot to add description. Yeap, this is demonstration that the same line is working in MRI.

**Comment by headius** [comment]
This should be improved on the ruby-2.3+socket branch but I have not completed that work yet :-(
