### ISSUE TITLE
Usage of deprecated and unimplemented Thread.stop(Throwable)

### ISSUE THREAD

**Issue by jussimarttila** [jruby/jruby#3232]
JRuby seems to use the above mentioned method in code, which will break at least on any remotely modern Oracle JDKs (as well as hide the original exception).

Originally encountered here http://stackoverflow.com/questions/31870750/logstash-unexpectedly-stopped/31872698

The current version of RubyThread still seems to call it in certain circumstances.

**Comment by rtyler** [comment]
@jussimarttila Can you list which JDK you've observed the problem from the linked SO thread?

I don't know logstash well enough to tell what kind of JRuby version is being used, so if you know that, it is also useful

**Comment by rtyler** [comment]
This looks like it might be related to #1183

**Comment by jussimarttila** [comment]
I don't have the JRuby version used in the original problem, but it doesn't matter. Even the current codebase contains a call to Thread.stop(Throwable). While Thread.stop() has been deprecated, it still works, whereas Thread.stop(Throwable) has no implementation starting from JDK 1.8.

**Comment by headius** [comment]
Ahh, nice find. I didn't realize they'd finally started to make this really deprecated.

The only instance I could find was for propagating a Thread.abort_on_exception to the main thread. I'm testing a change to just use the existing thread event logic for that. It will be less guaranteed to fire, but no more so than for other cross-thread exception raises.
