### ISSUE TITLE
Rails.root set to "uri:classloader:/" for new Rails app with JRuby 9.0.0.0

### ISSUE THREAD

**Issue by donv** [jruby/jruby#3233]
For a new Rails app running the Rails runner prefixed with ```jruby -S``` make ```Rails.root``` get the value ```uri:classloader:/```.  Starting without the ```jruby -S``` prefix works as expected.

```
$ rvm use jruby
Using /Users/uwe/.rvm/gems/jruby-9.0.0.0
$ gem install rails
Successfully installed rails-4.2.3
$ rails new test_app
      create  
      ...
$ cd test_app
$ ruby -S rails r "puts Rails.root"
uri:classloader:/
$ rails r "puts Rails.root"
/Users/uwe/workspace/jruby/test_app
```

The effect is the same with JRuby installed via RVM or by downloading and unpacking the JRuby 9.0.0.0 tarball.

**Comment by donv** [comment]
Reproduced on OS X 10.10.4 and Centos 6.5.

**Comment by donv** [comment]
Same behaviour using Java 8 or Java 7.

**Comment by mkristian** [comment]
needs rvm to reproduce it !!!

**Comment by mkristian** [comment]
the only workaround I know is to use "rbenv" instead of "rvm"

**Comment by donv** [comment]
@mkristian do you know what rbenv does differently?

**Comment by mkristian** [comment]
@donv rbenv installs the bin stubs in JRUBY_HOME/bin (which is actually the default from dist install as well) - not sure where rvm installs them. but  JRUBY_HOME/bin is the first location it looks for bin files. then comes the classpath where things fail for rails.

**Comment by donv** [comment]
A simple workaround is to specify the relative path to the binary:

```
$ ruby -S rails r 'puts $0'
uri:classloader:/bin/rails
$ ruby -S bin/rails r 'puts $0'
bin/rails
```

```
 jruby -S rails r "puts Rails.root"
uri:classloader:/
$ jruby -S bin/rails r "puts Rails.root"
/Users/uwe/workspace/jruby/test_app
```

**Comment by donv** [comment]
Verified that it works with jruby-head from RVM:

```
$ rvm use jruby-head
Using /Users/uwe/.rvm/gems/jruby-head
$ ruby -v
jruby 9.0.1.0-SNAPSHOT (2.2.2) 2015-08-07 926fbb7 Java HotSpot(TM) 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 +jit [darwin-x86_64]
$ jruby -S rails r "puts Rails.root"
/Users/uwe/workspace/jruby/test_app
$ ruby -S rails r 'puts $0'
/Users/uwe/workspace/jruby/test_app/bin/rails
```
