### ISSUE TITLE
What determines whether Process.kill is supported?

### ISSUE THREAD

**Issue by lukehorvat** [jruby/jruby#3244]
Hi, I'm attempting to run a Rails app on a Raspberry Pi as a WAR file (packaged via Warbler).

I get this error because I'm using `Process.kill` throughout my codebase:

```
file:/tmp/jruby6309588954101406081extract/gems/gems/jruby-jars-1.7.21/lib/jruby-core-1.7.21.jar!/jruby/kernel/jruby/process_manager.rb:28 warning: executable? does not in this environment and will return a dummy value
Exiting
ERROR: org.jruby.exceptions.RaiseException: (NotImplementedError) kill unsupported or native support failed to load
```

So what determines whether `Process.kill` is supported? Given that Raspbian is POSIX, I'd have thought it would just work?

**Comment by rtyler** [comment]
The [RubyProcess class implements Process.kill](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyProcess.java#L1004-L1098) and I *believe* that where this code is actually coming from is in the [jnr-posix](/jnr/jnr-posix) library, perhaps [from here](https://github.com/jnr/jnr-posix/blob/master/src/main/java/jnr/posix/JavaPOSIX.java#L256-L258).

I would bet dollars to donuts that this is something to do with some native libraries not being present for your arm platform.

**Comment by lukehorvat** [comment]
Yep, I think you're right. The call to `loadNativePOSIX` [here](https://github.com/jnr/jnr-posix/blob/master/src/main/java/jnr/posix/POSIXFactory.java#L90) must be returning `null` or throwing an exception.

Killing the process via backticks (i.e. \`kill #{pid}\`) works, but it's not ideal. Do you think I should raise an issue on jnr-posix?

**Comment by rtyler** [comment]
@lukehorvat it certainly can't hurt, if you've got a small ruby script that spawns and then attempts to kill the child process, that would also help I think

**Comment by enebo** [comment]
1.7.x is EOL and this will not get fixed.  Marking WONTFIX
