### ISSUE TITLE
Parser fails on `assert_equal(true, (not ()))` expresion

### ISSUE THREAD

**Issue by pitr-ch** [jruby/jruby#3245]
I am getting a NullPointerException `/Users/pitr/Workspace/labs/jruby/test/mri/lib/test/unit.rb:257:in `require': internal implementation error - NullPointerException null org.jruby.parser.ParserSupport.cond0(ParserSupport.java:544) (RubyTruffleError)`. I've tracked it down to this expression `assert_equal(true, (not ()))` in `test/mri/ruby/test_not.rb`. Could you look at it?

**Comment by enebo** [comment]
I solved this differently than MRI which was adding lots of null checks by returning () as nil.  I think this should be safe if you consider '()' in other non-parameter contexts like:

```ruby
p () #=> "nil"
```

**Comment by pitr-ch** [comment]
@enebo Thanks for quick fix. Reenabling in truffle MRI tests too.

**Comment by enebo** [comment]
@pitr-ch cool.  If you find more (as we have tons of tests commented out) then open up issues.  I should be able to fix parsing issues quick.  This '()' has been one which seems to never completely go away...
