### ISSUE TITLE
require 'digest/bubblebabble' fails

### ISSUE THREAD

**Issue by kares** [jruby/jruby#3246]
`bin/jruby -rdigest -e "p Digest.bubblebabble ''"` does not work in MRI

which is probably fine, but still JRuby should not fail the MRI-way on `require 'digest/bubblebabble'` even if it does not actually load anything.

p.s. bonus points for back-porting #3238 to **jruby-1.7**

**Comment by kubum** [comment]
@kares is it a duplicate of #2955 or is there any difference?

**Comment by kares** [comment]
its the same, thanks! ... was just thinking of quick-adding a LOADED-FEATURE entry

**Comment by kubum** [comment]
@kares no worries! Are you still interested in a back-port to jruby-1_7 branch? :)

**Comment by kares** [comment]
@kubum we can always cherry-pick your commit - no worries there

**Comment by kares** [comment]
for the record its been backported including previous bubblebabble commits ... expect this in 1.7.22 as well
