### ISSUE TITLE
File.fnmatch doesn't match german vowels

### ISSUE THREAD

**Issue by sliminas** [jruby/jruby#3248]
I have an issue when Rails is resolving the view templates and the template paths contain the german vowels ä, ö or ü.
When using Ruby 2.2.2 the following will match and return true:
```ruby
File.fnmatch("#{Dir.pwd}/exämple.txt", "#{Dir.pwd}/exämple.txt")
```
But when using JRuby 9K this will actually return false.

**Comment by headius** [comment]
Looks like this is a signed versus unsigned problem.
