### ISSUE TITLE
jruby: warning: unknown property jruby.{memory,stack}.max

### ISSUE THREAD

**Issue by echristopherson** [jruby/jruby#3251]
Whenever I run JRuby or JIRB using 9.0.0.0, installed with RVM, on a 64-bit Ubuntu 14.04.2 Linux 3.16.0-43 system, I get four warning lines:

    jruby: warning: unknown property jruby.memory.max
    jruby: warning: unknown property jruby.stack.max
    jruby: warning: unknown property jruby.memory.max
    jruby: warning: unknown property jruby.stack.max

It looks like those properties are hardcoded (to 500m and 2048k, respectively) in jruby-launcher-1.0.15-java/argparser.cpp now.

**Comment by headius** [comment]
These properties are used to indicate what the command-line stack and heap max were set to, since we can't retrieve that information directly from standard Java APIs. I'll modify our list of options so that they don't cause a warning.
