### ISSUE TITLE
Encoding issue in jruby 9.0.0.0

### ISSUE THREAD

**Issue by deivid-rodriguez** [jruby/jruby#3267]
Hi!

My tests pass under MRI 2.2.3 but fail under jruby 9.0.0.0. This is the error I'm getting:

```
  1) Error:
AdminScenarioTest#test_scenarios_are_listed_in_the_index_page:
RegexpError: invalid multibyte character: /PerÃ­ode\ de\ retorn/
    test/support/admin.rb:34:in `assert_table_header'
    test/support/admin.rb:25:in `assert_table_col'
    test/admin/scenario_test.rb:22:in `test_scenarios_are_listed_in_the_index_page'
```

Adding magic utf-8 comments where the utf-8 string is defined does not help.

I'll try to post a proper reproduction if necessary, I just wanted to get feedback about it first in case this is a known issue.

Thanks!

**Comment by enebo** [comment]
@deivid-rodriguez Could you try adding env var: JRUBY_OPTS='-J-Dfile.encoding=UTF-8' and see if this goes away?  I am trying to fix this without requiring that but I am curious if this fixes the problem for you.

**Comment by deivid-rodriguez** [comment]
I forgot to mention that I tried that and didn't work either.

Thanks!

**Comment by enebo** [comment]
@deivid-rodriguez ok.  Yeah something which reduces this to a script we can run and see the issue will allow us to fix it the quickest.

**Comment by deivid-rodriguez** [comment]
Here you go!

```
bundle
RAILS_ENV=test bundle exec rake db:migrate
bundle exec rake
```

should do it.

**Comment by enebo** [comment]
This will work but I was hoping to have something which ran as a single file and did not require loading a big env.

**Comment by deivid-rodriguez** [comment]
This is a default Rails app plus `capybara` plus an `activeadmin` resource. "Big" is a relative word... :)

I can further isolate the problem, but it's unlikely that I get the time to do it before October.

Thanks for your work!

**Comment by enebo** [comment]
@deivid-rodriguez ok I will fix the other known encoding issues and circle back to this.   Having a reproduction is great in that we can at least know if it has been addressed.  Thanks for that.  I just get greedy and want it localized more :)

**Comment by deivid-rodriguez** [comment]
@enebo That sounds great, I will circle back here as well if I get the time to further localize the issue for you!

**Comment by headius** [comment]
I believe I've narrowed this down to:

```ruby
"".force_encoding('US-ASCII').match("Període\\ de\\ retorn".force_encoding('UTF-8'))
```

Investigating.

**Comment by headius** [comment]
I have a fix. We do not follow the correct path for constructing the regexp from the match string, and so the encoding does not get negotiated correctly.

**Comment by deivid-rodriguez** [comment]
Thanks!!
