### ISSUE TITLE
What is the minimum Java version supported for JRuby 9.0.0.0?

### ISSUE THREAD

**Issue by plusjeff** [jruby/jruby#3273]
I haven't been able to find this information form a cursory Google Search. Is there a place I can find this information?

**Comment by benlovell** [comment]
It's in the README:

>To run JRuby you will need a JRE (the JVM runtime environment) version 7 or higher.

I've also read @headius quoted as saying:

>With JRuby 9000, Java 7 is now the minimum Java version. "We use many Java 7 features, and so JRuby requires a Java 7 JVM and JDK [Java Development Kit] to run,"

**Comment by plusjeff** [comment]
@benlovell Thanks!

**Comment by svatada** [comment]
JRuby compatible with JAVA 11?

**Comment by enebo** [comment]
@svatada 9.2.x will run on Java 11 although you may see some module warnings depending on what you are doing.
