### ISSUE TITLE
non-intuitive overloaded varargs matching

### ISSUE THREAD

**Issue by kares** [jruby/jruby#3279]
assuming 2 methods `(Object... args)` and `(String a, Object... args)`

a `call('str')` won't match `(String a, Object... args)` but simply uses the generic one

**Comment by kares** [comment]
... not sure if it's a good idea to fix these on JRuby 1.7.x (assuming not due compatibility) ?

**Comment by headius** [comment]
I'd guess that `call('str'.to_java) invokes the right one, but I agree we could do a better job when we know we're turning an argument into a `java.lang.String` or other basic type.

**Comment by kares** [comment]
it's not an issue with type matching (`call('str'.to_java)` does not invoke the right one) but of a varargs processing as it's only considered a suitable match for arities where the var-arg parameter receives an arg...
