### ISSUE TITLE
Not getting SIGCHLD when a child process dies

### ISSUE THREAD

**Issue by jensnockert** [jruby/jruby#3283]
You do not get a signal when a child process dies, you should get SIGCHLD.

Example, the following code works on MRI (and is differently broken on pre-9k JRuby, where you do get SIGCHLD, but the processed is reaped by Java)

https://gist.github.com/jensnockert/05e03714f57ee04ec2da

**Comment by jensnockert** [comment]
Okay, running dtrace on this

```
dtrace -qn '
proc:::signal-discard
{
        printf("Process %d discarded signal %d\n",
        args[1]->pr_pid,args[2]);
}'
```

I get `Process 26312 discarded signal 20` so we're discarding the SIGCHLD.

**Comment by jensnockert** [comment]
@headius helped me find that if you add `java.lang.UNIXProcess` to the top of the script, it starts working. That class should probably be loaded early.

**Comment by headius** [comment]
Root problem was that `java.lang.UNIXProcess` initializes after the user's trap is installed, and it then proceeds to reset SIGCHLD handling to default. According to sigaction man page, default behavior for SIGCHLD is to discard, so we silently lose the trap and the signal.

I have a fix that forces java.lang.Process and java.lang.UNIXProcess to load before setting up the Signal module. That should guarantee the JVM's SIGCHLD handler has been installed and that it will be overwritten by the user's trap.
