### ISSUE TITLE
9K seems to be handling all jruby.xxx properties

### ISSUE THREAD

**Issue by kares** [jruby/jruby#3288]
they're used e.g. with gems such as jruby-openssl the jruby.openssl.xxx namespace is used : 
```
:~/workspace/oss/jruby$ jruby -J-Djruby.openssl.debug=true ...
jruby: warning: unknown property jruby.openssl.debug
jruby: warning: unknown property jruby.openssl.debug
```
... no longer works as it used to on JRuby 1.7

**Comment by enebo** [comment]
@kares perhaps we will just special case anything starting with jruby.openssl. ?

**Comment by kares** [comment]
how about letting unknown ones through, is that not possible?

**Comment by chrisseaton** [comment]
Here's the first weird thing - why is the warning being printed twice? It turns out that JRuby runs `processArguments`

```
	at org.jruby.RubyInstanceConfig.processArguments(RubyInstanceConfig.java:166)
	at org.jruby.Main.run(Main.java:224)
	at org.jruby.Main.main(Main.java:197)
```

```
	at org.jruby.RubyInstanceConfig.processArguments(RubyInstanceConfig.java:166)
	at org.jruby.Main.doProcessArguments(Main.java:468)
	at org.jruby.Main.internalRun(Main.java:257)
	at org.jruby.Main.run(Main.java:225)
	at org.jruby.Main.main(Main.java:197)
```

Is that the right behaviour?

**Comment by chrisseaton** [comment]
As for actually fixing this issue, I can do two things - we can remove this feature that warns you about an unknown property (and that's all it is by the way - a warning - we don't 'handle' it as in removing it or something like that). Or we could add a feature that says ignore properties in `jruby.openssl.*` and some other known patterns. Which do we want?

**Comment by kares** [comment]
aah, right - there's actually no debug lines to be printed in my script :) ... my bad thought this is more serious. at this point I do not care what the fix is - if its a useful feature for users than keep it and add jruby.openssl.* as a know pattern. maybe jruby-openssl is the only one using the jruby.xxx namespace.

**Comment by enebo** [comment]
@chrisseaton I think we keep going and just add jruby.openssl.* to the exclude list.  We could eventually go whole hog and let libraries register these properties but that seems a bit over the top.  Let's try something simple as a workaround.

**Comment by kares** [comment]
@chrisseaton thanks ... and maybe we need another bug for the processArguments going on twice?

**Comment by kares** [comment]
oh you already did it, just noticed
