### ISSUE TITLE
UTF-8 encoding on MS-Windows

### ISSUE THREAD

**Issue by carlosmrce** [jruby/jruby#3292]
Hi there,

I posted an issue a while back, but it seems to be back!!!

Original issue: https://github.com/jruby/jruby/issues/1198

Just tested on MS-Windows and Linux, and the bug still exists.

![bug](https://cloud.githubusercontent.com/assets/1188933/9521412/2e0b5908-4ca5-11e5-96a3-55e2ec4982f8.png)

Thanks!

**Comment by enebo** [comment]
My fix seems to have been removed on master (probably during native IO translation work).  @headius can you see if this can be re-shoehorned in.  I am guessing native path is not being called and non-native should have #1198 re-applied.

**Comment by headius** [comment]
Heh:

```java
    // io_fwrite
    public long fwrite(ThreadContext context, IRubyObject str, boolean nosync) {
        // TODO: Windows
//        #ifdef _WIN32
//        if (fptr->mode & FMODE_TTY) {
//            long len = rb_w32_write_console(str, fptr->fd);
//            if (len > 0) return len;
//        }
//        #endif
        str = doWriteconv(context, str);
        ByteList strByteList = ((RubyString)str).getByteList();
        return binwrite(context, str, strByteList.unsafeBytes(), strByteList.begin(), strByteList.length(), nosync);
    }
```

I will DO the TODO now :-)

**Comment by headius** [comment]
FWIW, most of the divergence between native and non-native is wrapped up inside PosixShim, which has native and non-native paths. That lives at the level of a C library "write" call, for example. The rest of the ported MRI code I tried to keep as close to MRI as possible and abstract those native/non paths elsewhere.

Fix coming. I don't have Windows handy to test, but perhaps we poke the nightly build and give @carlosmrce a build to confirm with, ok?

**Comment by headius** [comment]
If anyone has an idea of how to test this, I'd love to hear it :-\

**Comment by carlosmrce** [comment]
I will be more than happy to test this out @headius

**Comment by carlosmrce** [comment]
Worked perfectly @enebo @headius 

Thanks!

**Comment by headius** [comment]
Note for future: `System.console()` can return null when stdio is not connected to a console, causing this fix to blow up in subprocesses. I'm adding a null check that will act similar to the TTY check in the MRI code.

**Comment by enebo** [comment]
Note for a happier future: we should just go full native on this and hook into any neccesary transcoding.  I fixed this originally with System.console() because it was super easy and works mostly.  

A second note is that I think our sub-process spawning is done wrong in jnr-posix and if it was done properly System.console() would not be null.

The second note would make many more cases work and the former will work in cases where our default_internal is not a Java Charset.
