### ISSUE TITLE
strftime_spec.rb SPEC test fails in "returns the timezone with %Z"

### ISSUE THREAD

**Issue by tdaitx** [jruby/jruby#3303]
In certain cases `Time#zone` and `Time#strftime("%Z")` might not match, causing *"returns the timezone with %Z"* in `spec/ruby/core/time/strftime_spec.rb` to fail.

### How to reproduce
One of such cases happens when running *joda-time <= 2.8.0* and *OpenJDK 8u60* or earlier. 

Due to a change in *OpenJDK 8u60*, Java's `DateTimeUtils.getZoneStrings()` is now returning 7 elements instead of just 5, causing *joda-time* `DefaultNameFormatter.getName()` to return `null`. In effect causing *joda-time* `DateTimeZone.getShortName()` or `DateTimeZone.getName()` to return TZ in *[+-]hh:mm* format instead of the abbreviation name. The issue was reported in https://github.com/JodaOrg/joda-time/issues/288 and https://github.com/JodaOrg/joda-time/issues/291.

To reproduce simply run:
```
$ JAVA_HOME=<jdk8u60 home> ./bin/jruby spec/mspec/bin/mspec run spec/ruby/core/time/strftime_spec.rb
```
with *joda-time <= 2.8.0*.

### Current result:
Requires *OpenJDK 8u60* (or earlier) and *joda-time <= 2.8.0*.

`Time.strftime("%Z")` returns the TZ in*"[+-]hh:mm* format (as if *"%z"* was given), while `Time.zone` returns the TZ abbreviation name.

```
$ ./bin/jruby spec/mspec/bin/mspec run spec/ruby/core/time/strftime_spec.rb 
jruby 1.7.21 (1.9.3p551) 2015-09-01 fffffff on OpenJDK 64-Bit Server VM 1.8.0_66-internal-b01 +jit [linux-amd64]

1)
Time#strftime returns the timezone with %Z FAILED
Expected "-03:00"
 to equal "BRT"

/build/jruby-shb6eX/jruby-1.7.21/spec/ruby/core/time/strftime_spec.rb:238:in `(root)'
org/jruby/RubyBasicObject.java:1574:in `instance_eval'
org/jruby/RubyEnumerable.java:1412:in `all?'
org/jruby/RubyFixnum.java:275:in `times'
org/jruby/RubyArray.java:1613:in `each'
/build/jruby-shb6eX/jruby-1.7.21/spec/ruby/core/time/strftime_spec.rb:4:in `(root)'
org/jruby/RubyKernel.java:1059:in `load'
org/jruby/RubyBasicObject.java:1574:in `instance_eval'
org/jruby/RubyArray.java:1613:in `each'
```

### Expected result:
The spec states that `Time#zone` and `Time#strftime("%Z")` should always match. Also, [Time.strftime documentation](http://apidock.com/ruby/v1_9_3_392/Time/strftime) states that *%Z - Time zone abbreviation name*.

### Background, why Time#zone and Time#strftime differs
JRuby's `Time#zone` has additional code to be able to handle a *[+-]hh:mm* return by `DateTimeZone.getShortName()` when compared to `Time#strftime("%Z")`.

RubyTime.zone() [890-908]
```Java
        String zone = dt.getZone().getShortName(dt.getMillis());

        Matcher offsetMatcher = TIME_OFFSET_PATTERN.matcher(zone);

        if (offsetMatcher.matches()) {
            boolean minus_p = offsetMatcher.group(1).toString().equals("-");
            int hourOffset  = Integer.valueOf(offsetMatcher.group(2));

            if (zone.equals("+00:00")) {
                zone = "GMT";
            } else {
                // try non-localized time zone name
                zone = dt.getZone().getNameKey(dt.getMillis());
                if (zone == null) {
                    char sign = minus_p ? '+' : '-';
                    zone = "GMT" + sign + hourOffset;
                }
            }
        }
```

RubyDateFormatter.format() [489-491] and
RubyDateFormat.format() [622-624]
```Java
                case FORMAT_ZONE_ID:
                    output = dt.getZone().getShortName(dt.getMillis());
                    break;
```

Some code from `RubyTime.zone()` *offsetMatcher* should be refactored (or copied) into `RubyDateFormatter.format()` and `RubyDateFormat.format()` *FORMAT_ZONE_ID* clauses.

**Comment by headius** [comment]
Fixed in 1.7.22 and 9.0.1.0.
