### ISSUE TITLE
zone_spec.rb fails SPEC test "Time#zone returns UTC when called on a UTC time"

### ISSUE THREAD

**Issue by tdaitx** [jruby/jruby#3304]
As described in #3303 the combination of *joda-time <= 2.8.0* and *OpenJDK 8u60* or earlier causes *joda-time* to return a *[+-]hh:mm* TZ format when calling `DateTimeZone.getShortName()` or `DateTimeZone.getName()`. This in turn causes `RubyTime.zone()` to return GMT instead of UTC by following a different code path then usual. 

### Current result
```
jruby-1.7.21$ ./bin/jruby spec/mspec/bin/mspec run spec/ruby/core/time/zone_spec.rbjruby 1.7.21 (1.9.3p551) 2015-09-01 fffffff on OpenJDK 64-Bit Server VM 1.8.0_66-internal-b01 +jit [linux-amd64]
..F

1)
Time#zone returns UTC when called on a UTC time FAILED
Expected "GMT"
 to equal "UTC"

/build/jruby-shb6eX/jruby-1.7.21/spec/ruby/core/time/zone_spec.rb:19:in `(root)'
org/jruby/RubyBasicObject.java:1574:in `instance_eval'
org/jruby/RubyEnumerable.java:1412:in `all?'
org/jruby/RubyFixnum.java:275:in `times'
org/jruby/RubyArray.java:1613:in `each'
/build/jruby-shb6eX/jruby-1.7.21/spec/ruby/core/time/zone_spec.rb:4:in `(root)'
org/jruby/RubyKernel.java:1059:in `load'
org/jruby/RubyBasicObject.java:1574:in `instance_eval'
org/jruby/RubyArray.java:1613:in `each'

Finished in 0.061000 seconds
```

### Expected result
As per [Time#zone documentation](http://apidock.com/ruby/v1_9_3_392/Time/zone) it should return *UTC*.

### Offending code
I believe that the `if (zone.equals("+00:00")` bellow should return *UTC* instead of *GMT*.

RubyTime.zone() [890-908]
```Java
        String zone = dt.getZone().getShortName(dt.getMillis());

        Matcher offsetMatcher = TIME_OFFSET_PATTERN.matcher(zone);

        if (offsetMatcher.matches()) {
            boolean minus_p = offsetMatcher.group(1).toString().equals("-");
            int hourOffset  = Integer.valueOf(offsetMatcher.group(2));

            if (zone.equals("+00:00")) {
                zone = "GMT";
            } else {
                // try non-localized time zone name
                zone = dt.getZone().getNameKey(dt.getMillis());
                if (zone == null) {
                    char sign = minus_p ? '+' : '-';
                    zone = "GMT" + sign + hourOffset;
                }
            }
        }
```

**Comment by headius** [comment]
joda was updated for JRuby 1.7.22, released last week, and 9.0.1.0 released yesterday. Are you seeing these issues with the latest releases?

**Comment by headius** [comment]
Neither 1.7.22 nor 9.0.1.0 appear to fail the spec in question here, so I will be marking this fixed in those releases. Let me know if you're still seeing an issue.

**Comment by tdaitx** [comment]
@headius you are right that running it against joda-time 1.8.1 or earlier will prevent the issues, but I wouldn't call that *fixing* them. The underlying problem is still there, if joda-time *getShortName* presents yet another problem in the future, then the issues will show up again.

IMHO JRuby itself should be more resilient and behave as closely as expected by the spec.

The following patch would fix it.
```
--- a/core/src/main/java/org/jruby/RubyTime.java 2015-09-04 09:45:25.733338886 -0300
+++ b/core/src/main/java/org/jruby/RubyTime.java 2015-09-04 09:45:16.441344417 -0300
@@ -896,7 +896,7 @@
             int hourOffset  = Integer.valueOf(offsetMatcher.group(2));
 
             if (zone.equals("+00:00")) {
-                zone = "GMT";
+                zone = "UTC";
             } else {
                 // try non-localized time zone name
                 zone = dt.getZone().getNameKey(dt.getMillis());
```

Let me know if that is a reasonable fix. I can also create a pull request for it.

**Comment by mkristian** [comment]
@tdaitx both jruby-1.7.22 and jruby-9.0.0.0 default to joda-2.8.2: https://github.com/jruby/jruby/blob/9.0.1.0/pom.rb#L80

I do not understand your remark.

if your patch brings JRuby closer to MRI and passes all specs then go for PR. @headius  ???

**Comment by tdaitx** [comment]
@mkristian I meant that the tests work fine when joda-time behaves as expected, otherwise JRuby will fail the tests, IMHO it shouldn't depend so much on joda-time.

I have created https://github.com/jruby/jruby/pull/3310 to fix this. =)

Thanks!
