### ISSUE TITLE
RubyTCPSocket:87- TypeError: can't convert nil into String

### ISSUE THREAD

**Issue by ebbflowgo** [jruby/jruby#3314]
TypeError: can't convert nil into String
   initialize at org/jruby/ext/socket/RubyTCPSocket.java:87
          new at org/jruby/RubyIO.java:851
       stream at /Users/obedear/.rvm/gems/jruby-1.7.19/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16
      request at /Users/obedear/.rvm/gems/jruby-1.7.19/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:119
       sample at /Users/obedear/.rvm/gems/jruby-1.7.19/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:58
       (root) at text.rb:22

https://gist.github.com/ebbflowgo/f7eab9f24214b64b0059

**Comment by headius** [comment]
Hi there...did you find this is fixed in newer JRuby or was closing it a mistake?

**Comment by ebbflowgo** [comment]
Hi, I moved it to https://github.com/sferik/twitter/issues/726 because it only breaks on twitter 5.15.0 and works fine on twitter 5.14.0
