### ISSUE TITLE
GBK Symbol Error (jruby 9.0.1.0)

### ISSUE THREAD

**Issue by personnel** [jruby/jruby#3347]
GBK encoding source file with GBK symbol like 

``` ruby
#encoding : GBK

puts :测试
```

reports error "Invalid char...", but

``` ruby
#encoding : GBK

puts :'测试'
```

is ok.
However,same file run in MRI is ok.

**Comment by headius** [comment]
This appears to be working mostly ok now. My console does not appear to render the puts output correctly but there's no error.

**Comment by personnel** [comment]
great! It's works now!
But still has bug for exsample:
```
# encoding : GBK
# frozen_string_literal: true

class CTT
	def 测试
		puts "#{__callee__} : first"
	end
	define_method(:测试){
		puts "#{__callee__} : second"
	}
end

obj = CTT.new
obj.测试
obj.send :测试
```
output:
```
?? : first
测试 : second
```
MRI output:
```
测试 : second
测试 : second
```

**Comment by headius** [comment]
@personnel This is the other half of encoding work that @enebo  is working on: making all identifiers use proper encoding too. In this case, it will need to get translated into the JIT naming of the compiled method as well as being properly represented in the method table.

Can you open a new bug for that, please?
