### ISSUE TITLE
IO.popen(cmd, "w+") generates a non-writable pipe in JRuby 9.0.1.0

### ISSUE THREAD

**Issue by thjek** [jruby/jruby#3369]
The following code works in JRuby 1.7.22:

```
cmd = "C:/Lang/R/x64/bin/xterm.exe --ess --slave"
engine = IO.popen(cmd, "w+")
engine.write("x <- 20")
```

The same code generates the following error message in JRuby 9.0.1.0:

```
IOError: not opened for writing
  write at org/jruby/RubyIO.java:1437
  write at org/jruby/RubyIO.java:1411
```

My underlying platform is JDK 8 (x64), update 60 on Windows 10.

```
jruby 9.0.1.0 (2.2.2) 2015-09-02 583f336 Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [Windows 10-amd64]
```

**Comment by headius** [comment]
This is a known issue with subprocess IO on Windows and still remains an issue. However we have #4964 and others that document this issue. Since this is almost four years old and duplicated by others, I'm going to close it.
