### ISSUE TITLE
FileUtils#remove_tailing_slash is a poor method name

### ISSUE THREAD

**Issue by rthbound** [jruby/jruby#3372]
From https://bugs.ruby-lang.org/issues/11548 -

> One would expect this method to be called **remove_trailing_slash**

> I asked around on IRC and the consensus is this is probably an unfortunate typo that's survived too long.

> Tailing and Trailing mean similar things, but I think most would expect "trailing" to be the clear choice here.

> http://ruby-doc.org/stdlib-2.2.3/libdoc/fileutils/rdoc/FileUtils.html#method-i-remove_tailing_slash

This may be changing in ruby, I'm thinking JRuby will want to make the change as well.

**Comment by headius** [comment]
Hah, I never noticed this one. Nobu points out it's a private method and can be changed right now, so I'll have a look at your PR.

**Comment by headius** [comment]
So your PR is ok. The excludes are strange, because they only exist in the Truffle excludes and I can find no such test in MRI's suite.

I will merge this.
