### ISSUE TITLE
OpenSSL::Cipher missing auth_data=

### ISSUE THREAD

**Issue by trashhalo** [jruby/jruby#3376]
Ruby 2.2 defines a method on Cipher with the signature auth_data=
http://ruby-doc.org/stdlib-2.2.2/libdoc/openssl/rdoc/OpenSSL/Cipher.html#method-i-auth_data-3D

jruby is bombing on our test suite with (9.0.1.0)
`NoMethodError: undefined method `auth_data=' for #<OpenSSL::Cipher:0x1ed38b74>`

Looks like this method was added in ruby 2 and is missing in 1.9

http://ruby-doc.org/stdlib-1.9.3/libdoc/openssl/rdoc/OpenSSL/Cipher.html
vs
http://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html

**Comment by saghaulor** [comment]
+1 bump

I'm trying to add support to AEAD to https://github.com/attr-encrypted/encryptor/pull/18 and the JRuby build is failing because of the lack of `auth_data=` support.

I'd like to maintain JRuby support but I may have to remove it until this feature is supported.

**Comment by nahi** [comment]
Yeah I once tried to fix jruby-openssl but so far I don't have enough time to do that. FYI w/r/t AES-GCM on JRuby you can do that like this: https://github.com/nahi/ruby-crypt/blob/master/odrk05/kms_encryptor.rb

**Comment by saghaulor** [comment]
@nahi Thanks for the suggestion. From my understanding of the code that you provided, authentication data is not supported, only authenticated encryption. However, based on https://tools.ietf.org/html/rfc5084#section-1.5, AES-GCM accepts authentication data as optional input. As such your suggestion would work, though wouldn't be ideal. 

It seems though that JRuby 1.7 doesn't support AES-GCM.

**Comment by kares** [comment]
has been added at some point in jruby-openssl 0.9.1x releases. pls report at [JRuby-OpenSSL](http://github.com/jruby/jruby-openssl/issues) if otherwise.
