### ISSUE TITLE
#to_ary behavior does not conform to MRI Ruby (1.7.22)

### ISSUE THREAD

**Issue by asthasr** [jruby/jruby#3378]
In MRI Ruby, when you iterate over an object providing a block with extra parameters, it seems that #to_ary is called and, if it returns nil, is disregarded. This is a test that you can execute to see the behavior on different Rubies:

```ruby
class Example
  def to_ary
    nil
  end
end

test = [Example.new].map { |x, _| x }

puts test == [nil] ? "fail" : "pass"
```

On MRI versions, this passes. On JRuby 1.7.22, it returns [nil] and thus fails. On JRuby 9.0.1.0, it raises an exception: TypeError: Example#to_ary should return Array. It seems that the behavior in this case should conform to the behavior on MRI, in order to avoid surprising behavior when attempting to use map, each and other enumerable methods.

In real projects, this is observable on any ActiveRecord object as well as DelayedJob, as seen in Issue https://github.com/jruby/jruby/issues/3338.

**Note** -- I am opening this bug for 1.7.22 per a request from @enebo .

**Comment by enebo** [comment]
commit noted for this in #3338.
