### ISSUE TITLE
Poor argument handling in jruby.bash start script for the JRuby interpreter

### ISSUE THREAD

**Issue by nelsnelson** [jruby/jruby#3384]
This sort of error should be handled more gracefully, I think.

```{bash}
$ jruby -version
jruby 9.0.1.0 (2.2.2) 2015-09-02 583f336 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]
NameError: undefined local variable or method `rsion' for main:Object
  <top> at -e:1
```

**Comment by nirvdrum** [comment]
That's a tricky one. We do what MRI does:

```
> ruby -version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
-e:1:in `<main>': undefined local variable or method `rsion' for main:Object (NameError)
```

**Comment by nirvdrum** [comment]
To be clear, what's happening is the `-v` flag is recognized, followed by the `-e` flag, followed by the argument to the `-e` flag, which in this case is "rsion".  "rsion" is evaluated as an inline script and you end up getting the error about the undefined local variable.

**Comment by nelsnelson** [comment]
:+1 @nirvdrum

**Comment by nelsnelson** [comment]
Ah, I see.  Well, if MRI does it then, nevermind.

**Comment by nirvdrum** [comment]
FWIW, I do agree it could be more friendly. It'd probably be best to take it up with the MRI tracker and see if gets accepted there.

**Comment by enebo** [comment]
```ruby
module Kernel
  def rsion
     org.jruby.util.cli.OutputStrings.get_version_string
  end
end
```

**Comment by enebo** [comment]
(This was a joke)
