### ISSUE TITLE
NullPointerException  in getCompatVersionParameter(JRubyApplet.java:140)

### ISSUE THREAD

**Issue by BeGe78** [jruby/jruby#340]
Hello,
I am trying to start a simple applet with Jruby 1.7.0 RC1 and get an error with getCompatVersion.
I could not find a solution on the web so it could well be an issue with this RC1 version.
My environment: Linux Fedora 17 and 
# jruby -v
Picked up _JAVA_OPTIONS: -Xms512m -Xmx1024m -XX:PermSize=64m -XX:MaxPermSize=128m -Dawt.useSystemAAFontSettings=lcd
jruby 1.7.0.RC1 (1.9.3p203) 2012-09-25 8e849de on OpenJDK Server VM 1.7.0_06-icedtea-mockbuild_2012_08_31_14_28-b00 [linux-i386]
My HTML page helloworldapplet.html
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>Hello World</title>
</head>

<body>
<div id="container">  
  <div id="the_applet">
<APPLET code="org.jruby.JRubyApplet.class" codebase="./lib/" archive="jruby-complete-1.7.0.RC1.jar"  width=400 height=400>
<param name="jruby.objectspace" value="true" /> 
<param name="compat" value="1.9" />    
<param name="jruby.eval" value="ARGV[0] = 'helloworldApplet.rb'" />
</APPLET>

</div>  
</div>
</body>
</html>
I have added the <param name="compat" value="1.9" />  because reading the code of JRubyApplet.java, i thought it could be the problem. Anyway removing it gives the same problem.

I launch the applet with
# appletviewer -J-Djava.security.policy=securitypolicy.txt helloworldapplet.html
And got the following error
Picked up _JAVA_OPTIONS: -Xms512m -Xmx1024m -XX:PermSize=64m -XX:MaxPermSize=128m -Dawt.useSystemAAFontSettings=lcd
java.lang.NullPointerException
        at org.jruby.JRubyApplet.getCompatVersionParameter(JRubyApplet.java:140)
        at org.jruby.JRubyApplet.access$800(JRubyApplet.java:88)
        at org.jruby.JRubyApplet$1.<init>(JRubyApplet.java:227)
        at org.jruby.JRubyApplet.init(JRubyApplet.java:222)
        at sun.applet.AppletPanel.run(AppletPanel.java:435)
        at java.lang.Thread.run(Thread.java:722)
The security policy file has been added due to some problem with JRuby 1.6.8.
This error does not appear if i use the jruby-complete-1.6.8.jar.

Just in case (but i don't think it is problem), here is my simple applet helloworldApplet.rb that i am trying to launch

require "java"
include_class "java.applet.Applet"
include_class 'com.sun.j3d.utils.applet.MainFrame'
java_import java.awt.Button
class Ruby3d
def initialize
  super
  $b=Button.new("Hello Button")
  JRUBY_APPLET.setSize(500, 500)
  JRUBY_APPLET.add($b)
end
def main
  MainFrame.new(JRUBY_APPLET, 600, 600)
end
end
Ruby3d.new.main

**Comment by headius** [comment]
Fixed in 1.7. JRubyApplet no longer exists in 9k.
