### ISSUE TITLE
[Truffle] Methods like File.readable? don't work on stdlib files in a JAR

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#3400]
IRB does this to load locale information, for example. Means we always need to keep the stdlib in the FS rather than in a JAR.

**Comment by eregon** [comment]
I think JRuby might solve this by making `File.readable?` JAR-aware.
But some stuff really needs the files like file locks.

**Comment by chrisseaton** [comment]
I think we could probably implement as a special-case what we need for stdlib, but not in general support the contents of JAR files for all file operations.

**Comment by chrisseaton** [comment]
Closing as won't-fix. We have no immediate plans to support reading files from JAR files. When it becomes clear it's important for existing JRuby applications that we're trying to run, we can reconsider.
