### ISSUE TITLE
Hash has bug to set encoding into key string wrongly when the key string is used once with different encoding

### ISSUE THREAD

**Issue by tagomoris** [jruby/jruby#3405]
On JRuby 9.0.1.0, Hash sets wrong encoding only when the key string is used as Hash key with different encoding.

```ruby
hash1 = {}
hash1['str'.force_encoding('ASCII-8BIT')] = 1
p hash1.keys.first.encoding # ASCII-8BIT

hash2 = {}
hash2['str'.force_encoding('UTF-8')] = 1
p hash2.keys.first.encoding # ASCII-8BIT !? (expected: UTF-8)
```

Script to show situations to reproduce bugs:
```ruby
# encoding: ascii-8bit

str = 'hello'
obj1 = {'hello' => 1}
obj2 = {str => 2}
p({str: str, enc: str.encoding, k1enc: obj1.keys.first.encoding, k2enc: obj2.keys.first.encoding})

str = 'hello'.force_encoding('UTF-8')
obj1 = {'hello'.force_encoding('UTF-8') => 1}
obj2 = {str => 2}
p({str: str, enc: str.encoding, k1enc: obj1.keys.first.encoding, k2enc: obj2.keys.first.encoding})

str = 'hello'.force_encoding('UTF-8')
obj1 = {}
obj1[str] = 1
obj2 = {}
obj2[str] = 2
p({str: str, enc: str.encoding, k1enc: obj1.keys.first.encoding, k2enc: obj2.keys.first.encoding})

str = 'world'.force_encoding('UTF-8')
obj1 = {'world'.force_encoding('UTF-8') => 1}
obj2 = {str => 2}
p({str: str, enc: str.encoding, k1enc: obj1.keys.first.encoding, k2enc: obj2.keys.first.encoding})

str = 'unused'
obj1 = {'unused'.force_encoding('UTF-8') => 1}
obj2 = {str.force_encoding('UTF-8') => 2}
p({str: str, enc: str.encoding, k1enc: obj1.keys.first.encoding, k2enc: obj2.keys.first.encoding})
```

Expected result is:
* First line: all keys are encoded in ASCII-8BIT
* Rest: all keys are encoded in UTF-8

Actual result in JRuby 9.0.1.0 is:
* First line: all keys are encoded in ASCII-8BIT
* All `hello` as hash keys are encoded in ASCII-8BIT

**Comment by tagomoris** [comment]
JRuby 1.7.x and MRI works as expected, and only JRuby 9.0.1.0 works in wrong way.

All outputs from script above in JRuby 9.0.1.0, JRuby 1.7.22 and MRI 2.2.2:
```
# $ ruby -v ; ruby ~/encoding_test.rb
# jruby 9.0.1.0 (2.2.2) 2015-09-02 583f336 Java HotSpot(TM) 64-Bit Server VM 25.31-b07 on 1.8.0_31-b13 +jit [darwin-x86_64]
# {:str=>"hello", :enc=>#<Encoding:ASCII-8BIT>, :k1enc=>#<Encoding:ASCII-8BIT>, :k2enc=>#<Encoding:ASCII-8BIT>}
# {:str=>"hello", :enc=>#<Encoding:UTF-8>, :k1enc=>#<Encoding:ASCII-8BIT>, :k2enc=>#<Encoding:ASCII-8BIT>}
# {:str=>"world", :enc=>#<Encoding:UTF-8>, :k1enc=>#<Encoding:UTF-8>, :k2enc=>#<Encoding:UTF-8>}
# {:str=>"unused", :enc=>#<Encoding:UTF-8>, :k1enc=>#<Encoding:UTF-8>, :k2enc=>#<Encoding:UTF-8>}

# $ ruby -v ; ruby ~/encoding_test.rb
# jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_31-b13 +jit [darwin-x86_64]
# {:str=>"hello", :enc=>#<Encoding:ASCII-8BIT>, :k1enc=>#<Encoding:ASCII-8BIT>, :k2enc=>#<Encoding:ASCII-8BIT>}
# {:str=>"hello", :enc=>#<Encoding:UTF-8>, :k1enc=>#<Encoding:UTF-8>, :k2enc=>#<Encoding:UTF-8>}
# {:str=>"world", :enc=>#<Encoding:UTF-8>, :k1enc=>#<Encoding:UTF-8>, :k2enc=>#<Encoding:UTF-8>}
# {:str=>"unused", :enc=>#<Encoding:UTF-8>, :k1enc=>#<Encoding:UTF-8>, :k2enc=>#<Encoding:UTF-8>}

# $ ruby -v ; ruby ~/encoding_test.rb
# ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
# {:str=>"hello", :enc=>#<Encoding:ASCII-8BIT>, :k1enc=>#<Encoding:ASCII-8BIT>, :k2enc=>#<Encoding:ASCII-8BIT>}
# {:str=>"hello", :enc=>#<Encoding:UTF-8>, :k1enc=>#<Encoding:UTF-8>, :k2enc=>#<Encoding:UTF-8>}
# {:str=>"world", :enc=>#<Encoding:UTF-8>, :k1enc=>#<Encoding:UTF-8>, :k2enc=>#<Encoding:UTF-8>}
# {:str=>"unused", :enc=>#<Encoding:UTF-8>, :k1enc=>#<Encoding:UTF-8>, :k2enc=>#<Encoding:UTF-8>}
```

**Comment by headius** [comment]
Huh, wacky.

**Comment by headius** [comment]
Ok, I think this is due to our Hash logic using the new "string".freeze optimization for String keys. They are getting deduplicated, but improperly not considering encoding in the dedup store.

Options:

* Don't dedup keys except for literal hashes with literal string keys.
* Fix dedup to consider encoding as well.

**Comment by headius** [comment]
I will fix this today.

**Comment by headius** [comment]
I have chosen the second option for now. The proper way for us to dedup hash keys is to only do it for literal hashes with literal string keys, but that will require a bit more work in IR compilation. The short term fix of only using the cached string if the encoding matches will work for now (and may be necessary anyway).

**Comment by headius** [comment]
I'm not sure the best way to spec this out, since it depends on literal strings in hashes having specific encodings; this is not easy to spec in a single file. I've filed ruby/rubyspec#162 to discuss that, and we'll proceed for now without a spec or test to go with my fix.

**Comment by headius** [comment]
I've committed a fix for the dedup cache to consider encoding. It's a trivial change, preventing new strings with the same contents but different encodings from updating the cache or picking up a wrong-encoding string.

I'll file a separate issue to fix dedup behavior wrt Hash keys, and we'll work on specs separately in ruby/rubyspec#162.
