### ISSUE TITLE
[Truffle] timezone related bugs manifesting in activesupport tests

### ISSUE THREAD

**Issue by pitr-ch** [jruby/jruby#3414]
please see https://gist.github.com/pitr-ch/1dc387164294bb23459b#file-test-log-L221-L290 and others

**Comment by bjfish** [comment]
`TimeWithZoneTest#test_change` is fixed at 2951c362ff83af4621c6317407064e2220da8e4e

An example rollover is `ruby -e 'puts Time.local(2000,2,31)'` which results in `2000-03-02 00:00:00 -0600`
