### ISSUE TITLE
[Truffle] add support for Zlib::GzipWriter to let activesupport tests pass

### ISSUE THREAD

**Issue by pitr-ch** [jruby/jruby#3415]
please see https://gist.github.com/pitr-ch/1dc387164294bb23459b#file-test-log-L37-L55

**Comment by chrisseaton** [comment]
I've started to stub this out in fd2c1799783c7cb7123281e1f5d213dba47b9e05.

**Comment by pitr-ch** [comment]
yeah, I see the `not supported` error in the AS tests 3 times.
