### ISSUE TITLE
[Truffle] fix MultibyteCharsUTF8Behaviour related bugs to let activesupport pass

### ISSUE THREAD

**Issue by pitr-ch** [jruby/jruby#3416]
please see https://gist.github.com/pitr-ch/1dc387164294bb23459b#file-test-log-L58-L147

**Comment by chrisseaton** [comment]
I think the underlying problem here is that we seem to be leaking a Java `String` into the Ruby data flow graph.

**Comment by nirvdrum** [comment]
I fixed the Java `String` leak. It was a bad refactoring on the `Kernel#method` work I was doing. I think the remaining multibyte char tests are failing due to a difference in `Marshal.load`.

**Comment by pitr-ch** [comment]
@nirvdrum Could you look at the remaining issues? (3 errors)

**Comment by pitr-ch** [comment]
tracked in #3543
