### ISSUE TITLE
bundler `ruby` specification fails if not set to 2.2.2

### ISSUE THREAD

**Issue by jtarchie** [jruby/jruby#3427]
With the following JRuby,

```
$ jruby --version
jruby 9.0.3.0 (2.2.2) 2015-10-21 633c9aa Java HotSpot(TM) 64-Bit Server VM 25.25-b02 on 1.8.0_25-b17 +jit [darwin-x86_64]`
```

And the following Gemfile,

```
source 'https://rubygems.org'

ruby '2.2.3', :engine => 'jruby', :engine_version => '9.0.3.0'
```

And you run `bundle install`,
You see this error message,

```
Your Ruby version is 2.2.2, but your Gemfile specified 2.2.3
```

JRuby claims to be 2.2.x compatible. Should [this be updated](https://github.com/jruby/jruby/blob/master/core/pom.xml#L20) so it is explicit?

**Comment by donv** [comment]
This is the same behaviour as with MRI.

You should file an issue with bundler if you (like me) want it changed:  

    https://github.com/bundler/bundler/issues/2213

JRuby will probably update the line you mentioned, but then then your example with fail for all Gemfiles specifying `ruby '2.2.2'`.

**Comment by jtarchie** [comment]
@donv, I think we are on the same page with [bundler](https://github.com/bundler/bundler/pull/4064).

My point for this issue was that it wasn't clear in any docs that JRuby was locked at 2.2.2. The [blog post](http://jruby.org/2015/10/21/jruby-9-0-3-0.html) specifically says 2.2.x, so we assumed it would be the latest MRI version.

**Comment by jtarchie** [comment]
@donv: We've added a bit of coverage to [bundler](https://github.com/bundler/bundler/pull/4064) to support version operators. Would love to have a second pair of eyes review it.

**Comment by donv** [comment]
@jtarchie Will take a look.

**Comment by donv** [comment]
@jtarchie Looks good to me.  :+1:
