### ISSUE TITLE
[Truffle] implement SHA2

### ISSUE THREAD

**Issue by pitr-ch** [jruby/jruby#3439]
see https://gist.github.com/pitr-ch/1dc387164294bb23459b#file-test-log-L635-L642

**Comment by chrisseaton** [comment]
I think this is fixed in f62de7e6e5f9e1ee2806fd7cd249d9532c4f7b32, but I can't even see where ActiveSupport loads `digest/sha2` so not sure. Can you check and close or let me know any new error.

**Comment by pitr-ch** [comment]
Thanks, I do not see any more sha2 errors.
