### ISSUE TITLE
Testingjrubyinvokedynamic page is outdated?

### ISSUE THREAD

**Issue by thehappycoder** [jruby/jruby#3440]
https://github.com/jruby/jruby/wiki/Testingjrubyinvokedynamic

$ git checkout tags/9.0.3.0

$ ant clean jar
Buildfile: build.xml does not exist!
Build failed

**Comment by kares** [comment]
https://github.com/jruby/jruby/wiki/Testingjrubyinvokedynamic updated, thanks.
