### ISSUE TITLE
Random "string modified" RunTime error

### ISSUE THREAD

**Issue by bpardee** [jruby/jruby#3445]
In attempting to upgrade to JRuby 9030 from 1.7.19, we had to rollback because we would occasionally get the following Exception:

RuntimeError string modified app/models/stability_model.rb:122 block in product_after_new
```
119	def product_after_new
120	  super
121	  self.class.has_one_list.each do |child|
122	    self.send("#{child}=", child.to_s.classify.constantize.new(parent: self))
123	  end
124	end
```
Here is the stacktrace:
```
Exception: RuntimeError: string modified
org/jruby/RubyString.java:2230:in `sub!'
org/jruby/RubyString.java:2209:in `sub'
/var/www/rails/connect/components/transaction/vendor/bundle/jruby/2.2.0/gems/activesupport-4.1.13/lib/active_support/inflector/methods.rb:71:in `camelize'
/var/www/rails/connect/components/transaction/vendor/bundle/jruby/2.2.0/gems/activesupport-4.1.13/lib/active_support/inflector/methods.rb:160:in `classify'
/var/www/rails/connect/components/transaction/vendor/bundle/jruby/2.2.0/gems/activesupport-4.1.13/lib/active_support/core_ext/string/inflections.rb:186:in `classify'
/var/www/rails/connect/components/transaction/app/models/stability_model.rb:122:in `block in product_after_new’
```
I suspect we can fix it by changing the line as follows but I thought I would let you know about it.
```
self.send("build_#{child}", parent: self)
```

**Comment by reidmorrison** [comment]
Based on analyzing our log files, it appears that this problem only occurs shortly after startup and when the system is under heavy load across 10 threads.

I.e. It appears to be that the regular expression is being optimized on one thread, when another thread is running the same code it is getting the "string modified" error.

Once this problem has occurred in a process it does not appear to occur in the same place. We were only able to run for about 30 minutes under extreme load before backing out. This load was generated on our batch processing servers using the [rocketjob.io](http://rocketjob.io) batch  / background job processing system.

I am on the jruby gitter if you have any questions.

**Comment by bpardee** [comment]
Here is another exception we are getting that we think is probably releated:
```
DataCleansing.register_cleaner(:clarity_string) do |string, params|
  if string.is_a?(String)
    # Strip leading and trailing whitespace
    string.strip!

    # Convert to uppercase
    string.upcase! if params.fetch(:upper_case, false)

    # Remove all non-word characters
    if params.fetch(:remove_all_non_word_chars, false)
      string.gsub!(/\W/, '')
    elsif params.fetch(:remove_all_non_printing_chars, true)
      # Remove all non-printing characters
      string = string.scan(/[[:print:]]/).join   # <===== THIS LINE (123) IS CAUSING THE EXCEPTION
    end
```
```
Exception: Java::JavaLang::ClassCastException: org.jruby.RubyNil cannot be cast to org.jruby.RubyMatchData
org.jruby.RubyString.scanOnce(RubyString.java:3671)
org.jruby.RubyString.scan19(RubyString.java:3638)
org.jruby.RubyString$INVOKER$i$1$0$scan19.call(RubyString$INVOKER$i$1$0$scan19.gen)
org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:380)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
var.www.rails.connect.components.common.config.initializers.data_cleansing.invokeOther31:scan(/var/www/rails/connect/components/common/config/initializers/data_cleansing.rb)
var.www.rails.connect.components.common.config.initializers.data_cleansing.RUBY$block$\=\|var\|www\|rails\|connect\|components\|common\|config\|initializers\|data_cleansing\,rb$0(/var/www/rails/connect/components/common/config/initializers/data_cleansing.rb:123)
```

**Comment by reidmorrison** [comment]
We are able to reproduce the second exception in our test environment.

Running JRuby:
```
jruby 9.0.3.0 (2.2.2) 2015-10-21 633c9aa Java HotSpot(TM) 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [linux-amd64]
```

Java:
```
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

Java Options:
```
export JAVA_OPTS="-server -Xms8192m -Xmx8192m -Xss2048k -XX:G1HeapRegionSize=8m
-XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=1000
-XX:+UseCodeCacheFlushing -Dfile.encoding=UTF-8
-Dcompile.invokedynamic=true"
```

Turning off `invokedynamic` did not help either.

Also tried the following options as a shot in the dark:
```
export JAVA_OPTS="-server -Xms8192m -Xmx8192m -Xss2048k -XX:G1HeapRegionSize=8m
-XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=1000 
-XX:+UseCodeCacheFlushing -Dfile.encoding=UTF-8 
-Dcompile.invokedynamic=false -Dcompile.mode=FORCE -Dglobal.require.lock=true"
```

**Comment by kares** [comment]
could you verify whether it would happen when the String is not modified in place e.g. : 
```ruby
    # Strip leading and trailing whitespace
    string = string.strip

    # Convert to uppercase
    string = string.upcase if params.fetch(:upper_case, false)

    # Remove all non-word characters
    if params.fetch(:remove_all_non_word_chars, false)
      string.gsub!(/\W/, '')
    elsif params.fetch(:remove_all_non_printing_chars, true)
      # Remove all non-printing characters
      string = string.scan(/[[:print:]]/).join   # <===== THIS LINE (123) IS CAUSING THE EXCEPTION
    end
```
... or add a `rescue Exception` around :123 to log the String instance it is happening on (as it shouldn't be hard to reproduce locally then). 

**p.s.** also you seem to be missing the `jruby` prefix to the system properties for JRuby e.g. its : `-Djruby.compile.invokedynamic=false`

**Comment by reidmorrison** [comment]
@kares Thank you that did the trick, we are now moving ahead with the code below:

```ruby
  if string.is_a?(String)
    # Strip leading and trailing whitespace
    string = string.strip

    # Convert to uppercase
    string = string.upcase if params.fetch(:upper_case, false)

    # Remove all non-word characters
    if params.fetch(:remove_all_non_word_chars, false)
      string.gsub!(/\W/, '')
    elsif params.fetch(:remove_all_non_printing_chars, true)
      begin
        # Remove all non-printing characters
        string = string.scan(/[[:print:]]/).join
      rescue Exception => exc
        Rails.logger.error("Failed to scan string: #{string.inspect}", exc)
      end
    end
```

We are also using the following Java and JRuby options for the batch workers:
```
export JAVA_OPTS="-server -Xms8192m -Xmx8192m -Xss2048k -XX:G1HeapRegionSize=8m 
-XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=1000 
-XX:+UseCodeCacheFlushing -Djruby.file.encoding=UTF-8 -Djruby.compile.invokedynamic=true 
-Djruby.compile.mode=FORCE -Djruby.global.require.lock=true"
```

On the Puma Web servers we are using:
```
export JAVA_OPTS="-server -Xms8192m -Xmx8192m -Xss2048k -XX:G1HeapRegionSize=8m 
-XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
-XX:+UseCodeCacheFlushing -XX:+ParallelRefProcEnabled -Djruby.file.encoding=UTF-8 
-Djruby.compile.invokedynamic=true -Djruby.global.require.lock=true 
-Djruby.thread.pool.enabled=true"
```

**Comment by reidmorrison** [comment]
I also confirmed that running the above updated Java and JRuby options, that without the code fix above it results in the same exception. The exception will only occur about once in every 10,000 calls.

**Comment by enebo** [comment]
So the same string instance is getting modified at the same time on multiple threads (just must be an uncommon occurrence).  You can also take @kares snippet and add a single dup at the top and then use all mutable operations after that to save GC churn.  You will then only make one copy than one per operation.

**Comment by reidmorrison** [comment]
There is no sharing of data between threads, which is why we thought maybe it is a code optimization issue. One thread is optimizing the code / regexp when another thread is trying to run the code at the same time.
These are batch worker threads that fetch data from the database themselves, and process it entirely on the current thread before fetching the next work item. No data is shared between threads.
The issue only appeared after moving from 1.7.19 to 9.0.3.0. I looked at the JRuby Java code in the stack trace and did not see anything obvious. The only common thread between these two stack traces is that they are both performing a RegExp when the problem occurs.

Thank you for looking into this issue for us @enebo.

**Comment by enebo** [comment]
@reidmorrison Ah ... we do cache all regexps internally.  There must be some path where the underlying bytelist is being passed out/in and not dup'd (or shared).  Then you modify it and it changes the same bytelist as the regexp?  I just audited all outgoing regexps and see nothing bad.  I wonder if this is from making a regexp from a string and we are not marking the bytelist going in as shared somewhere.  Do you know how the regexp it crashes on is created?  Is it made through a string or quote or something like that?

**Comment by reidmorrison** [comment]
It turns out the above code changes do not fix the problem. Helps when I check in the right place in NewRelic for the above `Failed to scan string` error message. The catch clause just logs the error and moves on.

We also noticed that this error is occurring in our Rails Puma web processes during load testing. I.e. It is not limited to the [RocketJob](http://rocketjob.io) workers.

The regular expression in this case is just supplied inline:
```ruby
string = string.scan(/[[:print:]]/).join
```

There are no other occurrences of `/[[:print:]]/` in our codebase.

**Comment by reidmorrison** [comment]
The following code appears to be working, and after 3 hours of continuous testing have not seen the above error since. The regular expression was "compiled" in advance, a much faster regular expression is being used that avoids the scan and join, and the string is modified in place again:
```
  NOT_PRINTABLE = Regexp.compile(/[^[:print:]]/)
  NOT_WORDS     = Regexp.compile(/\W/)
  register_cleaner(:clarity_string) do |string, params|
    if string.is_a?(String)
      # Strip leading and trailing whitespace
      string.strip!

      # Convert to uppercase
      string.upcase! if params.fetch(:upper_case, false)

      # Remove all non-word characters
      if params.fetch(:remove_all_non_word_chars, false)
        string.gsub!(NOT_WORDS, '')
      elsif params.fetch(:remove_all_non_printing_chars, true)
        begin
          # Remove all non-printing characters
          string.gsub!(NOT_PRINTABLE, '')
          # Old code
          # string = string.scan(/[[:print:]]/).join
        rescue Exception => exc
          Rails.logger.error("Failed to scan string: #{string.inspect}", exc)
        end
      end
```

Unfortunately we cannot yet re-produce the problem locally with a stand-alone test script.

**Comment by reidmorrison** [comment]
If we go back to the very first stack trace at the top and walk though it:

1. sub is called on a string:

    - [activesupport-4.1.13/lib/active_support/inflector/methods.rb:71](https://github.com/rails/rails/blob/v4.1.13/activesupport/lib/active_support/inflector/methods.rb#L71):in `camelize'

    ```ruby
    string = string.sub(/^[a-z\d]*/) { inflections.acronyms[$&] || $&.capitalize }
    ```

2. Java sub is called which dups the string and calls sub!

    - [org/jruby/RubyString.java:2209](https://github.com/jruby/jruby/blob/9.0.3.0/core/src/main/java/org/jruby/RubyString.java#L2209):in `sub'

    ```java
@JRubyMethod(name = "sub", reads = BACKREF, writes = BACKREF)
    public IRubyObject sub19(ThreadContext context, IRubyObject arg0, Block block) {
        RubyString str = strDup(context.runtime);
        str.sub_bang19(context, arg0, block);
        return str;
    } 
    ```

3 . Java sub!

[org/jruby/RubyString.java:2230](https://github.com/jruby/jruby/blob/9.0.3.0/core/src/main/java/org/jruby/RubyString.java#L2230)
:in `sub!': string modified (RuntimeError)

    ```java
    ```

**Comment by enebo** [comment]
Ah if you can add -d to your jruby command-line (also -Xbacktrace.style=raw won't hurt) it should go further and give the full java stacktrace.  It is happening in modifyCheck and it means something it is expecting has changed but 'sub' calls a lot of other methods so it may be any of those.

If you are re-spawning JRuby (which rails does from command-line) set env:

```text
JRUBY_OPTS="-d -Xbacttrace.style=raw"
```

I think this output will localize things more.

**Comment by reidmorrison** [comment]
Unfortunately we are not able to re-produce the first stack trace in out test environment, we can only reproduce the second stack trace.

By turning on the debug option `-d` the problem does not occur at all. After removing the `-d` option but keeping `backtrace.style=raw`, and reverting the code to the original listed first above, we were able to obtain the following stack trace:
```
Java::JavaLang::ClassCastException: org.jruby.RubyNil cannot be cast to org.jruby.RubyMatchData
org.jruby.RubyString.scanOnce(RubyString.java:3671)
org.jruby.RubyString.scan19(RubyString.java:3638)
org.jruby.RubyString$INVOKER$i$1$0$scan19.call(RubyString$INVOKER$i$1$0$scan19.gen)
org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:380)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
var.www.rails.connect.components.common.config.initializers.data_cleansing.invokeOther31:scan(/var/www/rails/connect/components/common/config/initializers/data_cleansing.rb)
var.www.rails.connect.components.common.config.initializers.data_cleansing.RUBY$block$DataCleansing$0(/var/www/rails/connect/components/common/config/initializers/data_cleansing.rb:124)
```

**Comment by kares** [comment]
as you guys mentioned that both threads do regexp-s (although I still believe there might be an underlying string sharing issue) ... could you share what the other thread(s) tends to be doing - same code ?
... I failed to reproduce with up to thousands of threads running - maybe for the scan part I might need some string inputs although probably not.

**Comment by reidmorrison** [comment]
Yes, I could not reproduce it locally either.

The reproducible scenario is a batch worker, where every thread works on a different inquiry. The inquiries run the exact same code and run similar code paths, but do not share any data, since it is read directly from MongoDB.

To help reproduce the issue I am going to look at adding in the [Data Cleansing](https://github.com/reidmorrison/data_cleansing) gem with a cleaner defined, to see if invoking the Regex via a global block makes a difference.

**Comment by kares** [comment]
did try to figure this one (and did some cleansing of the related code on master) - so far not sure how the cast exception possibly happens but I believe its related to a previous regexp-matching context. in the mean time I did found another nasty bug with the "optimized" `str.scan('str-passed')` path (likely unrelated here) where it might leak a previous regexp/pattern in `MatchData` (if `$~` is used) in <= 9.0.3 ... [with the master updates simply ended up in NPE](https://github.com/jruby/jruby/commit/0265698d06a9e76be2e8aa88d2f65e144de6505e)

can come up with some System.err logging around **RuntimeError: string modified** if you're willing to try out a master snapshot *jruby.tar.gz* build (knowing the string instance might shed some light) and @enebo does not have an ace up in his sleeve ...

**Comment by bpardee** [comment]
Yes, we can try out a master snapshot.  Just let us know how we can help!

**Comment by kares** [comment]
you could try the [dist from here](https://dl.dropboxusercontent.com/u/149718/jruby-dist-9.0.4.0-SNAPSHOT-bin.tar.gz) (or do `mvn -P dist`) ... it's off **test-str-leak** branch (did not put the logging commit onto master ... yet, although it might be useful in general) and on top of some internal refactoring it [will log to](https://github.com/jruby/jruby/commit/42234f7e3e05db1e20bf659b35b277c4c477b230) `System.err` whenever a **RuntimeError: string modified** is to be raised ...

**Comment by enebo** [comment]
#3031 seems to be the base cause of this issue.

**Comment by bpardee** [comment]
Closed as duplicate of https://github.com/jruby/jruby/issues/3031
