### ISSUE TITLE
NameError: uninitialized constant  in a nested for loop

### ISSUE THREAD

**Issue by andrewt0301** [jruby/jruby#3455]
I faced a strange error in JRuby 9.0.3.0. With JRuby 1.7.22, the same code works fine.
A constant gets uninitialized when it is accessed inside a nested for loop. Code is below:

test.rb:

``` ruby
class Base
  @@inherited_classes = Array.new

  def self.inherited_classes
    @@inherited_classes
  end

  def self.inherited(subclass)
    @@inherited_classes.push subclass
  end
end

file = File.expand_path ARGV[0]
require file

inherited_classes = Base::inherited_classes
inherited_classes.each do |inherited_class|
  inherited_class.new
end
```

test_inherited.rb:

``` ruby
class Inherited < Base
  X = 10

  def initialize
    super
    puts "HI from Inherited.initialize"

    puts X # OK: X is defined here as 10
    for i in 0..1 do
      puts X # OK: X is defined here as 10
      for j in 0..1 do
        puts X # Error: uninitialized constant X
      end
    end
  end
end
```

Command:
 java -jar jruby.jar test.rb test_inherited.rb

Console output:
HI from Inherited.initialize
10
10
NameError: uninitialized constant X
        const_missing at org/jruby/RubyModule.java:3181
  block in initialize at /home/andrewt/jars/test_inherited.rb:13
                 each at org/jruby/RubyRange.java:454
  block in initialize at /home/andrewt/jars/test_inherited.rb:12
                 each at org/jruby/RubyRange.java:454
           initialize at /home/andrewt/jars/test_inherited.rb:10
     block in test.rb at test.rb:19
                 each at org/jruby/RubyArray.java:1560
                <top> at test.rb:18

**Comment by kares** [comment]
there was a similar issue reported and this is fine on 9.1.6/9.1.7 please feel free to re-open otherwise
