### ISSUE TITLE
LoadError: no such file to load

### ISSUE THREAD

**Issue by Javix** [jruby/jruby#3456]
I switched from `jruby-9.0.0.0.pre1 [ x86_64 ]`to `jruby-9.0.3.0 [ x86_64 ]`and it fails to load java jars in a simple require loop:
```
require 'java'

Dir["jars/*.jar"].each { |jar| require jar }
```
What was changed since `jruby-9.0.0.0.pre1`version ? How to adapt the require ?

- reproduced on OS 10.11.1
- jruby version: `jury 9.0.3.0 (2.2.2) 2015-10-21 633c9aa Java HotSpot(TM) 64-Bit Server VM 24.51-b03 on 1.7.0_51-b13 +jit [darwin-x86_64]`

Thank you.

**Comment by mkristian** [comment]
the current directory is  not on the load_path anymore, I think

```
Dir["./jars/*.jar"].each { |jar| require jar }
```
or
```
Dir["jars/*.jar"].each { |jar| require File.expand_path(jar) }
```
should work.

**Comment by Javix** [comment]
Version `Dir["./jars/*.jar"].each { |jar| require jar }`worked for me. Thank you very much Christian.
