### ISSUE TITLE
Unable to override classpath for ScriptingContainer

### ISSUE THREAD

**Issue by r6p** [jruby/jruby#3461]
In one of my target deployment environments the Java classpath contains another older version of JRuby. Our application is making use of ScriptingContainer to execute Ruby code and when it goes to load YAML files it uncovers the classpath collision between the two versions of JRuby with an error related to Psych. To workaround this issue, I've attempted to make use of ScriptingContainer#setLoadPaths to control the classpath provided to the Ruby "environment" by excluding the older jruby-complete jar from the classpath , but it doesn't seem to take, it always inherits the classpath from the parent Java environment. 

Maybe this isn't supposed to work in this way, but the documentation below led me to believe this would be possible. If this isn't a bug, is there another way to override the CLASSPATH or class loading behavior to exclude certain jars at runtime?

````
From: org.jruby.embed.ScriptingContainer

public void setLoadPaths(List<String> paths)
Changes a list of load paths Ruby scripts/libraries. The default value is an empty array. 
If no paths is given, the list is created from java.class.path System property. 
This value can be set by org.jruby.embed.class.path System property, also. 
Call this method before you use put/get, runScriptlet, and parse methods so that the given paths will be used.

Specified by:
setLoadPaths in interface EmbedRubyInstanceConfigAdapter

Parameters:
paths - a new list of load paths.

Since:
JRuby 1.5.0.
````

**Comment by mkristian** [comment]
@r6p the only thing you can set with the ScriptingContainter is the the classloader:
```scriptingContainer.setClassLoader(somehting)```

and this classloader needs to contain the org.jruby:jruby dependencies (or jruby-complete). so you can always get the "jars" and setup a clean classloader hierarchy with only ONE jruby in it.

if you use the ```IsolatedScriptingContainer``` then you get one which does not inherit GEM_HOME, GEM_PATH, JARS_HOME from the outer environment but assumes everything is embedded.

you also can try to look at the jruby classloader before going to the parent but this one has problems with nokogiri gem (and maybe others). but there is a change to this solves your problem:
```scriptingContainer.setClassloaderDelegate(false)```

**Comment by r6p** [comment]
I actually already tried what you suggested i.e. IsolatedScriptingContainer#setClassLoader but had no luck with that. Adding scriptingContainer.setClassloaderDelegate#setClassloaderDelegate(false) doesn't seem to change the behavior the parent classloader is always at play.

**Comment by mkristian** [comment]
```new URLClassLoader(urls)``` does use the "application classloader" as parent. you better use
```new URLClassLoader(urls, ClassLoader.getSystemClassLoader().getParent())``` which is the extension classloader and best place to start your own classloader hierarchy.

but this will not work if jruby is the bootstrap classloader which for example bin/jruby from the binary distribution does for faster loading.

**Comment by r6p** [comment]
@mkristian ````new URLClassLoader(urls, ClassLoader.getSystemClassLoader().getParent())````, didn't seem to work either. I am going to give, ````new URLClassLoader(urls, ClassLoader.getSystemClassLoader().getParent())```` as shot, unless you can think of a better option.

**Comment by r6p** [comment]
@mkristian, both our jar with 9K embedded and the conflicting older jruby-complete.jar are in the SystemClassLoader. That is why it seems that #getParent() should work as you describe.

I've also tried the code below and within an 'rspec' context the resulting $CLASSPATH still contains jars that come from the SystemClassLoader that I had filtered out when creating the isolatedClassLoader. Let me try it in the true runtime context to see if anything changes.


````
    IsolatedScriptingContainer ruby = null;
    ClassLoader isolatedClassLoader = new URLClassLoader(urls, ClassLoader.getSystemClassLoader().getParent());
    try {
      ruby = (IsolatedScriptingContainer) isolatedClassLoader.loadClass("org.jruby.embed.IsolatedScriptingContainer").newInstance();
    } catch (ClassNotFoundException ex) {
      // Unable to resolve class for some reason, fallback to default and move on
    } catch (InstantiationException ex) {
      // Unable to instantiate class for some reason, fallback to default and move on
    } catch (IllegalAccessException ex) {
      // No access to instantiate class for some reason, fallback to default and move on
    }
    ruby.setClassloaderDelegate(false);
    ruby.setClassLoader(isolatedClassLoader);

    ruby.runScriptlet("require 'pp'; pp $CLASSPATH");

````

**Comment by mkristian** [comment]
@r6p what is the output of this ?

FYI $CLASSPATH are the urls from ```JRuby.runtime.jruby_class_loader``` this jruby-classloader has the classloader of the ScriptingContainer as parent.

now I had the thought that the problem might be that per default those ScriptingContainer create singleton runtime, i.e. uses the global runtime which might be the reason things get shared between the two runtime (are there two runtimes ? it sounds like what you described so far).

**Comment by mkristian** [comment]
@r6p hey any luck with this ? I know it is tricky and remote debugging is difficult but actually I am sure there is a way of getting it to work (as I had similar cases in the past).

**Comment by r6p** [comment]
@mkristian, i've tried a few things and none worked. The last major effort I made was to use an IsolatedScriptingContainer created via reflection, with setClassLoaderDelegate(false), and setClassLoader(customClassLoader) being called to then launch the Ruby code  to kick's off our Map/Reduce jobs. Doing this produces a number of problems associated with code loading from multiple class loaders, i.e. the same types not being equivalent as they could have been loaded under multiple class loaders mostly as it is related to Hadoop dependencies. I am going to try to generate a simple test case that reproduces the problem and post back.

With regards to you thoughts own two runtimes, can you give me more information on how I can either ensure that there are two separate Runtimes or verify that a single runtime is being shared? Is there a JRuby test case that validate that each ScriptingContainer has a unique Runtime? If, so can you point me to that?

**Comment by r6p** [comment]
So I was able to get something working using multiple classloaders (not ideal), but the key was to create a new classloader that doesn't the the conflicting jruby-complete jar in that classloader, then load the IsolatedScriptingContainer via reflection, setClassloaderDelegate(false), and finally in the Map/Reduce Ruby code that is being executed via the scripting container ````java.lang.Thread.currentThread().setContextClassLoader(JRuby.runtime.jruby_class_loader)````.

All this was required to avoid a YAML conflict when doing ```require 'yaml'```` that was loading YAML code from both versions of the JRuby jars on the classpath although the preferred version of JRuby was in a jar that was earlier in the classpath. I "think" this bit of irb code illustrates the issue that I was facing.

````
cmd: pwd
/tmp/jruby-collision

cmd: ls
jruby-complete-1.7.19.jar
jruby-complete-9.0.3.0.jar

cmd: java -Xmx500m -Xss1024k -jar jruby-complete-9.0.3.0.jar -e 'load "META-INF/jruby.home/bin/jirb"'
["file:/Users/me/.m2/repository/jline/jline/2.11/jline-2.11.jar", "file:/var/folders/20/fx2s3vsn3tgf_88k5yq6qpyw0000gn/T/jruby-15276/jruby6743288289275416610readline.jar"]
=> nil
>> puts $LOAD_PATH
uri:classloader:/META-INF/jruby.home/lib/ruby/2.2/site_ruby
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib
=> nil
>> c = org.jruby.embed.IsolatedScriptingContainer.new
=> #<Java::OrgJrubyEmbed::IsolatedScriptingContainer:0x6dab01d9>
>> c.run_scriptlet("puts $LOAD_PATH")
uri:classloader:/META-INF/jruby.home/lib/ruby/2.2/site_ruby
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib
=> nil
>> c.run_scriptlet("puts $CLASSPATH")
["file:/Users/me/.m2/repository/jline/jline/2.11/jline-2.11.jar", "file:/var/folders/20/fx2s3vsn3tgf_88k5yq6qpyw0000gn/T/jruby-15276/jruby6743288289275416610readline.jar"]
=> nil
>> $CLASSPATH << File.join(Dir.pwd, 'jruby-complete-1.7.19.jar')
=> ["file:/Users/me/.m2/repository/jline/jline/2.11/jline-2.11.jar", "file:/var/folders/20/fx2s3vsn3tgf_88k5yq6qpyw0000gn/T/jruby-15276/jruby6743288289275416610readline.jar", "file:/private/tmp/jruby-collision/jruby-complete-1.7.19.jar"]
>> puts $LOAD_PATH
uri:classloader:/META-INF/jruby.home/lib/ruby/2.2/site_ruby
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib
=> nil
>> puts $CLASSPATH
["file:/Users/me/.m2/repository/jline/jline/2.11/jline-2.11.jar", "file:/var/folders/20/fx2s3vsn3tgf_88k5yq6qpyw0000gn/T/jruby-15276/jruby6743288289275416610readline.jar", "file:/private/tmp/jruby-collision/jruby-complete-1.7.19.jar"]
=> nil
>> c.run_scriptlet("puts $LOAD_PATH")
uri:classloader:/META-INF/jruby.home/lib/ruby/2.2/site_ruby
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib
=> nil
>> c.run_scriptlet("puts $CLASSPATH")
["file:/Users/me/.m2/repository/jline/jline/2.11/jline-2.11.jar", "file:/var/folders/20/fx2s3vsn3tgf_88k5yq6qpyw0000gn/T/jruby-15276/jruby6743288289275416610readline.jar", "file:/private/tmp/jruby-collision/jruby-complete-1.7.19.jar"]
=> nil
>> c = org.jruby.embed.IsolatedScriptingContainer.new
=> #<Java::OrgJrubyEmbed::IsolatedScriptingContainer:0x68ee3b6d>
>> c.setClassloaderDelegate(false)
=> nil
>> c.run_scriptlet("puts $LOAD_PATH")
uri:classloader:/META-INF/jruby.home/lib/ruby/2.2/site_ruby
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib
=> nil
>> c.run_scriptlet("puts $CLASSPATH")
["file:/Users/me/.m2/repository/jline/jline/2.11/jline-2.11.jar", "file:/var/folders/20/fx2s3vsn3tgf_88k5yq6qpyw0000gn/T/jruby-15276/jruby6743288289275416610readline.jar", "file:/private/tmp/jruby-collision/jruby-complete-1.7.19.jar"]
=> nil
>> c.run_scriptlet("require 'yaml'")
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/psych.rb:229: warning: already initialized constant LIBYAML_VERSION
````

**Comment by r6p** [comment]
@headius @enebo, any chance I can get you guys to have a look at this as well. I basically have two colliding version of jruby-complete on the classpath that I don't control. The primary version that I want to use is bundled into my own jar. But there is another older version of the jruby-complete jar on the classpath. I basically want all resources for 9000 from stdlib and site_ruby to load from my jar like ````require 'yams'```` instead of loading from both jars.

**Comment by mkristian** [comment]
@r6p when you talked about classpath and mean ```$CLASSPATH``` as in your sample code. then you have snakeyaml.jar as part of jruby-complete-1.7.19.jar and psych gem from jruby-9k uses a different version of snakeyaml. both will use the same $CLASSPATH. so you end up with two different versions of the snakeyaml on the same classloader and there is no way to fix this beside not bringing the jruby-complete-1.7.19.jar on the classpath. btw jruby-complete-1.7.23.jar uses the same snakeyaml version as psych from jruby-9k

**Comment by r6p** [comment]
@mkristian this happens/is true whether it is ````$CLASSPATH```` or the java.class.path. So I guess the short answer is that there is no way to exclude the 2nd version of JRuby from interfering when Ruby at least Ruby files are being loaded from the $LOAD_PATH. I guess I'll have to go with the custom ClassLoader option for now.

**Comment by mkristian** [comment]
@r6p what I said is around ```$CLASSPATH``` and adding a jruby-9k jar there will blow up as well.

the java.class.path - let me try this.

**Comment by mkristian** [comment]
@r6p I just played around a bit with having both jruby-complete-17.19 and jruby-complete-9.0.4.0 on the java.class.path. this starts using  org.jruby.gen.org$jruby$ext$psych$PsychParser$POPULATOR which does not exists on jruby-9k anymore, and this uses methods which only exists in jruby-1.7.x. yes, there is no way to run both jrubies in one classloader

**Comment by r6p** [comment]
@mkristian, ok many thanks for your help. Is it worthy of a technical feature request to be able to isolate the ScriptingContainer environments to a single version of JRuby? Or is this just too hard or impossible to do?

**Comment by mkristian** [comment]
@rp6 the problem here is really that you have two versions of the same library on classloader - in general this is source for all kind of classloader problems: NoSuchMethodError, ClassCastException. this is true for any library. having a classpath there is an order and you could make something here but putting the same jars into WEB-INF/lib directory there is no order - maybe the lexical or creation time. IMO there is no way to achieve this.

**Comment by r6p** [comment]
@mkristian ok thanks again for all your help.

**Comment by mkristian** [comment]
@r6p closing issue since as far I understood the problem there nothing we can do on the JRuby side of things
