### ISSUE TITLE
Method aliases are not consistently mapped for a class with isFoo and getFoo

### ISSUE THREAD

**Issue by benissimo** [jruby/jruby#3470]
For a class

```java
public class Ugh {

  public boolean isFoo() {
     return false;
  }

  public int getFoo() {
     return 3;
  }
}
```
calling `.foo` from Jruby results in inconsistent behavior.

Sometimes it behaves this way:
```
jruby-1.7.22 :001 > Java::Ugh.new.foo
 => 3 
```

Other times (exit jruby and fire up irb a new time, this time using, say, java 8 instead of java 7) it behaves this way:
```
jruby-1.7.22 :001 > Java::Ugh.new.foo
 => false 
```

Per https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby
'something' -> 'getSomething'
'something?' -> 'isSomething'

However in practice 'something' gets mapped to both 'getSomething' and 'isSomething' (assuming the java class has both methods) and, as the order those methods get mapped appears to be nondeterministic, there's no consistency as to which one gets mapped last (clobbering the first). At least that's my best guess as to what's causing the issue here.

We stumbled across this when upgrading to java 8, initially thought it was related to that, but ultimately found there to be no consistent behavior (different developers got different results running the above test).

We suspect that ./core/src/main/java/org/jruby/javasupport/JavaUtil.java is involved.

Suggestion: do _not_ map 'foo' to 'isFoo'. Only map 'foo?' to 'isFoo' (as the wiki says).
Or: ensure java methods are sorted in some consistent order before mapping them.

**Comment by benissimo** [comment]
p.s. the workaround in these cases is to rely on `get_foo` and `foo?` instead of `foo`

**Comment by headius** [comment]
Your suggestion is reasonable, and it now seems a little odd to me that we would map "boolean isFoo" to "foo" and not just "foo?".

I expect the issue is that different versions of JVM provide these methods do us in different orders. We could (perhaps should) make this more consistent by sorting the lists of methods before binding them, but I agree this case requires a bit of improvement.

**Comment by kares** [comment]
@benissimo is this 9K only for you or 1.7 as well ?

**Comment by kares** [comment]
on both releases and [foo is used as an alias for isFoo](https://github.com/jruby/jruby/blob/aedbf26/core/src/main/java/org/jruby/javasupport/JavaUtil.java#L460-L479) ;( ... too bad this didn't get spotted before 9K.

**Comment by benissimo** [comment]
@kares I've only got jruby 1.7.22 installed, can't confirm re 9K, but sounds like you have already.

**Comment by kares** [comment]
a bit of a hack but likely the simplest thing we could do: https://github.com/jruby/jruby/commit/63b65ef5e840f763ed5a588b685ec83985b2da11

**Comment by benissimo** [comment]
Thanks for responding to this so quickly! Kudos!
