### ISSUE TITLE
Monkey Patching extension classes

### ISSUE THREAD

**Issue by monkstone** [jruby/jruby#3471]
I am not sure whether this an issue, or wrinkle that needs to be made more known? In ruby-processing/JRubyArt I have monkey patched Numeric to provide radians and degrees methods, and this works without any problems.  When I tried to monkey-patch my Vec3D class (which is a jruby extension) the same way there was an error, however if instead I used this form

``` ruby
Vec3D.class_eval do
   def rotate_x(theta)
      ...
   end
end
```

It worked as expected see gist https://gist.github.com/monkstone/1620da6a63cba504931b

**Comment by headius** [comment]
Can you provide the error as well? I don't know why there would be an issue patching an extension class, though frequently extensions make direct calls to the Java methods (as do C extensions in some cases), bypassing your patches.

**Comment by monkstone** [comment]
Well I've done a bit more research trying to produce a simple test case (but that doesn't produce the error), so it may have something to do with where the patch is done

This was the error I got:-
```bash
Java::OrgJrubyExceptions::RaiseException
  (ArgumentError) wrong number of arguments calling `initialize` (3 for 0)
 	RUBY.mouse_moved(mesh_doodle.rb:62)
```
So it looks like the Vec3D of the patch is seen in this case (lacks constructor of the original)?

PS: I was using java 8 lambda in constructor but I think that is irrelevant as I used the same in my simple test case, which failed to create error.  This is probably an edge case, and there is a decent workaround, do you think it needs pursuing?

**Comment by monkstone** [comment]
Had a bit of brain-wave, created and this test case https://github.com/ruby-processing/monkey reproduces behaviour, whether it is an error or just something to advise about...
`rake` to compile and run tests.

**Comment by monkstone** [comment]
Updated build to use polyglot build https://github.com/ruby-processing/monkey, problem seem to be that the regular monkey patching does something to class constructor.

**Comment by monkstone** [comment]
Just thought I had better test using without lambda8 constructor:-
```java
  /**
  *
  * @param runtime
  */
  public static void createVec(final Ruby runtime) {
      RubyClass vecCls = runtime.defineClass("Vec2D", runtime.getObject(), new ObjectAllocator() {
        @Override
        public IRubyObject allocate(Ruby runtime, RubyClass rubyClass) {
          return new Vec(runtime, rubyClass);
        }
    });
    vecCls.defineAnnotatedMethods(Vec.class);
  }
```
Still get same pattern ie class_eval works, regular class monkey patch fails.

**Comment by monkstone** [comment]
Interesting monkey patch instance works
```ruby
gem 'minitest' # don't use bundled minitest
require 'java'
require 'minitest/autorun'
require 'minitest/pride'
require_relative '../../monkey/lib/monkey.rb'

Dir.chdir(File.dirname(__FILE__))

module Processing
  
  class VecTest < Minitest::Test
    def test_rotate
      a = Vec2D.new(3, 5)
      class << a
        def rotate(theta)
          self.x *= Math.cos(theta)
          self.y *= Math.sin(theta)
          self 
        end
      end
      a.rotate(Math::PI / 4)
      b = Vec2D.new(3 * Math.cos(Math::PI / 4), 5 * Math.sin(Math::PI / 4))
      assert_equal(a, b, 'Failed Rotate')
    end 
  end
end
```

**Comment by monkstone** [comment]
Still failing with:-
jruby 9.1.0.0-SNAPSHOT (2.3.0) 2016-02-27 e657f19 OpenJDK 64-Bit Server VM 25.74-b02 on 1.8.0_74-b02 +jit [linux-amd64]
