### ISSUE TITLE
Chat window not tall enough for reCAPTCHA.

### ISSUE THREAD

**Issue by lonny** [jruby/jruby#3482]
When go to jruby chat (jruby.org/chat) and try to log in, and click "I am not a robot", the reCAPTCHA window that pops up is taller than the embed window, so the instructions at the top of the reCAPTCHA are not visible. See screenshot.

Firefox 42 on OS X 10.10.4.

![screen shot 2015-11-20 at 10 41 18 am](https://cloud.githubusercontent.com/assets/4526/11308641/3b67dcc2-8f74-11e5-9b84-c51a7be5b079.png)

**Comment by kares** [comment]
thx, seems fine with the Kiwi IRC [switch](https://github.com/jruby/jruby.github.io/commit/ca59471f9ac896487e74414449eb79a4bc4be48b) ... bugs should maybe be reported against that repo for next.
