### ISSUE TITLE
Strange warning "io/console not supported" when doing a syntax check on Windows

### ISSUE THREAD

**Issue by rovf** [jruby/jruby#3489]
jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 24.79-b02 on 1.7.0_79-b15 +jit [Windows 7-amd64]

When I syntax check a file with warnings turned on, i.e.

   jruby -wc myfile.rb

I get the warning 

  io/console not supported; tty will not be manipulated

**Comment by mprins** [comment]
duplicate #2944

**Comment by kares** [comment]
> duplicate #2944
