### ISSUE TITLE
extending RubyProc to easily trigger arity check?

### ISSUE THREAD

**Issue by kares** [jruby/jruby#3499]
currently a `RubyProc` instance only seems to validate args if its a lambda (which is fine of course).

however I stumbled upon an "edge" case from MRI 2.3.0-preview1 where a non-lambda does validation.
`Hash#to_proc` seems to be an exceptional case, behaves (does not seem like a bug in MRI) : 

```ruby
    h = { 1 => 10, false => true, '2' => :'20' }
    assert_equal false, h.to_proc.lambda?
    proc = h.to_proc
    assert_equal 10, proc.call(1)
    assert_equal true, proc.call(false)
    assert_equal nil, proc.call(2)

    assert_raises(ArgumentError) { proc.call }
    assert_raises(ArgumentError) { proc.call 1, 2 }
```

please review, should it get refactored in any way - does it seems like a hack to you guys to sub-class : 
55fdd007f34e3f2eac58b38ce36b236a5cfafddd // cc @enebo @subbuss 

p.s. also tried `:symbol.to_proc.call 1, 2, 3` but that seems to accept any number of arguments ... like a plain-old Ruby proc.

**Comment by enebo** [comment]
@kares I think extending RubyProc is fine but there seems to be no block semantics in the underlying method (e.g. arity must be 1 and there are no captures).  So you might want to just implement call directly in StrictProc (which I would rename to HashProc).

**Comment by kares** [comment]
right - seemed I over complicated so I simplified with a RubyProc sub-class only : 
https://github.com/kares/jruby/commit/b24bad10e5c8845ba7ddd498f6095d428bb5387f

... but than I realized that won't work since the block can not stay at `NULL_BLOCK` due [`isGiven`](https://github.com/kares/jruby/blob/ruby-2.3/core/src/main/java/org/jruby/runtime/Block.java#L240)
and sub-classing a `Block` only mean unfinalizing the runtime `Block` class, is that right to do ?

**Comment by enebo** [comment]
@kares ah ick! I guess we do need a specialized version of block after all :|

**Comment by kares** [comment]
closing (for now). on **ruby-2.3** a custom `Block` sub-class has been invented (which required class Block to be no longer final) - that seems to cover all the cases without sub-classing a `BlockBody` : https://github.com/jruby/jruby/commit/b2cac044d69873405d8bce925b8ff317bce4ff59
