### ISSUE TITLE
[Truffle] Support ObjectSpace.each_object for classes without deoptimisation

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#3501]
Truffle supports `ObjectSpace.each_object` but it is currently implemented using stop-and-deoptimise-the-world, which means it's expensive to use.

That's ok, as `ObjectSpace.each_object` is pretty rare, and is probably (I'm guessing - no empirical data) that it's generally used in things like testing frameworks. There is one exception, which is when it's used with classes.

For example: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/class/subclasses.rb

JRuby support this specific case by maintaining a weak set of potentially live classes, which they add to whenever a class is created. We should do the same.

Important: check how this interacts with singleton classes, which we may allocate in inner loops. It should just work with singleton classes on classes and modules, I believe.

**Comment by robacarp** [comment]
For another reference, Sidekiq is using ObjectSpace though it wouldn't hurt it that much to hit a hard stop as it hits only at boot:

- https://github.com/mperham/sidekiq/blob/7a727c61cfd3f174d32e3a231b14833b61b897fe/lib/sidekiq/logging.rb#L63
- https://github.com/mperham/sidekiq/blob/e664794b6a02ca9fec4892367c14a3519560da08/lib/sidekiq/cli.rb#L169

**Comment by chrisseaton** [comment]
@nirvdrum do you know how JRuby is able to run Sidekiq when it's using `each_object` with `File`?

**Comment by kares** [comment]
@chrisseaton `each_object` works for class/module argument by default as those objects are already tracked by the runtime: https://github.com/jruby/jruby/blob/f9d03ff86c1da78f71341d0c9d7b78324330eec7/core/src/main/java/org/jruby/RubyObjectSpace.java#L124-L149

**Comment by chrisseaton** [comment]
@kares yes but this is calling it with `File`.

**Comment by kares** [comment]
oh right, that's interesting. believe its not run with `--daemon` or handling *USR2* under JRuby than.

**Comment by chrisseaton** [comment]
Closing because we've moved out of this repository.
