### ISSUE TITLE
JRuby 2.2 mode inconsistent with MRI 2.1+

### ISSUE THREAD

**Issue by envygeeks** [jruby/jruby#3507]
As it stands JRuby 2.2 mode (on 9.0.3.0) is inconsistent with MRI 2.1+ when it comes to `module_function` and `define_method` behavior.  Take the following sample:

```ruby
module MyModule module_function
  methods = { :hello => :world }
  methods.each do |key, val|
    define_method key do
      val
    end
  end
end
```

In Ruby 2.0 `module_function` is not inherited, but in 2.1+ it is inherited, this leads to inconsistent behavior when moving between JRuby and MRI.

**Comment by headius** [comment]
Surprising. This should just be a frame field that propagates to the define_method.

**Comment by headius** [comment]
Simpler repro:

```ruby
module Foo
  module_function
  define_method :foo {}
end
Foo.foo # error on JRuby, not on MRI
```

**Comment by headius** [comment]
I'm not sure this has worked for a long time. JRuby appears to always define_method as public as far back as 2011:

```
[] ~/projects/jruby $ rvm jruby-1.6 do ruby -e "module Foo; module_function; define_method :foo do; end; end; Foo.foo"
NoMethodError: undefined method `foo' for Foo:Module
  (root) at -e:1

[] ~/projects/jruby $ rvm jruby-1.7 do ruby -e "module Foo; module_function; define_method :foo do; end; end; Foo.foo"
NoMethodError: undefined method `foo' for Foo:Module
  (root) at -e:1
```

Going to look at improving this for 9.1, when we make a bigger move to 2.3 compatibility.

**Comment by envygeeks** [comment]
Aww boo :cry: so no fix for 9.5 so we can stop doing extend self on modules?

**Comment by eregon** [comment]
I added a spec for the private case with an UnboundMethod in d6b97fb6ced317df8ce72c62aa00157a2f21e06f. It would be good to have new specs for blocks and private and module_function visibility.

**Comment by headius** [comment]
@envygeeks You should be able to modify it to do module_function after the definition. It will work the same way as calling it once before a group of method definitions.

**Comment by headius** [comment]
The trivial fix (grabbing current frame's visibility) appears to regress a couple specs:
```
1)
main#define_method creates a public method in TOPLEVEL_BINDING FAILED
Expected Object to have method 'boom' but it does not
/Users/headius/projects/jruby/spec/ruby/core/main/define_method_spec.rb:17:in `block in (root)'
org/jruby/RubyBasicObject.java:1641:in `instance_eval'
org/jruby/RubyEnumerable.java:1562:in `all?'
org/jruby/RubyFixnum.java:296:in `times'
org/jruby/RubyArray.java:1565:in `each'
/Users/headius/projects/jruby/spec/ruby/core/main/define_method_spec.rb:6:in `<top>'
org/jruby/RubyKernel.java:952:in `load'
org/jruby/RubyBasicObject.java:1641:in `instance_eval'
org/jruby/RubyArray.java:1565:in `each'

2)
main#define_method creates a public method in script binding FAILED
Expected Object to have method 'boom' but it does not
/Users/headius/projects/jruby/spec/ruby/core/main/define_method_spec.rb:22:in `block in (root)'
org/jruby/RubyBasicObject.java:1641:in `instance_eval'
org/jruby/RubyEnumerable.java:1562:in `all?'
org/jruby/RubyFixnum.java:296:in `times'
org/jruby/RubyArray.java:1565:in `each'
/Users/headius/projects/jruby/spec/ruby/core/main/define_method_spec.rb:6:in `<top>'
org/jruby/RubyKernel.java:952:in `load'
org/jruby/RubyBasicObject.java:1641:in `instance_eval'
org/jruby/RubyArray.java:1565:in `each'
```
I don't think we're properly managing visibility yet.

**Comment by headius** [comment]
With a tweak to the "top self" `main` I believe all specs pass again. I've pushed my fix and we'll see how the other suites like it.
