### ISSUE TITLE
Having Problems With Celluloid::IO / Nonblocking IO

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jruby/jruby#3520]
Coming from https://github.com/celluloid/celluloid-io/issues/156. Maybe someone reported this already, couldn't find the specific one, but I saw a lot of non-blocking IO related issues.

**Comment by tarcieri** [comment]
For context, this is the error:

```
SocketError: (IO::EAGAINWaitReadable) recvfrom(2) would block
    org/jruby/ext/socket/RubyUDPSocket.java:220:in `recvfrom_nonblock'
    org/jruby/ext/socket/RubyUDPSocket.java:227:in `recvfrom_nonblock'
    /install/path/gems/celluloid-io-0.17.2/lib/celluloid/io/udp_socket.rb:22:in `recvfrom'
    /install/path/gems/celluloid-io-0.17.2/lib/celluloid/io/dns_resolver.rb:45:in `resolve'
    /install/path/gems/celluloid-io-0.17.2/lib/celluloid/io/tcp_socket.rb:63:in `initialize'
```

Expected: `IO::EAGAINWaitReadable` (or at least a class with `IO::WaitReadable` as an ancestor)
Actual: `SocketError` (with odd "IO::EAGAINWaitReadable" parenthetical)

**Comment by tarcieri** [comment]
Here's the code in question:

https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/socket/RubyUDPSocket.java#L220

It looks like it's throwing the wrong exception in this case?

**Comment by TiagoCardoso1983** [comment]
It's actually throwing SocketError in other places where it shouldn't:

```ruby
# ruby 2.0.0
> UDPSocket.new.bind "127.0.0.1", 191 #=> Errno::EACCES: Permission denied - bind(2)
# jruby 9.0.4.0
> UDPSocket.new.bind "127.0.0.1", 191 #=> SocketError: bind: name or service not known
from org/jruby/ext/socket/RubyUDPSocket.java:157:in `bind'
```

**Comment by TiagoCardoso1983** [comment]
I also think that this is an overall socket handling issue (not only udp):

```ruby
# ruby 2.0.0
> u = TCPSocket.new "127.0.0.1", 22
> u.read_nonblock 22 #=> "Open bla bla"
> u.read_nonblock 22 #=> Errno::EAGAIN: Resource temporarily unavailable - read would block
# jruby 9.0.4.0
> u = TCPSocket.new "127.0.0.1", 22
> u.read_nonblock 22 #=> "Open bla bla"
> u.read_nonblock 22 #=> IO::EAGAINWaitReadable: Resource temporarily unavailable - read would block
from org/jruby/RubyIO.java:2767:in `read_nonblock'
```

**Comment by kares** [comment]
3cadb0cf6af913 handles the main issue and there's some more tunings: bdcc08eaa990, 75456736bab1 and 4f9e6bec6813. note that some of MRI's error is not followed blindly e.g. `TCPSocket.new` https://github.com/jruby/jruby/commit/75456736bab130415b8803023248dd75d9743947#diff-f433d6e3a0314b6d0e9bcf7669f745aaR147 (error type changes when port is too big vs. negative) ... but that should not matter much. let us know if there's anything not behaving sufficiently for `Celluloid::IO`.
