### ISSUE TITLE
Encoding::CompatibilityError: incompatible encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by nadavshatz** [jruby/jruby#3521]
`Encoding::CompatibilityError: incompatible encodings: UTF-8 and ASCII-8BIT`

```
  from active_record/callbacks.rb:306:in `block in _create_record'
  from active_record/attribute_methods/dirty.rb:132:in `_create_record'
  from active_record/locking/optimistic.rb:75:in `_create_record'
  from active_record/counter_cache.rb:139:in `_create_record'
  from active_record/persistence.rb:524:in `_create_record'
  from active_record/relation.rb:64:in `insert'
  from active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
  from active_record/connection_adapters/abstract/database_statements.rb:107:in `insert'
  from active_record/connection_adapters/abstract/database_statements.rb:13:in `to_sql'
  from active_record/connection_adapters/abstract_adapter.rb:116:in `compile'
  from arel/collectors/bind.rb:32:in `compile'
  from org/jruby/RubyArray.java:1789:in `join'
  from org/jruby/RubyArray.java:1783:in `join'
```

I've narrowed the issue down and I'm not sure if this should be opened here or under arel.

I'm using arel 6.0.3 and Jruby 9.0.4.0 with rails 4.2.5

It looks like arel is building an insert statement with some UTF-8 characters and it fails with this exception when it tries to join it at https://github.com/rails/arel/blob/master/lib/arel/collectors/bind.rb#L32
I'm guessing that some of the strings are generated as ASCII and that's what causes the exception.

**Comment by kares** [comment]
is this still relevant? if so we would need a way of reproducing - currently I do not see a way to proceed.

**Comment by nadavshatz** [comment]
@kares It is.
I'll try and look into an easy way to reproduce.
Cheers

**Comment by nadavshatz** [comment]
very stale
