### ISSUE TITLE
BigDecimal.new("5-6").to_i returns 0 on 9k where 1.7 and MRI returns 5

### ISSUE THREAD

**Issue by kml** [jruby/jruby#3527]
```
2.2.3p173
>> BigDecimal.new("5-6").to_i
=> 5

1.7.19
>> BigDecimal.new("5-6").to_i
=> 5

9.0.4.0
>> BigDecimal.new("5-6").to_i
=> 0
```

**Comment by kml** [comment]
Probably same as https://github.com/jruby/jruby/issues/3504 https://github.com/jruby/jruby/issues/3242
If so please close.

**Comment by kares** [comment]
not really, this one is probably a regression since: https://github.com/jruby/jruby/commit/ae7c19773894f7503e9265e362c3ca091530fb97
