### ISSUE TITLE
warning: io/console not supported; tty will not be manipulated

### ISSUE THREAD

**Issue by kowal** [jruby/jruby#354]
I know that http://jira.codehaus.org/browse/JRUBY-1608 is marked for 1.7.1 to be resolved. 

Just want to say that after upgrading from **1.7.0.RC2** to **1.7.0** I started to see this warning (in rake test and rails server):

```
io/console not supported; tty will not be manipulated
```

Nothing breaks in the app, just the warning.

``` bash
$ ruby -v
jruby 1.7.0 (1.9.3p203) 2012-10-22 ff1ebbe on Java HotSpot(TM) 64-Bit Server VM 1.6.0_34-b04 [linux-amd64]

# from console
$ stty
speed 38400 baud; line = 0;

# from irb
$ irb
jruby-1.7.0 :002 > `stty`
stty: standard input: Invalid argument
=> "" 
jruby-1.7.0 :002 > system("stty")
stty: standard input: Invalid argument
 => false
```

This works On MRI 1.9.3: 

``` bash
$ ruby -v
ruby 1.9.3p286 (2012-10-12 revision 37165) [x86_64-linux]

$ irb
1.9.3p286 :001 > `stty`
 => "speed 38400 baud; line = 0;\n" 
1.9.3p286 :002 > system('stty')
speed 38400 baud; line = 0;
 => true 
```

This is specific to 'stty', other shell commands/programs works fine from _system_ or backticks calls.

**Comment by perlun** [comment]
I'm seeing this now with JRuby 1.7 on Windows. Java 8.

**Comment by perlun** [comment]
(ah, nvm - I noticed it was never marked as finished on Windows)
