### ISSUE TITLE
Warning: setEvalType unimplemented in org.jruby.RubySymbol$1

### ISSUE THREAD

**Issue by ginkel** [jruby/jruby#3541]
jruby 9.0.4.0 (2.2.2) 2015-11-17 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [linux-amd64]

When running our RSpec tests under JRuby 9k, some tests emit the following warning:

    setEvalType unimplemented in org.jruby.RubySymbol$1

I haven't yet been able to pinpoint what is actually leading to `setEvalType` being called as it seems to be impossible to monkey-patch `org.jruby.runtime.BlockBody` where this method is defined (monkey-patching seems to have no effect at all). Any hints how to effectively debug this are much appreciated!

**Comment by mkristian** [comment]
I did see this recently for the first time but as it did not give any tests failures we decided to ignore it. so is it more then the warning message with you ?

**Comment by ginkel** [comment]
It's just a warning message, but it clutters STDERR and gets annoying. ;-) I'd like to understand what is causing this so that it can eventually be fixed.

**Comment by obfuscoder** [comment]
I would love to get rid of this warning

**Comment by kares** [comment]
what would likely speed this up being resolved is to have a reproduction piece of rspec suite or whatever ...

**Comment by headius** [comment]
Trivial reproduction:

```ruby
def foo; end
instance_eval &:foo
```

The problem is that the proc created for `:foo` does not have a typical Ruby block binding, so when we try to force it into an eval mode it doesn't mean anything. I'll have a look.

**Comment by headius** [comment]
I think this warning might have been added during 9k dev just for us to see what blocks were not honoring evalType. I think it's safe to just remove the warning and/or make the method abstract and force all blocks to decide if evalType means anything.
