### ISSUE TITLE
[Truffle] Fix remaining ActiveSupport tests

### ISSUE THREAD

**Issue by pitr-ch** [jruby/jruby#3543]
- [x] ~~03~~ 02 kernel test (will silence any $stdout output rendering rest of the test unusable) @pitr-ch
- [x] 12 Ropes related errors @nirvdrum 
- [x] 01 LoadPathsTest#test_uniq_load_paths (seems like an environment issue, I see doubled path from 
RUBYLIB coming from rbenv)
- [x] 21 Time class related issues @pitr-ch
- [x] 01 FileStoreTest#test_two_classes_autoloading (autoload constant or marshall related)
- [x] 02 ModuleTest (probably backtrace format) @pitr-ch
- [x] 10 OpenSSL (OpenSSL stubs are not complete for AS tests) @pitr-ch
- [x] 02 ActiveSupport::NumberHelper::NumberHelperTest#test_to_rounded* (something to do with Rational?) @chrisseaton
- [x] 01 NumericExtFormattingTest#test_to_s__rounded__with_significant_digits @chrisseaton
- [x] 01 DurationTest#test_eql Fixnum#eql? (uses == which is called in reverse order and returns false positive) @pitr-ch
- [x] 03 gzib @chrisseaton 
- [x] 04 Multibyte @nirvdrum 
- [x] 01 OrderedHashTest#test_select (Hash#map iterates only keys, bad block arguments)

**Comment by chrisseaton** [comment]
I think the zlib stuff is fixed now as I can't see it in your latest gist.

**Comment by pitr-ch** [comment]
yep, zlib looks fine, OrderedHashTest#test_select was also fixed

**Comment by chrisseaton** [comment]
Not listed in this issue: I'm also seeing

```
  1) Failure:
LoadPathsTest#test_uniq_load_paths [/Users/chrisseaton/Documents/ruby/rails/activesupport/test/load_paths_test.rb:14]:
{"/Users/chrisseaton/Documents/ruby/rails/activesupport/.jruby+truffle_bundle/jruby+truffle/2.2.0/bundler/gems/qu-d098e2657c92/lib"=>3}
```

**Comment by pitr-ch** [comment]
The list and gist are updated.
