### ISSUE TITLE
[Truffle] Fix remaining language specs

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#3549]
- [x] predefined/data
- [x] regexp/character_classes
- [x] regexp/modifiers
- [x] block
- [x] break
- [x] case
- [x] class
- [x] constants
- [x] def
- [x] encoding
- [x] file
- [x] lambda
- [x] method
- [x] predefined
- [x] send
- [x] super
- [x] variables

**Comment by eregon** [comment]
* I did the last `break` spec.
* `constants` specs all pass. There are tags, but it's only in 2.3 and we are not targeting that Ruby version yet.
* `break` needs a "frame on stack marker" technique to work most likely, like in SOM, so we can detect we should not throw the BreakException when the frame is no longer on the stack. And likely it's better to avoid this when we can detect statically it cannot happen.
* `def` might be a bit tricky, I'll take a look at it.
* The rest seems related to bugs/missing handling in the translator with masgn and other. Not very hard, just use `bin/ast` and breakpoint in the translator to see structure. `setRHS` and `translateDummyAssignment` might help to build assignments nodes with proper RHS.

**Comment by chrisseaton** [comment]
> constants specs all pass. There are tags, but it's only in 2.3 and we are not targeting that Ruby version yet.

If we can clear 2.3 tags that would be good. If we can get to zero tags then that's better than any other implementation isn't it?

**Comment by eregon** [comment]
Indeed, only MRI passes all of RubySpec currently.
I have some fix for that 2.3 constant change, but it's not trivial so I'd rather focus on 2.2 compat first (also 2.3 is still a bit of a moving target for some stuff).

**Comment by chrisseaton** [comment]
The last character classes spec is blocked by https://github.com/jruby/jcodings/issues/13.

**Comment by chrisseaton** [comment]
Last last regex modifiers spec is blocked by https://github.com/jruby/joni/issues/13

**Comment by chrisseaton** [comment]
I can't see how to implement `Global variable $0 actually sets the program name`. This modifies `argv[0]`, which we could do if only we could get the address of it.

**Comment by chrisseaton** [comment]
I've figured out assignment of `$0` on Mac. Still not idea for Linux. Note that `prctl` won't cut it as it's limited to 16 bytes.

**Comment by eregon** [comment]
Truncating for `$0` might be OK, some OS only support in-place modifications of argv[0] I think.
`Process.setproctitle` also exists to set the process title (and it's also the name of a system call).
In MRI it's implemented in https://github.com/ruby/ruby/blob/trunk/missing/setproctitle.c for OS without `setproctitle`.

**Comment by chrisseaton** [comment]
Yes, but the key thing we're missing is the value of `argv`. I can't find any way to do that on Linux.

**Comment by eregon** [comment]
For reading it?

**Comment by chrisseaton** [comment]
Well, indirecting it in order to write to it, yeah.

**Comment by headius** [comment]
I looked into the argv approach too. It doesn't appear that OpenJDK saves
the reference anywhere so there's no way to get at it even under the
covers. It would require a patch for the JVM itself.
