### ISSUE TITLE
Warning "io/console not supported; tty will not be manipulated" occurs again on 1.7.23

### ISSUE THREAD

**Issue by rovf** [jruby/jruby#3550]
Using: jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15 +jit [Windows 7-amd64]

A related issue, #1614, was closed on the grounds, that it was finally fixed (for Windows).

At least in JRuby 1.7.23, installed from 

https://s3.amazonaws.com/jruby.org/downloads/1.7.23/jruby_windows_x64_1_7_23.exe

the warning still occurs, when I do a 

  jruby -c FILENAME

**Comment by rjattrill** [comment]
Yes - I observe this with 1.7.22 on Windows but not 1.7.16.1


C:\Users\rattrill>jruby -v
jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15 +jit [Windows 7-amd64]

C:\opt\jruby-1.7.16.1\bin>jruby -v
jruby 1.7.16.1 (1.9.3p392) 2014-10-28 4e93f31 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15 +jit [Windows 7-amd64]

**Comment by psuzzi** [comment]
I get the same error in Windows 10, with ruby 2.3.3 (64bit)

ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]

**Comment by kares** [comment]
@psuzzi well we can't do much about that on JRuby's end :) ... report with Ruby!

**Comment by enebo** [comment]
@kares I think he might be saying we match MRI behavior?

**Comment by psuzzi** [comment]
Sorry, my bad. This IS about JRuby, but I wrongly reported the version of ruby. 

Here you can see a pastebin for the error: http://pastebin.com/Di6V9hAK

**Comment by kares** [comment]
and what would the version of JRuby (used by Gradle's asciidoctor) be than :) ? if you have any hints ...

**Comment by fap-** [comment]
From my understanding, gradle asciidoctor plugin uses asciidoctorj.
Newest version of asciidoctorj (1.5.4) uses jruby 1.7.26.
https://github.com/asciidoctor/asciidoctorj/blob/master/build.gradle#L37

But the gradle plugin is using asciidoctorj 1.5.3.2
 https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/development/build.gradle#L48
It seems like they ended up using jruby 1.7.21 for this version?
https://github.com/asciidoctor/asciidoctorj/issues/401

**Comment by kares** [comment]
thanks @fap- ... @psuzzi please try the latest version (which should be 1.5.4) as this has been resolved around 1.7.24 thus 1.5.3 might not have the desired JRuby version (and would still warn) !
