### ISSUE TITLE
jdk9 produces warning on launcher

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#3563]
https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyInstanceConfig.java#L1867

falls back to java 1.5 mode for jdk9

**Comment by kares** [comment]
yes cause its **9.0** now, right?

**Comment by mkristian** [comment]
the output is
```
unsupported Java version "9", defaulting to 1.5
```
so with jdk9 (both oracle and openjdk) it is **9** and not **1.9**
