### ISSUE TITLE
[2.3] Missing <<~ heredoc form

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3565]
From MRI 2.3 test suite:

```
SyntaxError: /Users/headius/projects/jruby/test/mri/ruby/test_symbol.rb:168: syntax error, unexpected tLSHFT
    assert_separately([], <<~"end;", timeout: 1) # do
```

**Comment by enebo** [comment]
[master f568b8d] Fix dstr-laden dedents?  Makes all MRI tests pass...It is a little different than MRI in that we compare source line vs wrap in extra arraynodes but I think it is the same?  We shall see...
