### ISSUE TITLE
**kwd, call(**kwd) does not behave like MRI.

### ISSUE THREAD

**Issue by envygeeks** [jruby/jruby#3572]
The following was discovered through RSpec Mocks and I'm cross posting it just in-case.  Given the following code:

```
allow(described_class).to receive(:new).and_wrap_original do |method, *args, **kwd|
  kwd[:root] = true unless kwd.key?(:root) || kwd.key?(:root_metadata)
  method.call(*args, **kwd)
end
```

The method being wrapped never receives the kwd, this was discovered when our specs started failing on JRuby when we started defaulting to reduce duplication in our specs, which ultimately was dumb anyways but it still surfaced an inconsistency.

RSpec Mocks Ticket:  https://github.com/rspec/rspec-mocks/issues/1045

**Comment by enebo** [comment]
This was no doubt fixed a very long time ago but I used this snippet to verify:

```ruby
define_method(:foo) do |method, *args, **kwd|
  kwd[:root] = true unless kwd.key?(:root) || kwd.key?(:root_metadata)
  method.call(*args, **kwd)
end

foo(proc do |*b, **k|
  p b, k
end)
```

I would be incredibly surprised if we do not already have a test/spec on this between the testing suites so closing.  I will close against next release so people can notice this was fixed in release notes.
