### ISSUE TITLE
autoload + const_defined? inconsistent with Ruby 2.0+

### ISSUE THREAD

**Issue by envygeeks** [jruby/jruby#3574]
On Ruby 2.0+ `const_defined?` with Autoload does not load a constant, but JRuby does load said constant.  While it helped me surface a bug in my source, it also helped me surface an inconsistency with JRuby.

**Comment by kares** [comment]
expected to be fixed with https://github.com/jruby/jruby/commit/b216c5d5d5f532f75d6cf92b3098b6d42bbba7c4 ... MRI's test-suite is testing this and is un-excluded at abbe9255a512394710b3a0a137f2835598b47f3f

**Comment by envygeeks** [comment]
Awesome, thanks!
