### ISSUE TITLE
jruby-9.0.2.0+graal-dev fails to install on OSX.

### ISSUE THREAD

**Issue by vjdhama** [jruby/jruby#3578]
I was trying to install `jruby-9.0.2.0+graal-dev` using rbenv but it fails with following error.

```
Downloading jruby-dist-9.0.2.0-SNAPSHOT+graal-macosx-x86_64-bin.tar.gz...
-> http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-9.0.2.0-SNAPSHOT+graal-macosx-x86_64-bin.tar.gz
/usr/local/bin/ruby-build: line 207: pushd: jruby-9.0.2.0-SNAPSHOT: No such file or directory

BUILD FAILED (OS X 10.10.5 using ruby-build 20151230)
```

**Comment by chrisseaton** [comment]
Yes these files seem to have been corrupted by something - they're empty. I'lll look into this.

In the mean time, I'd recommend either using jruby-9.0.4.0 and running with http://lafo.ssw.uni-linz.ac.at/graalvm/openjdk-8-graalvm-b132-macosx-x86_64-0.7.tar.gz manually (set `JAVACMD`), or build from source and use the GraalVM https://github.com/jruby/jruby/wiki/Downloading-GraalVM.

Let me know if you need any help with that.

**Comment by chrisseaton** [comment]
We've restored the file - can you try again?

**Comment by bitfurry** [comment]
it's working now. I tried. @chrisseaton

**Comment by vjdhama** [comment]
Worked for me too. Thanks.
