### ISSUE TITLE
Open3.popen3 in JRuby 1.7 behaves differently than JRuby 9 and MRI

### ISSUE THREAD

**Issue by chingc** [jruby/jruby#3580]
I'm having the following issue in the JRuby 1.7.23 in which the code snippet below will display `hello world` with the `system` call, but `$hi` when using `popen3`.  In JRuby 9.0.4.0 and MRI Ruby, both calls display `hello world` as expected.

I'd love to update to the 9 series, but my current development environment requires 1.7 and updating is unlikely to happen swiftly.

```ruby
require "open3"

system( { "hi" => "hello world" }, "echo $hi" )

Open3.popen3( { "hi" => "hello world" }, "echo $hi" ) do | i, o, e |
    puts o.read
end
```

**Comment by headius** [comment]
Unfortunately the popen3 in JRuby 9 works like MRI because a tremendous amount of work went into making subprocess logic do the right thing. The logic in 1.7 is built entirely atop the JDK's process APIs, which are severely lacking.

This might not be an easy item to fix, I'm afraid.

**Comment by chingc** [comment]
Ahh, sounds like I'll have to find some other way to resolve my issue.  Thanks for the info @headius.
