### ISSUE TITLE
1.7.x define_singleton_method fails in fascinating ways in odd situations

### ISSUE THREAD

**Issue by andrewvc** [jruby/jruby#3582]
This change ( https://github.com/elastic/logstash/commit/a0819e2ead311c26fae723d3a23ac8009b2f9e46 ) in Logstash is a workaround for a bizarre JRuby 1.7.x bug. This bug is not present in JRuby 9.x. 

The synopsis is that sometimes `define_singleton_method(:mymethod, method(:mymethodalt))` fails where `define_singleton_method(:mymethod, lambda { mymethodalt })` does not.

For reasons that are not clear, when running the specs for https://github.com/logstash-plugins/logstash-output-file against logstash in the preceding commit preceding https://github.com/elastic/logstash/commit/a0819e2ead311c26fae723d3a23ac8009b2f9e46 a  `TypeError: can't bind singleton method to a different class` exception would be raised. 

The funky thing is that not only was this not a subclass of `OutputDelegator`, but there are no subclasses defined anywhere for it. Weird stuff!

**Comment by kares** [comment]
since 1.7.x is EOL and logstash is updating to 9K I think this can be closed. esp. since there's a work-around.
