### ISSUE TITLE
IO.copy_stream leaves opened files in ObjectSpace

### ISSUE THREAD

**Issue by scarfacedeb** [jruby/jruby#3590]
It seems to me that JRuby deviates from MRI implementation of `IO.copy_stream`:

To demonstrate run the following snippet in MRI and jruby: 
```ruby
puts ObjectSpace.each_object(File).reject(&:closed?).count # == 1
IO.copy_stream "README.md", "/tmp/readme"
puts ObjectSpace.each_object(File).reject(&:closed?).count # == 1 in MRI, == 3 in jruby
```

In MRI `IO.copy_stream "README.md", "/tmp/readme"` doesn't leave opened files in the ObjectSpace.

But in jruby, `ObjectSpace.each_object(File).reject(&:closed?)` would include 2 extra implicitly created file descriptors from `IO.copy_stream`.

It is an expected behaviour?

Relevant refile/refile issue: https://github.com/refile/refile/issues/414

**Comment by headius** [comment]
Weird. And even weirder that you have a related issue.

**Comment by headius** [comment]
Tell ya what...I'll at least make sure that streams opened by IO#copy_stream get closed when it's done. They would close due to finalization, so this wasn't really a leak...but it was bad form.

**Comment by jowl** [comment]
FYI: This also solves another issue I stumbled upon using JRuby 1.7.19, which was that the `RubyIO` instances could be GC'd during `#copy_stream`, since they weren't referenced after getting their channels, which caused their finalizers to run and close them. This error appeared as
```
Errno::EBADF: Bad file descriptor - Bad file descriptor
  copy_stream at org/jruby/RubyIO.java:4694
```
