### ISSUE TITLE
Jruby 9040 matchdata incorrect

### ISSUE THREAD

**Issue by rinkevichjm** [jruby/jruby#3598]
m="at\nM.S. degree 2004\NM.S. CS 2005\n".match /(M\.S\.)/
should produce
m.offset 0
[3,7]
m.offset 1
[20,24] instead it repeats [3,7]

**Comment by donv** [comment]
Have you verified with MRI?  Using MRI 2.2.2, I get [3,7] and [3,7].

**Comment by rinkevichjm** [comment]
I didn't have MRI installed on it but compared with the Rubular web page which show both expressions as the matches. MRI docs say it should work as I wrote it.

**Comment by kares** [comment]
confirming @donv's observrations ... MRI 2.2.3 as well as 2.3.0 both behave as they "should not" : 
```
2.2.3 :001 > m="at\nM.S. degree 2004\NM.S. CS 2005\n".match /(M.S.)/
 => #<MatchData "M.S." 1:"M.S."> 
2.2.3 :002 > m.offset 0
 => [3, 7] 
2.2.3 :003 > m.offset 1
 => [3, 7] 
2.2.3 :004 > m.offset 2
IndexError: index 2 out of matches
	from (irb):4:in `offset'
	from (irb):4
	from /opt/local/rvm/rubies/ruby-2.2.3/bin/irb:11:in `<main>'
2.2.3 :005 > exit

2.3.0 :001 > m="at\nM.S. degree 2004\NM.S. CS 2005\n".match /(M.S.)/
 => #<MatchData "M.S." 1:"M.S."> 
2.3.0 :002 > m.offset 0
 => [3, 7] 
2.3.0 :003 > m.offset 1
 => [3, 7] 
```
@rinkevichjm you should not assume Rubular being right but if you feel this is buggy please report to MRI first to confirm its an actual bug and not a :icecream: feature ... for now closing as Invalid.
