### ISSUE TITLE
Windows: jruby appear to pass unknown java option when JRUBY_HOME is set

### ISSUE THREAD

**Issue by rob99** [jruby/jruby#3610]
C:\scripts>set JRUBY_HOME=c:\downloads\jruby-9.0.4.0\
    C:\scripts>jruby -v
    Usage: java [-options] class [args...]
               (to execute a class)
       or  java [-options] -jar jarfile [args...]
               (to execute a jar file)
    where options include:
        -d32          use a 32-bit data model if available
        -d64          use a 64-bit data model if available

snip...

    C:\scripts>set JRUBY_HOME=
    C:\NotBackedUp\brownr12\scripts>jruby -v
    jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 24.71-b01 on 1.7.0_71-b14 +jit [Windows 7-amd64]

**Comment by headius** [comment]
Looks like it's passing the -v to the JVM rather than passing it into JRuby's argument processing.

**Comment by headius** [comment]
I was able to reproduce this with our Windows installer:

```
C:\Users\headius                                                                                               
λ echo %JRUBY_HOME%                                                                                            
%JRUBY_HOME%                                                                                                   
                                                                                                               
C:\Users\headius                                                                                               
λ jruby -v                                                                                                     
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 +jit [mswin32-x86_64]                                                                                                    
                                                                                                               
C:\Users\headius                                                                                               
λ set JRUBY_HOME=C:\jruby-9.1.2.0\                                                                             
                                                                                                               
C:\Users\headius                                                                                               
λ jruby -v                                                                                                     
Usage: java [-options] class [args...]                                                                         
```

And it does appear to be the executable, rather than the batch file. I guess it's simply a bug in the Windows native launcher.

**Comment by enebo** [comment]
@headius try removing the last backslash.  I think we have run into this one before...

**Comment by headius** [comment]
@enebo Ah, that does work. Do you know why having a trailing slash fails? It's very unexpected.

**Comment by headius** [comment]
I've moved this issue to jruby-launcher and explained the basic problem and workaround at jruby/jruby-launcher#10.
