### ISSUE TITLE
jruby -i Edit files in place behaves inconsistent with MRI

### ISSUE THREAD

**Issue by crccw** [jruby/jruby#3617]
Manifest.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="#testPackage#"
      android:versionCode="3"
      android:versionName="0.3.0">
```

and the command is:

```
ruby -pi.back -e "gsub(/#testPackage#/,'foo')" Manifest.xml
```

With MRI, `#testPackage#` gets replaced successfully.

With JRuby 9.0.4.0, nothing changes.

I'm using JRuby 9.0.4.0 with calabash-android. When executing `calabash-android build <apk>`,  this problem seems to jeopardize it.

Thoughts?

**Comment by enebo** [comment]
This was fixed some long time in the past but marking against something so someone can notice it has been fixed.
