### ISSUE TITLE
JRUBY_OPTS gives misleading warning

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#3620]
Either I don't understand how `JRUBY_OPTS` is supposed to work, or it gives misleading warnings:

```
$ JRUBY_OPTS='-J-ea' bin/jruby -e 1
warning: -J-ea argument ignored (launched in same VM?)
```

We haven't launched a sub-JRuby there, and I think the argument isn't ignored:

```
$ JRUBY_OPTS='-J-version' bin/jruby -e 1
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```

**Comment by enebo** [comment]
I don't know the answer to your question but I can say why it is a warning...ArgumentProcessor is seeing this and you are already running the JVM so it is trying to point out we cannot enable ea at that point.  I wonder if in the past we had not passed JRUBY_OPTS env into the JVM (but appropriately setting up the Java command-line) and somenoe realized not doing that would break sub-invokes of JRuby or something like that?

**Comment by chrisseaton** [comment]
At the very least the warning is simply wrong; the argument wasn't ignored.

**Comment by enebo** [comment]
Yeah.  So if we cannot tell if assertionas are enabled progrmatically we should probably disable the warning altogether.  I think at one time this warning worked as expected but it appears like it must not any more.
