### ISSUE TITLE
SystemCallError: Unknown error - Unknown Error (0) - .gitignore

### ISSUE THREAD

**Issue by atambo** [jruby/jruby#3621]
IBM JDK 8 on redhat 6.7 I end up with this error:

```
SystemCallError: Unknown error - Unknown Error (0) - .gitignore
                   stat at org/jruby/RubyFile.java:902
   validate_permissions at classpath:/META-INF/jruby.home/lib/ruby/shared/rubygems/specification.rb:2716
```

See full error here: https://gist.github.com/atambo/8b7809f08a6f7b0421c9

Looks like stat is having problems on IBM JDK? Could this be related to https://github.com/jruby/jruby/issues/3505? @enebo 

Anything I can do to try to narrow this down?

**Comment by atambo** [comment]
So the line that is blowing up is this one:
https://github.com/rubygems/rubygems/blob/v2.4.8/lib/rubygems/specification.rb#L2716

I was able to run the same code in irb on the server like so:
```
./java -jar jruby-complete-1.7.24.jar -e 'load "META-INF/jruby.home/bin/jirb"'
irb(main):001:0> File.stat("/opt/ibm/WEX/AppBuilder/wlp/usr/servers/AppBuilder/apps/AppBuilder/javascripts/.gitignore").mode & 0444 == 0444
=> true
```
and it works fine. Any ideas on how I can reproduce this without needing a full warbled rails application?

**Comment by enebo** [comment]
@atambo This problem is not on windows and unfortunately those issue(s) never touched anything outside of windows.  I wonder if jnr-posix native is really loading?  -Xnative.verbose=true should tell you if it loaded or something fell back to non-native mode.  Even so if this is happening non-native it seems we have an issue retrieving the mode properly.

**Comment by atambo** [comment]
When I run:

```
./java -Djruby.native.verbose=true -jar jruby-complete-1.7.24.jar -e 'load "META-INF/jruby.home/bin/jirb"'
```

I get:

```
Successfully loaded native POSIX impl.
```

So it looks like the native stuff is loading. I'm still not able to reproduce the issue outside of a warbled application :(. Let me try inside of the warbled application.

**Comment by atambo** [comment]
I haven't been able to reproduce this problem after I fixed some other unrelated issues...I'm going to close this for now.

**Comment by splashing-atom** [comment]
For posterity, I resolved this issue by removing 'noexec' flag from a tmpdir mount.
