### ISSUE TITLE
Process#spawn error when redirecting error to stdout (jruby 9.0.4.0)

### ISSUE THREAD

**Issue by vassilios** [jruby/jruby#3627]
Redirecting stderr to stdout in spawn gives an exception. 

    $ jirb
    irb(main):001:0> Process.spawn('ls -al',:err => :out)
    Java::JavaLang::ArrayIndexOutOfBoundsException: -2
	from org.jruby.util.io.PopenExecutor.run_exec_dup2(PopenExecutor.java:789)
	from org.jruby.util.io.PopenExecutor.execargRunOptions(PopenExecutor.java:986)
	from org.jruby.util.io.PopenExecutor.spawnProcess(PopenExecutor.java:113)
	from org.jruby.util.io.PopenExecutor.spawn(PopenExecutor.java:75)
	from org.jruby.RubyProcess.spawn(RubyProcess.java:1296)
	from             

Same thing happens if you use STDERR => STDOUT or 2 => 1 (instead of :err => :out) as shown in http://ruby-doc.org/core-2.2.2/Process.html#method-c-spawn

This was run on:
    $ jruby -v
    jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa OpenJDK 64-Bit Server VM 24.91-b01 on 1.7.0_91-b02 +jit [linux-amd64]

**Comment by headius** [comment]
It appeared to work ok for me on 9.1:
```
$ jruby -e "Process.spawn('ls -al',:err => :out)"
total 490264
drwxr-xr-x   61 headius  staff       2074 Mar  4 11:57 .
drwxr-xr-x  144 headius  staff       4896 Feb 25 15:18 ..
drwxr-xr-x   18 headius  staff        612 Mar  4 12:06 .git
```
If it's still broken for you with a 9.1 snapshot from http://ci.jruby.org, reopen this issue.
