### ISSUE TITLE
DEAD: marking instr dead!!

### ISSUE THREAD

**Issue by dgasson** [jruby/jruby#3636]
I've been generating XML using nokogiri and jruby.  On occasion, to stdout is printed the following text: "DEAD: marking instr dead!!".  I can actually see where that is being generated in the jruby source (line 85 of LocalOptimizationPass.java, to be precise), but I don't know enough about jruby internals to determine whether this is something to be concerned about, or whether the `System.out.println` line was left in accidentally.  I do notice the other` System.out.println` calls are commented out so perhaps that is the case?  FWIW, I've seen the behaviour in both 9.0.4.0 and 9.0.5.0.

**Comment by enebo** [comment]
I fixed this about 30 minutes after you came on the channel.

**Comment by dgasson** [comment]
LOL, thanks enebo.
