### ISSUE TITLE
Dir::Tmpname.make_tmpname inconsistent with Ruby 2.2+

### ISSUE THREAD

**Issue by envygeeks** [jruby/jruby#3646]
In Ruby 2.1 you had to do:

```ruby
Dir::Tmpname.make_tmpname(["prefix", ""], nil)
Dir::Tmpname.make_tmpname(["prefix", ".ext"], nil)
Dir::Tmpname.make_tmpname(["", ".ext"], nil)
```

In 2.2+ the second value of the array is optional so you can do:

```ruby
Dir::Tmpname.make_tmpname(["prefix"], nil)
```

if you do not wish to have an extension.

**Comment by headius** [comment]
Hmm...well Tmpname comes from tmpdir.rb which is just stdlib. I'll try to figure why we differ here.
