### ISSUE TITLE
Implement Process::setproctitle

### ISSUE THREAD

**Issue by donv** [jruby/jruby#3658]
Trying to set process title gives an error:

```
# jruby -ve "Process.setproctitle('myapp')"
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.72-b15 on 1.8.0_72-b15 +jit [linux-amd64]
NoMethodError: undefined method `setproctitle' for Process:Module
  <top> at -e:1
```

It should either be implemented or NOOP with a warning.

**Comment by headius** [comment]
I'll mark it as not implemented. It's difficult to implement across platforms even from C, and from Java it's going to be nearly impossible.

**Comment by headius** [comment]
It looks like MRI marks it as noop and doesn't report an error on platforms where it is not supported.
