### ISSUE TITLE
[Truffle] instance_eval should allow three arguments

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#3677]
Example code
```
class Test
end

code = <<-eos
  def blah?
    true
  end
eos

Test.instance_eval(code, "blah.rb", 30)
puts Test.blah?
```
Expected 
`true`

Actual
```
/Users/brandonfish/Documents/jruby-patches/ineval.rb:11:in `instance_eval': wrong number of arguments (3 for 0) (ArgumentError)
	from /Users/brandonfish/Documents/jruby-patches/ineval.rb:11:in `<main>'
```

Used in bundler.  I think the second and third arguments could be ignored for usage in error reporting for now if too difficult to implement.

**Comment by bjfish** [comment]
This appears to be fixed. Maybe at this commit: https://github.com/jruby/jruby/commit/72f116a18c67249fc57a5d9c1d4ff3d253c3ff91

**Comment by pitr-ch** [comment]
yeah, sorry I missed the issue.
