### ISSUE TITLE
[Truffle] $? Dollar question mark should hold last exit status after backtick command

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#3678]
### Environment

Truffle

```
`git --version`
puts $?.inspect
```
### Expected Behavior

```
#<Process::Status: pid 52128 exit 0>
```

### Actual Behavior

```
nil
```

This is used in bundler.

**Comment by chrisseaton** [comment]
Fixed somewhat in 9394eb1c65afcb549dc229e8af34563b47784c42, but we don't have the PID. Hopefully it's enough. We should perhaps implement in Ruby instead.
