### ISSUE TITLE
[Truffle] class_eval should allow negative line number

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#3683]
### Environment
Truffle
```
class First
end
First.class_eval("def hello; puts 'hello'; end", "test.rb", -10)
n = First.new
n.hello
```

### Expected Behavior
```
$ruby ceval.rb 
hello
```
Found in tilt which is used sinatra for erb templating

### Actual Behavior
```
$ruby ceval.rb 
ceval.rb:3:in `class_eval': internal implementation error - NegativeArraySizeException null org.jruby.truffle.core.module.ModuleNodes$ClassEvalNode.classEvalSource(ModuleNodes.java:673) (RubyTruffleError)
	from ceval.rb:3:in `<main>'
```

**Comment by chrisseaton** [comment]
Ha ha how did you find that one?

**Comment by bjfish** [comment]
@chrisseaton I was trying the erb functionality in sinatra:
Rubygems require and gem methods appear to work pretty well when enabled. So, I could just run:
```
GEM_HOME=/path/to/gem/home gem install sinatra # using ruby 2
GEM_HOME=/path/to/gem/home ruby sinatra_app.rb # using truffle
```

**Comment by chrisseaton** [comment]
What did you have to do to enable it? Remove our `gem` shim? What about the `require` shim that they need? How was that enabled?

**Comment by bjfish** [comment]
@chrisseaton See this patch: https://gist.github.com/bjfish/840c11b171450642bdab

- Uncommented the Kernel gem and require methods in rubygems.rb
- Removed the existing Kernel gem shim
- Modified the psych loading code because the caller changes
- Create a io/console.rb file to shim when this is required by thor

With these changes, I think there is only one MRI regression. It might regress the way we test activesupport though.

**Comment by bjfish** [comment]
This has been fixed for a while.
