### ISSUE TITLE
[Truffle] Error flattening array in Graal

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#3684]
### Environment
Graal 0.10
```
2000.times { |i|
[["~> 4.3"]].flatten
}
puts "Done"
```

### Expected Behavior
`Done`
in Truffle (no Graal) and JRuby

### Actual Behavior
```
JAVACMD=/GraalVM-0.10/jre/bin/javao ../jruby/bin/jruby -X+T -Xtruffle.exceptions.print_java=true flatten.rb 
/flatten.rb:2:in `recursively_flatten': tried to flatten recursive array (ArgumentError)
	from /flatten.rb:2:in `flatten'
	from /flatten.rb:2:in `block in <main>'
	from /flatten.rb:1:in `times'
	from /flatten.rb:1:in `<main>'
```

Used in rubygems.

**Comment by eregon** [comment]
`Graal 0.1` ? 0.10 maybe?

**Comment by bjfish** [comment]
@eregon Yes, I meant `0.10`

**Comment by nirvdrum** [comment]
I can't reproduce this with df26e2cdafdb5e8f686820184ac3d16d5ed97479 on GraalVM 0.11.

**Comment by bjfish** [comment]
@nirvdrum I'll close it then.

**Comment by nirvdrum** [comment]
No worries. I left it open just to make sure I wasn't doing something wrong.
