### ISSUE TITLE
Significant increase in memory use switching from 9.0.1.0 to 9.1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by donv** [jruby/jruby#3690]
jruby 9.0.1.0 (2.2.2) 2015-09-02 583f336 Java HotSpot(TM) 64-Bit Server VM 25.72-b15 on 1.8.0_72-b15 +jit [linux-amd64]

jruby 9.1.0.0-SNAPSHOT (2.2.3) 2016-02-17 482c35a Java HotSpot(TM) 64-Bit Server VM 25.72-b15 on 1.8.0_72-b15 +jit [linux-amd64]

CentOS release 5.11 (Final)
Linux 2.6.18-406.el5 #1 SMP Tue Jun 2 17:25:57 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

Full Rails 4.2.5.1 environment with lots of gems :)

When switching from 9.0.1.0 to 9.1.0.0-SNAPSHOT memory use increases by about 20%.

I would expect memory use to be about the same as with JRuby 9.0.x.  Give me a hint of how to profile and give more information.

**Comment by enebo** [comment]
@donv you could use jvisualvm to figure out what there happens to be more of.  I would guess most likely it is org.jruby.ir.* types.  comparing heaps from both versions will help.  

We do have a plan to be able to share instrs coming at some point in the future which should help on memory but I don't actually know why we are using more memory than in 9.0.0.0.

**Comment by donv** [comment]
Will do a heap dump and compare.

**Comment by kares** [comment]
believe this has been resolved by subsequent 9.1 releases ... @donv could you confirm please?

**Comment by headius** [comment]
There have been a number of memory improvements since 9.1 that could easily explain this, like the excessive creation of method handles or the infinite chaining of constant caches.

**Comment by donv** [comment]
Sorry for the late reply.  I think this issue is resolved.
