### ISSUE TITLE
jnr-ffi version inconsistency

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#3707]
We're using com.github.jnr:jnr-ffi:jar:2.0.7

https://github.com/jruby/jruby/blob/e283630670846704795e3cd339644a555b735a44/core/pom.rb#L50

But the latest version is 2.0.7-SNAPSHOT

https://github.com/jnr/jnr-ffi/blob/4a82c62872b7fcd0a6f2817c5af4db938e0ed994/pom.xml#L12

Was there a 2.0.7 release that maybe someone forgot to push to GitHub?

**Comment by enebo** [comment]
@chrisseaton whoops...I never pushed the pom.xml commit.  Pushed and updated to 2.0.8-SNAPSHOT.
