### ISSUE TITLE
Passing in command line arguments containing "%20n" causes jruby to abort with error "%n in writable segment detected"

### ISSUE THREAD

**Issue by ptepper** [jruby/jruby#3711]
### Environment
**Version:** jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 25.74-b02 on 1.8.0_74-b02 +jit [linux-amd64]

**OS & platform:**  Ubuntu 15.10 (GNU/Linux 4.2.0-27-generic x86_64))

### Expected Behavior

`jruby` should accept the command line arguments containing the substring "%20n" as a normal string. 

### Actual Behavior

Immediate failure and abort:
```
> jruby -S script.rb -a "Foo%20nar"
*** %n in writable segment detected ***
Aborted (core dumped)
```

The script contents can be anything, e.g. a script containing `puts "Hello, world!"` alone will trigger this behavior.

**Comment by Lan5432** [comment]
Could we recreate this on Windows command line? What should be "%20n" in the invocation?

**Comment by BanzaiMan** [comment]
I don't see this:

```sh-session
$ jruby -v                         
jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [darwin-x86_64]
$ cat script.rb                                                                                                                                                                   
puts "Hello, World!"
$ jruby -S script.rb -a "Foo%20nar"
Hello, World!
```

**Comment by Lan5432** [comment]
I also tried creating a file with that as a substring, and it wasn't a problem. But that's why I'm asking if Windows works. I will try it on KUbuntu eventually

**Comment by kares** [comment]
seems to happen on Linux, 9.0.5.0 is affected as well. but master seems to be doing fine already : 
```
$ bin/jruby -v
jruby 9.1.0.0-SNAPSHOT (2.3.0) 2016-03-08 dc21f62 Java HotSpot(TM) 64-Bit Server VM 24.72-b04 on 1.7.0_72-b14 +jit [linux-amd64]

$ bin/jruby -S script.rb -a "Foo%20nar"
jruby: No such file or directory -- script (LoadError)
```
