### ISSUE TITLE
RubyGems after 2.4.8 is broken on JRuby

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3718]
We're going to need to work with RG folks to get recent RG releases working on JRuby.

At a minimum we have:

* rubygems/rubygems#1541
* rubygems/rubygems#1534

We want to ship JRuby 9.1 and 1.7.25 soon with updated RubyGems, but for now we're stuck.

cc @tenderlove @indirect @segiddins

**Comment by segiddins** [comment]
As I commented on that issue, I have a fix that'll be ready really soon.

**Comment by headius** [comment]
All known issues with RubyGems were fixed as of 2.6.2, and we are running that version for 9.1 now.
