### ISSUE TITLE
Control-C doesn't do anything anymore when entering code in IRB

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby#3721]
In C-Ruby (and also in JRuby until recently), if you pressed Control-C in IRB while in the middle of writing a line of code, any code entered up until then wouldn't be evaluated, and you would be given a new line on which to enter code from scratch. Now, if you press Control-C in the middle of writing a line of code, its as if nothing happened. If you press Control-C and then enter, the code entered up until that point gets evaluated.

**Comment by headius** [comment]
@mohamedhafez Hmm, that's odd. I see the same result...the Control-C seems to be ignored.

**Comment by headius** [comment]
It doesn't seem like the trap is being installed correctly anymore.

**Comment by headius** [comment]
@mohamedhafez Can you provide info on your environment? OS/platform, JRuby version, etc.

**Comment by mohamedhafez** [comment]
I'm using jruby 9.0.4.0, and experiencing the issue on both Ubuntu 12.04 and OS X 10.11. Oh and I'm still using Java 7 on both.

**Comment by headius** [comment]
Strange...it appears to be doing a read inside our readline implementation (based on jline) and it does not wake up when the signal triggers an interrupt exception (RubyLex::TerminateLineInput). I'm going to try rb-readline and see if the behavior is better.

**Comment by headius** [comment]
For whatever reason I can't even get signals to register properly when I use rb-readline, so I'm abandoning that path for the moment.

Now I'm confused how this ever worked right. We have used jline as our readline impl for many years, and the logic for accepting input has not changed much during that time. The main thread is stuck in a blocking read operation underneath jline, which can't normally be interrupted.

The signal is handled by printing out `^C` and raising the exception I mention above. In MRI, this will interrupt the currently-blocked thread (main) and reset the prompt and lexer. In JRuby, signals are always handled in a separate dedicated thread, so this exception raise should not have ever propagated to the main thread.

**Comment by headius** [comment]
Hmm, I tried versions of JRuby 1.7 and 1.6 and they also show the same behavior, so it doesn't seem like this was working any time recently. Do you know of a version where it works?

**Comment by mohamedhafez** [comment]
So in jruby-1.7.21, doing a control-C will print ^C and a newline in the screen, but won't give you a new prompt the way C-Ruby does. HOWEVER: if you press enter after that point, the code you had entered *won't* be evaluated, and you'll get the new prompt. This is the way I remember it always being until Jruby 9000

**Comment by headius** [comment]
Ok, I think this stopped working in part because we started using native channels for stdio.

Here's 9.1.3.0 exhibiting the bad behavior:

```
[] ~/projects/jruby $ jirb -v
irb 0.9.6(09/06/30)

[] ~/projects/jruby $ jruby -v
jruby 9.1.3.0-SNAPSHOT (2.3.0) 2016-08-15 b8739c1 Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [darwin-x86_64]

[] ~/projects/jruby $ jirb
irb(main):001:0> asdf^C

NameError: undefined local variable or method `asdf' for main:Object
	from (irb):1:in `<eval>'
	from org/jruby/RubyKernel.java:994:in `eval'
	from org/jruby/RubyKernel.java:1295:in `loop'
	from org/jruby/RubyKernel.java:1114:in `catch'
	from org/jruby/RubyKernel.java:1114:in `catch'
	from /Users/headius/projects/jruby/bin/jirb:13:in `<main>'
```

Now here's 9.1.3.0 with native integration disabled, and it works like it used to:

```
[] ~/projects/jruby $ JRUBY_OPTS=-Xnative.enabled=false jirb
irb(main):001:0> ^C

irb(main):002:0> 
```

This could mean that because we're routing around readline, we're interfering with buffering that happens in the regular stdio streams from the JDK.

**Comment by headius** [comment]
I have a fix for jruby-readline that makes it use the same streams as JRuby itself. It appears to restore us basically to 1.7 behavior (there's a CR after the ^C below, as in 1.7):

```
[] ~/projects/jruby-readline $ jirb
irb(main):001:0> puts 'hello'
hello
=> nil
irb(main):002:0> asdf^C
irb(main):002:0>
```

I'll do some testing with this, but it seems good so far.

**Comment by headius** [comment]
I have pushed the jruby-readline fix to that repo and to JRuby. Please test master and make sure it works for all your IRB console needs.

Reopening until we fully release jruby-readline 1.1.

**Comment by headius** [comment]
@mkristian I could not figure out the right way to release jruby-readline-1.1. I tried the release plugin (`mvn release:prepare` etc) but it keeps trying to push to jruby/jruby rather than jruby/jruby-readline and I don't know why :-(

**Comment by headius** [comment]
OH, I found the readme :-) Trying it now.

**Comment by headius** [comment]
I could not get the release to go. It uploaded to Sonatype, but then failed to close/release due to source, javadoc, and pom checks failing.

@mkristian You're my only hope!

**Comment by mkristian** [comment]
@headius I have a look - too bad that it did not just work

**Comment by headius** [comment]
@mkristian Sonatype has requirements for artifacts getting pushed to central. Maybe there's a way around it since we're not pushing a jar?

**Comment by enebo** [comment]
@mkristian this is our last issue for 9.1.3.0 unless we snipe any recent incoming issues.  Any chance you can look at this in the next day?

**Comment by etehtsea** [comment]
@enebo @headius https://github.com/jruby/jruby/blob/master/core/pom.rb#L51 possibly jnr-constants should also be released before 9.1.3.0

**Comment by headius** [comment]
Ok, so this isn't a complete fix. It does bring you back to the prompt, but the already-entered text is still in a buffer somewhere:

```
[] ~/projects/jruby $ jirb
irb(main):001:0> asdf^C
irb(main):001:0> puts 'hello'
NoMethodError: undefined method `asdfputs' for main:Object
	from (irb):1:in `<eval>'
	from org/jruby/RubyKernel.java:994:in `eval'
	from org/jruby/RubyKernel.java:1295:in `loop'
	from org/jruby/RubyKernel.java:1114:in `catch'
	from org/jruby/RubyKernel.java:1114:in `catch'
	from /Users/headius/projects/jruby/bin/jirb:13:in `<main>'
irb(main):002:0>
```

I suspect we may finally need to go with rb_readline as our primary readline library and only have the jline/java-based version as a non-native fallback.

**Comment by headius** [comment]
Bumping to 9.1.4.0 to investigate further improvement.

**Comment by headius** [comment]
Ok, a quick check of rb-readline shows that it does not work properly (on JRuby) wrt ^C either. So something more needs to be done either way.

Maybe @djberg96 or someone else familiar with rb-readline will have some tips for us.

**Comment by djberg96** [comment]
I'm afraid I have no idea. You'll have to bug Luis Lavena or Park Heesob about it.

**Comment by headius** [comment]
@etehtsea The jnr-constants snapshot has been fixed for #4135, and a preventative measure will merge in with #4137.

This issue is still outstanding.

**Comment by headius** [comment]
Ok, it seems like something's wrong registering the SIGINT handler in IRB that's responsible for cancelling execution and input. I can see it get registered, but it never seems to fire in response to ^C.

A simple trap("SIGINT") at -e *sorta* works; the block will run once, and then the process terminates like ^C was never trapped.

**Comment by headius** [comment]
So it turns out the ^C issue might be a jline problem. jline registers its own signal handler so it can intercept various readliney signals. Seems very likely that's getting in our way.

**Comment by headius** [comment]
I may have stumbled on to a way to make things work correctly with rb-readline.

1. Install rb-readline gem
2. Remove lib/stdlib/readline* from JRuby
3. Comment out the bodies of "block_sigint" and "release_sigint" OR comment out the calls to them (four total)

It seems that the signal handling rb-readline does to protect its `\`stty\`` calls is mucking up the INT trap that IRB installs. It seems to try to restore the original handler, but it eventually gets set to IGNORE. I'm not sure what's happening yet; this could be a bug in our Signal.

In any case, with rb-readline patched and our own jline-based readline removed, ^C works exactly like MRI!
```
irb(main):001:0> asdf^C
irb(main):001:0> 
irb(main):002:0* 
```

I'm also going to explore what it would take to have a pure-FFI readline binding.

**Comment by headius** [comment]
I had almost forgotten about @koichiro's excellent work on [readline-ffi](https://github.com/koichiro/readline-ffi) so many years ago!

readline-ffi is *almost* perfect. Just gem install it, remove readline from stdlib, and you can do this:

```
irb(main):001:0> asdf^C^C

irb(main):001:0> 
irb(main):002:0* 
```

The input is cancelled, but we now see *two* ^C and we still need to hit enter to get back to a prompt.

**Comment by headius** [comment]
We need to re-spin jruby-readline without this fix and get it into 9.1.6.0 as a default gem.

**Comment by headius** [comment]
@enebo Ok, I guess I answered my own question here. We need to spin jruby-readline for 9.1.6.0.

**Comment by enebo** [comment]
@headius how does this jive with our last comments from #4141

**Comment by headius** [comment]
The reverted bad fix will go into 9.1.6.0, but any further improvements for this issue will not happen until 9.1.7.0 or later.

**Comment by headius** [comment]
Moving readline rework to 9.3.

**Comment by byteit101** [comment]
Confirmed this still affects JRuby 9.3.4.0. Linux x64, Java 11

**Comment by headius** [comment]
This works correctly now with new IRB and reline.

```
$ jirb
irb(main):001:0> asdf
^C                        
irb(main):001:0> foob
^C                                               
irb(main):001:0>
```
