### ISSUE TITLE
Drop 500MB cap for 9.1 on (and all launchers)

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3739]
I think it is time to drop the -Xmx default we have in the JRuby launchers.
# History

Ten years ago, when JRuby supported Java 1.4, we were forced to modify our launcher to bump up the default max heap size because the JVM always defaulted to 64MB. Unfortunately we did not keep up with the times. As of Java 5, the default max heap size got bumped up to be 1/4 of physical memory. 
# Proposal

I propose the following:
- For 9.1, we will remove -Xmx setting from jruby.bash. Most users that get JRuby will end up using the bash script.
- When we release the new jruby-launcher based on mjruby, we should also remove the -Xmx there. Mostly just new users will get that launcher, and then only if they use Windows, rvm, or install it themselves.
# Risks

Obviously if JRuby apps start using a lot more memory, people may notice that. But the JVM still limits it to avoid swamping the OS, and we get a lot of annoying reports from people due to the 500MB limit. I think it would be worth the risk to eliminate those reports, many of which start out as "why is this slow" and require manual investigation.

**Comment by kares** [comment]
some drawbacks (mostly for the record) are memory constrained env-s esp. if JRuby shells out another `jruby`. we've started seeing some "Killed" failures on travis-ci that went away after *-Xmx* [was set](https://github.com/jruby/jruby/commit/7a73edd2774bb6fe131f16db9e7306d15eac3189).

**Comment by headius** [comment]
I believe it was either @kares or @enebo who also pointed out that there are some issues with JVMs determining maximum memory when running in containerized environments. Specifically, the container reports the whole machine's memory rather than any restricted memory just for the container. The JVM as a result will pick a too-large value for the container.

I note this while still supporting the change but I'm unsure what timeframe.

**Comment by headius** [comment]
I would still like to do this for 9.1, which just needs a change in jruby-launcher...but we'd need to do a release of jruby-launcher.

**Comment by headius** [comment]
We'll do this whenever we update the launchers. It has already been done for jruby.bash.

**Comment by abiacco** [comment]
I would suggest this be put under the "Notable updates since..." part of the release page for 9.1.0.0.
I just upgraded to 9.1 to start testing and my "bundle install" started hanging trying to install gems (java 7) and then OutOfMemoryError when i tried with java 8.
Only after some research did i realize the Xmx had been dropped. Setting it with JRUBY_OPTS then made bundle work again.

**Comment by headius** [comment]
We'll reexamine this in the 9.2 timeframe. We're still behind on getting the new launcher integrated.

**Comment by headius** [comment]
Everything done for this except rebuilding .exe and releasing jruby-launcher gem.

**Comment by headius** [comment]
FTR, bash script change has been in the wild since 9.1 and we've received no directly related bug reports.

**Comment by headius** [comment]
jruby-launcher 1.1.6 has been released.
