### ISSUE TITLE
How do I use JRuby along with Ruby 2.2.3?

### ISSUE THREAD

**Issue by AbhimanyuAryan** [jruby/jruby#3746]
<img width="905" alt="screen shot 2016-03-19 at 5 53 48 am" src="https://cloud.githubusercontent.com/assets/8083613/13895240/1da22ad6-ed97-11e5-8653-66cab17f19cf.png">

**Comment by kares** [comment]
all seems well - not sure what you've expected by `require 'java'` in zsh - just use it like :1234: a Ruby!

**Comment by AbhimanyuAryan** [comment]
@kares 

yaa it worked.. I got little confused as I was following this link: http://rubylearning.com/satishtalim/jruby_tutorial.html

```
# javaSwingHello.rb  
require 'java' # Line 2  
JFrame = javax.swing.JFrame  
JLabel = javax.swing.JLabel  
frame  = JFrame.new  
jlabel = JLabel.new("Hello World")  
frame.add(jlabel)  
frame.setDefaultCloseOperation(JFrame::EXIT_ON_CLOSE)  
frame.pack  
frame.setVisible(true) 
```
