### ISSUE TITLE
Need to make `oj` work because of its runtime dependency on `boxr`.

### ISSUE THREAD

**Issue by swapnilabnave** [jruby/jruby#3751]
### Environment
* JRuby version :
  jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 Java HotSpot(TM) 64-Bit Server VM 25.65-b01 on 1.8.0_65-b17 +jit [linux-amd64]
* Operating system and platform

	➜  trunk `uname -a`
	Linux swapnil-Lenovo-Z50-70 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

	➜  trunk `lsb_release -a`
	No LSB modules are available.
	Distributor ID:	Ubuntu
	Description:	Ubuntu 15.10
	Release:	15.10
	Codename:	wily

Relevant info:
* [Gemfile](https://gist.github.com/swapnilabnave/7a545cda3f8d6e97297c), [Gemfile.lock](https://gist.github.com/swapnilabnave/19b5826c48484da55234)
* Application/framework version: rails 3.2.22.1
* [Environment variables](https://gist.github.com/swapnilabnave/9f6b403c76a1bf3fcb78)

This is not an issue, really. Just a situation.
I am using [`boxr`](https://rubygems.org/gems/boxr) to communicate with [Box API](https://developers.box.com/).

boxr  : I need [oj](https://github.com/ohler55/oj). Runtime dependency you know.
jruby : Please Use [alternatives(gson, json or json_pure instead)](https://github.com/jruby/jruby/wiki/C-Extension-Alternatives)
boxr  : [I like Oj](https://github.com/cburnette/boxr/search?utf8=%E2%9C%93&q=oj)

Me : How can I make them both settle, so that everyone is happy ?

--
Error log:

Installing oj 2.12.9 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/swapnil/.rvm/rubies/jruby-9.0.0.0/bin/jruby -r ./siteconf20160322-8577-urgrdc.rb extconf.rb
NotImplementedError: C extensions are not supported
    <top> at /home/swapnil/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/mkmf.rb:1
  require at org/jruby/RubyKernel.java:940
   (root) at /home/swapnil/.rvm/rubies/jruby-9.0.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
    <top> at extconf.rb:1

extconf failed, exit code 1

Gem files will remain installed in /home/swapnil/.rvm/gems/jruby-9.0.0.0@JayApp/gems/oj-2.12.9 for inspection.
Results logged to /home/swapnil/.rvm/gems/jruby-9.0.0.0@JayApp/extensions/universal-java-1.8/2.2.0/oj-2.12.9/gem_make.out

**Comment by kares** [comment]
Swapnil, you have 2 options to make this work: 
1. create a "native" (JRuby ext) backend for **oj** gem so it works the same on JRuby
2. avoid **boxr** direct dependending on **oj** (there used to be stuff such as multi_json which could maybe work with oj as the backend?)

`NotImplementedError: C extensions are not supported` won't go away - we can not fix that.

**Comment by swapnilabnave** [comment]
Thanks @kares for the quick reply.
>  create a "native" (JRuby ext) backend for oj gem so it works the same on JRuby

Sounds exciting. Please excuse my knowledge in the `native JRuby extension` basics. But can you please guide me how to do that ?

>  avoid boxr direct dependending on oj (there used to be stuff such as multi_json which could maybe work with oj as the backend?)

This looks like an option I can try out. *Make the json parser configurable in boxr itself (Oj/Multi_Json/<any json parser you want>)* Again haven't tried this before will try though.

**Comment by kares** [comment]
there's lots of gems out there that work as described in 1. (they do release 2 platform speficic gems for MRI and JRuby e.g. nokogiri) just do some research. there's also https://github.com/jruby/jruby-examples ... thanks for helping out on making gems work on JRuby!

**Comment by enebo** [comment]
@kares @swapnilabnave I have in fact very infrequently been working on a native extension for oj.  At this point I have most of the parsers ported but I am on the dumper (which is massive).  Once the dumper is done I should be able to have a proper test run since results in tests require the dumper.  At the point that is done I will try and merge it with oj assuming the author is happy.

**Comment by swapnilabnave** [comment]
Marvelous @enebo :+1: Looking forward to it :smiley:
