### ISSUE TITLE
Some cases of assignment in conditional do not warn as in MRI

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3757]
### Environment

JRuby 9.1 (HEAD)

### Expected Behavior

We should display the same warnings for "assignment in conditional" as in MRI.

### Actual Behavior

The following cases differ, which prevents MRI's TestRubyOptions#test_assignment_in_conditional from passing. These are the only remaining issues for that test to be green.

Here's output comparing JRuby and MRI:
```
[] ~/projects/jruby $ jruby -Xbacktrace.style=mri -e "if a = [a]; end"
-e:1: warning: found = in conditional, should be ==

[] ~/projects/jruby $ jruby -Xbacktrace.style=mri -e "if a = {1=>2}; end"

[] ~/projects/jruby $ jruby -Xbacktrace.style=mri -e "if a = {}; end"

[] ~/projects/jruby $ ruby23 -e "if a = [a]; end"

[] ~/projects/jruby $ ruby23 -e "if a = {1=>2}; end"
-e:1: warning: found = in conditional, should be ==

[] ~/projects/jruby $ ruby23 -e "if a = {}; end"
-e:1: warning: found = in conditional, should be ==

**Comment by enebo** [comment]
This involved two fixes:
1. HashNode was not marked as a ILiteralNode
2. The warning only triggers if Arrays/Hashes do not contain anything but other literal nodes.
