### ISSUE TITLE
after invoked the java API, couldn't exit to command line nomarly

### ISSUE THREAD

**Issue by catfishuang** [jruby/jruby#3759]
### Environment

jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 24.79-b02 on 1.7.0_79-b15 +jit [Windows 7-amd64]

actionmailer (4.2.5.2)
actionpack (4.2.5.2)
actionview (4.2.5.2)
activejob (4.2.5.2)
activemodel (4.2.5.2)
activerecord (4.2.5.2)
activerecord-jdbc-adapter (1.3.19)
activerecord-jdbcmysql-adapter (1.3.19)
activesupport (4.2.5.2)
akami (1.3.1)
amq-protocol (2.0.1)
arel (6.0.3)
arrayfields (4.9.2)
builder (3.2.2)
bundler (1.11.2)
bunny (2.3.0)
childprocess (0.5.9)
chronic (0.10.2)
coderay (1.1.1)
commonwatir (4.0.0)
concurrent-ruby (1.0.1 java)
dbd-jdbc (0.1.6 java)
dbi (0.4.5)
deprecated (2.0.1)
diff-lcs (1.2.5)
erubis (2.7.0)
fattr (2.2.2)
ffi (1.9.10 java)
globalid (0.3.6)
gyoku (1.3.1)
httpi (2.4.1)
i18n (0.7.0)
jar-dependencies (0.2.3)
jdbc-derby (10.11.1.1)
jdbc-mysql (5.1.38)
jruby-jars (9.0.5.0)
jruby-openssl (0.9.15 java)
jruby-win32ole (0.8.5)
json (1.8.3 java, 1.8.0 java)
logger (1.2.8)
loofah (2.0.3)
mail (2.6.3)
mailfactory (1.4.0)
main (5.3.2)
map (6.6.0)
method_source (0.8.2)
mime-types (3.0, 2.99.1)
mime-types-data (3.2016.0221)
minitest (5.4.1)
multi_json (1.11.2)
nokogiri (1.6.7.2 java)
nori (2.6.0)
power_assert (0.2.3)
pry (0.10.3 java)
psych (2.0.15 java)
racc (1.4.13 java)
rack (1.6.4)
rack-protection (1.5.3)
rack-test (0.6.3)
rails (4.2.5.2)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3)
railties (4.2.5.2)
rake (10.1.0)
rdoc (4.1.2)
rspec (3.4.0)
rspec-core (3.4.3)
rspec-expectations (3.4.0)
rspec-mocks (3.4.1)
rspec-support (3.4.1)
ruboto (1.4.1)
ruby-debug-base (0.10.6 java)
ruby-debug-ide (0.6.0)
ruby-ole (1.2.12)
rubygems-update (2.6.1)
rubyzip (1.2.0)
savon (2.11.1)
selenium-webdriver (2.52.0)
sinatra (1.4.7)
slop (3.6.0)
spoon (0.0.4)
spreadsheet (1.1.1)
sprockets (3.5.2)
sprockets-rails (3.0.3)
test-unit (3.0.3)
thor (0.19.1)
thread_safe (0.3.5 java)
tilt (2.0.2)
tzinfo (1.2.2)
wasabi (3.5.0)
watir (5.0.0)
watir-webdriver (0.9.1)
websocket (1.2.2)
xml-simple (1.1.5)
### Expected Behavior

after invoked the java API and done,exited to command line promoter
`client = RequestServiceHelper::RequestServiceClient.new 
  request = Java::JavaLang::String.new(req.to_json.to_s) 
  obj_class = Java::JavaClass.for_name('com.xxx.xxx.xxx.xxx.RequestModel') 
  client.createRequest(JSON.parseObject(request,obj_class))`
### Actual Behavior

invoked the java API and got a correct response, but couldn't exit to command line nomarly, see attachment ( bye the way, the java api is proved correct by testing in java)
![17](https://cloud.githubusercontent.com/assets/18095865/14063952/a043e8ca-f41e-11e5-87ac-3f077aab7c93.png)

**Comment by kares** [comment]
there must be a Java library blocking the exit - maybe a daemon thread started (e.g. by log4j?). 
you could confirm by stub-ing out the Java parts (`RequestModel`) to confirm which path it relates to.
we probably won't be able to do more without knowing your app or having a reproducable piece ...
