### ISSUE TITLE
Bundle install stops with handshake_failure trying to fetch specs from rails-assets.org

### ISSUE THREAD

**Issue by lumrandir** [jruby/jruby#3764]
### Environment
Jruby-9.0.5.0 
Windows 10 x86_64, MacOS (not windows-specific)
jruby-openssl-0.9.16
Oracle JDK 1.8.0_77

### Expected Behavior
Expect this script
```ruby
require 'net/http'
require 'openssl'

uri = URI.parse('https://rails-assets.org/specs-4.8.gz')
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
request = Net::HTTP::Get.new(uri.request_uri)
response = http.request(request)
```

to run successfully.

### Actual Behavior

I'm getting OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure
Trace:

        from org/jruby/ext/openssl/SSLSocket.java:215:in `connect'
        from C:/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:927:in `block in connect'
        from org/jruby/ext/timeout/Timeout.java:127:in `timeout'
        from C:/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:927:in `connect'
        from C:/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:867:in `do_start'
        from C:/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:856:in `start'
        from C:/jruby-9.0.5.0/lib/ruby/stdlib/net/http.rb:1388:in `request'

I have seen [this](https://github.com/jruby/jruby/issues/2220) issue and tried setting ssl_version, which didn't help at all.

**Comment by enebo** [comment]
I added a line I think you accidentally deleted when you entered this issue (request= line...).  I can reproduce this on MacOS so I think this is a generic openssl thing.  I tried some of the TLS config flags to JVM mentioned in #2220 and I can confirm those do not change this behavior.  I did confirm this does work on MRI 2.3 too.

@kares @mkristian you guys have any thoughts on this.

**Comment by mkristian** [comment]
I could reproduce the error with jdk8 but jdk7 did work for me on my macos

got the idea from https://www.ssllabs.com/ssltest/analyze.html?d=rails-assets.org which does actually indicate the opposite outcome.

@lumrandir did you try different JDKs ?

**Comment by lumrandir** [comment]
@mkristian Oh, sorry, I forgot to mention JDK version being used. Added the line in the issue description. Tried this on JDK 7u79, and It works just fine. Guess I'll stick with it for a while.

**Comment by lumrandir** [comment]
@hut8 it works OK on JDK 7/8, thank you. Guess I can close the issue now.
