### ISSUE TITLE
WARNING: SSLSocket#session= is not supported

### ISSUE THREAD

**Issue by lolwhitaker** [jruby/jruby#3765]
Hello.  I've seen this WARN log frequently in our builds during the [bundler](https://github.com/bundler/bundler/blob/20f04aa8923c0d0f02e7a74d5e9609d772351668/lib/bundler/vendor/net/http/persistent/ssl_reuse.rb#L67) process as well as when using the [net-http-persistent](https://github.com/drbrain/net-http-persistent/blob/5bae22e8a3626ab3b14743c00796d4f176580ad8/lib/net/http/persistent/ssl_reuse.rb#L67) adapter running jruby 1.7.22.  

```
WARNING: SSLSocket#session= is not supported
```

It looks like this was just [not implemented](https://github.com/jruby/jruby-openssl/blob/master/src/main/java/org/jruby/ext/openssl/SSLSocket.java#L1035).  Its pretty annoying, but is it something I should be concerned about? I asked the same question in the jruby-openssl project but it was closed without any response.

#3635 also mentions this warning in 9.0.5.0...

```jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 +jit [darwin-x86_64]```

**Comment by kares** [comment]
opened: https://github.com/drbrain/net-http-persistent/issues/72 to see what they think about removing `ssl.session=` on JRuby

**Comment by SuriyaaKudoIsc** [comment]
:+1:

**Comment by dgolombek** [comment]
Since updating to 0.9.17-java we're now seeing problems trying to open sessions -- it looks like this change is probably to blame.

```
handle_connection_error: No existing session to resume: org/jruby/ext/openssl/SSLSocket.jav
a:217:in `connect'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:70:in `connect'
org/jruby/ext/timeout/Timeout.java:115:in `timeout'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent/ssl_reuse.rb:70:in `connect'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.25.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:756:in `do_start'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/lib/jruby-stdlib-1.7.25.jar!/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:751:in `start'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:965:in `reset'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:628:in `connection_for'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http_persistent.rb:25:in `perform_request'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `call'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http_persistent.rb:21:in `with_net_http_connection'
/tmp/jetty-0.0.0.0-8080-evergreen.war-_evergreen-any-412843000765214245.dir/webapp/WEB-INF/gems/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
```

**Comment by dgolombek** [comment]
Created #3974

**Comment by headius** [comment]
@kares Any progress on this? I was hoping we'd be able to ignore `SSLSocket.session/=` but perhaps we need to find a way to finish it.

**Comment by kares** [comment]
it (kind of) is supported - was an empty stub up till 0.9.17 ... now it tries to force session re-use in 0.9.17.
... there seems to be some issues with the 0.9.17 change - waiting for feedback: https://github.com/jruby/jruby-openssl/issues/97
