### ISSUE TITLE
.bat files in bin incorrectly use "jruby.bat.exe" instead of "jruby.exe", which causes file not found errors when executing in Windows

### ISSUE THREAD

**Issue by ikakara** [jruby/jruby#3772]
Running rake results in the following error:

'"..\bin\jruby.bat.exe"' is not recognized as an internal or external command, operable program or batch file.

This is because the batch file contains "jruby.bat.exe" instead of "jruby.exe"

ast works fine, but many of the other batch files are incorrect.

### Environment

jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.74-b02 on 1.8.0_74-b02 +jit [Windows 10-amd64]

This issue also occurs in jruby version 1.7.24, and I imagine this bug is in other Windows versions as well.

### Expected Behavior

Running rake should produce:
C:\jruby-9.0.5.0\bin>rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
C:\jruby-9.0.5.0\bin\rake:23:in `<top>'
(See full trace by running task with --trace)

### Actual Behavior

'"C:\jruby-9.0.5.0\bin\jruby.bat.exe"' is not recognized as an internal or external command, operable program or batch file.

**Comment by ikakara** [comment]
There's an easy fix: replace all "jruby.bat.exe" with "jruby.exe" in all the batch files

**Comment by enebo** [comment]
@ikakara how are you installing JRuby on windows?  And which .bat scripts do you see have jruby.bat.exe?  I cannot find any reference to jruby.bat.exe.  If I had to guess you built jruby locally and there is something wrong with out build scripts which is putting this into .bat generated files.

**Comment by ikakara** [comment]
I'm using the download .exe(x64) installer.

**Comment by ikakara** [comment]
http://jruby.org/download - choose either 9.0.5.0 or 1.7.24 Windows Executable (x64)

**Comment by enebo** [comment]
@ikakara ok.  That was a random guess.  I installed exe 64 bit on win7 and I am not seeing this issue.  I wonder if it involves something with Win10.  I am grasping at straws :)

**Comment by ikakara** [comment]
Let me uninstall and reinstall.... Is there a difference with .exe and zip installations?

**Comment by enebo** [comment]
@ikakara .zip is mostly the same but the installer does extra stuff like install a program group for start menu and setup a path for you.  I would be interested in seeing if you have the same issue with the .zip version though.

**Comment by ikakara** [comment]
So the zip file contains windows .bat files w/ the correct info:
@ECHO OFF
@"%~dp0jruby.exe" -S rake %*

I'll double check the windows (x64) installation ...

**Comment by ikakara** [comment]
Well, I can't seem to reproduce the installation problem.  I do have bin directories w/ the wrong .bat files.  But when I reinstall w/ the same installation executables, the installation looks good.

Anyway, I don't know what happened - I guess we'll see if anyone encounters this issue, and try to further deduce when it happens again.

**Comment by enebo** [comment]
@ikakara ok.  I will close but if we see this again I will link the issues together.
