### ISSUE TITLE
Unicode chars in method names aren't accepted

### ISSUE THREAD

**Issue by jodosha** [jruby/jruby#3778]
### Environment

JRuby version:

`jruby 9.1.0.0-SNAPSHOT (2.3.0) 2016-04-01 30c1276 Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [darwin-x86_64]`

OS:

`Darwin escher 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64`

### Expected Behavior

Unicode chars in method names should be accepted.

I discovered this issue with `hanami-utils` and [patched it](https://github.com/hanami/utils/commit/e38490099113c4e6e1ad5878050ca826f7fabe3c) to make the build to pass with 9.0.0.0.

According to @enebo, [this supposed to be fixed with nightly series](https://github.com/jruby/jruby/issues/2127#issuecomment-204575538), but it isn't the case.

MRI/expected behavior:

```ruby
irb(main):001:0> RUBY_VERSION
=> "2.3.0"
irb(main):002:0> def тест
irb(main):003:1> puts "hi"
irb(main):004:1> end
=> :тест
irb(main):005:0> тест
hi
=> nil
```

### Actual Behavior

```ruby
irb(main):001:0> RUBY_VERSION
=> "2.3.0"
irb(main):002:0> def тест
irb(main):003:1> puts "hi"
irb(main):004:1> end
=> :????
irb(main):005:0> тест
NameError: uninitialized constant B5AB
	from org/jruby/RubyModule.java:3238:in `const_missing'
	from (irb):5:in `<eval>'
	from org/jruby/RubyKernel.java:983:in `eval'
	from org/jruby/RubyKernel.java:1290:in `loop'
	from org/jruby/RubyKernel.java:1103:in `catch'
	from org/jruby/RubyKernel.java:1103:in `catch'
	from /Users/luca/.rubies/jruby-9.1.0.0-SNAPSHOT/bin/irb:13:in `<top>'
irb(main):006:0> __send__(:тест)
hi
=> nil
irb(main):007:0> __send__("тест")
NoMethodError: undefined method `тест' for main:Object
	from (irb):7:in `<eval>'
	from org/jruby/RubyKernel.java:983:in `eval'
	from org/jruby/RubyKernel.java:1290:in `loop'
	from org/jruby/RubyKernel.java:1103:in `catch'
	from org/jruby/RubyKernel.java:1103:in `catch'
	from /Users/luca/.rubies/jruby-9.1.0.0-SNAPSHOT/bin/irb:13:in `<top>'
```

**Comment by headius** [comment]
It seems to be seeing `тест` as being preceded by a capital letter, causing the first error when it tries to access it. If instead you make that line `тест()` it invokes correctly.

The send issue is a known mismatch between how we store multibyte symbols and how we store methods.

**Comment by enebo** [comment]
@jodosha also extreme minor issue I should bring up it we recently learned multibyte methods defined in irb will not work (@uwe opened an issue on that a couple of days ago).  That is not related to this issue at all but you might trip over that as well.

**Comment by headius** [comment]
I think the main issue here above and beyond #3880 is that `тест` is getting parsed as a constant access. Using both Ruby's String and Java's string, the `т` codepoint appears to be lowercase.

```
[] ~/projects/jruby $ jruby -e "puts 'тест'"
тест

[] ~/projects/jruby $ jruby -e "puts 'тест'.to_java"
тест

[] ~/projects/jruby $ jruby -e "puts 'тест'.codepoint(0)"
NoMethodError: undefined method `codepoint' for "тест":String
Did you mean?  codepoints
  <main> at -e:1

[] ~/projects/jruby $ jruby -e "puts 'тест'.codepoints[0]"
1090

[] ~/projects/jruby $ jruby -e "puts 'тест'.to_java.charAt(0)"
1090

[] ~/projects/jruby $ jruby -e "p java.lang.Character.isUpperCase(1090)"
-e:1: warning: ambiguous Java methods found, using isUpperCase(char)
false
```

So whatever the parser is using to determine capital letters for constants, it's not handling this MBC properly.

**Comment by headius** [comment]
Oh, and I agree this isn't going to make 9.1.3.0, so punting.

**Comment by jodosha** [comment]
@enebo @headius Thanks for your follow up. This isn't a blocking issue for Hanami, I just reported to let you know 😄 .

Good luck with the next release and again thank you for JRuby!

**Comment by enebo** [comment]
@jodosha The comment explains this but it was pretty simple to fix and I feel this is not risky so this is in 9.1.3.0.

The send with a string is still broken but a different issue (alluded to in my previous comment).
