### ISSUE TITLE
[Truffle] Bundle error

### ISSUE THREAD

**Issue by brauliobo** [jruby/jruby#3782]
I got `Bundler::Dsl::DSLError` (nothing more, no stack trace) when trying to run jruby truffle with bundle exec: `JAVACMD=/home/braulio/Projects/GraalVM-0.10/jre/bin/javao bundle exec jruby.bash -X+T ./bin/benchmark components/pos_tagger_bench.rb`. It works without `-X+T`

**Comment by brauliobo** [comment]
the error can be reproduced with a very simple `Gemfile`:
```
source 'http://rubygems.org'

gem 'httpclient'
```

and then run `JAVACMD=/home/braulio/Projects/GraalVM-0.10/jre/bin/javao bundle exec jruby.bash -X+T -e 'puts Truffle.graal?'`

**Comment by chrisseaton** [comment]
In general we don't support Bundler at the moment, however I think @bjfish has been trying it and I think he said we were nearly there.

**Comment by pitr-ch** [comment]
@brauliobo to get around bundler we currently use different tool, please have look at https://github.com/jruby/jruby/tree/master/lib/ruby/truffle/jruby%2Btruffle. If you run into trouble I'll help.

**Comment by bjfish** [comment]
Last time I tried `rubygems` and  `Bundler` it was working very well for me. I think this was the patch I was using:
https://gist.github.com/bjfish/840c11b171450642bdab

I remember I was setting a custom GEM_HOME and using a different ruby to fetch the dependencies like this:
```
GEM_HOME=/path/to/gem/home gem install sinatra # using ruby 2
GEM_HOME=/path/to/gem/home ruby sinatra_app.rb # using truffle
```

**Comment by brauliobo** [comment]
cool @bjfish! could you create a PR?

**Comment by pitr-ch** [comment]
I've tried the gist changes, but it does not work at the moment because rubygems versions differ in JRuby stdlib and JRuby+Truffle stdlib. Generated gem bins are not running with older rubygems. The tool is fine.

**Comment by chrisseaton** [comment]
Thanks for the issue, but I'll close now that we are moving repository. Bundler still isn't quite ready yet in general so we don't expect it to work.
