### ISSUE TITLE
Recent CI snapshots give warning on load of openssl

### ISSUE THREAD

**Issue by donv** [jruby/jruby#3787]
Just so this does not slip into a release.

### Environment

jruby 9.1.0.0-SNAPSHOT (2.3.0) 2016-04-08 caff747 Java HotSpot(TM) 64-Bit Server VM 25.77-b03 on 1.8.0_77-b03 +jit [darwin-x86_64]

Darwin macbeth-2.local 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64

### Expected Behavior

$ jruby -ropenssl -e "puts 42"
42

### Actual Behavior

$ jruby -ropenssl -e "puts 42"
WARNING: while creating new bindings for class org.jruby.ext.openssl.X509Name,
found an existing binding; you may want to run a clean build.
WARNING: while creating new bindings for class org.jruby.ext.openssl.SSLSocket,
found an existing binding; you may want to run a clean build.
42

**Comment by donv** [comment]
This is for snapshots downloaded from http://ci.jruby.org/

**Comment by donv** [comment]
Can someone with access to the ci server try cleaning the work space?

**Comment by kares** [comment]
caused by doing a mess at: https://github.com/jruby/jruby/commit/9c555c2baafb48bcf2befca56923a367b10d09db#diff-0905351fb8beb19fd2ff8fcca920af53R285 ... thanks @donv!

**Comment by donv** [comment]
Fix verified on

```
jruby 9.1.0.0-SNAPSHOT (2.3.0) 2016-04-11 38e32b0 Java HotSpot(TM) 64-Bit Server VM 25.77-b03 on 1.8.0_77-b03 +jit [darwin-x86_64]
```

Thanks @kares !
