### ISSUE TITLE
problem of chinese method name 

### ISSUE THREAD

**Issue by catfishuang** [jruby/jruby#3819]
### Environment

jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 24.79-b02 on 1.7.0_79-b15 +jit [Windows 7-amd64]
### Expected Behavior

def 牛逼
  puts '111'
end

牛逼     # It's OK

@name = "中文"
  send :define_method,:"#{@name}" do
    puts "中文test"
  end

中文    # Error occur   but it run well in cruby

### Actual Behavior

NameError: undefined local variable or method `??' for main:Object

**Comment by enebo** [comment]
This symbol issue with define_method was fixed a couple of weeks ago.  Works on master.  9.1.0.0 will work for you.
