### ISSUE TITLE
Error when rspec loads files using Refinements

### ISSUE THREAD

**Issue by estolfo** [jruby/jruby#3820]
#### Summary
[Mongoid](https://github.com/mongodb/mongoid) has supported JRuby until now but I've run into some issues when refactoring Mongoid to use Refinements instead of monkey-patching core classes.

The Refinements branch in Mongoid is [here](https://github.com/mongodb/mongoid/tree/6.0.0-refinements).

I believe I'm seeing the same issue as this [one](https://github.com/jruby/jruby/issues/2977).

It seems that a problem is encountered when files are loaded by rspec. The line throwing the error is [here](https://github.com/mongodb/mongoid/blob/6.0.0-refinements/lib/mongoid/relations/targets/enumerable.rb#L20).

If I put the line ["using Refinements"](https://github.com/mongodb/mongoid/blob/6.0.0-refinements/lib/mongoid/relations/targets/enumerable.rb#L11) [after the culprit line](https://github.com/mongodb/mongoid/blob/6.0.0-refinements/lib/mongoid/relations/targets/enumerable.rb#L21), it will load with no errors.

Let me know if I can help with debugging. If you would like to test, you can clone the Mongoid repo, check out the 6.0.0-refinements branch, start mongod on the default host/port (localhost:27017), run bundle, and then rspec.

### Environment
* jruby 9.0.5.0
* mac os x
* [bundle list](https://travis-ci.org/mongodb/mongoid/jobs/122520661#L259-L282)

**Comment by headius** [comment]
I believe this will be fixed, but I'm not sure if things run properly. You'll see a commit for 9.1 shortly, and if you have a chance to test a 9.1 snapshot before we release next week it would be a great help.

If there's still outstanding issues that aren't the arity/block error, file a new issue and we'll look at it for 9.1.1.
