### ISSUE TITLE
repackage all jnr-* dependencies to make jruby-core to be used in OSGi setup

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#3821]
### Environment

any jruby-9k version

### Expected Behavior

be able to create osgi package out of jruby-core on the fly or even setup working osgi metadata for jruby-core
### Actual Behavior

can not find classes which are repacked by jruby but declared in the osgi metadata of the respective jnr-xyz jar.

**Comment by headius** [comment]
@mkristian I'm going to remove this from any release since it's not clear when it will happen.

**Comment by mkristian** [comment]
@headius I hope the repackaging I meant the java packages and shade them ALL into the jruby-core. doing so for jruby-9.2.x would be worth give it a thought

**Comment by headius** [comment]
@mkristian By shade, you mean take all of our internal dependencies and relocate them into JRuby packages, yes? That would be fine with me, if it doesn't impact build times too much. And any API that we expose, like date/time classes accepting or returning Joda's DateTime, would still need to be unshaded.

9.2 seems like a reasonable timeframe to consider this.

**Comment by headius** [comment]
Ping @mkristian. We need to address this or retarget (probably retarget).

**Comment by headius** [comment]
Too big a change to do right before release, according to @mkristian. I'll detarget until we can get this on a roadmap.

**Comment by headius** [comment]
We have discussed this in other contexts and this bug is old and stale.

**Comment by headius** [comment]
See for example #6205.
