### ISSUE TITLE
NoMethodError: undefined methodset_validate_after_inactivity'  when running logstash 2.1.3 and 5.0.0-alpha on JRuby 1.9

### ISSUE THREAD

**Issue by asitk** [jruby/jruby#3824]
### Environment

java -v
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

jruby -v
jruby 1.7.23 (1.9.3p551) 2015-11-24 f496dd5 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_77-b03 +jit [linux-amd64]

uname -a
Linux ak-ubuntu 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

lsb_release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

### Expected Behavior
logstash connects to elasticsearch 

input {
  tcp {
    port => 5000
    type => "apache_access_log"
  }
  tcp {
    port => 5001
    type => "apache_error_log"
  }
}

filter {
  if [type] == "apache_access_log" {
    grok {
      match => { "message" => "%{HOSTNAME:nodename} %{IP:nodeip} %{COMBINEDAPACHELOG}" }
    }
  }
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
    locale => "en"
  }
  if ([type] == "apache_error_log") {
    grok {
      match => [ "message", "%{HOSTNAME:nodename} %{IP:nodeip} %{APACHE_ERROR_LOG}" ]
    }
    date {
      match => [ "timestamp" , "EEE MMM d HH:mm:ss.SSSSSS yyyy" ]
      locale => "en"
    }
  }
}

output {
  elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => json }
}

### Actual Behavior

NoMethodError: undefined methodset_validate_after_inactivity' for #Java::OrgApacheHttpImplConn::PoolingHttpClientConnectionManager:0x49b00f6a

`Pipeline aborted due to error {:exception=>#<NoMethodError: undefined method `set_validate_after_inactivity' for #<Java::OrgApacheHttpImplConn::PoolingHttpClientConnectionManager:0x49b00f6a>>, :backtrace=>["/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:403:in `pool'", "org/jruby/RubyKernel.java:1858:in `tap'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:402:in `pool'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:208:in `initialize'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:100:in `__build_connections'", "org/jruby/RubyArray.java:2414:in `map'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:90:in `__build_connections'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:34:in `initialize'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:115:in `initialize'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport.rb:26:in `new'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.6.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:129:in `build_client'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.6.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.6.0-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:40:in `build'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.6.0-java/lib/logstash/outputs/elasticsearch.rb:132:in `build_client'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.6.0-java/lib/logstash/outputs/elasticsearch/common.rb:14:in `register'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha1-java/lib/logstash/output_delegator.rb:83:in `register'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha1-java/lib/logstash/pipeline.rb:216:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha1-java/lib/logstash/pipeline.rb:216:in `start_workers'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha1-java/lib/logstash/pipeline.rb:171:in `run'", "/opt/tools/logstash-5.0.0-alpha1/vendor/bundle/jruby/1.9/gems/logstash-core-5.0.0.alpha1-java/lib/logstash/agent.rb:217:in `start_pipeline'"], :level=>:error}
stopping pipeline {:id=>"main", :level=>:warn}`

**Comment by enebo** [comment]
@asitk can you try this with 1.7.25?  Logstash should not be having issues in the latest version.  At least they ran a bunch of sanity checks before 1.7.25 came out.

**Comment by asitk** [comment]
I think this was a perms issue. It was installed under root. Running logstash under sudo seems to address it.

**Comment by enebo** [comment]
ah ok...well all's well that ends well...

**Comment by tavisca-IdrisW** [comment]
Hi, Facing the same issue. This does not resolve even after running with sudo. Any other suggestions?
