### ISSUE TITLE
Another failure to pass arguments when rspec loads files using Refinements

### ISSUE THREAD

**Issue by estolfo** [jruby/jruby#3826]
### Summary

I opened [this issue](https://github.com/jruby/jruby/issues/3820) last week. The specific error noted in the issue description has indeed gone away with the fix applied in [this commit](https://github.com/jruby/jruby/commit/41cd2c3ac4a92451f3d61e6ef21d3de6ccb68a56) but it seems that there is another issue.

[This is the line](https://github.com/mongodb/mongoid/blob/6.0.0-refinements/lib/mongoid/validatable.rb#L19) from where the error is thrown.

This is the stack trace when I run rspec:
 
```
ArgumentError: wrong number of arguments calling `included` (0 for 1)
  <module:Validatable> at /Users/emily/Code/mongoid/mongoid/lib/mongoid/validatable.rb:19
      <module:Mongoid> at /Users/emily/Code/mongoid/mongoid/lib/mongoid/validatable.rb:15
                 <top> at /Users/emily/Code/mongoid/mongoid/lib/mongoid/validatable.rb:11
               require at org/jruby/RubyKernel.java:944
               require at /Users/emily/Code/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:120
                 <top> at /Users/emily/Code/mongoid/mongoid/lib/mongoid/composable.rb:1
               require at org/jruby/RubyKernel.java:944
               require at /Users/emily/Code/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:120
                 <top> at /Users/emily/Code/mongoid/mongoid/lib/mongoid/composable.rb:16
               require at org/jruby/RubyKernel.java:944
               require at /Users/emily/Code/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:120
                 <top> at /Users/emily/Code/mongoid/mongoid/lib/mongoid/document.rb:1
               require at org/jruby/RubyKernel.java:944
               require at /Users/emily/Code/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:120
                 <top> at /Users/emily/Code/mongoid/mongoid/lib/mongoid/document.rb:16
               require at org/jruby/RubyKernel.java:944
               require at /Users/emily/Code/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
                 <top> at /Users/emily/Code/mongoid/mongoid/lib/mongoid.rb:1
                  load at org/jruby/RubyKernel.java:962
       block in (root) at /Users/emily/Code/mongoid/mongoid/lib/mongoid.rb:23
                  each at org/jruby/RubyArray.java:1593
                (root) at /Users/emily/Code/mongoid/mongoid/spec/spec_helper.rb:1
                (root) at /Users/emily/Code/mongoid/mongoid/spec/spec_helper.rb:8
                (root) at /Users/emily/Code/mongoid/mongoid/spec/mongoid/atomic/modifiers_spec.rb:1
                (root) at /Users/emily/Code/mongoid/mongoid/spec/mongoid/atomic/modifiers_spec.rb:1
                (root) at /Users/emily/Code/jruby/lib/ruby/gems/shared/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1
                 <top> at /Users/emily/Code/jruby/lib/ruby/gems/shared/gems/rspec-core-3.4.4/exe/rspec:4

```

### Environment
* jruby 9.0.5.0
* mac os x
* [bundle list](https://travis-ci.org/mongodb/mongoid/jobs/122520661#L259-L282)

**Comment by headius** [comment]
Ok, so I suspect what's happening here is that it's finding the normal Module#included – which *does* require an argument – rather than some incuded you've refined into this body, yes?

This may be fixed by work I committed late last week and today that improves the search logic for refinements. I'll kick the snapshot build at http://ci.jrubyorg and you can let me know if it looks better.

**Comment by headius** [comment]
Also...I didn't find (in quick inspection) any instructions on how to get up a test run. If I could run your suite it might be easy for me to shake out any remaining bugs.

**Comment by headius** [comment]
Since this might have been fixed by additional work on refinements, and since we're running out of time for 9.1, I'm punting this to 9.1.1.0.

@estolfo Try to confirm last night's 9.1 snapshot. If it's still an issue and you can get us a way to reproduce it, we might be able to get it into 9.1.

**Comment by estolfo** [comment]
Thanks so much for working on this, @headius 
I haven't been able to test out the latest snapshot yet, but I don't want to hold you up. After some thought and further tests, I may not end up using Refinements. I've found some bizarre and unexpected behavior when on MRI that I'm not comfortable with introducing into Mongoid's codebase.
I'm happy to continue testing with my branch to help surface issues with Refinements in JRuby, but feel free to move forward with the 9.1 without my testing.

**Comment by headius** [comment]
@estolfo I recommend that nobody ever use refinements, for exactly those reasons :-) We do appreciate having bug reports since it is a supported feature and we intend to make it work right.

If you are still able to verify this bug, that would be great. However, if you won't be able to verify or if you want to close the bug, that's fine too.

**Comment by estolfo** [comment]
Hi @headius 
As I decided to not use Refinements in Mongoid, I haven't had the chance to test and provide more information to the ticket over the last week. I'll have an update within the next day or two, otherwise, feel free to close and I'll open another ticket when I get back to it.
Thanks again!

**Comment by estolfo** [comment]
I'm closing this and will open another issue when I have the chance to get back to trying out Refinements in Mongoid. Thanks!
