### ISSUE TITLE
jruby-openssl Socket Closed

### ISSUE THREAD

**Issue by jadon1979** [jruby/jruby#383]
Issue:  Net::HTTP calls failing when using jruby-openssl with a OpenSSL::SSLError Socket Closed, but working fine using MRI.  

Side Note:  Calls to many servers work, however this app is calling to a cisco sensor.  Again, it works via MRI but not Jruby.  

Failing At https://github.com/jruby/jruby/blob/master/src/org/jruby/ext/openssl/SSLSocket.java#L404  ?

Update:  http://jira.codehaus.org/browse/JRUBY-6346

Back Trace Excerpt

org/jruby/ext/openssl/Utils.java:79:in `newError'
org/jruby/ext/openssl/SSL.java:92:in `newSSLError'
org/jruby/ext/openssl/SSLSocket.java:192:in `connectCommon'
org/jruby/ext/openssl/SSLSocket.java:162:in `connect'
org/jruby/runtime/callsite/CachingCallSite.java:306:in `cacheAndCall'
org/jruby/runtime/callsite/CachingCallSite.java:136:in `call'
org/jruby/ast/CallNoArgNode.java:64:in `interpret'
org/jruby/ast/NewlineNode.java:105:in `interpret'

UPDATE:

I could not find an answer to this issue.  If you come across then I suggest the following work around (noted at the bottom)

http://stackoverflow.com/questions/13319698/jruby-openssl-vs-mri-openssl-socket-closed

**Comment by kares** [comment]
closing outdated issue - if someone ends up here make sure to try recent jruby-openssl
