### ISSUE TITLE
Double packaging of `org/joda/time/format/messages.properties` in jruby-jars

### ISSUE THREAD

**Issue by donv** [jruby/jruby#3861]
### Environment

* jruby-jars-9.1.0.0
* OS X 10.10.5
* Ruboto 1.5.0

### Expected Behavior

No duplicate files in `jruby-core` vs `jruby-stdlib`

### Actual Behavior

Found duplicate file: org/joda/time/format/messages.properties

When packaging Ruboto applications, this breaks the packaging.  Which file should be included in the package?

**Comment by donv** [comment]
There are several files that are duplicated:

    org/joda/time/format/messages*.properties
    org/joda/time/tz/data/**/*

**Comment by kares** [comment]
hey! there weren't any in 9.0.5.0, right? ... there wasn't much packaging related change as far as I know.

**Comment by mkristian** [comment]
@donv can you please tell me where you got the jruby-stdlib from ? the file from http://repo1.maven.org/maven2/org/jruby/jruby-stdlib/9.1.0.0/ has only files under META-INF directory which look all OK to me.

**Comment by headius** [comment]
Not critical for 9.1.1 release. Punting.

**Comment by donv** [comment]
I got the files from jruby-jars.gem from rubygems.org and from

http://ci.jruby.org/snapshots/master/jruby-jars-9.1.3.0.SNAPSHOT.gem

**Comment by kares** [comment]
for the 9.1.2.0 released jruby-jars gem (from rubygems) I do not see those duplicates in the packed : 
```
kares@sputnik:~/tmp$ jar tvf jruby-core-9.1.2.0-complete.jar | grep messages
   650 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages.properties
   663 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages_da.properties
   660 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages_de.properties
     0 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages_en.properties
   665 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages_es.properties
   670 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages_fr.properties
   658 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages_ja.properties
   649 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages_nl.properties
  1172 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages_pl.properties
   652 Thu May 26 16:49:16 CEST 2016 org/joda/time/format/messages_pt.properties
```
(no messages*.properties in jruby-stdlib .jar) ... same for the linked SNAPSHOT : 
```
kares@sputnik:~/tmp$ jar tvf jruby-core-9.1.3.0-SNAPSHOT-complete.jar | grep messages
   650 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages.properties
   663 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages_da.properties
   660 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages_de.properties
     0 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages_en.properties
   665 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages_es.properties
   670 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages_fr.properties
   658 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages_ja.properties
   649 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages_nl.properties
  1172 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages_pl.properties
   652 Mon May 30 00:36:54 CEST 2016 org/joda/time/format/messages_pt.properties
```
did I miss anything?

**Comment by mkristian** [comment]
@kares commit https://github.com/jruby/jruby/commit/5c712c5e9345801ba764d3e0c61f6e37d98878f4 brought the joda jars into jruby-stdlib which I think gives the error @donv sees as ruboto does unpack all jars found inside the jruby-stdlib

**Comment by kares** [comment]
oh najs ... that maven meta-data part seems scary  - good that you kept an eye on that one. thanks!

**Comment by kares** [comment]
did remove *jjoda-time-2.3.jar* from stdlib dist. not sure how it got there - thus keeping open just in case.

**Comment by headius** [comment]
What more do we need to do for this one, @kares?

**Comment by kares** [comment]
should be good to go ... we can always reopen if its still an issue.
