### ISSUE TITLE
Backport recent File.expand_path and basename encoding fixes

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3885]
As requested by @enebo we should try to backport the fixes for #3877 and #3866 to 1.7.

The #3866 fix is mostly isolated from joni transcoding, but the #3877 fix would require 1.7 to start using joni for at least the encoding of java.lang.String to unusual target encodings (like Windows-1250).

I started wotking on #3866 but there have been refactorings on 9.1 to negotiate, and there's missing fixes for e.g. the "filesystem" encoding. With all of #3866 naively ported, I was getting NPEs due to a null filesystem encoding.

Regardless, I don't believe it would be a lot of work to get both fixes ported appropriately.

**Comment by enebo** [comment]
1.7.x is EOL and this will not get fixed.  Marking WONTFIX
