### ISSUE TITLE
Kernel#proc with no arguments inside a method, fails with ArgumentError: tried to create Proc object without a block

### ISSUE THREAD

**Issue by djellemah** [jruby/jruby#3915]
jruby 9.0.5.0 and 9.1.0.0

OS:
gentoo linux kernel 4.1.15, 64 bit kernel, 32-bit userland
gentoo linux kernel 4.1.15, 64 bit kernel, 64-bit userland

~ $ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

``` ruby
def this_works( ary )
  if block_given?
    ary.map &Proc.new # this works
  end
end

this_works [9,8,7] do |item|
  item * 2
end

def this_doesnt_work( ary )
  if block_given?
    ary.map &proc # this *should* work, and does in MRI 2.1.10 .. 2.3.1
  end
end

this_doesnt_work [3,2,1] do |item|
  item * 2
end
```

**Comment by ekreutz** [comment]
**System info:**
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

RUBY (both versions reproduce the issue)
jruby-1.7.23 [ x86_64 ]
jruby-9.1.2.0 [ x86_64 ]

**Example code:**
```ruby
# this method somehow gets mangled in compilation?
def failingMethod
	::Proc.new.call
end

# if this is used instead, everything compiles well!
def workingMethod
	Proc.new.call
end

some_var = "it fails!"

failingMethod do
	some_var = "it works!"
end

# should print "it works!"
puts some_var

```
When run, the above code produces the output:
```
ArgumentError: tried to create Proc object without a block
            new at org/jruby/RubyProc.java:130
  failingMethod at hello.rb:2
         (root) at hello.rb:7
```
If the same ruby file is run with compilation turned off, everything works fine.

**Comment by doudou** [comment]
[Still present in 9.1.7.0](https://github.com/jruby/jruby/issues/4456)

**Comment by headius** [comment]
This isn't something we're likely to fix.

It works in MRI only because of the way MRI is implemented. The current call's passed block *just happens* to be available when calling proc, and proc *just happens* to not care where the block comes from. Similar behavior happens for Proc.new, but both behaviors are discouraged and may go away in future versions of Ruby.

FWIW, Proc.new does currently work only because we make a special case for it in our compiler.

Your best bet short term is to either use Proc.new or capture the block in the method signature with `&block`.

**Comment by doudou** [comment]
> It works in MRI only because of the way MRI is implemented. The current call's passed block just happens to be available when calling proc, and proc just happens to not care where the block comes from

I was kind-of expecting something like that given how "magic" the whole thing feels. Thanks for telling us that we shouldn't hold our breath, it's appreciated.

So, I'll slowly remove 'proc' from my projects ... It's not as if there was many of them.

**Comment by headius** [comment]
@doudou Thanks for understanding! I hope some day CRuby makes it official that these forms are not expected to work, since they're pretty weird anyway.
