### ISSUE TITLE
FFI::NotFoundError: Function 'CreateSymbolicLinkW' not found in [kernel32]

### ISSUE THREAD

**Issue by bioprogrammer** [jruby/jruby#3939]
### Expected Behavior

a_count = 0
c_count = 0
g_count = 0
t_count = 0

File.open('sequence.fasta').each do |line|
    a_count += line.split('').count('A')
    c_count += line.split('').count('C')
    g_count += line.split('').count('G')
    t_count += line.split('').count('T')
end

puts 'A: ' + a_count.to_s
puts 'C: ' + c_count.to_s
puts 'G: ' + g_count.to_s
puts 'T: ' + t_count.to_s

### Actual Behavior

FFI::NotFoundError: Function 'CreateSymbolicLinkW' not found in [kernel32]
     attach_function at C:/jruby-9.1.2.0/lib/ruby/stdlib/ffi/library.rb:241
        attach_pfunc at uri:classloader:/jruby/kernel/file.rb:25
  <module:Functions> at uri:classloader:/jruby/kernel/file.rb:31
       <module:File> at uri:classloader:/jruby/kernel/file.rb:16
    <module:Windows> at uri:classloader:/jruby/kernel/file.rb:8
      <module:JRuby> at uri:classloader:/jruby/kernel/file.rb:7
               <top> at uri:classloader:/jruby/kernel/file.rb:6
                load at org/jruby/RubyKernel.java:962
               <top> at file:/C:/jruby-9.1.2.0/lib/jruby.jar!/jruby/kernel.rb:1

**Comment by enebo** [comment]
@bioprogrammer could you tell us more about which version of Windows and the JVM you were using.  @djberg96 maybe you know about which envs may not be able to load this?

**Comment by djberg96** [comment]
@enebo My guess is that it's XP. Are you supporting versions of Windows older than Vista? If so, you'll need to make a guard for it.

FWIW, Microsoft end of life'd XP in April 2014.

**Comment by headius** [comment]
@djberg96 Good question. I'm not sure we've ever officially said what versions of Windows we support, but XP is so darn old now.

**Comment by djberg96** [comment]
@headius My advice is to NOT support XP, as it will otherwise encourage people to remain on unsupported operating systems when they really, really ought to either upgrade or simply switch to Linux or FreeBSD.

I typically have dropped support about a year after MS drops it for my own projects.

I also imagine that at some point JRuby will require a JRE that is no longer supported on XP, and that will pretty much be the end of it one way or another.

**Comment by pandar1** [comment]
Same problem here... "gem list" gives the same error on windows server 2003

C:\JRAILS~1\APPLIC~1\ASSETS~1>gem list
FFI::NotFoundError: Function 'CreateSymbolicLinkW' not found in [kernel32]
     attach_function at C:/jrails4_update/jruby-9.1.2.0/lib/ruby/stdlib/ffi/library.rb:241
        attach_pfunc at uri:classloader:/jruby/kernel/file.rb:25
  <module:Functions> at uri:classloader:/jruby/kernel/file.rb:31
       <module:File> at uri:classloader:/jruby/kernel/file.rb:16
    <module:Windows> at uri:classloader:/jruby/kernel/file.rb:8
      <module:JRuby> at uri:classloader:/jruby/kernel/file.rb:7
               <top> at uri:classloader:/jruby/kernel/file.rb:6
                load at org/jruby/RubyKernel.java:962
               <top> at file:/C:/jrails4_update/jruby-9.1.2.0/lib/jruby.jar!/jruby/kernel.rb:1

Does this mean windows server 2003 is not supported anymore? :O

**Comment by headius** [comment]
Close in favor of #3998, which is more specific about environment.

**Comment by sevk** [comment]
why not support win2003 server  ?
