### ISSUE TITLE
Apparent Regression: `ruby: warning: unknown property jruby.export`

### ISSUE THREAD

**Issue by JesseHerrick** [jruby/jruby#3940]
### Environment

```
jruby 9.1.1.0 (2.3.0) 2016-05-19 fe84e89 Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [darwin-x86_64]

Darwin MacBook Pro 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
```

### Actual Behavior

`ruby: warning: unknown property jruby.export` is thrown on every command that involves JRuby. 

Relevant: Issue #3034

**Comment by headius** [comment]
Can you show us your environment and exactly how you launch JRuby?

It's not an error that's being thrown, it's just a warning that we don't recognize that property...but how is that property getting into JRuby?

**Comment by JesseHerrick** [comment]
Do you mean what command I'm executing?

I used `jruby -v` for this example, but any command (`gem`, etc.) that invokes JRuby shows the warning.

**Comment by kares** [comment]
seems to be a duplicate of https://github.com/jruby/jruby/issues/3034 ... JRUBY_OPTS left-over or simply some tool using `-Djruby.export`
