### ISSUE TITLE
Array#min doesn't respect monkey patching

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#3944]
### Environment

master

```ruby
p [1, 2, 3].min

class Fixnum
  alias_method :old_cmp, :<=>
  def <=>(other)
    -old_cmp(other)
  end
end

p [1, 2, 3].min
```

### Expected Behavior

```
1
3
```

### Actual Behavior

```
1
1
```

I see this TODO https://github.com/jruby/jruby/blob/dc7c489e418f117018aaae6694bd3f0b78e77a2f/core/src/main/java/org/jruby/RubyArray.java#L4234-L4234, but it looks like it's been forgotten about and this broken behaviour has gone into the release.

**Comment by headius** [comment]
I did not consider the TODO important enough to finish before 9.1, especially since we first need a better mechanism to check for overridden methods without doing a lookup. It was not forgotten...just unlikely to ever be reported by someone who isn't also working on a Ruby implementation.

**Comment by eregon** [comment]
I think bccf82ea0a68439e560f18451daf5d96ecb0af4d from @enebo might address this :)
