### ISSUE TITLE
warning: Ambiguous first argument

### ISSUE THREAD

**Issue by yamam** [jruby/jruby#3946]
### Environment
jruby 9.1.0.0 - 9.1.2.0

### Expected Behavior

```
$ jruby -we 'p({x:-1})'
-e:1: warning: Ambiguous first argument; make sure.
{:x=>-1}
```

### Actual Behavior

jruby 9.0.5.0
```
$ jruby -we 'p({x:-1})'
{:x=>-1}
```

ruby 2.3.1
```
$ ruby -we 'p({x:-1})'
{:x=>-1}
```

**Comment by headius** [comment]
Might be an easy one, eh @enebo?

**Comment by enebo** [comment]
So easy it has been fixed since 9.0.5.0:

```ruby
jruby -we 'p({x:-1})'
-e:1: warning: Ambiguous first argument; make sure.
{:x=>-1}
```
I fixed a lot of parser problems for 9.1.0.0.

**Comment by yamam** [comment]
I tested 9.1.2.0 and 9.1.3.0-SNAPSHOT.
It still occurs.

```
$ jruby -v
jruby 9.1.3.0-SNAPSHOT (2.3.0) 2016-06-09 cd7ac37 OpenJDK 64-Bit Server VM 25.91-b14 on 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14 +jit [linux-x86_64]

$ jruby -we 'p({x:-1})'
-e:1: warning: Ambiguous first argument; make sure.
{:x=>-1}
```

**Comment by yamam** [comment]
Oh I'm sorry, I made a mistake. 

### Expected Behavior
No warnings generate.

### Actual Behavior 
A strange warning(Ambiguous first argument) generates.

**Comment by enebo** [comment]
@yamam ah yes sorry you are correct MRI does not do this.  I will reopen...
