### ISSUE TITLE
Open3.popen3 with block fails on Windows

### ISSUE THREAD

**Issue by elcubo** [jruby/jruby#3948]
### Environment
Windows 7, 64 bit
Jruby 9.1.2.0
Java 1.8.0_91-b14

### Expected Behavior
Running the following program 
```ruby
require 'open3'

Open3.popen3("c:/Windows/System32/whoami.exe", "/?") { |i, o, e| }
```

This should complete without exception.

### Actual Behavior
The program fails with an exception:
```
NotImplementedError: waitpid unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
```

**Comment by elcubo** [comment]
Ran `jruby  -Xnative.verbose=true open3_test.rb` and it returned `Successfully loaded native POSIX impl.`

**Comment by donv** [comment]
@elcubo could you test with JRuby 1.7.25?

**Comment by elcubo** [comment]
I've run my cute little test program on JRuby v1.7.13, and it worked perfectly.

Another thing I should mention is that when running on v9.1.2.0, the parameters to the program being called are getting mixed up somehow.  I'm not quite sure how, but the output from the command (whoami.exe) is
```
ERROR: Invalid argument/option - '{:in=>#<IO:fd 936>, :out=>#<IO:fd 1076>, :err=>#<IO:fd 1084>}'.
```

I don't know if it is related, but my guess is, it is.

**Comment by headius** [comment]
This is likely because we updated open3.rb to match MRI's version, which depends on spawn working properly. Our spawn implementation in Windows is still a bit lacking.

In the short term, we could restore the old open3.rb logic on windows, which should be as good as 1.7 at least. The longer term fix would be to get the proper spawn logic into JRuby.

**Comment by headius** [comment]
Ok, so the Windows logic was moved off to the side in f417f92f0b2316e8923ce1ac5628507210295ce2 and then the short-circuited load in open3.rb was lost again in 66570f070229525f1c1b37fc4eb6f51c0fc96dec.

I'm restoring the short-circuit logic, which should get us back to at least 1.7.25 level.

**Comment by elcubo** [comment]
Verified on nightly build.  Thanks!  :sunglasses:
