### ISSUE TITLE
Running with flag --enable-frozen-string-literal crashes stdlib/jar_dependencies.rb

### ISSUE THREAD

**Issue by brometeo** [jruby/jruby#3975]
### Environment

JRuby version: 9.1.2.0

### Expected Behavior

Work normally

### Actual Behavior

It crashes because of jruby-9.1.2.0/lib/ruby/stdlib/jar_dependencies.rb line 356:
`file = "#{group_id.gsub( '.', '/' )}/#{artifact_id}/#{version}/#{artifact_id}-#{version}"`

It should be substituted by:
`file = String.new("#{group_id.gsub( '.', '/' )}/#{artifact_id}/#{version}/#{artifact_id}-#{version}")`

for creating a mutable String object.

**Comment by kares** [comment]
thanks, this is likely an issue of https://github.com/mkristian/jar-dependencies // cc @mkristian

**Comment by brometeo** [comment]
Thank you. I have written it in jar-dependencies page :)

**Comment by mkristian** [comment]
https://github.com/mkristian/jar-dependencies/issues/48 as we might want to have this in the next release with fixed version of jar-dependencies

**Comment by headius** [comment]
@mkristian Can we get that done ASAP? We'd like to do 9.1.3.0 release some time next week.

**Comment by mkristian** [comment]
@headius will do it over the weekend
