### ISSUE TITLE
OpenSSL::SSL::SSLContext does not implement npn_protocols 

### ISSUE THREAD

**Issue by ostinelli** [jruby/jruby#3987]
```
jruby-9.0.5.0
Darwin 14.5.0 Darwin Kernel Version 14.5.0: root:xnu-2782.50.3~1/RELEASE_X86_64 x86_64
```

[`npn_protocols`](http://ruby-doc.org/stdlib-2.2.0/libdoc/openssl/rdoc/OpenSSL/SSL/SSLContext.html#npn_protocols-attribute-method) allows to set the protocols to be advertised as the list of supported protocols for Next Protocol Negotiation. This is very useful in HTTP/2, since the protocol is still in draft and some servers will not accept calls without a clear statement on the protocol used in the request.

Without this method, it is not possible to build highly-compatible HTTP/2 clients in JRuby.

**Comment by kares** [comment]
do not think this can be supported seamlessly as there's no standard API for NPN with the Java SSL engine. 
its possible but we would likely need a [custom provider](https://github.com/benmmurphy/ssl_npn) or at least some hooks to be implemented. you could move this feature requests to https://github.com/jruby/jruby-openssl/issues

**Comment by ostinelli** [comment]
Moved https://github.com/jruby/jruby-openssl/issues/99.
