### ISSUE TITLE
JRubyFX application not working when running from jar (works in 1.7, doesn't work in 9k)

### ISSUE THREAD

**Issue by oreoshake** [jruby/jruby#4000]
### Environment

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
  * `jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [darwin-x86_64]`
* Operating system and platform (e.g. `uname -a`)
  * `Darwin Neils-MacBook-Pro-4.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64`

Other relevant info you may wish to add:
* Installed or activated gems
  * https://github.com/oreoshake/jrubyfx-9k-jar-problems/blob/master/Gemfile.lock
* Application/framework version (e.g. Rails, Sinatra)
  * JrubyFX
* Environment variables

### Expected Behavior

The test application at https://github.com/oreoshake/jrubyfx-9k-jar-problems should build and run just fine. `$ bundle && rake && java -jar BrakemanPro.jar` should launch the app.

### Actual Behavior

builds and runs just fine under jruby 1.7.21, but fails under 9k:

```
$ bundle && rake && java -jar BrakemanPro.jar
Errno::ENOENT: No such file or directory - classpath:/Users/neilmatatall/workspace/jrubyfail/brakeman-pro/jar-bootstrap.rb
          realpath at org/jruby/RubyFile.java:810
  require_relative at uri:classloader:/jruby/kernel/kernel.rb:11
             <top> at classpath:jar-bootstrap.rb:1
```

But if I unzip the jar and run the file directly, everything is happy:

```
$ mkdir tmp && cp BrakemanPro.jar tmp/ && cd tmp && unzip BrakemanPro.jar 
... accept the file overwrites ... 
$ ruby jar-bootstrap.rb
```

There's also a flag for compiling code and using that in the jar, but I ran into errors that I can  no longer reproduce so it's disabled by default.

Since we're not using much of JRubyFX to build the jar, I assumed the problem lies with some difference between jruby 1.7 and 9k instead of a jrubyfx problem but I could of course be wrong.

EDIT:

I lied, this could also be a jrubyfx thing since I do call the jarify command:
```ruby
system 'bundle exec jrubyfx-jarify . --main bin/brakeman_pro_jar.rb BrakemanPro.jar --include-jars --verbose --name "BrakemanPro"'
```

I will file an issue there too.

**Comment by headius** [comment]
My first guess would be that the `require_relative` impl in 9k uses `realpath` where 1.7 doesn't, and `realpath` may not work right with a jar URL. Maybe @mkristian has some thoughts. I'll try a reduced repro with just `realpath`

**Comment by headius** [comment]
7e7292e632bd66a95fed78b37e73d6e63f90d631 appears to be the commit that introduced `File.realpath` use in `require_relative`. This change *does* appear in JRuby 1.7, in e88a5949f0ae2e495283baafe0f456697a42d0e8, but JRuby 1.7.21 was released about a month prior so you wouldn't see it.

Perhaps you can try to reproduce it with 1.7.22 or higher?

Definitely seems likely that this is an issue with `File.realpath` inside a jar.

**Comment by headius** [comment]
Ok, it does *seem* like `File.realpath` has support for classpath URLs, so the bug must be deeper than my quick read-through.

If you could reproduce with `-Xbacktrace.style=full` passed to JRuby, it would help us pinpoint where inside JRuby it blows up.

Ping @mkristian @kares for suggestions.

**Comment by oreoshake** [comment]
Aha! So it's not a jruby 9k issue. Doing the same thing with jruby-1.7.25 produces a similar, but different error:

```
Errno::ENOENT: No such file or directory - classpath:/Users/neilmatatall/workspace/jrubyfail/brakeman-pro/jar-bootstrap.rb
          realpath at org/jruby/RubyFile.java:820
  require_relative at file:/Users/neilmatatall/workspace/jrubyfail/brakeman-pro/BrakemanPro.jar!/jruby/kernel19/kernel.rb:11
            (root) at classpath:jar-bootstrap.rb:1
```

> If you could reproduce with `-Xbacktrace.style=full` passed to JRuby, it would help us pinpoint where inside JRuby it blows up.

Any tips on where this would be passed in? I'm afraid the layers of indirection have me at a loss on how to accomplish this. `JRUBY_OPTS="-Xbacktrace.style=full" java -jar BrakemanPro.jar` doesn't seem to do anything.

**Comment by oreoshake** [comment]
OK, after doing some RTFM'ing, I got more detailed output @headius:

```
Errno::ENOENT: No such file or directory - classpath:/Users/neil/workspace/jrubyfx-9k-jar-problems/.tmp/jar-bootstrap.rb
        getStackTrace at java/lang/Thread.java:1552
     getBacktraceData at org/jruby/runtime/backtrace/TraceType.java:246
         getBacktrace at org/jruby/runtime/backtrace/TraceType.java:47
     prepareBacktrace at org/jruby/RubyException.java:236
             preRaise at org/jruby/exceptions/RaiseException.java:214
             preRaise at org/jruby/exceptions/RaiseException.java:181
               <init> at org/jruby/exceptions/RaiseException.java:111
    newRaiseException at org/jruby/Ruby.java:4175
  newErrnoENOENTError at org/jruby/Ruby.java:3787
             realpath at org/jruby/RubyFile.java:810
                 call at org/jruby/internal/runtime/methods/JavaMethod.java:720
                 call at org/jruby/internal/runtime/methods/DynamicMethod.java:197
         cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:313
                 call at org/jruby/runtime/callsite/CachingCallSite.java:163
          processCall at org/jruby/ir/interpreter/InterpreterEngine.java:316
            interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:77
            interpret at org/jruby/ir/interpreter/InterpreterEngine.java:86
     INTERPRET_METHOD at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:179
     require_relative at uri:classloader:/jruby/kernel/kernel.rb:11
                 call at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:165
                 call at org/jruby/internal/runtime/methods/DynamicMethod.java:197
         cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:313
                 call at org/jruby/runtime/callsite/CachingCallSite.java:163
                <top> at classpath:jar-bootstrap.rb:1
  invokeWithArguments at java/lang/invoke/MethodHandle.java:627
                 load at org/jruby/ir/Compiler.java:111
            runScript at org/jruby/Ruby.java:833
            runScript at org/jruby/Ruby.java:825
          runNormally at org/jruby/Ruby.java:760
          runFromMain at org/jruby/Ruby.java:579
        doRunFromMain at org/jruby/Main.java:425
          internalRun at org/jruby/Main.java:313
                  run at org/jruby/Main.java:242
                 main at org/jruby/Main.java:204
                 main at org/jruby/JarBootstrapMain.java:57
```

**Comment by headius** [comment]
Very strange. Your case seems to be erroring against a classpath URL that contains your full system path. I'm not sure how that would happen. require_relative uses the caller's frame, from Kernel#caller, to determine the source location in the calling method. In my attempt to reproduce the issue, that path appeared to be correct. require_relative then takes that path and uses it to require the file in question. I get to that point in my local test of a hand-made jar. I never get an ENOENT.

I am trying to reproduce with your repo now.

**Comment by headius** [comment]
I can reproduce it! Very strange.

**Comment by headius** [comment]
Oh ho, I think I may have a clue!

My hand-reproduction was still not failing, so I looked at how JarBootstrapMain boots up. It tries to load the jar-bootstrap.rb file from classpath, but uses a URL without a slash in it:

```java
public class JarBootstrapMain {
    public static final String JAR_BOOTSTRAP = "classpath:jar-bootstrap.rb";
    public static void main(String[] args) {
        String[] newArgs = new String[args.length + 1];
        newArgs[0] = JAR_BOOTSTRAP;
        System.arraycopy(args, 0, newArgs, 1, args.length);
        Main.main(newArgs);
    }
}
```

This makes the jar-bootstrap.rb file look like a *relative* path, and it gets expanded somewhere along the way (probably by realpath) with the only path we know about: the current directory. So we get a classpath URL pointing at an absolute system path.

This exists in both 1.7 and 9k, but probably only became an issue once we started to use realpath for require_relative. Adding a slash to make these be absolute classpath URLs should fix the issue.

**Comment by headius** [comment]
Well, that's progress...I managed to get past the ENOENT. Unfortunately now I get the other error I was seeing, a LoadError when it actually tries to do the require within the jar. We must go deeper!

**Comment by oreoshake** [comment]
so much :heart: @headius

**Comment by headius** [comment]
I went ahead and pushed the additional change. I'm still not certain why it's needed for 9k and not for 1.7.

And with your repo...success! I think!

```
$ java -jar BrakemanPro.jar 
Please run `rake reflect` to generate the imports
```

It appears to be booting properly, but I don't know how to use it :-)

Optimistically calling this one fixed.

**Comment by oreoshake** [comment]
Thanks @headius. We're past this error and on to another `require`-related bug. I'll make sure it repros on my test repo and create a new issue with ⬆️  debug info.

**Comment by headius** [comment]
Sounds good, thanks!

**Comment by oreoshake** [comment]
Just wanted to report back on this. I was able to workaround the newer issues I stumbled upon and our app is up and running in all envs on `jruby-head` 🎊  🎉 . 

I did run across an issue with `require_relative` and `../../dir/path` type calls. I'll try to create a reproducible test case but this task that I've been putting off for at least a year can be declared complete ❗ 🎉  ❗ 

We'll pin to `jruby-head` until the next release. Much :heart: @headius.

**Comment by griest024** [comment]
@oreoshake were you able to get past the `Please run `rake reflect` to generate the imports` message?

I created an issue at jruby/jrubyfx#101 but haven't been able to resolve it. Is it related to `require_relative` issues?

**Comment by oreoshake** [comment]
> @oreoshake were you able to get past the Please runrake reflect to generate the imports message?

Yes, I commented over on https://github.com/jruby/jrubyfx/issues/101#issuecomment-240812987, but something about the way jrubyfx is checking things on disk has changed - maybe this is more of a jrubyfx bug however.

The two lines in question:

`$LOAD_PATH.inject(false) { |res,i| res || i.include?(".jar!/META-INF/jruby.home/lib/ruby/")}` (bypassed in https://github.com/BrakemanSecurityInc/jrubyfx/commit/5e36e097a33ed275741342d92d91b36628c7c68b)

and

`File.size? "#{File.dirname(__FILE__)}/jrubyfx/imports.rb"` (bypassed in https://github.com/BrakemanSecurityInc/jrubyfx/commit/d988324b9d5bf3b2c4bad00553d6129576de00fd and https://github.com/BrakemanSecurityInc/jrubyfx/commit/ed2279668d62c63ddba084828a8bda1fb8f26f3a)
