### ISSUE TITLE
gem list don't show some gems as default

### ISSUE THREAD

**Issue by etehtsea** [jruby/jruby#4019]
`jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.77-b03 on 1.8.0_77-b03 [darwin-x86_64]`

```
$ gem list |grep default 
jar-dependencies (default: 0.3.2)
minitest (5.9.0, 5.8.4, default: 5.4.1)
net-telnet (default: 0.1.1)
power_assert (default: 0.2.3)
rake (11.2.2, 10.5.0, default: 10.4.2, 10.1.1)
rdoc (4.2.2, default: 4.2.0)
test-unit (default: 3.1.1, 2.5.5)
```

Gems that are missing from this list:
- racc
- psych
- json
- jruby-openssl

```
$ gem uninstall json
ERROR:  While executing gem ... (Gem::InstallError)
    gem "json" cannot be uninstalled because it is a default gem
```

P.S. Why rake is default on JRuby and is not on MRI?

**Comment by mkristian** [comment]
rake is preinstalled with jruby but should not be a default gem.

the rest looks inconsistent as well.

**Comment by etehtsea** [comment]
Okay, issue that some gems aren't shown as `default` is unrelated to JRuby itself.
Leaving it open until rubygems will be updated.

**Comment by headius** [comment]
@etehtsea Help us by letting us know when there's a RubyGems release out. We can pull it into 9.1.3.0 if it's not too drastic.

**Comment by etehtsea** [comment]
@headius for sure

**Comment by headius** [comment]
I don't think this will be ready for 9.1.3.0. Bumping.

**Comment by etehtsea** [comment]
please reopen, because fix didn't get into release.

**Comment by headius** [comment]
Still waiting on a RubyGems release with the patch in question. We can patch it ourselves, but the first time anyone (or anything, like rvm) updates RubyGems, it will wipe out our change.

I have requested a backport of the patch and a 2.6.9 release of RubyGems in rubygems/rubygems#1685.

**Comment by kares** [comment]
this one is resolved by now, right? I am seeing default gems being reported using the current SNAPSHOT

**Comment by etehtsea** [comment]
@kares it seems that currently bundled rubygems is patched, but there is still no upstream rubygems version with this fix.

**Comment by headius** [comment]
I'm going to close this. If there's a RubyGems fix we don't have, or a fix that's not in RG, that needs to happen first. But we will be on latest RG for 9.2.
