### ISSUE TITLE
String range object incorrectly tries to convert to int

### ISSUE THREAD

**Issue by rovf** [jruby/jruby#4021]
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15 +jit [Windows 7-amd64]

Consider the following programs:

    mystr='2202702806'; (mystr..mystr).member?(mystr)

Or alternatively:

    ("2202702806".."2202702806").to_a

These are string ranges, and it works in MRI Ruby (the first example should return true, and the second one should returne a one-element array). In JRuby, I get an error:

    RangeError: integer 2202702806 too big to convert to `int'

It seems that JRuby tries to convert the range bounds into Java int values!

**Comment by rovf** [comment]
I just noticed that the same problem occurs on 

   jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) 64-Bit Server VM 24.79-b02 on 1.7.0_79-b15 +jit [Windows 7-amd64]

as well.

**Comment by kares** [comment]
present in latest 9K (9.1.2.0) as well ... maybe the index is too big when `to_a` converting to `Array`

**Comment by rovf** [comment]
On Tue, Jul 19, 2016, at 13:33, Karol Bucek wrote:
> present in latest 9K (9.1.2.0) as well ... maybe the index is too big
> when `to_a` converting to `Array`

I don't think so, for two reason: First, the array would contain only 1
element in the example which I have provided; second, the error does
also occur if we don't use to_a. See my other example. 

I didn't look at the Ruby code, but from the behaviour, a wild guess
would be, that JRuby became a victim of its own optimization:

Ranges of strings are defined (according to the docs) in terms of the
succ method and the <=> operator. Both work fine with the string given
in my example, so I don't think there is an error in this part. I don't
see any reason, why JRuby wants to convert the start or end of the range
into a Java-int. I would be surprised, if this was done for
optimization, for Range#member? can be done easily on strings too (one
doesn't gain that much when holding the values as int).

Ronald

**Comment by rovf** [comment]
On Tue, Jul 19, 2016, at 17:53, Karol Bucek wrote:
> Closed #4021 via 9c1abe71858061338e064b124d723569a23d8a3c.

Thank you for fixing this so quickly. Just a personal question: Why is
it necessary to convert a string to an integer, when the string consists
of digits only? For example 

    ('1234567'..'1234569').member?('12345678')

causes a conversion to int, while the seemingly similar

    ('1234567A'..'1234569Z').member?('12345678G')

works fine. Why is it that not all strings are treated equal in a Range?

Ronald
