### ISSUE TITLE
ArgumentError: invalid encoding when using NKF

### ISSUE THREAD

**Issue by xinqinglxl** [jruby/jruby#4033]
Got an invalid encoding when deal file whose contents is Japanese.
eg. test.txt (The encoding is UTF-8 without BOM)
------------
テスト#means test
------------
 Here is the code:

` lines = NKF.nkf('-w', File.read('test.txt')).split(/\r?\n/).map{|line| line.chomp}`

Then I got the exception

> ArgumentError: invalid encoding
>     nkf at org/jruby/ext/nkf/RubyNKF.java:228
>   <top> at test.rb:106

### Environment
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) Client VM 24.80-b11 on
 1.7.0_80-b15 +jit [Windows 7-x86]

**Comment by k77ch7** [comment]
@xinqinglxl the above script doesn't reproduce. Works for me.

### My Environment

jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 Java HotSpot(TM) 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [darwin-x86_64]

**Comment by headius** [comment]
This was fixed for 9.1 in efae5ad687e65220cf470171769ac02eede12641.
