### ISSUE TITLE
Java array (Enumerable) does not handle last()

### ISSUE THREAD

**Issue by kares** [jruby/jruby#4039]
```
jruby-9.1.2.0 :001 > [1, 2, 3].to_java.is_a? ArrayJavaProxy
 => true 
jruby-9.1.2.0 :002 > [1, 2, 3].to_java.is_a? Enumerable
 => true 
jruby-9.1.2.0 :003 > [1, 2, 3].to_java.last
NoMethodError: undefined method `last' for java.lang.Object[1, 2, 3]@1139b2f3:#<Class:0x7a69b07>
	from (irb):3:in `<eval>'
	from org/jruby/RubyKernel.java:983:in `eval'
	from org/jruby/RubyKernel.java:1290:in `loop'
	from org/jruby/RubyKernel.java:1103:in `catch'
	from org/jruby/RubyKernel.java:1103:in `catch'
	from /opt/local/rvm/rubies/jruby-9.1.2.0/bin/irb:13:in `<top>'
jruby-9.1.2.0 :004 > [1, 2, 3].to_java.count
 => 3 
jruby-9.1.2.0 :005 > [1, 2, 3].to_java.count { |e| e>=2  }
 => 2 
```
same on 1.7.x

... which seems unintended or is it not ?!

**Comment by enebo** [comment]
@kares last is not in Enumerable although strangely first is.  I think last is Ruby Array method specifically.  Not sure if this matters or not since it is somewhat a reasonable method to consider to add.

**Comment by kares** [comment]
@enebo right, thanks! I actually knew this a few weeks back ... seemed weird - why would it be removed :)
will most likely add `last` and `last(count)` just like Ruby's Array (and java.util.List) has.

**Comment by kares** [comment]
supported since https://github.com/jruby/jruby/commit/ddf7fa103371e8bc89867c4913d9ce8afb10cb9c
