### ISSUE TITLE
Wrong line numbers in Kernel#caller inside set_trace_func (with code to reproduce)

### ISSUE THREAD

**Issue by ivoanjo** [jruby/jruby#4051]
I was trying to see if I could get [`pry-nav`](https://github.com/nixme/pry-nav) to work with JRuby. It doesn't have a lot of features, but it's a straightforward use of `set_trace_func` and I wanted to experiment with it a bit.

I hit some issues, and investigating them led me to discover that when running code inside `set_trace_func` and then calling `Kernel#caller` (such as when stepping) leads to line numbers being wrong in the stack trace, which confuses `pry`.

### Environment

Running `jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f OpenJDK 64-Bit Server VM 25.91-b14 on 1.8.0_91-8u91-b14-3ubuntu1~15.10.1-b14 [linux-x86_64]` on `Ubuntu 15.10`.

### Expected Behavior

Example code:
```ruby
def sum(arg1, arg2)
  arg1 + arg2
end

def crazy_sums
  sum(1, 2)
end

set_trace_func proc { |type, _, line, *stuff|
  unless ['c-return', 'c-call'].include? type
    puts "Event #{type} @ #{line}, caller: #{caller.first}"
  end
}

crazy_sums
```

Output in MRI 2.3.1:
```
Event line @ 15, caller: test.rb:15:in `<main>'
Event call @ 5, caller: test.rb:5:in `crazy_sums'
Event line @ 6, caller: test.rb:6:in `crazy_sums'
Event call @ 1, caller: test.rb:1:in `sum'
Event line @ 2, caller: test.rb:2:in `sum'
Event return @ 3, caller: test.rb:3:in `sum'
Event return @ 7, caller: test.rb:7:in `crazy_sums'
```
With MRI, `caller.first` matches the line we get in `set_trace_func`.

### Actual Behavior

Output in JRuby:
```
Event line @ 15, caller: test.rb:9:in `<top>'
Event call @ 5, caller: test.rb:15:in `crazy_sums'
Event line @ 6, caller: test.rb:15:in `crazy_sums'
Event call @ 1, caller: test.rb:6:in `sum'
Event line @ 2, caller: test.rb:6:in `sum'
Event return @ 3, caller: test.rb:2:in `sum'
Event return @ 7, caller: test.rb:6:in `crazy_sums'
```
With JRuby, the line numbers don't match the line we get in `set_trace_func`.

There is also a minor difference where MRI calls the top-level `<main>` while JRuby uses `<top>`. This seems minor, but I can report it as a separate issue if needed.

**Comment by enebo** [comment]
Commit 44a2aa6 fixes us reporting top vs main.   Throwing it on this issue versus making a new one.

**Comment by enebo** [comment]
@ivoanjo heya.  I think I fixed the rest of this.  I can see two potential failure paths though:

1. It is possible I am missing return for non-methods.  This is less clear to be based on how these are emitted but if someone can find a test case I will fix it.
2. Something is really screwy with our AST generation of statements which include keywords.  I half expect to uncover some issues there.  However, stuff like 'foo if true'  is pretty rare and doubly rare for you to care about it in set_trace_func.

@ivoanjo If you can kick the tires it might be the best we can do for verifying this for the next JRuby release.

**Comment by ivoanjo** [comment]
Wow, nice to see you picked up the hard part after I did the easy one ;)

I'll try `set_trace_func` in a bigger codebase, see if I can spot any inconsistencies, and report back.

**Comment by ivoanjo** [comment]
Ok so I did a few tests and it seems like the lines are correct between the backtrace and what `set_trace_func` gets and match with MRI outputs.

The exception I saw was `end` trace events, which are reported off-by-one between what caller and `set_trace_func`, but also in many cases neither value is correct when comparing with the file and MRI.

**Comment by enebo** [comment]
@ivoanjo If you can distill some snippets then I will try and knock these down.  I did run into something where an extra keyword in a line can cause it to bump forward by one (which is super confusing output from the parser).  Open them as new issues.
