### ISSUE TITLE
Double-splat should not work with non-symbol keys

### ISSUE THREAD

**Issue by ivoanjo** [jruby/jruby#4055]
So for curiosity I ran a codebase which has been using JRuby from day one through MRI and some of the specs started failing. Looking at it, it seems JRuby is much more permissive than MRI with the double-splat, which in this case led my team to write code that is accepted by JRuby (and passes the specs) but is wrong as seen by MRI.

### Environment

Running `jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f OpenJDK 64-Bit Server VM 25.91-b14 on 1.8.0_91-8u91-b14-3ubuntu1~15.10.1-b14 [linux-x86_64]` on `Ubuntu 15.10`.

### Expected Behavior

Example code:
```ruby
foo = {1 => 'hello', 'world' => 'foo', Object.new => 'bar'}

baz = {**foo}

puts baz
```

Output in MRI 2.3.1:
```
example.rb:3:in `<main>': wrong argument type Fixnum (expected Symbol) (TypeError)
```

### Actual Behavior

Output in JRuby:
```
{1=>"hello", "world"=>"foo", #<Object:0x3b0143d3>=>"bar"}
```

(E.g. JRuby is happy to allow double-splatting of non-symbol keys).

**Comment by enebo** [comment]
This is a variant of another problem we knew we had.  The other issue (don't see it offhand in our tracker) we need to split incoming symbol from non-symbol keys on the receiving side.  Your bug is on the other end that kwarg-splatting does not allow that mixture at all.
