### ISSUE TITLE
Unusual regression in Range#to_a

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4069]
There was a strange regression in the behavior of the following expression:

```ruby
('2202702806'..'2202702806').to_a
```

This is tested in the jruby suite at test/jruby/test_array.rb:42.

I will commit a patch shortly that fixes it, but I'm confused how this ever would have worked. I need to bisect to make sure nothing else is broken.

**Comment by kares** [comment]
similar case has been (reported and) fixed with https://github.com/jruby/jruby/commit/9c1abe71858061338e064b124d723569a23d8a3c (for 9.1.3.0)

**Comment by headius** [comment]
@kares Did we do a bad merge and lose the fix or something? It was definitely still int on master when I patched it.

For now we'll call it fixed and blame the regression on gremlins.
