### ISSUE TITLE
Disable/fix AppVeyor

### ISSUE THREAD

**Issue by etehtsea** [jruby/jruby#4075]
I think many people feel a little bit uncomfortable when everything marked as failing.  😬 

Thank you!

**Comment by headius** [comment]
Agreed.

**Comment by etehtsea** [comment]
So could you please disable appveyor webhook in github project settings?

**Comment by headius** [comment]
@etehtsea I will do so.

@enebo @nirvdrum Any objections? I think if we're going to have it hooked up, we need to have it green. If we can get it green, that's cool...but I don't know status there.

**Comment by mprins** [comment]
currently it is failing because Apache moved stuff around on their download site, so the script can't find Maven.

I will prep a PR to update the build file

**Comment by enebo** [comment]
@mprins How we retrieve wlll need to change because it seems older versions are not retained as links.  I updated this once before about a month ago.

jruby-1_7 branch is green but master is not.  I am happy to turn off master until 9.1.3.0 is out but we really need at least a little windows coverage happening soon.

**Comment by mprins** [comment]
Ideally AppVeyor would have a pre-installed, recent version of Maven in their build image.
Any chance of that happening @FeodorFitsner ?

**Comment by FeodorFitsner** [comment]
The issue with pre-installed Maven is that we have several Java SDKs pre-installed on build worker VM.

**Comment by mprins** [comment]
Opened RFE: appveyor/ci#998

**Comment by nirvdrum** [comment]
@enebo Can we use the mvnw helper in the meanwhile?

**Comment by enebo** [comment]
@nirvdrum I guess it depends on whether it will download it every job or not.  If it gets saved in a place where it is not wiped out every build then that would be a good solution.

**Comment by mprins** [comment]
there is a `cache` directive at the bottom of the `appveyor.yml` that you can use to cache directories, atm it caches the maven directory (until the  `appveyor.yml` is touched ) and the .m2 directory until the pom is touched.
