### ISSUE TITLE
concurrent loading does not resolve loaded constant

### ISSUE THREAD

**Issue by kares** [jruby/jruby#4091]
seems to be a regression compared to 1.7 or even 9.0.5

a bit tricky - so far I have been only able to do a reproduction case that 'sometimes' fails : 

https://gist.github.com/kares/596f5a3648249181373dca2242332613

```
#<JRuby::Sample:0x1a09f207>
ERROR: #<NameError: uninitialized constant JRuby::Sample>
  org/jruby/RubyModule.java:3309:in `const_missing'
  repro/_run.rb:8:in `block in repro/_run.rb'
#<JRuby::Sample:0x3bf68c46>
```

HINT: loading seems to always fail from the same thread as the one first hitting the `require`.

**Comment by kares** [comment]
full raw trace on `NameError` with current master : 
```
  org/jruby/exceptions/RaiseException.java:214:in `preRaise'
  org/jruby/exceptions/RaiseException.java:181:in `preRaise'
  org/jruby/exceptions/RaiseException.java:141:in `<init>'
  org/jruby/exceptions/RaiseException.java:72:in `<init>'
  org/jruby/Ruby.java:3940:in `newNameError'
  org/jruby/RubyModule.java:3335:in `const_missing'
  org/jruby/RubyModule$INVOKER$i$1$0$const_missing.gen:-1:in `call'
  org/jruby/internal/runtime/methods/JavaMethod.java:383:in `call'
  org/jruby/RubyClass.java:879:in `finvoke'
  org/jruby/runtime/Helpers.java:406:in `invoke'
  org/jruby/RubyBasicObject.java:358:in `callMethod'
  org/jruby/ir/targets/ConstantLookupSite.java:119:in `searchModuleForConst'
  ../jruby-rack-worker/repro/_run.rb:8:in `block in ../jruby-rack-worker/repro/_run.rb'
  org/jruby/runtime/CompiledIRBlockBody.java:145:in `callDirect'
  org/jruby/runtime/IRBlockBody.java:64:in `call'
  org/jruby/runtime/Block.java:126:in `call'
  org/jruby/RubyProc.java:342:in `call'
  org/jruby/RubyProc.java:248:in `call'
  org/jruby/internal/runtime/RubyRunnable.java:104:in `run'
  java/lang/Thread.java:745:in `run'
  java/lang/Thread.java:1556:in `getStackTrace'
  org/jruby/runtime/backtrace/TraceType.java:246:in `getBacktraceData'
  org/jruby/runtime/backtrace/TraceType.java:47:in `getBacktrace'
  org/jruby/RubyException.java:235:in `prepareBacktrace'
  org/jruby/exceptions/RaiseException.java:214:in `preRaise'
  org/jruby/exceptions/RaiseException.java:181:in `preRaise'
  org/jruby/exceptions/RaiseException.java:141:in `<init>'
  org/jruby/exceptions/RaiseException.java:72:in `<init>'
  org/jruby/Ruby.java:3940:in `newNameError'
  org/jruby/RubyModule.java:3335:in `const_missing'
  org/jruby/RubyModule$INVOKER$i$1$0$const_missing.gen:-1:in `call'
  org/jruby/internal/runtime/methods/JavaMethod.java:383:in `call'
  org/jruby/RubyClass.java:879:in `finvoke'
  org/jruby/runtime/Helpers.java:406:in `invoke'
  org/jruby/RubyBasicObject.java:358:in `callMethod'
  org/jruby/ir/targets/ConstantLookupSite.java:119:in `searchModuleForConst'
  ../jruby-rack-worker/repro/_run.rb:8:in `block in ../jruby-rack-worker/repro/_run.rb'
```

**Comment by headius** [comment]
It looks to me like there's a bug in how we lock down concurrent requires. I suspect the failing thread is passing over the require call before it is complete, proceeding to access constants that are not there.

I'll be poking at this today.

**Comment by kares** [comment]
that's what I thought but the thread doing the require than fails resolving the constant.

**Comment by headius** [comment]
Are you sure? Here's output from my run, logging each thread before it attempts to read or write `Sample` constant:

```
[] ~/projects/jruby $ jruby -X-C -I. blah.rb
main is #<Thread:0x536aaa8d>
#<Thread:0x138ef471> accessing Sample
#<Thread:0x267a6717> accessing Sample
#<Thread:0x138ef471> error#<Thread:0x267a6717> error
#<Thread:0x1cc58fd0> about to define Sample

#<Thread:0x1cc58fd0> accessing Sample
#<JRuby::Sample:0x18fa0890>
```

This shows three non-main threads attempting to load that file and access that constant. Notice that "71" and "17" say they're going to access `Sample` before "d0" says it's about to define it, and the two formers both error out because it's not there yet. "d0" successfully accesses sample after defining it.

The only way we'd see "71" and "17" proceed to access without trying to define is if require either told them the file was already required (concurrency problem with loaded features?) or if it allowed them to proceed while the require was still in progress. I suspect the latter, since loaded features shouldn't be updated until the load/require has *completed*.

**Comment by headius** [comment]
On a hunch, I ran with -w. The results are very interesting:

```
[] ~/projects/jruby $ jruby -w -X-C -I. blah.rb
main is #<Thread:0x536aaa8d>
/Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /Users/headius/projects/jruby/sample.rb
/Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /Users/headius/projects/jruby/sample.rb
/Users/headius/projects/jruby/sample.rb:4: warning: Useless use of + in void context.
          require at org/jruby/RubyKernel.java:955
          require at /Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
  block in (root) at blah.rb:6
#<Thread:0x38f2831c> accessing Sample
          require at org/jruby/RubyKernel.java:955
          require at /Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
  block in (root) at blah.rb:6
#<Thread:0x43c0b3f1> about to define Sample#<Thread:0x1199c7ba> accessing Sample

#<Thread:0x1199c7ba> error
#<Thread:0x38f2831c> error
#<Thread:0x43c0b3f1> accessing Sample
#<JRuby::Sample:0x47ff2f51>
```

It seems like the locking logic for require is treating concurrent requires as circular rather than conflicting, and sending the calling thread on its way with nothing but a stern warning.

**Comment by headius** [comment]
And a bit more logging around the require lock confirms it:

```
Thread[Ruby-0-Thread-1: blah.rb:4,5,main] locking /Users/headius/projects/jruby/sample.rb for require
Thread[Ruby-0-Thread-2: blah.rb:4,5,main] locking /Users/headius/projects/jruby/sample.rb for require
Thread[Ruby-0-Thread-2: blah.rb:4,5,main] could not acquire lock for /Users/headius/projects/jruby/sample.rb
Thread[Ruby-0-Thread-3: blah.rb:4,5,main] locking /Users/headius/projects/jruby/sample.rb for require
Thread[Ruby-0-Thread-3: blah.rb:4,5,main] could not acquire lock for /Users/headius/projects/jruby/sample.rb
```

Here we see thread 1 attempt to acquire the lock, and then 2 and 3 follow it. Both 2 and 3 then follow the path that leads to circular warning (requireLocks.lock returned false rather than blocking).

**Comment by headius** [comment]
I should have examined this commit more closely: 455bcf067466d6a356d8efbaa5cc2dc0b490c16f

This is the culprit, and potentially the cause of many other require-time threading bugs we've seen.

This lock can't be a tryLock because we use a false return value here to indicate circular requires. It may have prevented some deadlocks, but only by allowing everyone to ignore the require lock altogether.

We obviously need better tests for this.

**Comment by headius** [comment]
Ref #3341 from the bad commit.

**Comment by headius** [comment]
This should be fixed now by reverting 455bcf067466d6a356d8efbaa5cc2dc0b490c16f in 93707ca.

NEEDS TESTS.

**Comment by headius** [comment]
This also appears to be the cause of other circular require warnings, like those seen in `test:jruby`.

**Comment by kares** [comment]
eh, sorry for the confusion I did not use `puts` as it affected my reproducibility but a concurrent queue of messages printed at the end - lead me wrong. I can confirm its doing good now, have added a test-case. thanks.
