### ISSUE TITLE
Enumerator's Yielder does not pass through one-elt array properly

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4108]
This is the continuation of #3814.

See the discussion there for the long form.

Short form, the following script should produce the given result. Two fail as shown by specs in #3814, and one works currently but may be the incorrect fix (#2458).

``` ruby
class Enumerator::Yielder
    def yield(*args)
      @proc.call(*args)
    end
end

module Enumerable
  def first
    val = nil
    catch(:foo) do
      each do |x|
        val = x
        throw :foo
      end
    end
    val
  end
end

p Enumerator.new {|y| y.yield([1])}.to_a
p Enumerator.new {|y| y << [1]}.to_a
p Enumerator.new {|y| y.yield([1])}.map {|e| e}.to_a
p Enumerator.new {|y| y.yield([1])}.lazy.map {|e| e}.to_a
p Enumerator.new {|y| y.yield [1]}.first
```

```
$ jruby blah.rb
[[1]]
[[1]]
[[1]]
[[1]]
[1]
```

**Comment by glebm** [comment]
I think this is the issue that prevents sassc and sassc-rails from working (`wrong number of arguments (1 for 3)`) on JRuby, while the Ruby version of Sass is deprecated and EOL next March.

**Comment by headius** [comment]
Well, I'm thrilled to see that the native replacement for sass is going to be FFI around libsass! We should prioritize getting this fixed in 9.3 or a 9.2 update by early next year.

**Comment by headius** [comment]
@glebm Can you give us a reproduction of that error?

**Comment by headius** [comment]
@glebm Oh I just noticed sass/sassc-rails#92 👍
