### ISSUE TITLE
Java 9 support

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4111]
We have not yet started testing on Java 9, and there are certain to be some interesting challenges running alongside Jigsaw.

This is a catch-all bug to get Java 9 support working by JRuby 9.2.

Here's what we know is outstanding:
- [x] Booting up currently raises `java.lang.reflect.InaccessibleObjectException`, a new exception in 9 that indicates we can't setAccessible JDK classes. (84b12e7 and 677ce03)
- [x] io/console warnings on startup (#3611)

**Comment by headius** [comment]
84b12e7 and 677ce03 fix the setAccessible problem for master and 1.7, respectively. That fix allows JRuby to at least do `-e 1` and `gem list` on my OS X system with a recent Java 9 EA release.

**Comment by kares** [comment]
"najs" hack - was thinking about approaching Java 8 support (in Java code) by doing a core sub-module but it gets complicated maintenance hell quickly. so your approach is probably the best it gets atm.

on a related note maybe we shall at least consider dropping Java 7 for **9.2** does that sound reasonable (we could do much greater JI when compiling under 8) ?

**Comment by kares** [comment]
just seen https://github.com/jruby/jruby/issues/4112 ... so I guess Java 7 stays in the picture (for 9.2) than :(

**Comment by jordansissel** [comment]
Following up here from https://github.com/jruby/jruby/issues/4558

Running JRuby 9.1.7.0 with a bunch of `--add-opens` flags lets me get to a hello-world:

`ruby -J--add-opens=java.base/{java.lang,java.security,java.util,java.security.cert}=ALL-UNNAMED`

(This adds opens for java.lang, java.security, java.util, and java.security.cert)

**Comment by jordansissel** [comment]
Gem installation seems to fail because RubyZlib fails during installation

* RubyZlib fails during initializer:

```
% ruby -J--add-opens=java.base/{java.lang,java.security,java.util,java.security.cert}=ALL-UNNAMED  -e 'p org.jruby.ext.zlib.RubyZlib'
NameError: cannot initialize Java class org.jruby.ext.zlib.RubyZlib (java.lang.ExceptionInInitializerError)
  method_missing at org/jruby/javasupport/JavaPackage.java:259
          <main> at -e:1
```

**Comment by jordansissel** [comment]
RubyZlib calls [setAccessible on java.util.zip.CRC32 ](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/zlib/RubyZlib.java#L77-L90), so adding `java.util.zip` to `--add-opens` works around this.

**Comment by perlun** [comment]
Do we have any updates on this? (I haven't yet installed Java 9; it was released a couple of weeks ago.)

**Comment by headius** [comment]
JRuby 9.1.14 will work properly on Java 9, albeit with some warnings for some actions. The examples here with `--add-opens` flags provide a fine workaround for now, and we may have to put some of these in our executables.

The other day I ran JRuby 9.1.14 with Rails 5 on JDK9 and it was able to do everything properly without many warnings. I would say we support JDK9 well enough to close this issue.

I will open a new issue for ongoing accessibility warnings, so we can aggregate what flags are needed and get them into the launchers (or find alternative ways that don't trigger warnings).

**Comment by jordansissel** [comment]
Awesome — thank you!
