### ISSUE TITLE
End-of-life for JRuby 1.7.x

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4112]
We currently plan to end our support for JRuby 1.7 at the end of 2016. We believe JRuby 9k has reached a stability and compatibility level that meets (and usually exceeds) JRuby 1.7, and maintaining two major versions is a real headache.

However, we are realistic, and we know there will be outstanding issues for people migrating from 1.7 to 9k. This bug is a placeholder for users to link all their blocking 9k items, so we can have them all in one place.

The sooner we gather these bugs, the sooner we can work toward having a 9k release that's a viable target for all current JRuby 1.7 users.

A few issues we will _not_ be addressing:
- JRuby 9k releases will always support the most-current Ruby version, give or take a version. We will not support 1.8.7, 1.9.3, 2.0, 2.1, or 2.2-specific behavior in any future releases, and once we have Ruby 2.4 support we will no longer support Ruby 2.3-specific behavior.
- JRuby 9k supports Java 7 and higher at present, and we will not work to support earlier versions of Java or the JDK. The one exception would be Android, if we can figure out a way to use the Java 7 features we need there. We may drop Java 7 support some time after Java 9 is released.

Other issues, we'll deal with on a case-by-case basis. Please let us know what's keeping you from migrating to JRuby 9k.

**Comment by netroby** [comment]
So where is the JRuby 10000 or JRuby 10.0.0.0

**Comment by cprice404** [comment]
So far, the things that are keeping us from moving are: #3928 , #3922 , #3921 , and the significantly increased memory overhead.  Some of those things we may be able to work around, and it's possible we'll stumble onto a few more things after we get past those.  Hoping to be able to pick back up on our efforts to explore the upgrade in the next month or two.

**Comment by ssteidte** [comment]
9k not yet running on AIX: https://github.com/jruby/jruby/issues/3495

**Comment by tbeauvais** [comment]
I know it's not your problem, but..... Since Torquebox 4 hasn't been released yet, and does not have all the features of Torquebox 3.x it would be great if Torquebox 3.x shipped with JRuby 9000   https://issues.jboss.org/browse/TORQUE-1259

**Comment by creddy** [comment]
Thank you all for the hard work you put into this project! It is much appreciated. Currently, this one is blocking us from moving to 9.1.3.0 https://github.com/jruby/jruby/issues/4124

**Comment by headius** [comment]
#4124 has been fixed for 9.1.4.0.

**Comment by headius** [comment]
Candidate for inclusion in #1183, too.

**Comment by JasonLunn** [comment]
#4365 prevents 9.1.x.x from being a viable candidate for use in production under OpenJDK 7. Is JRuby's official support going to move to 8 and above?

**Comment by jmiettinen** [comment]
Could we get #4389 to 1.7-branch?

**Comment by headius** [comment]
@jmiettinen I don't see why not. I know @kares had a revision, so I'll dig that up and merge that too.

**Comment by obfuscoder** [comment]
Is there an actual end-of-life date defined for JRuby 1.7.x by now? The initially given date (end of 2016) is obsolete. We need this info in order to decide whether and when we need to migrate.

**Comment by kares** [comment]
@obfuscoder the last (planned) release for JRuby 1.7.x has [already happened](http://jruby.org/2017/05/11/jruby-1-7-27) on May/2017
some jruby-openssl gem releases will still support some of the latest 1.7.x for a while but no JRuby releases are planned at this point.

**Comment by obfuscoder** [comment]
Thanks for your info. One small follow up question tho: Will there still be fixes and releases for the 1.7.x branch for newly found security issues or won't even those issues be fixed?

**Comment by enebo** [comment]
@obfuscoder It is our intent to not release any more but if it was devastatingly bad security issue we may end up releasing it just to not leave anyone hanging.  Thankfully, we have had very few CVEs to deal with over the years so fingers crossed...openssl is the most likely target for security problems in Ruby and that is still being maintained with backwards compat in mind (for now anyways).  If an openssl problem was found then any legacy production envs could update that gem.

**Comment by headius** [comment]
JRuby 1.7.27 appears to be sufficient as a last release for 1.7. We shall call 1.7 officially EOL now.
