### ISSUE TITLE
The child-process gem fails to spawn processes on Windows

### ISSUE THREAD

**Issue by joankaradimov** [jruby/jruby#4122]
### Environment

jruby version: jruby 9.1.3.0 (2.3.1) 2016-08-29 a2a3b29 Java HotSpot(TM) 64-Bit Server VM 25.66-b18 on 1.8.0_66-b18 +jit [mswin32-x86_64]
OS: Windows 10
childprocess version: 0.5.9

### Expected Behavior

Running:
```ruby
gem 'childprocess'
require 'childprocess'
cp = ChildProcess.new('notepad.exe')
cp.start # errors
```
... should spawn a new process. This works on jruby 9.1.2.0

### Actual Behavior

This exception is raised:
```
ChildProcess::Error: Unknown error (Windows says "The operation completed successfully.", but it did not.)
        from C:/dev/jruby-9.1.3.0/lib/ruby/gems/shared/gems/childprocess-0.5.9/lib/childprocess/windows/lib.rb:325:in `handle_for'
        from C:/dev/jruby-9.1.3.0/lib/ruby/gems/shared/gems/childprocess-0.5.9/lib/childprocess/jruby.rb:48:in `windows_handle_for'
        from C:/dev/jruby-9.1.3.0/lib/ruby/gems/shared/gems/childprocess-0.5.9/lib/childprocess/windows/lib.rb:306:in `handle_for'
        from C:/dev/jruby-9.1.3.0/lib/ruby/gems/shared/gems/childprocess-0.5.9/lib/childprocess/windows/process_builder.rb:137:in `std_stream_handle_for'
        from C:/dev/jruby-9.1.3.0/lib/ruby/gems/shared/gems/childprocess-0.5.9/lib/childprocess/windows/process_builder.rb:132:in `setup_io'
        from C:/dev/jruby-9.1.3.0/lib/ruby/gems/shared/gems/childprocess-0.5.9/lib/childprocess/windows/process_builder.rb:32:in `start'
        from C:/dev/jruby-9.1.3.0/lib/ruby/gems/shared/gems/childprocess-0.5.9/lib/childprocess/windows/process.rb:69:in `launch_process'
        from C:/dev/jruby-9.1.3.0/lib/ruby/gems/shared/gems/childprocess-0.5.9/lib/childprocess/abstract_process.rb:82:in `start'
        from (irb):4:in `<eval>'
        from org/jruby/RubyKernel.java:994:in `eval'
        from org/jruby/RubyKernel.java:1295:in `loop'
        from org/jruby/RubyKernel.java:1114:in `catch'
        from org/jruby/RubyKernel.java:1114:in `catch'
        from C:/dev/jruby-9.1.3.0/bin/jirb:13:in `<main>'
```

### Notes

I noticed that issue https://github.com/jruby/jruby/issues/2598 has an identical error message.

**Comment by enebo** [comment]
Running this I can see we bomb out trying to get the handle for stdin.  Something changed since 9.1.2.0

**Comment by headius** [comment]
Tracked it down to the fix for Drip in #2690 (7e024a761e3ecea96c66ecfd33984ceb6ab0c001) which modified stdio behavior to report *actual* fileno rather than always the 0, 1, 2 of typical in, out, err. This works fine on platforms where we can use native IO, but our Windows IO logic is not native yet. In addition, when running without native calls enabled, we still need to gracefully fall back and report 0, 1, 2.

I have a patch in progress.

**Comment by headius** [comment]
Have fix, need tests. Not sure the best way to do this beyond just verifying that in a "simple" JRuby process, stdio has sane filenos.

**Comment by headius** [comment]
All good!
