### ISSUE TITLE
[Truffle] Issue with dispatching to protected method

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#4125]
This is small example of an issue I've seen once before (in a different spec) in dispatch. I think the issue may be in the `UnresolvedDispatchNode` which I've tried to fix without success.

This is found while trying to untag `public_send_spec.rb` tags.

### Example
```ruby
class Foo
      protected
      def bar
        'done'
      end
end
puts Foo.new.public_send(:bar)
```

### Expected Behavior
```sh
../pubsend.rb:10:in `public_send': protected method `bar' called for #<Foo:0x007fd13095a4a8> (NoMethodError)
	from ../pubsend.rb:10:in `<main>'
```

### Actual Behavior
```sh
done
```

**Comment by eregon** [comment]
It's because `public_send` is not ignored when looking the caller frame.

**Comment by eregon** [comment]
Turns out the semantics are simpler than I thought, see 1dc8c8e.
