### ISSUE TITLE
$LOADED_FEATURES.clear does not appear to clear internal set

### ISSUE THREAD

**Issue by headius** [jruby/jruby#413]
We have an internal set in the $LOADED_FEATURES array that allows include? and friends to be O(1) complexity. However, it seems like it's not being cleared properly for some of the Array methods like #clear:

```
system ~/projects/jruby $ jruby -Itmp -e 'puts require "nothing"; $LOADED_FEATURES.clear; puts require "nothing"'
in nothing
true
false

system ~/projects/jruby $ ruby-1.9.3 -Itmp -e 'puts require "nothing"; $LOADED_FEATURES.clear; puts require "nothing"'
in nothing
true
in nothing
true
```

**Comment by headius** [comment]
This is still valid in JRuby 9.1 and should be fixed.

**Comment by kares** [comment]
this seems to be working (on master) now after: https://github.com/jruby/jruby/commit/f147a5e388952684fa5761ba49abac21da34932d + https://github.com/jruby/jruby/commit/e00bf500c294a85a10fc7cd104f146b8be8db58a ... need a similar fix on jruby-1_7

**Comment by kares** [comment]
wasn't fixed in the end - also needed some test tuning as some of the tests influence others.
not sure about the backport for **jruby-1_7** ... no one complained but its probably a good idea.
