### ISSUE TITLE
OpenSSL extension - corrupt CSR

### ISSUE THREAD

**Issue by technion** [jruby/jruby#4130]
### Environment

jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f OpenJDK 64-Bit Server VM 25.102-b14 on 1.8.0_102-b14 +jit [linux-x86_64]
Arch Linux, jRuby installed from AUR.

Linux linodeplz 4.4.0-2-ec2 #1 SMP Thu Jan 21 09:52:26 PST 2016 x86_64 GNU/Linux

Other relevant info you may wish to add:
This issue showed up in part of a Sinatra application, but has been reduced to a minimal test case.

### Expected Behavior

Generate a CSR using the script from this gist. Then use OpenSSL to view.

https://gist.github.com/technion/0e63d42299cc3d91f387d41e9e5c2c74

Under MRI 2.3.1, we can observe this behaviour:

```
$ ./ssltest.rb > mycsr.csr
$ openssl req -in mycsr.csr -noout -text | more
...
            X509v3 Subject Alternative Name:
                DNS:test.example.com, DNS:test2.example.com, DNS:example.com, DNS:www.example.com

```

It can be observed that the "Subject Alternative Name" field correctly matches those defined on line 13 of the gist.

### Actual Behavior

When recreating the above test:

```
$ jruby ./ssltest.rb > mycsr.csr
$ openssl req -in mycsr.csr -noout -text | more
...
           X509v3 Subject Alternative Name:
                .N test.example.com,DNS: test2.example.com,DNS: example.com,DNS: www.example.com
```
You can observe that the first 'DNS' field is broken, and the data appears to have different spacing.

**Comment by kares** [comment]
there's a lot of compatibility details [jruby-openssl](http://github.com/jruby/jruby-openssl) misses. feel free to move the issue [over](http://github.com/jruby/jruby-openssl/issues). thanks!

**Comment by technion** [comment]
@kares Sorry, didn't realise that had a separate wiki. Will move.
