### ISSUE TITLE
avoid JCE CNFE warning on non Oracle/OpenJDK

### ISSUE THREAD

**Issue by kares** [jruby/jruby#4136]
got in with the change set from https://github.com/jruby/jruby/issues/4101 ([details](https://github.com/jruby/jruby/issues/4101#issuecomment-243737644) also there)

... already fixed on master with: https://github.com/jruby/jruby/commit/0355763b6c06665785a31b78082f22e1923c2de5

**Comment by enebo** [comment]
@kares if you plan on backporting this then add a new issue if you want it reported as fixed there as I want this to go into 9.1.5.0 release notes (so I am closing)
