### ISSUE TITLE
Non-ASCII symbol without single quote not right

### ISSUE THREAD

**Issue by personnel** [jruby/jruby#4173]
code:
```
a = :测试
b = :'测试'
puts a,b,a==b

```
output:
```
??
测试
false

```
### Environment

jruby 9.1.5.0 (2.3.1) 2016-09-23 fffffff Java HotSpot(TM) Client VM 25.101-b13 on 1.8.0_101-b13 +jit [mswin32-x86]

**Comment by jsyeo** [comment]
This is a known issue https://github.com/jruby/jruby/issues/3880#issuecomment-219063538

**Comment by headius** [comment]
Yeah, I think we can call this one a duplicate. There's half a dozen issues about this :-(
