### ISSUE TITLE
Inconsistent behaviour of same code in Windows, from not finding an installed gem to missing methods

### ISSUE THREAD

**Issue by abelsromero** [jruby/jruby#4182]
Same code that uses jRuby shows different behaviour depending on whether it is executed from ID (IntelliJ), or a shell script.
Here is the repo to test it: https://github.com/robertpanzer/asciidoctorj-pdf/.
The full explanation of the different cases is here: https://github.com/robertpanzer/asciidoctorj-pdf/issues/3

### Environment
* JRuby version: 9.1.5.0
* Operating system and platform: Windows 7

### Expected Behavior

Tests in the project should execute correctly from shell and IDE.
Or at least, the errors should be consistent and not different depending on where the code is executed.

### Actual Behavior

Depending on whether the code is run as a shell script as part of a Gradle build or executed directly from IntelliJ different errors happen ony on Windows.
Details are here: https://github.com/robertpanzer/asciidoctorj-pdf/issues/3

**Comment by headius** [comment]
Closing as it the difference appears to be due to IntelliJ and Gradle setting up paths differently, rather than a JRuby issue. See my comment in robertpanzer/asciidoctorj-pdf#3.
