### ISSUE TITLE
prime? openssl error in 9.1.5.0

### ISSUE THREAD

**Issue by jzakiya** [jruby/jruby#4193]
### Environment

$ jruby -v
jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 Java HotSpot(TM) 64-Bit Server VM 25.102-b14 on 1.8.0_102-b14 +jit [linux-x86_64]

$ uname -a
Linux localhost 4.7.5-pclos1 #1 SMP Sun Sep 25 17:05:47 CDT 2016 x86_64 x86_64 x86_64 GNU/Linux

### Expected Behavior
```
> require 'openssl'
> 5.to_bn.prime?
 => true
> -5.to_bn.prime?
 => false
```
### Actual Behavior
```
> require 'openssl'
> 5.to_bn.prime?
 => true
> -5.to_bn.prime?     
 => true                  -- should be false, this is an error for all negative primes
```

**Comment by headius** [comment]
Seems legit. Normally I'd ask you to re-file at jruby/jruby-openssl but this seems pretty trivial.

**Comment by headius** [comment]
@kares @mkristian Any reason we couldn't put out a jruby-openssl release right now?

**Comment by headius** [comment]
This is fixed in jruby-openssl and just needs releases.

**Comment by headius** [comment]
Oh...we need tests for this. Want to PR something quick for jruby/jruby-openssl?

**Comment by kares** [comment]
this actually isn't in **9.1.6.0** unless `gem install jruby-openssl`, updated gem (0.9.18) should be in **9.1.7.0**
