### ISSUE TITLE
**operator behavior is different from MRI

### ISSUE THREAD

**Issue by personnel** [jruby/jruby#4210]
```
class AA < BasicObject
	def to_hash
		{}
	end
end

obj = AA.new

def func(**hash)
	puts hash
end

func **obj          # <- error on this line

```
run ok in MRI,but jruby report error :
```
NoMethodError: undefined method `respond_to?' for #<AA:0x282003e1>
  <main> at test.rb:13
    load at org/jruby/RubyKernel.java:974
  <main> at -e:1

```
i found jruby call `respond_to? :to_hash` before call `to_hash`,but MRI not.

### ENV
jruby 9.1.5.0 (2.3.1) 2016-09-23 fffffff Java HotSpot(TM) Client VM 25.101-b13 on 1.8.0_101-b13 +jit [mswin32-x86]

**Comment by headius** [comment]
It looks like we're doing 1.8 conversion logic for this case (and several others) rather than 1.9+ "checked" conversion logic. I have a fix coming that should solve this and prevent other reports down the line (by making the old 1.8 methods just call 1.9 logic).
