### ISSUE TITLE
IO.select breaks SSLSocket#read_nonblock on Linux

### ISSUE THREAD

**Issue by ferrous26** [jruby/jruby#423]
I've found another strange issue with `SSLSocket` and `IO.select` on Linux systems.

If input is not ready when I call `#read_nonblock` and I rescue and then call `IO.select` I will get a string of nulls from `#read_nonblock` when `IO.select` returns. However, if I just use `sleep` instead of `IO.select` then the input is read correctly.

```ruby
require 'openssl'
require 'socket'
require 'securerandom'

server = TCPServer.new 0
client = TCPSocket.new 'localhost', server.addr[1]

server_ctx             = OpenSSL::SSL::SSLContext.new
server_ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE
server_ctx.cert        = OpenSSL::X509::Certificate.new File.read "config/ssl/cert_test.pem"
server_ctx.key         = OpenSSL::PKey::RSA.new File.read "config/ssl/keys_test.pem"

ssl_server = OpenSSL::SSL::SSLServer.new server, server_ctx
ssl_client = OpenSSL::SSL::SSLSocket.new client, OpenSSL::SSL::SSLContext.new

Thread.new do ssl_client.connect end
server_socket = ssl_server.accept

output = SecureRandom.random_bytes(rand(256)+1)
server_socket.write output

input = ''
begin
  input << ssl_client.read_nonblock(output.length - input.length) until input.length == output.length
rescue OpenSSL::SSL::SSLErrorReadable
  p 'Need to wait'
  IO.select [ssl_client], nil, nil, 10
  retry
end

if input == output
  p 'OK'
else
  p 'FAIL'
  p input.inspect
end
```

If you change `IO.select [ssl_client], nil, nil, 10` to `sleep 0.01` then there are no problems.

I tested this on JRuby 1.7.1 (master) with jruby-openssl 0.8.0.pre3.

Fails 100% on the CentOS 6.3 system I am testing on.
Fails ~50% of the time in my Ubuntu 12.04 VM.
Fails 0% of the time on OS X 10.8.2

**Comment by kares** [comment]
seems to have been fixed over time - with JRuby 1.7.22/9.0.4.0 getting no failures on Ubuntu 15
