### ISSUE TITLE
Refinement that includes itself does not work

### ISSUE THREAD

**Issue by jeremyevans** [jruby/jruby#4236]
### Environment

jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 OpenJDK 64-Bit Server VM 25.72-b15 on 1.8.0_72-b15 +jit [OpenBSD-x86_64]
OpenBSD foo 6.0 GENERIC.MP#0 amd64

Also tested with 9.1.1.0 on Windows, same issue.
### Expected Behavior

``` ruby
module S
  private

  def S(v) p v; end

  refine Object do
    include S
  end
end

using S
S(1)
```

On ruby, prints 1.  
### Actual Behavior

On jruby:

```
NoMethodError: undefined method `S' for main:Object
  <main> at /home/billg/refinement_test.rb:12
```

**Comment by headius** [comment]
This works after #5604 and #5627.

**Comment by headius** [comment]
Both PRs and additional fixes have been merged.
