### ISSUE TITLE
[Truffle] Argument Error

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#4243]
### Example

``` ruby
class Test
  def test_method a, b = 2, c = nil
    puts "Hello `#{a}`, `#{b}`, `#{c}`"
  end
end
args = ["a", 1, nil, nil]
Test.new.test_method(*args, &args.pop)
```
### Expected Behavior

``` shell
Hello `a`, `1`, ``
```
### Actual Behavior

``` shell
.rb:2:in `test_method': wrong number of arguments (4 for 1..3) (ArgumentError)
```

Found in `rubygems/test_utilities.rb:263`

**Comment by eregon** [comment]
Looks very similar to https://bugs.ruby-lang.org/issues/12860, cc @headius 
So I suppose the splat in the call should not duplicate the array then?
