### ISSUE TITLE
JRuby unable to find methods unless jar is in boot classpath

### ISSUE THREAD

**Issue by jmiettinen** [jruby/jruby#4266]
### Environment

* JRuby 9.1.5.0 or 1.7.23 on OS X (`Darwin jmiettinen.local 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64`)
* No gems, no `JAVA_OPTS`
* To reproduce, clone [test-case repository](https://github.com/jmiettinen/jruby-test) and run `run.sh` which runs both failing and succeeding case. 
* JRuby-complete-jar is used to run `org.jruby.Main` which then runs a JRuby-script calling a few Java-classes.

### Expected Behavior

When running a simple [script](https://github.com/jmiettinen/jruby-test/blob/master/src/main/ruby/test.rb) with just having `JRuby` in the classpath, not in boot classpath, I would expect the JRuby to correctly resolve Java-methods and call them.

So in that case, the script should print out results of two different builder implementations:
```
SimpleClassImpl/5
SimpleClassImpl/5
BrokenClassImpl/5
BrokenClassImpl/5
```

### Actual Behavior

What actually happens is that calls succeed when the target Java-class is publicly visible, the calls succeed, but JRuby cannot find the target when implementor of the method is package-private.

```
SimpleClassImpl/5
SimpleClassImpl/5
NoMethodError: undefined method `set_value' for #<Java::FiRelex::BrokenClass::Builder:0x6fa0450e>
  <main> at src/main/ruby/test.rb:9
```

**Comment by mkristian** [comment]
to get your test case to the point where it fails I applied follow patch
```diff
diff --git a/src/main/java/fi/relex/SimpleClassImpl.java b/src/main/java/fi/relex/SimpleClassImpl.java
index 4ea0874..db6978c 100644
--- a/src/main/java/fi/relex/SimpleClassImpl.java
+++ b/src/main/java/fi/relex/SimpleClassImpl.java
@@ -1,10 +1,10 @@
 package fi.relex;

-public class SimpleClassImpl extends SimpleClass {
+class SimpleClassImpl extends SimpleClass {

     private final long value;

-    public SimpleClassImpl(long value) {
+    SimpleClassImpl(long value) {
         this.value = value;
     }
```
i.e. it is the https://github.com/jmiettinen/jruby-test/blob/master/src/main/java/fi/relex/BrokenClassImpl.java#L15 has a package private Builder whereas https://github.com/jmiettinen/jruby-test/blob/master/src/main/java/fi/relex/SimpleClassImpl.java#L16 is public

weird!  I would not ever thought that the bootclassloader can help here - good catch.

**Comment by jmiettinen** [comment]
Yeah, that's the thing that makes the difference. I should've brought it up more clearly.

As such, being on boot classpath should not have any effect on this as reflection should be able to reach and call both of the classes.
But with JRuby method resolution there seems to be.

Now that I think of it, we've been hit by JRuby being unable call methods from package-private classes before as we're deploying to Tomcat without adding JRuby to boot classpath there.

**Comment by jmiettinen** [comment]
The difference seems to stem from the fact that in `JavaUtil` there's a check for [`suppressAccessChecks` permission](https://github.com/jruby/jruby/blob/974bafbb6383ff64a4172279e3dea0a105fae882/core/src/main/java/org/jruby/javasupport/JavaUtil.java#L102). If that check fails, the code concludes that it cannot call `AccessibleObject#setAccessible`. 

This is not true at least if there's no `SecurityManager` present.

My colleague did some digging and it seems that @headius [introduced](http://markmail.org/message/gjye6xyiabyhpcg7#query:+page:1+mid:6g6x3iocawh3hoxd+state:results) first ban to not use methods from private classes: https://github.com/jruby/jruby/commit/ec8d280 as a fix for JRUBY-4799.

This ban seems to have been loosened a bit later on and public methods for private classes are added [if `JavaUtil.CAN_SET_ACCESSIBLE` is true](https://github.com/jruby/jruby/blob/974bafbb6383ff64a4172279e3dea0a105fae882/core/src/main/java/org/jruby/javasupport/binding/Initializer.java#L481).

I am not very familiar with how the `AccessController` should be used, but the current usage doesn't seem to match what happens in `AccessibleObject#setAccessible`.
There code first checks if there is a `SecurityManager` set and only if so calls `SecurityManager#checkPermission(Permission)` that delegates to the same `AccessController#checkPermission(Permission)` as the code in `JavaUtil` does.

**Comment by kares** [comment]
@jmiettinen thanks for the analysis ... your logic totally makes sense, I think there are 2 issues to fix : 

- change https://github.com/jruby/jruby/blob/974bafbb6383ff64a4172279e3dea0a105fae882/core/src/main/java/org/jruby/javasupport/JavaUtil.java#L102 to do some real code to check accessibility

- secondly, different methods being installed based on accessibility is quite a 'surprising' feature, JRuby should at least warn or figure out a uniform way to install and than fail at inaccessible methods at call-time (this is not something fixable in a patch release as it needs compatibility)
