### ISSUE TITLE
ruby/java coercion

### ISSUE THREAD

**Issue by abrandoned** [jruby/jruby#430]
I am looking for direction on any solidification of the coercion interface for Jruby/java.

After reading https://www.engineyard.com/blog/2009/5-things-to-look-for-in-jruby-1-4/ and seeing that `to_java(java.type)` was available I assumed that this was the chosen interface and built out the coercion mapping for one of our projects (that makes heavy use of java.math.BigDecimal and java.math.BigInteger in web services). 

while the coercion does work when explicitly calling `4.to_java(java.math.BigDecimal)` it does not work when passing a Ruby Fixnum directly to the web service client (Jax-ws).

https://github.com/abrandoned/jruby-coercion/blob/master/lib/jruby-coercion/numeric.rb

I can port the mapping over to java and submit a pull request for the java.\* types, but would also like to know if there is a coercion interface that support implicit coercion (that can be registered in gems)?

**Comment by headius** [comment]
I'm getting that @abrandoned has moved on from the projects that needed this, but if there's any discussion to be had please stop by Gitter or IRC. We've never really moved beyond the standard implicit coercion, and it has always bothered me a little.
