### ISSUE TITLE
Float vs BigDecimal

### ISSUE THREAD

**Issue by kirs** [jruby/jruby#4300]
```
# on ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
97.18 > BigDecimal.new("97.18")
=> true
```

Rails relies on the fact that the 97.18 as a float is greater than 97.18 as a BigDecimal due to floating point precision (https://github.com/rails/rails/blob/master/activemodel/test/cases/validations/numericality_validation_test.rb#L85
).

In JRuby that's not the case and a few ActiveModel tests fail:

```
# on jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]
97.18 > BigDecimal.new("97.18")
=> false
```

is it something that we can change in JRuby? or should we skip those tests in Rails when running on JRuby?

@headius

**Comment by kirs** [comment]
cc @guilleiguaran

**Comment by kares** [comment]
hey @kirs, thanks for the report. the test sound like it could be improved for the benefit of all :)
doubt there's actually any user reports on the behaviour and see no benefit in relying on the MRI specifics of how floats behave in that particular [test](https://github.com/rails/rails/blob/master/activemodel/test/cases/validations/numericality_validation_test.rb#L84) ... would be perfect if it simply did compare ~ 97.1**9** > 97.18
... that should also make understanding the test code clearer

**Comment by kirs** [comment]
> the test sound like it could be improved for the benefit of all

I absolutely agree. I ended up improving Rails' test suite to not rely on MRI specifics (https://github.com/rails/rails/commit/5abf662959aa2be98f4b5ce07c4051f530125e19)
