### ISSUE TITLE
JRuby 1.7: update to latest jruby-openssl version

### ISSUE THREAD

**Issue by cprice404** [jruby/jruby#4306]
### Environment

JRuby version 1.7.26 ships with jruby-stdlib 1.7.26, which bundles version 0.9.16 of the jruby-openssl gem.  We've had a few customers report some compatibility issues between some of their other x509 tools and older versions of bouncycastle/jruby-openssl, so we're trying to upgrade our packages to ship with jruby-openssl 0.9.18.  It seems like the cleanest path for that by far will be to upgrade the version that is included in jruby-stdlib.

### Expected Behavior

Latest JRuby 1.7.x release includes jruby-openssl 0.9.18.

### Actual Behavior

Latest JRuby 1.7.x release includes jruby-openssl 0.9.16.

I'll see if I can work up a PR.

**Comment by cprice404** [comment]
There are some errors that have shown up in CI for the related PR.  After exploration, I believe that the MRI `x509store` tests should be failing on JRuby9k with jruby-openssl `0.9.18`, just like the failure that is showing up in CI for JRuby 1.7 on my PR.  For more info see jruby/jruby-openssl#113.

If I should open another issue for JRuby9k (since this one's title mentions 1.7), let me know and I'll be happy to do so.

**Comment by cprice404** [comment]
Asking about this in IRC, and was told that the MRI tests for JRuby9k are run in CI via `mvn -Prake -Dtask=test:mri`.  I ran that and grepped all of the output for "openssl" and "x509" and didn't see any matches, leading me to believe that the openssl tests may not be getting run in CI for JRuby9k.

**Comment by kares** [comment]
on 0.9.17 for the moment, hopefully 0.9.19 will be released soon-ish ... (before the next/final? 1.7 release)

**Comment by kares** [comment]
and we're updated to **0.9.19** - took quite longer than expected.
hopefully it won't need to be done again (at least for 1.7)

**Comment by cprice404** [comment]
hooray, thanks!
