### ISSUE TITLE
Unexpected value for `$?.exitstatus` when process exited successfully

### ISSUE THREAD

**Issue by javierhonduco** [jruby/jruby#4361]
### Environment

* jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 Java HotSpot(TM) 64-Bit Server VM 24.65-b04 on 1.7.0_67-b01 +jit [darwin-x86_64]
* Darwin 16.1.0 Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64 x86_64

There's nothing special (gems or whatsoever) running on this machine.

### Expected Behavior
When running this snippet of code:
```ruby
system "exit 0"
puts "ruby_success=#{$?.success?} exit_code=#{$?.exitstatus}"
```
MRI (2.3.1) outputs 
```ruby_success=true exit_code=0```
### Actual Behavior
Unfortunately this is the output I'm getting under the JRuby version mentioned above:
```
ruby_success=false exit_code=127
```

I don't know if this is expected as per JRuby `system`'s implementation, sorry if that's the case!
Thanks,

**Comment by olleolleolle** [comment]
Same on 9.1.6.0.

```shell
$ rvm jruby-9.1.6.0 do ruby -e 'system "exit 0"; puts "ruby_success=#{$?.success?} exit_code=#{$?.exitstatus}"'
ruby_success=false exit_code=127
```

**Comment by headius** [comment]
Looks like we're not doing the right masking of the exit status.

**Comment by headius** [comment]
Ok, so here's the problem. We do the correct masking; however in this case the system call is actually failing. It tries to find an executable `exit` command, and seeing none it bails out with exit code of 127. MRI must be doing some extra logic here to know it needs to run with `sh -c`.

**Comment by javierhonduco** [comment]
Thanks a lot guys!

💚
