### ISSUE TITLE
JRuby 9.1.x.x is able to cause a SIGSEGV in OpenJDK 7.x

### ISSUE THREAD

**Issue by JasonLunn** [jruby/jruby#4365]
### Environment
JRuby 9.1.6.0

Observed in two environments:
```
JRE version: OpenJDK Runtime Environment (7.0_101) (build 1.7.0_101-b00)
Java VM: OpenJDK 64-Bit Server VM (24.95-b01 mixed mode linux-amd64 compressed oops)
Derivative: IcedTea 2.6.6
Distribution: Ubuntu 12.04 LTS, package 7u101-2.6.6-0ubuntu0.12.04.1
Problematic frame:
V  [libjvm.so+0x4752fc]
```
Most frequent - running tests on our own TeamCity agents

and

```
JRE version: Java(TM) SE Runtime Environment (7.0_76-b13) (build 1.7.0_76-b13)
Java VM: Java HotSpot(TM) 64-Bit Server VM (24.76-b04 mixed mode linux-amd64 compressed oops)
Problematic frame:
V  [libjvm.so+0x7d23fd]  methodOopDesc::result_type() const+0xd
```
Less frequent - running tests for a different project on Travis

### Expected Behavior

* JVM doesn't crash hard, ever

### Actual Behavior

* JVM crashes sporadically (say, ~1% of invocations?) with a message requesting that the bug report be submitted to either http://bugreport.java.com/bugreport/crash.jsp or http://icedtea.classpath.org/bugzilla, based on the distribution of the JDK.

**Comment by JasonLunn** [comment]
[hs_err_pid45220.log.txt](https://github.com/jruby/jruby/files/634650/hs_err_pid45220.log.txt)

**Comment by headius** [comment]
Definitely looks like a JVM issue unfortunately. We might be able to mitigate it. This is latest Java 7 yes? And you can't use 8?

**Comment by headius** [comment]
Ok, had a chance to look at your crash log. It is crashing in the GC thread, so it's looking more like a JVM bug. You might try running with a different GC (it's using CMS, you could try parallel or G1 perhaps). I see there are some Ruby threads running, but it's pretty hard to know how closely they are related to the GC crash.

**Comment by headius** [comment]
@bbrowning Any thoughts on this? According to the IcedTea issue, this is happening sporadically while running Torquebox tests.

**Comment by JasonLunn** [comment]
To be clear, the crash log above is not from my branch of torquebox (because if there is a way to get arbitrary crash log files out of Travis when it fails then I don't know it). The crash log is from a different code base entirely - the common thread between them is that in both code bases I was trying to transition to 9.1.6.0.

**Comment by JasonLunn** [comment]
More samples from our TeamCity CI server running tests for an in-house application.

[hs_err_pid41990.log.txt](https://github.com/jruby/jruby/files/646836/hs_err_pid41990.log.txt)
[hs_err_pid42275.log.txt](https://github.com/jruby/jruby/files/646835/hs_err_pid42275.log.txt)
[hs_err_pid46230.log.txt](https://github.com/jruby/jruby/files/646834/hs_err_pid46230.log.txt)

**Comment by enebo** [comment]
2 of those 3 crash were within safepoints.  I would have expected more all or nothing in that regard.

**Comment by JasonLunn** [comment]
FWIW, this issue was observed again today while using 9.1.7.0

[hs_err_pid20451.log.txt](https://github.com/jruby/jruby/files/752706/hs_err_pid20451.log.txt)

**Comment by JasonLunn** [comment]
Haven't observed this issue in a very long time and I am no longer running this configuration.
