### ISSUE TITLE
Possible memory issue with jruby / java / linux.

### ISSUE THREAD

**Issue by TheWudu** [jruby/jruby#4367]
Hi!

We experience some problems with the memory management of jruby / jvm / or linux?. As we are not sure if it belongs to jruby or not, I just want to know your opinion on that. We do not know how we can proceed with that issue any more.

Our environment:

* JRuby 9.1.5.0
* Linux <host> 3.13.0-95-generic #142~precise1-Ubuntu SMP Fri Aug 12 18:20:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux   
* Options:
-Djruby.shell=/bin/sh
-Djffi.boot.library.path=
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.authenticate=false
-Djava.rmi.server.hostname=localhost
-Djava.security.egd=file:/dev/./urandom
-Djruby.home=/<path>/.rvm/rubies/jruby-9.1.5.0
-Djruby.lib=/<path>/.rvm/rubies/jruby-9.1.5.0/lib
-Djruby.script=jruby
-Djruby.daemon.module.name=Trinidad
-Xmx3193m
-Xms3193m
-XX:PermSize=512m
-XX:+UseG1GC
-XX:MaxMetaspaceSize=768m
-XX:MetaspaceSize=512m
-Xss2048k
-Xbootclasspath/a:/<path>/.rvm/rubies/jruby-9.1.5.0/lib/jruby.jar
-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.port=1098
-Djava.rmi.server.hostname=<hostname>
-Dfile.encoding=UTF-8
-Dcommons.daemon.process.id=11164
-Dcommons.daemon.process.parent=11163
-Dcommons.daemon.version=1.0.8 abort 
* Framework: Triniad + Sinatra

When we look at the htop output, or at our graphs the server needs more and more memory over time. E.g. currently it shows
VIRT: 11,2G
RES: 6738M
running since last friday. The server itself has 7984 MB RAM. 

When i connect the process using visual vm, I see  that it uses ~ 1.5 gb of memory on heap, which is below the given amount (3193 mb), it uses about 175 mb metaspace, which is far below the given amount of 768 mb). It has between 58 and 62 threads (daemon and live), quite constant with a few spikes up to 72, which are opened and closed immediately.

The problem is, the system believes the process needs that much memory, but the java monitor shows a completely different status. When i restart the service (restart the process) the memory is freed again.

Can you give any hint on how to debug that further? Or maybe you know something else which could cause such an issue?

Any help would be appreciated,
Martin

**Comment by kares** [comment]
there's been couple of sim.reports such as these lately but somehow always turned out to be app specific.
my first advise is to get a heap dump and start poking around or setup a JVM monitoring tool and monitor when memory usage increases. you should not need that much metaspace unless doing hot redeploys.

we can certainly look at heap dump but its time-consuming ;( and sometimes needs source code access.
... are you seeing the "leak-like" behaviour just lately, did you change something, does it get more load?
(all relevant to consider/think about if you're running into this just lately)

**Comment by TheWudu** [comment]
We did not have these issues with jruby-1.7.x before and the load did not increase really. We have about 30-40k rpm in average the last 7 days with peaks up to ~ 150k rpms. The heap dumps does not show anything specific. If i do a dump file now it has about 1 gb, even if htop tells about 11.3gb VIRT memory, and MAT tells me that its about 300 mb of data on heap. Which matches with the visual vm output.

**Comment by TheWudu** [comment]
Additional the Leak Suspect from MAT tells me:

**Comment by kares** [comment]
thus if you're sure there's nothing crazy going on during requests can you let it (does it) fail with an OoME?
... that would confirm if there's a heap problem or one elsewhere.

> The problem is, the system believes the process needs that much memory, but the java monitor shows a completely different status. When i restart the service (restart the process) the memory is freed again.

so it must be native memory than? just guessing - there's only so much one could do without looking into it.
naively, did you try going to **9.1.6.0** ?

**Comment by headius** [comment]
It does sound like a native memory leak based on the numbers so far, especially if Java tools report a significantly smaller heap.

**Comment by headius** [comment]
First thing would be to confirm 9.1.6.0 has the problem. There were many fixes in that release.

After that, there's a link on the wiki to flags for profiling memory, tools for getting and analyzing heap dumps, etc.

**Comment by headius** [comment]
Oh, realized now some of those tools may not be super helpful for native memory leaks, and you already mentioned you've used MAT to analyze a heap dump. Ok...so let's get you on 9.1.6.0 and see if there's still a problem.

**Comment by andreaseger** [comment]
Hi
first sorry for the long silence.
Over the last weeks we worked around the leak by regular restarts of the app while also monitoring the leak during several jruby upgrades. Both 9.1.6.0 and 9.1.7.0 showed the leak.

Yesterday we performed the upgrade to 9.1.8.0 and as of now it looks like we're no longer leaking memory.

This shows the used system memory before and after the jruby upgrade.

![screenshot from 2017-03-22 09-28-44](https://cloud.githubusercontent.com/assets/172702/24188851/3043519c-0ee3-11e7-9087-cec5c49377f0.png)

**Comment by headius** [comment]
@andreaseger Great news! Thanks for updating us.

**Comment by the-michael-toy** [comment]
Any idea which fix in 9.1.8.0 would have caused this? We are seeing a similar problem on some, but not all instances, where since moving to j9k we have unbounded native memory growth.

**Comment by TheWudu** [comment]
@the-michael-toy No we have no idea which fix caused this.

**Comment by adpande** [comment]
I think the issue has resurfaced in 9.1.12.0

74,318 instances of "org.jruby.RubyClass", loaded by "sun.misc.Launcher$AppClassLoader @ 0x70b600ab8" occupy 402,588,016 (23.82%) bytes. 

Keywords
sun.misc.Launcher$AppClassLoader @ 0x70b600ab8
org.jruby.RubyClass

**Comment by adpande** [comment]
![ruby-leak1](https://user-images.githubusercontent.com/128881/36931333-9df7dc24-1ed9-11e8-8844-22eb488f82e5.png)
![ruby-leak2](https://user-images.githubusercontent.com/128881/36931334-9e21ac98-1ed9-11e8-9def-543016956044.png)
![ruby-leak3](https://user-images.githubusercontent.com/128881/36931335-9e49a46e-1ed9-11e8-93b4-d8236b7fe964.png)


Here are the issues from MAT
