### ISSUE TITLE
Windows Jruby Launcher has stopped working 

### ISSUE THREAD

**Issue by cawoodm** [jruby/jruby#4387]
Downloaded latest JRuby version (jruby-bin-9.1.6.0.zip but also tried jruby_windows_x64_9_1_6_0.exe) on Windows 7 64bit (MINGW64_NT-6.1 mycompooter 2.6.0(0.304/5/3) 2016-09-09 09:46 x86_64 Msys).

Set all my env variables, including JAVA_HOME without trailing slash. `jruby -v` just pops up the crash window "Windows Jruby Launcher has stopped working" with no other information.

![image](https://cloud.githubusercontent.com/assets/498834/21215244/3f60fa38-c2a0-11e6-8311-07c258875b66.png)

**Comment by enebo** [comment]
@cawoodm I test our releases on win7 64 bit as well so I wonder what is different.  Is it remotely possible there is more than one jruby installed somehow?  Or maybe did you use a different install directory?

**Comment by cawoodm** [comment]
I did indeed install it to my own directory `c:\prg\monitoring\jruby`. You don't mean that that causes a crash!??

Environment
```
JAVA_HOME=C:\Program Files\Java\jdk1.8
JRUBY_HOME=C:\Prg\monitoring\jruby\bin
```

**Comment by cawoodm** [comment]
My solution: reboot your PC. Worked for me!

Please make a better failover: an error message or log or something.

**Comment by enebo** [comment]
@cawoodm I still have no idea what was wrong.  I know some people have reported security issues executing our launcher from some directories.   I do not think that should create a seg fault though.  In the not so distant future we will be replacing our current launcher with mjruby.  If we do see this come up again we can try and figure out what is not working...
