### ISSUE TITLE
Concurrent::ScheduledTask is broken on master JRuby

### ISSUE THREAD

**Issue by kirs** [jruby/jruby#4407]
I'm running latest version of concurrent-ruby (1.0.3) and JRuby master.

```ruby
require 'concurrent'
class Job
  def perform
    puts "ddd"
  end
end

job = Job.new
executor = Concurrent::ImmediateExecutor.new
Concurrent::ScheduledTask.execute(10, args: [job], executor: executor, &:perform)
```

The last line crashes with `java.lang.NoSuchFieldError: SUPPORTS_FENCES` ([full stacktrace](https://gist.github.com/66fee73f27dfd455d93750d920f5620f))

The same snippet works fine on `jruby-9.1.6.0`, so I believe there is a regression in `9.1.7` / master.

@headius

**Comment by olleolleolle** [comment]
This commit removed `SUPPORTS_FENCES`: [Remove unsafe block from build altogether](https://github.com/jruby/jruby/commit/64b955381d951d7f6f90cc87f440db4ed3d69459) 64b955381d951d7f6f90cc87f440db4ed3d69459

And concurrent-ruby relies on that field: [concurrent-ruby code using that field in its Java/JRuby extension](https://github.com/ruby-concurrency/concurrent-ruby/blob/dcff3c1969113270ba1659d7fa5fcd7bba588273/ext/com/concurrent_ruby/ext/SynchronizationLibrary.java#L99,L113)

What's the new/preferred way forward for concurrent-ruby, now that this field is gone?

**Comment by headius** [comment]
Ahh I was worried about someone using those fields or methods. I will restore and deprecate the field.

**Comment by headius** [comment]
This should be fixed on master. Please confirm!

**Comment by kirs** [comment]
Thanks for fixing it! I confirm that it works.
