### ISSUE TITLE
chunk_while not returning results equivalent to MRI ruby 2.3+ (jruby 9.1.6.0)

### ISSUE THREAD

**Issue by olbrich** [jruby/jruby#4410]
### Environment

```
$ ruby -v
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.0-b70 on 1.8.0-b132 +jit [darwin-x86_64]
$ uname -a
Darwin Kevins-MacBook-Pro.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

### Expected Behavior

```
$  rvm use ruby-2.4.0
Using ruby-2.4.0
$ irb
2.4.0 :001 > [1].chunk_while { |x| x.even? }.to_a
 => [[1]]
```

### Actual Behavior

```
$  rvm use jruby-9.1.6.0
Using jruby-9.1.6.0
$ irb
jruby-9.1.6.0 :001 > [1].chunk_while { |x| x.even? }.to_a
 => []
```

**Comment by enebo** [comment]
Just going to note for anyone who wants to work on this that it is not a 2.4 compat bug but probably a 2.3 one (I did not check earlier).  @olbrich I am only mentioning this since 9.1.x of JRuby only supports 2.3 and not 2.4.  (9.2.x will support 2.4 specific features).  So this is fair game right now if anyone wants to take it on.

**Comment by olbrich** [comment]
@enebo yeah, it probably is inconsistent with all the MRI rubies that support chunk_while (which I think was introduced in ruby 2.3).

**Comment by headius** [comment]
@cthulhua Hey, feel like taking a stab at this? This was your patch from #3517.

**Comment by headius** [comment]
@cthulhua If it starts to look like it's a problem with JRuby's Enumerable or "native" bits, let us know. We're still dragging along some not-always-correct Java impls of the core Enumerable logic, and these sorts of things are not uncommon to see.

**Comment by headius** [comment]
@cthulhua Good catch...I'll give that a shot.

**Comment by headius** [comment]
Ok, I went with @cthulhua's suggestion and combined slice_when and chunk_while logic. This is now fixed.

We may want to look at the Truffle/Rubinius versions of these methods, since we depend on `#size` being available and they do not.
