### ISSUE TITLE
exit! and --debug events can cause a deadlock

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#4419]
This is an issue made because I had to revert the PR (Fix deadlock when tearing down runtime during debugging #4352).  I don't know if I am thick but I can also trivially deadlock with this:

```ruby
def foo
  1
end


2.times do
  puts "T"
  Thread.new {
    a = []
    [:call, :c_call, :return, :c_return].each do |n|
      t = TracePoint.new(n) { |tp| p tp.event }
      t.enable
    end
    loop do
      sleep 0.01
      foo
    end
  }
end

sleep 0.5
exit!
```

I think it is because both threads need to receive an event callback but the event callback is generating an event callback and we deadlock?  In any case I threw this second deadlock into this issue...

**Comment by enebo** [comment]
I should add this was reverted because simplecov stopped working for multiple users where only a small subset of coverage was being reported.

**Comment by PragTob** [comment]
Adding to what Tom said, there is further info as to how to check the things that caused problems on simplecov in the issue that caused the revert: #4404 (simplecovs integration test suite also helpfully fails :) )

It was also mentioned that it might be simplecovs fault, as in inadequate usage of hooks, I'm not really into the code base but would be willing to help debug issues given I got the time :)

**Comment by headius** [comment]
Still failing in 9.2.

**Comment by headius** [comment]
This is deadlocking because TracePoint events are synchronized and they cross over because of the two threads both trying to fire events at each other. I'm looking into a better way to synchronize trace events.
