### ISSUE TITLE
[Truffle] Can't modify frozen Regexp Error for Named Captures

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#4436]
### Environment

Also found while running in the addressable specs.

### Expected Behavior
```
$ ruby -e 'puts /(?<foo>.)(?<bar>.)/.freeze.named_captures'
{"foo"=>[1], "bar"=>[2]}
```
### Actual Behavior
```
$ jt p '/(?<foo>.)(?<bar>.)/.freeze.named_captures'
$ /Users/brandonfish/Documents/jruby/bin/jruby -X+T -Xtruffle.core.load_path=/Users/brandonfish/Documents/jruby/truffle/src/main/ruby -Xtruffle.graal.warn_unless=false -e 'p begin /(?<foo>.)(?<bar>.)/.freeze.named_captures end'
/Users/brandonfish/Documents/jruby/truffle/src/main/ruby/core/regexp.rb:312:in `named_captures': can't modify frozen Regexp (RuntimeError)
	from -e:1:in `<main>'

```

cc'ing: @eregon because it appears he has working on this recently: https://github.com/jruby/jruby/commit/d88a10101cadcf2729dc2d400d576748f58c9de6

MRI appears to avoid this frozen issue by always re-calculating. However maybe we have a way to cache this while avoiding this frozen error?

**Comment by eregon** [comment]
This is unfortunate. Maybe we can modify the code to avoid writing if `frozen?`. Or specialize that write to bypass the frozen check.

**Comment by eregon** [comment]
Or even simpler, remove the caching since I doubt this is called enough to matter.

**Comment by nirvdrum** [comment]
I'm not sure which cache you're talking about, but the various regexp caches were added because they made a pretty big difference when testing gems.

**Comment by eregon** [comment]
This caching the mapping of captures names and captured Strings.
