### ISSUE TITLE
Licensing is confusing

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#4454]
In `README.md`, source files and `COPYING` I can see references to GPL 2 and LGPL 2.1, but the POM talks about GPL 3, and LGPL 3

https://github.com/jruby/jruby/blob/664b6ee5ccf90c393d60e257c3fbd7fa9fbb7c84/pom.rb#L29-L30

**Comment by enebo** [comment]
This was a mistake when the ruby pom stuff was created to replace our old maven build system.  We will correct this to be GPL 2 and LGPL 2.1 like the rest of our project.

**Comment by headius** [comment]
This came in from PR #887.
