### ISSUE TITLE
ArgumentError when using 2-argument for of IO#each

### ISSUE THREAD

**Issue by rovf** [jruby/jruby#4459]
jruby 1.7.26 (1.9.3p551) 2016-08-26 69763b8 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15 +jit [Windows 7-amd64]

f=File.open('some_file','r')
f.each(nil, 1024) {}

I get: 

ArgumentError: wrong number of arguments (2 for 1)
	from (irb):16:in `evaluate'
	from org/jruby/RubyKernel.java:1079:in `eval'
	from org/jruby/RubyKernel.java:1479:in `loop'

The usage of f.each should be correct. From http://ruby-doc.org/core-1.9.3/IO.html#method-i-each :

------------------
each(sep,limit) {|line| block } → ios
Executes the block for every line in ios, where lines are separated by sep.
------------------

**Comment by aayush2610** [comment]
Hi, I am new to jruby and would like to contribute. Please let me know the details of this issue.

**Comment by kares** [comment]
has been working since around the (~2017) JRuby 9.1 days
