### ISSUE TITLE
according to badges in readme build is failing

### ISSUE THREAD

**Issue by matkoniecz** [jruby/jruby#4476]
Either this problem should be fixed or badges removed

https://github.com/jruby/jruby#jruby---an-implementation-of-the-ruby-language-on-the-jvm

**Comment by kares** [comment]
Thanks Mateus, its fairly common since there's so many different suites JRuby runs.
A lot of those are also sometimes failing intermediately (and only on CI). Its now down to one master failure.

**Comment by headius** [comment]
We appreciate your interest, but please don't file issues for failing CI. We intend to keep CI green, and usually do, but sometimes an intermittent failure or missed test sneaks through. Believe me, we don't like it either ;-)
