### ISSUE TITLE
stdlib/date/format.rb:837 error with date

### ISSUE THREAD

**Issue by mtoribio** [jruby/jruby#4480]
* jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.111-b14 on 1.8.0_111-b14 +jit [darwin-x86_64]
* Rails 5.1
Hi,
I have a problem with stdlib/date/format.rb line 837
`str = str.to_str if !str.kind_of?(::String) && str.respond_to?(:to_str)`
when you try to parse a date throw a exception: no method `to_str` for `Date`, I change `to_str` to `to_s`.

**Comment by olleolleolle** [comment]
@forumd Thanks for the report. Can you make a small program outside of Rails to show the problem?

**Comment by kares** [comment]
no feedback in a year+ and unfortunately no reproduction thus closing, for now
