### ISSUE TITLE
Travis-ci: Error parsing Gemfile on current jruby-head

### ISSUE THREAD

**Issue by prasunanand** [jruby/jruby#4487]
The new jruby-head is unable to parse Gemfile correctly [link](https://travis-ci.org/SciRuby/nmatrix/jobs/198114642#L732). NMatrix has 4 different gemspecs. It is unable to load the Gemspec both on mac-os and ubuntu.
1. https://travis-ci.org/SciRuby/nmatrix/jobs/198114642
2. https://travis-ci.org/SciRuby/nmatrix/jobs/198114644

**Comment by headius** [comment]
Hmm, that's peculiar. I took the source of that gemspec and ran it through `jruby -c` (check syntax) and it was fine. I also ran it through JRuby 1.7 in Ruby 1.8 and 1.9 modes, and they were also able to parse it.

Do you get this running tests locally? If not, it may be something peculiar happening on Travis. They have docs on how to set up a Docker image that matches the CI instances so you can investigate. At the moment I have no theory why it fails for you in Travis.

**Comment by prasunanand** [comment]
The travis tests work fine with JRuby 9.0.5.0.[link](https://travis-ci.org/SciRuby/nmatrix).
I find this error exclusive to current JRuby head (9.1.8.0)[link](https://travis-ci.org/SciRuby/nmatrix/jobs/198114642#L244)

I will set up Docker Image and set up CI instances to investigate.

**Comment by prasunanand** [comment]
Fixed with the current jruby-head :) 
`jruby 9.1.9.0-SNAPSHOT (2.3.1)`
