### ISSUE TITLE
Refines coming from included modules aren't recognized by jruby

### ISSUE THREAD

**Issue by najamelan** [jruby/jruby#4489]
### Environment
`jruby -v`    : jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae OpenJDK 64-Bit Server VM 25.121-b13 on 1.8.0_121-8u121-b13-2-b13 +jit [linux-x86_64]
`uname -a` : Linux computer 4.9.0-1-amd64 #1 SMP Debian 4.9.2-2 (2017-01-12) x86_64 GNU/Linux

### Expected Behavior

This works on MRI:
```ruby
module A
  refine String do
    def foo; puts :foo; end
  end
end

module B
  refine String do
    def bar; puts :bar; end
  end
end

module C
  include A, B
end

using C

"blah".foo
"blah".bar
```

On jruby it doesn't take the refine :(

### Actual Behavior
```
$ jruby test.rb
NoMethodError: undefined method `foo' for "blah":String
  <main> at test.rb:19
```
As discussed in #4475

**Comment by headius** [comment]
Thank you! We shall endeavor to fix it :-)

**Comment by headius** [comment]
JRuby output matches MRI 2.5.3 after #5604 and #5627.

**Comment by headius** [comment]
Both PRs and additional fixes have been merged.
