### ISSUE TITLE
YAML: Can't load files with characters in the supplementary plane

### ISSUE THREAD

**Issue by y8** [jruby/jruby#4492]
> Loading YAML fails if they have a character in the supplementary plane:
> 
> ```
> jruby-9.1.5.0 :002 > require 'yaml'; YAML.load('೬')
>  => "೬" 
> jruby-9.1.5.0 :003 > require 'yaml'; YAML.load('1🎁')
> Psych::SyntaxError: (): 'reader' unacceptable character ' at line 0 column 0
>     from org/jruby/ext/psych/PsychParser.java:231:in `parse'
>     from /home/glopes/.rvm/rubies/jruby-9.1.5.0/lib/ruby/stdlib/psych.rb:376:in `parse_stream'
>     from /home/glopes/.rvm/rubies/jruby-9.1.5.0/lib/ruby/stdlib/psych.rb:324:in `parse'
>     from /home/glopes/.rvm/rubies/jruby-9.1.5.0/lib/ruby/stdlib/psych.rb:251:in `load'
>     from (irb):3:in `'
>     from org/jruby/RubyKernel.java:995:in `eval'
>     from org/jruby/RubyKernel.java:1296:in `loop'
>     from org/jruby/RubyKernel.java:1115:in `catch'
>     from org/jruby/RubyKernel.java:1115:in `catch'
>     from /home/glopes/.rvm/rubies/jruby-9.1.5.0/bin/irb:13:in `'
> ```
> 
> Confusingly, it says the error is at line 0 column 0.

See original issue: https://github.com/ruby/psych/issues/293

I can confirm this behaviour on 1.7.25, 9.1.5.0, 9.1.6.0 and 9.1.7.0

OS: 

```
Darwin <> 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

Java:

```
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
```

ENV:

```
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
TERM=xterm-256color
```

**Comment by focusshifter** [comment]
Can confirm, got bitten by it while trying to parse emoji-powered YML.

**Comment by headius** [comment]
This is likely a bug in the SnakeYAML library we use. It's probably not handling surrogate pairs in its parser.

**Comment by headius** [comment]
This appears to have been fixed in snakeyaml but there has been no release with that fix. I just requested one here: https://bitbucket.org/asomov/snakeyaml/issues/323/is-there-any-reason-to-not-support

**Comment by y8** [comment]
@asomov could you please save us by rolling outthe release with a fix? Спасибо! 🤗

**Comment by headius** [comment]
I'll keep this open until we have the psych release integrated into JRuby.
