### ISSUE TITLE
SystemCallError: Unknown error - <STDOUT>

### ISSUE THREAD

**Issue by perlun** [jruby/jruby#4505]
### Environment

Provide at least:
* JRuby version: `9.1.7.0`
* Operating system and platform: Ubuntu 12.04.5 LTS
* Java version: 1.7.0_76, vendor: Oracle Corporation

### Expected Behavior

`bundle install` should succed.

### Actual Behavior

```
Using rake 12.0.0
Using concurrent-ruby 1.0.4 (java)
Using i18n 0.8.1
Using thread_safe 0.3.6 (java)
Using public_suffix 2.0.5
Using ansi 1.5.0
Using ast 2.3.0
Using bson 4.2.1 (java)
Using hitimes 1.2.4 (java)
Using logify 0.2.0
Using mime-types 2.99.3
Using ffi 1.9.17 (java)
Using choice 0.2.0
Using coderay 1.1.1
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using json 2.0.3 (java)
Using docile 1.1.5
Using simplecov-html 0.10.0
Using tins 1.13.2
Using thor 0.19.4
Using diff-lcs 1.3
Using unf 0.1.4 (java)
Using slack-notifier 1.5.1
Using mixlib-log 1.7.1
Using rainbow 2.2.1
Using rack 1.6.5
Using uuidtools 2.1.5
Using multi_json 1.12.1
Using multipart-post 2.0.0
Using formatador 0.2.5
Using rb-fsevent 0.9.8
Using ruby_dep 1.5.0
Using lumberjack 1.0.11
Using nenv 0.3.0
Using shellany 0.0.1
Using method_source 0.8.2
Using slop 3.6.0
Using guard-compat 1.2.1
Using rspec-support 3.5.0
Using log4r 1.1.10
Using net-http-persistent 2.9.4
Using netrc 0.11.0
Using nokogiri 1.7.0.1 (java)
Using powerpack 0.1.1
Using quantile 0.2.0
Using rack-cors 0.4.1
Using ruby-progressbar 1.8.1
Using unicode-display_width 1.1.3
Using semantic 1.6.0
Using sequel 4.43.0
Using tilt 2.0.6
Using xml-simple 1.1.5
Using bundler 1.14.5

SystemCallError: Unknown error - <STDOUT>

An error occurred while installing minitest (5.10.1), and Bundler cannot
continue.

Make sure that `gem install minitest -v '5.10.1'` succeeds before bundling.

RuntimeError: Error occured while running Java. Full command line was: java  -jar workers/jruby/jruby-complete-9.1.7.0.jar workers/gems/jruby/2.3.1/bin/bundle --deployment --standalone --path workers/gems --jobs 7 --retry 15
```

I will try upgrading the Java version to see if it makes any difference.

**Comment by perlun** [comment]
Seem to be able to reproduce this on Java 1.8.0_31 as well.

**Comment by perlun** [comment]
> I've added some additional info to the error message so we can at least see what type of system error it was trying to raise.

Good! I'll see if I can reproduce this with a build from master as well. Can it easily be installed on Travis/i.e. using rvm somehow?

**Comment by headius** [comment]
Specifying jruby-head should pull from our more recent green build. I'll make sure we have a green build (things are a little fluxy today).

**Comment by headius** [comment]
I think there should be a good recent build for you to try if you go with jruby-head. We have logic to ping Travis for every green build so they update their pre-built "jruby-head".

**Comment by headius** [comment]
Oh, and if you just want to do it yourself, I believe rvm install jruby-head will just build master fine.

**Comment by perlun** [comment]
The problem with my use case is we use a jruby-complete here to run the bundle install. So even though I can `rvm install jruby-head` (thanks for that suggestion), it still uses the wrong JRuby when doing the bundle install. Can you get a jruby-complete snapshot as wel somewhere?

**Comment by headius** [comment]
The snapshot builds at http://ci.jruby.org/ appear to be up to date.

**Comment by perlun** [comment]
Thanks @headius. So weird - when trying this snapshot, I cannot reproduce this error any more...

I suggest we close it for now; _if_ we find a way to reproduce this with the latest code on `master` we can dig into it more. For now, the added debugging info you put there is a great start. Thank you thus far.
