### ISSUE TITLE
release and upgrade BC (jruby-openssl)

### ISSUE THREAD

**Issue by kares** [jruby/jruby#4512]
due BC 1.56 http://bouncycastle.org/releasenotes.html

... its already pretty much prepared for release, will do a release when 9.1.8.0 is near

**Comment by kares** [comment]
1.7 probably deserves an jruby-openssl upgrade as well if there's to be one single "final" 1.7.x release

**Comment by headius** [comment]
No plans at the moment to do a 1.7 release, but you can go ahead with OpenSSL any time. We want to release 9.1.8.0 this week.

**Comment by kares** [comment]
0.9.20 released and updated on master (CI :green_heart: )

**Comment by headius** [comment]
Awesome, thanks @kares!
