### ISSUE TITLE
Output of backticks call not returned but written to stdout instead

### ISSUE THREAD

**Issue by til** [jruby/jruby#4515]
### Expected Behavior
Output of command is returned from calling backticks, like in this working example on MRI (2.3.3):
```
$ ruby -e 'p `echo test`'
"test\n"
```
### Actual Behavior
Output is written to stdout, and the return value of the backticks call is an empty string:
```
$ /opt/jruby-9.1.7.0/bin/jruby -e 'p `echo test`'
test
""
```
### Environment

Ubuntu 16.04 / Linux 4.4.0-042stab120.6

jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae OpenJDK 64-Bit Server VM 9-internal+0-2016-04-14-195246.buildd.src on 9-internal+0-2016-04-14-195246.buildd.src +jit [linux-x86_64]

I observed this on two machines with Ubuntu 16.04 from different providers, with both jruby 9.1.6.0 and 9.1.7.0. On my local machine with ArchLinux and jruby 9.1.7.0 it behaves as expected.

Same with popen:
```
$ /opt/jruby-9.1.7.0/bin/jruby -e "IO.popen('echo test') { |io| p io.read }"
test
""
```

Verifying that output goes to stdout:
```
$ /opt/jruby-9.1.7.0/bin/jruby -e 'p `echo test`' > /tmp/output
$ cat /tmp/output
test
""
```

Is that a bug or could it be some kind of misconfiguration on the Ubuntu servers? Any hints appreciated.

**Comment by headius** [comment]
Wow, this seems super unlikely to be broken since there are definitely backquote tests in various test suites we run. I also can't confirm what you're seeing:

```
$ rvm jruby-9.1.7.0 do jruby -v -e 'p `echo test`'
jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae OpenJDK 64-Bit Server VM 24.131-b16 on 1.7.0_131-b16 +jit [linux-x86_64]
"test\n"
```

Perhaps something's weird with your shell? I have no explanation for what you're seeing, but if either of those behaviors were actually happening we'd have dozens of broken tests.

**Comment by til** [comment]
I could reproduce it now on a fresh digitalocean instance with Ubuntu 16.04, without any additional configuration, with java installed from the package `openjdk-9-jre-headless`:

```
root@ubuntu-2gb-fra1-01:~/jruby-9.1.7.0# bin/jruby -v -e 'p `echo test`'
jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae OpenJDK 64-Bit Server VM 9-internal+0-2016-04-14-195246.buildd.src on 9-internal+0-2016-04-14-195246.buildd.src +jit [linux-x86_64]
test
""
```

With `openjdk-8-jre-headless` it works as expected:

```
root@ubuntu-2gb-fra1-01:~/jruby-9.1.7.0# bin/jruby -v -e 'p `echo test`'
jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae OpenJDK 64-Bit Server VM 25.121-b13 on 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13 +jit [linux-x86_64]
"test\n"
```

**Comment by til** [comment]
Please excuse my ignorance regarding Java versions - since `openjdk-9` packages are included in a recent Ubuntu release, I had assumed that it is a version automatically supported by jruby. On Ubuntu one should probably install the `default-jdk` package (or the `default-jre-headless` variant) instead, which depends on `openjdk-8`.

Downgrading openjdk works fine for me, so I'm closing this issue, feel free to reopen if openjdk-9 compatibility is desired.

**Comment by headius** [comment]
Actually I do want to look into those. We have not focused on JDK9 support, but we should do that soon.

**Comment by headius** [comment]
We'll do a push for Java 9 in the 9.2 cycle.

**Comment by p0deje** [comment]
I can confirm that issue exists on JRuby 9.1.14.0 + JDK 9.0.1.

**Comment by headius** [comment]
This appears to work fine on 9.1.16.0 + Java 9.0.1. Please let us know if it's still causing problems.
