### ISSUE TITLE
File.mtime doesn't return milliseconds

### ISSUE THREAD

**Issue by AlexWayfer** [jruby/jruby#4520]
### Environment

* JRuby version is `9.1.7.0` (and older)
* ArchLinux, Kernel version is `4.9.11`
* Ruby version manager is `rbenv`

### Expected Behavior

`File.mtime` returns `Time` with milliseconds:

```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

$ ruby -e "puts File.mtime('README.md').to_f"
1488443688.4152856
```

### Actual Behavior

`File.mtime` returns `Time` without milliseconds:

```
$ ruby -v
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 +jit [linux-x86_64]

$ ruby -e "puts File.mtime('README.md').to_f"
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
1488443688.0
```

**Comment by harshvardhansharma** [comment]
did some research and found these links:
 - http://stackoverflow.com/questions/18403588/how-to-return-millisecond-information-for-file-access-on-mac-os-x-in-java/18404059#18404059
 - https://github.com/rubinius/rubinius/issues/3502

**Comment by AlexWayfer** [comment]
@harshvardhansharma We cannot bypass some limitations of file systems. But this should work on file systems that allow, especially where MRI works.

**Comment by harshvardhansharma** [comment]
@AlexWayfer, right and seems to be working on a machine with MRI interpreter, will try with jRuby one and see how it can be fixed. 
Do you have any other thoughts on this?

**Comment by AlexWayfer** [comment]
@harshvardhansharma I found this: #4393 and #1951

But they are not about files.

I think it's a flaw in JRuby, but can't say for sure, because not worked with him closely.

**Comment by headius** [comment]
@harshvardhansharma Thanks for the investigation on this one! It appears that in order to support this we would need to conditionally access the newer st_mtim etc timespec fields on the stat struct. This needs to be done in https://github.com/jnr/jnr-posix before we can use it in JRuby.

**Comment by headius** [comment]
Good news! It looks like we may have the nsec fields mapped already in jnr-posix. I'll see if I can wire them up.

**Comment by headius** [comment]
And more good news...as of Java 7, the "NIO 2" file APIs also appear to support nsec resolution. It may be possible to expose them without tying jnr-posix to Java 7, but I'm just going to wire it up for native UNIX stats for now.

**Comment by headius** [comment]
Someone want to contribute a spec to https://github.com/ruby/spec for this behavior? I don't see any existing stat a/c/mtime nanosecond specs in there and we don't want this to get missed.

**Comment by AlexWayfer** [comment]
@headius I'm trying!

**Comment by AlexWayfer** [comment]
And done!

**Comment by headius** [comment]
Thank you!
