### ISSUE TITLE
JRuby 9.1.8.0: Kernel#sprintf() reference-by-name throws ArgumentError.

### ISSUE THREAD

**Issue by clonezone** [jruby/jruby#4524]
### Environment

jruby 9.1.8.0 (2.3.1) 2017-03-06 90fc7ab Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 +jit [linux-x86_64]

Ubuntu 14.04: Linux hostname 3.13.0-110-generic #157-Ubuntu SMP Mon Feb 20 11:54:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Expected Behavior

Expect the example from the bottom of the MRI Kernel#sprintf() docs for reference-by name to work: http://ruby-doc.org/core-2.3.1/Kernel.html#method-i-sprintf

### Actual Behavior

```bash
> jruby -e 'sprintf("%<foo>d : %<bar>f", { :foo => 1, :bar => 2 })'
ArgumentError: name<bar> after <foo>
        % at org/jruby/RubyString.java:1191
  sprintf at org/jruby/RubyKernel.java:811
   <main> at -e:1
```

**Comment by enebo** [comment]
This was just fixed this morning in #4523

**Comment by enebo** [comment]
@clonezone hey is this occurring as part of a gem?  two people reporting it in one day makes me wonder...

**Comment by clonezone** [comment]
Nope. I'm running into it as part of my server startup processing its configuration.
