### ISSUE TITLE
Update "Improving startup time" documentation

### ISSUE THREAD

**Issue by cFire** [jruby/jruby#4525]
The wiki page has a section found here:
https://github.com/jruby/jruby/wiki/Improving-startup-time#running-sub-rubies-in-the-same-jvm
that suggests setting the `-J-Djruby.launch.inproc=true` flag, however, according to this issue: https://github.com/jruby/jruby/issues/2754
this mode has been disabled.

I think it would be helpful to mention this change in the "Improving startup time" wiki page.

**Comment by headius** [comment]
Fixed in https://github.com/jruby/jruby/wiki/Improving-startup-time/fa6cb32ac61999368cc68579a8a9c0f6da717bdb with a link to the RedBridge embedding API and a short example.
