### ISSUE TITLE
String#codepoints for one-byte encodings

### ISSUE THREAD

**Issue by InfraRuby** [jruby/jruby#4533]
On many versions of JRuby, including 9.1.8.0:

    "\x80".force_encoding("WINDOWS-1252").codepoints.first # => 0x80

I expected 0x20AC: https://en.wikipedia.org/wiki/Windows-1252

See:
  https://github.com/jruby/jruby/blob/9.1.8.0/core/src/main/java/org/jruby/RubyString.java#L5117-L5118
  https://github.com/jruby/jruby/blob/9.1.8.0/core/src/main/java/org/jruby/util/StringSupport.java#L1473

**Comment by headius** [comment]
We behave like MRI does here, so I'd be reluctant to change it.

```
$ rvm ruby-2.4 do ruby -e 'p "\x80".force_encoding("WINDOWS-1252").codepoints.first.to_s(16)'
"80"
```

If you believe this is wrong, I think you should take it up with them on [their bug tracker](https://bugs.ruby-lang.org) first.

**Comment by InfraRuby** [comment]
> If you believe this is wrong, I think you should take it up with them on their bug tracker first.

Ok: https://bugs.ruby-lang.org/issues/13321

**Comment by lopex** [comment]
I'ts an issue with codepoints method ifself or jcodings ?

**Comment by InfraRuby** [comment]
@headius: that's expected behavior over there! https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/58000/diff
