### ISSUE TITLE
RubyUDPSocket swallows exceptions

### ISSUE THREAD

**Issue by jagregory** [jruby/jruby#455]
The [RubyUDPSocket](https://github.com/jruby/jruby/blob/master/src/org/jruby/ext/socket/RubyUDPSocket.java) implementation swallows exceptions that're raised. For example: [line 318](https://github.com/jruby/jruby/blob/master/src/org/jruby/ext/socket/RubyUDPSocket.java#L318).

In my case I was getting `Errno::ECONNREFUSED: Connection refused - send(2)` exceptions raised, but I couldn't see that in JRuby. I had to switch to MRI to see it.

I'm happy to provide a patch if someone can recommend the best way to raise the exception (I don't know if there's any conventions for doing this).

**Comment by kares** [comment]
has been redone lately and should work fine on >= 9.0.5.0
