### ISSUE TITLE
Support grapheme detection via \X

### ISSUE THREAD

**Issue by janlelis** [jruby/jruby#4568]
JRuby should support matching "grapheme clusters" (glyphs), which are constructed using mutliple Unicode codepoints.

### Expected Behavior (MRI)

```ruby
glyphs = "\u{61 308 62}".scan(/\X/) # => ["ä", "b"]`
glyphs.map{ |e| e.codepoints.map{ |f| f.to_s(16) } } #=> [["61", "308"], ["62"]]
```

### Actual Behavior (JRuby)

```ruby
glyphs = "\u{61 308 62}".scan(/\X/) # =>  ["a", "b"]`
glyphs.map{ |e| e.codepoints.map{ |f| f.to_s(16) } } #=> [["61"], ["62"]]
```

### Related Links

- Unicode® Standard Annex #29: Unicode Text Segmentation: http://unicode.org/reports/tr29/
- Introduction of `\X` to Onigmo: https://github.com/k-takata/Onigmo/commit/dde0c4329284a8383e732c608cae4acd01b4b8ed
  - Non-Unicode should match: `(?>\x0D\x0A|(?m:.))`
- Seems to only work properly in MRI 2.4: https://github.com/rails/rails/pull/26743
- Related Ruby issue: https://bugs.ruby-lang.org/issues/12831
- Example graphemes: https://github.com/janlelis/uniscribe/blob/master/spec/uniscribe_spec.rb

**Comment by headius** [comment]
Given that this does not appear to be fully baked in MRI 2.3 I think this is safe to defer to our 2.3-compatible release in 9.2.0.0.

**Comment by lopex** [comment]
This should work ootb with new joni

**Comment by headius** [comment]
@lopex I forget our status here. We can move 9.1 to the new joni, yes?

**Comment by headius** [comment]
Works in 9.1.16.0.

```
irb(main):001:0> glyphs = "\u{61 308 62}".scan(/\X/) # => ["ä", "b"]`
(irb):1: warning: character class has duplicated range
=> ["ä", "b"]
irb(main):002:0> glyphs.map{ |e| e.codepoints.map{ |f| f.to_s(16) } } #=> [["61", "308"], ["62"]]
=> [["61", "308"], ["62"]]
```
