### ISSUE TITLE
LocalJumpError: unexpected break in spec/ruby/language/break_spec.rb

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#4577]
jruby 9.1.9.0-SNAPSHOT (2.3.3) 2017-04-28 038f790 OpenJDK 64-Bit Server VM 25.121-b14 on 1.8.0_121-b14 +jit [linux-x86_64]

Which can be reproduced with:
```
 bin/jruby spec/mspec/bin/mspec run -Gfails -Gcritical -Gslow spec/ruby/language/break_spec.rb
```

This specific spec is currently excluded in jruby.2.3.mspec so that's why it got unnoticed.
There are only 3 `ruby_exe` calls in that spec so once this is fixed I would advise to include it on CI.

**Comment by eregon** [comment]
@headius @enebo Could you have a look at this?

**Comment by headius** [comment]
Would be nice to get this fixed and the spec running.

**Comment by headius** [comment]
So this is another case where we are propagating the break out like we should, but we don't produce a rescuable LJE until it's too late. So there's some missing logic at the closure boundary (a proc in this case) to know that the break has no target and the LJE needs to start propagating earlier.

**Comment by eregon** [comment]
The full backtrace is
```
1)
An exception occurred during: loading /home/eregon/code/jruby/spec/ruby/language/break_spec.rb
The break statement in a captured block when the invocation of the scope creating the block is still active raises a LocalJumpError when invoking the block from the scope creating the block ERROR
LocalJumpError: unexpected break
org/jruby/RubyKernel.java:979:in `load'
/home/eregon/code/jruby/spec/mspec/lib/mspec/runner/mspec.rb:1:in `block in (root)'
org/jruby/RubyBasicObject.java:1691:in `instance_eval'
/home/eregon/code/jruby/spec/mspec/lib/mspec/runner/mspec.rb:81:in `files'
/home/eregon/code/jruby/spec/mspec/lib/mspec/runner/mspec.rb:98:in `block in protect'
org/jruby/RubyArray.java:1734:in `each'
/home/eregon/code/jruby/spec/mspec/lib/mspec/runner/mspec.rb:81:in `files'
/home/eregon/code/jruby/spec/mspec/lib/mspec/runner/mspec.rb:72:in `each_file'
/home/eregon/code/jruby/spec/mspec/lib/mspec/runner/mspec.rb:77:in `files'
/home/eregon/code/jruby/spec/mspec/lib/mspec/runner/mspec.rb:48:in `process'
/home/eregon/code/jruby/spec/mspec/lib/mspec/commands/mspec-run.rb:83:in `run'
spec/mspec/bin/mspec-run:7:in `<main>'
```

So it seems the stack is unwound until the load call, which is way too far.
It should stop at the rescue inside:
```
lambda { @program.break_in_method }.should raise_error(LocalJumpError)
```

**Comment by headius** [comment]
Yes, it doesn't stop at the rescue for the reason I mentioned above. We need to raise the LJE immediately when we can determine the break is not valid, so it can be rescued.

A hacky alternative I've considered is to make LJE and superclasses match our non-local flow exceptions, but it would be better to just raise the real one.

**Comment by headius** [comment]
Reopening to backport to 9.1.14.
