### ISSUE TITLE
Javadoc jar published to Maven Central contains no content

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4579]
As part of our releases, we publish a javadoc jar. Unfortunately it seems to be empty.

This appears to affect both 1.7 and 9k.

cc @mkristian @enebo

**Comment by headius** [comment]
Link to example empty jar: http://search.maven.org/remotecontent?filepath=org/jruby/jruby/9.1.8.0/jruby-9.1.8.0-javadoc.jar

**Comment by enebo** [comment]
@mkristian If you are game to fix this by Monday we can reinclude this in 9.1.9.0 but otherwise I think we can punt it since our Javadocs suck and it has been this way for a while.

**Comment by mkristian** [comment]
@enebo will do either today or sunday
