### ISSUE TITLE
Broken post-arg and arity logic in compiler

### ISSUE THREAD

**Issue by headius** [jruby/jruby#458]
There are some failures in the MRI 1.9.3 tests that relate to arity-checking a specific form of lambda arguments and post arguments. These may or may not be important to normal apps. The missing ArgumentError is probably not a large concern, since it would be an error. Post arguments are only rarely used, still, so they're also unlikely to come up often.

Nevertheless, these should be fixed. They are excluded for now.

```
  2) Failure:
test_exact_parameter(TestLambdaParameters) [/Users/headius/projects/jruby/test/externals/ruby1.9/ruby/test_lambda.rb:6]:
ArgumentError expected but nothing was raised.

  3) Failure:
test_proc_args_opt_and_rest_and_post(TestProc) [/Users/headius/projects/jruby/test/externals/ruby1.9/ruby/test_proc.rb:474]:
<[1, nil, :c, [], nil]> expected but was
<[1, nil, :c, [], 1]>.

  4) Failure:
test_proc_args_opt_and_rest_and_post_and_block(TestProc) [/Users/headius/projects/jruby/test/externals/ruby1.9/ruby/test_proc.rb:657]:
<[1, nil, :c, :d, [], nil, nil, NilClass, nil]> expected but was
<[1, nil, :c, :d, [], nil, 1, NilClass, nil]>.

  5) Failure:
test_proc_args_rest_and_post(TestProc) [/Users/headius/projects/jruby/test/externals/ruby1.9/ruby/test_proc.rb:390]:
<[1, nil, [], nil, nil]> expected but was
<[1, nil, [], nil, 1]>.

  6) Failure:
test_proc_args_rest_and_post_and_block(TestProc) [/Users/headius/projects/jruby/test/externals/ruby1.9/ruby/test_proc.rb:541]:
<[1, nil, [], nil, nil, NilClass, nil]> expected but was
<[1, nil, [], nil, 1, NilClass, nil]>.
```

**Comment by enebo** [comment]
We do have some tagged tests on 9k in MRI tests but the names are not exactly the same and this clearly was marked against 1.7.  Closing.  If we want to advertise fixing tags in MRI tests we can just open up an issue per thing fixed once we fix them.
