### ISSUE TITLE
Define method with GBK name by using 'def' has wrong symbol name

### ISSUE THREAD

**Issue by pbl-pw** [jruby/jruby#4580]
Refer to #3347 GBK symbol is now ok. But define method by 'def' still has problem.
For exsample:
```
# encoding : GBK
# frozen_string_literal: true

class CTT
	def 测试
		puts "#{__callee__} : first"
	end
	define_method(:测试){
		puts "#{__callee__} : second"
	}
end

obj = CTT.new
obj.测试
obj.send :测试
```
jruby 9.1.9.0-SNAPSHOT (2.3.3) 2017-04-28 ee137a8 Java HotSpot(TM) Client VM 25.131-b11 on 1.8.0_131-b11 +jit [mswin32-x86] output:
```
?? : first
测试 : second
```
MRI output:
```
测试 : second
测试 : second
```

**Comment by kares** [comment]
resolved in JRuby 9.2 with reworded (byte-list) identifiers
```
测试 : second
测试 : second
```
