### ISSUE TITLE
Jruby profiler raises exception when using the holidays gem

### ISSUE THREAD

**Issue by vassilios** [jruby/jruby#4586]
### Environment

* JRuby version (`jruby -v`) 
jruby 9.1.8.0 (2.3.1) 2017-03-06 90fc7ab OpenJDK 64-Bit Server VM 25.72-b15 on 1.8.0_72-internal-b15 +jit [linux-x86_64]

* command line (flags, JRUBY_OPTS, etc)
JRUBY_OPTS="--profile.api"

* Operating system and platform (e.g. `uname -a`)
Linux ip-172-30-3-223 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Other relevant info 
* gem install holidays -v 5.5.0

### Expected Behavior

Using jruby 1.7.22 (on same server)

    $ jruby -v
    jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on OpenJDK 64-Bit Server VM 1.8.0_72-internal-b15 +jit [linux-amd64]

    $ jruby -rdate -rholidays -e 'puts Date.civil(2017,2,20).holiday?(:us)'
    Profiling enabled; ^C shutdown will now dump profile info
    true

### Actual Behavior

    $ jruby -v
    jruby 9.1.8.0 (2.3.1) 2017-03-06 90fc7ab OpenJDK 64-Bit Server VM 25.72-b15 on 1.8.0_72-internal-b15 +jit [linux-x86_64]

    $ jruby -rdate -rholidays -e 'puts Date.civil(2017,2,20).holiday?(:us)'
    Profiling enabled; ^C shutdown will now dump profile info
    LoadError: load error: holidays -- java.lang.UnsupportedOperationException: We do not know enough about the arity to convert it to a signature
      require at org/jruby/RubyKernel.java:961
      require at /opt/jruby-9.1.8.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:133

**Comment by vassilios** [comment]
Thank you!

**Comment by dewani-saurabh** [comment]
How did you solve the issue??
