### ISSUE TITLE
COPYING is missing Java libraries

### ISSUE THREAD

**Issue by madrob** [jruby/jruby#4587]
jruby-complete bundles jline (3 clause bsd) but does not include the license text in its COPYING file.

We had it before, but then lost it in 2da0320

cc: @headius

**Comment by headius** [comment]
Yup, we should fix that.

**Comment by madrob** [comment]
Cracking open `jruby-complete-9.1.8.0.jar` I see the following jars:

jar | license | link
--- | -------- | ----
jline/jline/2.11/jline-2.11.jar 	| BSD-3 | https://github.com/jline/jline2
jopenssl.jar 	| EPL/GPL/LGPL | https://github.com/jruby/jruby-openssl
json/ext/generator.jar | Ruby |	https://github.com/flori/json
json/ext/parser.jar |	Ruby | https://github.com/flori/json
org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.jar | 	MIT | 
org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar | 	MIT | 
org/yaml/snakeyaml/1.18/snakeyaml-1.18.jar | 	ASLv2 | https://github.com/asomov/snakeyaml
psych.jar |	EPL/GPL/LGPL | https://github.com/ruby/psych
racc/cparse-jruby.jar | 	??? | ???
readline.jar |	EPL/GPL/LGPL | https://github.com/jruby/jruby-readline

Also, looking at the `.class` files present, I can account for most of the current ASLv2 list in the current COPYING. I think we'll need to add all these:

folder | license | link
------- | --------- | ----
me/qmx/jitescript | ASLv2 | https://github.com/qmx/jitescript
jnr/posix | EPL/GPL/LGPL | https://github.com/jnr/jnr-posix
jnr/x86asm | MIT | https://github.com/jnr/jnr-x86asm
com/headius/options | ASLv2 | https://github.com/headius/options
com/headius/invokebinder | ASLv2 | https://github.com/headius/invokebinder
com/headius/unsafe/fences | ASLv2 | https://github.com/headius/unsafe-fences
com/jcraft/jzlib | BSD-3 | http://www.jcraft.com/jzlib/LICENSE.txt

I'm also a little confused about how we bundle with [maven](https://github.com/jruby/jruby/blob/master/COPYING#L46). I think I saw it included inside of readline, but that seemed strange enough that I'd rather ask for help than try to research it on my own.

If this list looks complete, then it should just be a matter of collecting the appropriate pieces and updating our COPYING file.

**Comment by headius** [comment]
I filled in the rest of your chart above (racc and bouncycastle). This looks like a good list and I agree we should note each library in COPYING.

**Comment by madrob** [comment]
racc is LGPL not GPL according to the link you gave, updated the chart

**Comment by headius** [comment]
Oops, thanks.

**Comment by madrob** [comment]
PR was merged, thanks!

**Comment by madrob** [comment]
Just realized I forgot to include the json libs.

**Comment by headius** [comment]
Ok, all set then!
