### ISSUE TITLE
Introduce Date._strptime in Java to improve the performance

### ISSUE THREAD

**Issue by muga** [jruby/jruby#4591]
### Overview

- I want to improve the performance of `Date._strptime` method.
- I'm implementing `Date._strptime` in Java on https://github.com/embulk/embulk/pull/608
- Can you consider about introducing our implementation to JRuby? If you agree, I will work on it after completing the implementation.

### Details

My application, Embulk, is using JRuby and heavily using `Date._strptime` method internally to parse timestamp strings. I found that the heavy usage is one of the performance bottlenecks in my application.
To mitigate the performance issue, I started implementing `Date._strptime` in Java. The features are:

- 100% compatibility with the specification of `Date._strptime` in CRuby
- Faster performance because the # of objects passing is reduced between Java and (J)Ruby
- The implementation uses similar approach with `org.jruby.util.RubyDateFormatter` and `org.jruby.lexer.StrftimeLexer`.

### Environment

- JRuby 9.1.5.0
- Java 1.8.0_91 64-Bit Server VM (build 25.91-b14, mixed mode)
- Ubuntu 16.04

**Comment by headius** [comment]
@muga We'd love to incorporate your implementation! Provide a PR and let us know you consent to it being in JRuby under our tri-license (GPL 2, LGPL 2, EPL). Thank you!

**Comment by muga** [comment]
@headius Thank you for letting me know. I complete the implementation and then create new PR.

**Comment by kares** [comment]
related https://github.com/jruby/jruby/issues/3640 (include some numbers)

**Comment by muga** [comment]
@kares We started reviewing the implementation on our application github repo https://github.com/embulk/embulk/pull/611. I'll do my best :)

**Comment by muga** [comment]
I'm closing this ticket because #4635 was merged into master.
