### ISSUE TITLE
The behavior of Enumerable#each_with_index has changed in JRuby 9.1.9.0

### ISSUE THREAD

**Issue by koic** [jruby/jruby#4610]
### Environment

* jruby 9.1.9.0 (2.3.3) 2017-05-15 28aa830 Java HotSpot(TM) 64-Bit Server VM 25.5-b02 on 1.8.0_05-b13 +jit [darwin-x86_64]
* Darwin Kernel Version 13.0.2: Sun Sep 29 19:38:57 PDT 2013; root:xnu-2422.75.4~1/RELEASE_X86_64 x86_64

### Expected Behavior

This is behavior of JRuby 9.1.8.0 and MRI 2.4.1 and MRI 2.5.0dev (2017-05-16 trunk 58738) .

```ruby
> %i(foo bar baz).each_with_index {|v| puts v.inspect }
:foo
:bar
:baz
```

### Actual Behavior

This is behavior of JRuby 9.1.9.0.

```ruby
> %i(foo bar baz).each_with_index {|v| puts v.inspect }
[:foo, 0]
[:bar, 1]
[:baz, 2]
```

JRuby 9.1.9.0 returns array object. Is this intentionally changed?

**Comment by headius** [comment]
Huh, I wonder what changed.

**Comment by headius** [comment]
I do not see any modifications to `each_with_index` directly, but there are some changes to the utility methods it uses in RubyEnumerable.

This code is unfortunately rather fragile. MRI seems to have strange rules (or else no rules at all) about which Enumerable methods will break up arguments this way and which will box them in array. We probably fixed it for one method and broke it for others.

**Comment by headius** [comment]
It appears to be from e4adab3be6809078c97214d6484ca8e55c49951e which was part of clean-up efforts for our block protocol. It seems this one might have overreached a bit. cc @enebo

**Comment by PragTob** [comment]
Hello friends :wave: 

Just one "me too" for the simplecov gem (and I'm about to check if shoes4 is affected).

Honestly, I think I'd appreciate a patch level release.. but well, I can also do simplecov patch level release :)

**Comment by PragTob** [comment]
simplecov-html 0.10.1 released with a fix. Shoes4 otherwise unaffected :)

**Comment by koic** [comment]
Thank you for the quick answer. I understood that it was an unexpected regression.

**Comment by aviflax** [comment]
I’m looking forward to a patch release that fixes this… I’m eager to upgrade to 9.1.9.x but this regression makes me nervous.

**Comment by npomf** [comment]
Depending on if block arity is being checked, this could make sense; an arity of 1 could thus infer passing the array object produced by `each_with_index()`, wherein an arity of 2 would perform the expected splat of the values.

That might make sense for the change from `call()` to `yieldSpecific()`, which I believe I recall reading functions similar to what's described above.

Oddly enough, a quick check of both JRuby 9.1.9.0 and MRI 2.3.3 works for the following:

```ruby
# convert array to Hash of index => value
Hash[ [:foo, :bar, :baz].each_with_index.map {|value, index| [index, value] }]
```

**Comment by enebo** [comment]
I reverted this in ad368eedd4bcf376edbdd2ea238fec3e1c25030d.  With the millions of specs/test asserts we do apparently this is not covered and I did not try/think of this permutation.

The original intent is that we are slowly cleaning up our internal call paths for blocks/closures such that we can replace them with our own IR instructions when we inline a block back through a method.  Unfortunately, the Enumerable stuff is the most difficult to follow.

I will put out 9.1.10.0 this week with this fix and a second fix for become_java! (unrelated to users of this issue).

**Comment by koic** [comment]
Thank you for the release of JRuby 9.1.10.0. I confirmed that this regression was resolved.

**Comment by mojavelinux** [comment]
It seems like this bug is back in 9.1.11.0 and 9.1.12.0. See:

* https://travis-ci.org/asciidoctor/asciidoctor/builds/257592282
* https://travis-ci.org/asciidoctor/asciidoctor/builds/257593658

**Comment by enebo** [comment]
@mojavelinux thanks for letting us know.  Opened #4724 to track this second regression :(

**Comment by mojavelinux** [comment]
:+1:
