### ISSUE TITLE
REGRESSION - File.realpath fails on classpath paths

### ISSUE THREAD

**Issue by trejkaz** [jruby/jruby#4612]
### Environment

JRuby 9.1.9.0
*Windows only*

### Test Case

    @Test
    public void testResolveClasspath() throws Exception
    {
        ScriptEngine engine = createEngine();

        String path = "classpath:/path/to/this/TestRubyFile.class";
        String result = (String) engine.eval("File.realpath('" + path + "')");
        assertThat(result, is(equalTo(path)));
    }

    protected ScriptEngine createEngine()
    {
        return new JRubyEngineFactory().getScriptEngine();
    }

### Expected Behavior

Test should pass, like it did on JRuby 9.0.5.0.

### Actual Behavior

Test now fails:

    Caused by: org.jruby.exceptions.RaiseException: (Errno::ENOENT) classpath:BY\path\to\this\TestRubyFile.class
	at org.jruby.RubyFile.realpath(org/jruby/RubyFile.java:864)
	at RUBY.<main>(<script>:1)

I'm not sure where it pulled the "BY\" from, but the slashes are in the wrong direction too.

**Comment by trejkaz** [comment]
Problem _appears_ to be here:

```
        else if (protocol.find()) {
            preFix = protocol.group();
            int offset = protocol.end();
            String extra = "";
            if (relativePath.contains("file://")) {
                if (relativePath.contains("file:///")) {
                    offset += 2;
                    extra = "//";
                }
                else {
                    offset += 1;
                    extra = "/";
                }
            }
            relativePath = canonicalizePath(relativePath.substring(offset));
            if (Platform.IS_WINDOWS && !preFix.contains("file:") && startsWithDriveLetterOnWindows(relativePath)) {
                // this is basically for classpath:/ and uri:classloader:/
                relativePath = relativePath.substring(2).replace("\\", "/");
            }
            return runtime.newString(preFix + extra + relativePath);
        }
```

This call to canonicalizePath is implemented as follows:

```
    private static String canonicalizePath(String path) {
        try {
            return new File(path).getCanonicalPath();
        } catch (IOException ignore) {
            return path;
        }
    }
```

That `File#getCanonicalPath()` call will return the path with backslashes, so now it's already broken. Still not quite sure how a `"BY\"` ends up in there as well.

**Comment by trejkaz** [comment]
Seems to have been fixed in 9.1.10.0.

**Comment by trejkaz** [comment]
The new behaviour is:

```
Expected: is "classpath:/org/joda/time/DateTime.class"
     but: was "classpath:\org\joda\time\DateTime.class"
```

I remember I had commented on slash direction in `File` in the past, and was told that because MRI always produced forward slashes, JRuby also produced forward slashes... but is this not the case anymore? Would be fine by me. Although... I don't know about producing backslashes in a classpath... maybe it's OK?

**Comment by mkristian** [comment]
just our of curiosity - does this also happen for `uri:classloader:/
path/to/this/TestRubyFile.class` as `classpath:/` is 'translated' to
`uri:classloader` when resolving to `Resource` objects ?

**Comment by trejkaz** [comment]
Tried `uri:classloader:/...` - it fails with `AccessControlException` when it tries to read IDEA's jar here:

	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at org.jruby.util.JarCache$JarIndex.<init>(JarCache.java:46)
