### ISSUE TITLE
jrubyc compiled representation breaks but source rb works fine

### ISSUE THREAD

**Issue by stergiom** [jruby/jruby#4621]
### Environment

The AOT compiled representation of code utilising the `dry-auto_inject` gem breaks yet works fine when the source rb is used, - [gist illustrating the issue](https://gist.github.com/stergiom/f4d79fa01488401dcf5e3334e002e869#file-output-sh-L17)

* _Tested with 9.1.7.0 & 9.1.9.0, the issue is present in both cases_

### Expected Behavior

Same behavior as with the source rb

### Actual Behavior

An `ArgumentError` is thrown

**Comment by flash-gordon** [comment]
The more concise example:
```ruby
class A
  def initialize(foo: 1)
  end
end

class B < A
  def initialize(*, **)
    super
  end
end

B.new
```

Fails with 
```
ArgumentError: unknown keyword:
```

But 
```ruby
class B < A
  def initialize(*)
    super
  end
end
```
works fine. This means the problem is in using `**` along with `*`, this should make no difference
 so it looks like a minor bug.

@stergiom just remove `**` from your constructor and you should be fine.
