### ISSUE TITLE
Delete old TruffleRuby support repositories

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#4624]
There are several left-over repositories that were supporting TruffleRuby.

* https://github.com/jruby/all-ruby-benchmarks
* https://github.com/jruby/jruby-truffle-gem-test-pack
* https://github.com/jruby/jruby-build-pack
* https://github.com/jruby/benchmark-interface
* https://github.com/jruby/deep-bench
* https://github.com/jruby/bench9000
* https://github.com/jruby/jruby-truffle-stack
* https://github.com/jruby/pushing-pixels-benchmarks

We aren't using them any more. Are you happy for me to delete them? Or would you prefer we left them in place?

**Comment by chrisseaton** [comment]
I have local backups of these repos, and almost all the content is now in https://github.com/graalvm/truffleruby. I'll be deleting these today unless anyone wants to stop me.

**Comment by headius** [comment]
If all the content has been moved, I see no reason to keep them. Have at it!
