### ISSUE TITLE
Inconsistency dumping integer with YAML

### ISSUE THREAD

**Issue by Tonkpils** [jruby/jruby#4626]
### Environment

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [darwin-x86_64]
* Operating system and platform (e.g. `uname -a`)
Darwin Leonardos-MacBook-Pro-3.local 16.7.0 Darwin Kernel Version 16.7.0: Tue May  9 11:48:28 PDT 2017; root:xnu-3789.70.9~16/RELEASE_X86_64 x86_64

### Expected Behavior

```ruby
2.4.1 :001 > require 'yaml'
 => true
2.4.1 :002 > YAML.dump(30)
 => "--- 30\n...\n"
```

### Actual Behavior
```ruby
jruby-9.1.7.0 :002 > require 'yaml'
 => true
jruby-9.1.7.0 :003 > YAML.dump(30)
 => "--- 30\n"
```

**Comment by headius** [comment]
Does this affect you in some way? We have found these minor differences are usually due to the downstream YAML library we use, but they don't affect round-tripping. MRI loads our output correctly, and we load theirs correctly.

**Comment by Tonkpils** [comment]
Yeah, I was actually debugging a library that uses msgpack which managed to load the output of the jruby version yank output but raised an exception on the MRI one because of the extra characters. 

I ended up releasing a new version of the library that yanked YAML support since it was for backwards compatibility anyway but I just thought I would report it.
