### ISSUE TITLE
Jarified app breaks with `uri:classloader:BY\` on Windows with 9.1.10.0

### ISSUE THREAD

**Issue by stergiom** [jruby/jruby#4630]
### Expected Behavior
A working Jar

### Actual Behavior
The app breaks _(seemingly only on Windows)_ at the first line `require "jrubyfx"` with what seems to be an error related to the `:BY\` in its path..

```cmd
>java -jar main.jar
Errno::ENOENT: No such file or directory - uri:classloader:BY\jrubyfx.rb
          realpath at org/jruby/RubyFile.java:864
  require_relative at uri:classloader:/jruby/kernel/kernel.rb:11
            <main> at uri:classloader:/jrubyfx.rb:34
           require at org/jruby/RubyKernel.java:961
            (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
            <main> at classpath:/jar-bootstrap.rb:1
```

**Comment by headius** [comment]
Can you provide an example build for us to reproduce this?

**Comment by stergiom** [comment]
-> [Example build](https://github.com/jruby/jruby/files/1045831/app.zip)

`uri:classloader:BY\` has come up with #4612, this seems specific to `expandPathInternal`, it might be related to the last two letters of this statement.. https://github.com/jruby/jruby/blob/949da5180f6d457c451ca77e6ba741e454b02b90/core/src/main/java/org/jruby/RubyFile.java#L1666

**Comment by mkristian** [comment]
looks like on windows `"/THIS_IS_A_FAKE_PATH_FOR_JRUBY"` is not treated as absolute path and handled differently somewhere else. a `c:\THIS_IS_A_FAKE_PATH_FOR_JRUBY` might work for windows platforms. @stergiom fancy to patch and try it out ?
