### ISSUE TITLE
Gem lookup problem when warbling on Windows

### ISSUE THREAD

**Issue by jasonrclark** [jruby/jruby#4653]
### Environment

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
  * Building with `jruby-jars` for 9.1.10.0 on Mac (`jruby 9.1.8.0 (2.3.1) 2017-03-06 90fc7ab Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 [darwin-x86_64]`)
  * _running resulting jar on Windows (so using embedded `jruby-jar` components) rather than installed JRuby_

* Operating system and platform (e.g. `uname -a`)
Running jars on `MSYS_NT-6.1 IE11Win7 2.6.0(0.304/5/3) 2016-09-09 09:32 i686 Msys`

Other relevant info you may wish to add:
* This problem manifests when using `warbler` to build a standalone jar for execution, but only on Windows.
* Test repo at  https://github.com/jasonrclark/tale-of-two-warbles

### Expected Behavior

A standalone jar built with warbler should load the embedded gems when running on Windows.

### Actual Behavior

A standalone warbled jar can't load the embedded gems when running with JRuby 9.1.10.0's `jruby-jars` vs JRuby 9.1.8.0 when on Windows.

A sample repo is available at https://github.com/jasonrclark/tale-of-two-warbles that demonstrates the problem and has both versions side-by-side for demonstration.

This was [found in Shoes during testing](https://github.com/shoes/shoes4/pull/1442) for our next pre-release.

The exact error is a typical `LoadError`:

```
LoadError: no such file to load -- active_support
  require at org/jruby/RubyKernel.java:961
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:130
   <main> at uri:classloader:/9.1.10.0/app.rb:3
     load at org/jruby/RubyKernel.java:979
   <main> at uri:classloader:/META-INF/main.rb:1
  require at org/jruby/RubyKernel.java:961
   (root) at uri:classloader:/META-INF/main.rb:1
   <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
```

The `Gem.paths.path` in both working (9.1.8.0) and non-working (9.1.10.0) cases are the same:

```
C:/Users/IEUser/.gem/jruby/2.3.0
uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared
uri:classloader:
```

 I'm mildly suspicious that it could be related to https://github.com/jruby/jruby/pull/4543 which relates to how classloader paths are handled, and happened in the right version range. Could potentially also be something with the new Rubygems that 9.1.9.0 (and hence 9.1.10.0) pulled in.

**Comment by mprins** [comment]
may be fixed with #4647

**Comment by jasonrclark** [comment]
That looks like it's almost certainly the same thing. Thinking back I suspect I searched only open issues... doh! Thanks.

**Comment by headius** [comment]
@jasonrclark If you get a chance, verify with JRuby master. Thanks for the update!

**Comment by jasonrclark** [comment]
@headius Didn't get to checking on master, but did bump to 9.1.11.0 and everything works smoothly. Thanks @kares for the quick fix! ✨
