### ISSUE TITLE
JRuby raises 'syntax error, unexpected kDO_BLOCK' where MRI does not

### ISSUE THREAD

**Issue by eprothro** [jruby/jruby#4663]
Experienced in  9.1.5.0, reproduced in 9.1.9.0 as well.

```
SyntaxError: /Users/eprothro/.rbenv/versions/jruby-9.1.9.0/lib/ruby/gems/shared/gems/perform-later-1.0.0/lib/perform_later/aliasing.rb:47: syntax error, unexpected kDO_BLOCK
        perform_async(method, *args).tap do |id|

  org/jruby/RubyKernel.java:961:in `require'
```

Patch showing workaround with different block syntax:

https://github.com/eprothro/perform-later/commit/2b7e9edd8aad25d02e2313e953fed10589bef04a#diff-27c9b4687d0af0abaa0b859ff0486858

**Comment by enebo** [comment]
Reduced to:

```ruby
foo ->() do
  bar.gar do |id|
  end
end
```

So stabby needs to be an argument for this to fail AND gar needs to be a call and not an fcall.
