### ISSUE TITLE
become_java! does not respect superclass (methods)

### ISSUE THREAD

**Issue by HeikoBornholdt** [jruby/jruby#4670]
I've got the ruby classes `Foo` & `Bar`and want to generate the corresponding java class with `become_java!`:
`````ruby
class Foo
  def foo
    puts 'Hello foo'
  end
end

class Bar < Foo
  def bar
    puts 'Hello bar'
  end
end

cls = Bar.become_java!
cls.declared_methods.each do |method|
  puts method.name
end
`````

### Expected Behavior (ruby script output)
`````ruby
foo
bar
clinit
`````

### Actual Behavior (ruby script output)
`````ruby
bar
clinit
`````
(`foo` is missing)

### Environment
`````bash
$ ruby -v
jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +jit [darwin-x86_64]

$ echo $JRUBY_OPTS
$
`````

**Comment by headius** [comment]
I don't think this has ever worked, has it?

**Comment by heikobornholdt** [comment]
I'm new to jruby, so I can't answer this question.

Does someone know a workaround to call `foo` in Java?
