### ISSUE TITLE
Error installing rubygems-bundler in 9.1.11.0

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby#4671]
Using the latest version of rvm to install 9.1.11.0 with the command `rvm install jruby-9.1.11.0`, I get the following error on both Mac 10.12 and Ubuntu 16.04:

```
ERROR:  Error installing rubygems-bundler:
        invalid gem: package is corrupt, exception while verifying:  (Java::JavaLang::ArrayIndexOutOfBoundsException) in /home/web/.rvm/gems/jruby-9.1.11.0@global/cache/executable-hooks-1.3.2.gem
```

I also get the same error when trying to install `gem install gcm -v '0.0.2'`, which makes me think this is a jruby issue and not a rvm issue...

```
ERROR:  Error installing gcm:
	invalid gem: package is corrupt, exception while verifying:  (Java::JavaLang::ArrayIndexOutOfBoundsException) in /home/web/.rvm/gems/jruby-9.1.11.0/cache/gcm-0.0.2.gem
```

I've tried uninstalling & reinstalling several times to be sure its not a case of a corrupted download or anything as well.

**Comment by enebo** [comment]
yay...I guess 9.1.12.0 will be coming tomorrow.  This is probably a bit bigger than we want (although I installed like 30-40 gems during testing and never hit this).

**Comment by enebo** [comment]
our recent PR for unreading stuff had a small flaw which did not consider the case that the read() was already at EOF.  Surprisingly, we probably mostly hit a path where we read() to end but do not need to call isEOF().
