### ISSUE TITLE
SSL connection fails due to no available cipher on IBM JRE

### ISSUE THREAD

**Issue by ysohda** [jruby/jruby#4679]
Hi,

Due to no available cipher for TLSv1.2 on IBM JRE, SSL connection fails.

The reason of no available cipher is a difference of cipher suite names as I reported on jruby-openssl:
https://github.com/jruby/jruby-openssl/issues/125
The pull request to solve this issue has been merged:
https://github.com/jruby/jruby-openssl/pull/126

So, it would be nice if jruby-openssl bundled with jruby is updated on next jruby release.
@kares, could you please help us to update jruby-openssl in jruby?

Thank you,
Yuki.

### Environment
```
>jruby -v
jruby 9.1.12.0 (2.3.3) 2017-06-15 33c6439 IBM J9 VM 2.8 on pwa6480sr4fp5-20170421_01 (SR4 FP5) +jit [mswin32-x86_64]
```
OS: Windows 7 Professional (x64)

### Current Behavior
```
>gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
   Unable to download data from https://rubygems.org/ - Received fatal alert: handshake_failure (https://api.rubygems.org/specs.4.8.gz)
```
With debug option:
```
>jruby -J-Djavax.net.debug=all -S gem install bundler
IBMJSSE2 will not allow protocol SSLv3 per com.ibm.jsse2.disableSSLv3 set to TRUE or default
IBMJSSEProvider2 Build-Level: -20170331
Installed Providers =
        IBMJSSE2
        IBMJCE
        IBMJGSSProvider
        IBMCertPath
        IBMSASL
        IBMXMLCRYPTO
        IBMXMLEnc
        IBMSPNEGO
        SUN
 <snip> 
Is initial handshake: true
Ignoring unsupported cipher suite: SSL_RSA_WITH_DES_CBC_SHA for TLSv1.2
Ignoring unsupported cipher suite: SSL_DHE_RSA_WITH_DES_CBC_SHA for TLSv1.2
No available cipher suite for TLSv1.2
 <snip>
```

### Expected Behavior
When I replaced "jruby-9.1.12.0\lib\ruby\stdlib\jopenssl.jar" by one in jruby-openssl-0.9.21.dev-20170329.100355-1.gem, it works as expected:
```
>gem install bundler
Fetching: bundler-1.15.1.gem (100%)
Successfully installed bundler-1.15.1
1 gem installed
```

**Comment by kares** [comment]
next JRuby release (9.2) will for sure update. we have not forgoten about this, there's simply a lot on the plate (more long term issues that need adressing). also thought the pre release is useful for now. sorry for the wait, doing my best ...

**Comment by kares** [comment]
expected to be resolved with https://github.com/jruby/jruby/pull/4726

**Comment by ysohda** [comment]
Hi Kares, 
Thank you for your work to update jruby-openssl in JRuby.
It looks that JRuby 9.1.13.0 is scheduled, so it would be nice if your effort is also in 9.1.13.0.
Thank you,
Yuki.

**Comment by AndrewClarke** [comment]
So.... for the dummies out here, what's the work-around to get past this problem?
