### ISSUE TITLE
Where to find changelog?

### ISSUE THREAD

**Issue by Paxa** [jruby/jruby#4680]
Where can I find changelog for previous versions?

I see only release notes for latest release

**Comment by donv** [comment]
Hi @Paxa !

You can find announcements for older releases here:  http://jruby.org/news

**Comment by headius** [comment]
We have discussed generating changelogs from git commits in the past, but we don't see the value. It's simple enough to get a log between two release tags. We also find the raw commit logs to be too verbose and not as useful as our hand-created release notes that @donv pointed out.
