### ISSUE TITLE
RubyEnumerator.SizeFn does not receive enough context

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4688]
In order to implement enumerators with sizes, we have a SizeFn interface we implement for various types of collection and enumeration. However this interface currently only receives `IRubyObject[]` which means the runtime, context, self, and other contextual values must be captured (usually as an anonymous inner class) or acquired (e.g. `runtime.getCurrentContext()`).

This interface should be expanded to accept at least context and self, and all uses should be audited to see if we can make the impls static instances rather than creating them anew each time.

**Comment by anukin** [comment]
@headius I have raised a PR here https://github.com/jruby/jruby/pull/4714. Can you take a look ?

**Comment by headius** [comment]
@anukin I have reworked your original PR and will finish the remaining requirements of this issue as part of #6321. Thank you for your help, even though it got left behind.

**Comment by anukin** [comment]
Hey thanks :)

**Comment by edipofederle** [comment]
@headius could you close this issue?

**Comment by headius** [comment]
@edipofederle Yeah I guess this should have gone along with #6321. Thanks for the audit!
