### ISSUE TITLE
File path canonicalization still broken inside jars on Windows

### ISSUE THREAD

**Issue by presidentbeef** [jruby/jruby#4692]
Despite https://github.com/jruby/jruby/pull/4647 and earlier patches, this issue persists.

[As](https://github.com/jruby/jruby/issues/4188) [previously](https://github.com/jruby/jruby/issues/4645), please see https://github.com/presidentbeef/jruby-realpath-error and the simple reproduction steps therein.

I hate to keep mentioning this, but due to this issue we are still stuck releasing on JRuby 1.7.

### Expected Behavior

On Linux with JRuby 9.1.11.0:

```
$ java -jar myapp.jar
"uri:classloader:/lib/test.rb"
"classpath:/jar-bootstrap.rb"
```

### Actual Behavior

On Windows with JRuby 9.1.11.0:

```
> java -jar myapp.jar
LoadError: no such file to load -- classpath:c:/lib/test
           require at org/jruby/RubyKernel.java:961
  require_relative at uri:classloader:/jruby/kernel/kernel.rb:13
            <main> at classpath:/jar-bootstrap.rb:1
```

**Comment by presidentbeef** [comment]
Should probably tag @kares

**Comment by stergiom** [comment]
@presidentbeef, have you tried with 9.1.12.0? This worked for me.

**Comment by presidentbeef** [comment]
9.1.12.0 has the same behavior.

**Comment by enebo** [comment]
@presidentbeef can you try latest on jruby-9.1.13 branch?   @kares added some logic which should work a week or two ago and it did not get associated with this issue.

**Comment by enebo** [comment]
Ah I knew I had downloaded your test repo but now running it I can see require_relative is broken still although I think @kares patch did fix a good chunk of the issues around the fakepath part of it all.  So here is a smaller repro:

```ruby
relative_arg = "lib/test"
dir = "classpath:/"
p File.expand_path(relative_arg, dir)
```

This prints out 

```text
"classpath:C:/lib/test"
```

The C: should not be there...

**Comment by presidentbeef** [comment]
Thanks for checking @enebo.

**Comment by enebo** [comment]
Ok fixed the letter and now I see this:

```text
"uri:classloader:\\lib\\test.rb"
"classpath:\\jar-bootstrap.rb"
```

GRRRRRRR,  :)

**Comment by enebo** [comment]
Yay...so __FILE__ is correct but File.realpath is swapping the / to \\.  So a second weird behavior.   

@presidentbeef Is the reason for doing this to potentially elide stuff like '..' or '.'.  I don't think classpath uris can actually have softlinks.  With that said it no classpath: uri should ever get converted to back slashes.  So it should just get fixed.

**Comment by presidentbeef** [comment]
Our app does have a lot of uses of `require_relative "../../` but it would be nice for it to "just work" inside a jar.

**Comment by enebo** [comment]
@presidentbeef yeah I think you should not need to be concerned with whether you are calling with real filesystem paths or a classpath uri.  I just wondered if you were using it for '..'.  I am pushing a fix here.  I would love it if you could try your product on jruby-9.1 branch and see if it is golden now?

**Comment by presidentbeef** [comment]
9.1.13.0 works!! Thank you @enebo 😄
