### ISSUE TITLE
Super does not mark literal blocks as escaped

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4695]
For #4686 and #4577 I did #4694 to start setting all literal blocks as "escaped" once the method they are passed to has returned. This allows us to properly raise LocalJumpError when a block with a break escapes its original context.

However I did not fix super, because there's longer and more complicated logic paths through which we'd need to push the literal closure information, and there's no one location where we can do the try/finally to set the block escaped.

This bug is for that work to be done.

Example case:

```ruby
class A; def foo(&b); b; end; end
class B; def foo; super { break }.call; end
B.new.foo
```

This should raise a rescuable LocalJumpError at the break, but instead it unrolls most of the stack.

**Comment by eregon** [comment]
@headius Could you write a spec with this code?
I also had to fix break with super and noticed it through some assertion failing.

**Comment by headius** [comment]
The case as written is not syntactically correct. It should look like this:

```
class A; def foo(&b); b; end; end
class B < A; def foo; super { break }.call; end; end
B.new.foo
```

This does raise a LocalJumpError on CRuby, which is expected. The block has escaped its original activation.

```
$ ruby -v blah.rb
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
Traceback (most recent call last):
	2: from blah.rb:3:in `<main>'
	1: from blah.rb:2:in `foo'
blah.rb:2:in `block in foo': break from proc-closure (LocalJumpError)
```

In JRuby, it eventually turns into a LocalJumpError, but not before passing through all the other stack frames and bubbling out of the root of the script:

```
$ ruby -v blah.rb
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-07-10 c3a04136fb OpenJDK 64-Bit Server VM 25.222-b10 on 1.8.0_222-b10 +jit [darwin-x86_64]
LocalJumpError: unexpected break
```

More clearly, what's happening is that we do not detect that the block has escaped its original activation because the super call is not wrapped in logic to mark it as such. In other call paths, such as via CachingCallSite, this is done with a try/finally that marks the block as escaped after the call has completed.

I have a Ruby spec for this, and for the similar non-escaping case which does not raise an error on CRuby or JRuby. I will commit that after fixing the issue.
