### ISSUE TITLE
Thread.current.status is wrong for killed thread

### ISSUE THREAD

**Issue by iaddict** [jruby/jruby#4705]
### Environment

Provide at least:
* JRuby version: jruby 9.1.12.0 (2.3.3) 2017-06-15 33c6439 Java HotSpot(TM) 64-Bit Server VM 25.112-b16 on 1.8.0_112-b16 [darwin-x86_64]
* Operating system and platform: Darwin de01pc11303.global.jhcn.net 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

### Expected Behavior

A sleeping thread that gets killed should have status 'aborting' and not 'run'.

### Actual Behavior

The following code outputs 'run' on jruby, whereas on mri it outputs 'aborting'.

```ruby
t = Thread.new {
  begin
    sleep
  ensure
    puts Thread.current.status # should output 'aborting' when killed
  end
}
t.kill
```

Example run on jruby:
```ruby
irb(main):020:0> t = Thread.new { begin; sleep; ensure; puts Thread.current.status; end }
=> #<Thread:0x79ad8b2f@(irb):20 sleep>
irb(main):021:0> t.kill
run
=> #<Thread:0x79ad8b2f@(irb):20 dead>
```

Example run on mri ruby:
```ruby
irb(main):013:0>  t = Thread.new { begin; sleep; ensure; puts Thread.current.status; end }
=> #<Thread:0x007faefc8bad78@(irb):13 run>
irb(main):014:0> t.kill
aborting
=> #<Thread:0x007faefc8bad78@(irb):13 sleep>
```

This code is a simplified version of ActiveRecord transaction code that fails.
See:
  * https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L237
  * Failing test case: https://github.com/rails/rails/blob/master/activerecord/test/cases/transactions_test.rb#L587

**Comment by kares** [comment]
did not expect using `Thread.current.status` to manage transaction state. haven't seen this anywhere else, anyone nows if this is really necessary or just a bad design decision ?

**Comment by eregon** [comment]
Interesting, I recently looked at this in TruffleRuby and could not figure how the user can observe the `aborting` status.
We should definitely add a spec for this.
Note that you might need a `sleep 0.1` before the `t.kill` in the example above to observe it, as otherwise it could kill the thread before it even reaches the `sleep`.

**Comment by iaddict** [comment]
Here is a slightly better version of the sample code which uses a Queue to ensure that the thread is sleeping.
```ruby
q = Queue.new
t = Thread.new { begin; q.push nil; sleep; ensure; puts Thread.current.status; end }
q.pop
t.kill
```

**Comment by iaddict** [comment]
I ran the specs again with the current jruby master branch and they did pass, albeit the above referenced pull request did not catch the issue in its entirety. I created another pull request that properly tests the status of a sleeping killed thread that fails on jruby but passes on mri. See: https://github.com/ruby/spec/pull/462. Thus the problem still is present.

**Comment by eregon** [comment]
That spec is now in jruby and fails as expected:
https://travis-ci.org/jruby/jruby/jobs/275547991
```
     [exec] Thread#status reports aborting on an externally killed thread that sleeps FAILED
     [exec] Expected "run"
     [exec]  to equal "aborting"
     [exec] 
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/thread/status_spec.rb:58:in `block in (root)'
     [exec] org/jruby/RubyBasicObject.java:1750:in `instance_eval'
     [exec] org/jruby/RubyEnumerable.java:1704:in `all?'
     [exec] org/jruby/RubyArray.java:1764:in `each'
     [exec] /home/travis/build/jruby/jruby/spec/ruby/core/thread/status_spec.rb:4:in `<main>'
     [exec] org/jruby/RubyKernel.java:986:in `load'
     [exec] org/jruby/RubyBasicObject.java:1750:in `instance_eval'
     [exec] org/jruby/RubyArray.java:1764:in `each'
```

**Comment by eregon** [comment]
This is still a bug. I tagged the spec so the CI is green in 73b01140aea830b4887e70642ab4328cc439cb95

**Comment by iaddict** [comment]
@eregon Does this mean the bug does not get fixed anytime soon? The AR and transactions (mentioned above) will thus persist?

**Comment by eregon** [comment]
I'm not fixing the bug in JRuby, merely updating the specs.
But I guess @headius might take care of it.

**Comment by headius** [comment]
Additional commit for this, to actually set aborting status upon kill: 919832e3b9444524f705007fa5479b48a5d4c051
