### ISSUE TITLE
[2.4] Hash key randomization, universal hashing, new Hash impl

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4708]
MRI has implemented a new Hash that has some innovative features:

* Open addressing for better cache locality
* Automatically switching over to a secure hash when a "hash DOS" attack is detected.

We currently have the original "chained buckets" implementation of Hash with no generalized hash randomization except for strings. This is open work to be done for JRuby.

See https://bugs.ruby-lang.org/issues/12142
See https://bugs.ruby-lang.org/issues/13002

Part of TBD work for 2.4 support in #4293.

**Comment by headius** [comment]
Tag #4687 for other unimplemented features.

**Comment by eregon** [comment]
> Automatically switching over to a secure hash when a "hash DOS" attack is detected.

AFAIK this was removed later, as it was discovered to be a user-visible change (2 different objects with same `hash` and `eql?` could no longer find the same key in a Hash IIRC).

**Comment by headius** [comment]
@eregon Thanks, makes sense.

**Comment by kares** [comment]
guess we can call this a day for 9.2.1 (with @ChrisBr excellent open-addressing work) 
... although the description mentions some more things such as specialization?

**Comment by ChrisBr** [comment]
According to @eregon this was removed from CRuby later on... So yep, should be fine to close
