### ISSUE TITLE
Puma processes time out when run with JRuby 9.1.8.0+

### ISSUE THREAD

**Issue by batasrki** [jruby/jruby#4722]
This seems to affect all versions of JRuby from 9.1.8.0 upwards. The gory details are in https://github.com/puma/puma/issues/1375 and https://github.com/puma/puma/issues/1359. Essentially, the puma process gets stuck and never returns the response.

I have tested on Ubuntu 16.04 and RHEL 6.6. The JVM version is 1.8.0 rev 131 on both platforms.

The Puma web server fronts a Rails app, version 4.2.8. I can post the Gemfile, but I have tested extensively and the same thing shows up when running Trinidad and Torquebox app servers, as well as Puma. It isn't exclusive to it.

**Comment by kares** [comment]
another /dev/random enthropy depletion ;( seriously need to find some time to look into it at jruby-openssl
closing as a duplicate
