### ISSUE TITLE
to_inputstream method

### ISSUE THREAD

**Issue by ahmgeek** [jruby/jruby#4749]
this is not an actual issue it's just a question regards the method `to_inputstream`:
```
  io = java_input_stream.to_io # works for InputStreams, OutputStreams, and NIO Channels
  stream = io.to_inputstream # also to_outputstream and to_channel
```
Why it's not `to_input_stream` like `to_java_bytes` why the naming is not like ruby snake_case convention ?

update:
also `to_outputstream` shouldn't it be `to_output_stream`

**Comment by kares** [comment]
its simply soft-ware evolution (done by different folks) ... but you're right naming should be consistent :+1:

**Comment by ahmgeek** [comment]
thanks, while we here I edited the issue to include `to_outputstream` so it could be `to_output_stream` 🤗
