### ISSUE TITLE
Implement get_dns_server_list

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#4755]
### Environment

jruby 9.2.0.0-SNAPSHOT (2.4.1) 2017-08-20 c22987a Java HotSpot(TM) 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [mswin32-x86_64]

#4687

### Expected Behavior

get_dns_server_list is not implemented on jruby
https://github.com/jruby/jruby/blob/d3d918af43fc56b57640cc5359e9184b97aae690/lib/ruby/stdlib/win32/resolv.rb#L75

### Actual Behavior

https://github.com/ruby/ruby/blob/202bbda2bf5f25343e286099140fb9282880ecba/ext/win32/resolv/resolv.c

`
>jgem install benchmark-ips
ERROR:  While executing gem ... (NameError)
    undefined local variable or method `get_dns_server_list' for Win32::Resolv:Module
`

**Comment by headius** [comment]
Indeed it is not! Perhaps you can help?

**Comment by ahorek** [comment]
https://github.com/jruby/jruby/pull/5158 it's a workaround and it doesn't fix the original issue https://bugs.ruby-lang.org/issues/12604
I wasn't able to find simmilar API in Java. Can I use the C extension from iphlpapi.h in JRuby using FFI / JNI?

**Comment by headius** [comment]
@ahorek If it's possible to do it through Ruby FFI that would probably be the quickest option. Go for it, and feel free to ping gitter or IRC with questions!

**Comment by headius** [comment]
Marking for 9.2 since we at least seem to have a workaround.

**Comment by ahorek** [comment]
thanks, I'll look into it!
