### ISSUE TITLE
deprecate Class#subclasses from jruby/core_ext.rb

### ISSUE THREAD

**Issue by kares** [jruby/jruby#4760]
as an outcome to eventually remove the *core_ext/class.rb* extension
[(which colides with ActiveSupport's own `subclasses` whenever *jruby/core_ext* is loaded)](https://github.com/jruby/jruby/issues/4741)

JRuby should deprecate the method and maybe provide an alternative `JRuby.subclasses_for(klass)`

... so that we can eventually remove it completely at some point later

**Comment by headius** [comment]
I always wished subclasses would get added as a standard Class method rather than everyone relying on Rails's patch.
