### ISSUE TITLE
JRuby hangs when one line is super long in require

### ISSUE THREAD

**Issue by cjyclaire** [jruby/jruby#4778]
Background, [`aws-sdk-ruby`](https://github.com/aws/aws-sdk-ruby) travis jruby suit (version > 9.1.5.0) starts hanging and ends up in being killed by travis, and I cannot reproduce this at my local mac sierra environment. This can be reproduced at travis docker (ubuntu trusty), and I have already merged a [PR](https://github.com/aws/aws-sdk-ruby/pull/1597) that fixes this.

The issue is when requiring a file that has a super long line (> 2048), jruby ubuntu distribution hangs with no output.

### Environment

Travis [docker](https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally)
Error [log](https://travis-ci.org/aws/aws-sdk-ruby/jobs/248527729) with installation commands.

the install command is simply:
```
export PURE_RUBY=1
rvm use jruby-9.1.5.0 --install --binary --fuzzy
```

### Expected Behavior

works fine

### Actual Behavior

no error trace and hangs until the process is being killed

example error log from travis: https://travis-ci.org/aws/aws-sdk-ruby/jobs/248527729

Any advice would be appreciated.

**Comment by headius** [comment]
How peculiar! I assume you can trigger this locally. Do so and get a thread dump from the JVM (Ctrl+\ on unix terminal, Ctrl+Brk on Windows, jstack command) and provide it here.

I suspect this is getting stuck in the regular expression we use to look for encoding, frozen string, and other pragmas in comments at the top of the file. The thread dump will tell us for sure.

**Comment by enebo** [comment]
If it is from magic comment parsing then I suggest trying on master of jruby-9.1 branch: https://github.com/jruby/jruby/issues/4728 ... It might be fixed.

**Comment by cjyclaire** [comment]
Ah that's exactly it, glad to know it's taken care of, thanks!
