### ISSUE TITLE
yaml/store has a hack until we get an updated psych.

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#4779]
Offshoot of #4770.  I patched around the problem of pstore using ASCII-8BIT as an encoding by adding the same method to yaml/store which picks UTF-8 as the encoding.

**Comment by headius** [comment]
Link to #4784.

**Comment by headius** [comment]
This will fix itself when we update to Psych 3.0.0.

**Comment by headius** [comment]
Psych 3.0.2 will ship with 9.2.
