### ISSUE TITLE
conda-forge package for jruby

### ISSUE THREAD

**Issue by abhi18av** [jruby/jruby#4794]
Hi guys,

I've been working on the [`conda-forge`](https://conda-forge.org/) package for `jruby` in this [PR](https://github.com/conda-forge/staged-recipes/pull/4022) 

I'm running into issues, could you help me get jruby into the conda management space ?

**Comment by headius** [comment]
@abhi18av That's great! Sorry nobody jumped on this yet but I'll have a look at the PR.

**Comment by headius** [comment]
@abhi18av Well what you have looks correct, at least as far as JRuby goes. I'm not familiar with conda-forge...what do you need help with?

**Comment by abhi18av** [comment]
@headius I'm glad that it's not being overlooked now.

I'm almost done with the PR and all I need is to implement some bash and batch script to put the binary in a proper location.

Thanks for not letting this bit-rot +1

**Comment by headius** [comment]
@abhi18av Ok, so I guess there's nothing we need to do for this bug? If you run into any issues you think we need to fix on the JRuby side, let us know!

**Comment by abhi18av** [comment]
Hmm, sure. 

I'd keep you posted in this issue if I run into bugs etc. I really do think that conda and jruby would play a major role in Data Science
