### ISSUE TITLE
SSL issues when building JRuby on Java 9

### ISSUE THREAD

**Issue by p0deje** [jruby/jruby#4799]
### Environment

* jruby/jruby cloned at c911af4b28
* java 9 installed with [homebrew-cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/java.rb)
* macOS 10.12.6

### Expected Behavior

Building complete JRuby jar succeeds.

### Actual Behavior

Building complete JRuby jar on Oracle JDK 8 succeeds, but fails on Oracle JDK 9. The output refers to SSL issues like this:

```
Caused by: org.jruby.embed.EvalFailedException: (OpenSSL::X509::StoreError) setting default path failed: No password supplied for PKCS#12 KeyStore.
```

Full compile log is available at [gist](https://gist.github.com/p0deje/25555c07bb6c23d0246883f71c66ce1b).

### Notes

My first thought was that it's my environment issue. However, when I downgraded Java to 1.8.0_144, JRuby was built successfully, which makes me think it might be a different problem.

Mentioning #4111 as a main issue to track.

**Comment by headius** [comment]
Ah, I have not tried building jruby-complete on 9. I made changes for the main build to work on 9, but this doesn't appear to be the same issue. I have seen SSL problems *running* on 9, but not during the base build.

We'll have to look into this for 9.2.

**Comment by p0deje** [comment]
Please, let me know if I can help anyhow (provide more details, hop on IRC).

**Comment by headius** [comment]
#4805

**Comment by p0deje** [comment]
Thank you!

I confirm it builds perfectly on JDK9 now.
