### ISSUE TITLE
"gem install bundler" times out instead of installing normally

### ISSUE THREAD

**Issue by zebralight** [jruby/jruby#4801]
### Environment

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
* Operating system and platform (e.g. `uname -a`)
JRuby version 9.1.5.0 and 9.1.13.0
Linux 4.4.0-43-Microsoft

Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables
trying to install bundler

### Expected Behavior

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.
* Provide an executable Ruby script or a link to an example repository.
I'm expecting executing the command 'gem install bundler' while setting my current active ruby version via chruby to jruby v. 9.1.5.0 or v. 9.1.13.0 would result in the bundler gem being installed the way they install on my non jruby ruby versions.

### Actual Behavior

* Describe or show the actual behavior.
* Provide text or screen capture showing the behavior.

I get the following error message after over ten minutes of waiting: 
```
ERROR: Could not find a valid gem 'bundler' (>=0), here is why:
Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)
```
I had tried to run `gem update --system` but that results in a time out message as well.  I'm currently on gem version 2.6.13.
Any help would be much appreciated.

**Comment by headius** [comment]
So there's a couple things that immediately come to mind:

* RubyGems.org may have simply had some down time. It appears to be working ok for me locally (macos) with JRuby master.
* [SSL draining entropy](https://github.com/jruby/jruby/wiki/FAQs#why-is-jruby-so-slow-to-install-why-does-jruby-take-so-long-to-make-secure-connections), especially on VMs
* Some local env issue routing the connection incorrectly.

Are you still having this problem?

**Comment by headius** [comment]
No follow-up for potentially transient issue, please reopen if you're still having trouble.
