### ISSUE TITLE
Rework global variables, caching to eliminate race conditions

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4808]
This issue spawned from discoveries in #4797, where @eregon discovered that various races in our global variable subsystem seem to be causing us to cache invalid values.

There are numerous races, including but not limited to:

* GlobalVariables uses a CHM but manually performs multi-step read/write operations that would race with other threads.
* UndefinedVariable modifies the GlobalVariable it was attached to, updating it with a different accessor. This makes caching the accessor impossible.
* The traces active for each global variable are managed in an unsynchronized ArrayList, which additionally can be modified from outside the subsystem.

There are likely others. The main problems lie in the fact that this part of JRuby is some of the oldest code, many files only bearing the copyright of the first committer to JRuby. None of this code was built for concurrency, and the many levels of abstraction and mutation make a simple fix impossible.

This bug will track a rework of the global variable subsystem for JRuby 9.2, which will eliminate some of the unnecessary abstraction, use appropriate thread-safe structures and synchronization for modification, and properly enable safe caching of values.

**Comment by sumitmah** [comment]
I remember discussing similar stuff mruby with Matz in Rubyconf.

**Comment by headius** [comment]
We did various amounts of work to improve globals during the 9.1 cycle, but I have not evaluated how well the current implementation deals with globals. The plumbing is still a bit messy and I'm sure there are remaining races, plus we have never really reenabled global optimization in indy the way I'd like.

Bumping to post 9.2 for additional work.

**Comment by headius** [comment]
See #5525 for another example of problems with this code. It needs to be reworked from the ground up.

**Comment by headius** [comment]
This is largely resolved by #5536 but latest additions there appear to be hanging some suites. I also need to benchmark "bad" cases like heavily-modified globals to ensure we're no worse than the existing logic. Bumped to 9.2.9.

**Comment by headius** [comment]
Moved to 9.4 as part of larger perf work that will happen there.

**Comment by headius** [comment]
This is now happening in #8003.
