### ISSUE TITLE
JRuby 9.2.0.0-SNAPSHOT does not return result of `rake` via `system`

### ISSUE THREAD

**Issue by koic** [jruby/jruby#4809]
### Environment

* jruby 9.2.0.0-SNAPSHOT (2.4.1) 2017-09-07 b6a4df9 OpenJDK 64-Bit Server VM 24.121-b00 on 1.7.0_121-b00 +jit [linux-x86_64]
* Linux rails-dev-box 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

### Expected Behavior

This is behavior of JRuby 9.1.13.0 and MRI 2.4.2.

```console
% rvm use jruby-9.1.13.0
Using /home/vagrant/.rvm/gems/jruby-9.1.13.0
% rake --version
rake, version 12.1.0
% ruby -e 'system("rake --version")'
rake, version 12.1.0
```

### Actual Behavior

This is behavior of JRuby 9.2.0.0-SNAPSHOT.

```console
% rvm use jruby-head
Using /home/vagrant/.rvm/gems/jruby-head
% rake --version
rake, version 12.1.0
% ruby -e 'system("rake --version")' # Do not return `rake` version
```

JRuby 9.2.0.0-SNAPSHOT does not return result of `rake --version` via `system` method. The same phenomenon will occur even if `rake --version` is replaced with `bundle --version`.

I noticed this issue is occurring in Travis CI of bbatsov/rubocop repository.
https://travis-ci.org/bbatsov/rubocop/jobs/285144081#L712-L714

**Comment by headius** [comment]
Thanks for the report! This is surprising, but I believe I saw another bug with the same problem.

I am unable to reproduce so far on this macOS system:

```
$ ruby -v -e 'system("rake --version")'
jruby 9.2.0.0-SNAPSHOT (2.4.1) 2018-03-22 b4b496a Java HotSpot(TM) 64-Bit Server VM 25.161-b12 on 1.8.0_161-b12 +jit [darwin-x86_64]
rake, version 10.4.2
```

Will investigate on other platforms.

**Comment by headius** [comment]
Sorry we didn't get to this until now...I had not even seen it yet!

**Comment by headius** [comment]
I have reproduced it on Ubuntu. Investigating!

**Comment by headius** [comment]
Fixed! A refactoring done in August accidentally removed a PATH lookup step in process launching.

I am very surprised this did not trigger any other failures in our CI. Perhaps you can make a spec for https://github.com/ruby/spec so we never regress again?

**Comment by koic** [comment]
Thanks for the fixes and advice! I'm interested in https://github.com/ruby/spec and I'd like to try it later.
