### ISSUE TITLE
Psych yaml parser can not parse uppercase ÄÖÜ but äöü can parse 

### ISSUE THREAD

**Issue by spider-network** [jruby/jruby#483]
**My Env**

```
java -version
java version "1.7.0_09"
OpenJDK Runtime Environment (IcedTea7 2.3.3) (7u9-2.3.3-0ubuntu1~12.04.1)
OpenJDK 64-Bit Server VM (build 23.2-b09, mixed mode)
```

```
ruby -v
jruby 1.7.1 (1.9.3p327) 2012-12-03 30a153b on OpenJDK 64-Bit Server VM 1.7.0_09-b30 [linux-amd64]
```

With jruby 1.7.2 it does also not work, bit it works with the normal MRI ;-(
## How to reproduce the bug

**test.yml**

```
de:
  test: "Ä"
```

**test.rb**

``` ruby
require 'yaml'

YAML.parse(open("test.yml").read)

puts "Done"
```

**Error**

```
ruby test.rb
Psych::SyntaxError: (<unknown>): 'reader' unacceptable character '?' (0x84) special characters are not allowed
in "'reader'", position 14 at line 0 column 0
         parse at org/jruby/ext/psych/PsychParser.java:225
  parse_stream at /home/vagrant/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/psych.rb:205
         parse at /home/vagrant/.rvm/rubies/jruby-1.7.2/lib/ruby/1.9/psych.rb:153
        (root) at test.rb:3
```

Someone knows a workaround?

**Comment by pvmeerbe** [comment]
I encountered the same issue. I'm sending a YAML dump with an Ü  from MRI ruby v2.2.3  to a torquebox v3.1.2 with  jruby v1.7.8 via an API call (java version is 1.8.0_91-b14) .

Upgrading to torquebox v3.2.0 with jruby v9.1.5.0 solved the issue


Locale info : 
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_BE.UTF-8
LC_TIME=de_BE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_BE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_BE.UTF-8
LC_NAME=de_BE.UTF-8
LC_ADDRESS=de_BE.UTF-8
LC_TELEPHONE=de_BE.UTF-8
LC_MEASUREMENT=de_BE.UTF-8
LC_IDENTIFICATION=de_BE.UTF-8
LC_ALL=
