### ISSUE TITLE
jitescript jar clashes with bundled jitescript classes in jruby-complete jar

### ISSUE THREAD

**Issue by mpe85** [jruby/jruby#4831]
In our project we have jitescript-0.4.1.jar on the classpath because another 3rd party library has a dependency to it.
But this clashes with jitescript bundled with the jruby-complete.jar.
I'm new to jruby, so I don't know if this can be changed easily.
The main problem is that the bundled jitescript classes are not the original ones, because they include ASM artifacts which is bundled in the jruby jar (org.jruby.org.objectweb.asm) instead of the original ASM artifacts (org.objectweb.asm).
Maybe the bundled jitescript classes can also be moved to the package org.jruby, this would avoid the clash.
This issue should apply to all 9.x versions of jruby.

**Comment by mkristian** [comment]
right I see the problem: we repackaged the org.objectweb.asm.* but now it clashed with me.qmx.jitescript.* being on the classpath twice.

to repackage all the 3rd party jars would be the right thing as it easily can conflict in a similar manner with gems and their bundled jars. and for the OSGi it is also better to avoid non org.jruby classes altogether (#3821)

**Comment by headius** [comment]
I'll add jitescript to shade.
