### ISSUE TITLE
S3 missing jruby-src-9.1.14.0.zip

### ISSUE THREAD

**Issue by havenwood** [jruby/jruby#4848]
The other 9.1.14.0 src and bin gz/zip files are present on S3, but the src zip seems to be missing: https://s3.amazonaws.com/jruby.org/downloads/9.1.14.0/jruby-src-9.1.14.0.zip

**Comment by headius** [comment]
I pointed out the maven locations for source on IRC. @havenwood said this S3 URL was used by a script of to comb metadata for new JRuby versions, and it stumbled over this missing file. I recommended moving that script to the preferred Maven location.

We still should get this zip uploaded. Keep S3 functional as long as we can.

**Comment by havenwood** [comment]
The file now exists. Thanks!
