### ISSUE TITLE
Opaque `SystemCallError` in Conjunction with `Puma::ConnectionError: Socket timeout writing data`

### ISSUE THREAD

**Issue by aryeh-looker** [jruby/jruby#4856]
Thanks you kindly for taking the time to consider this issue. Originally I opened this issue in the Puma repository and am opening here upon suggestion from @nateberkopec (https://github.com/puma/puma/issues/1460). 

### Expected Behavior

Some useful message about why a socket is non-writable or data are successfully written to the socket.

### Actual Behavior

An opaque `SystemCallError: Unknown error` is raised.

### Other details

Here is a stack trace. We are attempting to stream some data to a client over HTTP.

`SystemCallError` is raised

```
SystemCallError: Unknown error (SystemCallError) - No message available
  from org/jruby/RubyIO.java:1440:in `write'
  from org/jruby/RubyIO.java:1411:in `write'
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/minissl.rb:65:in `write'
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/server.rb:852:in `fast_write'
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/server.rb:671:in `block in handle_request'
  from /gems/rack-1.5.4/lib/rack/deflater.rb:88:in `write'
  from org/jruby/ext/zlib/JZlibRubyGzipWriter.java:374:in `write'
  from /gems/rack-1.5.4/lib/rack/deflater.rb:78:in `block in each'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:405:in `block in <<'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:378:in `schedule'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:405:in `<<'
... application code here

Puma::ConnectionError: Socket timeout writing data
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/server.rb:860:in `fast_write'
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/server.rb:671:in `block in handle_request'
  from /gems/rack-1.5.4/lib/rack/deflater.rb:88:in `write'
  from org/jruby/ext/zlib/JZlibRubyGzipWriter.java:374:in `write'
  from /gems/rack-1.5.4/lib/rack/deflater.rb:78:in `block in each'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:405:in `block in <<'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:378:in `schedule'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:405:in `<<'
... application code here
```

### System configuration

**Ruby version**: JRuby `9.1.8.0`
**Rails version**: n/a — Sinatra `1.4.3`
**Puma version**: `2.12.3`
**Rack**: `1.5.4`
**OS**: Linux (apologies for the ambiguity, not known yet)

**Comment by headius** [comment]
Ok, first thing I need you to do is try the most recent JRuby version, 9.1.14.0. The error messages related to IO failures have had some improvements over the past year, which might have fixed this error to raise something more appropriate.

**Comment by headius** [comment]
No follow-up and likely fixed; closing as invalid.
