### ISSUE TITLE
Ruby 2.5 Gemification

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4875]
This bug will track the process of using the new gemiified stdlib gems for Ruby 2.5 (which should be released as JRuby 9.3 or JRuby 10).

The current Appveyor builds show the gems being installed. https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby

Many of the libraries in question either do not have (never had) JRuby equivalents (sdbm etc) or are unmodified (or barely modified) pure-Ruby libraries. Others like `openssl` will need to have a -java equivalent so users don't have to isolate those dependencies.

**Comment by headius** [comment]
#4876

**Comment by olleolleolle** [comment]
Here are the gems listed, at the end of the build output (as of today):

## Default Gems

|  Gem         | Version      |
|  ---         | ---          |
|  bigdecimal  |        1.3.2 |
|  bundler     |       1.16.0 |
|  cmath       |        0.0.1 |
|  csv         |        0.1.0 |
|  date        |        0.0.1 |
|  dbm         |  1.0.0.beta1 |
|  digest      |        0.1.0 |
|  etc         |        0.2.1 |
|  fcntl       |        0.0.1 |
|  fiddle      |  1.0.0.beta2 |
|  fileutils   |        0.7.2 |
|  gdbm        |  2.0.0.beta1 |
|  io-console  |        0.4.6 |
|  ipaddr      |        1.2.0 |
|  json        |        2.1.0 |
|  openssl     |  2.1.0.beta2 |
|  psych       |        3.0.0 |
|  rdoc        |  6.0.0.beta4 |
|  scanf       |        0.0.1 |
|  sdbm        |        0.0.1 |
|  stringio    |        0.0.1 |
|  strscan     |        0.0.1 |
|  webrick     |  1.4.0.beta1 |
|  zlib        |        0.1.0 |

## Bundled Gems

| Gem          | Version |
| ---          | ---     |
| did_you_mean |  1.1.2  |
| minitest     | 5.10.3  |
| net-telnet   |  0.1.1  |
| power_assert |  1.1.1  |
| rake         |  12.3.0 |
| test-unit    |  3.2.6  |
| xmlrpc       | 0.3.0   |

**Comment by headius** [comment]
Thanks again! The pure-Ruby gems should be easy to get gemified. The ones that have exts, we'll either defer on gemifying or have to get our exts released under the MRI name.

**Comment by headius** [comment]
We match the CRuby pure-Ruby gems (bundler, cmath, csv, fileutils, ipaddr, json, rdoc, scanf, webrick) as of now, as well as io-console (using our contributed FFI code, https://github.com/ruby/io-console/pull/22), json and psych (using our ext for years).

The remaining missing gems are summarized below:

* bigdecimal - we still have our own version and it is not integrated into the gem in any way. The gem maintainer has expressed some reluctance to incorporating JRuby code in the past.
* date - we have our own impl for 90% of this and it has not been incorporated into the gem.
* dbm, gdbm, and sdbm have never been supported and likely never will.
* digest - we have our own impl and it has not been incorporated into the gem.
* etc - we have our own impl and it has not been incorporated into the gem. This could potentially be replaced by Ruby FFI code and made easier to add to the gem.
* fcntl - we have our own impl and it has not been incorporated into the gem. This could also be replaced by FFI code.
* fiddle - we have a pure-Ruby impl based on FFI that has not been incorporated into the gem. In the past we had talked with @chrisseaton about unifying on a shared fiddle impl that uses FFI, or else a shared FFI based on fiddle, but that has not happened.
* openssl - we release this in gem form but our version of the library has not been incoporated into the standard gem.
* stringio - we have our own impl and it has not been incorporated into the gem.
* strscan - we have our own impl and it has not been incorporated into the gem (https://github.com/ruby/strscan/issues/15).
* zlib - we have our own impl and it has not been incorporated into the gem.

**Comment by headius** [comment]
Marking this resolved since we match Ruby (2.6) for as many gems as possible. The next release after 9.3 will incorporate additional pure-Ruby gems, and I will open a separate issue about the native libraries that are still shipped only with JRuby.
