### ISSUE TITLE
Dead Exception in RealClassGenerator

### ISSUE THREAD

**Issue by nglorioso** [jruby/jruby#4880]
https://github.com/jruby/jruby/blob/355f943da6dab62fc7c3f31aceaf92f8640081f9/core/src/main/java/org/jruby/java/codegen/RealClassGenerator.java#L147

This line creates an exception, but doesn't throw it. If thrown, a number of CI tests fail: https://travis-ci.org/jruby/jruby/builds/305072247

This condition/exception should be removed if it's not needed, or the exception should be thrown and the relevant tests fixed.

**Comment by headius** [comment]
The fact that so many tests fail tells me this condition is no longer valid, but I'll take a deeper look.

**Comment by headius** [comment]
The condition is backwards. I'll fix in a moment.
