### ISSUE TITLE
Inconsistent TimeWithZone equality checks

### ISSUE THREAD

**Issue by NC-phuh** [jruby/jruby#4892]
### Environment

* jruby-9.1.15.0
* rails 4

* 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

### Expected Behavior
The following occurs in MRI ruby:
```
> DateTime.now.in_time_zone('Eastern Time (US & Canada)') == DateTime.now.utc
=> true
```

### Actual Behavior
In Jruby-9.1.15.0:
```
> DateTime.now.in_time_zone('Eastern Time (US & Canada)') == DateTime.now.utc
=> false
```

**Comment by headius** [comment]
I'm not sure where this `in_time_zone` method comes from. Can you provide a standalone script that we can run?

**Comment by NC-phuh** [comment]
@headius It's from rails:

Here's a snippet that should run
```
gem 'rails', '4.2.8'
require 'rails'

puts "#{DateTime.now.in_time_zone('Eastern Time (US & Canada)') == DateTime.now.utc} should be true"
```

**Comment by headius** [comment]
Confirmed on jruby-9.1 branch as well.

**Comment by headius** [comment]
Still failing on current JRuby master (9.2).

**Comment by kares** [comment]
let's have it - this is slightly :sneezing_face: since one should never expect a time clock to return the same
... just because its on the same line, teste the following script: 
```ruby
require 'date'
require 'active_support/all'

puts ActiveSupport::VERSION::STRING

now = DateTime.now
puts inz = now.in_time_zone('Eastern Time (US & Canada)')
puts utc = now.utc

puts inz == utc
```
**9.2** (master) output: 
```
4.2.10
2018-05-24 05:24:43 -0400
2018-05-24T09:24:43+00:00
true
```
same with 9.1.16.0 + AS 5.1 : 
```
5.1.6
2018-05-24 05:27:39 -0400
2018-05-24 09:27:39 UTC
true
```
