### ISSUE TITLE
NameError: cannot load Java class jline.console.ConsoleReader

### ISSUE THREAD

**Issue by khirod12** [jruby/jruby#4893]
jruby-jars 9.1.15.0 is having compatible issue with highline-1.7.10 . It throws below error. where as it jruby-jars 9.1.14.0 working fine.

NameError: cannot load Java class jline.console.ConsoleReader
                      for_name at org/jruby/javasupport/JavaClass.java:286
               get_proxy_class at org/jruby/javasupport/JavaUtilities.java:34
          block in java_import at uri:classloader:/jruby/java/core_ext/object.rb:49
                           map at org/jruby/RubyArray.java:2487
                   java_import at uri:classloader:/jruby/java/core_ext/object.rb:36
  initialize_system_extensions at uri:classloader:/gems/highline-1.7.10/lib/highline/system_extensions.rb:21
                    initialize at uri:classloader:/gems/highline-1.7.10/lib/highline.rb:201

**Comment by petrvalkoun-gooddata** [comment]
https://github.com/jruby/jruby/issues/4889
https://github.com/JEG2/highline/issues/227

**Comment by khirod12** [comment]
Thank you  , highline 2.0 is working fine.
