### ISSUE TITLE
RubyHash doesn't implement the contract of java.util.Map correctly

### ISSUE THREAD

**Issue by robertpanzer** [jruby/jruby#4916]
### Environment

JRuby 9.1.13.0
OS X

(The sources show though that the same behavior should observable with the current master)

### Expected Behavior

The Javadoc of `java.util.Map.put()` defines this:

> Returns:
> the previous value associated with key, or null if there was no mapping for key. (A null return can also indicate that the map previously associated null with key, if the implementation supports null values.)

Therefore I would expect these 2 tests to pass:
```java
  @Test
  public void test1() {
    Ruby ruby = Ruby.newInstance();
    IRubyObject hash = ruby.evalScriptlet("{ \"Jane Doe\" => 10, \"Jim Doe\" => 6 }");
    assertThat(hash, instanceOf(RubyHash.class));
    RubyHash rubyHash = (RubyHash) hash;
    // Should return previous value 10, but returns the new value 42
    assertThat(rubyHash.put("Jane Doe", 42), is((Object) 10)); 
  }

  @Test
  public void test2() {
    Ruby ruby = Ruby.newInstance();
    IRubyObject hash = ruby.evalScriptlet("{ \"Jane Doe\" => 10, \"Jim Doe\" => 6 }");
    assertThat(hash, instanceOf(RubyHash.class));
    RubyHash rubyHash = (RubyHash) hash;
    // Should return null because the key wasn't present before, but returns the new value 42
    assertThat(rubyHash.put("Robert Panzer", 42), nullValue());
  }
```

### Actual Behavior
The tests fail, because `RubyHash.put()` returns the value passed to this call:
https://github.com/jruby/jruby/blob/7bd10a61c70d7ab271f5a1403b64ef37eaaf036a/core/src/main/java/org/jruby/RubyHash.java#L2127-L2131

**Comment by headius** [comment]
Ah, very good. A simple fix for once!

**Comment by headius** [comment]
Ok, not totally simple, since internalPut and downstream methods do not return any existing value. But I'll have a patch shortly.

**Comment by headius** [comment]
Fix and tests (adapted from yours) pushed in db06305.

**Comment by robertpanzer** [comment]
Thanks! 🎉
