### ISSUE TITLE
No stdout with drip on jruby-9.1.15.0

### ISSUE THREAD

**Issue by marvinTD** [jruby/jruby#4942]
```
jruby -e 'puts "foobar"'
```

First run when there is no drip jvm started, I see the output. Once it starts using that idle jvm, there's no output. Similar experience when running rspec commands for a pretty barebones rails project.

I'm running rbenv to manage my versions. Additional details below

```
jruby --version
jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 OpenJDK 64-Bit Server VM 24.95-b01 on 1.7.0_95-b00 +jit [linux-x86_64]
echo $JRUBY_OPTS
-J-Xmx2g
```
Also had the same issue with --dev on. More stuff:
```
env | grep drip                                                                                                                                                        
JAVACMD=/home/marvin/bin/drip
env | grep DRIP                                                                                                                                                          
DRIP_INIT=
DRIP_INIT_CLASS=org.jruby.main.DripMain
uname -a
Linux machine 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Edit:
Also tested with openjdk 1.8 and experienced the same issue. Obtained my version of drip using:
curl -L https://raw.githubusercontent.com/ninjudd/drip/master/bin/drip > ~/bin/drip
Looks like it's 0.2.5

**Comment by marvinTD** [comment]
dripmain.rb
```
require_relative 'config/application'
require 'rubygems'
require 'bundler'

Bundler.require(:development, :test)
```

**Comment by headius** [comment]
Likely broken by work to make JDK 9 run better. Specifically, the logic that defaults to using real native stdio rather than JDK stdio.
