### ISSUE TITLE
Hash#rehash does not properly rehash

### ISSUE THREAD

**Issue by ChrisBr** [jruby/jruby#4958]
### Environment
* jruby 9.3.0.0-SNAPSHOT (2.5.0) 2018-01-08 4b5cea6 OpenJDK 64-Bit Server VM 25.151-b12 on 1.8.0_151-b12 +jit [linux-x86_64]

### Expected Behavior
When rehashing a hash with equal objects in it, they don't get removed.
```
a = [1,2]
b = [1]
h = {}
h[a] = true
h[b] = true
b << 2
puts h.rehash # { [1,2]: true, [1,2]: true } 
```

I already looked into the issue and it seems that the problem is that Hash#rehash does not handle collisions properly. When two objects have the same hash / bucket number, they get inserted even if they are the same (see example).

### Actual Behavior
Hash#rehash should remove the duplicate entries.

**Comment by headius** [comment]
I looked at your impl, and it was fine except for a couple things:

* entry.equals checks equality of values too, which we don't want
* we need to remove not-added entries from the insertion-order chain; if an entry is not kept, prevAdded and nextAdded entries need to be fixed up
* we need to check the whole chain of entries, not just the first one

I almost had a fix but I'm pulled away to finish something else.
