### ISSUE TITLE
An object with defined singleton method and no external references is not GC from memory

### ISSUE THREAD

**Issue by brometeo** [jruby/jruby#4985]
### Environment

* JRuby version: 9.1.15.0
* Java version: OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1-b12). 64 -Bit server VM
* flags: --enable=frozen-string-literal -J-Djruby.reify.classes=true -J-XX:+UseCompressedOops -J-XX:+UseCMSInitiatingOccupancyOnly -J-XX:CMSInitiatingOccupancyFraction=50 -X-C -J-Xmx300m -J-XX:+CMSClassUnloadingEnabled -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1
* Operating system and platform: Linux bree 4.14.0-2-amd64 #1 SMP Debian 4.14.7-1 (2017-12-22) x86_64 GNU/Linux

Here you have potentially offending code:
```
require 'pry'
  
class Foo
  def define_bar_method(&block)
    define_singleton_method(:bar, &block)
  end

  def remove_bar_method
    singleton_class.class_eval do
      remove_method :bar
    end
  end
end

foo = Foo.new
foo.define_bar_method {2 + 2}
foo.bar
foo.remove_bar_method
foo = nil
binding.pry
```

### Expected Behavior

An object with a defined singleton method should be garbage collected if there are no external references pointing it.

### Actual Behavior

When referenced by a Binding object from a defined singleton method, foo object is not collected by GC and it seems it should be. I try to remove singleton method before GC.

On pry stop, I try GC from visualvm. Foo object is still there if I run a memory sampling from visualvm. More GC don't change that situation.

**Comment by headius** [comment]
Same issue as #4968 most likely.

**Comment by headius** [comment]
Workaround is to use those objects/variables in a subscope. For example:

```ruby
tap {
  foo = Foo.new
  foo.define_bar_method {2 + 2}
  foo.bar
  foo.remove_bar_method
}
binding.pry
```

Not ideal I know.
