### ISSUE TITLE
How to connect to mysql? 

### ISSUE THREAD

**Issue by dersar00** [jruby/jruby#5033]
Hello!
I'm have a trouble with finding info about connecting to mysql database if I'm using jruby.
How I can do it? I need to connect mysql to one of my .rb file.

**Comment by mprins** [comment]
https://github.com/jruby/jruby/wiki/ActiveRecord-JDBC  not enough?

**Comment by kares** [comment]
you either setup the `gem 'activerecord-jdbcmysql-adapter'` n your *Gemfile* (`platform: :jruby`) for Rails
... or simply use another library such as Sequel which has JRuby support for almost all of its DB support
than obviously you could use the 'raw' Java standard JDBC with MySQL's driver (which the above all are using behind the scene). your question is too generic and maybe would have been a better suit for SO ...
