### ISSUE TITLE
IO.copy_stream replaces read chunk even if it's duplicated

### ISSUE THREAD

**Issue by janko-m** [jruby/jruby#5048]
### Environment

```
$ jruby -v
jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 Java HotSpot(TM) 64-Bit Server VM 25.40-b25 on 1.8.0_40-b27 +jit [darwin-x86_64]
$ uname -a
Darwin Jankos-MacBook-Pro-2.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

### Expected Behavior

I'm using a trick in [HTTP.rb](https://github.com/httprb/http/blob/9b40c143c68f3f94cde90ce3c9da3ec4123e1bbf/lib/http/request/body.rb#L37) where I utilize `IO.copy_stream` to yield chunks of data into a block. However, the tests for this behaviour are failing on JRuby.

I managed to isolate the problem in this script:

```rb
require "stringio"

class ProcIO
  def initialize(&block)
    @block = block
  end

  def write(data)
    @block.call(data)
    data.bytesize
  end
end

chunks = []

stringio = StringIO.new("a" * 16*1024 + "b" * 10*1024)
procio   = ProcIO.new { |data| chunks << data.dup }

IO.copy_stream(stringio, procio)

puts chunks
```

On MRI this prints `16*1024` characters `a` and `10*1024` characters `b`.

### Actual Behavior

On JRuby this script prints `3 x 8*1024` characters `b` and `1 x 2*1024` characters `b`. This totals to the correct number of characters, but they're all `b`. Since JRuby seems to use chunk size of 8KB (unlike MRI which uses 16KB), I expected the output to be `2 x 8*1024` characters `a`, `1 x 8*1024` characters `b` and `1 x 2*1024` characters `b`.

I tried printing each chunk as it's yielded:

```rb
procio   = ProcIO.new { |data| chunks << p(data.dup) }
```

And the chunks were in fact correct. So it seems that, even though I duplicated the string, JRuby still somehow overrode it when reading subsequent chunks. And in a strange way too, I would have expected to get 4x the last chunk (`2*1024` characters `b`), but instead JRuby kept the string length and still somehow replaced the content.

**Comment by headius** [comment]
I'm not at a terminal now, hit can you try this with a snapshot of 9.1.16? I did a bunch of work this cycle to improve copy_stream.

**Comment by janko-m** [comment]
I successfully build JRuby from `master` by running `./mvnw`, but when I try to run `bin/jruby bug.rb` I get

```
Error: Could not find or load main class org.jruby.Main
```

I tried doing `rbenv shell system` before, but it didn't work.

**Comment by headius** [comment]
Try downloading a nightly from the link http://jruby.org/download

**Comment by janko-m** [comment]
@headius Strange, I get the same error with the executable from the nightly link.

**Comment by headius** [comment]
Yeah really seems like an env issue. Try a clean shell, make sure no vars are redirecting commands somewhere they should not be. I'll have a look tomorrow too.

**Comment by janko-m** [comment]
@headius You're right, running from a clean shell worked 👍

And yes, the script now produces correct output on the 9.1.16.0 snapshot, which is great. Thank you very much! ❤️

**Comment by headius** [comment]
It seems likely this was the same issue as #4093. I wish you had filed first...that one was complicated to diagnose! 😆
