### ISSUE TITLE
String literal difference from MRI

### ISSUE THREAD

**Issue by bobjalex** [jruby/jruby#5052]
### Environment
Running on Windows 10
```
>jruby -v
jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 Java HotSpot(TM) 64-Bit Server VM 9.0.4+11 on 9.0.4+11 +jit [mswin32-x86_64]
>systeminfo
Host Name:                 BOB-ACER-SWIFT-
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.16299 N/A Build 16299
...
```

### Expected Behavior
```
>irb
irb(main):001:0> "#@"
=> "\#@"
```

### Actual Behavior
```
>jirb
irb(main):001:0> "#@"
=> "@"
```

**Comment by headius** [comment]
The "WARNING" are a Java 9 thing about us using reflection to crack open core JDK classes, and the stack trace is a known bug with readline on Windows that's fixed in 9.1.16.0, so I'll remove those from your description.

The actual string bug should have a fix shortly; I believe @enebo is on it.
