### ISSUE TITLE
Hard to explain breakage of build with no code change

### ISSUE THREAD

**Issue by rafaelfranca** [jruby/jruby#5059]
Two builds, with the same code have different results in JRuby builds

This one is failing: https://travis-ci.org/rack/rack/jobs/340783715
This one is passing: https://travis-ci.org/rack/rack/jobs/335916086

The diff between the two build is a change in the README.rdoc file https://github.com/rack/rack/compare/2a5f80d189c7...d1363a66ab21.

Since the build #1768 all other JRuby builds are having similar failures.

The kernel version, JVM version, JRuby version, Rubygems version and bundler version are the same in all the builds.

Any idea what would cause such strange failures.

**Comment by headius** [comment]
I believe you are in error. There is at least one difference between these two builds.

Passed:
```
$ gem --version
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
2.7.4
```

Failed:
```
$ gem --version
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
2.7.5
```

And in fact there's a bug we reported in RubyGems 2.7.5 that prevents it from activating updated default gems like minitest, test-unit, rake, and so on: https://github.com/rubygems/rubygems/issues/2188

For this reason we did not ship the latest RubyGems in JRuby 9.1.16.0, but I believe RVM attempts to install the latest regardless. I assume there's a way you can turn that off.

Please confirm that reverting to RubyGems prior to 2.7.5 fixes your issues.

**Comment by enebo** [comment]
An obvious one (so I doubt it is this) is whether you have no .lock file and Gemfile with open dependencies.  Some gem being different could explain this.

As an aside we would love to see 9.0.4.0 be replaced with 9.1.16.0.  We have not supported 9.0.x for more than a year.

**Comment by headius** [comment]
FWIW the RubyGems issue may eventually come back around to being a JRuby bug, but  for now I think the ball's in their court. You may be able to help them investigate, though.

**Comment by rafaelfranca** [comment]
It is passing locally with 9.1.15 but failing on travis ci with some kind of deadlock. Any recommendations how to debug?

**Comment by headius** [comment]
@rafaelfranca Hmm I'm not sure. Best way to investigate would be to reproduce that environment locally and try to get a thread dump, or use the Travis docker image to do the same on a local environment. You may be able to figure out what's freezing by adding `-v` or similar to the test run so we can see where it hangs.

I'm going to call this fixed, but I'm happy to assist figuring out the deadlock.
