### ISSUE TITLE
Memory Leak issue in ScriptingContainer using SingleThreaded LocalContext scope

### ISSUE THREAD

**Issue by adpande** [jruby/jruby#5077]
### Environment

Provide at least:
* Jruby version 9.1.12.0
* Linux 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux: Contos 7

Other relevant info you may wish to add:
* Ruby is embeded in Java 8.
* None

### Expected Behavior

* Ruby should clean up the memory once the script execution is done.

### Actual Behavior

Ruby is creating too many runtimes and failing with OOM error.

Code we use to create scripting container:
```java
ScriptingContainer container = new ScriptingContainer(LocalContextScope.SINGLETHREAD,LocalVariableBehavior.TRANSIENT,false);
```
We are also using a pool of scripting containers and use it.

Probably the issue #4367 again resurfaced.

Here are the MAT analysis of the problem:

![ruby-leak1](https://user-images.githubusercontent.com/128881/36931403-6fbd7368-1eda-11e8-9e2c-1e804b5667de.png)
![ruby-leak2](https://user-images.githubusercontent.com/128881/36931405-6fe9b19e-1eda-11e8-8f6c-f198ff1c6c62.png)
![ruby-leak3](https://user-images.githubusercontent.com/128881/36931406-7010bcb2-1eda-11e8-9cf7-91d7fc54f6eb.png)

**Comment by adpande** [comment]
#4367

**Comment by adpande** [comment]
This is a native memory leak. This may be similar to https://github.com/jruby/jruby/issues/1791

**Comment by headius** [comment]
Strange...the MAT report shows paths to root via SoftReference, so I would have expected these things to go away.

@adpande Does the problem exist on JRuby 9.1.16? If so, can you provide a heap dump we can use to investigate?

**Comment by adpande** [comment]
Hello @headius, Sorry for the delay. I will test and try to generate heap dump with v9.1.1.16. Thanks!

**Comment by headius** [comment]
@adpande Any luck?

**Comment by headius** [comment]
No respond, closing. If you still have an issue, please open a new bug, since a lot has changed in two years.
