### ISSUE TITLE
Error when installing 9.1.16.0 on Windows 10 (64 Bit)

### ISSUE THREAD

**Issue by bolandross** [jruby/jruby#5084]
Hey Folks,

when trying to install JRuby on my Windows machine, I'm getting an error message.

I am using JRE 9.0.4

Do you have an idea what might be the problem?

![message](https://user-images.githubusercontent.com/5481702/37253265-d342557e-252f-11e8-9d07-dcd267977f36.png)

**Comment by headius** [comment]
Can you provide the error log? This is some issue inside the installer we use (Install4J) but this isn't enough information.

**Comment by bolandross** [comment]
Yeah, I attached the logfile. It was produced by the **jruby_windows_x64_9_1_16_0.exe** file.
[install4jError11964220859875075325.log](https://github.com/jruby/jruby/files/1816680/install4jError11964220859875075325.log)

**Comment by headius** [comment]
Ok, I suspect this is a problem with install4j (perhaps just the version we used) incompatibility with Java 9.

JRuby is also a little iffy on Java 9 still (we're working on it) so you may want to run with Java 8 for now. Try that and let us know if it installs. We'll still get this fixed, but at least you'll be up and running.

Alternatively, just use Java 8 for the install by [passing flag to the installer](https://resources.ej-technologies.com/install4j/help/doc/#install4j.helptopics.installers.options) to make it use a Java 8 runtime. Then you can still run JRuby on 9 if you wish.

**Comment by headius** [comment]
I just discovered this in the Install4J change logs: https://www.ej-technologies.com/download/install4j/changelog.html

So apparently they just got a version out a couple months ago that works on Java 9.

**Comment by headius** [comment]
@enebo We will need to update Install4J to be able to install with Java 9.

**Comment by enebo** [comment]
I applied for OSS license for current version.  We shall see how that goes.  The version we have been using which we had an OSS license for was very old (it only applied for a single version of install4j).  That license came from codehaus itself so I am not sure how that all worked :|
