### ISSUE TITLE
IRB doesn't start on jRuby 9.1.16.0

### ISSUE THREAD

**Issue by raelik** [jruby/jruby#5104]
### Environment

* `jruby 9.1.16.0 (2.3.3) 2018-02-21 8f3f95a Java HotSpot(TM) 64-Bit Server VM 25.60-b23 on 1.8.0_60-b27 +indy +jit [darwin-x86_64]`
* `Darwin heretic 14.5.0 Darwin Kernel Version 14.5.0: Mon Aug 29 21:14:16 PDT 2016; root:xnu-2782.50.6~1/RELEASE_X86_64 x86_64` (Mac OS X Yosemite)
* Using jruby-mains 0.6.1 from https://oss.sonatype.org/content/repositories/releases/org/jruby/mains/jruby-mains/0.6.1/

### Behavior

Trying to run `irb` raises an exception: `java.lang.IncompatibleClassChangeError: Found class jline.Terminal, but interface was expected`, full stack trace is here: https://gist.github.com/raelik/f8e73b2ab46b46b3fcde231d4fc0cbdb

This error doesn't occur on 9.1.15.0 and prior.

**Comment by headius** [comment]
Are you certain you're not mixing environments? We addressed this issue during 9.1.16.0 cycle, but if you have 9.1.16.0 for whatever reason picking up 9.1.15.0's gems it might still happen.

**Comment by raelik** [comment]
I'm using the jruby-gradle-plugin to build an artifact jar containing jruby and all of my gems, and I blow it away and rebuild it from scratch.

**Comment by headius** [comment]
@mkristian Any idea why this would still be happening?

**Comment by raelik** [comment]
Just looking at the stack trace, the only way I can see this happening if somehow jline 1.x was somehow being loaded.  That's the last time that `jline.Terminal` was implemented as a class instead of an interface.

**Comment by raelik** [comment]
@headius That's exactly what's happening.  Here's a the result of running `jar -tvf | grep jline` on my jar built for  9.1.16.0:
```
     0 Wed Feb 21 10:21:44 CST 2018 META-INF/jruby.home/lib/ruby/stdlib/jline/
    11 Wed Feb 21 10:20:46 CST 2018 META-INF/jruby.home/lib/ruby/stdlib/jline/.jrubydir
     0 Wed Feb 21 10:21:44 CST 2018 META-INF/jruby.home/lib/ruby/stdlib/jline/jline/
    35 Wed Feb 21 10:20:46 CST 2018 META-INF/jruby.home/lib/ruby/stdlib/jline/jline/.jrubydir
     0 Wed Feb 21 10:21:44 CST 2018 META-INF/jruby.home/lib/ruby/stdlib/jline/jline/2.11/
    20 Wed Feb 21 10:20:46 CST 2018 META-INF/jruby.home/lib/ruby/stdlib/jline/jline/2.11/.jrubydir
208781 Wed Feb 21 10:20:46 CST 2018 META-INF/jruby.home/lib/ruby/stdlib/jline/jline/2.11/jline-2.11.jar
   288 Wed Feb 21 10:20:46 CST 2018 META-INF/jruby.home/lib/ruby/stdlib/jline/jline/maven-metadata-local.xml
     0 Thu Mar 22 14:09:52 CDT 2018 jars/jline/
     0 Thu Mar 22 14:09:52 CDT 2018 jars/jline/jline/
     0 Thu Mar 22 14:09:52 CDT 2018 jars/jline/jline/0.9.94/
 87325 Thu Mar 22 14:09:52 CDT 2018 jars/jline/jline/0.9.94/jline-0.9.94.jar
```

Here it is for 9.1.15.0:
```
     0 Thu Mar 22 14:32:42 CDT 2018 jars/jline/
     0 Thu Mar 22 14:32:42 CDT 2018 jars/jline/jline/
     0 Thu Mar 22 14:32:42 CDT 2018 jars/jline/jline/0.9.94/
 87325 Thu Mar 22 14:32:42 CDT 2018 jars/jline/jline/0.9.94/jline-0.9.94.jar
```

**Comment by raelik** [comment]
I tracked down the problem, not sure how to resolve it.  My project uses Apache Curator 2.x, which depends on ZooKeeper 3.4.8... which depends on jline 0.9.94.  Luckily, none of my code touches any parts of ZK that depend on jline (most likely command-line utilities).

**Comment by raelik** [comment]
Ok, I was able to fix this by excluding jline from my runtime configuration in my build.gradle. Nothing to see here, move along!

**Comment by mkristian** [comment]
great this got resolved. this exactly the reason we try to get rid of jline altogether in jruby.
