### ISSUE TITLE
Stop wrapping Java exceptions with LoadError

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5135]
In looking at #5115, I realized we are still wrapping Java exceptions that bubble through a `load` or `require` with a new `LoadError`. The only way to see the original exception is to pass `-d` to JRuby and capture stderr so you can see the actual exception's stack trace.

```
$ cat blah.rb
raise java.lang.NullPointerException.new

$ jruby -e 'require "./blah.rb"'
LoadError: load error: ./blah -- java.lang.NullPointerException: null
  require at org/jruby/RubyKernel.java:956
  require at /Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at -e:1
```

We need to do a better job reporting these exceptions, since they usually will indicate a load-time bug in some called library.

One option would be to set the `cause` of the LoadError to the Java exception, and make sure that exception dumping is outputting cause correctly. This should naturally then output the LoadError trace followed by the original Java exception trace.

After thinking about it for a while, I do not believe we can stop wrapping them since the typical pattern in Ruby is that `rescue LoadError` covers a multitude of sins (library loading, library IO, other system exceptions during load). Any current libraries that depend on this behavior will continue to work as before. However, the logged output of those LoadError will now make it more obvious there's a problem to be fixed in the library itself.

**Comment by kares** [comment]
+1 have been using the native exception Java cause wrapping in RaiseException in a few places already.
mostly out of JRuby itself as well - AR-JDBC, JOSSL. maybe designing some explicit API could be handy ...

**Comment by headius** [comment]
Well I can certainly add the cause, but it does not appear to be default behavior in CRuby to print the cause in the top-level exception printout. It's a start, but so far I am not seeing much default logging behavior associated with `Exception#cause`.

**Comment by kares** [comment]
how about just using the Java `initCause` and having a flag to "long" print cause traces or simply do it with 
`-Xexception.style=raw` ... just an idea. most users probably do not want to see Java traces by default ...

**Comment by kares** [comment]
(since `initCause` is used in external exts - it would allow traces to "switch" using the feature on as well)

**Comment by enebo** [comment]
@headius @kares So using cause may interfere with MRI future plans but I bet we could submit it since it sort of sucks to not know why something did not load.  As far as not wanting to see this...It is quite rare an ordinary user would see this in the case of a Java Exception being the cause.  Perhaps we can just display in that case.  I suspect 99% of the time it is an ext developer or us.  Most requires work or are a simple syntax error (which would be a Ruby exception not a Java one).

**Comment by headius** [comment]
Both CRuby and JRuby actually the actual exception for syntax errors and any regular Ruby errors that occur during load time. I'm not sure how to cause internal load errors in CRuby, so I can only test what happens when it can't find or load a file, which obviously leads to load errors.

I should be clear...I'd *like* to just get rid of the wrapper altogether. If the Ruby code loads, everything that happens after that should just raise as a normal error. But I'm worried about libraries that use LoadError as a catch all around JRuby extensions or Java library calls, as an indication to fall back to pure-Ruby or a different version of the library.

**Comment by headius** [comment]
We will leave this unfixed for now. LoadError *only* wraps Java exceptions, allowing others to bubble out properly. This aligns (in my opinion) with MRI testing runtime-level failures in loading a library as more LoadError.
