### ISSUE TITLE
New psych failures with 3.0.3 + updated tests.

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5142]
For #5098 I am about to release Psych 3.0.3 and use it in JRuby 9.1.17. However updating the tests (required because some older deprecated tests no longer load) exposes some failures. These may be regressions in the JRuby part of Psych, but they are more likely one of the following:

* fixes that were made to the C code in Psych but not the Java code
* minor behavioral differences between libyaml and SnakeYAML
* regressions in SnakeYAML

I will be tagging them for now.

**Comment by headius** [comment]
@enebo How concerned do you think we should be putting 9.1.17 out with these failures? I'm not sure how new they are; we have updated Psych a few times without updating tests, and had not seen these failures up until now.

**Comment by enebo** [comment]
@headius I guess it depends on how ominous the failures look.  Do they look like someone would be depending on behavior that changed?

**Comment by headius** [comment]
@enebo They didn't look too ominous to me, but I'm not sure what some of them are testing. I'll push the excludes shortly.

**Comment by headius** [comment]
Ok...so it looks like there's spec failures too. This probably needs to be addressed before we release with the new Psych/SnakeYAML.

I will push a pre gem and a branch to get a complete listing of failures.

**Comment by headius** [comment]
Excludes for MRI failures, should they be useful.
```diff
commit dbd70b4930477f4e6efba07a0a6a05f4765334bb
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Mon Apr 16 11:47:36 2018 -0500

    Tag off new Psych 3 failures.

diff --git a/test/mri/excludes/Psych/JSON/TestStream.rb b/test/mri/excludes/Psych/JSON/TestStream.rb
new file mode 100644
index 0000000000..a433613abc
--- /dev/null
+++ b/test/mri/excludes/Psych/JSON/TestStream.rb
@@ -0,0 +1,4 @@
+exclude :test_datetime, "new test or regression, #5142"
+exclude :test_hash, "new test or regression, #5142"
+exclude :test_list_to_json, "new test or regression, #5142"
+exclude :test_time, "new test or regression, #5142"
diff --git a/test/mri/excludes/Psych/TestCoder.rb b/test/mri/excludes/Psych/TestCoder.rb
new file mode 100644
index 0000000000..54282f5aac
--- /dev/null
+++ b/test/mri/excludes/Psych/TestCoder.rb
@@ -0,0 +1 @@
+exclude :test_dump_with_tag, "new test or regression, #5142"
diff --git a/test/mri/excludes/Psych/TestJSONTree.rb b/test/mri/excludes/Psych/TestJSONTree.rb
new file mode 100644
index 0000000000..a433613abc
--- /dev/null
+++ b/test/mri/excludes/Psych/TestJSONTree.rb
@@ -0,0 +1,4 @@
+exclude :test_datetime, "new test or regression, #5142"
+exclude :test_hash, "new test or regression, #5142"
+exclude :test_list_to_json, "new test or regression, #5142"
+exclude :test_time, "new test or regression, #5142"
diff --git a/test/mri/excludes/Psych/TestOmap.rb b/test/mri/excludes/Psych/TestOmap.rb
new file mode 100644
index 0000000000..d5e2564a8f
--- /dev/null
+++ b/test/mri/excludes/Psych/TestOmap.rb
@@ -0,0 +1 @@
+exclude :test_dump, "new test or regression, #5142"
diff --git a/test/mri/excludes/Psych/TestToYamlProperties.rb b/test/mri/excludes/Psych/TestToYamlProperties.rb
new file mode 100644
index 0000000000..09e5fd915e
--- /dev/null
+++ b/test/mri/excludes/Psych/TestToYamlProperties.rb
@@ -0,0 +1,3 @@
+exclude :test_object_dump_yaml_properties, "new test or regression, #5142"
+exclude :test_string_dump, "new test or regression, #5142"
+exclude :test_struct_dump_yaml_properties, "new test or regression, #5142"
diff --git a/test/mri/excludes/Psych/Visitors/TestEmitter.rb b/test/mri/excludes/Psych/Visitors/TestEmitter.rb
new file mode 100644
index 0000000000..16e63c0256
--- /dev/null
+++ b/test/mri/excludes/Psych/Visitors/TestEmitter.rb
@@ -0,0 +1,2 @@
+exclude :test_options, "new test or regression, #5142"
+exclude :test_sequence, "new test or regression, #5142"
```

**Comment by headius** [comment]
I removed my patch for excludes since we now have a complete accounting of failures in this build: https://travis-ci.org/jruby/jruby/jobs/367441040

**Comment by headius** [comment]
I've done a re-update of Psych tests and excludes and I don't think there's a need to keep this issue open. The remaining issues are mostly minor differences in SnakeYAML behavior or other small features we'll get to.
