### ISSUE TITLE
Is possible to use JRuby command line arguments inside of a .jar?

### ISSUE THREAD

**Issue by bolandross** [jruby/jruby#5150]
Hey folks,
sorry for the fact that this isn't an 'issue' and more just a question.

I am packaging my app with warbler to create a Java Jar file.
As far as I know, this bundles up JRuby with all my gem dependencies and then runs my script. Is there a way to specify command line arguments for this?

For example, I'd like to use the --dev argument for improved startup times.
Can I somehow define this inside of the jar manifest file?

**Comment by enebo** [comment]
This is what I have always considered a weird oversight in executable jar format in Java.  You basically need to load java and the re-load it again (tiny Java programs startup much faster than JRuby itself so this may not be a big hit).  I think there are some other programs which were made for this too (Capsule?):

http://blog.codejava.net/nam/trick-for-passing-vm-options-when-launching-jar-file/
