### ISSUE TITLE
Updating JRuby from 1.7.4

### ISSUE THREAD

**Issue by pdhimal1** [jruby/jruby#5152]
We are stuck in the past, 1.7.4 to be specific. When we tried to update to the newer versions on JRuby we get compile errors: 
`TextAreaReadline` cannot be resolved to a type.

This is more of a question then an issue. I couldn't find any documentations or forum out there that answers my question. Was the class renamed, moved, or replaced by another class?

Appreciate your support. 
Thanks,
Prakash

**Comment by headius** [comment]
`TextAreaReadline` was dependent on the implementation of our readline library, and as such it was pulled out to a separate jar file, lib/ruby/stdlib/readline.jar, with its jline dependency under lib/ruby/stdlib/jline/jline/<version>/jline-<version>.jar.

If you are compiling directly against that class we'll have to figure out a way to make it available to you, perhaps by pushing a maven artifact for the JRuby readline jar (cc @mkristian). May I ask what you are using `TextAreaReadline` for?

**Comment by mkristian** [comment]
yes, we can publish the old readline jar as jruby-readline.jar or so if this helps.

@pdhimal1 not clear to which version of jruby you are trying to upgrade ?

**Comment by pdhimal1** [comment]
@headius @mkristian thank you both for quick replies.

Tab completion does not work with our current version `1.7.4`. Shooting for `1.7.27` if the update is smooth. Any version that supports tab completion will be fine. 

If you can publish the old readline jar as `jruby-readline.jar`, that will be great!

Let me know of any updates.

//Prakash

**Comment by pdhimal1** [comment]
According to this https://stackoverflow.com/questions/13381560/how-to-enable-irb-tab-completion-in-jruby, tab complete stopped working with 1.7.0?

Is there a way to fix tab complete in 1.7.4? This will the easiest way to fix my problem for the moment. I would still like to be able to update though.
 
Thanks,
Prakash

**Comment by mkristian** [comment]
@pdhimal1 you could try jruby-1.7.27 and install one of the older jruby-readline gems from here: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22rubygems%22%20AND%20a%3A%22jruby-readline%22
but I can not tell you where and if the tab-completion works with any of these

**Comment by pdhimal1** [comment]
@mkristian thank you for the solution. I will close this issue now.
