### ISSUE TITLE
Fix refinements

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5153]
This is a catch-all bug for the various refinements issues. I'll try to get as close to 100% as possible before 9.2.

Known bugs fixed for this issue: #5054 #5221 #4514 #4489 #4330 #4288 #4237 #4236.

**Comment by Envek** [comment]
Please also add https://github.com/jruby/jruby/issues/5221 to this list :pray:

**Comment by headius** [comment]
@Envek It appears #5221 was fixed along with most of the others.

Only #4840 remains unsolved, and we know the issue. I'm going to mark this one fixed since the bulk of user-reported refinement problems are now solved.
