### ISSUE TITLE
JRuby doesn't support OpenSSL library

### ISSUE THREAD

**Issue by CT-Rahul** [jruby/jruby#5174]
JRuby doesn't support OpenSSL library

**Comment by kares** [comment]
is this just a random issue report or could you explain what do you mean by that?
`require 'openssl'` clearly works in any JRuby -> if it weren't most libraries such a RubyGems wouldn't work

**Comment by headius** [comment]
JRuby clearly does support the API of Ruby's openssl library, so this is not a valid report. If you have a specific issue using openssl in JRuby please file a more detailed report.

**Comment by CT-Rahul** [comment]
I am using Mechanize gem(jruby-9.1.15.0) to get the page, but following error is there. 

OpenSSL::SSL::SSLError: handshake alert:  unrecognized_name
from org/jruby/ext/openssl/SSLSocket.java:228:in `connect_nonblock'

My code is..
agent = Mechanize.new
agent.verify_mode = OpenSSL::SSL::VERIFY_NONE
page = agent.get "some url"

Then I added OpenSSL and jruby-openssl gems but i did not find any solution for that.

![openssl](https://user-images.githubusercontent.com/25149472/40294349-d0938cc6-5cf2-11e8-8515-18321d0b7243.png)
