### ISSUE TITLE
Java types should simply toString on inspect?

### ISSUE THREAD

**Issue by kares** [jruby/jruby#5182]
Java types `inspect` isn't as useful as for Ruby objects.
When using Ruby tools it usually just shows the type but no real information, e.g.

```
  2) Date"to_java java 8 types coerces to java.time.Instant
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }

       expected: #<Java::JavaTime::Instant:0x25ce9dc4>
            got: #<Java::JavaTime::Instant:0x17f62e33>

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -#<Java::JavaTime::Instant:0x25ce9dc4>
       +#<Java::JavaTime::Instant:0x17f62e33>
     # ./spec/java_integration/types/coercion_spec.rb:946:in `block in (root)'

```

its likely a breaking change -> so only to be done in a major version such as **9.2**

**Comment by headius** [comment]
At one point inspect also showed fields, by reflectively digging them out. Once we removed that, the inspect output is now largely useless other than showing what type the object is.

Perhaps it should be something like `#<Java::SomeJavaPackage::SomeClass:0xcafebabe "toString output">` I think objections in the past were that the toString for a Java object could be very large, and inspect is often used for logging errors etc.

**Comment by kares** [comment]
> At one point inspect also showed fields, by reflectively  digging them out. Once we removed that, the inspect output is now  largely useless other than showing what type the object is.

that would make sense for me, but only doing that if there isn't a toString override (which is tricky).
should mean common types such as `ArrayList` or Java `Date` will return a simple representation (like in Ruby). large or not, there's giant inspect in Rails e.g. when you inspect a `connection` or smt holding it.

**Comment by headius** [comment]
A simple way to do this is to just define java.lang.Object.inspect to call to_s, but that will do it for all Java objects, not just the ones that have overridden to_s.

**Comment by kares** [comment]
have an idea to play some 'ugly' tricks around and hook this up into the JavaProxy class, as I want it to play well with existing Java array inspect-ing while also providing a reflective default, we'll see how it goes ...

**Comment by headius** [comment]
Ok I'll let you play with it then.

**Comment by kares** [comment]
some progress - to make it somehow cleaner I would be reverting an old feature, where a proxy Java class does not get instance methods put in if its smt that exists in super hierarchy e.g. an `ArrayList` has a toString from `AbstractCollection` but the `AbstractCollection.instance_methods` won't include `:toString` since its already there on `java.lang.Object` ... this 'feature' is way back from https://github.com/jruby/jruby/commit/fe133a20ed63fe724ba9bef644b6e05a6b05fdf5

**Comment by kares** [comment]
JRuby will be shipping changed Java type inspect -> toString in 9.2.1 (https://github.com/jruby/jruby/pull/5219)
