### ISSUE TITLE
[9.2.0.0] Missing gems in dist

### ISSUE THREAD

**Issue by cpuguy83** [jruby/jruby#5196]
```
jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 OpenJDK 64-Bit Server VM 25.162-b12 on 1.8.0_162-8u162-b12-1~deb9u1-b12 +jit [linux-x86_64]
```

The provided jruby packaging is missing some pre-installed gems which were previously included:

- net/telnet
- xmlrpc/server
- xmlrpc/client
- rake

**Comment by headius** [comment]
cc @mkristian 

I guess I missed a step getting preinstalled gems into the dist, because only the "default" gems (those installed into stdlib dir) are actually present.

**Comment by headius** [comment]
Oh, workaround...

In both JRuby 9.2 and CRuby 2.5, these gems truly are just preinstalled. If you install the missing gems into your JRuby 9.2 dist you'll basically have the same setup as CRuby. And in both cases if you're using them in, say, a bundled app, you still have to specify them anyway:

```
$ bundle exec ruby -v -e 'require "net/telnet"'
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
Traceback (most recent call last):
	1: from -e:1:in `<main>'
-e:1:in `require': cannot load such file -- net/telnet (LoadError)
```

**Comment by headius** [comment]
@mkristian Thank you!
