### ISSUE TITLE
GZipFile#close does not return IO object as MRI does

### ISSUE THREAD

**Issue by pcarlisle** [jruby/jruby#5197]
MRI documents (and implements) that #close on GZipFile and subclasses should return the associated IO object. JRuby returns nil.

https://ruby-doc.org/stdlib-2.3.0/libdoc/zlib/rdoc/Zlib/GzipFile.html#method-i-close

https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/zlib/RubyGzipFile.java#L252-L255

https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/zlib/JZlibRubyGzipWriter.java#L195

In MRI I can do this:

```ruby
    writer = Zlib::GzipWriter.new(str)
    writer.write(data)
    writer.close.string
```
which fails in JRuby when trying to call `string` on `nil`. I'm running 9.1.16.0 but looks from the source like this has not changed.

**Comment by headius** [comment]
Weird feature.

**Comment by headius** [comment]
Ok, I think I've fixed this on master. You should see an [updated build](https://projectodd.ci.cloudbees.com/view/JRuby/job/jruby-development-dist/lastSuccessfulBuild/artifact/release/). There does not appear to be a test for this in either CRuby's suite or in ruby/spec. Perhaps you could add something over at https://github.com/ruby/spec?
