### ISSUE TITLE
Modifying a StringIO can overwrite other strings derived from it

### ISSUE THREAD

**Issue by pcarlisle** [jruby/jruby#5203]
### Environment

```
Linux wait-and-see 4.16.8-1-ARCH #1 SMP PREEMPT Wed May 9 11:25:02 UTC 2018 x86_64 GNU/Linux

jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.162-b12 on 1.8.0_162-b12 +jit [linux-x86_64]
```

I am testing some file rewriting by using a StringIO instance. The original contents get parsed, resulting in various other strings, and then the StringIO is rewritten. I've found that the rewriting will modify the other strings from parsing.

I've managed to reproduce it with this standalone script:

```ruby

require 'stringio'

a = []

# The interpolation here makes the sharelevel 0 on the argument to StringIO.new,
# which is necessary to trigger the issue
# I'm sure there's a better way but this was how I encountered it
thing = 'kjh'
strio = StringIO.new(<<EOS)
      before = value to keep before
      base = #{thing}
      after = value to keep
EOS

strio.each_line do |line|
  a << line
end

strio.rewind
strio.write('xxxxxxxx')

puts a
```

Since `a` is an array of the original lines from `each_line` this script should print the original string argument to `StringIO.new`, but instead it includes the output `xxxxxxxx` overwriting part of the first line.

I've poked around a bit, and it seems like in this case StringIO.getline creates a substring such that the new string is shared but the original doesn't get marked as shared.

**Comment by aryeh-looker** [comment]
This bug breaks the S3 AWS SDK gem when using the multipart upload API to an invalid region https://github.com/aws/aws-sdk-ruby/issues/1843. I have verified that https://github.com/jruby/jruby/commit/b0875446c80d496a7f0e4b71183beef0839f4de1 fixes the issue by:
* running the repro in the S3 ticket under master — it succeeds
* running the repro in the S3 ticket under master with a revert of https://github.com/jruby/jruby/commit/b0875446c80d496a7f0e4b71183beef0839f4de1 — it fails

Looking forward to this being in `9.1.18.0` and thanks for your fix @kares!
