### ISSUE TITLE
ScriptEngine.put doesn't work with JRuby 9.2.0.0

### ISSUE THREAD

**Issue by pajswigger** [jruby/jruby#5207]
### Environment

jruby-complete-9.2.0.0.jar
MacOS Darwin

### Expected Behavior

```
import org.jruby.embed.jsr223.JRubyEngineFactory;
import javax.script.ScriptEngine;

public class jruby
{
    public static void main(String[] args) throws Exception
    {
        ScriptEngine scriptEngine = new JRubyEngineFactory().getScriptEngine();
        scriptEngine.put("foo", "bar");
        scriptEngine.eval("puts $foo");
    }
}
```

With JRuby 9.1.12.0 this outputs "bar" as expected.

### Actual Behavior

With JRuby 9.2.0.0 the output is empty

```
$ java -cp jruby-complete-9.1.12.0.jar:. jruby
bar
$ java -cp jruby-complete-9.2.0.0.jar:. jruby

```

**Comment by kares** [comment]
but `scriptEngine.eval("puts foo")` likely does? ... if I recall right the var scope was switched to local

**Comment by pajswigger** [comment]
I see, yes it does. Ok, as the change is intentional we can work around it on our side.
