### ISSUE TITLE
Haml on JRuby 9.2.0.0 throws error evaluating interpolated element attribute with `#`

### ISSUE THREAD

**Issue by HarlemSquirrel** [jruby/jruby#5210]
Interesting issue with JRuby 9.2.0.0 and Haml when attempting to evaluate an element attribute with a `#` just before the interpolated variable.

This is the line which causes the error. 

```haml
-# app/views/welcome/_partial.html.haml
%p{ data: { target: "##{partial_local_var}" } }
```

```
Error:
WelcomesTest#test_visiting_the_index:
ActionView::Template::Error: undefined local variable or method `partial_local_var' for #<Haml::AttributeCompiler:0x9906d99>
    (eval):1:in `<eval>'
    app/views/welcome/index.html.erb:3:in `_app_views_welcome_index_html_erb___706324677_2068'
```

Using `%p{ data: { target: ('#' + partial_local_var.to_s) } }` does not throw the error.

I made a [test app](https://github.com/HarlemSquirrel/jruby-rails-haml-test) to demonstrate the error.

**Comment by HarlemSquirrel** [comment]
Actually, I was able to make a much smaller test case. Too bad I didn't think of this before making the whole Rails app.

```haml
-# test.haml
- time = Time.now
%p{ 'data-time': "##{time}" } Time
```

```
➤  rvm use jruby-9.2.0.0 do haml test.haml 
Exception on line 1: undefined local variable or method `time' for #<Haml::AttributeCompiler:0x144a5e6e>
  Use --trace for backtrace.

➤  rvm use jruby-9.1.17.0 do haml test.haml                                                                                     1 ↵
<p data-time='#2018-06-06 13:04:38 -0400'>Time</p>

➤  rvm use 2.5.1 do haml test.haml
<p data-time='#2018-06-06 13:04:45 -0400'>Time</p>
```

**Comment by headius** [comment]
Neato...so it's having a problem with the double # here. Maybe a simple fix @enebo?

**Comment by enebo** [comment]
Maybe not simple at all... :)  It took a while to trace this to Temple using Ripper.

I did just reduce it to a ripper bug though.  Here is a minimized test case:

```text
jruby -rripper -e "p Ripper.lex('\"##{time}\"')"
```

We should be seeing to_tstring_content of just '#', but instead we slurp in '##{time}'.  Getting close.

**Comment by HarlemSquirrel** [comment]
Nice work!
