### ISSUE TITLE
Illegal reflective access by org.jruby.util.ShellLauncher

### ISSUE THREAD

**Issue by elsabio** [jruby/jruby#5223]
### Environment

I'm seeing this with jruby 9.1.17.0 (jrubycomplete.jar's ScriptingContainer) with Java 10.0.1 on a Windows 10 platform.

### Expected Behavior

No Warning!

### Actual Behavior

This is the warning I see:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.ShellLauncher (jar:file:/C:/Work/.../script_jruby.jar!/lib/jrubycomplete.jar) to field java.lang.ProcessImpl.handle
WARNING: Please consider reporting this to the maintainers of org.jruby.util.ShellLauncher
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by hupfis** [comment]
Similar problem with jruby 9.2.0.0 with Java 10.0.2 on a Windows 10 platform
Jruby version info: 
> jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 10.0.2+13 on 10.0.2+13 +jit [mswin32-x86_64]

Warnings:
> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.runtime.encoding.EncodingService to field java.io.Console.cs
WARNING: Please consider reporting this to the maintainers of org.jruby.runtime.encoding.EncodingService
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by elsabio** [comment]
Thanks for the statement of direction.  Just in case anyone else finds this ticket in a search, for Open JDK at least, JEP 261 does specify that modules can be opened up either on the command line or in a jar manifest.  This is obviously at the user's own risk, but we have had some success with Add-Opens in the manifest.
