### ISSUE TITLE
jruby (ext) loading left-overs to consider

### ISSUE THREAD

**Issue by kares** [jruby/jruby#5233]
... left-overs from https://github.com/jruby/jruby/pull/5205

- do we force users extension authors to do a `require 'jruby'` ... loosely needed atm
  (most exts tend to have an explicit `require 'jruby'` or use the new `load_ext` mechanism)
- JRuby auto-loads the `java` library (since ~ 1.6/1.7) think about NOT auto loading `require 'jruby'` 
  now, its auto-loaded from kernel which was likely not intentional (should only auto `require 'java'`)?

- document extension loading (wiki): `require 'jruby'; JRuby.load_ext('foo.bar.MyExtClass')`

- need to propagate `load_ext` changes to gems we tend to boot often (on every run) ~ due RGs : 
  [~~jruby-openssl~~](https://github.com/jruby/jruby-openssl/pull/167), [~~jruby-readline~~](https://github.com/jruby/jruby-readline/pull/3), [psych](https://github.com/ruby/psych/pull/365), [jar-dependencies](https://github.com/mkristian/jar-dependencies/pull/67)
  ... and get them to propagate releases (so this PR delivers the promised loading speed improvement)

**Comment by enebo** [comment]
@kares will load_ext work on 9.1.x?  It is not unsurmountable if it won't but this would make it much easier for extensions to update. 9.1.x is probably living until beginning of 2019 at least.

**Comment by kares** [comment]
@enebo we could back-port if it makes sense ...
but than I am not sure we need that - all of these gems handle `load_ext` backwards compatibly.
your assumption would be that it would help adoption - migrating gems to an official way of ext loading? 

>  9.1.x is probably living until beginning of 2019 at least.

that "long" for 9.1 - thought you guys do not plan on supporting multiple 2.x versions in parallel.

**Comment by enebo** [comment]
@kares I guess I did not realize load_ext worked on 9.1.  If so then no reason to backport.  Right now most exts I have written do this: 'Java::oj.OjLibrary.new.load(JRuby.runtime, false)'.

At this point I think we have reverted to the idea of supporting 2 versions only.  The problem with only one 9.x is that we cannot just say 9.2.0.0 is out use it!  We know it takes several point releases to iron over the work made (2.3->2.5 was larger than we actually planned since we skipped 2.4 too).   I am hoping 9.2.x matures faster than 9.1.x but there has to be some overlap so people don't feel dropped and angry about it.

**Comment by kares** [comment]
OK, just to clarify - `load_ext` does not work in 9.1 (unless backported) but the way we add support for it a newer gems is backward compatible : 
```ruby
+if JRuby::Util.respond_to?(:load_ext) # JRuby 9.2
+  JRuby::Util.load_ext('org.jruby.ext.openssl.OpenSSL')
+else; require 'jruby'
+  org.jruby.ext.openssl.OpenSSL.load(JRuby.runtime)
+end
```
(JRuby::Util has existed as an internal pre-loaded piece to help boot - somehow resurrected the concept just so "internal" loading works even without `require 'jruby'`) ... thus your ext would do the "official" way  : 
```crystal
require 'jruby'
if JRuby.respond_to?(:load_ext)
  JRuby.load_ext('oj.OjLibrary')
else
  Java::oj.OjLibrary.new.load(JRuby.runtime, false)
end
```

BTW some questions still remain e.g. whether to remove `require 'jruby'` happening on JRuby boot -
no opinions there really other than loading "less" so eventually JRuby could also NOT auto `require 'java'` at some point in the future ... maybe :)

**Comment by enebo** [comment]
@kares thanks.  I suppose for backwards compat we need to do new and old way anyways so this is some good boilerplate which should be on our wiki somewhere too.

**Comment by kares** [comment]
jar_dependencies has been updated already ^^ and now psych 3.0.3 is also in https://github.com/jruby/jruby/commit/d18d98d74e596a99234f09bd1b85ebe76e6fc5ee
... so all the left-overs are handled -> JRuby shouldn't do any self reflection on its own, at least with its default commands such as gem, irb
