### ISSUE TITLE
popen3 doesn't works fine with java 9/10 and jruby > 1.9.13

### ISSUE THREAD

**Issue by areman** [jruby/jruby#5235]
The stdout, stderr is not captured with java 9 and 10.

I'm running this simple test on Ubuntu 16.04 and SLES with the same result
```
require 'open3'

Open3.popen3('echo 123') do |_stdin, stdout, _stderr|
  out = stdout.read.strip
  fail "exprected '123' but got '#{out}'" unless out == '123'
end
```
With Java 10.0.1 and 9.1.13 it works fine.
Starting from jruby 9.1.14 the test fails.
Switching to Java 1.8.0_144 the test works again with jruby version greater than 9.1.13.

**Comment by lberoiza** [comment]
Thank you all for your answers.

But the problem is that popen3 doesn't works fine with **java 9/10** and **jruby 1.9.13**

**Comment by headius** [comment]
Relates to #4835 which will continue work in 9.2.2.

**Comment by headius** [comment]
This seems to work fine for me on Java 11 on MacOS:

```ruby
require 'open3'

Open3.popen3('echo 123') do |_stdin, stdout, _stderr|
  out = stdout.read.strip
  p out
end
```
```
$ jruby -v x.rb
jruby 9.2.8.0-SNAPSHOT (2.5.3) 2019-08-06 4d4d303 OpenJDK 64-Bit Server VM 11.0.2+9 on 11.0.2+9 +jit [darwin-x86_64]
"123"
```

**Comment by JonRowe** [comment]
This is happening on "JRuby 9.1.17.0" for "ubuntu 20.04" on Github actions, it might be the default Java for that release is broken?  https://github.com/rspec/rspec-support/runs/1435614749?check_suite_focus=true
