### ISSUE TITLE
cannot download .exe files

### ISSUE THREAD

**Issue by bshabash** [jruby/jruby#5236]
Not even sure where to report this, but I am on my browser, Chrome trying to download the .exe files (x64) and the website won't let me. When I click on it it gives me an XML report with the following:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>94D24A781FC1A8E5</RequestId>
<HostId>
6W7Fgx2Xl2sPyXnNeHfxpYOCmWHzVh2LsVQgJj7+TGdlF3E1DGmawDNGlkIwf01gvEwiN6b+H6Q=
</HostId>
</Error>

And when I right click and select "save as..." it won't download either. What is this?

**Comment by guyboertje** [comment]
@headius @enebo 
Please look into this as soon as you can. I'd be most appreciative.

**Comment by yaauie** [comment]
Related: URLs for artifacts on all of the versions listed on http://jruby.org/files/downloads/ end up emitting `HTTP` `404` `Not Found`.

**Comment by andreaseger** [comment]
all downloads from `https://s3.amazonaws.com/jruby.org/*` are impacted by this

**Comment by kares** [comment]
confirmed - none work e.g. anything from 9.2.0.0 http://jruby.org/files/downloads/9.2.0.0/index.html

**Comment by jsvd** [comment]
it seems everything moved to maven, example: `https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.1.13.0/jruby-dist-9.1.13.0-bin.tar.gz`

**Comment by ioquatix** [comment]
Seems like our travis builds are broken

https://travis-ci.org/igrigorik/http-2/jobs/399058240

https://travis-ci.org/socketry/nio4r/jobs/390765726

Does RVM need to be updated?

**Comment by guyboertje** [comment]
It looks like the JRuby team [asked RVM to change their links](https://github.com/rvm/rvm/issues/4223) to Maven on Nov 9, 2017 but the issue stalled and I can't find a PR on RVM that would fix this.

**Comment by ioquatix** [comment]
Damn, that's frustrating.

**Comment by headius** [comment]
Ugh...it sounds like the basket was removed again. We'll get it restored today.

**Comment by jsvd** [comment]
@headius should we see the maven repo as the right/official/futureproof place to get jruby from?

**Comment by enebo** [comment]
@jsvd yeah maven was intended to be the replacement and it happened for rbenv but we did not realize rvm has not updated to it yet.

**Comment by enebo** [comment]
In process of re-uploading all releases 9.2.0.0 and 9.1.17.0 are back up so those should be working again.

**Comment by headius** [comment]
@jsvd Yeah those files just need to be patched to use maven locations.

**Comment by enebo** [comment]
index files should largely be updated.  This involved a script but all the normative urls for -bin,-src,-complete all no point at maven instead of s3 (for 1.7.26, 9.1+ as those are only -dist releases we have made).  Older pre jruby-dist builds still point at s3.

**Comment by zevans** [comment]
@enebo Thank you for the above info. We recently upgraded to 1.7.27 on windows to gain TLSv1.2 support for access to rubygems. In doing so we're running into the issue described here in [3920](https://github.com/jruby/jruby/issues/3920)

So - We've been on the hunt for 1.7.24 which may have the TLSv1.2 support we need but without the issue in 3920. (In parallel we're working on a major upgrade to 9k series if it doesn't pan out). While looking for 1.7.24 for windows x64, we discovered the missing S3 downloads and subsequently that maven doesn't have windows versions just yet. 

Is there another way at this point to find this version? 

Thank you kindly!

**Comment by lucassch** [comment]
https://s3.amazonaws.com/jruby.org/downloads/1.7.27/jruby_windows_x64_1_7_27.exe broken

**Comment by davemitchell** [comment]
I'm experiencing the same issue today

**Comment by headius** [comment]
Old issue that should have been closed. Long story short, we lost most of our S3 downloads when our project host mistakenly removed our buckets from what they thought was a shared account. The archives were restored from another location but the original .exe installers were lost.

Going forward, we will publish the .exe installers to Maven, like we now do for the rest of the archives. We recommend using Maven as the canonical source.

See #4829.
