### ISSUE TITLE
tty issue with 1.7.2 (and 1.7.1), works in MRI

### ISSUE THREAD

**Issue by bcardarella** [jruby/jruby#524]
I'm getting an error in jruby that isn't happening in cruby 1.9.3. Here is the stack trace: https://gist.github.com/4700559 and line of code that is causing the failure https://github.com/dockyard/party_foul/blob/master/lib/generators/party_foul/install_generator.rb#L11 I'm not quite sure how to debug this

The strange thing is if I run the code that causes the issue in isolation: https://gist.github.com/4702733 it runs just fine with 1.7.2

**Comment by rtyler** [comment]
I believe this issue to be fixed, I've cloned the repository in question and run the tests on JRuby 9k and they work just fine on Debian/JDK8

```
➜  party_foul git:(master) rake test
Run options: --seed 13358

# Running tests:

.....................................................

Finished tests in 0.988000s, 53.6437 tests/s, 122.4696 assertions/s.

53 tests, 121 assertions, 0 failures, 0 errors, 0 skips
➜  party_foul git:(master) ruby -e "puts JRUBY_VERSION"
9.0.0.0
➜  party_foul git:(master) git log --oneline -n 1     
2678572 Merge pull request #114 from mkozono/prevent-exceptions
➜  party_foul git:(master) 
```
