### ISSUE TITLE
9.2.0.0 rake missing rake gem and fails

### ISSUE THREAD

**Issue by anthraxx** [jruby/jruby#5244]
### Environment

* jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 OpenJDK 64-Bit Server VM 10.0.1+10 on 10.0.1+10 +jit [linux-x86_64]
* Stock distributed 9.2.0.0 tarball

### Expected Behavior

`rake` in `jruby` dist should work out of the box

### Actual Behavior

```
# /opt/jruby/bin/rake
Gem::GemNotFoundException: can't find gem rake (>= 0.a) with executable rake
  find_spec_for_exe at /opt/jruby/lib/ruby/stdlib/rubygems.rb:289
  activate_bin_path at /opt/jruby/lib/ruby/stdlib/rubygems.rb:308
             <main> at /opt/jruby/bin/rake:23
```

the ```rake.gemspec``` is missing from the tarball's ```lib/ruby/gems/shared/specifications/default```

All works fine in `jruby-9.1.17.0` and that dist contains the gemspec so that ```rake``` works.

**Comment by headius** [comment]
Yeah we needed some extra build logic to include the gem in our dist after we made it a "normal" preinstalled gem like CRuby.

You can just install it. This has already been fixed on master.

**Comment by anthraxx** [comment]
@headius When is a new fixed release planned? We are packaging jruby for a distro and it would be best to have it working in the archive. using gem and installing aside for packaging rake into jruby is bit pain and ugly.
