### ISSUE TITLE
timeout.rb seems to be missing 

### ISSUE THREAD

**Issue by fabianfrz** [jruby/jruby#5264]
### Environment

https://github.com/jruby/jruby/tree/master/lib/ruby/stdlib is missing `timeout.rb`

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc): jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 OpenJDK 64-Bit Server VM 25.172-b11 on 1.8.0_172-b11 +jit [linux-x86_64]
* Operating system and platform (e.g. `uname -a`) : `Linux host 4.17.6-1-hardened #1 SMP PREEMPT Thu Jul 12 11:39:44 CEST 2018 x86_64 GNU/Linux`

Other relevant info you may wish to add:
* Installed or activated gems [Gemfile.lock](https://github.com/jruby/jruby/files/2237786/Gemfile.lock.txt)
* Application/framework version (e.g. Rails, Sinatra): rails 5.1

### Expected Behavior

Rails should start (newly generated application) should start .

### Actual Behavior

```
jruby-9.2.0.0/bin/rails s
#<Class:0xce5a68e>: cannot load such file -- timeout
                             require at /path/to/jruby/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bootsnap-1.3.1-java/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32
                    block in require at /path/to/jruby/jruby-9.2.0.0/lib/ruby/gems/shared/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292
                     load_dependency at /path/to/jruby/jruby-9.2.0.0/lib/ruby/gems/shared/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258
                             require at /path/to/jruby/jruby-9.2.0.0/lib/ruby/gems/shared/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292
                              <main> at /path/to/jruby/jruby-9.2.0.0/lib/ruby/gems/shared/gems/concurrent-ruby-1.0.5-java/lib/concurrent/concern/obligation.rb:2
```

**Comment by enebo** [comment]
@fabianfrz our timeout exists in Java code. This might be related to bootsnap maybe. Can you -rtimeout -e 1 outside rails

**Comment by fabianfrz** [comment]
@enebo yes it works, I've also tried a case with an exception which seems to work. I close this issue here and recreate it in the bootsnap repository. Thanks for clarification.

**Comment by enebo** [comment]
Oh I s only guessing it may be related to bootsnap. I am not sure what is up, but I suspected something rails is doing we do not expect

**Comment by fabianfrz** [comment]
sure, but bootsnap contains native code, which of won't run on jruby anyway (at least from my knowledge) and needs an appropriate jar instead. Because rails should run on jruby, this dependency should not be loaded when running on jruby.
