### ISSUE TITLE
DifferencesBetweenMriAndJruby is removed from wiki?

### ISSUE THREAD

**Issue by jychen7** [jruby/jruby#5283]
Hi I am a Rubyist and normally use MRI ruby. And I am going to use JRuby in AWS Lambda, and reading wiki for JRuby. I do want to know about is there anything need to take care of when switch from MRI to JRuby.

> See Differences Between MRI And JRuby for more information on potential incompatibilities between JRuby and the C implementation of Ruby.
from https://github.com/jruby/jruby/wiki/AboutJRuby

### Expected Behavior

there is a wiki page for https://github.com/jruby/jruby/wiki/DifferencesBetweenMriAndJruby 

### Actual Behavior

page not found

**Comment by mprins** [comment]
someone edited https://github.com/jruby/jruby/wiki/Differences-Between-MRI-and-JRuby ad github wiki isn't smart about it

**Comment by jychen7** [comment]
ah, thx
