### ISSUE TITLE
Zlib crc32 resulting into Java::JavaLang::ArrayIndexOutOfBoundsException (32)

### ISSUE THREAD

**Issue by vipulnsward** [jruby/jruby#5290]
After https://github.com/jruby/jruby/pull/5088/files was merged:

```
irb(main):027:0> n =  "p" ; key = ~305419896
=> -305419897
irb(main):028:0> Zlib.crc32(n, key)
Traceback (most recent call last):
       16: from org.jruby.RubyKernel.eval19(RubyKernel.java:1037)
       15: from org.jruby.RubyKernel.evalCommon(RubyKernel.java:1070)
       14: from org.jruby.ir.interpreter.Interpreter.evalWithBinding(Interpreter.java:197)
       13: from org.jruby.ir.interpreter.Interpreter.evalCommon(Interpreter.java:173)
       12: from org.jruby.ir.interpreter.Interpreter.INTERPRET_EVAL(Interpreter.java:119)
       11: from org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
       10: from org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
        9: from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:201)
        8: from org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:365)
        7: from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
        6: from org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:801)
        5: from org.jruby.ext.zlib.RubyZlib$INVOKER$s$0$2$crc32.call(RubyZlib$INVOKER$s$0$2$crc32.gen)
        4: from org.jruby.ext.zlib.RubyZlib.crc32(RubyZlib.java:206)
        3: from com.jcraft.jzlib.JZlib.crc32_combine(JZlib.java:90)
        2: from com.jcraft.jzlib.CRC32.combine(CRC32.java:108)
        1: from com.jcraft.jzlib.CRC32.gf2_matrix_times(CRC32.java:134)
Java::JavaLang::ArrayIndexOutOfBoundsException (32)
```

This passes successfully on ruby 2.5.1 as:

```
irb(main):010:0> n =  "p" ; key = ~305419896
=> -305419897
irb(main):011:0> Zlib.crc32(n, key)
=> 4046865307
```

Related on why ruby seems to allows this: https://github.com/ruby/ruby/commit/778796b00813a96925ab1156d8f8a41f3315c2c2

**Comment by prashantvithani** [comment]
@vipulnsward I'm facing same issue. Have you found any workaround?

**Comment by headius** [comment]
Huh...is this our bug or a bug in jzlib?

**Comment by vipulnsward** [comment]
Its just deviation from functionality in jruby vs ruby. 

https://github.com/ruby/ruby/commit/778796b00813a96925ab1156d8f8a41f3315c2c2 takes care of adjusting byte width in MRI.

**Comment by headius** [comment]
I'm having a little trouble figuring out the right way to address this.

The fix in MRI seems to try to force longs into UINT, because that's what the zlib functions accept. Am I following correctly?

We use a pure-Java zlib port called jzlib, which always uses 64-bit signed longs for this parameter. So it seems like the only thing we need to do is to normalize negative long values passed in to their positive equivalents, rather than doing this extra loop to handle UINT-sized chunks. But I'm not sure if this is going to produce the equivalent values as MRI.

**Comment by headius** [comment]
Ping @ymnk for input.

**Comment by prashantvithani** [comment]
This error will occur only for negative long numbers. CRC32 requires the initial value (say `crc1`) to be of 32 bits only and expects it to become 0 after `crc1 >> 32`.

https://github.com/ymnk/jzlib/blob/a21be20213d66eff15904d925e9b721956a01ef7/src/main/java/com/jcraft/jzlib/CRC32.java#L129-L139

The size of lookup table `mat` is fixed at 32. The return value of `RubyNumeric.num2long(-305419897)` is equal to `0xFFFFFFFFEDCBA987`, 64-bit number. As it doesn't resolve to 0 after `0xFFFFFFFFEDCBA987 >> 32` (i.e. 32 times (>>1) in loop), the loop goes on for the index 32, which is not expected.

The immediate fix for this would be to trim the 64-bit hex to 32-bit using `start & 0xFFFFFFFFL`. So it becomes 0 after 32 loops.

**Comment by prashantvithani** [comment]
@headius: This seems to produce the equivalent value as in MRI for the example quoted by @vipulnsward.
