### ISSUE TITLE
rehashing regression with compare_by_identity

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#5304]
### Environment
jruby 9.2.1.0-SNAPSHOT (2.5.0) 2018-08-29 dad052a Java HotSpot(TM) 64-Bit Server VM 10.0.1+10 on 10.0.1+10 +jit [mswin32-x86_64]

probably related to the new hash implementation https://github.com/jruby/jruby/pull/5215 , @ChrisBr ?

https://github.com/jruby/jruby/blob/4e8bb2666a7257f0f5986800f96bb88efdd6acbd/spec/ruby/core/hash/compare_by_identity_spec.rb#L17
```ruby
1000.times do
  h = {}
  (1..10).each { |k| h[k] = k }
  o = Object.new
  def o.hash; 123; end
  h[o] = 1
  h.compare_by_identity
  puts h[o] == 1
end
```

another example (fails randomly)
https://travis-ci.org/rails/sprockets/jobs/422225343

### Expected Behavior
should always return true

### Actual Behavior
```
true
true
true
false
true
true
true
true
true
true
true
false
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
false
true
true
true
true
true
true
false
false
true
true
true
true
true
true
...
```

**Comment by ChrisBr** [comment]
@ahorek thanks for the bug report.

Confirmed, this does not happen with 9.2.2.0. I will look into it!

**Comment by ChrisBr** [comment]
@ahorek found the issue and submitted a PR, stay tuned :+1:
