### ISSUE TITLE
Invalid byte sequence in UTF-8 for StringIO objects

### ISSUE THREAD

**Issue by prashantvithani** [jruby/jruby#5309]
### Environment

Provide at least:
* jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 OpenJDK 64-Bit Server VM 10.0.2+13-Ubuntu-1ubuntu0.18.04.1 on 10.0.2+13-Ubuntu-1ubuntu0.18.04.1 +indy +jit [linux-x86_64]

### Expected Behavior
In MRI,

`file = URI.parse(url).open` gives `StringIO` object, which has `external_encoding` set to `ASCII-8BIT` . Doing `file.read.match(//)` works fine as expected.

### Actual Behavior
In JRuby

`URI.parse(url).open` gives `StringIO` object, which has `external_encoding` set to `UTF-8`. Doing `file.read.match(//)` throws error `Invalid byte sequence in UTF-8`

The actual encoding of the downloaded content is `ASCII-8BIT`. If we set the encoding of `StringIO` object to `ASCII-8BIT`, and do`file.read.match(//)`, it works fine again.

**Comment by enebo** [comment]
@prashantvithani Any chance you can make a script showing this problem?  open is a private method which expects an argument.  I am not sure how to reproduce this.

**Comment by ahorek** [comment]
it looks like open-uri?
```
require 'open-uri'
url = "http://xxx"
open(url).string.encoding
```

**Comment by prashantvithani** [comment]
```ruby
require 'open-uri'
url = "https://lh3.googleusercontent.com/hGq42jW-gwJc8hWmzbseAsvnEKMSe9ukj8drAp0M8T0NY_Ya4ibxERW5eICoZt0WbpQnsF4=s64"
file = open(url)
if file.is_a?(StringIO)
  image = file.read
  image.match(//) # Throws Invalid byte sequence in UTF-8
end
```

@enebo This script should help in reproducing. The thing to note here is that the error occurs only if the return type of `open(url)` is `StringIO`. I believe the content is saved on `Tempfile` or `StringIO` based on the size of the content which is downloaded. It works fine for larger files which gets saved through `Tempfile`.

**Comment by lopex** [comment]
Isnt that a case where MRI tends to mark everything as ascii when there's only 7 bit content like in #5086

**Comment by enebo** [comment]
So I figured something out but I am done for today.  the StringIO is extended with some module Meta and that does some meta handling of HTTP headers which ends up calling @io.string.force_encoding.  We do this and @io.string is ASCII-8BIT but the @io.ptr.encoding is still set to UTF-8.  I half wonder if both string.encoding and ptr.encoding in MRI are sharing the same pointer?  Otherwise our impls are nearly identical (not in a way which should affect this bug).

I've nearly figured this out though.

**Comment by enebo** [comment]
Will add a spec for this behavior as it is very unintuitive that io.string.force_encoding somehow will change the result of calling io.external_encoding.
