### ISSUE TITLE
Unable to use jirb on ARMv7 processor

### ISSUE THREAD

**Issue by abhi18av** [jruby/jruby#5362]
Hello jRuby team,

I'm trying to setup `rails` on my `ARMv7` instance on `Scaleaway C1` server but I am stuck with this error when I try to use `jirb`

```
root@pup:~# jirb
NotImplementedError: fstat unimplemented unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
  initialize at org/jruby/RubyIO.java:1036
        open at org/jruby/RubyIO.java:1177
  initialize at /usr/local/jruby/lib/ruby/stdlib/irb/input-method.rb:141
  initialize at /usr/local/jruby/lib/ruby/stdlib/irb/context.rb:70
  initialize at /usr/local/jruby/lib/ruby/stdlib/irb.rb:410
       start at /usr/local/jruby/lib/ruby/stdlib/irb.rb:381
      <main> at /usr/local/jruby/bin/jirb:13

```

* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)

```
root@pup:~# jruby -v
jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) Client VM 25.181-b13 on 1.8.0_181-b13 +jit [linux-arm]

```
* Operating system and platform (e.g. `uname -a`)

```
root@pup:~# uname -a
Linux pup 4.9.93-mainline-rev1 #1 SMP Tue Apr 10 09:42:40 UTC 2018 armv7l armv7l armv7l GNU/Linux
```

**Comment by headius** [comment]
You may be able to run with `-Xnative.enabled=false` which will disably some native-level features but boot up better. We have another issue #5192 that also has issues booting on armv7 and hope to address that for 9.2.1.

**Comment by abhi18av** [comment]
Mm hmm, I understand @headius , thanks 👍 

Do you mean that I can use `jirb` like this 
```
root@pup:~# jruby -Xnative.enabled=false -S jirb
NotImplementedError: fstat unimplemented unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
  initialize at org/jruby/RubyIO.java:1036
        open at org/jruby/RubyIO.java:1177
  initialize at /usr/local/jruby/lib/ruby/stdlib/irb/input-method.rb:141
  initialize at /usr/local/jruby/lib/ruby/stdlib/irb/context.rb:70
  initialize at /usr/local/jruby/lib/ruby/stdlib/irb.rb:410
       start at /usr/local/jruby/lib/ruby/stdlib/irb.rb:381
      <main> at /usr/local/jruby/bin/jirb:13
```

**Comment by headius** [comment]
Finally got my Raspberry Pi 3 running...and I can reproduce.

**Comment by headius** [comment]
I believe I have a lead on the problem.

There are a number of posts from 5-6 years ago about a transition that Debian made (and Rasbian with it) from soft floating point logic to hard floating point logic on ARM. Unfortunately softfp and hardfp must be compiled for and are not compatible with each other, so on a hardfp system as Rasbian is now, a softfp-compiled library won't be able to load.

That appears to be the case here. Here's the ELF EABI sections for the library we ship and for the `java` executable that comes with Rasbian:

```
pi@raspberrypi:~/jruby $ readelf -A jffi4052622518226348551.so 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "ARM9TDMI"
  Tag_CPU_arch: v4T
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_FP_arch: VFPv2
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_optimization_goals: Aggressive Speed
pi@raspberrypi:~/jruby $ readelf -A `which java` 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "6"
  Tag_CPU_arch: v6
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_FP_arch: VFPv2
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: SP and DP
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_DIV_use: Not allowed
```

Given that hardfp is now the most common mode on all modern ARM systems, and our 32-bit ARM library has not been rebuilt since 2012, I'm thinking we should recompile it with hardfp.

**Comment by headius** [comment]
Rebuilding the ARM binary on my pi3 appears to produce a binary with the proper EABI:

```
pi@raspberrypi:~/jffi $ readelf -A build/jni/libjffi-1.2.so 
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "6"
  Tag_CPU_arch: v6
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_FP_arch: VFPv2
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: SP and DP
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
```

And voila, it works in JRuby:

```
pi@raspberrypi:~/jruby $ jirb
irb(main):001:0> puts 'hello'
hello
=> nil
irb(main):002:0> 
```

So the remaining question is whether this is suitable to ship as our *sole* ARM32 binary, or whether we need to add in loading logic to support both soft and hardfp as done in Pi4J/pi4j#1.

**Comment by headius** [comment]
I have pushed an updated ARM binary in jnr/jffi#58. You can test it in JRuby by rebuilding both:

1. Check out the PR branch from jnr/jffi#58
2. `mvn install` from jffi dir
3. Check out JRuby master
4. Modify JRuby's root pom.rb to use `1.2.18-SNAPSHOT` for `jffi.version`.
5. `mvn clean package` from jruby dir

This should produce a JRuby distribution that works properly on hardfp ARM32.

I'm still trying to determine the risk of shipping a hardfp binary.

**Comment by headius** [comment]
You should be able to test the fix from a snapshot build here: https://projectodd.ci.cloudbees.com/view/JRuby/job/jruby-development-dist/lastSuccessfulBuild/artifact/release/
