### ISSUE TITLE
Kernel#sleep hangs on CI

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#5365]
### Environment
jruby 9.2.1.0-SNAPSHOT (2.5.0) 2018-10-12 b2f694c Java HotSpot(TM) 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 +jit [linux-x86_64]

script
```ruby
100.times do
  t = Thread.new do
    Kernel.sleep
    :ok
  end

  JRuby.reference(t).native_thread.interrupt
  t.value
end
```

JRuby.reference(t).native_thread.interrupt should stop the thread
```ruby
  t = Thread.new do
    Kernel.sleep
    :ok
  end

  JRuby.reference(t).native_thread.interrupt
  => #<Thread:0x69aabcb0@(irb):31 dead>
```

under load (if I run it in a loop), some threads sometimes remain still in a sleep state
```ruby
=> #<Thread:0x2dfeb141@(irb):39 sleep>
```

t.value calls Thread#join and because the thread is alive, it sleeps forever

https://github.com/jruby/jruby/blob/66d2905ae233a39e36fcbe3ade6382c2892ade8e/core/src/main/java/org/jruby/RubyThread.java#L1077

### Expected Behavior
it looks like there's a race condition somewhere? If I add a sleep call between Thread.new and thread.interrupt it won't hang. Or is it just a bad test?

```ruby
100.times do
  t = Thread.new do
    Kernel.sleep
    :ok
  end

  sleep 0.25
  JRuby.reference(t).native_thread.interrupt
  t.value
end
```

### Actual Behavior
hangs in an infinite loop

https://travis-ci.org/jruby/jruby/jobs/440880330
```
....
     [exec] Kernel#sleep
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by headius** [comment]
Have you confirmed that the thread is actually sleeping before you try to interrupt it? The race here is that the thread may or may not have actually called sleep, so the interrupt call might happen when it's just running the preamble code for the block. It's possible the thread hasn't even been *scheduled* yet by the time you call interrupt.

**Comment by ahorek** [comment]
> It's possible the thread hasn't even been scheduled yet by the time you call interrupt.

I think this is the case

```
100.times do
  t = Thread.new do
    Kernel.sleep
    :ok
  end

  sleep 0.25
  puts t.status

  JRuby.reference(t).native_thread.interrupt
  t.value
end
```
=>
sleep
sleep
sleep
sleep
....

```
100.times do
  t = Thread.new do
    Kernel.sleep
    :ok
  end

# sleep 0.25
  puts t.status

  JRuby.reference(t).native_thread.interrupt
  t.value
end
```
=>
run
run
run
run
hangs

**Comment by headius** [comment]
Since that's the case...is there really anything to fix? You are basically interrupting the sleep before it happens. If you wait for status == sleep it should work better, I believe.

Let us know if you believe there's something more we should be doing in JRuby for this case.

**Comment by ahorek** [comment]
no, I think the behaviour is ok, but the test is wrong.

if the thread isn't scheduled yet, it'll cause random failures like this
https://travis-ci.org/jruby/jruby/jobs/440880330

the test should wait until the thread is ready before calling
JRuby.reference(t).native_thread.interrupt
otherwise it hangs

makes sense? @headius ?

**Comment by headius** [comment]
Oh, somehow I missed that you were debugging a test hang. Yes, I agree the test should be fixed.
