### ISSUE TITLE
Method parameter and local variable values isn't passed to a block executed inside ensure from v9.2.1.0

### ISSUE THREAD

**Issue by jbaiza** [jruby/jruby#5434]
Inside our code we use `Concurrent::AtomicReference.update` (http://ruby-concurrency.github.io/concurrent-ruby/master/Concurrent/AtomicReference.html#update-instance_method) method to change the value of a given variable. Starting from JRuby 9.2.1.0 the code fails - method parameter and local variable values isn't passed to a block executed inside ensure.
I managed to simplify the code to get rid of gem dependencies - https://gist.github.com/jbaiza/af626e00ff13732b4e1007c6c9b24050.

### Environment

Tried 2 different configuration - **macOS Mojave**:
* JRuby version (jruby -v) and command line (flags, JRUBY_OPTS, etc)
```
jruby 9.2.1.0 (2.5.0) 2018-11-06 7b14404 Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 +jit [darwin-x86_64]
```
* Operating system and platform (e.g. uname -a)
```
Darwin JBA-MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
```

and **Ubuntu**:
* JRuby version (jruby -v) and command line (flags, JRUBY_OPTS, etc)
```
jruby 9.2.1.0 (2.5.0) 2018-11-06 7b14404 OpenJDK 64-Bit Server VM 10.0.2+13-Ubuntu-1ubuntu0.18.04.3 on 10.0.2+13-Ubuntu-1ubuntu0.18.04.3 +jit [linux-x86_64]
```
* Operating system and platform (e.g. uname -a)
```
Linux 033a88b50ae3 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Other relevant info you may wish to add:
* Installed or activated gems
N/A
* Application/framework version (e.g. Rails, Sinatra)
N/A
* Environment variables
N/A

### Expected Behavior

The code sample is successfully executed (as in versions before JRuby 9.2.1.0)
From macOS:
```
$ jruby jruby_9210_parameter_passing.rb
TEST: BEFORE UPDATE 0.000262
TEST: INSIDE UPDATE 0.000262
```

From Ubuntu:
```
# jruby jruby_9210_parameter_passing.rb
TEST: BEFORE UPDATE 0.00041799999999999997
TEST: INSIDE UPDATE 0.00041799999999999997
```

### Actual Behavior

The code sample returns an error if JRuby 9.2.1.0 or 9.2.2.0 is used.
From macOS:
```
$ jruby jruby_9210_parameter_passing.rb
TEST: BEFORE UPDATE 0.000234
: INSIDE UPDATE
TypeError: nil can't be coerced into Float
        + at org/jruby/RubyFloat.java:318
  process at jruby_9210_parameter_passing.rb:19
   update at jruby_9210_parameter_passing.rb:7
  process at jruby_9210_parameter_passing.rb:17
   <main> at jruby_9210_parameter_passing.rb:23
```

From Ubuntu:
```
# jruby jruby_9210_parameter_passing.rb
TEST: BEFORE UPDATE 0.000396
: INSIDE UPDATE
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper$ReflectiveAccess to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper$ReflectiveAccess
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
TypeError: nil can't be coerced into Float
        + at org/jruby/RubyFloat.java:318
  process at jruby_9210_parameter_passing.rb:19
   update at jruby_9210_parameter_passing.rb:7
  process at jruby_9210_parameter_passing.rb:17
   <main> at jruby_9210_parameter_passing.rb:23
```

**Comment by enebo** [comment]
I just tried this with 9.2.3.0 and this is now working:

```text
jruby ../snippets/param1.rb 
TEST: BEFORE UPDATE 0.000268
TEST: INSIDE UPDATE 0.000268
```

Please re-open if you see something else with 9.2.3.0.

**Comment by jbaiza** [comment]
Tried out 9.2.3.0 - the problem is fixed, tnx!
