### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#5450]
### Environment
```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

### Actual behaviour
`rvm get head`

raises an error
```
    Installing rvm gem in 1 gemsetsUnhandled Java exception: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
           encode at org/jruby/RubyEncoding.java:306
     doEncodeUTF8 at org/jruby/RubyEncoding.java:197
   encodeBytelist at org/jruby/RubyString.java:6191
           <init> at org/jruby/RubyString.java:377
        newString at org/jruby/RubyString.java:468
        newString at org/jruby/Ruby.java:3563
  createFileClass at org/jruby/RubyFile.java:219
         initCore at org/jruby/Ruby.java:1547
        bootstrap at org/jruby/Ruby.java:1318
             init at org/jruby/Ruby.java:1217
      newInstance at org/jruby/Ruby.java:362
      internalRun at org/jruby/Main.java:273
              run at org/jruby/Main.java:234
             main at org/jruby/Main.java:206
```

the problem is that I have a jruby's binary that was compiled with java 9, but executed with java 8.

### Expected behaviour
this should be a workaround
https://jira.mongodb.org/browse/JAVA-2559
https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyEncoding.java#L306

**Comment by kares** [comment]
should be easy to put up a PR ... mostly about: `((Buffer) buf).clear();` with a comment why its there.

**Comment by headius** [comment]
Hmm that is harder to avoid ☹️ If we wrap this in another method we may interfere with the VM intrinsic used to optimize these methods.

These cases should be pretty limited, though...we can just cast everything to long in those few places.

I hope there aren't going to be too many more of these; we are not ready to start depending on Java 11. Maybe we need to look into the build using JDK8 runtime library.

**Comment by headius** [comment]
Ok I looked into the Java 9+ -release flag for javac, and it gets us halfway there. If you specify `-release 8` it will only compile against Java 8 APIs, which should solve all these cases in one swoop. Unfortunately, it also does not expose unsupported APIs like all of `sun.misc` from which we get signal-handling and Unsafe classes. So this might be a dead end, unless we can eliminate all uses of sun.misc in our main codebase (might be able to move to another library).

**Comment by headius** [comment]
@enebo We might be able to get the `-release 8` flag to work if we reincorporate mock libraries for Unsafe and the whole SignalHandler stuff in sun.misc.

**Comment by kares** [comment]
resolved by https://github.com/jruby/jruby/commit/62dc58b6d1bfdc825386721d7ea313895deab3d6 (and some previous commits actually)
