### ISSUE TITLE
Weird `Kernel.autoload` behavior

### ISSUE THREAD

**Issue by MaxLap** [jruby/jruby#5466]
### Environment

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
  `jruby 9.2.5.0-SNAPSHOT (2.5.0) 2018-11-22 93f0df3 OpenJDK 64-Bit Server VM 25.181-b13 on 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13 +jit [linux-x86_64]`
* Operating system and platform (e.g. `uname -a`)
  Ubuntu 16.04
  `Linux max-u1604 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### Problem

I expect `Kernel.autoload :Hi, 'somefile'` to do something useful. Right now, the only way found to trigger that autoload is do call `.singleton_class::Hi` on any class (It can be `String`, `Object`, etc). I really doubt there is any usecase for this.

In MRI, `Kernel#autoload` and `Kernel.autoload` always use the `Module.nested` of the calling context. 

In JRuby, `Kernel#autoload` uses the object of the calling code. (This difference only shows up if the `autoload` call is in an instance method of a module, which is included in a class, and the method is called from an instance of the class.. Not something to worry about)

However, JRuby seems to special case `Kernel.autoload` weirdly. Looking at the code:
https://github.com/jruby/jruby/blob/93f0df32f2c77e2fbc4929a5b01771ef85a47b25/core/src/main/java/org/jruby/RubyKernel.java#L222-L223

Ideally, `Kernel.autoload` would behave the same as calling `Kernel#autoload`.

**Comment by headius** [comment]
We do not currently support this behavior of MRI because it requires `autoload` to be able to inspect the caller's frame. In JRuby that capability must be explicitly added to a "native" method, and it causes any code that calls the given method name to deoptimize in some way.

It's probably fine to add this capability to our autoload since it's primarily used at boot, in class bodies, and usually only once for a given constant.

**Comment by headius** [comment]
The code snippit you showed basically tries to set the autoload on the singleton class of Object, since it's assuming if you call `Kernel.autoload` directly you want to set a global autoload, rather than an autoload scoped to the caller's module nesting.

**Comment by MaxLap** [comment]
From testing locally, `Kernel.autoload` doesn't seem to do what you say.

```
> Kernel.autoload :Hi, 'something'
> Object.constants.include?(:Hi)
 => false
> Object::Hi
NameError (uninitialized constant Hi)
> Hi
NameError (uninitialized constant Hi)
> ::Hi
NameError (uninitialized constant Hi)
> Object.singleton_class::Hi # Only way to trigger it, works for other classes, ex: String.singleton_class::Hi
LoadError (no such file to load -- something)
```

I don't think `Kernel.autoload` is used frequently, but it just seems like such a weird behavior that I decided to report it. 

I am very confused that this test passes (i'm assuming it does), but I don't have the time to investigate:

https://github.com/jruby/jruby/blob/ebbb75026757e17613c3fd754e706c7e349f0b72/spec/ruby/core/kernel/autoload_spec.rb#L121-L123

**Comment by headius** [comment]
Yeah, I don't want to claim that what we do is right. The constant search against Object won't see Object's singleton class, so this all looks "correct" to me ("correct" as in it does what I'd expect from the code.

And the spec you point out does not pass... https://github.com/jruby/jruby/blob/25823b3b318a55e84c61b7c3dd2893030c63976c/spec/tags/ruby/core/kernel/autoload_tags.txt#L1-L0

**Comment by headius** [comment]
My mistake...adding access to caller's class in Kernel.autoload will cause Module#autoload to need access too, since we base that decision on the name of the method. But I think it's still fine; autoload is typically used at boot, within a class body; in the former case we're almost always in the interpreter with full frames, and in the latter case we always provide a frame.

**Comment by headius** [comment]
Did not make 9.2.6, hopefully next one.

**Comment by headius** [comment]
With the changes in #5764, this appears to be working as you expect:

```
$ irb
irb(main):001:0> Kernel.autoload :Hi, 'something'
=> nil
irb(main):002:0> Object.constants.include?(:Hi)
=> true
irb(main):003:0> Object::Hi
Traceback (most recent call last):
       10: from /Users/headius/projects/jruby/bin/irb:23:in `<main>'
        9: from org/jruby/RubyKernel.java:1049:in `load'
        8: from /Users/headius/projects/jruby/lib/ruby/gems/shared/gems/irb-1.0.0/exe/irb:11:in `<main>'
        7: from org/jruby/RubyKernel.java:1234:in `catch'
        6: from org/jruby/RubyKernel.java:1234:in `catch'
        5: from org/jruby/RubyKernel.java:1504:in `loop'
        4: from org/jruby/RubyKernel.java:1088:in `eval'
        3: from (irb):3:in `evaluate'
        2: from /Users/headius/projects/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85:in `require'
        1: from org/jruby/RubyKernel.java:1014:in `require'
LoadError (no such file to load -- something)
```

I do not have a "something.rb" in load path but it is clearly finding the autoload constant and attempting to load the file.
