### ISSUE TITLE
Update ERB stdlib from MRI 2.5.0 to at least 2.5.1

### ISSUE THREAD

**Issue by presidentbeef** [jruby/jruby#5479]
### Environment

jruby 9.2.4.0 (2.5.0) 2018-11-13 8faff06 Java HotSpot(TM) 64-Bit Server VM 10.0.1+10 on 10.0.1+10 +jit [darwin-x86_64]

### Issue

JRuby 9.2.4.0 uses the stdlib version of ERB from MRI 2.5.0. Unfortunately, that version introduced a backwards-incompatible change, as documented in https://redmine.ruby-lang.org/issues/14243. The change was reverted in MRI 2.5.1.

FWIW I tried the [current trunk version of ERB](https://github.com/ruby/ruby/blob/ab5a3db48e446a33f790fa5e8594a6dc24062987/lib/erb.rb) instead and it seemed to work fine with JRuby 9.2.4.0.

I'm not sure what the JRuby policy is for updating the stdlib, but I'm guessing it's to match the compatibility version that's reported with `jruby -v`. That would rule out just updating ERB to the 2.5.1 version.

So I suppose this ticket is just a little bit of motivation to update to the latest 2.5.x stdlib :)

**Comment by headius** [comment]
@presidentbeef So you're saying that 2.5.1 has the fix? I agree, we should do a stdlib update for 9.2.6 (9.2.5 already has a lot of fixes in it) to the latest 2.5.x stdlib.

Need to figure out a better policy here...maybe I can get our patches into the MRI repo so we can just source stdlib directly from.there.

**Comment by presidentbeef** [comment]
Yes, that's correct: 2.5.1 has the fix.

I was tracking down why I was having test failures with JRuby and I realized it was the same bug I had already seen and reported with MRI. It's *only* in 2.5.0.

**Comment by headius** [comment]
Gotcha, thanks. We will roll stdlib to latest 2.5.x (and gems, if there's updates) for 9.2.6 some time in December. I'll start that soon...if it looks like not-too-many changes it might make 9.2.5.

**Comment by headius** [comment]
This has been fixed in jruby/jruby#5505 and which was merged to master in d03c357. JRuby 9.2.6 will ship with Ruby 2.5.3 stdlib. We also fixed all relevant test failures in the updated MRI test suite, mostly outside of stdlib (in core).
