### ISSUE TITLE
Class names are mutable

### ISSUE THREAD

**Issue by remofritzsche** [jruby/jruby#5480]
### Environment

* `jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.172-b11 on 1.8.0_172-b11 +jit [darwin-x86_64]`
* `Darwin albus.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64`

### Expected Behavior (MRI 2.5)

```
irb(main):001:0> class Foo; end
=> nil
irb(main):002:0> Foo.name
=> "Foo"
irb(main):003:0> Foo.name << 'bla'
=> "Foobla"
irb(main):004:0> Foo.name
=> "Foo"
```

### Actual Behavior (jRuby 9.2.0.0)

```
jirb(main):001:0> class Foo; end
=> nil
jirb(main):002:0> Foo.name
=> "Foo"
jirb(main):003:0> Foo.name << 'bla'
=> "Foobla"
jirb(main):004:0> Foo.name
=> "Foobla"
```

**Comment by headius** [comment]
Oops!
