### ISSUE TITLE
FileUtils.chmod failes when called on symlink under linux

### ISSUE THREAD

**Issue by kschoelhorn** [jruby/jruby#5547]
Calling `FileUtils.chmod` on a symlink tries to call `File.lchmod` if available. It checks this by calling `File.lchmod` with an empty file list. This succeeds, because `POSIX.lchmod` is not actually called in this case:
https://github.com/jruby/jruby/blob/d03c357cef56ff2935fdb1c3d534d7286d5286cc/core/src/main/java/org/jruby/RubyFile.java#L1010-L1026

This leads to the following error, because `lchmod` does not exist under linux:
```
NotImplementedError: No message available
  lchmod at org/jruby/RubyFile.java:1019
   chmod at /data/software/jruby/9.2.5.0/lib/ruby/stdlib/fileutils.rb:1320
   chmod at /data/software/jruby/9.2.5.0/lib/ruby/stdlib/fileutils.rb:1000
    each at org/jruby/RubyArray.java:1792
   chmod at /data/software/jruby/9.2.5.0/lib/ruby/stdlib/fileutils.rb:999
  <main> at ./test.rb:15
```

This is the test program I used, which includes a workaround that makes sure `File.lchmod` is not considered available:
```ruby
#!/usr/bin/env jruby

require 'fileutils'

# uncomment to fix NotImplementedError
# class FileUtils::Entry_
#   def have_lchmod?
#     false
#   end
# end

FileUtils.rm_f "link"
FileUtils.ln_s "target", "link"

FileUtils.chmod 400, "link"
```

I am using jruby 9.2.5.0 under RHEL 7.4.

**Comment by headius** [comment]
It looks like CRuby defines lchmod as an unimplemented method when it's not available; I'll modify the way we define our version to follow suit.
