### ISSUE TITLE
Binary packages are missing again

### ISSUE THREAD

**Issue by BanzaiMan** [jruby/jruby#5551]
### Environment

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
* Operating system and platform (e.g. `uname -a`)

Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables

RVM installation from S3 fails.

    rvm use jruby-9.1.14 --install --binasry --fuzzy

### Expected Behavior

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.
* Provide an executable Ruby script or a link to an example repository.

Installation succeeds

### Actual Behavior

* Describe or show the actual behavior.
* Provide text or screen capture showing the behavior.

It fails.

<details>
<summary>RVM install output</summary>
<pre>
travis@9abf2a311a96:~$ rvm use jruby-9.1.14 --install --binary --fuzzy
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Required jruby-9.1.14 is not installed - installing.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Searching for binary rubies, this might take some time.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm jruby-9.1.14 do rvm gemset create ' first, or append '--create'.
</pre>
</details>

RVM should find the binary archive from S3, but it is not there.

<details>
<summary>--debug output</summary>
<pre>
travis@9abf2a311a96:~$ rvm use jruby-9.1.14 --install --binary --fuzzy --debug
__list_remote_all https://rvm_io.global.ssl.fastly.net/binaries ubuntu/14.04/x86_64
__list_remote_for_local found
__list_remote_all1 https://s3.amazonaws.com/jruby.org downloads
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://s3.amazonaws.com/jruby.org/index.txt --insecure
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://s3.amazonaws.com/jruby.org/downloads/index.txt --insecure
__list_remote_for_s3-0 https://s3.amazonaws.com/jruby.org?prefix=downloads/
Running(15): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -s https://s3.amazonaws.com/jruby.org?prefix=downloads/
__list_remote_for_s3-1 https://s3.amazonaws.com/jruby.org?prefix=downloads/&marker=downloads/9.2.4.1/jruby-complete-9.2.4.1.jar.md5
Running(15): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -s https://s3.amazonaws.com/jruby.org?prefix=downloads/&marker=downloads/9.2.4.1/jruby-complete-9.2.4.1.jar.md5
__list_remote_all2 https://rubies.travis-ci.org ubuntu/14.04/x86_64
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rubies.travis-ci.org/index.txt --insecure
__list_remote_for_index https://rubies.travis-ci.org/index.txt
Running(15): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -s https://rubies.travis-ci.org/index.txt
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rubies.travis-ci.org/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://rubies.travis-ci.org/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz
rvm_remote_server_url3 not found
No remote file name found
Required jruby-9.1.14 is not installed - installing.
jruby-9.1.14 - install
__list_remote_all https://rvm_io.global.ssl.fastly.net/binaries ubuntu/14.04/x86_64
__list_remote_for_local found
__list_remote_all1 https://s3.amazonaws.com/jruby.org downloads
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://s3.amazonaws.com/jruby.org/index.txt --insecure
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://s3.amazonaws.com/jruby.org/downloads/index.txt --insecure
__list_remote_for_s3-0 https://s3.amazonaws.com/jruby.org?prefix=downloads/
Running(15): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -s https://s3.amazonaws.com/jruby.org?prefix=downloads/
__list_remote_for_s3-1 https://s3.amazonaws.com/jruby.org?prefix=downloads/&marker=downloads/9.2.4.1/jruby-complete-9.2.4.1.jar.md5
Running(15): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -s https://s3.amazonaws.com/jruby.org?prefix=downloads/&marker=downloads/9.2.4.1/jruby-complete-9.2.4.1.jar.md5
__list_remote_all2 https://rubies.travis-ci.org ubuntu/14.04/x86_64
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rubies.travis-ci.org/index.txt --insecure
__list_remote_for_index https://rubies.travis-ci.org/index.txt
Running(15): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -s https://rubies.travis-ci.org/index.txt
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rubies.travis-ci.org/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://rubies.travis-ci.org/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz
rvm_remote_server_url3 not found
No remote file name found
jruby-9.1.14 - #already removed src/jruby-9.1.14
jruby-9.1.14 - #already removed rubies/jruby-9.1.14
Searching for binary rubies, this might take some time.
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rubies.travis-ci.org/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://rubies.travis-ci.org/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz
rvm_remote_server_url3 not found
No remote file name found
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz
Unknown ruby string (do not know how to handle): jruby-9.1.14.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rubies.travis-ci.org/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz --insecure
Remote file does not exist https://rubies.travis-ci.org/ubuntu/14.04/x86_64/9.1.14/jruby-bin-9.1.14.tar.gz
rvm_remote_server_url3 not found
No remote file name found
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm jruby-9.1.14 do rvm gemset create ' first, or append '--create'.
__rvm_rm_rf already gone: /home/travis/.rvm/tmp/291*
</pre>
</details>

Indeed, https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz returns a 404.

```
travis@9abf2a311a96:~$ curl -IL https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz
HTTP/1.1 404 Not Found
x-amz-request-id: 3C493B841547F5DE
x-amz-id-2: mUx9UVufIJN4oQfunEx+38nE76aLPw5Nq+udoA3PPXhM+SzBJ0ILBRXLk2xR1IRHy5mcW9uQGqc=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Tue, 08 Jan 2019 17:13:06 GMT
Server: AmazonS3
```

This is similar to #4789.

https://travis-ci.community/t/unable-to-install-jruby-9-1-14-and-latter-via-rvm/1724

**Comment by BanzaiMan** [comment]
Hmm. The files are now provided from maven.org? https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.1.14.0/jruby-dist-9.1.14.0-bin.tar.gz

**Comment by BanzaiMan** [comment]
The latest RVM is aware of the new archive. I'll fix this with travis-build.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/1635 fixes it for Travis CI.

**Comment by headius** [comment]
Hmm...we should still be pushing to S3, but yes the maven central way is preferred.

**Comment by headius** [comment]
@enebo Are all releases 9.1+ still being pushed to S3?

**Comment by headius** [comment]
@BanzaiMan Thanks for taking care of that on Travis's end 🎉

**Comment by enebo** [comment]
@headius @BanzaiMan yes...they do exist on s3.  I am not sure what travis/rvm is doing but:

```text
Indeed, https://s3.amazonaws.com/jruby.org/downloads/9.1.14/jruby-bin-9.1.14.tar.gz returns a 404.
```

is not the name of our release or is a valid url.  It is 9.1.14.0.  Although if 9.1.14.0 works from the maven source it is definitely the preferred one.
