### ISSUE TITLE
float format-ing regression in 9.2

### ISSUE THREAD

**Issue by kares** [jruby/jruby#5556]
```
ruby -e 'n = 97.65625; puts format("%f %f %.1f", n, n.round(1), n)'
```
Ruby 2.3, 2.5 and JRuby 9.1.17.0
```
97.656250 97.700000 97.7
```
JRuby 9.2.5.0
```
97.656250 97.700000 97.6
```
... discovered at *image_optim*'s: https://github.com/toy/image_optim/pull/168

**Comment by lassiter** [comment]
Hi, @kares. Can I take this issue? I'd love to have the opportunity to contribute.

**Comment by kares** [comment]
yes please - that would be great if you took a detailed look.
if you start around `RubyKernel.format` and follow around where it leads to ... also if you get stuck bisecting should point you to a commit that regressed.

**Comment by lassiter** [comment]
So, I think I know which method (`rubySprintfToBuffer` in [Sprintf.java](https://github.com/jruby/jruby/compare/9.1.17.0...9.2.0.0#diff-b75708650b99f06adfa2b1a269064787)) is the cause of the error but it's unclear on exactly where inside is wrong. I finally got Eclipse running with the debugger and will know more soonish. I've got a test written so I have something to run against in the unit test folder.

Java is brand new to me, so it's a little to getting used too. This is my first time working with the language.

**Comment by kares** [comment]
well done, yeah it might be hard to tell from all the commits 
... maybe try disabling 'new' parts that seem [suspicious](https://github.com/jruby/jruby/compare/9.1.17.0...9.2.0.0#diff-b75708650b99f06adfa2b1a269064787R1573) otherwise bisecting is your friend.
alternatively, since you're suspecting, a change in `Sprintf.java` ... try confirming that by replacing it with code from 9.1.17's version, where possible ...

**Comment by lassiter** [comment]
I've tried that but then I get a compile error. So far using bisecting, I've gotten it down to 9 commits based on my assumption but these are the ones I'm interested in most. Also, while bisecting, I get a lot of compile errors when I run `mvn -Pbootstrap` to run the current state against my test (second code block); So, I'm not sure exactly how to test those changes. Any ideas?

```
commit 49a74b95fbd7a00a22cdeb0a1a25192c196ecd55
Author: Miguel Landaeta <miguel@miguel.cc>
Date:   Sun Mar 25 14:26:50 2018 +0100

    Kernel#sprintf must raise ArgumentError on dangling '%' chars in format string since Ruby 2.5

commit 6a543f192ff9f770b37b23eb0c61ba2b67cede5d
Author: Miguel Landaeta <miguel@miguel.cc>
Date:   Fri Jan 5 16:37:49 2018 +0000

    Implement KeyError#receiver and KeyError#key

    For more information, please see feature #12063.

commit 056ec1ed7fdbd6054438fa0089899e8715b4d2dd
Author: kares <self@kares.org>
Date:   Tue Aug 8 11:47:10 2017 +0200

    new_float checks Float + compare bits directly instead of alloc.floats

commit 68ea9a33bf51e475ba4aab47cf3c7dfefba0409f (HEAD)
Author: kares <self@kares.org>
Date:   Tue Aug 8 11:12:24 2017 +0200

    depreacate and cleanup/simplify RubyKernel.new_float19 usage

commit bc2ba39ed88096f0d3557231e10bb22a84ee9508
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Mon Jul 31 10:00:38 2017 -0500

    [2.4] sprintf now rounds half to even.

    See https://bugs.ruby-lang.org/issues/12889

commit 472599c2c29dcb8c8d4abe1b4a932bbbb3b00671
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Wed Jul 12 17:44:40 2017 -0500

    Additional tweaks and re-ports for Float#round and friends.

commit b3c5bad9e1cecf18c586dfe9bb4dd5108de8d516
Merge: 4633080753 3a91f9e7d3
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Thu Jul 6 15:45:12 2017 -0500

    Merge branch 'master' into ruby-2.4

commit 5e779b50b9dd72726e8ccc82d855c100bac5b4e2
Author: kares <self@kares.org>
Date:   Wed Jun 28 16:34:14 2017 +0200

    fix warning on var init; prefer local runtime var; avoid stringToInum19

commit 39155ec2a841bc9d4cbc46bc9b04b45df0d3b919
Merge: cd0b9db083 fb4276238b
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Tue Mar 14 16:10:42 2017 -0500

    Merge remote-tracking branch 'origin/master' into ruby-2.4

commit b3b5d1172b92788c2c8beebcfc9e619cd98df17f
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Mon Nov 21 18:49:54 2016 -0600

    Test physical type before casting blindly.

commit a103596f667cfb5158568b6c96ec5bb43e53924b
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Thu Nov 17 09:13:29 2016 -0600

    Eliminate expectation of FIXNUM or BIGNUM from class index.

commit 4dd37024b366c088fc79400fbe1a6142529305d9
Author: Charles Oliver Nutter <headius@headius.com>
Date:   Thu Nov 17 00:53:26 2016 -0600

    Start eliminating Fixnum and Bignum in favor of Integer. #4293
```

```
require 'test/unit'

class TestFormat < Test::Unit::TestCase
  # Test Case based on https://github.com/jruby/jruby/issues/5556
  def test_sprintf_one
    n = 97.65625
    s = format("%f %f %.1f", n, n.round(1), n).to_s
    assert(s === "97.656250 97.700000 97.7", "Test failed, value of #{s} did not match '97.656250 97.700000 97.7'.")
  end
end
```

**Comment by kares** [comment]
hey @lassiter, great find - seems like the removal makes sense, at least as a starter, here.
would propose as a PR and than we can review the current C-code from there for comparison.
