### ISSUE TITLE
org.jruby.RubyTime can no longer be compared to java.util.Date (9.1.0.0 onwards)

### ISSUE THREAD

**Issue by betesh** [jruby/jruby#5570]
```
$ rvm jruby 9.0.5.0 do ruby -e "puts java.util.Date.new(2018,3,1) > Time.new(2018,2,1)"
true
$ rvm jruby 9.1.0.0 do ruby -e "puts java.util.Date.new(2018,3,1) > Time.new(2018,2,1)"
TypeError: org.jruby.RubyTime cannot be cast to java.util.Date
      > at org/jruby/RubyComparable.java:166
  <top> at -e:1
```

### Environment

* JRuby version: All versions from 9.1.0.0 onwards

* Operating system and platform:
```
$ uname -a
Linux 4.17.0-041700-generic #201806041953 SMP Mon Jun 4 19:55:25 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Expected Behavior

When I compare a Ruby Time object to a `java.util.Date`, I expect it to work the same was as it did in jruby 9.0, by comparing the 2 objects and returning either true or false.

### Actual Behavior

It raises a TypeError, as in the example above.

**Comment by kares** [comment]
yes, you were able to do that on 1.7 and up to 9.0 but that does not mean it wasn't a bug, try : 
```
$ jruby -e "puts java.util.Date.new(2000,1,1) > Time.new(2018,2,1)"
true
$ jruby -e "puts java.util.Date.new(2010,1,1) > Time.new(2018,2,1)"
true
```
... current behaviour also seems consistent with stricter `<=>` rules 
while you can to_java (coerce) a `Time` into a `java.util.Date` it does not imply comparability
e.g. you can not compare `Time` with `DateTime` in ruby (2.5) :
```
ruby -e "require 'date'; puts DateTime.new(2010,1,1) > Time.new(2018,2,1)"
Traceback (most recent call last):
	1: from -e:1:in `<main>'
-e:1:in `>': comparison of DateTime with Time failed (ArgumentError)
```

**Comment by kares** [comment]
on the Java level (passing a `org.jruby.RubyTime` into a Java method), it might be interesting to know whether `java.util.Date` could be mixed with the Java 8 time types, one likely needs to explicitly convert first. the thing we could do is implement some of the interfaces e.g. `Instant` but than since we auto cast when seeing a proper type signature that seems also useless.
