### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by cpuguy83** [jruby/jruby#5598]
I have been maintaining a jruby image for the "official" docker images program (https://github.com/docker-library/official-images) for several years now.
These are being built from https://github.com/cpuguy83/docker-jruby.

Unfortunately I have not really been part of the Ruby community in quite some time and am rather disconnected, and even more so with the Java community.

Recent changes with [bundler 2.0](https://github.com/cpuguy83/docker-jruby/issues/43) highlight this.
There's also some things that I really don't have the bandwidth or know-how to investigate: https://github.com/cpuguy83/docker-jruby/issues/42 https://github.com/cpuguy83/docker-jruby/issues/37

Wanted to reach out and see if you'd be up to taking over maintenance for this, perhaps as part of your release process.

Let me know, thanks!

**Comment by cpuguy83** [comment]
ping @headius

**Comment by headius** [comment]
Yes, I think it's time. Can you hold our hand and show us how to make an officially official jruby image?

**Comment by cpuguy83** [comment]
>  Can you hold our hand and show us how to make an officially official jruby image?

Gladly. I'll start off by linking the contributing docs: https://github.com/docker-library/official-images/#contributing-to-the-standard-library

The basic flow is I keep a set of build instructions (in Dockerfiles) in https://github.com/cpuguy83/docker-jruby.

Then in https://github.com/docker-library/official-images there is a manifest in library/jruby which contains all the supported versions/platforms.

In the manifest are several stanzas:

https://github.com/docker-library/official-images/blob/885bfe7d277d52837bc84e303d5b947bc83d75d7/library/jruby#L2-L4

This is the main section that sets all the "default" (for lack of a better word) values, which can all be overwritten in each section.

Then each section relates to a (docker image) tag:
https://github.com/docker-library/official-images/blob/885bfe7d277d52837bc84e303d5b947bc83d75d7/library/jruby#L6-L8

Tags in this case are incorporated in the name of the image... so someone can pull `jruby:9` `jruby:9.2`, `jruby:9.2.7`, or `9.2.7.0` and these would all be pointing at the same image content.

There are variants for both jdk and jre, as well as alpine Linux (no `-alpine` is debian based).
 
The official images team is responsible for taking the manifest and building/pushing the images for each specified platform.

---

Happy to jump on a call or whatever to discuss, answer questions, etc.

/cc @tianon

**Comment by headius** [comment]
Busy time of year...when were you hoping to drop your support? After RailsConf next week we'll have more cycles to take this over.

**Comment by cpuguy83** [comment]
Whenever you have some cycles.

**Comment by lopex** [comment]
@cpuguy83 what are the steps necessary so we can take over docker image management ?

**Comment by headius** [comment]
@cpuguy83 Our friend @lopex is willing to take responsibility for the JRuby image...hopefully you can connect up with him on IRC or Matrix or whatever and hand off the relevant bits!

**Comment by cpuguy83** [comment]
Thanks! I'm taking some time off until September. Hope we can sync up then?

**Comment by lopex** [comment]
@cpuguy83 Hi there!, pinging you so we can sync up again :)

**Comment by cpuguy83** [comment]
@lopex Definitely let's discuss. When are you usually online?
I can certainly start by giving you push access to the existing repo and we can go from there.

**Comment by fidothe** [comment]
Going over Docker's docs for 'official images' it sounds like the primary steps needed to do a hand over and maintain the existing images (which Docker is very keen on) would be to:

1. Fork https://github.com/cpuguy83/docker-jruby to the jruby org. (Docker want you to maintain the existing commit history when taking over maintainership of a project)
2. Notify Docker of the change in maintainership
3. Submit a PR to https://github.com/docker-library/official-images repointing the `GitRepo` field in the `library/jruby`

How step 2 is accomplished isn't immediately clear. The docs mention a `docker-library-transitioner` tool for performing steps 1 and 2 that doesn't seem to actually exist. I guess it's a matter of @cpuguy83 opening an issue on `docker-library/official-images`?

**Comment by fidothe** [comment]
The official image docs I found are here: https://github.com/docker-library/official-images/blob/master/README.md and here: https://docs.docker.com/docker-hub/official_images/

**Comment by tianon** [comment]
I wouldn't recommend a fork, perse (since GitHub does weird things with forks) -- I'd recommend having @cpuguy83 transition the repo directly to your org -- the "docker-library-transitioner" mentioned there is just https://github.com/docker-library-transitioner which we can temporarily give all parties admin access to in order to facilitate the transfer, but I think GitHub got better in the meantime about allowing direct repo transfers without admin access (because @cpuguy83 is a great guy and I'm happy to vouch for his credibility, but all that notwithstanding you probably don't want to give him admin access to the jruby org :sweat_smile:).

At a minimum we'd request you keep the commit history (which could just be pull / push), but keeping the issue history intact would be nice too, so a proper repo move is the best bet.

The second step is just to update `Maintainers:` in that same PR as the third step (https://github.com/docker-library/official-images/blob/658d421367e74d33bafabb6275c50c50c46095e9/library/jruby#L1).

**Comment by lopex** [comment]
@fidothe @tianon thanks for the info, I'll jave to digest that for the moment.
@cpuguy83 are you affiliated with them just in case ?

**Comment by pavolzbell** [comment]
@lopex Hello, what is the current state of this issue? We would like to easily run the latest JRuby on possibly the latest Java in our projects so maybe I could help somehow with this. Let me know, thanks.

**Comment by headius** [comment]
The current situation is that the active JRuby committers have basically zero knowledge of how to maintain a Docker image. I think once we get the right expertise in place, probably via community assistance, the transition should go very quickly.

In short, help wanted!

**Comment by jsuchal** [comment]
@headius Looks like @cpuguy83 recently (4 days ago) added support for multiple java versions. https://github.com/cpuguy83/docker-jruby/tree/master/9000

I assume @cpuguy83 still wants to move the maintenance to JRuby org, right?

**Comment by cpuguy83** [comment]
I think it's best, particularly since I'm not part of the ruby or jruby community at this point outside of maintaining that image.

**Comment by headius** [comment]
@cpuguy83 We thank you again for your help here... sorry this has taken a year to get resolved, but I think we have a few volunteers now.

**Comment by headius** [comment]
@cpuguy83 I am going to invite you to transfer your repo to the jruby organization, so you will get some notifications about whatever these buttons do.

**Comment by headius** [comment]
Rather than make a hard break with the original repo, I've instead forked to https://github.com/jruby/docker-jruby

**Comment by jsuchal** [comment]
@headius probably the best way to do this would be to create a new temp org, give @cpuguy83 admin rights, he moves the repo ownership, then you move the repo ownership to jruby and we should be done.

**Comment by fidothe** [comment]
Looking back at the comment from @tianon above (https://github.com/jruby/jruby/issues/5598#issuecomment-554098644) we should avoid a fork and transfer if at all possible. Per that comment, Docker provide a specific empty org for helping with the transfers (if we need that). I'd also be willing to take on some of this - I have already packaged multiple java versions and jruby versions as Docker images for CI/CD on a project of mine...

**Comment by tianon** [comment]
Yep, doing a proper transfer has the benefit of transferring not just open issues/PRs, but also all the issue history, and GitHub will maintain redirects for the old URLs (as long as @cpuguy83 doesn't then create a new repository with the same name, or fork it back :sweat_smile:), and the "fork tree" will remain intact.

The experience for users on the original repo will also be better than on a fork, since GitHub has a tendency to do things like sending users to the original when they're trying to open a PR, etc.

As you've alluded to, we have the https://github.com/docker-library-transitioner organization specifically for this purpose if you're (IMO understandably) not willing or able to add someone else to your organization with repository creation access -- I'm happy to make you both members there such that the repo can be transferred into that organization and from there transferred by someone with the appropriate permissions here to complete the move (but you'll want to delete any fork in the target organization first).

**Comment by reidmorrison** [comment]
Looks like lots of volunteers, otherwise I am more than happy to help out / contribute.
I have moved GitHub repos in the past which is relatively straight forward. The owner moves the repo to the JRuby org and an admin in JRuby org accepts it.
While waiting for the transfer, which JVM/JDK version do we want to ship as default for JRuby 9.3?

**Comment by headius** [comment]
@reidmorrison I just saw this update... my backlog has been pretty deep. I'm thinking Java 11 would be the target, but we need to get test runs passing. It's not far off, just needs some tweaking here and there.

**Comment by reidmorrison** [comment]
If we want to push the above repo to the JRuby org, in my experience with moving personal Github repos to organizations is to push the repo to the personal account of one of the org admins. They in turn can push the repo to the org.

I.e. @cpuguy83 can you push the repo to @headius then he can push it immediately to the JRuby org?

**Comment by headius** [comment]
Working on this today.

**Comment by headius** [comment]
Bear with me, Docker experts.

As I understand things:

* the repo maintained by @cpuguy83 contains Dockerfile for the combinations of current JRuby and various versions of JDK and JRE.
* Updating a JRuby version is a matter of running the update.sh script, which updates the version strings, URLs, and SHA256 for the Dockerfiles.
* Once updated to a new version, tag in docker-jruby repo and update official images.
* Official image is updated by doing a PR to the "jruby" library with the new versions, git hash for the update.
* Docker Hub then takes over the process of updating the official jruby image.

Do I basically have this process right? The Dockerfiles are straightforward enough, so maintaining it should not be a problem. We will include the image update into our regular release process run by @enebo and myself.

The cpuguy83 docker-jruby repo has been forked over to the jruby organization, but can be remade as its own repository. I am not sure the process for updating the official library to be under our repository and probably me or a jruby.org email as the maintainer. Just do a PR? Do I need to provide a blood sample?

I think we can move this to the new jruby organization any time.

**Comment by cpuguy83** [comment]
> Do I basically have this process right? 

Yep!

> Just do a PR?

Yep!

> Do I need to provide a blood sample?

Hair sample might work 😜 

❤️ ❤️ ❤️ 

Also thanks to everyone who has been diligently helping to keep the image up to date over the last year or so.

**Comment by headius** [comment]
@cpuguy83 Other than the version update, which of these steps do you do manually and which are automated? None of these updates are particularly complex, but if there is a standard way to automate this pipeline I would like to know it.

I am preparing a PR to update the library to an official JRuby email and the jruby/docker-jruby repository now and will check that everything is correct before I push.

**Comment by cpuguy83** [comment]
I do not currently have any automation around this except for CI to test the builds are working: https://github.com/cpuguy83/docker-jruby/blob/master/.github/workflows/test.yml

**Comment by headius** [comment]
I have repushed jruby/docker-jruby as a duplicate rather than a fork.

PR will be from my form of official-images here: https://github.com/headius/official-images/commit/8fa1115b0908309dd9c1956ecd4c208853ed1cc6

Note this does not reflect the in-progress PR to update to 9.2.14.0: docker-library/official-images#9318. If that is likely to land soon I can wait for it.

**Comment by headius** [comment]
I went ahead with the PR. We can adjust it as appropriate.

Once again, thank you for maintaining these images for so many years, @cpuguy83!

**Comment by fidothe** [comment]
FYI, my take on this (for generating docker images for CI on Circle CI) automates a lot with Rake

(https://github.com/fidothe/circleci-jruby-docker/blob/master/Rakefile) 

Lack of concrete committed Dockerfiles a deal-breaker for official images, IIRC (generated files were pushed to my personal hub account for this), but the basic principle ought to work just fine. Once things are bedded in after the transfer I can take another look and see if I can apply any of that to making the official images stuff more automatable.

**Comment by fidothe** [comment]
Also, 💯 🎉 🥇 everyone

**Comment by headius** [comment]
@fidothe That would be very helpful, thanks!

This will become part of the standard release process that is *mostly* run by @enebo and which is detailed here:https://github.com/jruby/jruby/wiki/ReleaseDocumentation

Anything we can do to automate the Docker updates (or anything else on this list) will help to make releases happen more frequently and with fewer glitches.

Timeframe-wise, we will not be doing any releases until January, and will then decide whether we are ready for 9.3 or whether we will put out 9.2.15.0 to pick up a few more fixes.

**Comment by headius** [comment]
@cpuguy83 Can we transfer the repo to the JRuby organization? The dockerhub folks wanted to make sure all issues and PRs and such get preserved at the new home. I believe they also have a dummy organization that can be used as an intermediate for such transfers, or we could temporarily grant org privileges on one side or the other.

**Comment by cpuguy83** [comment]
@tianon can you set us up with the intermediate org?

**Comment by tianon** [comment]
Yep, done, and I see you've already moved your `docker-jruby` into it -- I've invited @headius; I'd suggest deleting `github.com/jruby/docker-jruby` before initiating the transfer (or else the new repo will become `docker-jruby-1` IIRC).

**Comment by headius** [comment]
I'm on it!

**Comment by headius** [comment]
The `docker-jruby` repository has been transferred to the `jruby` organization.

@cpuguy83 @tianon Thank you for your help! I believe we are ready to move forward with https://github.com/docker-library/official-images/pull/9319 now.

**Comment by headius** [comment]
Release doc updated with basic instructions: https://github.com/jruby/jruby/wiki/ReleaseDocumentation/_compare/dc7b8f7b6d22d69309123a2e4e62e26b54e327ab...0c73dacfe86e8397ae6bd6c10fca76e393fb2ddd

**Comment by headius** [comment]
Thanks everyone for helping us with this transition! We will update the images as part of our release process going forward, and you should file issues and PRs against https://github.com/jruby/docker-jruby from now on.

**Comment by tedhexaflow** [comment]
Hello 🙏 @headius,

I'm trying to pull a JRuby image with jdk15 without any success and finally landed here.

According to my understanding, https://github.com/jruby/docker-jruby/tree/master/9000 already have Dockerfile for jdk14 and jdk15, but there is no tag in the PR submitted https://github.com/docker-library/official-images/commit/f35fca715133e189e63624895d33fe584d0b9674#diff-d2864a21ae1dc6fe49c3e9d03d02880d62a38cc13a6996ed3dc6b55f8452dd22

Would you kindly update the tag to include jdk14 and jdk15 and submit a new PR to docker-library/official-images.

Thank you so much in advance. 🙏

**Comment by tianon** [comment]
Probably also relevant:
https://github.com/docker-library/openjdk/commit/c74ad8736c35c9946aecf43679c4d959178e54c1
(OpenJDK 15 is EOL)

**Comment by tedhexaflow** [comment]
Oh. I guess I have to pull the available image and install the required JDK manually (for now).

**Comment by headius** [comment]
Back in the saddle again. What is needed here? I can add configurations easily enough.

**Comment by tedhexaflow** [comment]
Hello @headius,

At this moment, there are images with jre8, jdk8, jre11, and jdk11.
Is there any plan to release images with other JDK versions? (i.e., jdk15, jdk16, jdk17, etc.,). 

Thanks 🙏

**Comment by headius** [comment]
@tedhexaflow I don't see why not... the configurations are pretty easy to add.

However, I am reluctant to add JDK releases that are not long-term supported (by Oracle) since they will become stale once the base image no longer gets updates.

Could you open a separate issue on our docker-jruby repository and we can discuss which versions to support there?
