### ISSUE TITLE
Kernel#warn doesn't handle exceptions as expected

### ISSUE THREAD

**Issue by ashmaroli** [jruby/jruby#5608]
## Environment

(**Note: This issue was detected on Travis CI and has has not been tested elsewhere.**) 

* JRuby version (`jruby -v`): 9.2.6.0
* Operating system and platform (e.g. `uname -a`): Ubuntu 14.04.5 LTS

Other relevant info you may wish to add:
* Travis Build log: https://travis-ci.org/jekyll/jekyll/jobs/492066402

### Expected Behavior

```ruby
# sample script

exp = ArgumentError.new('lorem ipsum dolor sit')
warn exp

# (On MRI):
# => "lorem ipsum dolor sit"
```

### Actual Behavior

```
TypeError: no implicit conversion of ArgumentError into String
```

**Comment by enebo** [comment]
Wow you found something we have never implemented which was valid in Ruby 1.8 (and possibly older)!
