### ISSUE TITLE
Open3.popen3 does not work in jruby 9.2.6 with openjdk 11.0.2

### ISSUE THREAD

**Issue by osammler** [jruby/jruby#5616]
### Environment

    Linux  4.20.2-1-default #1 SMP PREEMPT Sun Jan 13 12:37:46 UTC 2019 (036c5c2) x86_64 x86_64 x86_64 GNU/Linux
    jruby 9.2.6.0 (2.5.3) 2019-02-11 15ba00b OpenJDK 64-Bit Server VM 11.0.2+9 on 11.0.2+9 +jit [linux-x86_64]

### Expected Behavior

- Script:

[test.txt](https://github.com/jruby/jruby/files/2861293/test.txt)

    require 'open3'

    def doit(command)
       stdout = nil
       Open3.popen3(command) do |i, o, e|
              stdout = o.read.chomp
       end
       puts("stdout: " + stdout)
    end

    doit("ls  /etc/hosts")

expected (with jdk1.8.0_121 it works correct):
variable stdout will get the stdout stream output

Output:
stdout: /etc/hosts

### Actual Behavior

the output stream goes directly to screen and is not redirected with popen3

Output:
/etc/hosts
stdout:

**Comment by k77ch7** [comment]
@osammler maybe this works.

### My Environment
```
jruby 9.2.8.0-SNAPSHOT (2.5.3) 2019-06-10 d2875a4 OpenJDK 64-Bit Server VM 11.0.2+9 on 11.0.2+9 +jit [darwin-x86_64]
```

>

**Comment by headius** [comment]
Appears to be working properly in JRuby 9.2.8.0 on Java 11.

**Comment by osammler** [comment]
It works now with Jruby 9.2.8.0 on Java11. 
Thanks for help.
