### ISSUE TITLE
IO.popen (Tempfile) does not function in jruby 9k

### ISSUE THREAD

**Issue by annabackiyam** [jruby/jruby#5622]
JRuby 9.1.13.0
Linux 4.1.12-124.20.7.el6uek.x86_64
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)

sample.rb
```ruby
require 'open3'
require 'tempfile'
@temp_file = Tempfile.new(["anna-temp",".sh"])
@temp_file.write("ls")
@temp_file.chmod(0500)
puts `cat #{@temp_file.path}`
IO.popen(["sh #{@temp_file.path}"]) { |ls_io|
        ls_io.each_line do |l|
          puts l
        end
}
IO.popen(["sh /tmp/anna-temp.sh"]) { |ls_io|
        ls_io.each_line do |l|
          puts l
        end
}
```

commands to run:
1.`java -jar -Djruby.native.enabled=false /opt/lib/jruby-complete.jar sample.rb`
The first popen doesn't print anything with a temp file. so, I have created a physical .sh file with just "ls".
The second popen does print the output of the command in the .sh file when native flag is set to false
2. `java -jar /opt/lib/jruby-complete.jar sample.rb`
Both popen don't work when native flag is enabled

**Comment by headius** [comment]
@annabackiyam IO in Ruby is buffered, and since you have not closed the tempfile here I suspect it has simply not written anything to disk yet. Can you add a `@tempfile.flush` after `@tempfile.write` and confirm it resolves your issue?

Also...if you can confirm the behavior exists in 1.7.x, that would tell us it's not a behavior change we should look into.

**Comment by enebo** [comment]
@annabackiyam I noticed this does not work in C Ruby either.  I noticed two issues in your script (my version below):

1. @temp_file is not flushing or is closed so the temp file you create does not quite have any contents yet.
1. Using array for command line here is assuming that whole command-line is the name of the executable.

Look at what I did here to see how I changed things:

```ruby
require 'open3'
require 'tempfile'
@temp_file = Tempfile.new(["anna-temp",".sh"])
path = @temp_file.path
@temp_file.write("ls -l")
@temp_file.chmod(0500)
@temp_file.close # 
puts "FILE"
puts `cat #{@temp_file.path}`
puts "------"
puts "OUTPUT"
IO.popen(["sh", path]) { |io|
  p io.read
}
```

**Comment by enebo** [comment]
I thought I would add that you can also add a shebang line and get rid of needing to include 'sh' into you popen command as well:

```ruby
require 'open3'
require 'tempfile'
@temp_file = Tempfile.new(["anna-temp",".sh"])
shell_script = @temp_file.path
@temp_file.write <<EOS
#!/bin/sh
ls -l
EOS
@temp_file.chmod(0500)
@temp_file.close
puts "FILE"
puts `cat #{@temp_file.path}`
puts "------"
puts "OUTPUT"
IO.popen(shell_script) { |io|
  p io.read
}
```

**Comment by annabackiyam** [comment]
@headius @enebo Thank you both for your comments.
File execution works after adding flush from the command line. 
I still could not make it work in my bundle. I'll check in the bundle code and send you the link.
Yes, everything worked in 1.7 without flush too.
