### ISSUE TITLE
Bundler .bat is incorrect on Windows after updating rubygems

### ISSUE THREAD

**Issue by karlhe** [jruby/jruby#5632]
### Environment

JRuby: jruby 9.2.6.0 from jruby-dist-9.2.6.0-bin
OS: Windows Server 2012 R2, Windows Server 2016 Datacenter

### Expected Behavior

Bundler runs normally

### Actual Behavior

Fresh install

```
C:\jruby-9.2.6.0\bin>gem update --system
C:\jruby-9.2.6.0\bin>gem install bundler
C:\jruby-9.2.6.0\bin>bundle
'"C:\jruby-9.2.6.0\bin\ruby.exe"' is not recognized as an internal or external c
ommand,
operable program or batch file.
```

Contents of bundle.bat:

```
@ECHO OFF
@"%~dp0ruby.exe" "%~dpn0" %*
```

When installing bundler 1.17.3 without updating rubygems:

```
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"C:\jruby-9.2.6.0\bin\jruby.exe" "C:/jruby-9.2.6.0/bin/bundle" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"C:\jruby-9.2.6.0\bin\jruby.exe" "%~dpn0" %*
```

Also of note: `gem update --system` installs bundler 1.17.3 and creates jbundle and jgem binaries, which I'm not sure what the purpose of is.

May well be an issue with rubygems or bundler, but since bundler 2 requires rubygems 3 it's a bit hard to pinpoint...

**Comment by headius** [comment]
Sorry for the delay on this one!

Yeah I think this is likely a problem with RubyGems, since the only thing you did to break it was to update RubyGems.

Could you open an issue with RubyGems about this and let us know?

**Comment by karlhe** [comment]
They seem to have a handle on this, so I'll close the issue on this side. See rubygems issue for updates.
