### ISSUE TITLE
Maven cannot build jruby due to Gems downloading from mvnrepository via RVM

### ISSUE THREAD

**Issue by rsov** [jruby/jruby#5674]
Hello,

I am having issues installing jruby though RVM. It looks like RVM cannot find binaries and reverts to building from source. [See this issue](https://github.com/rvm/rvm/issues/4655)

The build fails because maven cannot download rake 10.4.2 from rubygems.org (connection refused). 

I see that `mavengems` is supposed to be handling the download of ruby gems from rubygems.org.

However if I change the rake version in pom.rb to match rake version that is hosted on mvnrepository (rake 10.1.0) then build continues fine and breaks on the next gem that is not in mvnrepository

This happens with new versions of jruby (9.2.6.0 and 9.2.5.0)

I tried with maven 3.5.2 and 3.3.9

**Comment by mkristian** [comment]
@rsov yes, jruby build downloads gems from rubygems.org and doing so by using a virtual mvn-repo which converts rubygems.org. as maven uses all repo configured it will find these old rake gems on maven central but not the new ones.
the question is why there is a 'connection refused' as build just works fine locally and travis and other places.

**Comment by rsov** [comment]
@mkristian I think that's where the issue is. For some reason mvn goes after gems hosted on maven site instead of using rubygems.org. 

I am not sure is it because virtual repo is not set up properly or if it uses it as a fallback when call to rubygems.org gets refused

**Comment by mkristian** [comment]
@rcov maven central is a fallback.  `connection refused' is kind of strong, as I am sure it is not rubygems.org
need to try to reproduce this locally

**Comment by rsov** [comment]
@mkristian Thank you, that makes sense now why it goes to maven now. I will fix my connection to rubygems

**Comment by rsov** [comment]
Well @mkristian and @kares ,

Opened up all the corporate firewalls, disabled all proxies, still no luck

Now it's getting connection timeout when dowloading rubygems through maven proxy

I have checked your travis logs and it looks like your gems are cached / being copied from local storage instead of loading though maven 


My rvm maven build log looks like this:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building JRuby Lib Setup 9.1.17.0
[INFO] ------------------------------------------------------------------------
Downloading: mavengem:https://rubygems.org/rubygems/rake/10.4.2/rake-10.4.2.pom
2019-04-05T09:41:13.713-05:00 [main] WARN Ruby : Warning: not setting network stack system property because socket subsystem may already be booted.If you need this option please set it manually as a JVM property.
Use JAVA_OPTS=-Djava.net.preferIPv4Stack=true OR prepend -J as a JRuby option.
set default encoding to UTF-8 for current runtime
Downloading: mavengem:https://rubygems.org/rubygems/rdoc/4.2.0/rdoc-4.2.0.pom
Downloading: mavengem:https://rubygems.org/rubygems/test-unit/3.1.1/test-unit-3.1.1.pom
Downloading: mavengem:https://rubygems.org/rubygems/psych/2.2.4/psych-2.2.4.pom
Downloading: mavengem:https://rubygems.org/rubygems/json/1.8.3/json-1.8.3.pom
Downloading: mavengem:https://rubygems.org/rubygems/jar-dependencies/0.3.12/jar-dependencies-0.3.12.pom
Downloading: mavengem:https://rubygems.org/rubygems/net-telnet/0.1.1/net-telnet-0.1.1.pom
Downloading: mavengem:https://rubygems.org/rubygems/did_you_mean/1.0.1/did_you_mean-1.0.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JRuby .............................................. SUCCESS [  0.174 s]
[INFO] JRuby Core ......................................... SUCCESS [ 18.544 s]
[INFO] JRuby Lib Setup .................................... FAILURE [17:31 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17:52 min
[INFO] Finished at: 2019-04-05T09:58:43-05:00
[INFO] Final Memory: 81M/924M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jruby-stdlib: Could not resolve dependencies for project org.jruby:jruby-stdlib:jar:9.1.17.0: Failed to collect dependencies at rubygems:rake:gem:10.4.2: Failed to read artifact descriptor for rubygems:rake:gem:10.4.2: Could not transfer artifact rubygems:rake:pom:10.4.2 from/to mavengems (mavengem:https://rubygems.org): Error transferring file: RubygemsFile[type=POM, storage=/maven/releases/rubygems/rake/10.4.2/rake-10.4.2.pom, remote=/maven/releases/rubygems/rake/10.4.2/rake-10.4.2.pom, name=rake, state=ERROR, exception=IOException: java.net.ConnectException: Connection timed out (Connection timed out)] on https://rubygems.org -> [Help 1]
```

This happens for any jruby I tried installing; 9.2.6.0, 9.2.5.0

**Comment by rsov** [comment]
never mind, more firewall rules got in a way

**Comment by rabos5** [comment]
I saw this was closed but wasn't sure exactly what the resolution was.  Can somebody add more detail?

**Comment by headius** [comment]
@rabos5 Apparently @rsov had a firewall in the way, and must have been able to deal with that. If you're having a similar problem please open a new bug so we don't get these mixed up (since this one was not actually a bug).
