### ISSUE TITLE
jruby 9.2.7.0 ships with bundler (it didn't before)

### ISSUE THREAD

**Issue by jsvd** [jruby/jruby#5686]
I was trying the new jruby and noticed that 9.2.7.0 ships with bundler:

```
/tmp/jruby % tar -zxf jruby-dist-9.2.6.0-bin.tar.gz
/tmp/jruby % tar -zxf jruby-dist-9.2.7.0-bin.tar.gz
/tmp/jruby % find . -name *bundler*
./jruby-9.2.6.0/lib/ruby/stdlib/rubygems/bundler_version_finder.rb
./jruby-9.2.7.0/lib/ruby/stdlib/rubygems/bundler_version_finder.rb
./jruby-9.2.7.0/lib/ruby/stdlib/bundler.rb
./jruby-9.2.7.0/lib/ruby/stdlib/bundler
./jruby-9.2.7.0/lib/ruby/stdlib/bundler/templates/Executable.bundler
./jruby-9.2.7.0/lib/ruby/gems/shared/specifications/bundler-1.16.6.gemspec
./jruby-9.2.7.0/lib/ruby/gems/shared/cache/bundler-1.16.6.gem
./jruby-9.2.7.0/lib/ruby/gems/shared/gems/bundler-1.16.6
./jruby-9.2.7.0/lib/ruby/gems/shared/gems/bundler-1.16.6/bundler.gemspec
./jruby-9.2.7.0/lib/ruby/gems/shared/gems/bundler-1.16.6/lib/bundler.rb
./jruby-9.2.7.0/lib/ruby/gems/shared/gems/bundler-1.16.6/lib/bundler
./jruby-9.2.7.0/lib/ruby/gems/shared/gems/bundler-1.16.6/lib/bundler/templates/Executable.bundler
./jruby-9.2.7.0/lib/ruby/gems/shared/gems/bundler-1.16.6/exe/bundler
```

[edit] This is creating an issue for us in Logstash as we install our own version of Bundler

**Comment by headius** [comment]
The Bundler in stdlib was an oversight...the RubyGems updater now installs Bundler alongside RubyGems as a standard library, rather than just as a preinstalled gem.

I have already removed the files on master for 9.2.8, and I did confirm that installing a newer Bundler does override the one in stdlib, as it should. Does that not seem to be the case in your setup?

**Comment by headius** [comment]
We've already decided to remove bundler files from stdlib, which is done on master.

We need to decide if we will ship bundler as a preinstalled gem, as it is set up to be right now on master.

**Comment by headius** [comment]
From tarball:

```
[] ~/projects/jruby-9.2.7.0 $ which jruby
/Users/headius/projects/jruby-9.2.7.0/bin/jruby

[] ~/projects/jruby-9.2.7.0 $ jruby -v
jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 OpenJDK 64-Bit Server VM 25.202-b08 on 1.8.0_202-b08 +jit [darwin-x86_64]

[] ~/projects/jruby-9.2.7.0 $ bundle -v
Bundler version 1.16.6

[] ~/projects/jruby-9.2.7.0 $ gem install bundler
Fetching: bundler-2.0.1.gem (100%)
Successfully installed bundler-2.0.1
1 gem installed

[] ~/projects/jruby-9.2.7.0 $ which jruby

[] ~/projects/jruby-9.2.7.0 $ bundle -v
Bundler version 2.0.1
```

**Comment by jsvd** [comment]
this may be because we use a separate GEM_HOME to house the gems (logstash plugins). that said, it still seems strange that the stdlib is taking precendence in our situation, but may just be our fault. I will investigate.

**Comment by kares** [comment]
@headius isn't is just RGs 3.0 that pre-installs Bundler?
was also a bit surprised by the Bundler inclusion, know its a default gem but I thought only since Ruby 2.6
so in the end its the move towards the right direction ...

**Comment by headius** [comment]
@kares That's what I thought too, but apparently they have been installing bundler for some time. I went back as far as 2.7.0 in the changelog and there were still mentions of the default bundler install.

```
$ gem update --system 2.7.9
Updating rubygems-update
Fetching: rubygems-update-2.7.9.gem (100%)
Successfully installed rubygems-update-2.7.9
Installing RubyGems 2.7.9
Bundler 1.16.6 installed
RubyGems 2.7.9 installed
Regenerating binstubs
```

Personally I don't care much either way but I'm leaning toward removing the default gem and going back to shipping no bundler. It is annoying that RG updater does this.

**Comment by headius** [comment]
Removed the last bits in bd67051add.
