### ISSUE TITLE
Licensing confusion; perhaps out of date

### ISSUE THREAD

**Issue by hyandell** [jruby/jruby#5691]
Hi JRuby folk,

Looking at the COPYING file there is a section that says:

> 
> Some additional libraries distributed with JRuby are not covered by
> JRuby's licence. Most of these libraries and their licenses are listed 
> below. Also see LICENSE.RUBY for most files found in lib/ruby/stdlib.
> 
>  bench/rails/public/javascripts/* are distributed under the MIT
>  license, and have the following copyrights:
> 
>    controls.js is Copyright:
>    (c) 2005-2008 Thomas Fuchs (http://script.aculo.us, http://mir.aculo.us)
>    (c) 2005-2007 Ivan Krstic (http://blogs.law.harvard.edu/ivan)
> (c) 2005-2007 Jon Tirsen (http://www.tirsen.com)

Those files no longer seem to be in the JRuby source. I've seen confusion on controls.js suggesting it's this GPL 3.0 project ( https://github.com/controlsjs/controls.js ). It seems unlikely the two relate, but perhaps you could remove this from COPYING if it's no longer accurate?

**Comment by headius** [comment]
Good catch, it looks like these files were only ever part of a Rails benchmark, which has been removed from the repository. It was never shipped as part of JRuby (we don't ship benchmarks and tests in the binary distribution).

I'll update COPYING.
