### ISSUE TITLE
Address all tests failing with asserts enabled

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5692]
In https://github.com/jruby/jruby/pull/5612#issuecomment-482196145, @kares fixed our builds to properly pass `-ea` flag down to child processes, and as a result a bunch of test suites went red. This may indicate these asserts are not correct, or that we have code that happens to work even though it violates valid asserts. Either way they all need to be addressed.

The patch is here:

```diff
diff --git a/bin/jruby.bash b/bin/jruby.bash
index 4e50cb0b5dc..7318d896deb 100755
--- a/bin/jruby.bash
+++ b/bin/jruby.bash
@@ -240,6 +240,7 @@ do
         else
             if [ "${val:0:3}" = "-ea" ]; then
                 VERIFY_JRUBY="yes"
+                java_args=("${java_args[@]}" "${1:2}")
             elif [ "${val:0:16}" = "-Dfile.encoding=" ]; then
                 JAVA_ENCODING=${val:16}
             elif [ "${val:0:20}" = "-Djava.security.egd=" ]; then
```

An example build showing all failed suites (for as long as it exists in Travis history) is here: https://travis-ci.org/kares/jruby/builds/518835139

Note that at least one of these failures is due to the issue reported in #5612.

**Comment by kares** [comment]
yeah, I was working on that. will shoot off a PR

**Comment by headius** [comment]
Merged #5693 to master to go with my fixes, which should make everything green. None of the ones I fixed were really critical, but they might have led to odd errors further down the line.

**Comment by headius** [comment]
Still seems to be a few red; I'm working on it.

**Comment by headius** [comment]
Fixed an issue with BEGIN and END breaking the compiler tests; they compile ok, but we were not running optimization passes, and then the test attempted to wrap the code in CompiledIRMethod which requires those passes.

ef1cb4d489

**Comment by headius** [comment]
@enebo Do you know any reason why we wouldn't be able to optimize BEGIN and END like any other block, especially `for` blocks? See my commit above; I just turned it on and it seems to work.

**Comment by enebo** [comment]
@headius I think rationale behind not bothering is that they only execute once and AOT essentially will save them as startup interp instrs.  As far as whether they can be compiled?  Only thing I wonder about is variable scoping itself.

**Comment by headius** [comment]
GREEN

**Comment by headius** [comment]
@enebo Yeah they seem to be working fine, and I could find no reason why they wouldn't optimize. Lots of *old* comments in there they predate 9k.

See #5695 for my PR to get BEGIN working 100% in bytecode-compiled code.
