### ISSUE TITLE
sun.misc does not exist build issue.

### ISSUE THREAD

**Issue by FuncGuy** [jruby/jruby#5699]
Hi,
when i try to build jruby with jdk 11 getting a compiler error "java package sun.misc does not exist".
please have a look.

**Comment by headius** [comment]
I can reproduce problems during the build.

```
Caused by: org.jruby.exceptions.RaiseException: (OpenSSL::X509::StoreError) setting default path failed: No password supplied for PKCS#12 KeyStore.
	at org.jruby.ext.openssl.X509Store.set_default_paths(org/jruby/ext/openssl/X509Store.java:165)
	at RUBY.SSLContext(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:31)
	at RUBY.SSL(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:22)
	at RUBY.OpenSSL(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:21)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:20)
```

We have attempted to fix this before: https://github.com/jruby/jruby/issues/4805, https://github.com/jruby/jruby/issues/4799

Looking at the backtraces, I can see that jruby-openssl is loading the 1.9-compatible logic, which means this could not possibly be using JRuby 9.x. Something in this process is attempting to use an older JRuby 1.7.x.

@mkristian You helped someone else stumbling into JRuby 1.7 in #4805, but in this case we are simply trying to build JRuby itself. I thought for sure we had full builds working under Java 9+.

This only appears to affect the "bootstrap" maven profile, so it should still be possible for you to build JRuby and get a usable distribution out of it. The "bootstrap" profile just installs tools necessary for working on JRuby itself.

**Comment by headius** [comment]
@FuncGuy Please post full output of your build, adding -X to the mvn command line. That output will be very long, so please use gist.github.com or similar.

Now on a second attempt I can't get the error to fail. All I did in between was run `keytool -list -cacerts` and entered a blank password when prompted.

**Comment by headius** [comment]
I cannot reproduce the sun.misc issue. We do reference that package in various places but it builds ok for me on Java 9+.

I still can't reproduce the keystore error.

**Comment by FuncGuy** [comment]
if i compile with mvn command build will be success but if i run any tests or when i select build project option then it is throwing this compiler error(sun.misc).

**Comment by headius** [comment]
Aha! So you are trying to build and run tests within IntelliJ I guess?

Yes, this configuration is not *currently* supported, mostly because our build is significantly more complex than the typical Java application. I'd certainly like this to work, though...

**Comment by FuncGuy** [comment]
yes i'm using intelliJ.. is there any chance that i work on this as a first contributor?

**Comment by headius** [comment]
@FuncGuy That would be excellent! You should connect with @mkristian here or on Gitter since he's our build expert. I don't think this will take too much work. We may just have to add some flags to the build when running on 9+ to open up that package. I don't know how IntelliJ decides to compile things based on a maven project.

**Comment by FuncGuy** [comment]
Now i'm not getting sun.misc error but getting another error "javax.annotation.Generated" can not find symbol.

**Comment by headius** [comment]
Yeah, that package got moved out with the module system. Looks like you have a workaround already!

**Comment by FuncGuy** [comment]
yep! I've added the javax.annotation dependency and raised the PR.

**Comment by headius** [comment]
@FuncGuy If you can tidy up that PR in the way @mkristian suggested, I see no reason we can't merge it. Are you able to build under IntelliJ after those changes?

**Comment by FuncGuy** [comment]
@headius we have to configure some settings in intellij for annotation processing to activate.. so this PR will not impact much.

**Comment by robevansuk** [comment]
Not sure if this helps at this stage but I had this error with the netty/netty project. One setting I needed to change to get things working in intelliJ was:
Preferences -> Build, Execution, Deployment -> Compiler -> Java Compiler -> (untick) Use '--release' option for cross-compilation (Java 9 and later)
The next setting I switched on was under the maven settings so this may/not be relevant:
Preferences -> Build, Execution, Deployment -> Build Tools -> Maven -> (tick) Use plugin registry

**Comment by sonhmai** [comment]
@robevansuk thanks a lot, this actually solved the issue. :)
