### ISSUE TITLE
Not running or not seeing failures in command line specs

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#5705]
Looking at JRuby built from source. I'm trying to run `:command_line` specs. The docs say to use

```
jruby spec/mspec/bin/mspec ci spec/ruby/<path to spec>
```

So I tried

```
bin/jruby spec/mspec/bin/mspec ci :command_line
```

But I'm still getting failures. For example just one of them

```
The --encoding command line option does not accept a third encoding FAILED
```

I also tried with the explicit file

```
bin/jruby spec/mspec/bin/mspec ci spec/ruby/command_line/dash_encoding_spec.rb 
```

That still fails. I wasn't sure why the tags aren't being picked up. But then I found there is no tag for this anyway. So I tried the spec code manually

```
bin/jruby --disable-gems --encoding big5:ISO-8859-1:utf-32le -e "print [Encoding.default_external.name, Encoding.default_internal&.name].inspect"
```

And the behaviour is sure enough not passing the spec. So I think you have at least `:command_line` specs that you're either not running, or not seeing that they fail.

(It's not about this particular spec or fixing it - the issue is why isn't it failing or tagged?)

**Comment by headius** [comment]
It appears we have not been running the `:command_line` specs as part of our rake targets, which has allowed the tags to drift. I'm re-adding it to the "slow" spec suite and will tag off what we don't pass.

There's some low-hanging fruit here if someone wants to add these more recent flags (e.g. `--encoding` and similar flags are basically shortcut versions of the `-E` flag).

**Comment by headius** [comment]
It looks like nearly all of the failing specs were added within the last year, most in August. The existing specs do not appear to have regressed in any substantial way.
