### ISSUE TITLE
Enumerator#any? and yield(*[[]]) bug

### ISSUE THREAD

**Issue by marcandre** [jruby/jruby#5710]
### Environment

```
$ ruby -v
jruby 9.2.8.0-SNAPSHOT (2.5.3) 2019-04-25 9477784 Java HotSpot(TM) 64-Bit Server VM 25.102-b14 on 1.8.0_102-b14 +jit [darwin-x86_64]
```

### Bug

```ruby
class Foo
  def each
    return to_enum :each unless block_given?
    x = [[]]
    yield(*x)
  end
end
enum = Foo.new.each
p enum.to_a  # => [[]], ok
p enum.any?  # => false, should be true
```

Replacing the `yield(*x)` with `yield(x[0])` circumvents the bug.

**Comment by headius** [comment]
Likely the same as other issues with yield + enumerator. There's still some places where we're not unwrapping properly, or unwrapping too much.

**Comment by ahorek** [comment]
I can confirm it's already fixed on master https://github.com/jruby/jruby/pull/6112

**Comment by marcandre** [comment]
Thanks @ahorek
