### ISSUE TITLE
Module#autoload (concurrently) blocks a second thread...hanging

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5717]
This spec has been intermittently hanging:

```
Module#autoload (concurrently)
- blocks a second thread while a first is doing the autoload
```

It will be fixed along with load service rework in #2794.

**Comment by eregon** [comment]
The next one also seems to hang:
```
Module#autoload (concurrently) blocks others threads while doing an autoload
```
See https://api.travis-ci.org/v3/job/525391791/log.txt
and https://github.com/jruby/jruby/pull/5719

**Comment by headius** [comment]
The load service rework landed long ago and these appear to run properly now.
