### ISSUE TITLE
0.0.to_d returns negative zero in jruby-9.2.7.0

### ISSUE THREAD

**Issue by ikonomov17** [jruby/jruby#5723]
### Environment

* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
   * jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 Java HotSpot(TM) 64-Bit Server VM 25.192-b12 on 1.8.0_192-b12 +jit [darwin-x86_64]
* Operating system and platform (e.g. `uname -a`)
    * MacOS Mojave 10.14.4

### Expected Behavior

* Using ruby-2.5.3, when I am trying to convert 0.0 to a BigDecimal I would expect to receive a zero without a negative sign, as shown in the example below.
```
>>  require "bigdecimal"
=> true
>>  require "bigdecimal/util"
=> true
>> 0.0.to_d
=> 0.0
>> BigDecimal(0.0, 0)
=> 0.0
```

### Actual Behavior

* When I am using jruby-9.2.7.0 and try to convert 0.0 to a BigDecimal I receive a negative zero.
```
>> require "bigdecimal"
=> true
>> require "bigdecimal/util"
=> true
>> 0.0.to_d
=> -0.0
>> BigDecimal(0.0, 0)
=> -0.0
```

**Comment by headius** [comment]
It's sometimes amazing the things that go unreported! Shouldn't be hard to fix.

**Comment by headius** [comment]
I see the problem...the code compares the value with `-0.0` to determine sign, but `-0.0 == 0.0` so it's always coming out negative.

**Comment by ikonomov17** [comment]
Great, thanks for solving it that quickly!
