### ISSUE TITLE
Puma failed to start giving LoadError: load error: puma/java_io_buffer

### ISSUE THREAD

**Issue by him3010** [jruby/jruby#5727]
### Environment

* jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 Java HotSpot(TM) 64-Bit Server VM 11.0.2+9-LTS on 11.0.2+9-LTS +jit [linux-x86_64
* Linux  3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux (ubuntu 14.04)

Other relevant info you may wish to add:
* using rails 5.1.4
* ruby version - 2.5.0
* puma gem version - 3.12.1

### Expected Behavior

*  It is working fine on mac os with the same above configuration but failing on ubuntu, it should worked on ubuntu as well

### Actual Behavior

* puma failed to start with the following error 
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
Exiting
LoadError: load error: puma/java_io_buffer -- java.lang.reflect.InaccessibleObjectException: Unable to make field protected byte[] java.io.ByteArrayOutputStream.buf accessible: module java.base does not "opens java.io" to module org.jruby.dist
          require at org/jruby/RubyKernel.java:983
          require at /home/ubuntu/.rvm/gems/jruby-9.2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292
  load_dependency at /home/ubuntu/.rvm/gems/jruby-9.2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258
          require at /home/ubuntu/.rvm/gems/jruby-9.2.5.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292
           <main> at /home/ubuntu/.rvm/gems/jruby-9.2.5.0/gems/puma-3.12.1-java/lib/puma/io_buffer.rb:6

**Comment by kares** [comment]
update to latest puma or use their master (not sure if they released but its fixed there). 
alternatively you can downgrade to Java 8 or setup proper `--add-opens` for Java (e.g. JRUBY_OPTS)

**Comment by kares** [comment]
for further reference, here's the change-set that resolves the issue: https://github.com/puma/puma/pull/1691
