### ISSUE TITLE
Tempfile#open doesn't support default argument

### ISSUE THREAD

**Issue by nori0320** [jruby/jruby#5735]
### Environment

    % uname -a
    Darwin xxxxxxxx.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64

    % jruby -v
    jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 Java HotSpot(TM) 64-Bit Server VM 25.202-b08 on 1.8.0_202-b08 +jit [darwin-x86_64]

    % ruby -v
    ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin16]

### Expected Behavior

    % ruby -v
    ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin16]
    % irb
    irb(main):001:0> require 'tempfile'
    => true
    irb(main):002:0> Tempfile.open {}
    => nil

### Actual Behavior

    % jruby -v
    jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 Java HotSpot(TM) 64-Bit Server VM 25.202-b08 on 1.8.0_202-b08 +jit [darwin-x86_64]
    % irb
    irb(main):001:0> require 'tempfile'
    => true
    irb(main):002:0> Tempfile.open {}
    Traceback (most recent call last):
            6: from /Users/xxxxxx/.rbenv/versions/jruby-9.2.7.0/bin/irb:13:in `<main>'
            5: from org/jruby/RubyKernel.java:1193:in `catch'
            4: from org/jruby/RubyKernel.java:1193:in `catch'
            3: from org/jruby/RubyKernel.java:1425:in `loop'
            2: from org/jruby/RubyKernel.java:1061:in `eval'
            1: from (irb):2:in `evaluate'
    ArgumentError (wrong number of arguments (given 0, expected 1..3))

**Comment by headius** [comment]
🤔

**Comment by Adithya-copart** [comment]
See https://github.com/jruby/jruby/pull/5782#issuecomment-508886310
