### ISSUE TITLE
Backtrace set with set_backtrace is not dup'd properly in 9.2.7.0

### ISSUE THREAD

**Issue by mvz** [jruby/jruby#5738]
### Environment

* `jruby -v`: `jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 OpenJDK 64-Bit Server VM 11.0.4+2-Debian-1 on 11.0.4+2-Debian-1 [linux-x86_64]`
* JRUBY_OPTS: `--dev`
* Operating system and platform (e.g. `uname -a`): `Linux bean 4.19.0-5-amd64 #1 SMP Debian 4.19.37-3 (2019-05-15) x86_64 GNU/Linux`

### Expected Behavior

Given the following ruby code:
```ruby
begin
  raise
rescue => err
  err.set_backtrace ['hi']
  p err.backtrace
  p err.dup.backtrace
end
```

In MRI and JRuby 9.2.6.0, this prints:
```
["hi"]
["hi"]
```

### Actual Behavior

In JRuby 9.2.7.0, this prints:
```
["hi"]
["foo.rb:2:in `<main>'"]
```

**Comment by headius** [comment]
Nice find! Maybe I don't want to know how you found it...

**Comment by mvz** [comment]
Thanks, @headius!
