### ISSUE TITLE
"class is not compiled Ruby" error for string interpolation expression

### ISSUE THREAD

**Issue by rsim** [jruby/jruby#5740]
### Environment

* jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 Java HotSpot(TM) 64-Bit Server VM 25.191-b12 on 1.8.0_191-b12 +jit [darwin-x86_64]

### Expected Behavior

Create a file `test.rb` with a content
```ruby
"#{123}"
```

And compile it and try to load:
```
jrubyc test.rb
jruby -e "load 'test.class'"
```

When using JRuby 9.2.6.0 then there are no error messages.

### Actual Behavior

When using JRuby 9.2.7.0 it fails:
```
$ jrubyc test.rb
$ jruby -e "load 'test.class'"
LoadError: test.class is not compiled Ruby; use java_import to load normal classes
    load at org/jruby/RubyKernel.java:1022
  <main> at -e:1
```

This is a critical bug for our precompiled application as now loading of many precompiled Ruby files fails.

**Comment by enebo** [comment]
7dc0ae fully fixes the issue but I am trying to reason out how we should test this.

**Comment by omegahm** [comment]
Just to add to this the following two examples (as `test.rb`) work:

```ruby
puts 123.to_s
```

```ruby
puts "#{"123"}"
```

while this one gives the same error:

```ruby
puts "#{123.to_s}"
```

**Comment by enebo** [comment]
@omegahm I am not seeing this with master:

```text
system ~/work/jruby master 2188% cat test.rb
puts "#{456.to_s}"
system ~/work/jruby master 2189% jrubyc test.rb
system ~/work/jruby master 2190% jruby -I. -e 'load "./test.class"'
456
```

**Comment by enebo** [comment]
Original problem was solved and no response on second commenter.  Closing as resolved.
