### ISSUE TITLE
mkmf: CCDLFLAGS is missing -fPIC

### ISSUE THREAD

**Issue by glebm** [jruby/jruby#5751]
`CCDLFLAGS` is missing `-fPIC`.
Instead `-fPIC` is set only in `CFLAGS` and because of this C++ code is compiled without it (breaking partial static linking).

**Comment by kares** [comment]
wonder (looking at https://github.com/jruby/jruby/issues/5749) why do you want extconf.rb to work?
... since C-extensions don't work, would this actually help you much, you only need a clean ext build?

**Comment by betesh** [comment]
@kares The motivation for #5749 #5750 #5751 #5752 is https://github.com/sass/sassc-ruby/pull/127

**Comment by glebm** [comment]
> since C-extensions don't work

They do work as long as they don't need libruby. So basically C libraries called from Ruby, e.g. via the FFI gem.
