### ISSUE TITLE
cipher.final should not be required for streaming ciphers

### ISSUE THREAD

**Issue by kreynolds** [jruby/jruby#5772]
### Environment

Provide at least:
* jruby 9.2.6.0 (2.5.3) 2019-02-11 15ba00b OpenJDK 64-Bit Server VM 11.0.2+9 on 11.0.2+9 +jit [darwin-x86_64]
* Darwin Kelleys-MBP.neo.rr.com 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

### Expected Behavior

* `OpenSSL::Cipher.new('aes-256-ctr')` should not require `cipher.final` for streaming ciphers

### Actual Behavior

* It requires `cipher.final` to get the trailing bytes

### Sample script

```ruby
require 'openssl'
require 'securerandom'

# String which will have 4 trailing bytes
string = 'a'.b*20

cipher = OpenSSL::Cipher.new('aes-256-ctr')
cipher.iv = SecureRandom.random_bytes(16)
cipher.key = SecureRandom.random_bytes(32)

# str should be 20 bytes long
puts cipher.update(string).size

# In MRI
# => 20
# In JRuby
# => 16
```

**Comment by shibz** [comment]
cipher.update and cipher.final have different behavior in JRuby vs MRI for block ciphers also when data is added in KEY_LENGTH sized chunks.

```
require 'openssl'
require 'securerandom'

KEY_LENGTH = 16

cipher = OpenSSL::Cipher.new("AES-128-CBC")
cipher.encrypt
cipher.key = SecureRandom.random_bytes(KEY_LENGTH)

puts cipher.update(SecureRandom.random_bytes(KEY_LENGTH)).length

# MRI = 16
# JRuby = 0

puts cipher.final.length

# MRI = 16
# JRuby = 32
```

**Comment by headius** [comment]
This might get more responses if filed with https://github.com/jruby/jruby-openssl but copying @kares here so everyone relevant sees it.

**Comment by kreynolds** [comment]
Ah .. I didn't realize that was a separate thing. I [refiled there](https://github.com/jruby/jruby-openssl/issues/182) and will close this issue.
