### ISSUE TITLE
SecureRandom does not implement #bytes like MRI

### ISSUE THREAD

**Issue by kreynolds** [jruby/jruby#5773]
### Environment

Provide at least:
* jruby 9.2.6.0 (2.5.3) 2019-02-11 15ba00b OpenJDK 64-Bit Server VM 11.0.2+9 on 11.0.2+9 +jit [darwin-x86_64]
* Darwin Kelleys-MBP.neo.rr.com 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

### Expected Behavior

* SecureRandom should implement `#bytes` to match MRI. For example, MRI implements `#bytes` and `#gen_random`, and the remaining methods are extended with a formatter.

### Actual Behavior

* It does not implement `#bytes` at all.

**Comment by headius** [comment]
We implement `random_bytes`...perhaps this is just a new alias?

**Comment by headius** [comment]
Looks like it was an alias that became a wrapper method, and we just never added it (or mistakenly removed it).

**Comment by headius** [comment]
Trivial fix coming.

It looks like there's specs for `Random#bytes` [here](https://github.com/jruby/jruby/blob/d850ba54e4c11b93ed59da341325eb74457602f0/spec/ruby/core/random/bytes_spec.rb) but nothing for `SecureRandom.bytes` [here](https://github.com/jruby/jruby/tree/d629c9464791d01f20f5cb805c45f287b06de1c1/spec/ruby/library/securerandom). Could you have a look and see if we can share or duplicate these specs? cc @eregon for help moving this to something shared, if that's necessary.

**Comment by headius** [comment]
FWIW this following workaround basically does what I did:

```ruby
class << SecureRandom
  def bytes(n); random_bytes(n); end
  alias gen_random bytes
end
```

**Comment by kreynolds** [comment]
Yeah, I know its a trivial alias, I just filed in the interest of maintaining general compatibility. Thanks for knocking this one out :)
