### ISSUE TITLE
Time#zone when no zone is known

### ISSUE THREAD

**Issue by zverok** [jruby/jruby#5785]
### Environment

```
$ jruby -v
jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 OpenJDK 64-Bit Server VM 25.212-b03 on 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03 +jit [linux-x86_64]
$ uname -a
Linux platypus 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
### Expected Behavior

On MRI (any version), when `Time`'s utc_offset is specified as a number, `Time#zone` returns `nil`

```ruby
t = Time.new(2019, 6, 1, 0, 0, 0, 3*3600) # => passing offset explicitly makes it lack symbolic zone
# => 2019-06-01 00:00:00 +0300
t.zone # => nil
```

### Actual Behavior

On JRuby (specified version), it returns `""` (empty string).
```ruby
t = Time.new(2019, 6, 1, 0, 0, 0, 3*3600)
# => 2019-06-01 00:00:00 +0300
t.zone
# => "" 

# Using text offset works as expected:
Time.new(2019, 6, 1, 0, 0, 0, '+03:00').zone
# => nil 
```

It is obviously very edge-case scenario, and never explicitly specified in `Time`'s docs, but MRI's behavior seems more consistent, and JRuby's way requires [special handling](https://github.com/zverok/time_calc/search?l=Ruby&q=jruby) in some cases.

**Comment by enebo** [comment]
This was fixed in 9.2.7.0.
