### ISSUE TITLE
LoadError: no such file to load while requiring jar-file

### ISSUE THREAD

**Issue by yaxartes** [jruby/jruby#5796]
Hello everyone!

I've got a problem trying to require jt400.jar from my Sinatra app.

### Environment

Provide at least:
* JRuby version:
jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 +jit [mswin32-x86_64]
* Operating system: Windows 7 Corporate

### My code

```ruby
require 'java'
require 'yaml'
require './extend'
require 'socket'
require 'lib/jt400.jar'
require 'lib/as400plugin-1.0.97.jar'
require 'lib/as400installer-generator-1.0.0.jar'

java_import 'ru.alfabank.gradle.as400plugin.AS400session'
java_import 'com.ibm.as400.access.AS400Text'
java_import 'com.ibm.as400.access.ProgramParameter'
java_import 'com.ibm.as400.access.ProgramCall'
java_import 'com.ibm.as400.access.QSYSObjectPathName'

$h_yaml ||= {}

class JT_EQ
  attr_accessor :unit, :user, :passw

  def initialize(unit, user, passw)
    @unit = unit
    @user = user
    @passw = passw
    begin
      init_as400
    rescue StandardError => e
      raise "\n#{"#" * 80}\n#  INIT ERROR\n#{e}\n#{"#" * 80}"
    end
    @set_tek_yaml = {}
  end
....
end
```
### My App folder
```bash
jt_eq
│   .gitignore
│   .rubocop.yml
│   config.ru
│   drb_server.rb
│   extend.rb
│   Gemfile
│   Gemfile.lock
│   hstat.rb
│   jt_EQ.rb
│   log_mongo.rb
│   my_mongo.rb
│
├───.idea
├───lib
│       as400installer-generator-1.0.0.jar
│       as400plugin-1.0.97.jar
│       jt400.jar
│
├───log
├───sinatra
│   │   sinatra_server.rb
│   │
│   ├───public
│   │   ├───css
│   │   │   ├───fonts
│   │   │   ├───i18n
│   │   │   ├───imgs
│   │   │   └───legacy
│   │   └───js
│   └───views│
└───yaml
```
### Actual Behavior

```bash
D:\work\jt_eq>jruby sinatra/sinatra_server.rb
LoadError: no such file to load -- lib/jt400
  require at org/jruby/RubyKernel.java:961
  require at C:/Sinatra/jruby-9.1.7.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at D:/work/jt_eq/jt_EQ.rb:8
  require at org/jruby/RubyKernel.java:961
   (root) at uri:classloader:/jruby/kernel/kernel.rb:1
   <main> at sinatra/sinatra_server.rb:2
```

**Comment by headius** [comment]
I think you may have a pathing issue; by default, the current directory is not in the Ruby load path. Note that "./extend" loads ok, because it explicitly uses a relative dir starting with "./".

If these jar files are intended to be part of your library, they should also live in the lib directory, along with your scripts either going in the lib directory or in the bin directory if they are intended to be run at the command line. Use "-I." to add the current directory to load path at the command line, or "-Ilib" if you move these files into lib.

Let us know if you still have issues after trying my suggestions!

**Comment by headius** [comment]
I forgot to mention, you may also look at the jar_dependencies tool which will automatically fetch jars from Maven Central when your gem is installed. This avoids having to keep binary files in the repository or the gem.

**Comment by yaxartes** [comment]
Thanks for you suggestions!
I use theese jar files as a part of the library, so yes, they should be in lib.
My attempt to add them to the $LOAD_PATH led to the error again. 
```
jruby -Ilib lib/jt400.jar
SyntaxError: lib/jt400.jar:1: Invalid char `\3' ('♥') in expression

```
I'll check out jar-dependencies, maybe I''l be able to make some use of it.
