### ISSUE TITLE
Prefer reline for readline support

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5802]
There's a new [pure-Ruby readline](https://github.com/ruby/reline) incorporated into Ruby 2.7. We may be able to use it as our primary readline with fallback to our less-than-perfect jline-based implementation.

https://bugs.ruby-lang.org/issues/14918

There are many [readline bugs](https://github.com/jruby/jruby/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+readline) in our project that may be fixed by this lib.

**Comment by headius** [comment]
It appears that reline uses Fiddle for Windows support, so we will need to test that. I do not currently have a Windows machine set up.

**Comment by sfrieske** [comment]
I've started to use JRuby 9.2.10 on Windows 10, adding reline gem and replacing the stdlib IRB by the current gem (with its dependencies). 
It works much better than the stdlib versions shipped with 9.2.10 (or former versions of JRuby 9), notably arrow keys and tab expansion works. There are still a few corner cases in the IRB gem that need to be ironed out, but I want to encourage the JRuby team to go this way.
To make it clear: all the small issues I see are issues within IRB's ruby code, no issues at all with respect to fiddle or other native code.

**Comment by headius** [comment]
@sfrieske Thank you for letting us know! I'm glad that the new IRB can install and works correctly for you. Definitely report issues to the IRB maintainers... they're very responsive.

I think it's safe to say we will move to reline and possibly new IRB in JRuby 9.3.

**Comment by headius** [comment]
IRB + reline load fine without modifications to JRuby. The only change we might make would be to have our readline attempt to load reline, but until we know it is 100% I don't think it is worth the effort. We will try to make the switch to reline in a future release.

**Comment by headius** [comment]
We won't ship it unless it works everywhere the old readline did!

**Comment by headius** [comment]
We're going to call this done. reline is definitely the path forward, and is working well for us after fixes over the past year.

Any remaining problems with reline/IRB should be filed as new bugs.
