### ISSUE TITLE
File.open should accept :newline keyword for text mode

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5817]
Yanked out of #5118 

Ruby 2.5 added the ability to specify that a file should be opened in text mode by passing the `newline: true` keyword argument to File.open. We have never added this feature. It probably only needs a bit of work to intercept the keyword argument and set the appropriate bits, like we do when processing file modes like "rt".

**Comment by MariuszCwikla** [comment]
@headius  are you sure about `newline: true`? MRI does not support this form but two others.

Perhaps you meant `crlf_newline: true` or `newline: :crlf`?

I did some testing and it looks like all these variants are already implemented

```
File.open("crlf.txt", cr_newline: true)
File.open("crlf.txt", crlf_newline: true)
File.open("crlf.txt", "wt", universal: true)
```
and both produce CR/CRLF correctly

And these also seem to be working fine (as specified in [Bug #13350](https://bugs.ruby-lang.org/issues/13350))

```
File.write("crlf.txt", "a\nb\nc", newline: :crlf)
File.binread("crlf.txt")
File.read("crlf.txt", mode: "r:utf-8:cp850", newline: :universal)
File.read("crlf.txt", newline: :universal)
File.read("crlf.txt", mode: "r:utf-8:utf-8", newline: :universal)
File.open("crlf.txt", "r:utf-8:utf-8", newline: :universal, &:read)
File.read("crlf.txt", newline: :universal) 
```

Corresponding code called from within `File.xxx` methods is in:`org.jruby.util.io.EncodingUtils.econvOpts`

**Comment by headius** [comment]
@MariuszCwikla Oh thanks for that! Yes it seems like we already have the logic in place, and I was wrong about my usage. Thank you!
