### ISSUE TITLE
Invalid `Tracepoint` Behavior for Blocks

### ISSUE THREAD

**Issue by aryeh-looker** [jruby/jruby#5859]
### Environment

* `jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff Java HotSpot(TM) 64-Bit Server VM 25.221-b11 on 1.8.0_221-b11 +jit [darwin-x86_64]`
* `Darwin MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

### Script Under Test

```
$ cat test.rb 
TracePoint.trace(:b_call) { puts 'called' }
do_thing = proc { puts 'thing done' }
do_thing[]
```

### Behavior Under MRI

```
$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
$ ruby test.rb 
called
thing done
```

### Behavior under JRuby 9.2.8.0

```
$ ruby --version
jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff Java HotSpot(TM) 64-Bit Server VM 25.221-b11 on 1.8.0_221-b11 +jit [darwin-x86_64]
$ JRUBY_OPTS="--debug" ruby test.rb 
thing done
```

**Comment by aryeh-looker** [comment]
Looks like not specifying an event name or using `:line` could be a sound workaround for some use-cases:

```
$ cat test.rb 
TracePoint.trace { |tp| puts [tp.event, tp.lineno].inspect }        # 1
do_thing = proc { puts 'thing done' }                               # 2
do_thing[]                                                          # 3
$ JRUBY_OPTS="--debug" ruby test.rb 
[:line, 1]
[:line, 2]
[:line, 1]
thing done
```

**Comment by headius** [comment]
Looks like we are missing a `:b_call` event along some path. Probably an easy fix.

**Comment by enebo** [comment]
@aryeh-looker :line itself appears to be an off by one bug and I don't actually see any place we emit b_call (although we do have it defined).  So two bugs found!

**Comment by enebo** [comment]
I fixed a serious of problems with TracePoint including fixing line numbers being +1 and also b_call.  

@aryeh-looker you should see a lot more events now with a default trace.  We were erroneously only emitting :line as a default before.
