### ISSUE TITLE
reporting a better error when tmp doesn't work for temporary executables

### ISSUE THREAD

**Issue by jacaetevha** [jruby/jruby#5900]
### Environment

* JRuby version: `9.2.8.0`
* OS: `Linux vpna-dev-tmc039.ad-dev.issgovernance.com 3.10.0-1062.1.1.el7.x86_64 #1 SMP Tue Aug 13 18:39:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

### Expected Behavior

When packing up a JRuby application as an executable JAR via `warble`, the app may crash if the temp directory (`/tmp` by default on most *nix systems) is mounted as read-only or `noexec`. A useful error message that instructs the user to set a temp directory to some user-space would be helpful. E.g. `/tmp is mounted as read-only or noexec. Some native extensions may not work properly. Try setting the "java.io.tmpdir" variable to a directory that is writeable and executable by your process, if you run into errors with native extensions.`

### Example Application

**example/bin/example**

```ruby
require 'irb'
IRB.start(__FILE__)
```

**config/warble.rb**

```ruby
Warbler::Config.new do |config|
  config.features = %w(gemjar)
  config.includes = FileList["script.rb"]
  config.jar_extension = "jar"
  config.autodeploy_dir = "dist/"
  config.bytecode_version = "1.8"
end
```

```shell
warble
java -jar example.jar # throws an error if /tmp is noexec or read-only
```

### Actual Behavior

When `/tmp` is mounted as `noexec` an error similar to the following is written to the console: 

```shell
NotImplementedError: fstat unimplemented unsupported or native support failed to load; see https://github.com/jruby/jruby/wiki/Native-Libraries
  initialize at org/jruby/RubyIO.java:1015
        open at org/jruby/RubyIO.java:1156
  initialize at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/input-method.rb:141
  initialize at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb/context.rb:70
  initialize at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:410
       start at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/irb.rb:381
      <main> at dbconsole/bin/dbconsole:10
        load at org/jruby/RubyKernel.java:1022
      <main> at uri:classloader:/META-INF/main.rb:1
     require at org/jruby/RubyKernel.java:987
      <main> at uri:classloader:/META-INF/main.rb:1
      <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
ERROR: org.jruby.embed.EvalFailedException: (NotImplementedError) fstat unimplemented unsupported or native support failed to load; see https://github.com/jruby/jruby/wiki/Native-Libraries
```

If you pass `-Djruby.native.verbose=true` to `java`, you'll get more information that indicates that `/tmp` may be the problem (e.g. [this gist](https://gist.github.com/jacaetevha/dcb39e2b3c227c26503fb7c958358c6c)).

**Comment by headius** [comment]
Read-only bug is at #1302. A suggestion there is that we could pick a different location, either by default or only when we detect that the default tmp location won't work.

However, it's not clear how we can tell tmp won't work unless we try to make it work. As it is, we are not the ones unpacking the native library; that is done by either jnr-ffi or jffi (I don't recall).

So we definitely need a better error or warning when tmp is unusable, and ideally a simple way to fall back to some other location (which is likely a change to the appropriate JNR library).

**Comment by headius** [comment]
@jacaetevha I am going to basically use the text you provided. Coming up with alternative directory fallback seems fraught with problems, so I'm going to prefer having a warning/error indicating that native support failed to load due to a filesystem issue.

**Comment by jacaetevha** [comment]
👍 Thanks, @headius.

**Comment by headius** [comment]
I have a patch for JFFI that will enhance the existing errors by indicating what failed and how to remedy it.

For  read-only temp location, you'll see the following in `jruby.native.verbose` output:

```
... Unable to write jffi binary stub to `/nowrite`. Set `TMPDIR` or Java property `java.io.tmpdir` to a read/write path that is not mounted "noexec".
```

And for a noexec temp location, the error will be like this:

```
... Unable to execute or load jffi binary stub from `/dev/shm`. Set `TMPDIR` or Java property `java.io.tmpdir` to a read/write path that is not mounted "noexec".
```

There's multiple levels of exception-handling and wrapping in this logic, unfortunately, so this message appears somewhat deep in a chain of exceptions...but it's a better error with a remedy.

**Comment by jacaetevha** [comment]
That first error is off a bit...

```diff
< ... Unable to write jffi binary stub to `/nowrite`. Set `TMPDIR` or Java property `java.io.tmpdir` to a read/write path that is not mounted "noexec".
> ... Unable to write jffi binary stub to `/nowrite`. Set `TMPDIR` or Java property `java.io.tmpdir` to a read/write path that is not mounted "readonly".
```

**Comment by headius** [comment]
I think the original is right...the path needs to be readable and writable (implying it is not readonly) and must not be mounted "noexec" (which is not the same as +x, so I wasn't sure of a better way to say this in few words).

Note I'm using the same remedy for both since the first thing someone might see is a read-only temp and the second thing they might see is noexec, so in both errors the remedy is to set temp to a read-only, non-noexec path.

**Comment by jacaetevha** [comment]
Ah, gotcha. Thanks for getting to this so quickly!
