### ISSUE TITLE
Java::JavaLang::Throwable missing full_message method

### ISSUE THREAD

**Issue by davishmcclurg** [jruby/jruby#5906]
I don't know if this is expected behavior, but I was surprised that `Java::JavaLang::Throwable` does not implement `full_message`:

```
irb(main):011:0> JRUBY_VERSION
=> "9.2.8.0"
irb(main):012:0> Java::JavaLang::Throwable.new('ugh').full_message
Traceback (most recent call last):
        6: from /Users/dharsha/.rbenv/versions/jruby-9.2.8.0/bin/irb:13:in `<main>'
        5: from org/jruby/RubyKernel.java:1193:in `catch'
        4: from org/jruby/RubyKernel.java:1193:in `catch'
        3: from org/jruby/RubyKernel.java:1425:in `loop'
        2: from org/jruby/RubyKernel.java:1061:in `eval'
        1: from (irb):12:in `evaluate'
NoMethodError (undefined method `full_message' for java.lang.Throwable: ugh:Java::JavaLang::Throwable)
Did you mean?  message
irb(main):013:0> StandardError.new('ugh').full_message
=> "(irb):12: ugh (StandardError)\n"
```

**Comment by kares** [comment]
throwable is the more general Java object here and Ruby exceptions are throwables :)
but yeah, the concern is valid as JRuby makes throwables Ruby Exception-like.

you could setup `full_message` as an alias to `inspect`, it would likely get merged ...
https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/javasupport/ext/JavaLang.java#L244 (the format would be slightly different but I think its a fine start)
