### ISSUE TITLE
Exception inspect in wrong encoding

### ISSUE THREAD

**Issue by jlahtinen** [jruby/jruby#5923]
### Environment

Seems to be problem since 1.7.27 (probably earlier also).
My console encoding:

    $ echo $LANG
    en_GB.utf8

### Expected Behavior

cruby gives excepted output for inspect:

    $ ruby -e 'e = Exception.new "å"; puts "#{RUBY_PLATFORM} - #{RUBY_VERSION} - #{e} - #{e.inspect}"'
    x86_64-linux - 2.5.3 - å - #<Exception: å>

### Actual Behavior

jruby behaviour:

    $ ruby -e 'e = Exception.new "å"; puts "#{RUBY_PLATFORM} - #{RUBY_VERSION} - #{e} - #{e.inspect}"'
    java - 2.5.3 - å - #<Exception: Ã¥>

Seems like "å" is read inside exception as  ISO-8859-1 and ouputted as encoded "UTF-8"

    $ ruby -e 'puts "å".force_encoding("ISO-8859-1").encode("UTF-8")'
    Ã¥

**Comment by enebo** [comment]
Note: Our inspect code internally is building a String up using a StringBuilder and not our newer str() methods (which assumes all string data will end up being in Java's default charset).  We just need to change this code to use our newer APIs.
