### ISSUE TITLE
Inner Java classes are nested recursively

### ISSUE THREAD

**Issue by MariuszCwikla** [jruby/jruby#5925]
jruby 9.2.9.0-SNAPSHOT (2.5.3) 2019-10-14 a8807f2 Java HotSpot(TM) 64-Bit Server VM 25.171-b11 on 1.8.0_171-b11 +jit [mswin32-x86_64]

I discovered simple bug while working on another issue #2639. Below is output from JIRB:

Actual Behavior:

```
irb(main):001:0> Java::JavaAwt::Desktop::Action
=> Java::JavaAwt::Desktop::Action
irb(main):002:0> Java::JavaAwt::Desktop::Action::Action
=> Java::JavaAwt::Desktop::Action
irb(main):003:0> Java::JavaAwt::Desktop::Action::Action::Action
=> Java::JavaAwt::Desktop::Action
```

Expected Behavior:

2nd and 3rd should result with `NameError` (there is no class `java.awt.Desktop.Action.Action.Action`).
Only 1st case is correct.

**Comment by headius** [comment]
Well that's a weird one! Thanks for the PR!

**Comment by edipofederle** [comment]
@headius / @kares I think this one could be closed as well. Could you please check it? thx
