### ISSUE TITLE
TypeError: "warn" with subclass of String constructed from heredoc

### ISSUE THREAD

**Issue by buehmann** [jruby/jruby#5935]
### Environment

```console
$ jruby -v
jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff OpenJDK 64-Bit Server VM 13+33 on 13+33 +jit [darwin-x86_64]
$ uname -a
Darwin mb204.fidor.loc 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin
```

### Expected Behavior

The script
```ruby
S = Class.new(String)

warn S.new("foo")
warn S.new(<<M)
bar
M
```
is expected to output
```
foo
bar
```
to stderr.

### Actual Behavior

Instead JRuby raises a TypeError for the second warning (heredoc case):
```
foo
TypeError: wrong argument type S (expected String)
    warn at org/jruby/common/RubyWarnings.java:224
  <main> at jruby-bug.rb:4
```

This was originally observed with the `rainbow` gem (https://github.com/sickill/rainbow) here: https://circleci.com/gh/rubocop-hq/rubocop/72166

**Comment by enebo** [comment]
This seems to be a precedence problem in the parser.  If I add a puts into that before that heredoc case it never prints.  Likely this is a one word fix but will it be easy? :)

**Comment by enebo** [comment]
derp...this has nothing to do with parser.  I just realized locally for me neither case works (I had put my puts between the two).   Now for the twist!  9.2.8.0 the first case works????  In both cases these are strings so this is strange.  Too strange to ignore for 9.2.9.0

**Comment by enebo** [comment]
Ok it took me longer to write my two comments then to actually figure this out.  We were using a type check method which expects an exact match on warn argument being a String versus a kind-of String.  Verifying something about protocol conversion before committing a fix.

**Comment by enebo** [comment]
Circling back on why the first case stopped working since 9.2.8.0...@kares had recently added some kwargs support to warn and what changed happened to change both into hitting the same incorrect typeconverter type check (I believe it from no newline strings performing a strDup which made first call work but it is enough for me to know I fixed both with my commit).

**Comment by buehmann** [comment]
Thanks for the quick response! You're right: The important difference between the cases seems to be the trailing newline character, not the heredoc.

In 9.2.8.0:
```ruby
warn S.new("foo\n")   # TypeError (wrong argument type S (expected String))
warn S.new(<<M.chomp) # works
bar
M
```
