### ISSUE TITLE
Requiring gems from embedded JRuby takes much longer than from irb

### ISSUE THREAD

**Issue by ljorquera** [jruby/jruby#5962]
### Environment

The issue happens using JRuby embedded into a Java application. JRuby version is  9.1.17.0.  

I noticed that requiring some gems takes a long time (8 - 10 seconds). We require the gems from a Ruby script that we require from a ScriptingContainer. 

In order to measure acurately the time, I replaced require with a method that puts the time it took to actually require a file/gem:

```
 require 'date'
    class << self
      alias_method :original_require,:require
    end
def self.require(file)

    now = DateTime.now
    original_require file
    t = (DateTime.now - now).to_f * 24 * 60 * 60
    puts "require #{file} took #{t} seconds"
end

```

### Expected Behavior
requiring 'yaml' from jruby irb took 0.268 seconds and showed the following  partial times:

require psych/versions took 0.0009999999999999998 seconds
require psych.jar took 0.0019999999999999996 seconds
require jar_dependencies took 0.007 seconds
require jar-dependencies took 0.009 seconds
require cgi/core took 0.009 seconds
require cgi/escape took 0.003 seconds
require cgi/util took 0.013000000000000001 seconds
require cgi/cookie took 0.017 seconds
require cgi/util took 0.0 seconds
require cgi took 0.028 seconds
require uri took 0.0 seconds
require rubygems/uri_formatter took 0.029 seconds
require psych_jars took 0.057 seconds
require psych/exception took 0.0009999999999999998 seconds
require stringio took 0.0009999999999999998 seconds
require psych/omap took 0.0009999999999999998 seconds
require psych/set took 0.0019999999999999996 seconds
require psych/class_loader took 0.011 seconds
require strscan took 0.018 seconds
require psych/scalar_scanner took 0.026000000000000002 seconds
require psych/nodes/node took 0.046 seconds
require psych/nodes/stream took 0.007 seconds
require psych/nodes/document took 0.0009999999999999998 seconds
require psych/nodes/sequence took 0.0009999999999999998 seconds
require psych/nodes/scalar took 0.0009999999999999998 seconds
require psych/nodes/mapping took 0.0009999999999999998 seconds
require psych/nodes/alias took 0.0019999999999999996 seconds
require psych/nodes took 0.065 seconds
require psych/streaming took 0.0019999999999999996 seconds
require psych/visitors/visitor took 0.003 seconds
require psych/scalar_scanner took 0.0009999999999999998 seconds
require psych/class_loader took 0.0 seconds
require psych/exception took 0.0 seconds
require psych/visitors/to_ruby took 0.012 seconds
require psych/visitors/emitter took 0.0019999999999999996 seconds
require psych/handler took 0.0009999999999999998 seconds
require psych/tree_builder took 0.005000000000000001 seconds
require psych/scalar_scanner took 0.0009999999999999998 seconds
require psych/class_loader took 0.0 seconds
require psych/visitors/yaml_tree took 0.012 seconds
require psych/json/ruby_events took 0.0009999999999999998 seconds
require psych/visitors/json_tree took 0.003 seconds
require psych/visitors/depth_first took 0.0009999999999999998 seconds
require psych/visitors took 0.036 seconds
require psych/handler took 0.0019999999999999996 seconds
require psych/tree_builder took 0.0009999999999999998 seconds
require psych/parser took 0.0019999999999999996 seconds
require psych/omap took 0.0009999999999999998 seconds
require psych/set took 0.003999999999999999 seconds
require psych/coder took 0.0019999999999999996 seconds
require psych/y took 0.0019999999999999996 seconds
require psych/core_ext took 0.005000000000000001 seconds
require psych/stream took 0.0019999999999999996 seconds
require psych/json/yaml_events took 0.0019999999999999996 seconds
require psych/json/tree_builder took 0.003999999999999999 seconds
require psych/json/ruby_events took 0.0 seconds
require psych/json/yaml_events took 0.0009999999999999998 seconds
require psych/json/stream took 0.003 seconds
require psych/tree_builder took 0.006 seconds
require psych/handlers/document_stream took 0.007999999999999998 seconds
require psych/class_loader took 0.003 seconds
require psych took 0.267 seconds
require yaml took 0.268 seconds

### Actual Behavior

requiring yaml in the embedded context took 8.889 seconds and showed the following partial times:

 require psych/versions took 0.114 seconds  
 require psych.jar took 0.113 seconds  
 require jar_dependencies took 0.114 seconds  
 require jar-dependencies took 0.232 seconds  
 require socket.so took 0.30899999999999994 seconds  
 require io/wait took 0.11800000000000002 seconds  
 require socket took 0.5409999999999999 seconds  
 require timeout took 0.12399999999999997 seconds  
 require io/wait took 0.027000000000000003 seconds  
 require net/protocol took 0.802 seconds  
 require uri took 0.033 seconds  
 require net/http/exceptions took 0.11499999999999998 seconds  
 require net/http/header took 0.12299999999999998 seconds  
 require net/http/generic_request took 0.129 seconds  
 require net/http/request took 0.12299999999999998 seconds  
 require net/http/requests took 0.11700000000000002 seconds  
 require net/http/response took 0.12200000000000001 seconds  
 require net/http/responses took 0.131 seconds  
 require net/http/proxy_delta took 0.11499999999999998 seconds  
 require net/http/backward took 0.11800000000000002 seconds  
 require net/http took 2.295 seconds  
 require thread took 0.022 seconds  
 require time took 0.034999999999999996 seconds  
 require rubygems/util took 0.113 seconds  
 require rubygems/user_interaction took 0.24700000000000003 seconds  
 require rubygems/request/http_pool took 0.12200000000000001 seconds  
 require rubygems/request/https_pool took 0.125 seconds  
 require thread took 0.022 seconds  
 require rubygems/request/connection_pools took 0.147 seconds  
 require rubygems/request took 3.127 seconds  
 require cgi took 0.020000000000000004 seconds  
 require uri took 0.023 seconds  
 require rubygems/uri_formatter took 0.16400000000000003 seconds  
 require psych_jars took 3.914 seconds  
 require psych/exception took 0.12100000000000002 seconds  
 require stringio took 0.021 seconds  
 require psych/omap took 0.113 seconds  
 require psych/set took 0.113 seconds  
 require psych/class_loader took 0.362 seconds  
 require strscan took 0.022 seconds  
 require psych/scalar_scanner took 0.14100000000000001 seconds  
 require psych/nodes/node took 0.635 seconds  
 require psych/nodes/stream took 0.11499999999999998 seconds  
 require psych/nodes/document took 0.12200000000000001 seconds  
 require psych/nodes/sequence took 0.12100000000000002 seconds  
 require psych/nodes/scalar took 0.12 seconds  
 require psych/nodes/mapping took 0.113 seconds  
 require psych/nodes/alias took 0.131 seconds  
 require psych/nodes took 1.463 seconds  
 require psych/streaming took 0.12100000000000002 seconds  
 require psych/visitors/visitor took 0.12299999999999998 seconds  
 require psych/scalar_scanner took 0.023 seconds  
 require psych/class_loader took 0.031999999999999994 seconds  
 require psych/exception took 0.031999999999999994 seconds  
 require psych/visitors/to_ruby took 0.221 seconds  
 require psych/visitors/emitter took 0.132 seconds  
 require psych/handler took 0.11499999999999998 seconds  
 require psych/tree_builder took 0.224 seconds  
 require psych/scalar_scanner took 0.027000000000000003 seconds  
 require psych/class_loader took 0.031999999999999994 seconds  
 require psych/visitors/yaml_tree took 0.40499999999999997 seconds  
 require psych/json/ruby_events took 0.11 seconds  
 require psych/visitors/json_tree took 0.241 seconds  
 require psych/visitors/depth_first took 0.11899999999999998 seconds  
 require psych/visitors took 1.3630000000000002 seconds  
 require psych/handler took 0.029 seconds  
 require psych/tree_builder took 0.034 seconds  
 require psych/parser took 0.11700000000000002 seconds  
 require psych/omap took 0.04100000000000001 seconds  
 require psych/set took 0.025 seconds  
 require psych/coder took 0.137 seconds  
 require psych/core_ext took 0.12299999999999998 seconds  
 require date took 0.021 seconds  
 require psych/deprecated took 0.144 seconds  
 require psych/stream took 0.11899999999999998 seconds  
 require psych/json/yaml_events took 0.10899999999999999 seconds  
 require psych/json/tree_builder took 0.228 seconds  
 require psych/json/ruby_events took 0.021 seconds  
 require psych/json/yaml_events took 0.023 seconds  
 require psych/json/stream took 0.16400000000000003 seconds  
 require psych/tree_builder took 0.022 seconds  
 require psych/handlers/document_stream took 0.16499999999999998 seconds  
 require psych/class_loader took 0.03 seconds  
 require psych took 8.806 seconds  
 require yaml took 8.889 seconds  

This does not happen only with yaml, all required gems take a lot longer to load in embedded environment.

**Comment by enebo** [comment]
This appears to be an issue with 9.1.17.0 probably not caching jar contents internally (my educated guess).  JRuby 9.1.17.0 is no longer supported unfortunately.  If you have to use 9.1.17.0 you could bisect JRuby 9.2.x and see when performance started to improve.

For JRuby 9.2.9.0 on my machine jruby-complete loading taked 0.28s but running from a JRuby install takes 0.32s.  There is a little noise there but no significant difference.

**Comment by ljorquera** [comment]
I can confirm that upgrading to 9.2.9.0 improve the performance a lot. Thanks!

**Comment by enebo** [comment]
@ljorquera happy you were able to run with the newer version.  It always makes us unhappy to tell people are not supporting an older version.
