### ISSUE TITLE
jruby.bash in v9.1.17.0 release tar is different from that in tag

### ISSUE THREAD

**Issue by mvz** [jruby/jruby#5974]
### Environment

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
```
ruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 11.0.5+10-post-Debian-2 on 11.0.5+10-post-Debian-2 [linux-x86_64]
```
* Operating system and platform (e.g. `uname -a`)
```
Linux bean 5.3.0-2-amd64 #1 SMP Debian 5.3.9-1 (2019-11-09) x86_64 GNU/Linux
```

Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables

N/A

### Expected Behavior

I can look at the code in the `9.1.17.0` tag in GitHub to see how `jruby.bash` behaves, in particular, whether it is expected to set any `--add-opens` in JAVA_OPTS

### Actual Behavior

The code in GitHub doesn't add `--add-opens`, but when I download and install JRuby 9.1.17.0 with ruby-install, the `bin/jruby.bash` file contains:
```
  # Add base opens we need for Ruby compatibility
  JAVA_OPTS="$JAVA_OPTS --add-opens java.base/java.io=org.jruby.dist --add-opens java.base/java.nio.channels=org.jruby.dist --add-opens java.base/sun.nio.ch=org.jruby.dist"
```

### Why is this a problem

When running JRuby with these flags, Java claims the `org.jruby.dist` module doesn't exist, causing JRuby to emit warnings. In turn, this causes build failures on Travis CI, without any possibility of correcting the erroneous JAVA_OPTS.

The warnings look like this:

```
WARNING: Unknown module: org.jruby.dist specified to --add-opens
```

An example of a failed build is this: https://travis-ci.org/troessner/reek/builds/611542039

**Comment by kares** [comment]
sounds like a ruby-install thing ... trying to play it smart and support 9.2 well on Java 9+
JRuby 9.1 did not have a module name so it won't work, recommend raising this as ruby-install

**Comment by mvz** [comment]
Hi @kares, thanks for your response. If I understand you correctly, you're suggesting jruby.bash is generated by ruby-install. However, the linked build on Travis uses rvm, and seems to show the same problem.

**Comment by mvz** [comment]
I don't know what happened, but I can't reproduce this anymore with my local jruby 9.1 installed with `ruby-install`. I also can't find anything in `rvm` that could be responsible for this so I've brought this up with Travis CI.
