### ISSUE TITLE
Run jruby on rails application using JRUBY_HOME on wildfly jboss server

### ISSUE THREAD

**Issue by abhichvn** [jruby/jruby#5980]
Scenario:
We have a case where our jruby on rails application should be run on wildfly (jboss) application server using JRUBY_HOME environment variable. This is needed as the jruby on rails application is using jruby to run ruby script as seperate process within an application.

This can be previously possible as we are using https://github.com/torquebox/torquebox which uses JRUBY_HOME.

Now as we are trying to upgrade to latest jboss application server which is wildfly 18, we wanted to support same behaviour.

Currently we can have the same behaviour by putting jruby jars "jruby-core-*", "jruby-stdlib-*" inside WEB-INF/lib folder and use JRUBY_HOME/bin/jruby to run ruby script.

This way it solves the purpose but there are 2 executables of jruby JRUBY_HOME and WEB-INF/lib/jruby-*.jar.

We want to use only JRUBY_HOME which is previously supported by https://github.com/torquebox/torquebox

**Comment by abhichvn** [comment]
After searching little bit more I find following which will run ruby file from java
=> java -cp %JRUBY_HOME%/lib/jruby.jar -Djruby.home=%JRUBY_HOME% org.jruby.Main test.rb

So here jruby.jar has to be in classpath and jruby.home property should be pointed to jruby installed location

**Comment by headius** [comment]
@abhichvn Thanks for following up!
