### ISSUE TITLE
Drip - mkdir: cannot create directory  File exists

### ISSUE THREAD

**Issue by rwilliams** [jruby/jruby#5982]
### Environment

jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [linux-x86_64]

**Host OS - WSL2**
Linux 975c34fa2e2c 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Docker Container**
GNU/LinuxDistributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch

**Gem/Framework info:**
Rails 6.1 nothing too exciting
dripmain.rb
`# Rails project:
require_relative 'config/application'`

**Environment variables**
JRUBY_OPTS=--dev
ENV JAVACMD=drip
ENV DRIP_INIT_CLASS=org.jruby.main.DripMain

### Expected Behavior
I expect `rails routes` to show routes and run fast after drip caching.

### Actual Behavior
I get the following error `mkdir: cannot create directory ‘/home/user/.drip/0.2.5/6d31047b091d93d5df4a320927084918f4f5928f/9-1’: File exists` and rails commands run at regular slow speeds.

**Comment by headius** [comment]
I'm not sure there's anything we can do here. It seems like this is a bug in Drip, but Drip appears to be unmaintained at this point. We have also chatted since this bug was filed about EOLing Drip and Nailgun support in favor of tools like Theine.

**Comment by rwilliams** [comment]
@headius I put a little bit of work into drip when i was messing with this https://github.com/rwilliams/drip The original test suite passes except for 1 test. 

I did quite a bit of debugging on it with my rails app but couldn't really pin anything down. It seems as though it tries to spin up multiple VM's and that is why we're seeing this error.
