### ISSUE TITLE
java.lang.module.ResolutionException

### ISSUE THREAD

**Issue by aonemd** [jruby/jruby#5988]
### Environment

* `jruby-9.2.9.0` installed via `ruby-install`

* Arch Linux with kernel `5.3.13`

* Application/framework version (e.g. Rails, Sinatra)
```
$ java -version

openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)
```

* Environment variables
```
export JAVA_HOME='/usr/lib/jvm/java-10-openjdk'
export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
```

### Expected Behavior

```
$ jruby -v

# should print the version number
```

### Actual Behavior

```
$ jruby -v

Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module org.jruby.dist contains package javax.annotation, module java.xml.ws.annotation exports package javax.annotation to org.jruby.dist
```

**Comment by headius** [comment]
I don't think we need anything from that package at runtime, so I'll make sure it's not being included in the jar.

**Comment by headius** [comment]
Should be fixed on master. I've filtered out the javax.annotation artifact from all shaded jars.
