### ISSUE TITLE
Invalid OSGi metadata

### ISSUE THREAD

**Issue by rmannibucau** [jruby/jruby#5991]
Hi,

the manifest - at least of jruby-complete - contains a JavaSE requirement of the v9 instead of v8.
this is a bug in bnd - transitively from maven-bundle-plugin - which does not ignore module-info.class out of the box, see https://issues.liferay.com/browse/LPS-98289?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aworklog-tabpanel

guess it should be fixed cause today jruby can't be used on java 8 in OSGi.

**Comment by headius** [comment]
Ahh good find. We'll see about getting this fixed up.

@mkristian Any suggestion here?

**Comment by headius** [comment]
This patch did not appear to help:

```
diff --git a/pom.rb b/pom.rb
index baee376e0f..4a6c5006a2 100644
--- a/pom.rb
+++ b/pom.rb
@@ -98,7 +98,8 @@ project 'JRuby', 'https://github.com/jruby/jruby' do
               'Bundle-Name' =>  '${bundle.name} ${project.version}',
               'Bundle-Description' =>  '${bundle.name} ${project.version} OSGi bundle',
               'Bundle-SymbolicName' =>  '${bundle.symbolic_name}'
-            } ) do
+            },
+            '_noee' => true) do
       dependency(groupId: 'biz.aQute.bnd', artifactId: 'biz.aQute.bndlib', version: '3.5.0')
       execute_goals( 'manifest',
                      :phase => 'prepare-package' )
diff --git a/pom.xml b/pom.xml
index 3f290be2cc..43f1873f61 100644
--- a/pom.xml
+++ b/pom.xml
@@ -201,6 +201,7 @@ DO NOT MODIFIY - GENERATED CODE
               <Bundle-Description>${bundle.name} ${project.version} OSGi bundle</Bundle-Description>
               <Bundle-SymbolicName>${bundle.symbolic_name}</Bundle-SymbolicName>
             </instructions>
+            <_noee>true</_noee>
           </configuration>
         </plugin>
         <plugin>
```

A jruby-complete build after this still had the following line:

```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=9.0))"
```

**Comment by rmannibucau** [comment]
A few options if it helps:

1. Upgrade bnd (as a bundle plugin dependency), this issue is supposed fixed
2. Just explicitly set this attribute with version 1.8

**Comment by rotty3000** [comment]
should just need an update of plugin that uses bnd, this is fixed upstream: https://github.com/bndtools/bnd/commit/62d1dec07e2f5d6222ab09ef172a54169a559dd6

according to tags that fix is in the 4.3.0.REL release.

**Comment by rotty3000** [comment]
- if using the `maven-bundle-plugin` you can:
1) update to it's latest: 4.2.1
2) give it an explicit depedency of `biz.aQute.bnd:biz.aQute.bndlib:4.3.1`

- if using `bnd-maven-plugin` directly, just update to 4.3.1 (latest)

**Comment by mkristian** [comment]
hmm still seeing
```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=9.0))"
```

**Comment by rmannibucau** [comment]
@mkristian https://github.com/jruby/jruby/pull/5999 fix JavaSE version

**Comment by mkristian** [comment]
@rmannibucau thanks, #5998 only changed the pom.xml - did not see that

**Comment by mkristian** [comment]
with #5999 I could reproduce the desired result
```
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```

**Comment by rotty3000** [comment]
yeah, my solution wasn't complete! thanks @rmannibucau both parts should be merged I guess ;)

**Comment by headius** [comment]
Thanks for the collab, folks!
