### ISSUE TITLE
http://rubygems-proxy.torquebox.org is unmaintained and insecure

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby#6003]
The default gem [jar-dependencies](https://github.com/mkristian/jar-dependencies) hits http://rubygems-proxy.torquebox.org, from what I understand in order to get a maven-compatible listing of the maven jar dependencies of a gem. For example this is required to resolve the maven jar dependencies of the [psych gem](https://github.com/ruby/psych). Other gems like [jbundler](https://github.com/mkristian/jbundler) also end up hitting this URL for the same reason.

There was a recent outage of  http://rubygems-proxy.torquebox.org, which got me looking in to it. It turns out that bbrowning has made the [following comment last May](https://github.com/jruby-gradle/jruby-gradle-plugin/issues/349#issuecomment-496564438):

> The rubygems-proxy.torquebox.org server is unmaintained and has been that way for a few years. I'd strongly suggest anything referencing it point to something else.

In addition, this URL isn't available over `https`. Considering that installing default gems and others depends on this URL, it would be great if an officially maintained, secure instance could be run somewhere like https://rubygems-proxy.jruby.org.

(tagging @mkristian since he's the primary contributor of jar-dependencies and jbundler)

**Comment by mkristian** [comment]
@mohamedhafez there is no need to use this proxy anymore and I thought all the implementations moved away from using this proxy: ruby-maven, jar-dependencies and jbundler. only gradle jruby plugin still depends on this. but let me double check. also be so kind and provide a usecase where you think any of this jar-dependencies and/or jbundler hits this torquebox proxy

**Comment by mohamedhafez** [comment]
@mkristian just doing `jbundle install` was giving me errors like the following earlier today:

> *** [err :: localhost] INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://rubygems-proxy.torquebox.org:80: Connection reset

It would keep retrying over and over until a request finally went through.

My Jarfile:

```
jar 'com.turo:pushy', '0.13.9'
jar 'org.slf4j:slf4j-simple', '1.7.25'
jar 'com.google.firebase:firebase-admin', '6.9.0'
```

Now that http://rubygems-proxy.torquebox.org/ is up again, things are working fine, even thought there are reports that its just that landing page that is working, and that actually trying to use the proxy is returning 503's (https://github.com/torquebox/rubygems-servlets/issues/20#issuecomment-567282372 and https://github.com/torquebox/rubygems-servlets/issues/20#issuecomment-567332985)

Perhaps [these code references](https://github.com/mkristian/jbundler/search?q=rubygems-proxy.torquebox.org&unscoped_q=rubygems-proxy.torquebox.org) to http://rubygems-proxy.torquebox.org/releases are causing something to at least make sure the proxy is up and running, even if it's not using it? 

--

There's also [this issue](https://github.com/ruby/psych/issues/427) claiming that running `gem install psych` was causing the same error, although its not any more now that http://rubygems-proxy.torquebox.org/ is back up. I'm guessing that's due to a similar issue with jar-dependencies

**Comment by mkristian** [comment]
@mohamedhafez thanks a lot - I will have a look and get this proxy out of the equation.

**Comment by dhanugupta** [comment]
@mohamedhafez http://rubygems-proxy.torquebox.org/  is down again..can you please take a look.

**Comment by dhanugupta** [comment]
@mohamedhafez any update to get this proxy up?

**Comment by mohamedhafez** [comment]
@dhanugupta it sounds like jruby and jbundler don't really use this proxy, with only some old code that unnecessarily checks that http://rubygems-proxy.torquebox.org/ and http://rubygems-proxy.torquebox.org/releases/ are up (they don't care that its not actually serving artifacts anymore). It sounds like that old code is going to be removed so that JRuby and jbundler don't depend on this proxy in any way at all. According to https://github.com/torquebox/rubygems-servlets/issues/20, that proxy isn't coming back, so you're better off moving to something else if you depend on that proxy for something

**Comment by headius** [comment]
I don't think this proxy should be needed anymore if users can switch to using maven gems support that @mkristian has put together for maven, yes? I admit I don't know how that would work in jruby-gradle though.

If it is necessary to get such a proxy set up permanently, we could run it ourselves or try to get an existing Maven host (like Sonatype) to run it for us.

**Comment by mkristian** [comment]
there are some old poms which declares this proxy as repository. but if jruby or jbundler or jar-dependencies do not rely on them but do add them into the list of possible maven repositories. any maven project can use https://github.com/torquebox/mavengem/tree/master/mavengem-wagon

gradle jruby plugin can be configured to launch a in process proxy, other tools like scala sbt would need such a proxy.

**Comment by mkristian** [comment]
I found 2 poms on my machine locally which 
```
repository/rubygems/jruby-openssl/0.10.1/jruby-openssl-0.10.1.pom:      <url>http://rubygems-proxy.torquebox.org/releases</url>
repository/rubygems/jruby-readline/1.3.7/jruby-readline-1.3.7.pom:      <url>http://rubygems-proxy.torquebox.org/releases</url>
```
i.e. need to update toolchain for these projects to not declare these repositories.

**Comment by mohamedhafez** [comment]
@mkristian doing a recursive grep for `torquebox.org` on my rvm directory, also found the following usages:

```
.rvm/gems/jruby-9.2.9.0/gems/maven-tools-1.1.6/spec/gemspec_with_prereleased_dependency_and_no_repo/pom.xml:      <url>http://rubygems-proxy.torquebox.org/prereleases</url>
.rvm/gems/jruby-9.2.9.0/gems/maven-tools-1.1.6/spec/gemspec_with_prereleased_dependency/pom.xml:      <url>http://rubygems-proxy.torquebox.org/prereleases</url>
.rvm/gems/jruby-9.2.9.0/gems/maven-tools-1.1.6/lib/maven/tools/dsl.rb:                                  'http://rubygems-proxy.torquebox.org/prereleases'
```

**Comment by mkristian** [comment]
thanks @mohamedhafez

**Comment by headius** [comment]
We have decided to officially support the proxy server, since there are a number of non-Maven users that need it. In order to have a better path going forward, we've brought the torquebox.org server back up under a new official hostname: mavengems.jruby.org

This is still insecure, and still not running on a server the JRuby team controls, but it is at least a better path forward toward fixing those issues.

We are looking for someone (already hosting public Ruby infrastructure) to donate a server for us to run the proxy on.

We have been discussing this on Matrix at https://matrix.to/#/#jruby:matrix.org so please stop by with any input you have!

**Comment by headius** [comment]
Since this was last updated, the proxy servers have been deprecated and are no longer available. You should instead use updated versions of plugins that use the mavengem protocol. See https://github.com/jruby/mavengem/blob/master/README.md.
