### ISSUE TITLE
Using a refinement breaks block parameters

### ISSUE THREAD

**Issue by philr** [jruby/jruby#6009]
**Environment**

_JRuby version:_

> jruby 9.2.10.0-SNAPSHOT (2.5.7) 2019-12-17 a5b8232 OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-8u232-b09-0ubuntu1~19.04.1-b09 +jit [linux-x86_64]

No command line flags or JRUBY_OPTS set.

_Operating system:_

> Ubuntu 19.04
> Linux ubuntudev 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Expected Behavior**

When running the following code (`ruby test.rb`), I would expect the `block_given?` path to be executed:

```ruby
module Refinement
  refine Object do
    def refinement
    end
  end
end

using Refinement

def test(arg1, arg2, arg3, &block)
  if block_given?
    puts "Called with a block: #{block}"
    yield 'test'
  else
    puts "Called without a block"
  end
end

test(1, 2, 3) {|s| puts s }
```

This should result in the following output:

> Called with a block: #<Proc:0x000055d413a462c0@/tmp/test.rb:20>
> test

**Actual Behavior**

With JRuby, the `else` case is executed instead, resulting in the following output:

> Called without a block

Commenting out the `using Refinement` line results in the correct behaviour.

I've only managed to reproduce the failure when the method has 3 arguments in addition to the block parameter.

**Comment by enebo** [comment]
This just happened to get fixed recently in #6002.   I see proper output when I run thisn ow.
