### ISSUE TITLE
Refinements in eval with binding

### ISSUE THREAD

**Issue by palkan** [jruby/jruby#6017]
**Environment**
  
* JRuby version: jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [linux-x86_64]
* Operating system and platform: Linux c2e6ee70592c 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux

**Expected Behavior**

Expected this script to behave the same way as in MRI 2.6.5:

```ruby
# test.rb
using(Module.new do
  refine String do
    def foo
      "bar"
    end
  end
end)

eval "\n#{<<~'END_of_GUARD'}", binding, __FILE__, __LINE__
  p "foo".foo
END_of_GUARD
```

```sh
$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]

$ ruby test.rb
"bar"
```

**Actual Behavior**

```sh
$ ruby -v
jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [linux-x86_64]

$ ruby test.rb
NoMethodError: undefined method `foo' for "foo":String
Did you mean?  fork
  <main> at tmp/eval_refine.rb:10
    eval at org/jruby/RubyKernel.java:1061
  <main> at tmp/eval_refine.rb:9
```

Moving `using` into `eval` resolves the issue.

**Comment by headius** [comment]
It would appear that the refinement scope is not being seen by the eval scope here.

**Comment by headius** [comment]
I have a fix locally. There does not appear to be any specs... perhaps you could contribute some to https://github.com/ruby/spec?

**Comment by headius** [comment]
FYI I did add one simple spec but it would be great to expand that for other forms of eval + binding.

**Comment by palkan** [comment]
Hey! I found yet another edge case: https://github.com/palkan/ruby-compatibility-examples/blob/master/examples/refine_eval_binding.rb (and failing build: https://github.com/palkan/ruby-compatibility-examples/runs/906167086?check_suite_focus=true).

If I remove `include refinery` (see https://github.com/palkan/ruby-compatibility-examples/commit/3d8ee30d017aad5c1b587db7aae23b3a1787e71d), everything works as expected.
