### ISSUE TITLE
Mixed quotes used in error messages

### ISSUE THREAD

**Issue by Kolano** [jruby/jruby#6026]
**Environment**
* 9.2.9.0
* Ubuntu 19.04

**Expected Behavior**
The same type of quotes should be used on either side of quotes (or appropriate non-matching fancy quotes used, though such should not be preferred).

**Actual Behavior**
Inconsistent quotes are used with a fancy quote on the left-hand side, and a standard single quote on the right...
```
(NoMethodError) undefined method `deep_merge' for #<Hash:0x6b29771f>
```

**Comment by enebo** [comment]
As weird as it is...it is what C Ruby does so we do the same thing...   Here is Ruby 2.5.3:

```text
-e:1:in `<main>': undefined local variable or method `foo' for main:Object (NameError)
```
