### ISSUE TITLE
Deprecation warning message : Gem::ConfigMap

### ISSUE THREAD

**Issue by mistergibson** [jruby/jruby#6030]
/opt/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:34: warning: constant Gem::ConfigMap is deprecated
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/jruby-9.2.9.0/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.

So, it seems an update of the script is in order. Note: everything WORKS fine, but you might have issues down the road leaning upon deprecated forms of code.

Thank you for creating something wonderful : I love JRuby.

**Comment by headius** [comment]
Perhaps just needs an update of RubyGems. I started that here, but ran into some failures due to new RG code: #5995.

**Comment by headius** [comment]
Strange...I don't see that warning nor do I see us accessing `ConfigMap` in `rubygems/defaults/jruby.rb`.

**Comment by headius** [comment]
Fixed by #5966.
