### ISSUE TITLE
What's a good way to install JRuby in Windows CI?

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6042]
I'd like to provide JRuby on Windows for https://github.com/eregon/use-ruby-action.

I first tried to download https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.9.0/jruby-dist-9.2.9.0-bin.tar.gz but `bin/jruby.exe` doesn't seem to execute in 64-bit environments.

I then tried https://s3.amazonaws.com/jruby.org/downloads/9.2.9.0/jruby_windows_x64_9_2_9_0.exe and execute it with `./jruby_windows_x64_9_2_9_0.exe -q -dir ~/.rubies/jruby-9.2.9.0`.
That part works fine.

Next I would like to add a `ruby` alias so users can just use `ruby ...` to run their script, and it's interchangeable with MRI.
I tried to copy `jruby.bat` to `ruby.bat` and `jruby.exe` to `ruby.exe`, but that gives:
```
jruby: No such file or directory -- ruby (LoadError)
```
https://github.com/eregon/use-ruby-action/runs/397935518

Which I don't understand what it means.

Other questions:
* Do I need to set any environment variable beyond `PATH`?
* What's the JRuby launcher normally used on Windows? `jruby.bat` that uses `jruby.exe`? `jruby.bash` seems to also work in a bash shell, but it's quite verbose to `jruby.bash ...`.

**Comment by eregon** [comment]
One setup that does seem to work is:
* No `ruby.exe`
* `ruby.bat` with:
```
@ECHO OFF
@"%~dp0jruby.exe" %*
```
(the same as `bin/gem.bat` without `-S gem `)

But I'm not sure whether that's ideal.

FWIW, PATHEXT on GitHUb Actions is `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`

**Comment by headius** [comment]
jruby.exe should work if the environment supports 32-bit executables, but we only build the one binary at the moment. That binary is from https://github.com/jruby/jruby-launcher. It's probably time we got a 64-bit version building for Windows.

I have not tried renaming the executable. It's possible something hardcoded in there expects to see "jruby.exe" on the command line.

The JRuby dist you downloaded should work just fine on Windows unmodified, so it would seem that one of the changes you made is causing some confusion for the native launcher.

**Comment by eregon** [comment]
You're right, jruby.exe in the `.tar.gz` seems to work fine too:
https://github.com/eregon/ruby-install-builder/runs/399733215
Copying `jruby.exe` to `ruby.exe` doesn't work though.

I found the error I got earlier:
https://github.com/eregon/ruby-install-builder/runs/397892437
```
curl --fail -L -O 'https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.9.0/jruby-dist-9.2.9.0-bin.tar.gz'
  mkdir ~/.rubies
  tar xf jruby-dist-9.2.9.0-bin.tar.gz -C ~/.rubies
  cd ~/.rubies/jruby-9.2.9.0/bin
  cp jruby.bat ruby.bat
  cp jruby.exe ruby.exe
  cp jruby ruby

Run ~/.rubies/jruby-9.2.9.0/bin/ruby --version
  ~/.rubies/jruby-9.2.9.0/bin/ruby --version
  shell: C:\Program Files\Git\usr\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
/c/Users/runneradmin/.rubies/jruby-9.2.9.0/bin/ruby: line 155: [: C:\Program: binary operator expected
jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 25.222-b10 on 1.8.0_222-b10 +jit [mswin32-x86_64]

Run ~/.rubies/jruby-9.2.9.0/bin/ruby --version
  ~/.rubies/jruby-9.2.9.0/bin/ruby --version
  shell: C:\Program Files\PowerShell\6\pwsh.EXE -command ". '{0}'"
Program 'ruby.exe' failed to run: The specified executable is not a valid application for this OS platform.At D:\a\_temp\8b8ee3e8-d3c0-4ec2-9181-aebcf3dc47b2.ps1:2 char:1
+ ~/.rubies/jruby-9.2.9.0/bin/ruby --version
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At D:\a\_temp\8b8ee3e8-d3c0-4ec2-9181-aebcf3dc47b2.ps1:2 char:1
+ ~/.rubies/jruby-9.2.9.0/bin/ruby --version
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : NativeCommandFailed
 
##[error]Process completed with exit code 1.
```
So copying `jruby` (which is the same as `jruby.bash`) to `ruby` makes it work in a Bash shell, but fails in a Powershell (instead of finding the .exe/.bat).

Lessons of the issue, on Windows:
* Don't copy `jruby.exe` to `ruby.exe`, that doesn't work.
* Don't copy `jruby` to `ruby`, that doesn't work (on Windows).
* Create `ruby.bat` with `@ECHO OFF\r\n@"%~dp0jruby.exe" %*\r\n`, that works fine.

**Comment by headius** [comment]
There's an argument to be made for us to just ship that ruby.bat you describe, since these days there's really no practical way to run with both JRuby and CRuby in path (which is why we did not always hijack the `ruby` command in the past). I am also thinking we could compile two executables: jruby32.exe and jruby64.exe which ruby.bat will select from based on the host system (assuming that's possible in batch) or which could be copied to ruby.exe directly.

Could you file something about this summary with jruby-launcher?

**Comment by eregon** [comment]
OK, I filed https://github.com/jruby/jruby-launcher/issues/29

**Comment by eregon** [comment]
I'm not sure what would be the advantage of a 64-bit vs 32-bit `jruby.exe`. It seems the existing 32-bit `jruby.exe` works fine for now.

**Comment by headius** [comment]
@eregon When the bits match (launcher + JVM) we can launch JRuby in-process using libjvm. Otherwise we have to spawn a separate process to launch `java`.

**Comment by eregon** [comment]
Oh I see, then it would likely be quite valuable to have a 64-bit launcher.
Doesn't `JRuby 9.2.9.0 Windows Executable (x64)` on https://www.jruby.org/download already contain a 64-bit launcher?

**Comment by headius** [comment]
@eregon I'm not sure what the x64 refers to there. I think it was probably referring to the packed-in JDK.

Ping @enebo
