### ISSUE TITLE
Java 11 Compatibility

### ISSUE THREAD

**Issue by klobuczek** [jruby/jruby#6043]
Would it possible to release some minor 9.2.9.1 that is compatible with Java 11? Otherwise, we would have to revert to 9.2.8.0.

**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
* Operating system and platform (e.g. `uname -a`)

Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables

**Expected Behavior**

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.
* Provide an executable Ruby script or a link to an example repository.

**Actual Behavior**

* Describe or show the actual behavior.
* Provide text or screen capture showing the behavior.

**Comment by headius** [comment]
@klobuczek Can you explain the bugs or issues that are causing you problems? We do have a known method-selection issue in JRuby 9.2.9.0 that will be fixed in 9.2.10.0 but we are strapped for time to release it before some conference work at FOSDEM and RubyFuza.

**Comment by klobuczek** [comment]
@headius those are exactly the bugs I reported previously https://github.com/jruby/jruby/issues/5969. No new issues.
We will be upgrading to neo4j 4.0.0 any day and that requires Java 11. So our only other option is a downgrade to 9.2.8.0. But I didn't mean to rush. Take the time you need.

**Comment by enebo** [comment]
This will be our first priority when we get back from RubyFuza.

**Comment by headius** [comment]
I believe this is already fixed based on #5969. @klobuczek We will be releasing 9.2.10 in the next few days.
