### ISSUE TITLE
libjffi should be rebuilt on darwin (using newer xcode)

### ISSUE THREAD

**Issue by kares** [jruby/jruby#6044]
due hardened security standards on new MacOS versions.

this came as a severe error trying to [notarize](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution) JRuby's files:
(disclaimer: did not run this myself)
```
    {
      "severity": "error",
      "code": null,
      "path": ".../jruby/lib/jni/Darwin/libjffi-1.2.jnilib",
      "message": "The binary uses an SDK older than the 10.9 SDK.",
      "docUrl": null,
      "architecture": "x86_64"
    }
```
... does this mean JRuby would need to drop support for older MacOS versions?

**Comment by kares** [comment]
nice wrap up from AdoptOpenJDK's issue tracker: https://github.com/AdoptOpenJDK/openjdk-build/issues/1130
clearly, this is going to be problematic for anything bundling up JRuby atm (e.g. LogStash).
the first step forward seems to me that the distributed jffi binary (from 2012) to get re-built ...

> In order for your app that is downloaded from the internet to be installed on Catalina (10.15) , it will have to get past the gatekeeper check that it is properly notarized. That happens right now on Catalina.

> What happens on Feb 03 is that you can't get your app notarized by Apple if it doesn't make the bar with regards to code signing and runtime hardening.

> Apple has been in a grace period right now, so that you can submit ANYTHING, and they will notarize it, even if it doesn't make the requirements. After Feb 3, you won't be able to get an app notarized, so you won't be able to distribute a new app without it passing. Of course, In July Apple said that it would be Sepember. In September they said January, and in December they have now said Feb. So they are recognizing that things aren't right and they are going to hurt alot of people by doing so.

**Comment by jsvd** [comment]
This is also requested here: https://github.com/jnr/jffi/issues/74
