### ISSUE TITLE
Dependency convergence errors in 9.2.10.0

### ISSUE THREAD

**Issue by pzygielo** [jruby/jruby#6081]
**Environment Information**
  
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc): 9.2.10.0, maven project
* Operating system and platform (e.g. `uname -a`): Linux

**Expected Behavior**

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.

Dependencies used by JRuby converge to the same version.

* Provide an executable Ruby script or a link to an example repository.

Repository using maven and jruby: [jruby-convergence-errors](https://github.com/pzrep/jruby-convergence-errors)

**Actual Behavior**

* Describe or show the actual behavior.

#5741 is back with [9.2.10.0](https://github.com/jruby/jruby/releases/tag/9.2.10.0) release:
```
[WARNING] 
Dependency convergence error for com.github.jnr:jnr-posix:3.0.53 paths to dependency are:
+-pzrep:jruby-convergence:1-SNAPSHOT
  +-org.jruby:jruby:9.2.10.0
    +-org.jruby:jruby-core:9.2.10.0
      +-com.github.jnr:jnr-unixsocket:0.27
        +-com.github.jnr:jnr-posix:3.0.53
and
+-pzrep:jruby-convergence:1-SNAPSHOT
  +-org.jruby:jruby:9.2.10.0
    +-org.jruby:jruby-core:9.2.10.0
      +-com.github.jnr:jnr-posix:3.0.54

[WARNING] 
Dependency convergence error for org.jruby.jcodings:jcodings:1.0.45 paths to dependency are:
+-pzrep:jruby-convergence:1-SNAPSHOT
  +-org.jruby:jruby:9.2.10.0
    +-org.jruby:jruby-core:9.2.10.0
      +-org.jruby.joni:joni:2.1.30
        +-org.jruby.jcodings:jcodings:1.0.45
and
+-pzrep:jruby-convergence:1-SNAPSHOT
  +-org.jruby:jruby:9.2.10.0
    +-org.jruby:jruby-core:9.2.10.0
      +-org.jruby.jcodings:jcodings:1.0.46
```
I understand I can choose to not upgrade, or to manage problematic dependencies myself. But as I'm not using `jcodings` nor `jnr-posix` directly, I would rather jruby have them synchronized (and tested for cooperation).

* Provide text or screen capture showing the behavior.
[build log with the same as above](https://travis-ci.org/pzrep/jruby-convergence-errors/builds/652341341#L563)

**Comment by headius** [comment]
jnr-unixsocket needs an updated jnr-posix and joni needs an updated jcodings.

Perhaps we can turn this dependency check into a CI job? Can you help with that?

**Comment by headius** [comment]
This has been fixed on master (9.3) and on a new `jruby-9.2` branch that would become 9.2.11 if we release it. @enebo not sure how to mark milestone for this... seems like 9.2.11 is more likely than we thought?

**Comment by enebo** [comment]
yeah I will add a 9.2.11.0 for this and for the rubygems issue.

**Comment by pzygielo** [comment]
> Perhaps we can turn this dependency check into a CI job? Can you help with that?

Now, that I know project is buildable in my proxied environment - I can try.
Could it be new IT in `maven/jruby-complete/src/it` with (probably failures-enabled) travis job?

**Comment by headius** [comment]
Cool I see the PR now. Thank you!
