### ISSUE TITLE
Update RubyGems to 3.0.8

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6088]
RubyGems 3.0.8 contains fixes for updating some default gems like bundler. We might as well pull the few changes it contains into 9.2.11.

This relates to jruby/jruby-launcher#29.

**Comment by chadlwilson** [comment]
FWIW I think this can be closed now, looks like JRuby `9.2.17.0` went straight from `3.0.6` -> `3.1.6` in #6294

**Comment by headius** [comment]
Oh yeah, this is an old one. Thanks!
