### ISSUE TITLE
Pontential performance issue

### ISSUE THREAD

**Issue by klobuczek** [jruby/jruby#6089]
Our test suite runs 19 minutes on 9.2.9.0 but 87 minutes on 9.2.10.0. No other changes just replacing the ruby gives the slow performance. I tried to play with memory settings but no significant difference.
We are running on jdk 11. I've noticed the problem on jruby-head but thought you had left there some debugging.

**Environment Information**
  
Provide at least:
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
* JRuby version 9.2.9.0/9.2.10.0 and no flags, default JRUBY_OPTS
* Operating system and platform (e.g. `uname -a`)
macOS catalina and Ubuntu 16.04
Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version rails 5
* Environment variables

**Comment by enebo** [comment]
@klobuczek wow.  You have any capacity to git bisect JRuby to see which commit may have caused this?  I realize based on time scale what I am asking but we do not know what is responsible at all from this report and that would figure it out.

**Comment by headius** [comment]
Yes, I concur with trying to get a bisect as soon as possible. If we can boil this down to one change then we can quickly fix it in 9.2.11.

**Comment by klobuczek** [comment]
I need to come up with a better test case, one that exhibits this on something running less than a minute.
Now if you say git bisect is there anyway to run jruby from source rather than installing all the different commits with rvm?

**Comment by enebo** [comment]
@klobuczek you need to clone this project and have a java JDK installed (java 8 from adoptjdk if you do not already have one -- try javac -version).

One you have that git co 9.2.10.0; git bisect bad; git co 9.2.9.0; git bisect good; ./mvnw clean; ./mvnw; jruby run_your_test then bisect good/bad until it tells a commit.

**Comment by headius** [comment]
We might also get some information if you can run your suite passing `--sample` to JRuby (only on Java 8) or passing one of a few other flags on Java 11+.

**Comment by klobuczek** [comment]
@headius can you let know the other flags for running the suite on java 11. Our app is only compatible with java 11. Will the git bisect work with jdk11?

**Comment by headius** [comment]
git bisect will work fine with 11.

For a sampled profile on 11 I'll try to get some instructions together.

**Comment by headius** [comment]
If you are adventurous, you could read through docs and try to use async-profiler: https://github.com/jvm-profiling-tools/async-profiler

I have been working on plugging this into JRuby, and there's a `jruby-async-profiler` gem that will install the library, which might help you bootstrap.

Here's a very simple session using the gem and running a sampled profile:

```
[] ~/projects/jruby $ gem install jruby-async-profiler
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.ext.openssl.SecurityHelper (file:/Users/headius/projects/jruby/lib/ruby/stdlib/jopenssl.jar) to field java.security.MessageDigest.provider
WARNING: Please consider reporting this to the maintainers of org.jruby.ext.openssl.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Building native extensions. This could take a while...
Successfully installed jruby-async-profiler-0.1.0
Parsing documentation for jruby-async-profiler-0.1.0
Done installing documentation for jruby-async-profiler after 1 seconds
1 gem installed

[] ~/projects/jruby $ jruby -J-agentpath:lib/libasyncProfiler.so=start,interval=500us,flat=1000,file=profile.txt -e "1000.times { 1000.times { 1000.times { 'foo' + 'bar' } } }"

[] ~/projects/jruby $ head -50 profile.txt 
--- Execution profile ---
Total samples       : 61988
unknown_Java        : 23 (0.04%)
not_walkable_Java   : 34 (0.05%)

Frame buffer usage  : 13.9663%

          ns  percent  samples  top
  ----------  -------  -------  ---
  9640500000   31.10%    19281  org.jruby.runtime.Frame.setSelf
  5238500000   16.90%    10477  org.jruby.util.ByteList.<init>
  2452500000    7.91%     4905  DashE.invokeOther0:+
  1907000000    6.15%     3814  jbyte_disjoint_arraycopy
  1440000000    4.65%     2880  org.jruby.util.StringSupport.addByteLists
   591000000    1.91%     1182  org.jruby.RubyString.newStringShared
   538500000    1.74%     1077  org.jruby.RubyString.newStringNoCopy
   440000000    1.42%      880  org.jruby.runtime.callsite.CachingCallSite.call
   416000000    1.34%      832  jbyte_arraycopy
   348500000    1.12%      697  org.jruby.util.ByteList.getUnsafeBytes
   323500000    1.04%      647  org.jruby.RubyBasicObject.getMetaClass
   292500000    0.94%      585  org.jruby.util.ByteList.getEncoding
   268500000    0.87%      537  java.lang.invoke.MethodHandle.linkToStatic
   256500000    0.83%      513  org.jruby.runtime.ThreadContext.pushFrame
   249000000    0.80%      498  java.lang.invoke.LambdaForm$MH.1795135446.invoke
   245000000    0.79%      490  org.jruby.RubyString.getCodeRange
   238500000    0.77%      477  org.jruby.util.ByteList.invalidate
   236000000    0.76%      472  java.lang.invoke.Invokers$Holder.invokeExact_MT
   232000000    0.75%      464  org.jruby.RubyString.op_plus19
   221500000    0.71%      443  DashE.RUBY$block$-e$2
   218500000    0.70%      437  org.jruby.Ruby.addToObjectSpace
   189000000    0.61%      378  org.jruby.util.ByteList.realSize
   180000000    0.58%      360  __psynch_cvwait
   125500000    0.40%      251  org.jruby.ir.runtime.IRRuntimeHelpers.updateBlockState
   124500000    0.40%      249  org.jruby.runtime.Frame.setVisibility
   122000000    0.39%      244  org.jruby.runtime.Block.allocScope
   118500000    0.38%      237  java.lang.invoke.Invokers.checkExactType
   115500000    0.37%      231  org.jruby.runtime.Binding.getSelf
   115000000    0.37%      230  org.jruby.RubyString$INVOKER$i$1$0$op_plus19.call
   112000000    0.36%      224  java.lang.invoke.DirectMethodHandle$Holder.invokeStatic
   111500000    0.36%      223  org.jruby.runtime.callsite.CacheEntry.typeOk
   106500000    0.34%      213  org.jruby.ir.runtime.IRRuntimeHelpers.prepareNoBlockArgs
   105000000    0.34%      210  org.jruby.runtime.Block.getBinding
   103000000    0.33%      206  org.jruby.RubyString.checkEncoding
   102500000    0.33%      205  org.jruby.util.ByteList.realSize
    96000000    0.31%      192  org.jruby.util.ByteList.setEncoding
    89000000    0.29%      178  __block_descriptor_tmp
    51000000    0.16%      102  _platform_bzero$VARIANT$Haswell
    45500000    0.15%       91  __psynch_mutexwait
    44500000    0.14%       89  PhaseChaitin::Split(unsigned int, ResourceArea*)
    40500000    0.13%       81  IndexSetIterator::advance_and_next()
```

**Comment by headius** [comment]
You can of course stop by Matrix to chat with us... I am traveling but still monitoring the room.

https://matrix.to/#/#jruby:matrix.org

**Comment by klobuczek** [comment]
@headius you must have some different setup. When I run jruby from the jruby directory I get the rvm one. bin/jruby does get the one just built. But that's minor. I don't understand how gem installation should work on the jruby built from source. e.g 
```
heinrich@berlin:~/mck/jruby$ bin/gem list
```
lists many gems installed in other jruby versions.
I general I am lacking understanding.
My application is a rails app and I can run the test the following way:
```
heinrich@berlin:~/mck/org-api$ rvm use 9.2.10; bundle; rspec
```
How does this translate to running it on jruby from source:
```
heinrich@berlin:~/mck/org-api$ git checkout 9.2.10.0; ./mvnw clean; ./mvnw; <what-command???>
```
Thanks

**Comment by headius** [comment]
@klobuczek When you run from the checked-out version it should just be a matter of putting the `bin` dir in `PATH` and/or setting `JRUBY_HOME` environment variable to the checkout dir.

We very much want to help diagnose whatever this issue is but I'm not sure how best to help you. These profiling tools work but require some finesse to get the right information out. I'd be happy to connect to a server instance of yours that clearly demonstrates the problem. Otherwise we are largely back to you bisecting our repository... check out JRuby, "mvn clean package" to update it, and use `git bisect` to narrow it down to a slow version.

How would you like to proceed?

**Comment by headius** [comment]
Ok after a bit of back and forth @klobuczek managed to sort out one spec that was 2x slower via rspec's `--profile` flag. Bisecting that regression led to ed72b695584909e3db384732c85643dcafbe337d by @kares.

It turns out the default `caller` and `caller_locations` paths (when the user passes no length argument) do not use `Integer.MAX_VALUE` as the upper bound. Instead, the code here passes `1 << 24` as the upper bound, which results in the ArrayList constructing a gigantic backing store.

https://github.com/jruby/jruby/blob/cf4d39c354995a6c67fb86334b2cefe350d5938c/core/src/main/java/org/jruby/RubyKernel.java#L1156

The original commit was intended to do a better job of "right-sizing" the ArrayList backing store, but unexpectedly regressed `caller` performance almost 1000x:

```
[] ~/projects/jruby $ jruby -rbenchmark/ips -e 'Benchmark.ips {|ips| ips.report { caller } }'
Warming up --------------------------------------
                         1.000  i/100ms
Calculating -------------------------------------
                         29.909  (±76.9%) i/s -     47.000  in   5.070658s

[] ~/projects/jruby $ rvm jruby-9.2.9.0 do jruby -rbenchmark/ips -e 'Benchmark.ips {|ips| ips.report { caller } }'
Warming up --------------------------------------
                         1.038k i/100ms
Calculating -------------------------------------
                         11.672k (± 5.3%) i/s -     58.128k in   4.996813s
```

I have reverted the change in b0086914a88faae9862225680a7a60607c1856ed, which should fix this issue.

@klobuczek FWIW, there's still a very large cost to this instrumentation. Hopefully you are not using it in a production setting, and this regression only affects your test environment.

@kares We should revisit this right-sizing and perhaps pick a reasonable maximum initial size for unbounded `caller` gathering.

**Comment by klobuczek** [comment]
Confirming, the specs running times are back to the 9.2.9.0 level on the jruby-9.2 branch HEAD.

**Comment by headius** [comment]
@klobuczek Thank you!
