### ISSUE TITLE
[9.2.10.0] bogus revision regression

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#6090]
simply run ```jruby -v```

**Environment Information**
jruby 9.2.10.0 (2.5.7) 2020-02-18 fffffff Java HotSpot(TM) 64-Bit Server VM 11.0.2+9-LTS on 11.0.2+9-LTS +jit [linux-x86_64]

**Expected Behavior**
jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e Java HotSpot(TM) 64-Bit Server VM 11.0.2+9-LTS on 11.0.2+9-LTS +jit [linux-x86_64]

**Actual Behavior**
jruby 9.2.10.0 (2.5.7) 2020-02-18 fffffff Java HotSpot(TM) 64-Bit Server VM 11.0.2+9-LTS on 11.0.2+9-LTS +jit [linux-x86_64]

```fffffff``` is a fake value https://github.com/jruby/jruby/blob/7103c2244b41908f78cdb36ee772f5970408a8b5/core/src/main/resources/org/jruby/runtime/Constants.java#L107

my first guess, it has something to do with https://github.com/jruby/jruby/pull/5996 ?

**Comment by headius** [comment]
Huh yeah I noticed that myself yesterday and thought I was doing something wrong. That hash should not be passing through RubyGems at all so I suspect a build change has broken how we get the git hash installed in our code. I'll get it fixed.

**Comment by headius** [comment]
Bisected to 2e604ade3a5dfc996003efc2565480c63d252ccc which attempted to remove some local build paths from the built artifacts.

I have a change that switches the phase this runs in from `initialize` to `prepare-resources`, and that seems to fix it. I'll push that change now.

@mkristian Anything wrong with this change you can see?

```diff
diff --git a/core/pom.rb b/core/pom.rb
index f38c197b43..549d4499b0 100644
--- a/core/pom.rb
+++ b/core/pom.rb
@@ -260,7 +260,7 @@ project 'JRuby Core' do
   end
 
   plugin :resources do
-    execute_goals('copy-resources', phase: :initialize,
+    execute_goals('copy-resources', phase: 'process-resources',
                   outputDirectory: '${basedir}',
                   resources: [
                     {
```

**Comment by mkristian** [comment]
Your phase seems right and if works then no objections.

**Comment by headius** [comment]
@mkristian Thank you!
