### ISSUE TITLE
TracePoint does not report calls to attribute reader methods

### ISSUE THREAD

**Issue by AndyObtiva** [jruby/jruby#6101]
**Environment Information**
  
Provide at least:
* JRuby version: `jruby 9.2.10.0 (2.5.7) 2020-02-18 fffffff Java HotSpot(TM) 64-Bit Server VM 12.0.1+12 on 12.0.1+12 +jit [darwin-x86_64]`
* Command line flags: `--debug`
* Operating system and platform: `Darwin Users-iMac-2.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`

Other relevant info you may wish to add:
* Installed or activated gems: N/A
* Application/framework version (e.g. Rails, Sinatra): N/A
* Environment variables: N/A

**Expected Behavior**

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.

```ruby
class Person
  attr_writer :first_name
  attr_writer :last_name
  def name
    "#{self.last_name}, #{self.first_name}"
  end
  def first_name
    @first_name
  end
  def last_name
    @last_name
  end
end

person = Person.new
person.first_name = 'Josh'
person.last_name = 'McGibbon'
trace = TracePoint.new(:call) do |tp|
  p [tp.path, tp.lineno, tp.defined_class, tp.event, tp.method_id]
end
trace.enable
person.name
trace.disable
```

When running the script above with `ruby --debug`, I get the following output:

```
["trace_point_issue.rb", 22, Person, :call, :name]
["trace_point_issue.rb", 28, Person, :call, :last_name]
["trace_point_issue.rb", 25, Person, :call, :first_name]
```

This is correct as per expectation. Next, we refactor `first_name` and `last_name` methods into attributes using `attr_accessor` (or `attr_reader`).

* Provide an executable Ruby script or a link to an example repository.

```ruby
class Person
  attr_accessor :first_name
  attr_accessor :last_name
  def name
    "#{self.last_name}, #{self.first_name}"
  end
end

person = Person.new
person.first_name = 'Josh'
person.last_name = 'McGibbon'
trace = TracePoint.new(:call) do |tp|
  p [tp.path, tp.lineno, tp.defined_class, tp.event, tp.method_id]
end
trace.enable
person.name
trace.disable
```

I expect the output from running this script to be the same as the script above.

```
["trace_point_issue.rb", 22, Person, :call, :name]
["trace_point_issue.rb", 28, Person, :call, :last_name]
["trace_point_issue.rb", 25, Person, :call, :first_name]
```

**Actual Behavior**

* Describe or show the actual behavior.

In the actual output, I didn't get any tracing of `first_name` and `last_name` after they have been changed from methods to attributes.

* Provide text or screen capture showing the behavior.

Actual output of running the refactored script above using `ruby --debug` (with `attr_accessor`):

```
["trace_point_issue.rb", 4, Person, :call, :name]
```

**Comment by headius** [comment]
Odd that CRuby doesn't report these as `c_call` since attrs are implemented in C.

Good catch though, perhaps you can add some specs for this in https://github.com/ruby/spec!

**Comment by AndyObtiva** [comment]
Thank you. 

I reported this issue for CRuby too over here: 
https://bugs.ruby-lang.org/issues/16383

The ruby specs you asked for are done:
https://github.com/ruby/spec/pull/761

Please let me know if you'd like anything else from me or if you have any feedback to take care of for my specs.

**Comment by headius** [comment]
@AndyObtiva Doesn't seem like the CRuby issue is moving forward very quickly. 😦

We could consider implementing this behind a configuration, but it's not something we'd support by default since it would trigger events that don't happen on CRuby.

**Comment by AndyObtiva** [comment]
Fair enough. Implementing this would have potentially made computed data-binding in Glimmer sing, but I guess I'll settle for what I have for now. Thanks. 

p.s. I am closing the ruby/spec pull request too.
