### ISSUE TITLE
java_import conflicts should get scoped properly

### ISSUE THREAD

**Issue by kares** [jruby/jruby#6115]
UPDATED example : 
```ruby
java_import 'java.util.jar.Attributes'

class JavaImportScope
  def do_import # self.do_import works
    java_import 'org.xml.sax.Attributes'
  end

  def self.attributes
    Attributes
  end
end

JavaImportScope.new.do_import

puts JavaImportScope.attributes # org.xml.sax.Attributes
puts Attributes # also org.xml.sax.Attributes (with a warning)
```

will try to come up with a detailed spec for the feature

**Comment by enebo** [comment]
@kares just using java_import?

**Comment by kares** [comment]
sorry, extracted the wrong thingy. updated reproducer. no longer sure if this is really an issue ...

**Comment by headius** [comment]
I looked into the logic in https://github.com/jruby/jruby/blob/0fbb2b72c1295cad4d3d7a840617537239a2448c/core/src/main/ruby/jruby/java/core_ext/object.rb and it's clear why it behaves oddly.

If `java_import` is called against a module, we `class_eval` a string that eventually defines the constant in that module.

However if `java_import` is called against a non-Module, we `eval` that same string against the `binding` inside the body of `java_import`... which means we end up defining the constant on `Object`.

Over a decade later, it's clear we should never have been defining this method on `Object` in the first place; it should be defined on `Module` and on the top-level scope, similar to `define_method`. We also should not (and do not need to) use `eval` forms to define the constants.

I'm playing with a patch but I don't think this behavior has changed. It's just weird.

**Comment by headius** [comment]
The PR has been merged, which makes Object#java_import deprecated with a warning. I'll leave it up to @kares if there's anything more to do here.

**Comment by kares** [comment]
thanks, no longer sure about having i-method scoping like if the target is a module
