### ISSUE TITLE
undefined method `runtime' for JRuby:Module on Travis CI when running `rubocop` for `rspec-rails`

### ISSUE THREAD

**Issue by pirj** [jruby/jruby#6125]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
https://rubies.travis-ci.org/ubuntu/14.04/x86_64/jruby-head.tar.gz as of today.
```ruby
JRUBY_OPT=--dev JAVA_OPTS="--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.security.cert=ALL-UNNAMED --add-opens=java.base/java.util.zip=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/javax.crypto=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED"
```
* Operating system and platform (e.g. `uname -a`)
Description:	Ubuntu 14.04.5 LTS
Release:	14.04

Other relevant info you may wish to add:
* Installed or activated gems
https://github.com/rspec/rspec-rails/tree/ddd29efbfa4425c815fb774a4d3b04d1fa232d28
See build log https://api.travis-ci.org/v3/job/664005787/log.txt starting from `Using rake 12.3.3`

**Expected Behavior**

`rubocop` runs with not errors

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.

Same build, other jobs for MRI pass https://travis-ci.org/github/rspec/rspec-rails/builds/664005783

* Provide an executable Ruby script or a link to an example repository.

https://github.com/rspec/rspec-rails/tree/ddd29efbfa4425c815fb774a4d3b04d1fa232d28

**Actual Behavior**

```
2.2.0-java.gemspec:18.

NoMethodError: undefined method `runtime' for JRuby:Module
  <class:Parser> at /home/travis/.rvm/rubies/jruby-head/lib/ruby/stdlib/racc/parser.rb:192
   <module:Racc> at /home/travis/.rvm/rubies/jruby-head/lib/ruby/stdlib/racc/parser.rb:182
          <main> at /home/travis/.rvm/rubies/jruby-head/lib/ruby/stdlib/racc/parser.rb:176
         require at org/jruby/RubyKernel.java:974
          <main> at /home/travis/build/rspec/bundle/jruby/2.5.0/gems/parser-2.7.0.4/lib/parser.rb:12
         require at org/jruby/RubyKernel.java:974
          <main> at /home/travis/build/rspec/bundle/jruby/2.5.0/gems/rubocop-0.80.1/lib/rubocop.rb:3
         require at org/jruby/RubyKernel.java:974
          <main> at /home/travis/build/rspec/bundle/jruby/2.5.0/gems/rubocop-0.80.1/exe/rubocop:6
            load at org/jruby/RubyKernel.java:1009
          <main> at /home/travis/build/rspec/rspec-rails/bin/rubocop:29
```

**Comment by ahorek** [comment]
this is related to https://github.com/jruby/jruby/pull/5381

simplified test case
```ruby
require 'parser'
```

**Comment by pirj** [comment]
Thanks 👍

**Comment by pirj** [comment]
https://github.com/ruby/racc/pull/132 is merged 🎉 
No pressure, just wondering what is the expected timeline for this to get its way into `jruby-head`?

**Comment by headius** [comment]
Master can be updated once the gem is released... we only source racc from the gem.

@hsbt Anything I can do to help get a racc release out?

**Comment by headius** [comment]
Actually master does not yet use the gem so I think I can make this change directly on our copy.

**Comment by headius** [comment]
This is fixed on master in dbad978b80.

**Comment by pirj** [comment]
Thanks!

**Comment by benoittgt** [comment]
Thanks 🙌🏻
