### ISSUE TITLE
Socket#connect is not interrupted by Timeout#timeout and Thread#kill

### ISSUE THREAD

**Issue by p-mongo** [jruby/jruby#6126]
**Environment Information**

<pre>
carbon% jruby -v
jruby 9.2.11.0 (2.5.7) 2020-03-02 612d7a05a6 OpenJDK 64-Bit Server VM 25.242-b08 on 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08 +jit [linux-x86_64]
carbon% uname -a
Linux carbon 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
</pre>
 
**Expected Behavior**

When I wrap a `Socket#connect` call with `Timeout#timeout`, I expect the call to time out after the specified time. [Test case](https://github.com/p-mongo/tests/blob/master/jruby-connect-timeout/test.rb)

MRI:

<pre>
carbon% ruby test.rb 
init
connect
Traceback (most recent call last):
	3: from test.rb:9:in `<main>'
	2: from /home/w/.rbenv/versions/2.7.0/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	1: from test.rb:11:in `block in <main>'
test.rb:11:in `connect': execution expired (Timeout::Error)
</pre>

**Actual Behavior**

The connect call appears to be hung indefinitely. The application can be aborted with Ctrl-C.

** Threaded Variation **

[This test](https://github.com/p-mongo/tests/blob/master/jruby-connect-timeout/thread-test.rb) completes when run on MRI. The thread is aborted and the `Thread#join` call finishes.

On JRuby this file hangs indefinitely. The thread is stuck in `aborting` state. The application can be aborted with Ctrl-C.

** Thread status oscillating between aborting and run **

I don't know if this is expected, but while the thread is stuck in the aborting state, calling Thread#run on it makes it switch back into run state, and it can be moved back and forth between these two states any number of times [as shown in this test](https://github.com/p-mongo/tests/blob/master/jruby-connect-timeout/thread-status.rb). My first reaction was if I kill the thread it should die, calling run on it shouldn't negate the kill request.

**Comment by headius** [comment]
The aborting state is expected, but it shouldn't stay in that state and become unresponsive. The abort indicates that there's a raise in progress on that thread, but because our implementation of `Socket#connect` is apparently blocking, it will never propagate that raise and terminate the thread.

So, we need to make `Socket#connect` non-blocking for this case.

Here's a partial stack trace from JRuby master (acquired via Ctrl+\ or the `jstack` command):

```
"main" #1 prio=5 os_prio=31 cpu=2314.23ms elapsed=7.28s tid=0x00007fcc44001000 nid=0x1e03 runnable  [0x000070000b0d8000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.Net.connect0(java.base@11.0.4/Native Method)
	at sun.nio.ch.Net.connect(java.base@11.0.4/Net.java:482)
	at sun.nio.ch.Net.connect(java.base@11.0.4/Net.java:474)
	at sun.nio.ch.SocketChannelImpl.connect(java.base@11.0.4/SocketChannelImpl.java:694)
	at org.jruby.ext.socket.RubySocket.doConnect(org.jruby.dist/RubySocket.java:548)
	at org.jruby.ext.socket.RubySocket.connect(org.jruby.dist/RubySocket.java:213)
```
