### ISSUE TITLE
LoadError:    no such file to load -- racc/info

### ISSUE THREAD

**Issue by pirj** [jruby/jruby#6131]
There are **two** different errors. What made me think that those two have a common cause is that [`rspec-rails` JRuby builds were green not long ago](https://travis-ci.org/github/rspec/rspec-rails/builds/663477670) (before https://github.com/jruby/jruby/issues/6125), but failed again when Rails 6.0.2.2 and 5.2.4.2 were out.

Please let me know if you want to track those two separately.

1. [triggered by nokogiri](https://github.com/sparklemotion/nokogiri/blob/v1.9.1/lib/nokogiri/css/parser.rb#L7):
```ruby
require 'racc/parser.rb'
```
```
An error occurred while loading spec_helper.
Failure/Error: require 'rails/all'

NameError:
  uninitialized constant ActionDispatch::Routing::RouteSet
# /home/travis/build/rspec/bundle/jruby/2.5.0/gems/railties-6.0.2.2/lib/rails/engine.rb:537:in `routes'
```

https://travis-ci.org/github/rspec/rspec-rails/jobs/665433957

* Application/framework version (e.g. Rails, Sinatra)
[Rails 5.2.4.2](https://weblog.rubyonrails.org/2020/3/19/Rails-6-0-2-2-and-5-2-4-2-has-been-released/)

2. Fails to [autoload `ActionDispatch::Routing::RouteSet`](https://github.com/rails/rails/blob/v6.0.2.2/railties/lib/rails/engine.rb#L537):
```ruby
    def routes(&block)
      @routes ||= ActionDispatch::Routing::RouteSet.new_with_config(config)
```
```
An error occurred while loading spec_helper.
Failure/Error: require 'rails/all'

NameError:
  uninitialized constant ActionDispatch::Routing::RouteSet
```
https://travis-ci.org/github/rspec/rspec-rails/jobs/665433954#L1060

* Application/framework version (e.g. Rails, Sinatra)
[Rails 6.0.2.2](https://weblog.rubyonrails.org/2020/3/19/Rails-6-0-2-2-and-5-2-4-2-has-been-released/)

**Environment Information**
  
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
`jruby-head` from RVM:
http://rubies.travis-ci.org/ubuntu/14.04/x86_64/jruby-head
74.24 MiB, 2020-03-22 03:44:10 UTC
```
export JRUBY_OPT=--dev
export JAVA_OPTS="--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.security.cert=ALL-UNNAMED --add-opens=java.base/java.util.zip=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/javax.crypto=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED"
```
* Operating system and platform (e.g. `uname -a`)
Ubuntu 14.04, x86_64 

**Expected Behavior**

There's no error, the build passes just like the rest of builds for a variety of MRI versions https://travis-ci.org/github/rspec/rspec-rails/builds/665433953

**Actual Behavior**

Errors, see above.

**Comment by headius** [comment]
Aha! Looks like at some point racc finally got rid of the GPL code it contained (or converted code to the Ruby license). This means we don't have to use a modified racc anymore, and in fact should include all the code from https://github.com/ruby/racc.

I will push a commit that adds the missing files.

@hsbt Since the released gem now contains no GPL code, we'd very much like to move this to being a default or preinstalled gem. When can we expect a release with the recent fix for JRuby?

**Comment by pirj** [comment]
Thanks!
