### ISSUE TITLE
Audit constant assignment paths for ID vs Java strings

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6144]
In the process of working on #5576 I ran into a number of code paths that bottom out in our RubyModule constant tables, but which are not passing in properly-mangled "ID strings". I am fixing what I can but a number of cases remain:

* Anything that calls `setConstant` or `storeConstant` from Java
* Java integration's binding of Java classes uses the Java string name rather than a mangled ID string. This will prevent those classes from being accessible from Ruby.

I found these cases by looking for calls to `IdUtil.isConstant`, which *only* works on decoded Java strings and should never be called with ID strings.

**Comment by headius** [comment]
Some of this was done with @enebo's work on unicode constants throughout the parser and compiler chain.

**Comment by enebo** [comment]
There are still paths we need to conside but the overall audit has been done.
