### ISSUE TITLE
--server argument warning pollutes standard output

### ISSUE THREAD

**Issue by p-mongo** [jruby/jruby#6147]
We upgraded to 9.2.11.0 recently and our CI started failing because the following warning is printed by jruby to standard output:

<pre>
[2020-03-28 19:41:36.535] Warning: the --server flag is deprecated and has no effect most JVMs
</pre>

For example, we have a [script](https://github.com/mongodb/mongo-ruby-driver/blob/master/.evergreen/get-mongodb-download-url) that outputs the result of its work to standard output, which is then [consumed by bash](https://github.com/mongodb/mongo-ruby-driver/blob/master/.evergreen/functions.sh#L280) as follows:

<pre>
 url=`$(dirname $0)/get-mongodb-download-url $download_version $arch`
</pre>

In 9.2.11.0 this produces:

<pre>
[2020-03-28 19:41:36.972] + prepare_server rhel70
[2020-03-28 19:41:36.972] + arch=rhel70
[2020-03-28 19:41:36.972] + test -n ''
[2020-03-28 19:41:36.972] + test 4.2 = latest
[2020-03-28 19:41:36.972] + download_version=4.2
[2020-03-28 19:41:36.973] +++ dirname .evergreen/run-tests.sh
[2020-03-28 19:41:36.974] ++ .evergreen/get-mongodb-download-url 4.2 rhel70
[2020-03-28 19:41:39.505] + url='Warning: the --server flag is deprecated and has no effect most JVMs
[2020-03-28 19:41:39.505] https://downloads.mongodb.com/linux/mongodb-linux-x86_64-enterprise-rhel70-4.2.5.tgz'
</pre>

You can see that the `url` variable now contains the warning message followed by the URL. Due to the warning message being prepended to the URL, this variable now has wrong content and subsequent operations using it fail.

It appears that the offending message was added in 9.2.10.0 [here](https://github.com/jruby/jruby/blob/master/bin/jruby.bash#L317).

Looking at that file, there are several other messages being printed to standard output and I expect they would also produce the same issue.

I tried to reproduce this issue locally [here](https://github.com/p-mongo/tests/blob/master/jruby-server-flag/test.sh) but have not succeeded in doing so by invoking `ruby` or `jruby`. If I invoke `jruby.bash` the issue reproduces.

**Environment Information**

Problematic system:

<pre>
jruby 9.2.11.0 (2.5.7) 2020-03-02 612d7a05a6 Java HotSpot(TM) 64-Bit Server VM 25.162-b12 on 1.8.0_162-b12 +jit [linux-x86_64]
</pre>

OK system:

<pre>
jruby 9.2.11.0 (2.5.7) 2020-03-02 612d7a05a6 OpenJDK 64-Bit Server VM 25.242-b08 on 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08 +jit [linux-x86_64]
</pre>

**Suggested fix**

All of the warning messages in https://github.com/jruby/jruby/blob/master/bin/jruby.bash should be output to stderr, not to stdout, using a pattern like:

<pre>
echo Warning message 1>&2
</pre>

**Comment by headius** [comment]
Aha, you are correct. We will fix these.

**Comment by p-mongo** [comment]
Thanks!
