### ISSUE TITLE
handle Java 9+ warnings on windows

### ISSUE THREAD

**Issue by kares** [jruby/jruby#6155]
JRuby already handles most annoying warnings (due accessing JVM internals) on Linux/Mac.
Windows seems left behind with these, someone should potentially port the [bash launcher changes](https://github.com/jruby/jruby/commit/30d6e7fd91fa202b9b7aedf130b5e274bdc4ec61#diff-fb0796a5d49e06c2f0661f656f61820c)
(to read dot files https://github.com/jruby/jruby/blob/9.2.11.1/bin/.jruby.module_opts)

```
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 11+28 on 11+28 +jit [mswin32-x86_64]
2020-03-31T02:40:37.913-07:00 [main] WARN FilenoUtil : Native subprocess control requires open access to sun.nio.ch
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist' or '=org.jruby.core' to enable.
irb(main):001:0> puts ''.encoding
Windows-1252
```

**Comment by enebo** [comment]
@kares this is only via .bat right?  jruby-launcher that comes with the installer should not be doing this now.

**Comment by enebo** [comment]
Oh hmm maybe not...9.2.11.1 might still be shipped with an earlier version of the launcher?

**Comment by kares** [comment]
the `jruby.bat` just delegates to `jruby.exe` (which I got using the default install4j installer)

**Comment by headius** [comment]
@enebo I think you only committed the new launcher to master.

**Comment by headius** [comment]
This commit only appears on master; the last `jruby.exe` update in 9.2 was in *November 2018*!!!

```
commit 28ef5382f6faf4c7f3c37a92df3333fbcf45a63a
Author: Thomas E. Enebo <tom.enebo@gmail.com>
Date:   Fri Mar 20 15:11:45 2020 -0500

    Update binaries with module handling enabled
```

If you copy over this binary to your 9.2.11.1 it will probably work. The new launcher that @enebo is working on will have a native binary gem so people can upgrade.

**Comment by headius** [comment]
FWIW we still need to get a launcher release out for Windows, but JRuby master has been tweaked to not warn even if run without module flags. See #6195.

**Comment by headius** [comment]
Marking for 9.3. We need to either fix the current launcher to do everything the bash script does, or finish @enebo's new launcher.

**Comment by headius** [comment]
The options in question were ported to the launcher some time ago, and the launcher exe has been updated for JRuby 9.2 releases along the way. This will also be reworked by @enebo's rust-based launcher.
