### ISSUE TITLE
Socket.gethostname encoding still platform specific

### ISSUE THREAD

**Issue by kares** [jruby/jruby#6156]
OK - since `Encoding.default_external => #<Encoding:Windows-1252>`
```
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 11+28 on 11+28 +jit [mswin32-x86_64]

irb(main):001:0> puts ''.encoding; require 'socket'; puts Socket.gethostname.encoding
Windows-1252
Windows-1252
=> nil
```

FAIL `Encoding.default_external => #<Encoding:UTF-8>`
`bin\jruby -v -S irb -EUTF-8`
```
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 OpenJDK 64-Bit Server VM 11+28 on 11+28 +jit [mswin32-x86_64]

irb(main):001:0>  puts ''.encoding; require 'socket'; puts Socket.gethostname.encoding
UTF-8
Windows-1252
=> nil
```

**Comment by kares** [comment]
also still problematic for ENV - getting Windows-1252 encoded keys/values regardless of external enc.

**Comment by headius** [comment]
I don't have a Windows environment handy... have we confirmed that MRI works differently?

Perhaps we should be using `default_internal` for this?

**Comment by ahorek** [comment]
it seems to be ASCII-8BIT on MRI

```
puts ''.encoding; require 'socket'; puts Socket.gethostname.encoding
```
ruby 2.7.0
CP852
ASCII-8BIT

jruby 9.3.0.0
IBM852
Windows-1250

```
ruby -S irb -EUTF-8
puts ''.encoding; require 'socket'; puts Socket.gethostname.encoding
```
ruby 2.7.0
UTF-8
ASCII-8BIT

jruby 9.3.0.0
UTF-8
Windows-1250

**Comment by headius** [comment]
If I'm reading the code right, they eventually create the string with `rb_str_new`, which does not set encoding. In other words, they leave it as the default encoding for a new string, which is `ASCII-8BIT`.

I think we could just hardcode this.

**Comment by kares** [comment]
since other parts in JRuby (`IPSocket#peeraddr`) just use `runtime.newString(addr.getHostName())` thus those do end up UTF-8 and `Socket.gethostname.encoding` is (by default) UTF-8 on Linux/Mac.

is it far fetched to just do the same with `Socket.gethostname` and potentially `ENV` keys/values?

**Comment by headius** [comment]
@kares Seems logical to me that we just make them be ASCII-8BIT like in MRI.

**Comment by headius** [comment]
After investigating WEBrick issues in #6171 I have realized that we can't do much about ENV until we completely route around the JVM's environment variable support. Env vars passing through the JDK `System.getenv` API must be decoded to characters, which mangles any environment variables that are not string content encoded with the system encoding.

We can still fix the encoding of these other strings, though, because it's safe to assume host names will have been properly decoded as string content, and we can just turn them back into ASCII-8BIT to match behavior.

**Comment by headius** [comment]
Hmm on second thought I have concerns about this.

The character range in ASCII-8BIT is clearly not sufficient to handle hostnames with non-ASCII characters. In this case, CRuby basically takes whatever bytes the system gives it and doesn't bother to deal with them as character data. In our case, the hostname has been decoded as a JVM string, and has all character data intact.

I think the better option here would be to return hostnames as the default internal encoding, which is now almost always UTF-8. This would avoid the per-platform encoding differences and fit better into the rest of the system. We'll leave the interpretation of hostname characters up to the JDK's socket API.

**Comment by kares** [comment]
> I think the better option here would be to return hostnames as the default internal encoding, which is now almost always UTF-8. This would avoid the per-platform encoding differences and fit better into the rest of the system. We'll leave the interpretation of hostname characters up to the JDK's socket API.

:+1: on providing consistency across platforms, just like the JVM
