### ISSUE TITLE
New Ripper features in 2.6

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6158]
Aggregate bug for remaining missing Ripper features in 2.6 support.

<details>
<summary>
Failures due to not having the same root layout and files as CRuby:
</summary>
<blockquote>
[  8/291] TestRipper::Generic#test_parse_files:ext = 1.74 s     
  1) Error:
TestRipper::Generic#test_parse_files:ext:
Errno::ENOENT: No such file or directory - /Users/headius/projects/jruby/test/ext
    org/jruby/RubyDir.java:431:in `chdir'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:37:in `<main>'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:27:in `assert_parse_files'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:10:in `block in test_parse_files:ext'

[  9/291] TestRipper::Generic#test_parse_files:lib = 1.67 s
  2) Error:
TestRipper::Generic#test_parse_files:lib:
Errno::ENOENT: No such file or directory - /Users/headius/projects/jruby/test/lib
    org/jruby/RubyDir.java:431:in `chdir'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:37:in `<main>'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:27:in `assert_parse_files'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:16:in `block in test_parse_files:lib'

[ 10/291] TestRipper::Generic#test_parse_files:sample = 1.71 s
  3) Error:
TestRipper::Generic#test_parse_files:sample:
Errno::ENOENT: No such file or directory - /Users/headius/projects/jruby/test/sample
    org/jruby/RubyDir.java:431:in `chdir'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:37:in `<main>'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:27:in `assert_parse_files'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:10:in `block in test_parse_files:sample'

[ 11/291] TestRipper::Generic#test_parse_files:test = 1.64 s  
  4) Error:
TestRipper::Generic#test_parse_files:test:
Errno::ENOENT: No such file or directory - /Users/headius/projects/jruby/test/test
    org/jruby/RubyDir.java:431:in `chdir'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:37:in `<main>'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:27:in `assert_parse_files'
    /Users/headius/projects/jruby/test/mri/ripper/test_files.rb:16:in `block in test_parse_files:test'
</blockquote>
</details>

<details>
<summary>Failures due to use of RubyVM</summary>
<blockquote>
[ 71/291] TestRipper::ParserEvents#test_block_variables = 0.06 s             
  5) Error:
TestRipper::ParserEvents#test_block_variables:
NameError: uninitialized constant TestRipper::ParserEvents::RubyVM
    org/jruby/RubyModule.java:3812:in `const_missing'
    /Users/headius/projects/jruby/test/mri/ripper/test_parser_events.rb:1461:in `test_block_variables'
</blockquote>
</details>

<details>
<summary>Probably valid failures</summary>
<blockquote>
[254/291] TestRipper::ScannerEvents#test_lex = 0.08 s                          
  6) Failure:
TestRipper::ScannerEvents#test_lex [/Users/headius/projects/jruby/test/mri/ripper/test_scanner_events.rb:63]:
<[[[1, 0], :on_int, "1", 2],
 [[1, 1], :on_nl, "\n", 1],
 [[2, 0], :on_int, "2", 2],
 [[2, 1], :on_nl, "\n", 1],
 [[3, 0], :on_int, "3", 2]]> expected but was
<[[[1, 0], :on_int, "1", EXPR_END|EXPR_ENDARG],
 [[1, 1], :on_nl, "\n", EXPR_BEG],
 [[2, 0], :on_int, "2", EXPR_END|EXPR_ENDARG],
 [[2, 1], :on_nl, "\n", EXPR_BEG],
 [[3, 0], :on_int, "3", EXPR_END|EXPR_ENDARG]]>.

[269/291] TestRipper::ScannerEvents#test_sp = 0.02 s          
  7) Failure:
TestRipper::ScannerEvents#test_sp [/Users/headius/projects/jruby/test/mri/ripper/test_scanner_events.rb:846]:
<["\\ "]> expected but was
<[" "]>.

[285/291] TestRipper::Sexp#test_dsym = 0.02 s                            
  8) Failure:
TestRipper::Sexp#test_dsym [/Users/headius/projects/jruby/test/mri/ripper/test_sexp.rb:139]:
[ruby-core:91852].
<[:dyna_symbol,
 [:string_add, [:string_content], [:@tstring_content, "sym", [1, 2]]]]> expected but was
<[:dyna_symbol,
 [:xstring_add, [:xstring_new], [:@tstring_content, "sym", [1, 2]]]]>.
</blockquote>
</details>

**Comment by headius** [comment]
Link to #5576

**Comment by headius** [comment]
Note the first four fail because they expect the test dir to be at root of project, rather than at `/test/mri` as it is for us.

**Comment by headius** [comment]
Link to #6161

**Comment by enebo** [comment]
I am going to compare against base parser and do this as part of 9.3.

**Comment by enebo** [comment]
I have fixed the 'real' problems (commit coming).  The first section is just ripper'ing all the files in their distro to make sure they parse.  The RubyVM one is a very specific test I don't think we need to worry about.  I will close this issue with those non-real tests tagged out.

**Comment by headius** [comment]
@enebo Should this be reopened since you had to revert your commit?
