### ISSUE TITLE
Windows installer fails with Oracle JDK-14: Missing unpack200.exe

### ISSUE THREAD

**Issue by Neurogami** [jruby/jruby#6175]
**Environment Information**
  
jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 Java HotSpot(TM) 64-Bit Server VM 14+36-1461 on 14+36-1461 +jit [mswin32-x86_64]

Windows 10 Pro 64-bit

Oracle JDK-14

**Expected Behavior**

- Double-click on jruby_windows_x64_9_2_11_1.exe
- Installer should launch, and walk you through the installation
- Should complete with JRuby installed

**Actual Behavior**

- Double-click on jruby_windows_x64_9_2_11_1.exe
- Error message appears with reference to a log file
- log file shows failure when trying to call unpack200.exe

```
[0:670] Loading of JVM-DLL successful
[0:671] unpacking i4jruntime.jar.pack
[0:673] c:\program files\java\jdk-14\bin\..\bin\unpack200.exe
[0:675] -r "C:\Users\james\AppData\Local\Temp\e4j17F3.tmp_dir1586834923\i4jruntime.jar.pack" "C:\Users\james\AppData\Local\Temp\e4j17F3.tmp_dir1586834923\i4jruntime.jar"
[0:678] could not create unpack process
```

Checking the install directory for JDK-14 shows that there is no unpack200.exe included.

**Comment by Neurogami** [comment]
I was able to complete the installation by locating a copy of unpack200.exe from an earlier JDK and copying into the current JDK bin folder, then re-running the JRuby installer

**Comment by headius** [comment]
I'm going to try to do a PR to remove all use of pack200 in other places but this will have to be tweaked in the installer by @enebo.
