### ISSUE TITLE
Link on JRuby webpage broken

### ISSUE THREAD

**Issue by rovf** [jruby/jruby#6179]
On the webpage

    https://www.jruby.org/files/downloads/1.7.9/index.html

the link labelled "jruby-complete-1.7.9-sources.jar" 

linking to 

   https://s3.amazonaws.com/jruby.org/downloads/1.7.9/jruby-complete-1.7.9-sources.jar

is broken. The same applies to the link labelled

     jruby-src-1.7.9.tar.gz

linking to

    https://s3.amazonaws.com/jruby.org/downloads/1.7.9/jruby-src-1.7.9.zip

I am waware that JRuby 1.7.9 is not supported, but why have the sources been removed, and why do we still have links to the sources, if they are not here anymore?

**Comment by enebo** [comment]
Updated the link to retrieve from maven and also updated fingerprint links.  Thanks for reporting.

**Comment by enebo** [comment]
@rovf at one point our sponsor deleted all our files and we did not have all of them backed up ourselves (and very surprisingly the S3 did not have backup enabled either).  We have run a dead link checker but it ran for days and we did not find all missing links.
