### ISSUE TITLE
missing method, `Coverage.line_stub` doesn't exist

### ISSUE THREAD

**Issue by danmayer** [jruby/jruby#6181]
**Environment Information**
  
Provide at least:
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-04-18 8ddaa561f9 OpenJDK 64-Bit Server VM 13.0.1+9 on 13.0.1+9 +jit [darwin-x86_64]

Darwin Dan’s-MacBook-Pro 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

**Expected Behavior**

Calling `Coverage.line_stub` should work, but it is undefined.

**Actual Behavior**

This method isn't defined in JRuby.

**notes**

This is defined here in CRuby: https://github.com/ruby/ruby/blob/c5eb24349a4535948514fe765c3ddb0628d81004/ext/coverage/lib/coverage.rb

Given it is just Ruby, I can work around this, but just adding that extension when running JRuby

require 'coverband/utils/jruby_ext' if RUBY_PLATFORM == 'java'

but I wanted to let you know, as I am not sure if that is something you would want to just directly support @headius

Creating a new issue, as this follows up on a closed out ticket, https://github.com/jruby/jruby/issues/3096

**Comment by danmayer** [comment]
Also, note... I have all of Coverband passing and I ran it end to end in a Rails app via JRuby, and all is good.

**Comment by headius** [comment]
@danmayer Great news! This shouldn't be a tough one to add either.

**Comment by headius** [comment]
@danmayer This turned out to be fairly easy to do in #6185, so that's merged to master now. We will look into the differences between our coverable lines and CRuby's coverable lines.

Let us know if you find any other issues!
