### ISSUE TITLE
File.fnmatch with File::FNM_PATHNAME doesn't treat [/a] or [a/] like [a] as MRI does

### ISSUE THREAD

**Issue by robotdana** [jruby/jruby#6193]
File.fnmatch with File::FNM_PATHNAME doesn't treat `[/a]` like `[a]` as MRI does, it seems like it treats it like `[]` instead:

Here's a travis build and sample project: 

https://travis-ci.org/github/robotdana/jruby-fnmatch/jobs/679588429

https://github.com/robotdana/jruby-fnmatch

The failing examples (that pass on at least mri 2.4-2.7) are: 
expect(::File.fnmatch?('a[a/]a', 'aaa', ::File::FNM_PATHNAME)).to be true
expect(::File.fnmatch?('a[/a]a', 'aaa', ::File::FNM_PATHNAME)).to be true

MRI seems to be interpreting the pattern as `a[a]a`, while jruby seems to be interpreting it as `a[]a` that is, a pattern that will match nothing.

The behaviour here is not documented either way https://ruby-doc.org/core-2.5.0/File.html#method-c-fnmatch so i'm not sure if it counts it as a bug, but it seems to have consistently worked that way in MRI. (also in git which like mri also uses c fnmatch internally, and is how i stumbled across this inconsistency when adding jruby to the test matrix for https://github.com/robotdana/fast_ignore)

**Comment by headius** [comment]
Thank you for the report! I'll have a look at it.

**Comment by headius** [comment]
Also thank you for the very nice reproduction code. It's refreshing to have someone provide a repository rather than a badly quoted IRB session.

**Comment by robotdana** [comment]
thanks :) i haven’t used jruby much before so i wanted to be sure i wasn’t just doing something silly

**Comment by headius** [comment]
I can confirm the issue on JRuby (and seemingly on TruffleRuby as well) but I did not find any test cases anywhere that exercise this case. JRuby passes all of the ruby specs and tests for fnmatch at present, so I think it would be a great contribution for you to add these specs to https://github.com/ruby/spec.

Fixing it is another matter...

**Comment by headius** [comment]
Luckily since our fnmatch is a port from CRuby, this has a straightforward fix. Unfortunately the existing port has diverged a bit, so I'll spin up a PR to do a re-port and re-factoring of the code.

**Comment by headius** [comment]
See #6231, which already passes your spec.
