### ISSUE TITLE
test/test_socket.rb:test_multicast_send_and_receive hangs with firewall enabled

### ISSUE THREAD

**Issue by ghost** [jruby/jruby#620]
test_multicast_send_and_receive performs network I/O on an external interface, which is a Bad Thing[tm] to do in unit tests.  It hangs completely if with a firewall enabled that blocks everything by default.

This test should either be fixed to only do I/O on localhost, or disabled.

**Comment by j2man** [comment]
Disabling this test was a bad idea. I/O on local host would have been much better. Multicast receive on Windows 10 is broken and who knows how long its been that way. Vendors that rely on JRuby like Elastic are left delivering broken code to their customers. Once you give a reason to move the only barrier is a competing product either homegrown or open source.
