### ISSUE TITLE
Time.now is inconsistent with MRI and Java System time

### ISSUE THREAD

**Issue by seanstory** [jruby/jruby#6202]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)

```
$ jruby -v
jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 25.222-b10 on 1.8.0_222-b10 +jit [darwin-x86_64]
```
* Operating system and platform (e.g. `uname -a`)

```
$ uname -a
Darwin Seans-MBP.attlocal.net 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
```

Other relevant info:
* locally cloned and built (`make`) [libfaketime](https://github.com/wolfcw/libfaketime)
* Environment variables

```
export DYLD_INSERT_LIBRARIES=/path/to/libfaketime/src/libfaketime.1.dylib # product of running `make` on the above-mentioned libfaketime/ repo
export DYLD_FORCE_FLAT_NAMESPACE=1
export FAKETIME="-15d"
```

**Expected Behavior**
If today's date is 5/4/2020, and I have the above environment variables set, and libfaketime built, I see the below with MRI ruby:

```
$ date
Sun Apr 19 12:21:46 CDT 2020
$ rbenv local 2.5.8
$ ruby -e 'p Time.now'
2020-04-19 12:21:53 -0500
```

Notice that libfaketime has correctly managed to change the date to 4/19/2020, rather than 5/4/2020.

**Actual Behavior**

Same day, same environment variables and libfaketime installation:

```
$ date
Sun Apr 19 12:23:44 CDT 2020
$ rbenv local jruby-9.2.9.0
$ ruby -e 'p Time.now'
2020-05-04 12:23:53 -0500
```
Notice that the date is not faked.

Further, notice that the Java System time is accurate:
```
$ ruby -e 'p Time.at java.lang.System.currentTimeMillis / 1000; p Time.now'
2020-04-19 12:24:55 -0500
2020-05-04 12:24:55 -0500
```

I filed a similar issue with libfaketime, as I wasn't initially sure where the bug really originates: https://github.com/wolfcw/libfaketime/issues/255

However upon noticing this [FIXME](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyTime.java#L1542)
```
// FIXME: we should have a pure Java fallback in jnr-posix and Windows is missing gettimeofday impl
```
in the `RubyTime.java` class, I modified my `~/.jrubyrc` such that:

```
$ cat ~/.jrubyrc
native.enabled=false
```
and voila:

```
$ rbenv local jruby-9.2.9.0
$ ruby -e 'p Time.at java.lang.System.currentTimeMillis / 1000; p Time.now'
2020-04-19 12:27:37 -0500
2020-04-19 12:27:37 -0500
```

However, having to disable _all_ native calls just to get Time to behave consistenly seems like overkill, especially due to the existing FIXME comment. I couldn't find an issue for that comment, but if there is one already, I'm happy to add this as ammunition for getting it fixed. :)

**Comment by headius** [comment]
How peculiar!

**Comment by headius** [comment]
@seanstory I have commented on wolfcw/libfaketime#255. This issue is probably not in libfaketime, but I'm not sure how to fix it in JRuby (and really, in jnr-posix). I've asked @wolfcw for some tips on how this DYLD_INSERT_LIBRARIES mechanism works, since docs online seem to be very slim.

I don't doubt there's a way for us to fix this, but at the moment I don't know how to proceed.

**Comment by seanstory** [comment]
Thanks! No worries - just having a paper trail that the next confused dev can follow is an awesome start. I'll follow the other issue as well.

**Comment by seanstory** [comment]
@headius I've been following the conversation in https://github.com/wolfcw/libfaketime/issues/255, specifically your last comment that:
> we'll carry on with jruby and jnr bugs to add this functionality on our end.

Is there already a jnr bug? Should I file one? or is this issue sufficient?

**Comment by headius** [comment]
@seanstory I'll open two new bugs against jnr-ffi and jnr-posix that support this one.

**Comment by headius** [comment]
Fixed on master!
