### ISSUE TITLE
Raise Ruby exception in JRuby 

### ISSUE THREAD

**Issue by p-mongo** [jruby/jruby#6203]
I would like to raise an exception class defined in Ruby from Java code. How would one do this?

The examples given in https://github.com/jruby/jruby/wiki/JRuby-Reference#Exceptions all show how to work with Java exceptions, but I would like to raise a Ruby exception.

We have this code:

<pre>
    try {
      string = (RubyString) value;
    } catch (ClassCastException e) {
      throw context.runtime.newArgumentError(e.toString());
    }
</pre>

I tried:

<pre>
        RubyClass cls = this.runTime.getClass("Mongo::GssapiNative::Error");
        RubyString msg = RubyString.newString(context.runtime, message);
        throw cls.newInstance(context, msg, Block.NULL_BLOCK);
</pre>

This failed with:

<pre>
src/main/org/mongodb/sasl/GSSAPIAuthenticator.java:141: error: incompatible types: IRubyObject cannot be converted to Throwable
        throw cls.newInstance(context, msg, Block.NULL_BLOCK);
                             ^
</pre>

So I need to convert my Ruby class instance to a Throwable?

Related question: our [existing code](https://github.com/mongodb/mongo-ruby-kerberos/blob/master/src/main/org/mongodb/sasl/MongoSecurityException.java) supports exception causes, how do I attach those to Ruby exception classes? Is this handled for me automatically somehow?

Thanks in advance.

**Comment by headius** [comment]
I guess you want to be able to *construct* a JRuby Throwable, yes?

When you have an existing Ruby exception in hand, you can use `RubyException#toThrowable` to get a Throwable that Java can raise.

If you need to *construct* a new Ruby exception, you have two options:

If you want to construct one of the built-in "standard" errors from Ruby, you can use the Ruby runtime's `newXXXError` methods. They will return a new RaiseException (a Throwable) that wraps a new RubyException (regular JRuby object). See for example the following code from JRuby itself:

https://github.com/jruby/jruby/blob/83d33f8763f085d877e857c8b724d29b63e0d32a/core/src/main/java/org/jruby/runtime/Arity.java#L164-L174

If, however, you need to construct a non-standard error (which appears to be the case from your example, you have two sub-options!

1. You can use the code you figured out on your own, followed by casting the object to `RubyException` and calling `toThrowable` to get a Throwable.
2. You can use `runtime.newRaiseException` or `RaiseException.from(runtime, exceptionClass, message)`

A simpler mechanism might be warranted.

**Comment by headius** [comment]
FWIW `exceptionClass` would be used with the object you retrieved from `this.runTime.getClass("Mongo::GssapiNative::Error")`.

**Comment by headius** [comment]
I looked into how we implement `cause` and I think we are missing some JVM integration. Basically, there are *two* possible causes for a given Ruby error in JRuby.

One of those causes is stored on the original Java Throwable, just like you are doing in your linked code. I believe once you get a JRuby Throwable, you should be able to set (exactly once) the Java cause to whatever you want.

The other cause is stored on RubyException, and must be a Ruby object.

The missing integration would be to unify these somewhat, so that setting a Ruby cause sets the Java cause and vice versa.

I think the actual work items for this bug are:

* Consider adding a better way to construct non-standard Ruby errors and their Throwable equivalents.
* Unify Ruby cause and Java cause.

**Comment by p-mongo** [comment]
Thank you @headius , this is very helpful. I ran into some other issues trying to apply [this](https://github.com/mongodb/bson-ruby/blob/master/src/main/org/bson/NativeService.java#L62) to our gssapi extension, and taking a step back I think I would like to start from the beginning of JRuby extension development and write a guide similar to what we've done [here](https://docs.mongodb.com/mongoid/master/tutorials/getting-started-rails/) for Mongoid, with narrative and sample code. Is there interest in JRuby project owning the repo with such a guide?

**Comment by headius** [comment]
@p-mongo We'd love to have more example repos! Let us know when you have something appropriate and we can see about including it in the jruby organization.

**Comment by headius** [comment]
I have a patch in progress to try to sync up cause between Java and Ruby. I will push it into a PR with some API enhancements for creating Ruby exceptions from Java.

**Comment by headius** [comment]
Oh I also updated the wiki page you referenced to have some Java examples!

**Comment by headius** [comment]
I've pushed #6234, have a look and see what you think!

**Comment by p-mongo** [comment]
I started on the guide: https://github.com/p-mongo/jruby-extension-guide

**Comment by headius** [comment]
I've merged #6234!

Your extension guide is looking good. Could you open a separate issue about it? I'd like to discuss it with @kares and @enebo not in the context of this bug. We do need a nice guide like this, and there have been attempts in the past... so it's time to clean it all up and decide on the "right" way to do all this stuff.
