### ISSUE TITLE
[Documentation / Wiki] Incorrect Link (Link is no longer working in one href)

### ISSUE THREAD

**Issue by rubyFeedback** [jruby/jruby#6208]
Yo headius and others,

Not sure if it is worth reporting so I just thought to briefly mention it. The link at:

https://github.com/jruby/jruby/wiki/WalkthroughsAndTutorials

contains another entry towards:

"Using Java Classes in JRuby"

which in turn links towards:

 -> http://blogs.oracle.com/coolstuff/entry/using_java_classes_in_jruby

However had, that last link towards blogs.oracle.com no longer is
available. "The content that you're looking is no longer on this page."
I noticed this while slowly reading jruby docs right now. Anyway
just wanted to briefly report it, cheers!

**Comment by headius** [comment]
It looks like the page has been gone for years, but I've modified the link to point at an internet archive.

Thank you! Let us know if you see any other problems with the wiki (or feel free to correct them yourself!)
