### ISSUE TITLE
jirb and the --debug flag

### ISSUE THREAD

**Issue by MarcoCostantini** [jruby/jruby#6216]
jirb says to use the --debug flag, but how can it be  supplied to jirb?

$ jruby -v
jruby 9.1.17.0 (2.3.3) 2020-02-29 fffffff OpenJDK 64-Bit Server VM 11.0.7+10-post-Ubuntu-3ubuntu1 on 11.0.7+10-post-Ubuntu-3ubuntu1 +jit [linux-x86_64]
$ jirb -v
irb 0.9.6(09/06/30)
$ jirb 
irb(main):001:0> require "test/unit/assertions"
/usr/lib/ruby/vendor_ruby/power_assert.rb:8: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
/usr/lib/ruby/vendor_ruby/power_assert.rb:8: warning: tracing (e.g. set_trace_func) will not capture all events without --debug flag
=> true
irb(main):002:0>

**Comment by enebo** [comment]
You can use -S:

```text
jruby --debug -S jirb
```

This is also useful for any other option you may want to pass to Ruby.

**Comment by headius** [comment]
Also `JRUBY_OPTS` environment variable!
