### ISSUE TITLE
testing with openjdk11 in Travis CI

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby#6278]
openjdk8 will stop being supported by Ubuntu releases in 9 months in April 2021, it would be great if CI could be done with openjdk11 as well since that's what a lot of people will need to move to in the near future. Just a suggestion!

**Comment by kares** [comment]
this is now a thing: https://travis-ci.org/github/jruby/jruby/builds/702101546 (even Java 14 was added later)
