### ISSUE TITLE
FFI::MemoryPointer autorelease issue

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#6284]
**Environment Information**
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-06-15 ccecbe8014 Java HotSpot(TM) 64-Bit Server VM 11.0.2+9-LTS on 11.0.2+9-LTS +jit [linux-x86_64]
(and jruby 9.2.11.1)

sassc 2.4.0

recently, I've noticed segfaults on https://travis-ci.org/github/rails/sprockets/jobs/696412377

```
git clone https://github.com/rails/sprockets.git
bundle update
rake test
```

**Expected Behavior**
it looks like FFI::MemoryPointer is being GCed, even if autorelease is explicitly disabled

**Actual Behavior**
see https://github.com/sass/sassc-ruby/pull/205

```
*** Error in `/usr/local/lib/jvm/openjdk11/bin/java': double free or corruption (out): 0x00007efc4cde2550 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7efc554f37e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7efc554fc37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7efc5550053c]
[0x7efc34c67890]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:01 791938                             /usr/local/lib/jvm/openjdk11/bin/java
...
```

**Comment by headius** [comment]
Aha, well this certainly could be a cause of #6310 and sass/sassc-ruby#208.

**Comment by headius** [comment]
@ahorek Help me by trying out https://github.com/jruby/jruby/pull/6331

**Comment by ahorek** [comment]
patch https://github.com/jruby/jruby/pull/6331 confirmed. thank you!

**Comment by headius** [comment]
@ahorek Hot diggity! We'll roll it into 9.2.13.
