### ISSUE TITLE
Failed to install bindex on a Windows 10 PC

### ISSUE THREAD

**Issue by belgoros** [jruby/jruby#6291]
I installed jruby `9.2.9.0` on a Windows 10 PC and tried to create a scaffolded Rails app as follows:
``` 
jruby -S rails new jruby-blog -T #to skip tests
```` 
Several tricks had to be done:
- modify the generated `Gemfile` and remove `ruby '2.5.7'` line, - bundler raised an error complaining about the difference in `.ruby-version` file (it has `jruby-9.2.9.0` declared) and the one declared in the Gemfile.
- running `jruby -S bundle` failed because of `bindex-0.8.1` gem compilation:
![image](https://user-images.githubusercontent.com/83579/85138454-1601ef80-b243-11ea-9f9d-c6281079dbb2.png)

So I tried to install the gem manually:
```
$ jruby -S gem install bindex -v '0.8.1'
C:/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:34: warning: constant Gem::ConfigMap is deprecated
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from C:/jruby-9.2.9.0/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from C:/jruby-9.2.9.0/lib/ruby/gems/shared/specifications/jruby-win32ole-0.8.5.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from C:/jruby-9.2.9.0/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
C:/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:34: warning: constant Gem::ConfigMap is deprecated
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from C:/jruby-9.2.9.0/lib/ruby/gems/shared/specifications/jruby-win32ole-0.8.5.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from C:/jruby-9.2.9.0/lib/ruby/gems/shared/specifications/default/json-2.2.0-java.gemspec:18.
Building native extensions. This could take a while...
ERROR:  Error installing bindex:
        ERROR: Failed to build gem native extension.

    current directory: C:/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bindex-0.8.1/ext/skiptrace
C:/jruby-9.2.9.0/bin/jruby.exe -I C:/jruby-9.2.9.0/lib/ruby/stdlib -r ./siteconf20200619-16248-vjxcvl.rb extconf.rb
extconf failedNo such file or directory - {"SOURCE_DATE_EPOCH"=>"1592574077"}

Gem files will remain installed in C:/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bindex-0.8.1 for inspection.
Results logged to C:/jruby-9.2.9.0/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.0/bindex-0.8.1/gem_make.out
```

Finally, no way to finish a Rails app creation and install the needed gems.

The same issue is reproducible on the `9.2.11.1` version. A temporary solution for **bindex** gem was to comment out the `web-console` gem in the `development` group of the Gemfile. But another error raised, - this time it is `sass-rails` that stopped the bundler:
```
Fetching sassc 2.4.0
Installing sassc 2.4.0 with native extensions
C:/jruby-9.2.11.1/lib/ruby/stdlib/rubygems/ext/builder.rb:76: warning: unsupported popen option: err
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/sassc-2.4.0/ext
C:/jruby-9.2.11.1/bin/jruby.exe -I C:/jruby-9.2.11.1/lib/ruby/stdlib -r
./siteconf20200619-21636-38dzv6.rb extconf.rb
creating Makefile

current directory: C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/sassc-2.4.0/ext
make "DESTDIR=" clean
current directory: C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/sassc-2.4.0/ext
make "DESTDIR="
make failedCannot run program "make" (in directory
"C:\jruby-9.2.11.1\lib\ruby\gems\shared\gems\sassc-2.4.0\ext"): CreateProcess
error=2, The system cannot find the file specified

Gem files will remain installed in
C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/sassc-2.4.0 for inspection.
Results logged to
C:/jruby-9.2.11.1/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.0/sassc-2.4.0/gem_make.out

An error occurred while installing sassc (2.4.0), and Bundler cannot continue.
Make sure that `gem install sassc -v '2.4.0' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  sass-rails was resolved to 6.0.0, which depends on
    sassc-rails was resolved to 2.1.2, which depends on
      sassc
```

**Environment Information**
  
* JRuby version: `jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 Java HotSpot(TM) 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 +jit [mswin32-x86_64]`.

* Operating system and platform: Windows 10, `MINGW64_NT-10.0-17763 PO190000391 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys`.

What is wrong with that?
I also have Ruby `ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]` installed which works without any problems.

**Comment by headius** [comment]
> modify the generated Gemfile and remove ruby '2.5.7' line, - bundler raised an error complaining about the difference in .ruby-version file (it has jruby-9.2.9.0 declared) and the one declared in the Gemfile.

This seems like a Rails issue... can you raise a bug with them about it? They are not generating the Gemfile for JRuby correctly.

> running jruby -S bundle failed because of bindex-0.8.1 gem compilation:

This seems to be a bug in bindex plus JRuby plus Windows: https://github.com/gsamokovarov/skiptrace/issues/8

I have pinged @gsamokovarov about getting the gem working on Windows (now called skiptrace).

> But another error raised, - this time it is sass-rails that stopped the bundler:

The sass problem is an issue with the sassc gem: https://github.com/sass/sassc-ruby/issues/182

I have also filed this issue with Rails, since they changed from using sass-ruby to sassc in a minor update: https://github.com/rails/rails/issues/38492

The workaround for now is to downgrade `sass-rails` to an earlier version that uses `sass-ruby`, I think.

I understand your frustration... perhaps you can understand ours. Please make noise in all these bugs!

**Comment by belgoros** [comment]
@headius Wow, thanks a lot! It seems like a dependency nightmare 😢 . Back in 2014, I could surprised my Java teammates how easy and quickly we could create a blog, package everything with Warbler and startup Tomcat. By the way, as it is often the case with Ruby packages for Windows, it fails compared to macOS, - I've just replayed the same installation steps using RVM, everything works as needed. I'll try to analyze it and _make noise_ here and there...

**Comment by headius** [comment]
Yeah, I would not say this is a problem supporting JRuby as much as it is a problem supporting Windows. It feels like over the years the rails team has grown less and less interested in keeping things working on Windows, but since JRuby works so well there we often end up having to field these issues.

None of these are particularly difficult to fix, in any case, but having a user make some noise will strengthen our case for actually making those fixes.

**Comment by headius** [comment]
Duplicated by #6648 but should be fixed by the same changes.
