### ISSUE TITLE
jruby-jars profile fails on Java 11

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6297]
I'm trying to get all suites running on Java 11 but having trouble with jruby-jars. It ends up with the old "No password supplied for PKCS#12 keystore" error, which I thought we had worked around in more recent versions of jruby-openssl.

```
[INFO] ------------------------< rubygems:jruby-jars >-------------------------
[INFO] Building JRuby Jars Gem 9.3.0.0-SNAPSHOT                           [5/5]
[INFO] --------------------------------[ gem ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (default) @ jruby-jars ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ jruby-jars ---
[INFO] 
[INFO] --- gem-maven-plugin:1.1.8:initialize (default-initialize) @ jruby-jars ---
Downloading from mavengems: mavengem:https://rubygems.org/org/jruby/jruby-complete/9.3.0.0-SNAPSHOT/maven-metadata.xml
OpenSSL::X509::StoreError: setting default path failed: No password supplied for PKCS#12 KeyStore.
  set_default_paths at org/jruby/ext/openssl/X509Store.java:165
         SSLContext at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:31
                SSL at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:22
            OpenSSL at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:21
             (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:20
               load at org/jruby/RubyKernel.java:1087
```

Note that the only place I could find the gem-maven-plugin used in the jruby-jars artifact already has it patched to set `jrubyVersion` to use a 9.3 snapshot, from commit bc9867abc7245b72ae951dbf17089fc52624de20.

The stack trace showing "jopenssl19" leads me to believe that it's still using JRuby 1.7, because that version was compatible with Ruby 1.9. I tried updating the plugins (it's on 1.0.7 now and current is 1.1.18) and setting the property `javax.net.ssl.trustStoreType` to `JKS` in various places, but nothing seems to change this output.

See #6296 for my ongoing Java 11 work.

**Comment by headius** [comment]
ping @mkristian @kares

**Comment by enebo** [comment]
I am able to successfully run ```mvn -Pjruby-jars``` on Java 11.  Closing.
