### ISSUE TITLE
Align behavior with CRuby for security specs

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6304]
In #6303 @eregon noticed a few of the security specs do not pass currently.

Tags are here: https://github.com/jruby/jruby/pull/6303/commits/48c5e8552f404be3153391cacb7de54e2476c587

An example run is here: https://travis-ci.org/github/jruby/jruby/jobs/702869188

The failures are mostly due to us not randomizing hash calculation, but there's a few others that warrant a second look. I believe it would be best for us to patch these for the 9.2.12 release this week.

**Comment by headius** [comment]
The hash failures are all due to us not using siphash plus a random seed in the numeric classes. As with other places this was patched, we have not generally agreed with the "fix" of randomizing hashes, and instead allow users to opt into siphash if they have concerns. That decision could be revisited, but at least we should update the numeric classes to also have optional siphash calculation. We may also be able to use our existing "perlhash" with a random seed and meet the spirit of these fixes.

The WEBrick failures appear to have never been made to the ruby/webrick repository, or at least Ruby 2.6 claims to ship WEBrick 1.4.2, but there are extensive diffs from the ruby_2_6 branch and the WEBrick v1.4.2 tag. It appears CRuby has diverged here without properly updating release versions.

The Array#pack failure shows a place where we are not propagating tainting. We have never fully supported tainting, as it is a broken security mechanism. Nevertheless, we should be able to patch this easily to pass the spec. I assume this spec will no longer be relevant when tainting is removed as a feature.

The String#unpack failure simply raises the wrong error. There's no vulnerability here (both because of the error and because the JVM will prevent such memory issues), but we could add the logic to raise the RangeError the spec expects.

**Comment by headius** [comment]
The numeric hash failures are addressed in #6305.

The String#unpack error is addressed in #6306.

**Comment by headius** [comment]
The Array#pack failure is due to us not tainting the result when any of the elements of the array are themselves tainted.

The modifications to fix this would be somewhat invasive.

Given the fact that:

* tainting is deprecated in 2.7 and to be removed in 2.8/3.0
* tainting has never been fully supported in JRuby
* tainting is in fact a broken security mechanism

...I vote that we don't bother with this change.

**Comment by headius** [comment]
The remaining WEBrick failures will be addressed once we figure out what version of WEBrick is actually being shipped in Ruby 2.5.x and 2.6.x. CRuby appears to be shipping heavily patched sources for both releases, while claiming they're both WEBrick 1.4.2.

https://github.com/ruby/webrick/issues/48

**Comment by eregon** [comment]
The 2 PRs seem green now.
Should they also be applied to master, along with removing no longer needed spec tags?

**Comment by headius** [comment]
@eregon We periodically merge jruby-9.2 to master. The spec tags can be removed at that point.

**Comment by headius** [comment]
All security spec failures have been addressed:

* The hashing randomization was fixed by #6305.
* The String#unpack exception was fixed by #6306.
* The Array#pack tainting issue will be ignored, since tainting is not a supported feature.
* The WEBrick request-splitting issue was fixed by updating to WEBrick 1.6.0 in #6308.

**Comment by headius** [comment]
Spec tags have been updated on master.
