### ISSUE TITLE
`Enumerator::Lazy#slice_after` returns non-lazy Enumerator (jruby-9.1.17.0)

### ISSUE THREAD

**Issue by DocX** [jruby/jruby#6324]
**Environment Information**

Both:

* (Mac): jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 13.0.2+8 on 13.0.2+8 +jit [darwin-x86_64]
* (Docker): jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 25.252-b09 on 1.8.0_252-b09 +jit [linux-x86_64]

**Expected Behavior**

`slice_after` on lazy enumerator should return lazy enumerator. This is to make sure chaining enum operators after that does not result in "finalized" array, but it keep be lazy enumerator.

```rb
[1,2,3].lazy.slice_after { |i| i == 2 }
=> #<Enumerator::Lazy: #<Enumerator: #<Enumerator::Generator:0x00007ffd2cabbd38>:each>>

[1,2,3].lazy.slice_after { |i| i == 2 }.map { |i| i }
=> #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator: #<Enumerator::Generator:0x00007ffd2caa97c8>:each>>:map>
```

**Actual Behavior**

`slice_after` returns instance of Enumerator, not Enumerator::Lazy. This causes that chaining enum operators like `map` results in `Array` instead of `Enumerator::Lazy` - breaking the expected interface.

```rb
[1,2,3].lazy.slice_after { |i| i == 2 }
=> #<Enumerator: #<Enumerator::Generator:0x47dd778>:each>

[1,2,3].lazy.slice_after { |i| i == 2 }.map { |i| i }
=> [[1, 2], [3]]
```

**Comment by headius** [comment]
This appears to be working in latest JRuby (9.2.12.0):

```
$ jruby -e 'p [1,2,3].lazy.slice_after { |i| i == 2 }'
#<Enumerator::Lazy: #<Enumerator: #<Enumerator::Generator:0x1b26f7b2>:each>>
```

This was probably fixed in 9.2.9.0 via #5834.

The 9.1.x line is no longer supported. You should upgrade to a recent version of 9.2 to get the fix.
