### ISSUE TITLE
spreading hashes does not work unless key is symbol

### ISSUE THREAD

**Issue by HoneyryderChuck** [jruby/jruby#6327]
**Environment Information**
  
Provide at least:
* JRuby version: 9.2.12.0
* Operating system and platform: MacOS

**Expected Behavior**

This is what happens on Ruby 2.7

```ruby
irb(main):001:0> {**{"a" => "b"}}
=> {"a"=>"b"}
irb(main):002:0>
```

**Actual Behavior**

```
irb(main):001:0> {**{"a" => "b"}}
Traceback (most recent call last):
        6: from /Users/me/.rubies/jruby-9.2.12.0/bin/irb:13:in `<main>'
        5: from org/jruby/RubyKernel.java:1189:in `catch'
        4: from org/jruby/RubyKernel.java:1189:in `catch'
        3: from org/jruby/RubyKernel.java:1442:in `loop'
        2: from org/jruby/RubyKernel.java:1048:in `eval'
        1: from (irb):1:in `evaluate'
TypeError (wrong argument type String (expected Symbol))
irb(main):002:0>
```

if the key were a symbol, it would work.

**Comment by headius** [comment]
This is correct behavior on both 2.5 and 2.6. We do not support Ruby 2.7 behavior yet.

```
$ rvm ruby-2.5.7 do ruby -v -e '{**{"a" => "b"}}'
ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-darwin18]
Traceback (most recent call last):
-e:1:in `<main>': wrong argument type String (expected Symbol) (TypeError)

$ rvm ruby-2.6.5 do ruby -v -e '{**{"a" => "b"}}'
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
Traceback (most recent call last):
-e:1:in `<main>': hash key "a" is not a Symbol (TypeError)
```

This also is still an open question even in CRuby, and I'm not sure the behavior you see will survive into Ruby 2.8/3.0. Could you do some investigation and see if you can figure out the current status of this behavior on CRuby master?

**Comment by HoneyryderChuck** [comment]
Created https://bugs.ruby-lang.org/issues/17035 , feel free to chime in.

**Comment by HoneyryderChuck** [comment]
@headius apparently it's a new feature starting from 2.7 . I'll close it, as you're right that compliance with 2.5 is already achieved.
