### ISSUE TITLE
java_send should be smart enough to unwrap the Ruby version of a Java class

### ISSUE THREAD

**Issue by carllerche** [jruby/jruby#638]
That's what @headius told me to say...

Trying to call java_send and pass references to the java classes results in the following error:

cannot convert instance of class org.jruby.RubyModule to class java.lang.Class

Using the following works:

java.lang.Class.for_name("com.netflix.astyanax.MutationBatch")

**Comment by kares** [comment]
expect this to be fixed on >= **1.7.20** ... an issue with the similar underlying cause was reported at #2881
