### ISSUE TITLE
DateTime loses timezone offsets on marshal/unmarshal

### ISSUE THREAD

**Issue by paulkerschen** [jruby/jruby#6385]
On JRuby 9.2, marshaling and unmarshaling a DateTime object with a nonzero timezone offset outputs an “invalid offset is ignored” warning, and returns a DateTime with the timezone offset set to zero.

I believe the marshal dump and load methods in org.jruby.ext.date.RubyDate may be representing nonzero timezone offsets in an incompatible way.

**Environment Information**
  
* JRuby 9.2.13.0
* Fresh install with no additional gems
* No additional flags or JRUBY_OPTS

**Expected Behavior**

On MRI 2.5.7, marshaling and unmarshaling a DateTime object preserves timezone offset without error. Minimal example in irb:

```
:001 > require 'date'
 => true 
 :002 > d = DateTime.now
 => #<DateTime: 2020-09-03T10:00:56-07:00 ((2459096j,61256s,323456000n),-25200s,2299161j)> 
 :003 > Marshal.load(Marshal.dump(d))
 => #<DateTime: 2020-09-03T10:00:56-07:00 ((2459096j,61256s,323456000n),-25200s,2299161j)>
```

**Actual Behavior**

Minimal irb example in JRuby 9.2.13.0. Note “invalid offset is ignored” warning and loss of timezone offset information after marshaling and unmarshaling.

```
jruby-9.2.13.0 :001 > require 'date'
 => true 
jruby-9.2.13.0 :002 > d = DateTime.now
 => #<DateTime: 2020-09-03T09:53:30-07:00 ((2459096j,60810s,196000000n),-25200s,2299161j)> 
jruby-9.2.13.0 :003 > Marshal.load(Marshal.dump(d))
invalid offset is ignored
 => #<DateTime: 2020-09-03T16:53:30+00:00 ((2459096j,60810s,196000000n),+0s,2299161j)> 
```

A DateTime object with zero offset does not trigger the warning.

```
jruby-9.2.13.0 :001 > require 'date'
 => true 
jruby-9.2.13.0 :002 > d = DateTime.now.new_offset(0)
 => #<DateTime: 2020-09-03T17:19:31+00:00 ((2459096j,62371s,904000000n),+0s,2299161j)> 
jruby-9.2.13.0 :003 > Marshal.load(Marshal.dump(d))
 => #<DateTime: 2020-09-03T17:19:31+00:00 ((2459096j,62371s,904000000n),+0s,2299161j)> 
```

JRuby 9.1.17.0 does not exhibit the issue.

```
jruby-9.1.17.0 :001 > require 'date'
 => true 
jruby-9.1.17.0 :002 > d = DateTime.now
 => #<DateTime: 2020-09-03T10:13:04-07:00 ((2459096j,61984s,83000000n),-25200s,2299161j)> 
jruby-9.1.17.0 :003 > Marshal.load(Marshal.dump(d))
 => #<DateTime: 2020-09-03T10:13:04-07:00 ((2459096j,61984s,83000000n),-25200s,2299161j)> 
```

**Comment by headius** [comment]
Interesting that this actually regressed. Will investigate.

**Comment by headius** [comment]
The "invalid offset" message shows up in 9.2.0.0 and not in 9.1.17.0 so this seems to be a regression in 9.2 right away.

**Comment by headius** [comment]
Ok, here's the code being ported over from the Ruby side to the Java side in 9.2.0.0 timeframe. The port seems straightforward:

https://github.com/jruby/jruby/commit/32a425d976c39d68389647f16a6d8346043285d5#diff-39bbca646c1ec079b72e5848192dc0efR720-R728

https://github.com/jruby/jruby/commit/32a425d976c39d68389647f16a6d8346043285d5#diff-3da55e4d15832938cf080abd73282c91L1546-L1547

But the dump output seems to have changed:

```
[] ~/projects/jruby $ rvm jruby-9.2.0.0 do ruby -rdate -e 'p Marshal.dump(DateTime.strptime("2020-09-15T19:14:30-05:00"))'
"\x04\bU:\rDateTime[\bU:\rRational[\al+\b\xBDJ\"\xA6\x01\x00i\x02@\vi\xFE\xB0\xB9i\x03\x19\x15#"

[] ~/projects/jruby $ rvm jruby-9.1.17.0 do ruby -rdate -e 'p Marshal.dump(DateTime.strptime("2020-09-15T19:14:30-05:00"))'
"\x04\bU:\rDateTime[\bU:\rRational[\al+\b\xBDJ\"\xA6\x01\x00i\x02@\vU;\x06[\ai\xF6i\x1Di\x03\x19\x15#"
```

There's also a port of `marshal_load` to Java:

https://github.com/jruby/jruby/commit/d5c2aea4d18b8e67cebfb357f060c9841b3daa2f

but using the 9.1.17.0 dump with the 9.2.0.0 load appears to work correctly:

```
[] ~/projects/jruby $ rvm jruby-9.2.0.0 do ruby -rdate -e 'p Marshal.load("\x04\bU:\rDateTime[\bU:\rRational[\al+\b\xBDJ\"\xA6\x01\x00i\x02@\vU;\x06[\ai\xF6i\x1Di\x03\x19\x15#")'
#<DateTime: 2020-09-15T19:14:30-05:00 ((2459108j,87270s,0n),-18000s,2299161j)>

[] ~/projects/jruby $ rvm jruby-9.1.17.0 do ruby -rdate -e 'p Marshal.load("\x04\bU:\rDateTime[\bU:\rRational[\al+\b\xBDJ\"\xA6\x01\x00i\x02@\vU;\x06[\ai\xF6i\x1Di\x03\x19\x15#")'
#<DateTime: 2020-09-15T19:14:30-05:00 ((2459108j,87270s,0n),-18000s,2299161j)>
```

So it seems this dump logic did not port as easily as it seemed. 🤔

**Comment by headius** [comment]
@kares Maybe you can see something that got lost during the porting work you did in 9.2?

**Comment by headius** [comment]
Thanks @kares for the fix!
