### ISSUE TITLE
Using <internal: for core library methods defined in Ruby

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6430]
Core library methods' `source_location` and in backtraces defined with Ruby code [look like](https://gist.github.com/eregon/912e6359e83781c5fa1c638d3768c526) this:
* `<internal:kernel>:89` on CRuby
* `<internal:core> core/kernel.rb:533` on TruffleRuby
* `uri:classloader:/jruby/kernel/enumerator.rb:243` on JRuby

I would suggest to use a `<internal:` prefix since this is becoming the de facto standard.
That will also provide a consistent way to filter out core library methods defined in Ruby when desirable.

Also note that both CRuby 3 and TruffleRuby ignore entries starting with `<internal:` for `Kernel#warn(msg, uplevel: n)` (details in https://github.com/rubygems/rubygems/pull/3987#issuecomment-704334889).

**Comment by headius** [comment]
I am reluctant to use something as meaningless as "internal" since it can't be resolved to a real path by any code. The path we provide with "uri:classloader:" is actually the path that gets required; it indicates clearly where the source is located (as a classloader resource) and the full path to that file within the classloader.

We will consider an appropriate way to add the "internal" identifier without losing the actual classloader path information.

**Comment by eregon** [comment]
What about something like:
`<internal:uri:classloader:/jruby/kernel/enumerator.rb:243>` or
`<internal:core> uri:classloader:/jruby/kernel/enumerator.rb:243`?
The only important part for this issue is that it starts with `<internal:`.

It doesn't seem good to ask 3rd-party libraries which sometimes need to filter out core methods (e.g. for warnings, or for more relevant backtraces for test frameworks) to have various different regexps to skip those, and `<internal:` seems an easy prefix to standardize on ([here](https://github.com/sinatra/sinatra/blob/0aa8d507a4b9140c883e4110e6023e90077bd1d4/lib/sinatra/base.rb#L1203-L1212) is a particularly telling example).

External processes can't understand `uri:classloader` anyway, and internally `File/IO` methods could recognize a variant of the prefix starting with `<internal:`.

**Comment by headius** [comment]
Linking with #5764 since that rewrites most of the load logic.

**Comment by eregon** [comment]
For more context, see
* https://bugs.ruby-lang.org/issues/17259: CRuby ignoring `<internal:` frames for `warn(msg, uplevel:)`
* which in turns enables to not need to override Kernel#warn in RubyGems: https://github.com/rubygems/rubygems/pull/4075
