### ISSUE TITLE
Stucking on Travis for 9.2.13.0

### ISSUE THREAD

**Issue by godfat** [jruby/jruby#6449]
**Environment Information**
  
* `export JRUBY_OPTS='--dev'`
* `jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc Java HotSpot(TM) 64-Bit Server VM 25.151-b12 on 1.8.0_151-b12 [linux-x86_64]`
* Travis build link: https://travis-ci.org/github/rspec/rspec-mocks/builds/738263507

It got stuck on `script/update_rubygems_and_install_bundler` and the last message was: `Installing ri documentation for rubygems-update-3.1.4`

* Java seems to be invoked via `java -Xmx32m` and `javac -J-Xmx32m`
* `rvm 1.29.3`

**Expected Behavior**

* Should not get stuck on installing Rubygems or something

**Actual Behavior**

* No output for 10 minutes. Travis message:

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

More context can be found at https://github.com/rspec/rspec-mocks/pull/1218#issuecomment-715318136

**Comment by headius** [comment]
@godfat Ok yeah that is pretty weird.

If this build is indeed running with `-Xmx32m` that is likely the problem, but I don't think that's relevant. That appears to only be passed as an argument for the `java` version check.

Stalls like this are sometimes caused by the machine entropy being exhausted, which causes random number seeding and generation to stall in JRuby. I thought we had mostly worked around that, but it might be worth you trying to install the "haveged" service to generate more entropy in the background.

At the moment, I don't see anything obvious that would be causing this.

**Comment by godfat** [comment]
@headius I added this to enable `haveged` (which I just searched around):

``` yaml
addons:
  apt:
    packages: haveged
```

And in https://travis-ci.org/github/rspec/rspec-mocks/jobs/739694269 I can see it it's installed via:

```
Installing APT Packages
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install haveged
Reading package lists...
Building dependency tree...
Reading state information...
haveged is already the newest version (1.7c-1).
0 upgraded, 0 newly installed, 0 to remove and 304 not upgraded.
```

I am not sure if we need to start it somehow or this will already do it 🤔  Unfortunately, the result is the same.

I also noticed that [`script/update_rubygems_and_install_bundler`](https://github.com/rspec/rspec-mocks/blob/main/script/update_rubygems_and_install_bundler) was actually a script from `rspec-mocks`, I thought that's from Travis. So I can take a look at that, and it's running the following: 

``` shell
yes | gem update --system
yes | gem install bundler
```

I am not fully sure if this is a good idea, can it be stdin buffer got filled somehow? I can try to update it and see if it'll make a difference. Will need to wait for a few hours to check the results. I'll update here.

**Comment by godfat** [comment]
@headius Oh it finally runs now, and I found the culprit, though I don't know what is the root cause. If I remove this line:

``` yaml
dist: trusty
```

Then it runs: https://travis-ci.org/github/rspec/rspec-mocks/jobs/739934099

So there's probably something wrong in this Ubuntu version. I bet there's nothing worth spending JRuby team's time for this, so I guess I am closing it.

Thanks!

**Comment by headius** [comment]
@godfat Ok, this doesn't really resolve anything for me, but Trusty Tahr is over four years old now so I'm not going to sweat it.
