### ISSUE TITLE
Bundler 2 related issues on Travis for 9.3.0.0-SNAPSHOT (2.6.5) 2020-10-21 6798b88442

### ISSUE THREAD

**Issue by godfat** [jruby/jruby#6450]
**Environment Information**
  
Provide at least:
* `export JRUBY_OPTS=--debug`
* `jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-10-21 6798b88442 OpenJDK 64-Bit Server VM 11.0.2+9 on 11.0.2+9 +jit [linux-x86_64]`
* Travis build link: https://travis-ci.org/github/godfat/muack/jobs/738072569

`bundler 2.1.4` should be used but it's complaining `You must use Bundler 2 or greater with this lockfile.`?

* Java seems to be invoked via `java -Xmx32m` and `javac -J-Xmx32m`
* `rvm 1.29.10`

**Expected Behavior**

* Bundler should be running with the correct version and should move forward

**Actual Behavior**

* It complained Bundler or greater should be used and exited

**Comment by headius** [comment]
I believe this is a problem with an older version of Bundler that did not support being installed as a "default gem". JRuby 9.3.0.0 currently ships/installs bundler 1.17.3 (this might need RubyGems update to get the newer version).

The error you see might be fixed by making sure the desired Bundler version has been explicitly installed before running the job.

**Comment by headius** [comment]
Actually now I see that you do install bundler 2.1.4 and we still don't pick it up. I suspect this is still an issue with the binstubs, and you are possibly getting an old RubyGems version by running off an old rvm.

Does that sound familiar @deivid-rodriguez?

https://github.com/rubygems/bundler/issues/6937

**Comment by deivid-rodriguez** [comment]
Yes, I think upgrading rubygems should do the trick here.

**Comment by godfat** [comment]
@headius I think the issue you're linking here showed the exact problem here, specifically this comment: https://github.com/rubygems/bundler/issues/6937#issuecomment-460446984

I'll quote the key points here:

> In 1.17.2 it look likes this: `s.files = ["bundler.rb".freeze, "exe/bundle".freeze, "exe/bundler".freeze]` adding `bundler/setup` to the list locally resolves this issue but an actual fix for this, at least as I understand it, means updating the spec file that is shipped with Ruby so likely requires a 1.17.x bundler release that would need to be included in a Ruby 2.6.x release.

And I am running the tests exactly with `bundler/setup` like this:

``` shell
ruby -vr bundler/setup -S rake test
```

So a workaround would be avoiding requiring `bundler/setup`. In the end I decided to just upgrade Rubygems by adding `gem update --system`, and after waiting for 2 hours (super long queue :() on Travis it now passed: https://travis-ci.org/github/godfat/muack/jobs/739642424

JRuby might want to take this patch if it was copied from Ruby: https://bugs.ruby-lang.org/issues/15582

Thank you @headius and @deivid-rodriguez so much! I am closing this assuming this will be fixed by next batch of updates with Rubygems/bundler whatever needed.

**Comment by headius** [comment]
I think a RubyGems update on JRuby master is probably in order. I'll look into that today. Thanks @deivid-rodriguez for confirming and I'm glad you have it working well now @godfat!

**Comment by headius** [comment]
My remaining confusions:

* JRuby master is already on RubyGems 3.0.6 which I believe should have the fixes. That version is still coupled with Bundler 1.17 but I have not locally had any issues activating a newer Bundler.
* With RG and Bundler "bundled" together now, I'm not clear how or if CRuby is upgrading them independently anymore. Maybe @deivid-rodriguez or @hsbt can help clear up how RG and Bundler versioning and stdlib versions of them work now.

I would really love to see someone with more knowledge about RG and Bundler answer this question: if we were to ship JRuby 9.3 (which is Ruby 2.6 compat) what RG and Bundler should be installed by default?

**Comment by deivid-rodriguez** [comment]
Hi @headius!

> JRuby master is already on RubyGems 3.0.6 which I believe should have the fixes. That version is still coupled with Bundler 1.17 but I have not locally had any issues activating a newer Bundler.

I think we fixed several bundler activation issues in rubygems 3.1.x that first showed up in ruby 2.6, since it's the first CRuby version that ships bundler as a default gem.

> With RG and Bundler "bundled" together now, I'm not clear how or if CRuby is upgrading them independently anymore. Maybe @deivid-rodriguez or @hsbt can help clear up how RG and Bundler versioning and stdlib versions of them work now.

We merged bundler & rubygems into a monorepo, but that should only affect _contributing_ to bundler & rubygems, not end users. Bundler and rubygems are still versioned and released independently.

> I would really love to see someone with more knowledge about RG and Bundler answer this question: if we were to ship JRuby 9.3 (which is Ruby 2.6 compat) what RG and Bundler should be installed by default?

This is up to you really, but I think the best end user experience would be to ship with the latest release of both.

**Comment by headius** [comment]
@deivid-rodriguez Thanks for clarification! I expect we will go ahead and ship the latest of each in JRuby 9.3.
