### ISSUE TITLE
Unable to install JRuby using rbenv and jenv

### ISSUE THREAD

**Issue by LoganBarnett** [jruby/jruby#6454]
**Environment Information**
  
Provide at least:
* Operating system and platform: `Darwin m-lbarnett2 18.7.0 Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64 x86_64`
* rbenv 1.1.2
* jenv 0.5.3
* openjdk version "1.8.0_242"

**Expected Behavior**

This command succeeds:
``` sh
rbenv install jruby-9.2.13.0
```

**Actual Behavior**

The install fails with the following spew:

``` 
$ rbenv install jruby-9.2.13.0
Downloading jruby-bin-9.2.13.0.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/73a8c241a162e644c87e864c3485c55adedeb82a6fd80fa3cb538fdacda7af58
Installing jruby-9.2.13.0...

BUILD FAILED (Mac OS X 10.14.6 using ruby-build 20201005)

Inspect or clean up the working tree at /var/folders/cm/z3ddv2v91yb7gyk6s_81vjz9klwdnq/T/ruby-build.20201029185223.58891.zDNNEj
Results logged to /var/folders/cm/z3ddv2v91yb7gyk6s_81vjz9klwdnq/T/ruby-build.20201029185223.58891.log

Last 10 log lines:

    current directory: /Users/logan.barnett/.rbenv/versions/jruby-9.2.13.0/lib/ruby/gems/shared/gems/jruby-launcher-1.1.13-java
/Users/logan.barnett/.rbenv/versions/jruby-9.2.13.0/bin/jruby -I /Users/logan.barnett/.rbenv/versions/jruby-9.2.13.0/lib/ruby/stdlib -r ./siteconf20201029-58999-cnamg8.rb extconf.rb
/Users/logan.barnett/.rbenv/versions/jruby-9.2.13.0/bin/jruby: line 446: /usr/local/opt/jenv/versions/system/bin/java: No such file or directory
/Users/logan.barnett/.rbenv/versions/jruby-9.2.13.0/bin/jruby: line 446: exec: /usr/local/opt/jenv/versions/system/bin/java: cannot execute: No such file or directory

extconf failed, exit code 126

Gem files will remain installed in /Users/logan.barnett/.rbenv/versions/jruby-9.2.13.0/lib/ruby/gems/shared/gems/jruby-launcher-1.1.13-java for inspection.
Results logged to /Users/logan.barnett/.rbenv/versions/jruby-9.2.13.0/lib/ruby/gems/shared/extensions/universal-java-14/2.5.0/jruby-launcher-1.1.13-java/gem_make.out
```

Thinking this might be related to #6434 I also attempted to set the `LC` and `LANG` environment variables, as well as export them just in case they might get lost in sub-shelling. None of these appears to have influenced the outcome.

Thanks for all the hard work! It's been a while since I've dipped into JRuby. Great to see it's still alive and well!

**Comment by headius** [comment]
Seems like it's not finding `java` when building the jruby-launcher executable? Can you look into your env and see if perhaps there's some problem locating the actual java binary?

You could also try unpacking the JRuby 9.2.13.0 tarball and using its bash-based bin/jruby to try to install the jruby-launcher gem. If this works then at least we'll know it's something specific to how rbenv sets up the extension build process.

**Comment by LoganBarnett** [comment]
@headius the Java exec is not in the path it shows (`/usr/local/opt/jenv/versions/system/bin/java`). I'm not entirely sure where it got that from. Perhaps an intelligent guess? This is where my `java` really (but not really - because shims) is:

``` sh
$ which java
/usr/local/opt/jenv/shims/java
```

Even if `system` were a good guess, it wouldn't always be a correct one. I'm not sure which actor requires it, but some part of this `rbenv` install process demands Java 1.8 - later version will not work (I can work on getting an error for that as well, if that seems useful).

Perhaps `jenv` changed where it locates the system JVM? Or maybe I never added it? Among the `*env` tools it seems to be the most manual one.

``` sh
$ ls /usr/local/opt/jenv/versions/
1.8                 1.8.0.242           11                  11.0                11.0.6              openjdk64-1.8.0.242 openjdk64-11.0.6
```

As an aside - it's great to see you and the crew are still driving JRuby forward! If you folks are in the PDX area (sans mask-era) I'd love to get a round.

**Comment by headius** [comment]
@LoganBarnett I can't comment on how those tools work but I can describe how we find the `java` command:

* use JAVACMD if set
* use JAVA_HOME/bin/java if JAVA_HOME is set
* use `java` from PATH

Based on this weird path to `java` you are seeing, perhaps JAVA_HOME is set to something unusual?

**Comment by headius** [comment]
@Unknown-Guy Is that a recent issue you had? Something specific to JRuby or a general problem?

I don't know if the original issue is still a problem...it's been a few years.

**Comment by headius** [comment]
Ok, we haven't had any recent reports of problems with JRuby 9.3 or higher, so I'm going to optimistically close this. Thanks for the info @Unknown-Guy.
