### ISSUE TITLE
Does the license announcement means I can choose one of  "EPL 2.0, GPL 2 and LGPL 2.1" as I like?

### ISSUE THREAD

**Issue by copbint** [jruby/jruby#6470]
Sorry for a silly question。I have googled a lot, but did not get the answer.

As in **README.md** use word **and**:
```
JRuby is licensed to you under three licenses - the EPL 2.0, GPL 2 and LGPL 2.1. 
```

while in **COPYING** use word **OR**:
```
JRuby is Copyright (c) 2007-2018 The JRuby project, and is released
under a tri EPL/GPL/LGPL license. You can use it, redistribute it
and/or modify it under the terms of the:

  Eclipse Public License version 2.0
    OR
  GNU General Public License version 2
    OR
  GNU Lesser General Public License version 2.1
```

Thanks!

**Comment by headius** [comment]
That is correct! JRuby can be considered to be licensed under any one of those licenses. We added EPL many years ago to allow a less restrictive license than GPL for commercial uses of JRuby.

I will look into clarifying this in the README, because it is indeed an OR and not an AND.

**Comment by copbint** [comment]
That's great, thanks!
