### ISSUE TITLE
Bundled did_you_mean gem v1.2.0 has a CC NonCommercial license in included file

### ISSUE THREAD

**Issue by colinsurprenant** [jruby/jruby#6471]
[Bundled gem did_you_mean v1.2.0](https://github.com/jruby/jruby/blob/47d0c634f6289bf469b9c7d691abe969d96f5390/lib/pom.rb#L49) has a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 license [on an included file](https://github.com/ruby/did_you_mean/blob/v1.2.0/evaluation/incorrect_words.yaml).

Per https://github.com/ruby/did_you_mean/issues/105 starting in v1.2.1 the whole `evaluation/` is now excluded from the gem which now ships without non-production code that has a non-commercial license.

I am leaving the trivial code-change to the team as I am unsure if a version more recent than v1.2.1 would be preferred here.

**Comment by headius** [comment]
I don't see any reason we can't upgrade this in 9.3, and possibly in 9.2.14 if the gem is still compatible with Ruby 2.5.

@enebo Any concerns about updating did_you_mean for 9.2.14?

**Comment by headius** [comment]
The latest is 1.4.0. We could either go to that and be current or just bump to 1.2.1 to get the CC stuff out of there. Bumping to 1.2.1 would clearly be the least impact.

**Comment by colinsurprenant** [comment]
Perfect, thanks @headius!

**Comment by headius** [comment]
Fixed by #6473.
