### ISSUE TITLE
BigDecimal Bug

### ISSUE THREAD

**Issue by mistergibson** [jruby/jruby#6476]
**Environment Information**
  
Provide at least:
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2020-11-16 73f455885e Java HotSpot(TM) 64-Bit Server VM 25.241-b07 on 1.8.0_241-b07 +jit [linux-x86_64]

Linux 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Other relevant info you may wish to add:

**Expected Behavior**

BigDecimal("0.04") --> 0.04

**Actual Behavior**
require 'bigdecimal'
BigDecimal
=> BigDecimal
BigDecimal.new("0.0")
(irb):7: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
=> 0.0
BigDecimal("0.9")
Traceback (most recent call last):
        6: from /usr/bin/irb:13:in `<main>'
        5: from org/jruby/RubyKernel.java:1268:in `catch'
        4: from org/jruby/RubyKernel.java:1268:in `catch'
        3: from org/jruby/RubyKernel.java:1538:in `loop'
        2: from org/jruby/RubyKernel.java:1122:in `eval'
        1: from (irb):8:in `evaluate'
NoMethodError (undefined method `BigDecimal' for main:Object)
Did you mean?  BigDecimal

**Comment by ahorek** [comment]
maybe you forgot to ```require 'bigdecimal'``` ?

BigDecimal("0.9")
=> 0.9e0

BigDecimal("0.04")
=> 0.4e-1

**Comment by headius** [comment]
Yeah I am unable to reproduce this with local JRuby master. Maybe try updating and rebuilding (or grab a newer snapshot)?

```
$ irb
irb(main):001:0> require 'bigdecimal'
=> true
irb(main):002:0> BigDecimal("0.9")
=> 0.9e0
irb(main):003:0>
```
