### ISSUE TITLE
JRuby 9.2.14.0 missing on Docker Hub

### ISSUE THREAD

**Issue by pavolzbell** [jruby/jruby#6502]
Hello @headius @kares can you please release 9.2.14.0 on Docker Hub? https://hub.docker.com/_/jruby

Also I think it would be nice to somehow automate this task, if you have an idea on where to start please let me know and maybe I can help with that in my spare time.

**Comment by headius** [comment]
I will spend the afternoon looking into this.

I have never published a Docker image to the hub, but we have had #5598 lingering for far too long. If you can assist maybe stop by our Matrix chat?

https://matrix.to/#/#jruby:matrix.org

**Comment by cpuguy83** [comment]
Sorry, it's mostly been other folks handling this for me recently.
PR to update dockerhub is here: https://github.com/docker-library/official-images/pull/9318

**Comment by headius** [comment]
@cpuguy83 Thank you, I am familiarizing myself with all the pieces now so I can take over the image.

**Comment by cpuguy83** [comment]
9.2.14 merged in official images, dockerhub should be updated soon.

**Comment by headius** [comment]
We will call this one resolved, thanks @cpuguy83!

**Comment by pavolzbell** [comment]
@headius @cpuguy83 Thank you guys for resolving this so quickly 🚀
