### ISSUE TITLE
javax.annotation-api has been deprecated, please move to jakarta-annotation-api

### ISSUE THREAD

**Issue by baldurmen** [jruby/jruby#6514]
Hi!

It seems jruby still depends on `javax.annotation-api 1.3.2`, which has been archived, deprecated and replaced by `jakarta-annotation-api`.

The new source code can be found here: https://github.com/eclipse-ee4j/common-annotations-api

I'm planning to see if I can build jruby using `jakarta-annotation-api 2.0.0` in the next few days, but meanwhile I'm opening this issue to track the need to move from the old javax lib :)

**Comment by headius** [comment]
@baldurmen Wow, we would love to have a PR to make this change! We only use the API at build time for our annotation processor, so it should be a pretty safe change to make. I am hoping, of course, that the Jakarta version of this API is basically a drop-in replacement.
