### ISSUE TITLE
Pathname#inspect behaviour is not consistent with other Ruby implementations

### ISSUE THREAD

**Issue by thbar** [jruby/jruby#6519]
I'm running JRuby 9.2.13.0 on Mac OS X (`Darwin Kernel Version 18.7.0`).

While debugging a JRuby-specific failure in `sshkit` (https://github.com/capistrano/sshkit/issues/488), I attempted to run the `sshkit` test suite, and noticed 3 failures caused by the way JRuby currently implements `Pathname#inspect`.

Only with JRuby, a heading hash (`#`) is missing.

```
$ RBENV_VERSION=2.3.8 ruby -e "require 'pathname'; puts Pathname.new('/tmp').inspect"
#<Pathname:/tmp>
$ RBENV_VERSION=3.0.0 ruby -e "require 'pathname'; puts Pathname.new('/tmp').inspect"
#<Pathname:/tmp>
$ RBENV_VERSION=truffleruby-20.2.0 ruby -e "require 'pathname'; puts Pathname.new('/tmp').inspect"
#<Pathname:/tmp>
$ RBENV_VERSION=jruby-9.2.13.0 ruby -e "require 'pathname'; puts Pathname.new('/tmp').inspect"
<Pathname:/tmp>       <---- missing # at beginning of line
```

While it may appear like a minor issue, or one that could cause breakage if we change it in JRuby right now, I believe it hinders JRuby use a bit, by causing small discrepancies in libraries test suites.

If possible, it would be great to align the behaviour on what MRI does.

**Comment by headius** [comment]
Should be an easy fix! Maybe you want to take a look at RubyPathname.java and attempt a PR?

**Comment by thbar** [comment]
Yes absolutely. Will do!

— Thibaut

**Comment by headius** [comment]
Thanks for the extra footwork on this!
