### ISSUE TITLE
Monitor synchronization issue in JRuby 9.2.14.0

### ISSUE THREAD

**Issue by dgolombek** [jruby/jruby#6526]
**Environment**

* JRuby version: jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9
* Operating system and platform: Linux 4.4.0-1118-aws #132-Ubuntu
* With Sinatra, AR 6.0.3, Redis 4.2.5, Concurrent Ruby 1.1.7

**Expected Behavior**

Service should run similarly to how it did in JRuby 9.2.6.0

**Actual Behavior**

Under high load, we are seeing threads appear to lock up. They are all within [Redis#synchronize](https://github.com/redis/redis-rb/blob/v4.2.5/lib/redis.rb#L69) blocks. In extensive conversation in [Matrix](https://matrix.to/#/!vyEDBdbmzqApWaugdd:matrix.org/$1610472205411631OWZSl:matrix.org?via=matrix.org), @headius  believes he traced this to a bug in CRuby's Monitor implementation. See the stack trace for full details: 
[jstack.log](https://github.com/jruby/jruby/files/5804677/jstack.log)

I initially thought that this was a reoccurrence of #6326 but it appears to be a separate issue.

**Comment by headius** [comment]
I have filed https://github.com/ruby/monitor/issues/2 to track what I believe is a bug in monitor.rb.

**Comment by dgolombek** [comment]
Thanks so much @headius !
