### ISSUE TITLE
Cruby/Jruby behavior difference with block keyword arguments

### ISSUE THREAD

**Issue by jhottenstein** [jruby/jruby#6540]
**Environment Information**
*  jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc Java HotSpot(TM) 64-Bit Server VM 25.271-b09 on 1.8.0_271-b09 +jit [darwin-x86_64]
* Darwin mac.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

Other relevant info you may wish to add:
* ruby2_keywords must be used - otherwise cruby returns the same error

**Expected Behavior**
I extracted the following behavior from a test failure when writing https://github.com/rspec/rspec-mocks/pull/1407
The below code works in every version of cruby tested by the rspec build(1.8.7-3.0.0) and jruby 1.7.  It failed for jruby 9.2.13.0 and 9.1.17.0
```
klass = Class.new do
  def a(*args, &block)
    block.call(*args)
  end

  ruby2_keywords(:a) if respond_to?(:ruby2_keywords, true)
end

klass.new.a(kw: :arg) { |kw:| kw }
=> :arg
klass.new.a(:positional, kw: :arg) { |kw:| kw }
=> :arg
```

**Actual Behavior**
```
klass.new.a(kw: :arg) { |kw:| kw }
=> :arg
klass.new.a(:positional, kw: :arg) { |kw:| kw }
Traceback (most recent call last):
        8: from /Users/jhottenstein/.rbenv/versions/jruby-9.2.13.0/bin/irb:13:in `<main>'
        7: from org/jruby/RubyKernel.java:1189:in `catch'
        6: from org/jruby/RubyKernel.java:1189:in `catch'
        5: from org/jruby/RubyKernel.java:1442:in `loop'
        4: from org/jruby/RubyKernel.java:1048:in `eval'
        3: from (irb):10:in `evaluate'
        2: from (irb):3:in `a'
        1: from (irb):3:in `block in evaluate'
ArgumentError (missing keyword: kw)
```

**Comment by headius** [comment]
Thank you for opening the issue!

**Comment by headius** [comment]
Looks like when we `call` a block with splatted arguments we are not handling keyword passing correctly. I would guess it is being passed as a normal argument containing a hash.

@enebo you might get to this before I do and you have worked on keyword arguments before...

**Comment by enebo** [comment]
@jhottenstein This will end up getting moved to .16 since 9.2.15.0 needs a release for a problem with Rails but I will triage it today so we know more.

I have already figured out that if you switch from .call to yield things work as expected.  Also if I switch .call to some other method it works as well.  So something in the implementation of call itself is losing the kwarg data.

**Comment by enebo** [comment]
Sitting on this until tomorrow morning to ponder it a bit more but the notion of what is happening is that we would truncate the kawrg argument off if the arityValue was calculated as 1 and there was not kwrest (**d).  This is obviously wrong.  Any kwargs present at all should not allow this truncation.

The thing to think about is how could this change break something.  At this point it would only seem to unbreak kwargs case so I see no downside...
