### ISSUE TITLE
Incorrect implementation of org.jruby.embed.variable.VariableInterceptor#terminateLocalVariables

### ISSUE THREAD

**Issue by rimvydasv** [jruby/jruby#6550]
Lets say that all variables in the list are local.
The method removes every second variable from the list. It should remove all variables.

**Comment by headius** [comment]
Got an example we can turn into a test?

**Comment by rimvydasv** [comment]
[jruby-test.zip](https://github.com/jruby/jruby/files/5931536/jruby-test.zip)

**Comment by rimvydasv** [comment]
Extract the zip. Execute: mvn test.

**Comment by headius** [comment]
@rimvydasv Thank you!

**Comment by headius** [comment]
Confirmed on master. I am curious, what are you using this for?

**Comment by headius** [comment]
Duh... it is deleting while it iterates, so it skips every other. Easy fix incoming.
