### ISSUE TITLE
JRuby should provide the line number of errors when executing in the JSR223 Context

### ISSUE THREAD

**Issue by boc-tothefuture** [jruby/jruby#6560]
**Environment Information**
  
Provide at least:
* JRuby version:  9.2.14.0
* Operating system and platform:  Mac

**Expected Behavior**

When operating in a JSR223 environment if there is an evaluation error the line number should be provided in the error message.  This information currently exists in the stack trace.  However, It is common for systems using JSR223 to not print the full stack trace on evaluation error and just to print the exception message itself.  

This is consistent with the behavior of JavaScript, Groovy and Jython.  However, JRuby does not do this.

Here is an exception from Jython:
```
 Error during evaluation of script 'file:/openhab/conf/automation/jsr223/python/personal/test.py': NameError: name 'asdf' is not defined in <script> at line number 32
```

**Actual Behavior**

This is the same type of error, from JRuby:
```
Error during evaluation of script 'file:/openhab/conf/automation/jsr223/ruby/personal/test.rb': org.jruby.embed.EvalFailedException: (NameError) undefined local variable or method `asfd' for main:Object
```

It would be beneficial for JRuby to operate in a similarly as other JSR223 implementations.

**Comment by headius** [comment]
It would not be too big a change to modify the embedding wrapper exceptions to include the nearest Ruby script line. My main worry is getting the wrong line, like if the Ruby code calls into Java we would not want to show the Ruby line.

For background here, Jython is simply formatting their error messages to include the file and line, while JRuby tries in most cases to match the format of CRuby's errors which do not include this information. Instead, JRuby provides a Ruby stack trace that will show all the lines leading up to the exception point, something Jython can't currently do.

We will clearly not be modifying all errors to include the file and line, but we could include some helpful information in these wrapper exceptions. The question is what.

Thoughts on this @kares @enebo @yokolet?

**Comment by headius** [comment]
@boc-tothefuture Can you try to confirm what message Jython uses when the error occurs a few levels deeper in the stack? I am wondering if maybe they are just using the topmost script, or if they are actually using the script where the exception occurred. I can't tell from your examples, since I suspect they are single-level scripts.

**Comment by kares** [comment]
> We will clearly not be modifying all errors to include the file and line, but we could include some helpful information in these wrapper exceptions. The question is what.

Heh, I actually tried to get rid of the `org.jruby.embed.EvalFailedException` wrapper :stuck_out_tongue: for JSR223 (https://github.com/jruby/jruby/pull/6457).
Even if it's to stay I am not sure how that would work other than filtering the caught Ruby exception's trace and extracting the top entry for file/line information.

Anyhow, I personally do not see an issue here - Ruby exceptions do not propagate file/line information as it's something to be found from the backtrace (same for Java - there's no way to tell where an exception originated unless looking at trace).

**Comment by headius** [comment]
@kares Yeah I would not say we are doing anything wrong, but for purposes of the JSR223 scripting API, we are conspicuously leaving out information most other languages provide in the message. If we can add that information in a reliable way without modifying the original exception message, we have a path forward.

Another option would be including all lines up to the nearest .rb file, which would avoid us possibly omitting any Java trace elements needed for debugging.

**Comment by jimtng** [comment]
Here is an example of an error inside a function in Jython:

```python
def test():
    asdf

test()
```

```
14:57:29.890 [ERROR] [ript.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/openhab/conf/automation/jsr223/python/personal/test.py': NameError: global name 'asdf' is not defined in <script> at line number 56
```

**Comment by headius** [comment]
> The error only shows test.py and not badlib.py

Ok that is what I suspected. So they are basically just using the frame at which the exception finally bubbles out of the scripting engine back into normal Java code.

I question the utility of this, but since it would not be *too* difficult to support I don't see a good reason not to do it.

**Comment by headius** [comment]
Ok after actually looking into this, most of the work is done by the default ScriptException from JSR223, if you provide it with a script and line number. In this case, we have the following wrapping:

* The actual Ruby exception that gets raised
* An EvalFailedException that wraps it using its message and setting it as the cause
* A ScriptException that just has EvalFailedException as its cause

If we were to provide a file and line to ScriptException, we would get this message for free.

@kares Where do we stand on your PR to simplify the exceptions from the embedding APIs? This would be a pretty small change to add... we just need to get that top Ruby frame and provide its file and line to the ScriptException.

**Comment by kares** [comment]
@headius that work should be complete at https://github.com/jruby/jruby/pull/6457
`EvalFailedException` is no longer used with javax.script (`ScriptException` [contains the underlying cause](https://github.com/jruby/jruby/pull/6457/files#diff-f9244da081dcd888fca3e2f4510c22382fbfe3172dcc69108a619cbf51874d36R83-R109))
... for direct `org/jruby/embed/ScriptingContainer` instantiation the `EvalFailuedException` is still used (nothing changes).

**Comment by headius** [comment]
Hey could one of you provide a test case of the JSR223 engine that exercises the paths you expect to have filename? I am looking over the Jython implementation and their handling of the exception is rather exotic. I would like to know exactly the call paths that should be reporting a file and line number so I can add similar (albeit less exotic) logic to include the top Ruby frame in the message.

https://github.com/jython/jython/blob/master/src/org/python/jsr223/PyScriptEngine.java#L194-L234

Thanks in advance. ❤️

**Comment by headius** [comment]
I have pushed a preliminary PR against master that adds this in a simple way, but our tests do not seem to supply a filename in the appropriate JSR-223 way. Looking forward to seeing someone with more familiarity with 223 write up some simple tests for this behavior!

```
[INFO] Running org.jruby.embed.jsr223.JRubyEngineTest
javax.script.ScriptException: Error during evaluation of Ruby at <script> at 2: (RuntimeError) hello from ruby
```

**Comment by boc-tothefuture** [comment]
@headius  - 
  Are you looking for test coverage beyond the filename?

To get the filename to show up you should be able to do this:
```
  container.getScriptEngine().put(ScriptEngine.FILENAME, fileName);
```

**Comment by headius** [comment]
@boc-tothefuture That helps, thanks! Mostly what I want is just a short set of JSR-223 snippits that drive it the way you want to drive it, expecting error messages formatted with file and line number.

The one I have may be sufficient with the filename change. I will add it to the pull request, but if you can write some additional cases that test other forms of script-running in 223 I would appreciate that. See the PR.

**Comment by headius** [comment]
I have pushed a working test to the PR. It only tests the invokeMethod path currently.

It also ooccurred to me that this will not improve the output of Java exceptions that happen to occur underneath a 223 script call. That is not something we can easily do, since the exceptions stack trace will not reflect JRuby's interpreted frames (to the JVM they just look like a series of interpreter calls).

But Ruby exceptions raised from the engine should at least show the top-level script name and line number, for what that is worth. 🤷‍♂️
