### ISSUE TITLE
Create a pre-release mailing list

### ISSUE THREAD

**Issue by kalenp** [jruby/jruby#6583]
It would be nice to be able to subscribe to a mailing list to get pre-release notifications.  That way large JRuby users could test the new version prior to it being cut and help identify any regressions.

**Comment by kares** [comment]
are the snapshots provided by JRuby insufficient for your use-case? 
folks usually use those in a CI (e.g. using `rvm: jruby-head`). sometimes a failure is intermittent but if it's there long enough it's usually worth investigating (reporting - tricky part being trying to come up with a reproducer).

just asking to understand how writing a mail e.g. a week before a release would be more useful compared to snapshots.

**Comment by headius** [comment]
It occurred to me... we have a mailing list that is underutilized. I think we should just try to start pushing prerelease announcements out there when we start talking about closing in on a release.

https://lists.ruby-lang.org/cgi-bin/mailman/listinfo/jruby

We don't need another list to maintain. We do have an internal list of people we email when the release comes out, but that is more of a "please update your distributions and packages etc" notification (and we also post release announcements to the mailing list and social media already).
