### ISSUE TITLE
[stdlib] resolve Set#initialize compatibility

### ISSUE THREAD

**Issue by kares** [jruby/jruby#6616]
there are some new failures since latest ruby:spec [update](https://github.com/jruby/jruby/pull/6584/files#diff-9cf108c066ad4af652611922ffbc5c5d7231f67095c4c0823a235e0f3782c757R1-R2):
```
fails:Set#initialize uses #each_entry on the provided Enumerable
fails:Set#initialize uses #each on the provided Enumerable if it does not respond to #each_entry
```

**Comment by headius** [comment]
9.3?
