### ISSUE TITLE
GPL-3.0 in the COPYING file

### ISSUE THREAD

**Issue by hyandell** [jruby/jruby#6627]
Digging into the COPYING file and comparing to the codebase, I'm wondering where the GPL-3.0 applies.

This was introduced [11 years ago](https://github.com/jruby/jruby/commit/b54bc96da9463322bb07b636c626650e48267bcf):

The following licenses cover code other than JRuby which is included with JRuby.

    Licenses listed below include:

    * GNU General Public License version 3
    * Apache 2.0 License
    * BSD License
    * MIT License
    
But it doesn't refer to what the code under that licensing is. 

Does anyone have any idea what it refers to?

**Comment by headius** [comment]
Ah this is probably old information. For a very short time the Java Native Runtime ([JNR](https://github.com/jnr)) project was relicensed GPL3, but we convinced the maintainer to instead move to Apache. I will investigate to be sure.

**Comment by hyandell** [comment]
Thank you :)
