### ISSUE TITLE
Fix issue with JAVA_HOME not being set

### ISSUE THREAD

**Issue by rogerhu** [jruby/jruby#6637]
See https://github.com/jruby/jruby-launcher/issues/34
**Environment Information**
  
Provide at least:
* JDK 8
* Java located in /usr/bin/java
* CentOS with /usr/lib/modules in existence

**Expected Behavior**

No --module-path being used.

**Actual Behavior**

--module-path being used

* Describe or show the actual behavior.
* Provide text or screen capture showing the behavior.

Line in question: https://github.com/headius/jruby/blob/ebf92b39391f04f06ebd6e3c54878f5a4bba4632/bin/jruby.bash#L139

Comments from jRuby launcher: https://github.com/jruby/jruby-launcher/commit/88e3c9613b63f1d4ac1db2a1730f2887422f7b17#r48827667

**Comment by headius** [comment]
This is yet to be fixed in the native launcher, so jruby/jruby-launcher#34 is still open.
