### ISSUE TITLE
Failure to RVM-install JRuby 9.2.{13,17},0 on Ubuntu 20 with JDK 8

### ISSUE THREAD

**Issue by thbar** [jruby/jruby#6689]
This is a follow-up of this [twitter thread](https://twitter.com/headius/status/1397728093108850689) and this [RVM issue](https://github.com/rvm/rvm/issues/5084).

I have managed to create a small reproduction with full logs here, using Vagrant:

https://github.com/thbar/jruby-rvm-ubuntu-focal-repro

I think JRuby 9.2.17.0 had a [fix for this](https://github.com/jruby/jruby/commit/ebf92b39391f04f06ebd6e3c54878f5a4bba4632), but something is still not working.

Happy to help out further!

**Comment by thbar** [comment]
A quick search in the logs shows:

```
Successfully installed jruby-launcher-1.1.15-java
```

So apparently the latest launcher available is installed.

**Comment by thbar** [comment]
@headius not sure how I can help further here ; I'm allowed to use a couple of client hours to dive further into it if you have a bit of guidance, so hit me up if you have any hint!

**Comment by headius** [comment]
Nice repro! I will give it a try.

**Comment by headius** [comment]
I believe I have located the missing logic in the native launcher: https://twitter.com/SilverBullets33/status/1400515009004847107

This piece of code ensures that a symlinked 'java' command gets resolved back to a real binary, which should be the one that lives in a real JAVA_HOME. This logic has never made it over to the native launcher.

I will file an issue at https://github.com/jruby/jruby-launcher to get this ported and released. We will incorporate the updated Windows .exe in 9.2.18.0.

The simplest workaround for you would be to set JAVA_HOME to a real JDK install (which will cause us to bypass the bad detection logic). In Debian-based systems like Ubuntu, that would be somewhere under /usr/lib/jvm.

**Comment by thbar** [comment]
Thanks! To make sure I understand the possibilities: I either use the work-around for immediate fix, or wait for JRuby 9.2.18.0 to be out, is that correct?

(thanks for both options, much appreciated!)

**Comment by headius** [comment]
@thbar Once I have fixed and released a new jruby-launcher, rvm *may* just work. I don't think it tries to install a specific version.

If for some reason it doesn't pick up the new jruby-launcher, then the workaround would be necessary.

**Comment by headius** [comment]
...and the fixed Windows executable will be bundled with JRuby 9.2.18.0, but that doesn't affect you (and this bug does not affect Windows).

**Comment by headius** [comment]
I have pushed jruby-launcher 1.1.16 and confirmed that rvm was able to (re)install JRuby 9.2.17.0 using your Vagrant example. Please confirm!

**Comment by thbar** [comment]
@headius thanks for the quick turn-around! 

> I don't think it tries to install a specific version.

Indeed it installs the latest available version.

> I have pushed jruby-launcher 1.1.16 and confirmed that rvm was able to (re)install JRuby 9.2.17.0 using your Vagrant example. Please confirm!

I am now able to use JDK 8 and can confirm everything works as expected.

Many thanks for your excellent work!
