### ISSUE TITLE
Autoload regression

### ISSUE THREAD

**Issue by ahorek** [jruby/jruby#6708]
**Environment Information**
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2021-06-06 02b783dc8c Java HotSpot(TM) 64-Bit Server VM 15.0.2+7-27 on 15.0.2+7-27 +jit [linux-x86_64]
works on 9.2 / cruby

**Expected Behavior**
repro
```
# Thread.report_on_exception = true

autoload(:FileUtils, 'fileutils.rb')

threads = []
50.times do
  threads << Thread.new do
    begin
      FileUtils
    rescue
      false
    else
      true
    end
  end
end
threads.each(&:join)
puts "Success: #{threads.select{|x| x.value}.count}"
puts "Failed: #{threads.select{|x| !x.value}.count}"
```

it should pass and load fileutils outside of the main thread

**Actual Behavior**
it fails on an uninitialized constant each time

refs: https://github.com/jruby/jruby/pull/5764

**Comment by headius** [comment]
This seems to only affect the toplevel autoload. Putting a similar autoload within a module succeeds every time. Investigating.

**Comment by headius** [comment]
I believe this is failing because it use the toplevel anonymous module as the target of the autoload, but it should be using Object, the nearest non-singleton non-include module.

**Comment by headius** [comment]
I believe I have the right combination of fixes in #6749:

* Only use the scope's module as the target for Kernel{#.}autoload
* Dig out the real module if that target is a singleton or include/prepend wrapper

**Comment by headius** [comment]
This is working now on the PR branch but that broke an old regression spec for a peculiar behavior of Kernel#autoload. I am investigating that now.

**Comment by headius** [comment]
After much analysis we have determined that the regression spec in question was never actually fixed, and the failure now just exposes that fact. I will move that spec to a rubyspec and we can discuss the peculiar behavior there (which will likely lead to it being deprecated).

**Comment by headius** [comment]
@ahorek Could you try to add a ruby/spec for this behavior? I will merge #6708 and filed https://github.com/ruby/spec/pull/839 for a peculiar (and questionable) behavior I broke.

**Comment by ahorek** [comment]
interesting. The original example passes in ```--dev``` mode without your fix and we do run ```spec:ruby:fast``` on Travis only in --dev mode. What would you recommend?

jit mode exposed new failures and some of them might be relevant, see https://github.com/jruby/jruby/pull/6753

**Comment by headius** [comment]
Hmmm that is interesting. There may be something different about how the interpreter and jit set up the module nesting or top level that causes the example to work in interpreter. We should look into those jit failures.
