### ISSUE TITLE
jruby-head no longer includes Bundler

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6713]
Is that intentional?

See https://github.com/ruby/setup-ruby/issues/186

**Comment by headius** [comment]
I just tested a master build and bundler is getting installed just fine. Could be an issue with the tarball packaging.

**Comment by eregon** [comment]
You can see which archive got downloaded in https://github.com/ruby/jruby-dev-builder/runs/2787013268?check_suite_focus=true
https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-dist/9.2.19.0-SNAPSHOT/jruby-dist-9.2.19.0-20210608.163348-1-bin.tar.gz does not have `bin/bundle`.

**Comment by eregon** [comment]
Ah maybe the issue is the script https://github.com/ruby/jruby-dev-builder/blob/master/find-jruby-head-url.rb found `9.2.19.0-SNAPSHOT` but it should be `9.3.0.0-SNAPSHOT/`?

**Comment by headius** [comment]
JRuby 9.2 does not include bundler because Ruby 2.5 did not include bundler. Did this script switch to fetching 9.2 instead of 9.3 recently?

**Comment by eregon** [comment]
Yeah, it sounds like it. It relies on the order of the versions, which was in that run:
```
     <versions>
      <version>9.2.18.0-SNAPSHOT</version>
      <version>9.3.0.0-SNAPSHOT</version>
      <version>9000.dev-SNAPSHOT</version>
      <version>9.2.19.0-SNAPSHOT</version>
    </versions>
```

and is now
```
    <versions>
      <version>9.2.18.0-SNAPSHOT</version>
      <version>9.2.19.0-SNAPSHOT</version>
      <version>9.3.0.0-SNAPSHOT</version>
      <version>9000.dev-SNAPSHOT</version>
    </versions>
```

Maybe we can use Gem::Version or so to sort them.

**Comment by headius** [comment]
Ok, closing this as it does not appear to be our issue.

**Comment by eregon** [comment]
The full contents of https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-dist/maven-metadata.xml is:
```
<?xml version="1.0" encoding="UTF-8"?>
<metadata modelVersion="1.1.0">
  <groupId>org.jruby</groupId>
  <artifactId>jruby-dist</artifactId>
  <versioning>
    <latest>9000.dev-SNAPSHOT</latest>
    <release></release>
    <versions>
      <version>9.2.18.0-SNAPSHOT</version>
      <version>9.2.19.0-SNAPSHOT</version>
      <version>9.3.0.0-SNAPSHOT</version>
      <version>9000.dev-SNAPSHOT</version>
    </versions>
    <lastUpdated>20210610034625</lastUpdated>
  </versioning>
</metadata>
```

So `latest` isn't reliable either.
What's 9000.dev-SNAPSHOT?
It seems old, maybe it could be removed? Otherwise I have to hardcode to ignore it.

**Comment by headius** [comment]
> What's 9000.dev-SNAPSHOT?

This was used before we released 9.0 and should not be in use anymore. I am not sure why the root metadata shows that this is the latest.

> It seems old, maybe it could be removed?

I will try to remove the old snapshots and hopefully they don't sneak back in there.

**Comment by headius** [comment]
FWIW I see that within the 9000.dev dir all the files are from 2014, so it is a mystery why the parent metadata thinks that is latest. Perhaps just because it has the highest version number?

**Comment by eregon** [comment]
> Perhaps just because it has the highest version number?

Ah, that makes some sense, I didn't think of it.

I (hopefully) fixed the script by using Gem::Version, should be good now.

**Comment by headius** [comment]
After deleting the 9000 snapshot dir, latest appears to point at 9.3. This metadata must be maintained automatically by the Sonatype server.

**Comment by eregon** [comment]
Thanks, that makes it quite a bit clearer.

**Comment by headius** [comment]
These old versions are supposed to age out and get cleaned up, but for some reason those 9000 dirs have stuck around. Could be the same explanation: it does not clean out latest version. In any case I have scrubbed the snapshot repo of all 9000 versions.

**Comment by headius** [comment]
Retargeting as non-release since there were a few cleanup items on our end.
