### ISSUE TITLE
Problems loading extensions in JRuby-9.3.0

### ISSUE THREAD

**Issue by monkstone** [jruby/jruby#6724]
This applies to https://github.com/jruby/jruby-examples as well as JRubyArt
```bash
NoMethodError: undefined method `runtime' for JRuby:Module
            <main> at /home/tux/jruby-examples/extensions/basic/lib/basic.rb:9
           require at org/jruby/RubyKernel.java:1014
  require_relative at org/jruby/RubyKernel.java:1042
```
How are we supposed to getRuntime for 
```ruby
# encoding: utf-8
# frozen_string_literal: true
require 'jruby' # we must use jruby runtime

# load the jar from the local directory
require_relative 'jruby-ext.jar' 
# load our ruby Bar class and Foo module into ruby runtime
# using java as follows
com.purbon.BasicService.new.basicLoad(JRuby.runtime)

# You may wish to use the camel-case form because it stands out
# that you are using 'java' to load your classes / modules
# Java::ComPurbon::BasicService.new.basicLoad(JRuby.runtime)
#
```

**Comment by headius** [comment]
`require 'jruby'` should be sufficient to get `JRuby.runtime`. That is not working?

**Comment by monkstone** [comment]
Yeah that's right it doesn't seem to be working.

**Comment by ahorek** [comment]
I can't replicate it, does it work in irb?
```
irb(main):001:0> require 'jruby'
=> true
irb(main):002:0> JRuby.runtime
=> #<Java::OrgJruby::Ruby:0x4e1d422d>
irb(main):003:0>
```

**Comment by monkstone** [comment]
Tried this on Archlinux (where jruby-2.19.0.0) is installed by distro.
When I fire up jirb as folows
```bash
/opt/jruby-head/bin/jirb
```
I tried as you suggested
```bash
irb(main):001:0> require 'jruby'
=> false
```
Checking jruby version
```
/opt/jruby-head/bin/jruby -v
```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/tux/tmp
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2021-06-09 ab15c01ff0 OpenJDK 64-Bit Server VM 15.0.3+3 on 15.0.3+3 +jit [linux-x86_64]
```

**Comment by monkstone** [comment]
I'm closing this assuming it is a non issue. Perhaps there should be a new issue regarding direct use of jirb where I was unable to require 'jruby'? compared with jruby -S irb where there was no issue.

**Comment by headius** [comment]
@monkstone Could be a loading issue... file another issue with a clear example and I will look into it.
