### ISSUE TITLE
JarCache checking for File.lastModified heavily slowing down startup

### ISSUE THREAD

**Issue by DirkMahler** [jruby/jruby#6730]
**Environment Information**
  
Provide at least:
* JRuby version: 9.2.17.0 (including latest 9.2.20.0-SNAPSHOT)
* Operating system: Windows 10

**Expected Behavior**

jQAssistant is using AsciidoctorJ for parsing and rendering Asciidoc files. As jQA is embedded into the build process of applications (for validating architecture & design rules) short startup times are crucial.

**Actual Behavior**

On Windows systems (especially in enterprise environments...) startup behavior is terribly slow. Looking at the VisualVM sampler it can be seen that JarCache.isValid() makes heavy use of File.lastModified which is very slow on this platform:

![image](https://user-images.githubusercontent.com/437925/123922493-60ef3080-d988-11eb-974d-6bd17327af30.png)

The times can go up to minutes, even on quite modern hardware (don't know what Windows, virus scanners, etc. are doing in the background). This problem has already been reported in #5857 but is not yet solved.

**Possible Solution**

I experimented on the 9.2 branch on caching the lastModification time for 500ms per cached JAR file for the isValid checks which gave a good improvement and made File.lastModified disappear from the sampler. 

The sample then shows the next bottleneck which is caused by using WeakHashMap for caching - which effectively does not cache anything. Replacing it by a HashMap made it finally acceptable but I assume that this should either be a limited LRU map or using soft references to avoid memory leaks.

![image](https://user-images.githubusercontent.com/437925/123926012-c2fd6500-d98b-11eb-9f84-8794ebdd01bc.png)

If interested I can provide a PR for caching the lastModification time but I don't know the possible impact.

**Comment by headius** [comment]
@DirkMahler This is a great discovery! I would not be surprised if this were also impacting other uses of JRuby.

I would **love** to see a PR with your changes. You are correct that the weak map should probably be soft.

**Comment by DirkMahler** [comment]
Ok, I'll prepare a PR then. Questions:

1. Which should be the base/target branch? I did my experiments on 9.2, should it go there and then up to master (i.e. 9.3)? For the latter I already saw that the WeakHashMap had been replaced by a SoftReference based solution.
2. The PR would change the behavior of JarCache to detect changes to a JAR file after a caching period of 500ms. Is this acceptable?
3. Is there anything specific to be considered for testing? There's a JarResourceTest that implicitly covers the JarCache. Would you prefer to have a dedicated test for the latter covering the behavior of the caching period?

**Comment by headius** [comment]
1. If the changes are not too drastic (doesn't sound like they are) then 9.2 is a good target. We will release 9.3 soon but still have to maintain 9.2 for a while (6-12mo probably). I will backport the soft reference change from master so you don't have to worry about that (and so merges are easier).
2. That seems fine to me. @enebo and @kares?
3. Use your best judgment. If the tests you want to add seem substantially different from the ones in JarResourceTest, a new test may be better.

**Comment by headius** [comment]
Assuming there's nothing wrong with the backported commit in #6734 I will merge that and you can base your PR off jruby-9.2 with the soft cache fix.

**Comment by DirkMahler** [comment]
@headius Just looked at `jruby-9.2` but cannot find the backport. Looks to me it has been merged to `master`. Can you check this (or am I missing something)? Nevertheless going create the PR today.

**Comment by headius** [comment]
Ugh you are correct... I forgot to change the target branch. It should be there now!

**Comment by DirkMahler** [comment]
Your changes are there, the PR (#6740) ready for review.

**Comment by headius** [comment]
All set! Thank you!

**Comment by DirkMahler** [comment]
Thank you: just cross-checked in an affected customer (enterprise) environment, looks much better now!

**Comment by ahorek** [comment]
Odesláno z mého chytrého telefonu Samsung Galaxy.
-------- Původní zpráva --------Od: Charles Oliver Nutter ***@***.***> Datum: 05.07.21  2:03  (GMT+01:00) Komu: jruby/jruby ***@***.***> Cc: Pavel Rosický ***@***.***>, Manual ***@***.***> Předmět: Re: [jruby/jruby] JarCache checking for File.lastModified heavily slowing down startup (#6730) 
Closed #6730.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/jruby/jruby/issues/6730#event-4975643814",
"url": "https://github.com/jruby/jruby/issues/6730#event-4975643814",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
