### ISSUE TITLE
FFI issue loading libidn2 in macos 

### ISSUE THREAD

**Issue by HoneyryderChuck** [jruby/jruby#6732]
Hi,

Coming from [the ffi issue](https://github.com/ffi/ffi/issues/901), where maintainers suggested me to share with the Jruby community. Loading the `libidn2` lib on MacOS isn't working. It's working well in CRuby, whereas in JRuby, the library isn't found. I'm assuming there's not a complete overlap in the system lib paths.

Link to the failing CI build [here](https://github.com/HoneyryderChuck/idnx/runs/2849724922?check_suite_focus=true).

**Environment Information**
  
Provide at least:
* JRuby version: 9.2.18.0
* Operating system and platform: MacOS 10.15.7

**Comment by headius** [comment]
Seems like some search logic for the library must be different? Can you give it a try on JRuby master (9.3)? We are closer to the FFI gem there (reusing all the .rb code as-is and passing all the same tests).

**Comment by HoneyryderChuck** [comment]
I can confirm that the [suite passes against jruby-head](https://github.com/HoneyryderChuck/idnx/runs/2985525037?check_suite_focus=true). I'll close this then. Thank you for the tip!

**Comment by headius** [comment]
I think it would be worth us backporting ffi for maintenance releases of 9.2. There weren't many changes and it would align is with master.

**Comment by headius** [comment]
The backport of logic from master to use the FFI gem is complete in #6747.
