### ISSUE TITLE
GPL-2.0 with Classpath Exception in the COPYING file

### ISSUE THREAD

**Issue by hyandell** [jruby/jruby#6737]
Looking at the current COPYING file, I notice there's a GPL-2.0 with Oracle Classpath Exception in there. Unlike other parts of the COPYING file it's not clear what it relates to. 

See: https://github.com/jruby/jruby/blob/master/COPYING#L1410
It's not mentioned in the header at: https://github.com/jruby/jruby/blob/master/COPYING#L1151

It was introduced in this commit 5 years ago: https://github.com/jruby/jruby/commit/92dc6cd288ce76a800ba86c40b71cd6b20caf0de and seems to relate to a Truffle component, which is no longer mentioned in the COPYING file.

Is this license inclusion out of date now?

**Comment by headius** [comment]
You are correct, those components are no longer part of JRuby. All references to Truffle or TruffleRuby can be removed from these files.

**Comment by headius** [comment]
Thank you!
