### ISSUE TITLE
private/private_method_defined? raising error when a module is prepended

### ISSUE THREAD

**Issue by JacobEvelyn** [jruby/jruby#6758]
**Environment Information**
  
* JRuby version (`jruby -v`): 9.2.19.0
* Operating system: Ubuntu 20.04.2, macOS 11.4

**Expected Behavior**

The following code executes without error in Ruby 2.5.8 (and 3.0.2):

```ruby
module Prepended
  def self.prepended(*) ; end
end

module TestModule
  prepend Prepended

  private_method_defined?(:foo)
  def foo ; end
  private :foo
end
```

**Actual Behavior**

In JRuby 9.2.19.0, we get:

```ruby
NameError: undefined method `foo' for module `TestModule'
              private at org/jruby/RubyModule.java:3139
```

Let me know if there's a better way to report this bug.

**Comment by PikachuEXE** [comment]
Same result with 
`jruby 9.3.0.0-SNAPSHOT (2.6.5) 2021-07-20 00ddf5da27 OpenJDK 64-Bit Server VM 11.0.11+9 on 11.0.11+9 +jit [darwin-x86_64]`

**Comment by edipofederle** [comment]
Maybe related with: https://github.com/jruby/jruby/issues/6445

I already starting get into this one (#6445) but still don't figure out how to fix it....
