### ISSUE TITLE
1r should equal to 1.0r

### ISSUE THREAD

**Issue by mrkn** [jruby/jruby#6764]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
```
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2021-07-23 68f7711598 OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04 on 11.0.11+9-Ubuntu-0ubuntu2.20.04 +jit [linux-x86_64]
```

* Operating system and platform (e.g. `uname -a`)
```
Linux mrkn-ubuntu2004 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Other relevant info you may wish to add:
* Installed or activated gems
No

* Application/framework version (e.g. Rails, Sinatra)
No

* Environment variables
No

**Expected Behavior**
`1r == 1.0r`

**Actual Behavior**
`1r != 1.0r`

```
$ RBENV_VERSION=jruby-dev ruby -ve "p 1r == 1.0r"
jruby 9.3.0.0-SNAPSHOT (2.6.5) 2021-07-23 68f7711598 OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04 on 11.0.11+9-Ubuntu-0ubuntu2.20.04 +jit [linux-x86_64]
false

$ ruby -ve "p 1r == 1.0r"
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
true
```

**Comment by edipofederle** [comment]
After a debug session on it, looks like some issue on how this is parsed, at least I can see `1.0r` in the AST node as `10`:

<img width="1015" alt="Screen Shot 2021-08-02 at 20 16 54" src="https://user-images.githubusercontent.com/50778/127936805-b5ee836c-2c5a-48a7-8fad-5445c7a3dd71.png">

@headius or @enebo  this makes sense ? Thx

**Comment by headius** [comment]
@edipofederle Wow, that is really weird.

```
$ jruby -e 'p 1.0r'
(10/10)
```

Definitely needs to be fixed on both branches.

**Comment by edipofederle** [comment]
> @edipofederle Wow, that is really weird.
> 
> ```
> $ jruby -e 'p 1.0r'
> (10/10)
> ```
> 
> Definitely needs to be fixed on both branches.

Yep, I would like to try this one, do you have some advise on how approach this?

**Comment by enebo** [comment]
@edipofederle It is RubyLexer#getFloatToken.  We make a BigDecimal and create the RationalNode right there.  Something wrong with how we use Java BigDecimal?

**Comment by edipofederle** [comment]
> @edipofederle It is RubyLexer#getFloatToken. We make a BigDecimal and create the RationalNode right there. Something wrong with how we use Java BigDecimal?

ok, so I am on the right place, I will take a look today and see if I can fix it.

**Comment by headius** [comment]
@enebo well the fact that we proceed to stuff it into either a Fixnum or a Bignum probably has something to do with it. 😀

**Comment by headius** [comment]
Just to confirm:

```
$ ruby26 -e 'p 1.0r'
(1/1)
```

**Comment by enebo** [comment]
@headius we extract the numerator and denominator from the bigdecimal.  I suppose however we do this math in RubyRational with big decimal we should do the same thing.

**Comment by enebo** [comment]
If this is canonicalization I am really surprised these still do not equate to being the same rational value 1/1 and 10/10 are the same thing aren't they?  Not saying we should not canonicalize but I am confused they are not equal?

**Comment by eregon** [comment]
I think Rational instances are always canonicalized, hence equality might just assume that.

**Comment by enebo** [comment]
@eregon yeah that appears to be the case.
