### ISSUE TITLE
Calling String#dup on strings used as a buffer in IO.copy_stream alters the body of all strings duped from the original

### ISSUE THREAD

**Issue by HoneyryderChuck** [jruby/jruby#6767]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc): 9.2.15
* Operating system and platform (e.g. `uname -a`): alpine (via docker)

**Expected Behavior**

First of all, I apologize for not bringing a contained example. I tried, but couldn't quite reproduce what I reliably get in `httpx` test suite.

The error surfaced when upgrading `httpx` jruby docker image for the CI suite from `9.2.14` to the latest. I've since tried all versions between, and can say that the regression happened between `9.2.14` and `9.2.15`. 

Relevant test suites (from the jruby reproduction branch):

* https://gitlab.com/honeyryderchuck/httpx/-/jobs/1474851865 (9.2.14)
* https://gitlab.com/honeyryderchuck/httpx/-/jobs/1474871005 (92.15, failed)

The debug output observed in the CI logs comes from [this change](https://gitlab.com/honeyryderchuck/httpx/-/blob/fix-jruby/lib/httpx/connection/http2.rb#L242-L244). If you check the build that passes, you'll find the following pattern:

```
(2054 loop: "--------") 
after: (2054) "--------", (2056) "\x8F\xA9\xF7\xB1\xED\x87\x89M"
(2056 loop: "\x8F\xA9\xF7\xB1\xED\x87\x89M") 
after: (2056) "\x8F\xA9\xF7\xB1\xED\x87\x89M", (2058) "\xAF\a\xCC\xA9-U\x1F;"
# ...
```

The "after: " line inspect both the `chunk` and the `next_chunk`, which should always be different, as they're the result of a call to `.drain_body`, which [duplicates the resulting string](https://gitlab.com/honeyryderchuck/httpx/-/blob/master/lib/httpx/request.rb#L141).

However, in the build that fails, you see:

```
# ...
(2060 loop: "\x89My@7\x8Ei\xB4") 
after: (2060) "\x1F;L\xD3\xB8\xF2\xE9\xFE", (2062) "\x1F;L\xD3\xB8\xF2\xE9\xFE"
# ...
```

So, the second call to `.drain_body` changes the first string.

I suspect that what causes this is the `.drain_body` implementation internals, which use an enumerator built from a call to `IO.copy_stream`. 

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.

I'm expecting the behaviour to be the same it was with `9.2.14`.

* Provide an executable Ruby script or a link to an example repository.

In order to reproduce it, you can:

* fork the [repo](https://gitlab.com/honeyryderchuck/httpx);
* switch to `fix-jruby` branch;
* `export BUNDLE_WITHOUT=website`;
* `bundle install`
* set the [fallback option](https://gitlab.com/honeyryderchuck/httpx/-/blob/master/lib/httpx/options.rb#L17) to `"h2"`;
* ` bundle exec ruby -Itest test/http_test.rb --name /test_plugin_multipart_pathname_put/`

The test run should pass in `9.2.14` and fail from `9.2.15` onwards.

**Comment by headius** [comment]
Thanks for the report! This should be easy to isolate given your reproduction.

**Comment by headius** [comment]
The changes that likely regressed this are in #6555 and do appear related to sharing String bytes.

**Comment by headius** [comment]
This patch fixes it. I am still trying to come up with a minimal reproduction.

```diff
diff --git a/core/src/main/java/org/jruby/util/IOChannel.java b/core/src/main/java/org/jruby/util/IOChannel.java
index 1bd1adc42a..3b00b1565f 100644
--- a/core/src/main/java/org/jruby/util/IOChannel.java
+++ b/core/src/main/java/org/jruby/util/IOChannel.java
@@ -111,7 +111,7 @@ public abstract class IOChannel implements Channel {
         // wrap buffer contents with String
         if (src.hasArray()) {
             // wrap heap src with shared string to prevent target from modifying our buffer (GH-4903)
-            string = RubyString.newStringShared(runtime, src.array(), position, remaining);
+            string = RubyString.newString(runtime, src.array(), position, remaining);
         } else {
             // copy native src to heap bytes to use in string
             byte[] bytes = new byte[remaining];
```

**Comment by headius** [comment]
The base problem is that the change to a shared string only protected the original content from being modified by the `write` callee, but modifications to the original content (in the ByteBuffer) can still show up in the strings passed to `write`.

**Comment by HoneyryderChuck** [comment]
I see. I guess this fix is also a "deoptimization", as the buffer will have to be exclusive for each string.

Yeah, I also couldn't reproduce the exact circumstance. I tried doing a combination of these "read to yield enumerables" + IO.copy_stream, but couldn't quite see it happen. Would be great if this could be tracked with some regression test :/

**Comment by headius** [comment]
e6c8407b618c9143a5da2b83f20088c30fb0c22a is the cause.

I have a working test now and I'm just reworking and commenting the code to make it clear what's going on. I was overzealous in using the incoming ByteBuffer array directly.

My test is pretty narrow, though... it tests this exact case. I would feel better if we could find some minimal reproduction in Ruby, so we ensure that path doesn't break some other way. I had some trouble following your code and then figured out the bug from my commits, so I didn't really dig into it.

**Comment by headius** [comment]
> I guess this fix is also a "deoptimization"

@HoneyryderChuck It is really an over-optimization on my part. The contract of `Channel#write` would seem to indicate that the buffer given is only a temporary view of data and should not be saved across calls. That's basically what I did here by reusing the buffer's array in a new String object.

**Comment by headius** [comment]
@HoneyryderChuck Could you at least narrow down what logic gets called for the `write` side of `copy_stream` here? It occurs to me that both my `Channel#write` and your IO-like `#write` should probably be making their own defensive copies of the incoming string, if we are to be strict about the `write` contract.

**Comment by headius** [comment]
Ignore that previous comment... I reread your report and you do point out the interesting logic, in the `drain_body` method. It does do a defensive `dup` but as in CRuby this still shares the original string's bytes. The fact that it works in CRuby indicates to me that they do a copy internally when the target IO-like is not a real IO, so I may have a way to test this in Ruby.

**Comment by HoneyryderChuck** [comment]
Sorry, missed the previous comments.

So you mean that the defensive copy happens because I'm using IO.copy_stream where the writer is not a real IO? I see.

**Comment by headius** [comment]
@HoneyryderChuck That is at least how it appears, but they may be simply copying for data transferred. In any case my fix works and there is a Java unit test, but I have not been able to simulate the problem in Ruby. Exercise for you if you get bored some afternoon. 😉
