### ISSUE TITLE
GC.start raises ArgumentError when passed named arguments

### ISSUE THREAD

**Issue by JasonLunn** [jruby/jruby#6818]
* JRuby version jruby-9.2.11.1
* Debian rodete 5.10.40-1rodete2 (2021-06-22) x86_64 GNU/Linux

**Expected Behavior**
Per the docs for `GC.start` and `GC.garbage_collect`, starting in version [2.1](https://ruby-doc.org/core-2.1.0/GC.html#method-c-start) these methods accept a dictionary of named arguments.

I understand that JRuby does not do anything with these values, however, calling these methods with named arguments currently raises an exception because neither are expecting any arguments.

**Actual Behavior**
`GC.start(full_mark: true, immediate_sweep: true)` raises an exception:

```ArgumentError: wrong number of arguments calling `start` (given 1, expected 0)```

**Comment by headius** [comment]
Thanks for the help!
