### ISSUE TITLE
JRuby 9.3 release notes

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6825]
This issue will let us collaborate on putting together the release notes for JRuby 9.3!

I have started filling in some of the major items and will add pieces as they come in. Once complete, we will use this content for the https://jruby.org and Github releases.

The full list of issues and PRs, sorted by creation date, is here:

https://github.com/jruby/jruby/issues?q=milestone%3A%22JRuby+9.3.0.0%22+is%3Aclosed+sort%3Acreated-asc

Look to past release for examples. We generally try to group similar fixes under a single bullet with a list of issue links. Small one-off bugs do not need their own release note bullets since they will be listed in a complete list of issues following the notes. Focus on new or rewritten subsystems, major compatibility changes or improvements, and important user-facing features.

Thanks for the help!

JRuby 9.3 Release Notes
===================

The JRuby community is pleased to announce the release of JRuby 9.3.0.0

* Homepage: http://www.jruby.org/
* Download: http://www.jruby.org/download

JRuby 9.3.x is compatible with Ruby 2.6.x and stays in sync with C Ruby. As always there is a mix of miscellaneous fixes so be sure to read the issue list below.

With such a long development cycle, there are bound to be "dot zero" bugs and compatibility gaps, so we plan to release incremental fixes for JRuby 9.3 rapidly. We encourage users to file issues for any problems they encounter.

Thanks to @byteit101, @ahorek, and ZZZ for their contributions!

Compatibility
--------------

* Ruby language compatibility is updated to match Ruby 2.6.8. ([#5576](https://github.com/jruby/jruby/issues/5576))
* The require/load/autoload subsystem has been rewritten to better match Ruby behavior. This improves support for the Zeitwerk loader and fixes many long-standing issues. ([#2794](https://github.com/jruby/jruby/issues/2794), [#3656](https://github.com/jruby/jruby/issues/3656), [#5403](https://github.com/jruby/jruby/issues/5403), [#5466](https://github.com/jruby/jruby/issues/5466), [#5590](https://github.com/jruby/jruby/issues/5590), [#5618](https://github.com/jruby/jruby/issues/5618), [#5638](https://github.com/jruby/jruby/issues/5638), [#5717](https://github.com/jruby/jruby/issues/5717), [#5763](https://github.com/jruby/jruby/pull/5763), [#5764](https://github.com/jruby/jruby/pull/5764), [#6347](https://github.com/jruby/jruby/issues/6347), [#6445](https://github.com/jruby/jruby/issues/6445))
* Improved logic for handling complex method and constant lookups, such as when prepends, refinements, or super calls are in play. Most known issues with these forms have been fixed. ([596](https://github.com/jruby/jruby/issues/596), [#2155](https://github.com/jruby/jruby/issues/2155), [#4678](https://github.com/jruby/jruby/issues/4678), [#6271](https://github.com/jruby/jruby/issues/6271), [#6712](https://github.com/jruby/jruby/pull/6712), [#6777](https://github.com/jruby/jruby/pull/6777), [#6778](https://github.com/jruby/jruby/pull/6778), [#6785](https://github.com/jruby/jruby/pull/6785))

Standard Library
-----------------

* The standard library has been updated to match Ruby 2.6.8. Several libraries now use the official gems, allowing them to be upgraded independently of JRuby. ([#4875](https://github.com/jruby/jruby/issues/4875), [#6150](https://github.com/jruby/jruby/pull/6150), [#6797](https://github.com/jruby/jruby/issues/6797), [#6796](https://github.com/jruby/jruby/issues/6796), [#6795](https://github.com/jruby/jruby/issues/6795), [#6794](https://github.com/jruby/jruby/issues/6794), [#6533](https://github.com/jruby/jruby/issues/6533), [#6802](https://github.com/jruby/jruby/issues/6802))

Java Integration
----------------

* JRuby supports Java versions 8 through 17, and should work well with any supported build of OpenJDK. Future versions of JRuby may drop support for Java 8 through 10, so we encourage users to upgrade older apps soon.
* The Java integration logic for extending Java classes from Ruby has been rewritten to better support Java constructors and to reuse more logic from the rest of our Java integration library. This allows users to use those Ruby subclasses with Java frameworks that bootstrap using reflection, such as JavaFX. ([#449](https://github.com/jruby/jruby/issues/449), [#2369](https://github.com/jruby/jruby/issues/2369), [#4165](https://github.com/jruby/jruby/issues/4165), [#5270](https://github.com/jruby/jruby/issues/5270), [#6422](https://github.com/jruby/jruby/pull/6422))
* JRuby now ships a new "jruby-base" jar artifact to Maven Central. This artifact provides a bare-bones JRuby jar file with no dependencies or standard libraries included. We may deprecate and remove the "jruby-core" artifact in the future, as it only provides Java dependencies and no standard libraries (users should prefer to build their own with jruby-base or use the jruby-complete artifact). ([#6233](https://github.com/jruby/jruby/pull/6233))

**Comment by thbar** [comment]
A section on JDK support (ref: https://twitter.com/headius/status/1436169461694861317) would be nice to have in the release notes (no matter if JDK 8 is still supported, or not).

Some people are still be on JDK 8 (via OpenJDK or Corretto https://stackoverflow.com/a/64391840/20302), and anything providing public visibility will help them negotiate upgrade budgets (in addition to "just knowing" when a switch will be strictly required or not). Thank you!

**Comment by mohits** [comment]
@headius - is this the kind of thing you are looking for?

JRuby on Windows
* Fixes failures with jar:file:stat on Windows (#6397)
* Fixed File.symlink on Windows (#6762)
* Upgraded Installer EXE from being based on install4j7 to install4j9 (#6750)

Updates to gems
* Update did_you_mean to 1.3.0 to match ruby 2.6.8 (#6797)
* Update rexml to 3.1.9.1 to match ruby 2.6.8 (#6796)
* Update rdoc to 6.1.2.1 to match Ruby 2.6.8 (#6795)
* Update to jruby-openssl 0.10.7 (#6794)
* Update RubyGems to 3.2 and Bundler 2.2 (#6533)
* Update non-gem stdlib to match RUby 2.6.8 (#6802)

Other Items
* Add an option for specifying the nested jar temp location (#6330)

**Comment by mohits-qi** [comment]
Copying the note from the mailing list in response to the point from @thbar 

JRuby 9.3 officially supports Java 8 through Java 17.

JRuby 9.4 (or whatever it will be called) *might* drop Java 8.

**Supported JAVA Versions**
JRuby 9.3 (and other minor versions such as 9.3.0.1, 9.3.1.0, etc.) officially support Java 8 through Java 17. The next major version (version 9.4 or such) might drop support for Java 8 in which case the minimum supported Java version would become Java 11, the next LTS version from Oracle.

**Comment by headius** [comment]
Yes that's the format for sure! If the fixes are fairly unique and small we
would not want a bullet for each, since they will also be listed below in a
complete listing of all issues and pull requests.

Generally my rule of thumb is if something is critical (i.e. a showstopper
for some common usage) or has more than one issue/PR associated, we should
include it.

If something is a library upgrade, we should include it.

If there's new functionality that could warrant its own wiki page (like the
excellent changes to Java integration by @byteit101) we should include it
(and consider making that accompanying wiki page.

Use your best judgment and add it to the issue and we can discuss and
revise!

- Charlie

**Comment by mohits** [comment]
Thanks, it's easier to remove than to write. So, if I find stuff that might be useful, I will try to collect stuff and you can see what editing is necessary on it.

**Comment by mohits** [comment]
Copying the note from the mailing list in response to the point from @thbar

JRuby 9.3 officially supports Java 8 through Java 17.

JRuby 9.4 (or whatever it will be called) might drop Java 8.

**Supported JAVA Versions**
JRuby 9.3 (and other minor versions such as 9.3.0.1, 9.3.1.0, etc.) officially support Java 8 through Java 17. The next major version (version 9.4 or such) might drop support for Java 8 in which case the minimum supported Java version would become Java 11, the next LTS version from Oracle.

**Comment by headius** [comment]
Yes, better to include stuff and then we can decide not to list it
separately, rather than to miss some major items.

The 9.2.18.0 release notes had a lot of issues and bullets, and is a
good model for the granularity we are looking at.

https://www.jruby.org/2021/06/08/jruby-9-2-18-0.html

FWIW I have been putting these together by hand for the past year or
so. We need a better system, but if you all can help gather the key
items it will go faster.

- Charlie

**Comment by headius** [comment]
I did one more pass through the issues and PRs marked for 9.3.0.0 and I think this is a pretty good set of major release items. I will add this to a wiki page and link it, so if we want to add additional items or link to more information (e.g. doco for the Java extension changes by @byteit101) we can keep improving it.

**Comment by headius** [comment]
Release notes are available on the wiki here: https://github.com/jruby/jruby/wiki/JRuby-9.3.0.0-Release-Notes
