### ISSUE TITLE
Calling exit! within at_exit doesn't "clear" the exception

### ISSUE THREAD

**Issue by palkan** [jruby/jruby#6874]
**Environment Information**
  
* JRuby version: jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 25.302-b08 on 1.8.0_302-b08 +jit [linux-x86_64]

**Expected Behavior**

Calling `exit!(0)` within the `at_exit` hook _silence_ the exception raised during the code execution:

```ruby
# at_exit_rescue.rb
at_exit do
  if SyntaxError === $!
    $stderr.puts "We caught it!"
    exit!(0)
  end
end

require_relative "../support/invalid_syntax"
```

```sh
$ ruby at_exit_rescue.rb

We caught it!
```

See https://github.com/palkan/ruby-compatibility-examples/runs/3790787723?check_suite_focus=true

See also https://github.com/ruby-next/ruby-next/issues/81

**Actual Behavior**

```sh
$ ruby at_exit_rescue.rb

SyntaxError: /home/runner/work/ruby-compatibility-examples/ruby-compatibility-examples/support/invalid_syntax.rb:1: syntax error, unexpected '}'
invalid_hash = {x =>                      ^
           require at org/jruby/RubyKernel.java:1017
  require_relative at org/jruby/RubyKernel.java:1045
            <main> at examples/at_exit_rescue.rb:8
We caught it!
```

----

A similar issue appeared and TruffleRuby: https://github.com/oracle/truffleruby/issues/2047

**Comment by headius** [comment]
Well you win the weird bug of the week award! 🏅

I'll look into this.

**Comment by headius** [comment]
So the problem is that we still print the exception, is that right? I confirmed on master that we do print "I caught it" after also printing out the exception.

```
$ jruby blah.rb
SyntaxError: /Users/headius/projects/jruby/invalid_syntax.rb:1: `@$' is not allowed as an instance variable name
           require at org/jruby/RubyKernel.java:1017
  require_relative at org/jruby/RubyKernel.java:1045
            <main> at blah.rb:9
We caught it!

$ jruby -v
jruby 9.3.1.0-SNAPSHOT (2.6.8) 2021-10-06 e50dcb87cc OpenJDK 64-Bit Server VM 11.0.4+11 on 11.0.4+11 +jit [darwin-x86_64]
```

**Comment by palkan** [comment]
> the problem is that we still print the exception, is that right? 

Yep!
