### ISSUE TITLE
Coordinate for porting Ruby 3 parser changes

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6880]
Since both [JRuby](https://github.com/jruby/jruby/issues/6878) and [TruffleRuby](https://github.com/oracle/truffleruby/issues/2453) are planning to work on Ruby 3.0 support soon, and we share the parser, I think it could be useful to coordinate.

Could we write here whenever someone starts working and get some part done on porting the parser changes from CRuby 3.0?
cc @headius @enebo @nirvdrum @chrisseaton @norswap @tomstuart

FWIW TruffleRuby already has AFAIK all 2.7 parser changes in with the exception of pattern matching, which you might find useful for JRuby.

**Comment by eregon** [comment]
This is one way to see changes:
In JRuby: https://github.com/jruby/jruby/commits/master/core/src/main/java/org/jruby/parser/RubyParser.y
In TruffleRuby: https://github.com/oracle/truffleruby/commits/master/src/main/java/org/truffleruby/parser/parser/RubyParser.y

It looks JRuby has ported some or all of the pattern matching syntax? (pattern matching was introduced in 2.7 and I think did not change too much in 3.0, but was slightly extended)
@enebo Could you maybe clarify that and make a summary of what's done/left for Ruby 3 parser changes?

**Comment by enebo** [comment]
@eregon grammar and lexer should be finished up to 3.0.2 barring mistakes/bugs.  I think perhaps warning subsystem stuff might need tweaks but that would only affect us. since you replace the meat of this stuff.

**Comment by eregon** [comment]
@enebo Great work, I didn't realize you already imported the Ruby 3 parser :)

I've started importing the changes in TruffleRuby and unfortunately it's a huge amount of work because of many small differences here and there, no automated update (except for `RubyParser.y`) and the parser being in general not standalone but depending on some internals (e.g., RubySymbol, ByteList).

I think the far better way forward would be to extract a standalone Ruby parser library/jar, that we could both reuse as-is and maintain.
Do you think that would be feasible in general?
So similar to https://github.com/jruby/jruby-parser, but it would be used by JRuby, by TruffleRuby, potentially other projects, and kept up-to-date.

I'd be happy to help design and migrate code to achieve that.

Regarding the design, I think the existing visitor pattern (`NodeVisitor`) is quite good and works well.

For the source positions, it seems CRuby exposes more and more the detailed column information and lines are no longer enough.
In Truffle, currently the most efficient way is to have a `char` offset (from the start of the file) and a `char` length, and this avoids a need to compute the line/offset mapping eagerly.
Currently in the JRuby parser it seems either single-line-only or start+end line/column is used, but nodes seem to remember only lines and not columns.
I think the reason in Truffle to prefer those offset+length is footprint (two `int` fields: `sourceCharIndex` and `sourceLength` vs 4) and also being able to efficiently communicate those offsets to debuggers, etc.
The packing of line & column info as two `int` in `ProductionState` seems the same in footprint, so that seems also a good alternative approach.
Either we could align to one of those approaches, or maybe it's possible to make it flexible and have access to both.

I think in general it's best to avoid Ruby runtime values in the AST like RubySymbol, notably to avoid dependencies on the runtime. But if it's better for it to be there for JRuby we could probably design something with generics (and e.g. `symbolID()` would return that generic type).
For strings, `ByteList` could be used, or just a raw `byte[]` + Encoding to be representation-neutral. One advantage of ByteList or another similar type is it's easy to support substring over the entire source `byte[]` without copying the bytes.

I think it would be productive to discuss this over a call. I can come to the JRuby Matrix, or I saw you're also on the GraalVM Slack, so we can schedule it, what do you prefer?

**Comment by enebo** [comment]
@eregon I think this sounds like a lot of work and is pretty ambitious.  If you want to play with these ideas jruby-parser might be the right place.  I can add you as a contributor and you can work through some of the ideas (like more efficient storage of lines/columns).  Also using byte[] vs ByteList (which seems like it will be a pretty tall order since we do not want any transient objects created during parsing).  Using id vs RubySymbol is another thing which I suspect is fine but we still need to eagerly create the symbols at some point during parse.  We do not need to store the Symbol in the Node it just is convenient to not ask the symbol table for it where it will immediately get used in IR building.

My main concern is warmup and memory.  Here is an example from our pre-IR days.  We used to use visitor pattern for our AST interpreter.  This extra indirection played very poorly with warmup and also ended up making us exhaust stack frames quicker (to the point of getting issues made about it).

I can help by answering questions about why something was done the way it was and if you start taking things in a direction which works for both of us then perhaps we will commit more to the idea.

**Comment by eregon** [comment]
@enebo I'm not sure how much work it would be to adapt `jruby-parser` and if it'd gain much over the parser inside JRuby.
I think the parser inside JRuby already includes column information now, right?

Most things I mentioned would be nice-to-have and could be done later or not, the main requirement from my side would be a shared parser code that works for both JRuby and TruffleRuby, so we stop duplicating efforts there.
So we'd need the parser to avoid depending on JRuby runtime things like RubySymbol and have it in its own package/module/pom/whatever so it stays that way and it's clear why. ByteList would just be in the same package to keep things simple.
I'll try that work myself, which would mean changes in JRuby to prepare for that.

I'd like a call to discuss this in more depth so I sent you an email.
Notably I'd like to learn more about how you port changes from CRuby,
 and other ideas on how we could reuse more of CRuby's lexer and parser with less efforts (I know @kddnewton is also looking into that and I had a call with him).

**Comment by enebo** [comment]
> I think the parser inside JRuby already includes column information now, right?

  It keeps track of columns during parsing itself but does not retain that in the AST.  That column info is the current line where the error occurs.  I am not sure if Ruby experimental AST package saves it or not but I am not sure we have any current plans to support that API unless it stops being experimental (and tbh it is highly representative of MRIs in-memory view -- whats a T_CLASS).

Main discussion on collaborating...Note that the tenor of this is that I don't think it is a good idea (upon quite a bit of reflection) but with that said there are things mentioned in here that I think can reduce the pain of consuming our code. Things which reduce frustration we can try and accommodate.


I have been thinking about this for a few weeks now.  I don't think we (both
projects) will get much out of a broader collaboration.  My main concerns:

  1. We want to pay zero penalty (warmup, memory) at runtime for sharing code
  2. We do not want to get locked into a solution (think sunk cost)
  3. The work to do this will come at the cost of other priorities

Number 3 is probably a reason which affects me more than you but we have so
many other things that we can be working on.  Just even composing these thoughts
is a significant amount of time.

Number 2 is largely from having some ideas to explore on what might be better than we do now but if we go through this shared route it will limit the desire to try new things.  This also means if we do decide to improve something we have to coordinate how that idea affects both of our projects.  The corollary here is a feeling of guilt if we want to radically change something knowing it will affect your projects ability to use what is changed (which I suspect an issue already).

Number 1 is probably a biggest concern.

We make live objects early (Symbol was mentioned but this includes numeric types, regexps, errors, and warnings).  If we indirect how we create those through an interface then we are introducing a tiny amount of warmup.  If we made these through a static call (and you just happen to have the same static call) then perhaps there is no penalty and it is easier to reuse.  I am not concerned about overhead of things like errors or warnings but anything involving identifiers or something hit often we want hot as quick as possible.

Do you want our AST specifically?  Don't you want to generate something closer to the nodes you will eventually have?  This is perhaps just questions but locking into our AST means bleeding some amount of indirect overhead into your project.  Again perhaps this could be done through static methods?  Not really sure.

We also have live context objects you probably have but are different (StaticScope, ThreadContext/Ruby).  Our current design assumes a type but perhaps we can abstract this as parameters to static methods so you can use your equivalent and we can use ours without any overhead.

We retain AST for unexecuted methods and so AST memory is important to us.  We have occasionally put them on diets to cut down memory use.  Having a heap size which competes with MRIs heap is a requirement.  Adding a field for columns is something we have no interest in at all unless we are forced to.

I guess one addendum is that I do not think I (as in Tom)  will gain anything personally from this.  I already update our parser and the need to make it fit some shareable definition will not reduce my work (this is just my opinion).  Having said this I do not want things to be more of a burden for you.  If I can make changes which makes it simpler and it does not interfere with warmup/memory and it also does not require a lot of extra time I will help make changes to make it easier to consume.

**Comment by headius** [comment]
It seems that our parser requirements are incompatible with the needs of other implementations, and with efforts by @kddnewton, @seven1m and others to produce an common native parser library, there's no reason to keep this open.

If at some point there's interest in using the JRuby parser directly without breaking our requirements, we're willing to collaborate on that.
