### ISSUE TITLE
RuntimeError: Found multiple supers in java ctor

### ISSUE THREAD

**Issue by yamam** [jruby/jruby#6935]
In jruby 9.3.1.0, I get an error when there are multiple super in the constructor of a class that inherits from a Java class, is this a limitation?

**Environment Information**
  
jruby 9.3.1.0 (2.6.8) 2021-10-13 2e01e7199d OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04 on 11.0.11+9-Ubuntu-0ubuntu2.20.04 +jit [linux-x86_64]

**Expected Behavior**

test.rb
```ruby
java_import 'java.util.BitSet'

class MyBitSet < BitSet
    def initialize
        if true
            super
        else
            super
        end
    end
end

MyBitSet.new
```

```
$ jruby-9.2.20.0/bin/jruby -v test.rb
jruby 9.2.20.0 (2.5.8) 2021-11-02 1a3255440b OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04 on 11.0.11+9-Ubuntu-0ubuntu2.20.04 +jit [linux-x86_64]
```

**Actual Behavior**
```
$ jruby-9.3.1.0/bin/jruby -v test.rb
jruby 9.3.1.0 (2.6.8) 2021-10-13 2e01e7199d OpenJDK 64-Bit Server VM 11.0.11+9-Ubuntu-0ubuntu2.20.04 on 11.0.11+9-Ubuntu-0ubuntu2.20.04 +jit [linux-x86_64]
RuntimeError: Found multiple supers in java ctor
  <main> at test.rb:13
```

**Comment by byteit101** [comment]
This is a limitation of the current `super` analysis in the IR that @enebo wrote. As java-extending classes must now compile to (compliant) bytecode, we must ensure certain constraints are met, namely `super` is called only 0 or 1 times. I could have sworn we fixed the case of a simple if, but perhaps not?

**Comment by enebo** [comment]
We can solve this specific case in an adhoc way but the only way to appropriately solve this would be performnig flow analysis.  I am not sure if we should support this or just document this as something we will not support.  We also need to be concerned with whatever is happening in the if test since it cannot use self.

**Comment by enebo** [comment]
I think the fix for this is to specify this is not allowed.  @byteit101 added a better error message to let people know and get a link to a page explaining more.  We may do more sophisticated analysis if this ends up being something a lot of people complain about.
