### ISSUE TITLE
NoMethodError loading bson-4.12.1-java

### ISSUE THREAD

**Issue by fabpoeschl** [jruby/jruby#6941]
Loading bson-4.12.1-java results in the following error:
NoMethodError:
  undefined method `runtime' for JRuby:Module

**Environment Information**
  
Provide at least:
* jruby-9.3.1.0 JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
* macOS Kernel version 20.6.0

**Comment by ahorek** [comment]
this has to be fixed in the library https://github.com/mongodb/bson-ruby/pull/252
