### ISSUE TITLE
Only since 9.3: SSLError certificate verify failed error in Rails console, but not in IRB

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby#6947]
Only since JRuby 9.3.0.0 and 9.3.1.0, if I run the following code it works just fine in IRB, but raises `OpenSSL::SSL::SSLError (certificate verify failed)` if you generate a new Rails 6.1.4.1 project with `rails new` and run the rails console:

```ruby
require 'net/http'
Net::HTTP.get(URI('https://api.profitwell.com/'))
```

This doesn't happen in JRuby 9.2.20.0, or in MRI 2.6.9. It also is _only happening with this URL_, the handful of other URLs I've tried work just fine. Looking at [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=api.profitwell.com), the URL's TLS configuration seems to be perfectly fine though so it's not an error on their end.

This happens both on Ubuntu 20.04 and MacOS 12.0.1 with OpenJDK 11.0.11.

Here's the full stack trace, doesn't add any extra info unfortunately:

```ruby
Traceback (most recent call last):
        1: from (irb):1:in `evaluate'
OpenSSL::SSL::SSLError (certificate verify failed)
```

**Comment by kares** [comment]
please update jruby-openssl to latest (0.11.0) to see if the issue gets resolved, 
9.3 does not yet have a release with the updated gem (only 9.2 https://github.com/jruby/jruby/pull/6909)

**Comment by mohamedhafez** [comment]
Adding `gem 'jruby-openssl', '>= 0.11.0'` to my Gemfile did indeed fix the issue, thanks!
