### ISSUE TITLE
JRuby seems to consumes much memory than CRuby

### ISSUE THREAD

**Issue by mohits** [jruby/jruby#6962]
**Environment Information**

* JRuby: jruby 9.2.18.0 (2.5.8) 2021-06-08 d67cb7d6e0 OpenJDK 64-Bit Server VM 25.265-b01 on 1.8.0_265-b01 +jit [mswin32-x86_64]
* Operating system and platform: Windows 10 Version 21H1 (19043.1348)
* Main gem in use: xlsxtream
* Ruby version: ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x64-mingw32]

**Behavior**

The gem `xlsxtream` writes an Excel file in streaming mode (flushes to disk as it runs) and I wrote a script that creates a file with 1M rows, and each row has 20 cells with an integer value (up to 4 digits).

Observing memory casually from Task Manager, I observed:
* JRuby consumes between 1.6GB - 2.0GB
* CRuby 3.0 consumes between 15GB - 20GB

It's common to see JRuby take approx 8 ~ 10x the memory but this seemed like a case where the consumption could be up to 100x of the CRuby version.

Note: no start-up parameters in place, no limiting of the max heap, and the numbers are simply read from Task Manager (see snapshot).

The code used is the `minimal-xlsxtream.rb` from https://github.com/mohits/rb-xlsx-converter-comparison

![jruby-cruby](https://user-images.githubusercontent.com/56816/144886943-81978ad2-f583-4c38-8aa2-fb6e85b00449.png)

**Comment by headius** [comment]
I can't see the headers in that process output. Perhaps this is just virtual memory that the JVM has requested?

I ran your example with xlsxtream and it took about a minute on my system, never exceeding a 300MB heap. Should this example reproduce your 2GB situation?

**Comment by headius** [comment]
Here's a heap dump mid-execution. It seems like the majority of the memory is consumed by byte arrays, probably String content? I don't see anything particularly unusual here. We may be using more memory simply because the JVM GC likes to wait to clean stuff up.

<img width="629" alt="Screen Shot 2021-12-06 at 11 45 46" src="https://user-images.githubusercontent.com/10135/144895565-8b47f925-efba-4d63-884d-55bedaa591d5.png">

**Comment by headius** [comment]
Just to try, I switched to the parallel GC and saw considerably wilder memory use. It did not appear to *require* more memory, but the high heap spikes were **much** higher, approaching 2GB while I watched. The G1 GC seems to have much better memory-utilization characteristics, and never exceeded a 400MB total heap while usually using less than half of it.

Java 8 uses the Parallel GC by default. Java 11+ use G1. You might try using a newer release of Java, or possibly switch to the G1 GC by passing `-J-XX:+UseG1GC` to the JVM via JRuby command line. FWIW the G1 GC is greatly improved in newer versions of Java and does not perform as well on Java 8 (unless they've backported all of that, but I don't think so).

**Comment by mohits** [comment]
Thanks @headius - sorry, for the delay in replying - I was asleep.

The value that I saw in the Task Manager is "Memory (active private working set)" which Windows shows as "The amount of physical memory in use by the process that that can't be used by other processes (excludes suspended UWP processes)".

![image](https://user-images.githubusercontent.com/56816/144958891-1a9d83c7-6d96-4c48-914d-5bc6e9d336e4.png)

You're right - I'm using Java 8. I will try both the options (use G1GC and also Java 11) - will also add this to the blog post I'm planning.

Thanks for digging into this!

**Comment by mohits** [comment]
> Here's a heap dump mid-execution. It seems like the majority of the memory is consumed by byte arrays, probably String content? I don't see anything particularly unusual here. We may be using more memory simply because the JVM GC likes to wait to clean stuff up.

I suspect both statements are true.

1. The bulk of the work is in creating cells that belong to rows that belong to a sheet that belongs to a workbook, and gets written out as XML.

2. I also think that given that memory is very much available (more than 50% on a 40GB system), that the JVM might have good reason to delay running.

**Comment by mohits** [comment]
Hi @headius - I finally got around to trying this with the `-J-XX:+UseG1GC` and also with Java 11 and Java 16. In all cases, the numbers are read off as a lot lower. The same value read directly off Windows Task Manager falls to 800MB ~ 900MB depending on the specific combination.

I'm closing this issue unless someone wants to re-open it.

**Comment by mohits** [comment]
This is the comparison with a couple of options. The second column from the right is the same as before - "Memory (active private working set)" which Windows shows as "The amount of physical memory in use by the process that that can't be used by other processes (excludes suspended UWP processes)".

![jruby-java-memory-comparison](https://user-images.githubusercontent.com/56816/147540570-61590015-3bc1-4cc1-ae4a-ca63636c18b6.png)

This issue/ thread/ conversation is also noted here now: https://notepad.onghu.com/2021/jruby-using-g1gc-reduces-memory/
