### ISSUE TITLE
9.3.3.0 nighly on an M1 mac: File permissions issues

### ISSUE THREAD

**Issue by kovyrin** [jruby/jruby#7013]
Hello,

I've just tried to test our project with the latest 9.3.3.0 nightly and noticed the following strange behaviour:

1. I ran the following command using mri 2.6.8, jruby 9.2.19 and the jruby 9.3.3.0 nighly: 

```
ruby -e "File.open('jruby-9.2.19.0.txt', 'w+').close"
```

2. Here are the results (look at the permissions):

```
ls -l *.txt
-rw-r--r--  1 kovyrin-elastic  staff  0 17 Jan 20:14 jruby-9.2.19.0.txt
---x------  1 kovyrin-elastic  staff  0 17 Jan 20:11 jruby-9.3.3.txt
-rw-r--r--  1 kovyrin-elastic  staff  0 17 Jan 20:11 mri-2.6.8.txt
```

This weird default permissions issue results in bundler blowing up very predictably with the following error:

```
There was an error while trying to read from
`/var/folders/__/tsvmjrss4q52s6_dc9w3g0440000gn/T/bundler-compact-index-20220117-37015-sw6fyi/versions`.
It is likely that you need to grant read permissions for that path.
```

I've checked umask values and they match across versions, so it does not seem to be an umask issue.

**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc):
```
jruby 9.3.3.0-SNAPSHOT (2.6.8) 2021-12-17 be64efd8d4 OpenJDK 64-Bit Server VM 17.0.1+12-39 on 17.0.1+12-39 [darwin-aarch64]
```

* Operating system and platform (e.g. `uname -a`)
```
uname -a
Darwin elastic-m1.home 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:05 PST 2021; root:xnu-7195.141.14~1/RELEASE_ARM64_T8101 arm64
```

Computer: 
MacBook Pro (13-inch, M1, 2020)

**Expected Behavior**

Default permissions for new files should be 0644

**Actual Behavior**

Default permission for new files seems to be 0100

**Comment by headius** [comment]
I believe you grabbed an old snapshot. This is dated 12-17, which would place it before most of the big M1 fixes. Can you give it a try with a newer one? I triggered at least one snapshot build yesterday.
