### ISSUE TITLE
Cannot install psych in JRuby-9.3.3.0 due to issue in ruby-maven

### ISSUE THREAD

**Issue by AndyObtiva** [jruby/jruby#7026]
This issue was originally reported at the psych project: 

https://github.com/ruby/psych/issues/520

It was also referenced at the ruby-maven project because it is the cause of the problem and the issue was fixed in this merged ruby-maven pull request:

https://github.com/jruby/ruby-maven/pull/2

I thought it would get resolved in JRuby-9.3.3.0 given that ruby-maven had the bug fixed, but apparently no new ruby-maven release was made along with the latest JRuby. That is why I am reporting this over here to raise the level of seriousness of this issue.

It is forcing me to downgrade psych to 3.3.2 in all my [Glimmer DSL for SWT projects](https://github.com/AndyObtiva/glimmer-dsl-swt) to avoid getting that error mentioned at the psych issue: "unsupported Java version "16", defaulting to 1.7 " (happens with JDK 17 too)

I'd like to keep this issue open until ruby-maven is updated. I realize ruby-maven is a different project, but it is under the jruby umbrella and I thought this would get much more attention over here (it got ignored at ruby-maven in the past as no new releases of it happened for several months).

**Comment by headius** [comment]
@AndyObtiva Thanks for bringing it to our attention again.

We have rights to push an update to the gem, but never really took over maintenance of it officially from @mkristian. Our plan going forward is to take over most of the Ruby/Maven projects so we can release new versions as needed. I will try to prioritize making that happen this week.

**Comment by headius** [comment]
Ok, I confirmed the error happens for me:

```
[] ~/projects/ruby-maven $ gem install psych
  jar dependencies for psych-4.0.3-java.gemspec . . .
unsupported Java version "16", defaulting to 1.7
[ERROR] Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @7f92b990 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @7f92b990
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @7f92b990
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /Users/headius/projects/jruby-9.3/lib/ruby/gems/shared/gems/psych-4.0.3-java/deps.lst
```

Installed a prerelease ruby-maven 3.3.13 and uninstalled 3.3.12:

```
[] ~/projects/ruby-maven $ gem install /Users/headius/projects/ruby-maven/pkg/ruby-maven-3.3.13.gem
Successfully installed ruby-maven-3.3.13
Parsing documentation for ruby-maven-3.3.13
Installing ri documentation for ruby-maven-3.3.13
Done installing documentation for ruby-maven after 1 seconds
1 gem installed

[] ~/projects/ruby-maven $ gem uninstall ruby-maven

Select gem to uninstall:
 1. ruby-maven-3.3.12
 2. ruby-maven-3.3.13
 3. All versions
> 1
Successfully uninstalled ruby-maven-3.3.12
```

And confirmed it is now working for me:

```
[] ~/projects/ruby-maven $ gem install psych
  jar dependencies for psych-4.0.3-java.gemspec . . .
2022-01-24T09:51:30.470-06:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
      org.yaml:snakeyaml:1.28:compile
Successfully installed psych-4.0.3-java
Parsing documentation for psych-4.0.3-java
Done installing documentation for psych after 2 seconds
1 gem installed
```

The maven-based gem push fails for ruby-maven due to it not being able to see my API keys, so I had to push it manually. I will take the current revision with 3.3.13 and bump the release version.

@mkristian Need to figure out how to hand off maintenance!

**Comment by mkristian** [comment]
@headius my impression was/is that @deivid-rodriguez was doing all the updates around ruby-maven the last time. maybe the missing bits are given him access to jruby-maven-plugins on github and sonatype, dito for the ruby gems, maven-tools, ruby-maven and for polyglot-maven (depends a bit on Jason v. Zyl what is possible). After seeing him I did not write up anything, but better I do . . .

**Comment by headius** [comment]
@mkristian As these libraries all revolve around JRuby, perhaps dumping everything you can into a Ruby+Maven wiki page would be a good start?

I admit I was not following how @deivid-rodriguez would fit into this long term, but we certainly can use the help maintaining these libraries. I also have a number of common-sense updates I want to make on the polyglot and Maven plugin side of this.

**Comment by deivid-rodriguez** [comment]
Yeah, to be honest, I contributed these patches because I was bitten by this issue via reports of `bundle install` issues, and because I like helping out where I see lack of human power, but the jruby core team is a much better fit to maintain this library in the long term.
