### ISSUE TITLE
Log rotation inter-process lock failed, Issue occurs in JRuby 9.3.0.0 and Windows

### ISSUE THREAD

**Issue by JesseChavez** [jruby/jruby#7038]
Here is the production steps (basically I copied what was logged in Logger gem repository https://github.com/ruby/logger/issues/67)

**1) Test script:**
`test_logger.rb`
```
logger = Logger.new("D:/log.txt", 5, 1024)
  
150.times do |i|
  logger.info i
end
```
**2) run script:**
The easiest way to run JRuby in windows would be  installing Java 11 and downloading `jruby-complete-9.3.0.0.jar`, then run:

```
D:\>java -jar jruby-complete-9.3.0.0.jar test_logger.rb
```
**3) Console output:**
log rotation inter-process lock failed. D:\log.txt -> D:\log.txt.0: The process cannot access the file because it is being used by another process.
log writing failed. closed stream
log shifting failed. closed stream
log writing failed. closed stream
log shifting failed. closed stream
...

**4) Cause:**
The issue occurs due JRuby returns `java` for `RUBY_PLATFORM` when loading the method `lock_shift_log`

**Comment by JesseChavez** [comment]
I have provided a Pull Request to fix this issue in the gem itself.
https://github.com/ruby/logger/pull/68

**Comment by headius** [comment]
Your PR looks great and was merged, but I don't think there's been a logger release with that change in it. The logger gem has moved on from the 1.3 versions, but the newer releases *should* be compatible with JRuby 9.3 (required Ruby version in the gemspec is 2.3). Once there's an updated version, we can depend on it in default gems and call this resolved.

Thank you for the extra footwork!

**Comment by headius** [comment]
I have requested a release of the logger gem, which hopefully will happen soon. We will then incorporate that gem into JRuby 9.3.4.
