### ISSUE TITLE
__callee__ uses real method and not aliased method name

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#7091]
I am not sure if this will end up on 9.2 or not but this is broken for all supported versions:

```ruby
def foo
  p __callee__
end

alias :bar :foo

bar
```

I noticed while examining 3.1 ripper which aliases all events to the same method name (and hilarity ensues).

**Comment by enebo** [comment]
Moving off of 9.2 since this has only been observed in one place and I worked around it (e.g. default ripper impl).

**Comment by joeldrapper** [comment]
@headius using `alias_method` with `__callee__` is an important Ruby meta-programming technique that allows you to define methods that behave differently depending on which method was called.

**Comment by headius** [comment]
This is actually a dupe of a very old bug, #2305, so I'm going to close it as a dupe.

But good news... I have a possible fix I'll push as a PR shortly.

**Comment by headius** [comment]
See #7702.
