### ISSUE TITLE
bad classpath with ant build/test when includeantruntime='true'

### ISSUE THREAD

**Issue by ryenus** [jruby/jruby#710]
Some tasks using javac, e.g. `compile-jruby` have `includeantruntime="true"`.

This cause build/test errors in some packaging systems, e.g. pacman for Arch Linux, because the `apache-ant` package ships with all the optional libraries, including a quite outdated jruby.jar (0.9.8 at the time of writing this).

I think the solution should be to change `includeantruntime` to `false`, then explicitly include only necessary libraries/jars from Ant.

We need yet to figure out what are the 'necessary jars we need from ant'.

**Comment by enebo** [comment]
No update in a long time and we have moved to maven along time ago...
