### ISSUE TITLE
already initialized IPv6 constants

### ISSUE THREAD

**Issue by ylecuyer** [jruby/jruby#7100]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc): 9.3.3.0
* Operating system and platform (e.g. `uname -a`) Linux 5.4.0-99-generic

Other relevant info you may wish to add:
* Environment: system with no IPv6 support

**Actual Behavior**

When running `require 'socket'` I have the following warnings:

```
/root/.rbenv/versions/jruby-9.3.3.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::AF_INET6
/root/.rbenv/versions/jruby-9.3.3.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::IPPROTO_ICMPV6
/root/.rbenv/versions/jruby-9.3.3.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::IPPROTO_IPV6
/root/.rbenv/versions/jruby-9.3.3.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::PF_INET6
/root/.rbenv/versions/jruby-9.3.3.0/lib/ruby/stdlib/socket.rb:4: warning: already initialized constant Socket::Constants::SOL_IPV6
```

**Expected Behavior**

No warning are raised

**Understanding**

From my understanding this is because of this code: https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/socket/RubySocket.java#L116-L123

which sets those constants to nil if the host has no IPv6 support

**Comment by ahorek** [comment]
see https://github.com/jruby/jruby/issues/7069 and https://github.com/jruby/jruby/pull/7071

**Comment by headius** [comment]
@ylecuyer I took care of that for you. We will release #7071 in 9.3.4 shortly.
