### ISSUE TITLE
Ripper.tokenize does not handle '?\n' correctly

### ISSUE THREAD

**Issue by nabice** [jruby/jruby#7114]
JRuby 9.3.3.0 output:
irb(main):007:0> Ripper.tokenize('?\n', "-", 1)
=> ["?\\", "n"]

CRuby 2.7.0 output:
irb(main):002:0> Ripper.tokenize('?\n', "-", 1)
=> ["?\\n"]

**Comment by enebo** [comment]
I fixed this for jruby-9.2 and jruby-9.3.  Simple low risk fix.
