### ISSUE TITLE
`Range#===` should not accept range argument

### ISSUE THREAD

**Issue by takaram** [jruby/jruby#7137]
**Environment Information**
  
`jruby 9.3.3.0 (2.6.8) 2022-01-19 b26de1f5c5 OpenJDK 64-Bit Server VM 11.0.13+8-Ubuntu-0ubuntu1.18.04 on 11.0.13+8-Ubuntu-0ubuntu1.18.04 +jit [linux-x86_64]`

**Expected Behavior**

Unlike `Range#cover?`, `Range#===` does not accept range arguments.

```rb
# MRI 2.6.9
p (1..10).cover?(2..3) #=> true
p (1..10) === (2..3) #=> false
```

**Actual Behavior**

`(1..10) === (2..3)` returns true.

**Comment by headius** [comment]
This appears to be the behavior as far back as 1.8.7.
