### ISSUE TITLE
File.identical? should use stat to compare files

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7151]
`File.identical?` in CRuby compares two files using the following algorithm:

* `fstat` each file's fd, or if either are a String path, `stat` the path.
* Compare the stat structs' `dev` and `ino` fields to confirm they do in fact point at or resolve to the same filesystem entry.

In JRuby, however, we do not use stat and instead just canonicalize the given paths or the **original** paths of any given open `File`s and compare the canonicalized results.

This generally works ok, since the canonicalized file path should be unique on most modern filesystems. It fails, however, if an open file's entry has been `rename`d (or `unlink`ed) on the file system. In that case, our canonicalization of the original path does not reflect the new filesystem entry (or lack thereof).

This is the cause of (at least) the sole remaining `Logger` test failure, `TestLogDevice#test_shifting_size_not_rotate_too_much`.

https://github.com/jruby/jruby/blob/85a47471700e2ad01775ba14e86a10d67474c7b5/test/mri/excludes/TestLogDevice.rb#L1

This test has a comment in the `logger` gem indicating that we fail it:

https://github.com/ruby/logger/blob/master/test/logger/test_logdevice.rb#L438

Note that our `File` objects *will* actually point at the new filesystem entry if it has been renamed, so this is just a flaw in how we implement `identical?`.

This has been a bug for a very long time, so it may not be a high priority to fix; however we do have the ability to do a native `stat` or `fstat` (for a path versus an open `File`) so it would not be a large amount of work to implement this correctly when native support is available.

**Comment by skmp** [comment]
This seems to be already implemented in `RubyFileTest::identical_p`, though as a fallback if the nio match fails.

https://github.com/jruby/jruby/blob/22f87be2eb4189e3927f89326cbe6ce00a9008d7/core/src/main/java/org/jruby/RubyFileTest.java#L175C1-L183C6

Rewriting as (this is untested code)
```
    @JRubyMethod(name = "identical?", required = 2, module = true)
    public static IRubyObject identical_p(IRubyObject recv, IRubyObject filename1, IRubyObject filename2) {
        Ruby runtime = recv.getRuntime();
        FileResource file1 = fileResource(filename1);
        FileResource file2 = fileResource(filename2);

        // Try posix first
        if (!Platform.IS_WINDOWS && runtime.getPosix().isNative()) {
            FileStat stat1 = file1.stat();
            FileStat stat2 = file2.stat();
    
            return runtime.newBoolean(stat1 != null && stat2 != null && stat1.isIdentical(stat2));
        }

        // fallback to NIO2 to support more platforms
        if (file1.exists() && file2.exists()) {
            try {
                Path canon1 = new File(file1.absolutePath()).getCanonicalFile().toPath();
                Path canon2 = new File(file2.absolutePath()).getCanonicalFile().toPath();
                return runtime.newBoolean(Files.isSameFile(canon1, canon2));
            } catch (IOException canonicalizationError) {
                // fall through
            }
        }
        return context.fals;
    }
```

Should get the intended effect for posix linux. Keep in mind, windows/ntfs also has "FileId" which can be used for a similar test there, assuming one can get the native handle, and `GetFileInformationByHandle/Ex` accesss.

**Comment by enebo** [comment]
@skmp This looks reasonable.  It might be possible the stat section WILL work on windows since we do have a stat impl in the jnr-posix library.  isIdentical uses inode + dev and if windows returns meaningful values for those then removing `!Platform.IS_WINDOWS` may make it work without needing to get windows HANDLE.  Can you open up a PR for this?

**Comment by robotdana** [comment]
fwiw this also seems to cause an issue with case insensitive file systems

given Dir.pwd != Dir.pwd.swapcase, and Dir.pwd is located on a case insensitive formatted drive
`File.identical?(Dir.pwd, Dir.pwd.swapcase)` is true for mri and false for jruby

i'm not sure if it's always the case yet

**Comment by headius** [comment]
PR coming that reorders to use native first. We'll see how it looks.
