### ISSUE TITLE
Ripper.sexp_raw returns a different value than C ruby

### ISSUE THREAD

**Issue by nabice** [jruby/jruby#7152]
JRuby Version: 9.3.3.0

An extra assign_error.

=============================
Ruby Code：
```
Object::A ||= 10
```
=============================

C Ruby output:
```
[:program,
 [:stmts_add,
  [:stmts_new],
  [:opassign,
   [:const_path_field,
    [:var_ref, [:@const, "Object", [1, 0]]],
    [:@const, "A", [1, 8]]],
   [:@op, "||=", [1, 10]],
   [:@int, "10", [1, 14]]]]]
```

JRuby output:
```
[:program,
 [:stmts_add,
  [:stmts_new],
  [:assign_error,
   [:opassign,
    [:const_path_field,
     [:var_ref, [:@const, "Object", [1, 0]]],
     [:@const, "A", [1, 8]]],
    [:@op, "||=", [1, 10]],
    [:@int, "10", [1, 14]]]]]]
```

**Comment by enebo** [comment]
I can see where this assign_error is coming from but the cause is from the code thinking it is in a method definition when it actually isn't.   We are releasing today and I don't want to try and force in a fix on this since it will take some deeper digging.
