### ISSUE TITLE
Ripper.sexp throws error while parsing 'ö'

### ISSUE THREAD

**Issue by nabice** [jruby/jruby#7153]
JRuby Version: 9.3.3.0
Code:
```
# -*- encoding: utf-8 -*-
require 'ripper'

Ripper.sexp("ö = 1")
```

Output:

```
EncodingError: invalid symbol in encoding US-ASCII :\xF6
```

**Comment by enebo** [comment]
I was concerned the fix in the PR was wrong until I checked.  I thought clean ASCII 7bit would be US-ASCII but it appears to honor #coding request anyways.
