### ISSUE TITLE
Encoding of string created from literal changes as side effect of ENV mutation

### ISSUE THREAD

**Issue by ivoanjo** [jruby/jruby#7166]
Hey hey! 👋 

As always, thanks for making JRuby awesome! I'm working on adding JRuby 9.3 to the [`ddtrace` gem CI](https://github.com/DataDog/dd-trace-rb) and ran into this really weird behavior 👀 

**Environment Information**
  
Provide at least:
* JRuby version: `jruby 9.3.4.0 (2.6.8) 2022-03-23 eff48c1ebf OpenJDK 64-Bit Server VM 11.0.14.1+1 on 11.0.14.1+1 +jit [x86_64-linux]`
* Operating system and platform: `Linux docker-desktop 5.10.104-linuxkit #1 SMP Wed Mar 9 19:05:23 UTC 2022 x86_64 GNU/Linux`

**Expected Behavior**

Testcase:

```ruby
puts RUBY_DESCRIPTION

utf8 = ''.encode(::Encoding::UTF_8).freeze
puts utf8.encoding

ENV['FOO'] = ''

puts utf8.encoding
```

When executed in the `jruby:9.3.4.0-jre11` docker image with `LANG=en_US.UTF-8`, e.g.:

```
$ docker run -ti -v `pwd`:/working jruby:9.3.4.0-jre11 /bin/bash
root# LANG=en_US.UTF-8 jruby working/encoding_bug.rb
jruby 9.3.4.0 (2.6.8) 2022-03-23 eff48c1ebf OpenJDK 64-Bit Server VM 11.0.14.1+1 on 11.0.14.1+1 +jit [x86_64-linux]
UTF-8
US-ASCII
```

This doesn't happen if don't change `LANG`. It also doesn't happen on 9.2, but seems to be there already in 9.3.0.0 so somewhere in the 9.3 work this bug came about.

**Comment by headius** [comment]
Likely that some shared ByteList instances are getting modified directly by ENV when they should not be.

**Comment by headius** [comment]
I pushed #7167 which seems to fix this, but we should audit the related code to see where along the way CRuby dups the incoming value string (and avoid doing it too much when we do not need to).

**Comment by ivoanjo** [comment]
Thanks for looking into this! 👍🙇
