### ISSUE TITLE
Wrong ELF

### ISSUE THREAD

**Issue by monkstone** [jruby/jruby#7170]
<!--

=->

jruby 9.3.3.0 (2.6.8) 2022-01-19 b26de1f5c5 OpenJDK 64-Bit Server VM 17.0.3+3 on 17.0.3+3 +jit [linux-x86_64]

  
get

jruby -S tar xzvf ~/Downloads/jruby-dist-9.3.4.0-bin.tar.gz ./
SyntaxError: /usr/bin/tar:1: Invalid char `\x7f' in expression

**Comment by headius** [comment]
Wrong ELF?!
