### ISSUE TITLE
Running Rails 7

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7175]
A checklist of issues to fix to get Rails 7 working. Additional items will be added as needed.

* [x] release patched net-http gem that feature-checks missing parts of jruby-openssl (https://github.com/ruby/net-http/pull/52)
* [x] release JRuby support for the strscan gem (https://github.com/ruby/strscan/pull/25)
* [x] release JRuby support for the stringio gem (does not get used during install or generate so far) (https://github.com/ruby/stringio/pull/21)
* [x] Fix argument delegation issue (https://github.com/jruby/jruby/issues/7174)

**Comment by headius** [comment]
Attaching prerelease gems of net-http and strscan based on the linked PRs:

* [net-http-0.2.0.gem.zip](https://github.com/jruby/jruby/files/8483261/net-http-0.2.0.gem.zip)
* [strscan-3.0.2-java.gem.zip](https://github.com/jruby/jruby/files/8483262/strscan-3.0.2-java.gem.zip)

**Comment by headius** [comment]
Preview releases of net-http, strscan, and stringio are now incorporated into JRuby, allowing Rails 7 to install without modification.

Unsure about the delegation issue, but it *may* be resolved by recent work from @enebo.

**Comment by enebo** [comment]
Adding some new stuff in this issue:

* [x] Update arjdbc CI to reflect jruby-head and Rails 7.
* [ ] Update sqlite3 to reflect API changes in Rails 7
* [ ] Update pg to reflect API changes in Rails 7
* [ ] Update mysql to reflect API changes in Rails 7
* [ ] Rails unit test pass (beyond activerecord handled by driver updates in arjdbc)(this will likely get expanded out)

**Comment by headius** [comment]
Rails is working pretty well, enough to scaffold and run a basic app. Only sqlite and mysql have adapters at the moment, and I'm not sure how complete they are.

**Comment by headius** [comment]
Punting remaining work to 9.4.1.
