### ISSUE TITLE
Spurious constant replacement warning when using include_package

### ISSUE THREAD

**Issue by ikaronen-relex** [jruby/jruby#7185]
When a Java class included in a module using `include_package` happens to share a name with a module in the global namespace, a spurious warning is emitted in verbose mode when the Java class is accessed via the including module for the first time.

**Test case**

```ruby
module Foo
  include_package 'java.util'
end

module ArrayList
end

Foo::ArrayList  # this line triggers the warning
```

**Expected behavior**

The code above runs with no warnings; `Foo::ArrayList` on the last line evaluates to `Java::JavaUtil::ArrayList`.

**Actual behavior**

The code runs correctly, but generates the following spurious warning:

> warning: replacing ArrayList with Java::JavaUtil::ArrayList in constant 'ArrayList on class/module Foo
 
(Also, the warning is misspelled, with an unmatched single quote before the constant name.)

**Environment information**
  
* JRuby version: 9.3.4.0

**Notes**

The warning comes from the following code in Java#setProxyClass:

https://github.com/jruby/jruby/blob/feb8fa4c86f42dea90a873ec1aa704d8c77b2857/core/src/main/java/org/jruby/javasupport/Java.java#L250-L254

Presumably the reason for the unexpected warning is that RubyModule#getConstantNoConstMissing behaves differently from what the code above expects, traversing the module hierarchy to see if the constant is accessible _from_ the target module instead of just checking whether the constant is already defined directly in the target module.

**Comment by headius** [comment]
Seems like this warning needs to be narrowed to just overriding a constant in the target module. Good find, thanks!

**Comment by headius** [comment]
I've pushed #7280 which simply removes this special logic and relies on `RubyModule#setConstant` to warn when overwriting on the target module itself. I'm not sure how much value there is in warning about "shadowing" constants higher up in the hierarchy or lexical scoping, and the behavior of `include_package` means that it will go ahead and overwrite anyway even if it warns.
