### ISSUE TITLE
jruby-openssl gem breaks PKCS5

### ISSUE THREAD

**Issue by headius** [jruby/jruby#719]
JRuby uses krypt to provide pkcs5, via require 'krypt/ossl' in lib/ruby/shared/openssl.rb. However, the jruby-openssl.rb file we load from the gem does not have this line, and so OpenSSL::PKCS5 is never defined.

A workaround is to require krypt/ossl yourself.

Proper gemification of jruby-openssl would fix this, as would simply adding the require to the gem's jruby-openssl.rb file, but we also need to ensure the depdency comes along for pre-1.7 JRuby (and we should probably be treating krypt as a default gem anyway).

Unsure of the status of gemification of krypt. Can you comment, @emboss?

**Comment by kares** [comment]
this is now obsolete with jruby-openssl **0.9.6** and since JRuby **1.7.20** will bundle 0.9.6 closing as resolved

**Comment by hathawad** [comment]
Just for clarity, if you are running into this issue w/ Rails, you need to add the `krypt` gem to your `GEMFILE` as the krypt jars are no longer part of the JRuby install.
