### ISSUE TITLE
Something changed from 9.2.x to 9.3.x that causes a SecurityException with access denied when using jruby as osgi-bundle

### ISSUE THREAD

**Issue by AlBundy33** [jruby/jruby#7216]
Unfortunately I can not provide a failing test-case - I can only try to describe my observations.

here is my test-script
```
$tool.logger.info("start... #{RUBY_VERSION} #{JRUBY_VERSION}")
for i in 1..100000 do
  begin
    java.lang.System.getProperty("foobar")
  rescue => e
    raise java.lang.IllegalStateException.new("error on loop index #{i}", e)
  end
end
$tool.logger.info("done")
```

as you can see the script only asks for the same property.

If I run this script in our RCP-application with
https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.2.20.1/jruby-complete-9.2.20.1.jar
all is working as expected.

If I run the same script in the same application with 
https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.3.4.0/jruby-complete-9.3.4.0.jar
we get an exception `access denied ("java.util.PropertyPermission" "foobar" "read")`

here is one of the stacktraces
```
...
           access denied ("java.util.PropertyPermission" "foobar" "read")
           java.security.AccessControlContext.checkPermission(java/security/AccessControlContext.java:472)
           org.eclipse.osgi.internal.permadmin.EquinoxSecurityManager.internalCheckPermission(org/eclipse/osgi/internal/permadmin/EquinoxSecurityManager.java:122)
           org.eclipse.osgi.internal.permadmin.EquinoxSecurityManager$CheckPermissionAction.run(org/eclipse/osgi/internal/permadmin/EquinoxSecurityManager.java:64)
           org.eclipse.osgi.internal.permadmin.EquinoxSecurityManager$CheckPermissionAction.run(org/eclipse/osgi/internal/permadmin/EquinoxSecurityManager.java:1)
           java.security.AccessController.doPrivileged(Native Method)
           org.eclipse.osgi.internal.permadmin.EquinoxSecurityManager.checkPermission(org/eclipse/osgi/internal/permadmin/EquinoxSecurityManager.java:93)
           org.eclipse.osgi.internal.permadmin.EquinoxSecurityManager.checkPermission(org/eclipse/osgi/internal/permadmin/EquinoxSecurityManager.java:196)
           java.lang.SecurityManager.checkPropertyAccess(java/lang/SecurityManager.java:1294)
           java.lang.System.getProperty(java/lang/System.java:719)
           java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
           org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:457)
           org.jruby.javasupport.JavaMethod.invokeStaticDirect(org/jruby/javasupport/JavaMethod.java:369)
           $_lt_script_gt_.invokeOther3:getProperty(<script>:9)
           $_lt_script_gt_.<main>(<script>:9)
           org.jruby.RubyInteger.fixnumUpto(org/jruby/RubyInteger.java:236)
           org.jruby.RubyRange.fixnumEach(org/jruby/RubyRange.java:629)
           org.jruby.RubyRange.each(org/jruby/RubyRange.java:599)
           org.jruby.RubyRange$INVOKER$i$0$0$each.call(org/jruby/RubyRange$INVOKER$i$0$0$each.gen)
           RUBY.<main>(<script>:5)
           org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:1294)
           org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:1298)
           org.jruby.embed.internal.EmbedEvalUnitImpl.run(org/jruby/embed/internal/EmbedEvalUnitImpl.java:119)
           org.jruby.embed.jsr223.JRubyEngine.doEval(org/jruby/embed/jsr223/JRubyEngine.java:97)
           org.jruby.embed.jsr223.JRubyEngine.eval(org/jruby/embed/jsr223/JRubyEngine.java:124)
           org.jruby.embed.jsr223.JRubyEngine.eval(org/jruby/embed/jsr223/JRubyEngine.java:140)
...
```

becuase this exception does not occur with jruby 9.2.20.1 i think this is an issue of jruby rather than equinox.
The exception occurs always on different indexes - somtimes 324, next time 932, ...

As mentioned before I was not able to reproduce this in a unit-test (without osgi) - but I can reproduce it always in our application.

Hopefully these are enough informations to find the problem.

Feel free to ask if you need more informations.

**Comment by headius** [comment]
cc @splatch

**Comment by splatch** [comment]
@headius thanks for pointer. @AlBundy33 It looks like security manager is your problem, can you check its configuration? I haven't done much with equinox security manager, but you call `System.getProperty` which is constrained with Java Security Manager turned on. For OSGi part you need bundle to declare permissions it wants - probably jruby or someone who calls it should do it.
Check this part https://docs.osgi.org/specification/osgi.core/7.0.0/service.permissionadmin.html, for equinox - I have no clue where to look for documentation of particular component which raises exceptions.

**Comment by AlBundy33** [comment]
But why does it work with jruby 9.2.20.1?
This error occurs only with 9.4

**Comment by headius** [comment]
I happened upon this bug report again so I took a closer look.

I am really baffled what might have changed in JRuby to cause this. It's a simple `getProperty` from Ruby code that seems to eventually fail a security check for accessing this property. It smells like a JDK bug to me...except that doesn't explain why it works in 9.2.20.1.

**Comment by headius** [comment]
I think this may be due to the JIT now being able to compile blocks independent of their surrounding method.

The property security check here basically tries to walk up the stack looking for the first class that has a non-null protection domain. Without JIT here, all classes are either the JDK or JRuby, both loaded from the system classloader without a protection domain. The new code generated by JRuby's JIT, on the other hand, is runtime-loaded code, and if I read this JDK ClassLoader code correctly it gets a default protection domain. That default domain is probably fairly limited and not allowing the property read.

The trigger is that between 9.2.20.1 and 9.4, we taught JRuby how to JIT blocks on their own. Previously, this `for` loop block would never have compiled because the rest of the script is interpreted and only called once.

I am not sure how to fix this. I don't know if there's a way to load bytecode at runtime without assigning it a ProtectionDomain of some kind. It will need more research.

As a workaround, you could force all JRuby scripts to remain interpreted by tweaking RubyInstanceConfig:

```java
config.setCompileMode(RubyInstanceConfig.CompileMode.OFF);
```

Sadly, even if we fix this somehow, the entire Java security subsystem is being removed in a future version.

**Comment by AlBundy33** [comment]
according to my notes the original-issue occured also in a loop.

Is JRuby 9.2 also using the JIT compiler?
Are there any impacts disabling the JIT-compiler?
We are using jruby to customize our application - to the executed scripts are not that big.

**Comment by headius** [comment]
JRuby 9.2 has the same JIT but cannot compile looping blocks unless the code around it also compiles. There should be no impact from disabling the JIT other than slower performance, but depending on what your scripts were doing they may have been running in the interpreter anyway.

**Comment by AlBundy33** [comment]
Can I check what is compiled or interpreted?

**Comment by headius** [comment]
Yes, running with JVM property "jruby.jit.logging=true" will output everything it compiles to stderr.

**Comment by AlBundy33** [comment]
@headius thanks for your support so far - is this your expected output/behavior?

**Comment by AlBundy33** [comment]
I've always wanted to try `git bisect` and played a litte bit with git and rcp sample applications. 😄 
If I have done everything correctly the is the commit that introduced the bug.
```
e352ba8265dd773fd341e8d6bbd0583540b119bd is the first bad commit
commit e352ba8265dd773fd341e8d6bbd0583540b119bd                                                       Author: Charles Oliver Nutter <headius@headius.com>
Date:   Wed Sep 2 17:28:29 2020 -0500

    Be sure to resolve class after defining

    This method is only provided for us to define a generated class                                       that we intend to immediately use, so we should also force the
    class to resolve.

 core/src/main/java/org/jruby/runtime/scope/DynamicScopeGenerator.java | 4 +++-                        core/src/main/java/org/jruby/util/OneShotClassLoader.java             | 4 +++-
 2 files changed, 6 insertions(+), 2 deletions(-)
bisect run success
```

**Comment by headius** [comment]
@AlBundy33 I would like to find a fix for this so your bisect is helpful. There may be a way we can specify that the jit compiled code loads with a protection domain no more restrictive than the one into which JRuby was loaded.

Turning off the jit is just an easy workaround for now.

**Comment by AlBundy33** [comment]
@headius also check my last post (I did some edits).
Calling super.defineClass with ClassDefiningJRubyClassLoader.DEFAULT_DOMAIN seems to fix the issue.
Two classes in the commit have changed but in only one the last srgument was removed so maybe that was by accident.

Disabling the JIT-compiler seems to be a workaround - for now we are using jruby 9.2.

thank you for staying tuned 👍

**Comment by AlBundy33** [comment]
@headius any news about this problem?
I assume the change in line 20 causes the problems
https://github.com/jruby/jruby/commit/e352ba8265dd773fd341e8d6bbd0583540b119bd

**Comment by headius** [comment]
Sorry about no follow up in so many months! I'm catching back up again so we can find a fix.
