### ISSUE TITLE
Empty rescue block returns exception object instead of nil

### ISSUE THREAD

**Issue by ivoanjo** [jruby/jruby#7218]
**Environment Information**
  
Provide at least:
* JRuby version: `jruby 9.3.4.0 (2.6.8) 2022-03-23 eff48c1ebf OpenJDK 64-Bit Server VM 11.0.14+9-LTS on 11.0.14+9-LTS [x86_64-darwin]`
* Operating system and platform: `Darwin ivoanjo-COMP-C02DT18AML87 20.6.0 Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64 x86_64 i386 Darwin`

**Expected Behavior**

Testcase:

```ruby
puts RUBY_DESCRIPTION

def handle_failure_and_return_nothing
  File.open('does-not-exist')
rescue StandardError => _e
  # do nothing
end

puts handle_failure_and_return_nothing.inspect
```

Here's what I get on MRI:

```
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin20]
nil
````

**Actual Behavior**

Here's what I get on JRuby:

```
jruby 9.3.4.0 (2.6.8) 2022-03-23 eff48c1ebf OpenJDK 64-Bit Server VM 11.0.14+9-LTS on 11.0.14+9-LTS [x86_64-darwin]
#<Errno::ENOENT: No such file or directory - does-not-exist>
```

Removing the `=> _e` on the original code seems to do the trick, since it wasn't using it anyway, but yeah it took a bit to figure out what was going on :)

**Comment by headius** [comment]
Wow that is a weird one to be broken without us noticing!

This is broken in at least 9.3 and 9.4 HEAD.

**Comment by headius** [comment]
This appears to be an IR bug, possibly a premature optimization of empty bodies.

The logic around here in IRBuilder appears to try to skip some logic when the body does not have an explicit return value:

https://github.com/jruby/jruby/blob/fbf83daa87e7720e661863b01be98496166ea3e1/core/src/main/java/org/jruby/ir/IRBuilder.java#L3833-L3841

However it ignores the fact that in this case, the exception is being captured into a specific variable, and still overwrites the return value `rv` before branching to the end of the logic.

I believe this should simply nil out `rv` and then branch, but I'm not sure of the implications.

**Comment by ivoanjo** [comment]
Thanks for the awesome diagnostic and fix! :)
