### ISSUE TITLE
JarCache still slow at startup in several Windows environments

### ISSUE THREAD

**Issue by DirkMahler** [jruby/jruby#7225]
**Environment Information**
  
* JRuby version: 9.2.20.1 (including latest 9.2.21.0-SNAPSHOT)
* Operating system: Windows 10

**Expected Behavior**

* Startup of jQAssistant/AsciidoctorJ which makes use of JRuby should be a matter of milliseconds or at most seconds

**Actual Behavior**

* The issue which had been fixed in #6730 re-appeared in virtualized, highly secured corporate Windows environments of a customer, startup again takes 5-8 minutes

**Possible Solution**

* The solution in #6730 was to reduce the amount of expensive File.lastModified calls in JarCache by introducing a grace-period of 500ms between checks (see https://github.com/jruby/jruby/blob/jruby-9.2/core/src/main/java/org/jruby/util/JarCache.java#L45). I verified that increasing the value to 750ms or 1s solves the issue again and I can provide an according PR. The question is if this value should be made configurable.

**Comment by DirkMahler** [comment]
@enebo Shall I close this ticket as the PR has been merged?

**Comment by enebo** [comment]
@DirkMahler I didn't realize it hadn't been.  Thanks for pinging.
