### ISSUE TITLE
Changing method visibility changes behavior for module-inherited methods

### ISSUE THREAD

**Issue by NC-piercej** [jruby/jruby#7240]
**Environment Information**
  
- JRuby 9.3.4.0
- `jruby:9.3.4.0-jre11` docker image

**Expected Behavior**

Here is an example of how CRuby behaves (2.7.5):

<img width="368" alt="Screen Shot 2022-06-09 at 11 26 51 AM" src="https://user-images.githubusercontent.com/17504011/172897292-7a17f906-b600-4314-a1de-1b44a0398fcf.png">

As we can see, method visibility changed, but behavior did not.

**Actual Behavior**

Here is what happens for the same example on JRuby:

<img width="449" alt="Screen Shot 2022-06-09 at 11 23 27 AM" src="https://user-images.githubusercontent.com/17504011/172896665-c04371fa-e32e-42f0-8ef4-815d7d5faf92.png">

Here, the behavior of the method unexpectedly changed after it was made public, preferring the signature of the first module that was overridden by the signature of the second.

**Comment by NC-piercej** [comment]
Issue is still present in `9.3.6.0`:

<img width="461" alt="Screen Shot 2022-06-30 at 3 57 22 PM" src="https://user-images.githubusercontent.com/17504011/176777082-a228ade5-49d6-4eaf-949d-34866ad1e8a3.png">

**Comment by headius** [comment]
Thank you for the report. It seems our aliasing logic is not quite matching CRuby here, or else the search for a method to make `public` is finding the wrong one (the `A` version rather than the `B` version.

**Comment by NC-piercej** [comment]
Confirmed that the issue is still present in `9.3.7.0`:

<img width="470" alt="Screen Shot 2022-08-19 at 1 28 27 PM" src="https://user-images.githubusercontent.com/17504011/185683876-932295fc-7cf7-4559-bd85-0a1dfda1397e.png">

**Comment by evaniainbrooks** [comment]
```
irb(main):023:0> C.instance_method(:derp).super_method
=> #<UnboundMethod: A#derp>
irb(main):024:0> C.send(:public, :derp)
=> C
irb(main):025:0> C.instance_method(:derp).super_method
=> #<UnboundMethod: B#derp>
```
Changing the visibility of the method as above creates an instance of `PartialDelegatingMethod` on C. It looks like what is happening is: now when we go to look up `super` we are incorrectly starting at C, ascending into B and stopping (method found).

There is some missing logic for handling `PartialDelegatingMethod` it seems, but I haven't quite figured out what that is yet.

**Comment by headius** [comment]
Thank you!

**Comment by eregon** [comment]
FYI the added specs checking `owner` behavior differently on 3.2: https://github.com/ruby/spec/commit/8b5acc9cb5be163b1067f7839b692a1e093d4723
It's due to CRuby < 3.2 skipping zsuper methods for `Kernel#method` and `Module#instance_method` and that's finally fixed.
