### ISSUE TITLE
[Q] About Found multiple supers in java ctor

### ISSUE THREAD

**Issue by hiroyuki-sato** [jruby/jruby#7241]
Hello, members. 

Could you tell me the detail `Found multiple supers in java ctor` message?
https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby#subclassing-a-java-class
Because I need to refactor the following code.

* JRuby version: 9.3.4.0
* Operating system and platform: macOS 12.3.1

```ruby
class ConfigError < Java::Config::ConfigException 
  def initialize(message=nil) 
    if message 
      super(message.to_s) 
    else 
      super() 
    end 
  end 
end 
```

#### 1. `Found multiple supers in java ctor` means

Does this mean the following? Is this correct?

NG. Can't call super twice in the initialize method.

```ruby
class ConfigError < Java::Config::ConfigException 
  def initialize(message=nil) 
    if message 
      super(message.to_s) 
    else 
      super() 
    end 
  end 
end 
```

OK: `super` call just once in the constructor.

```ruby
class ConfigError < Java::Config::ConfigException 
  def initialize(message=nil) 
    super(message.to_s) 
  end 
end 
``` 

#### 2. What constructor will call?

In the following code, there are two constructors.
I would like to know what method will call from JRuby subclasses.
Especially `null` behavior.

```java
package com.github.hiroyuki_sato;
public class JRubyTest {

  private String msg;
  public JRubyTest() {
    System.out.println("no args");
    this.msg = "default";
  }

  public JRubyTest(String msg) {
    System.out.println(msg);
    this.msg = msg;
  }

  public String hello(){
    return this.msg;
  }
}
```

```ruby
$CLASSPATH << "/path/to/test"
java_import "com.github.hiroyuki_sato.JRubyTest"

class Foo  < Java::ComGithubHiroyuki_sato::JRubyTest
  def initialize
    super
  end
end

class Bar < Java::ComGithubHiroyuki_sato::JRubyTest
  def initialize
    super("test")
  end
end

class Baz < Java::ComGithubHiroyuki_sato::JRubyTest
  def initialize
    super(nil)
  end
end

class Qux  < Java::ComGithubHiroyuki_sato::JRubyTest
  def initialize(msg=nil)
    super(msg)
  end
end

b = Foo.new
puts b.hello()
puts "-------------"

b = Bar.new
puts b.hello()
puts "-------------"

b = Baz.new
puts b.hello()
puts "-------------"

b = Qux.new("test test")
puts b.hello()
puts "-------------"

b = Qux.new(nil)
puts b.hello()
puts "-------------"
```

I summarized the tests. Does this result correct? And does `nil` always convert to empty strings?

| method              | call `super` in Ruby subclass        | be called Java class          |
|---------------------|------------------------------|----------------|
| initialize          | super                        | JRubyTest() |
| initialize          | super("test")                | JRubyTest("test") |
| initialize          | super(nil)                   | JRubyTest("null") ?? |
| initialize(msg=nil) | super(msg) # msg="test test" | JRubyTest("test test") |
| initialize(msg=nil) | super(msg) # msg=nil         | JRubyTest("null") ?? |

Best regards.

**Comment by enebo** [comment]
@hiroyuki-sato as it stands because we are directly extending Java classes from Ruby now (and not using a proxy class internally) initialize must follow the same rules as a java constructor.  super must be the first statement in the generated code.  This means we cannot support more than one super.

For your second question passing any value to Java will first use arity for resolution.  You have two constructors with arity 0 and 1.  Passing nil is still passing 1 argument so it will call the method with arity 1.  You are printing out the string value but the nil is being made into a java null which is ok in Java to be a String.  println is printing "null" for null.

You might be able to do something like

```ruby
def intiialize(*args)
   super
end
```

This will solve the arity issue.  If you plan on doing more with message then you pull message out of args after the super call.

**Comment by hiroyuki-sato** [comment]
Hello, @enebo.
Thank you for your reply.

Let me double-check, I understood the following.
I need to care about the number of an arity in the **Ruby method**, correct?

```ruby
#
# arity 0
#
class Foo  < Java::ComGithubHiroyuki_sato::JRubyTest
  def initialize
    super
  end
end

#
# arity 1
#
class Bar < Java::ComGithubHiroyuki_sato::JRubyTest
  def initialize(msg=nil)
    super
  end
end
```


| method              | arity  | parent method(super)  |
|---------------------|--------|-----------------------|
| initialize          | 0      | JRubyTest()           |
| initialize(msg=nil) | 1      | JRubyTest(String msg) |

And the following code solves arity issue.

```ruby
def intiialize(*args)
   super
end
```

Best regards.

**Comment by hiroyuki-sato** [comment]
Hello, @enebo.
Thank you for your comment.

I confirmed that `super` and `super()` don't same behavior.
A Ruby method with one arity like `initialize(msg=nil)`,
`super()` call `JRubyTest()` and `super`(without`()`) call `JRubyTest(String msg)`
I thought both methods work the same.

```java
package com.github.hiroyuki_sato;
public class JRubyTest {

  private String msg;
  public JRubyTest() {
    System.out.println("no args");
    this.msg = "default";
  }

  public JRubyTest(String msg) {
    System.out.println(msg);
    this.msg = msg;
  }

  public String hello(){
    return this.msg;
  }
}
```

```ruby
$CLASSPATH << "/path/to/dir"
java_import "com.github.hiroyuki_sato.JRubyTest"

class Foo  < Java::ComGithubHiroyuki_sato::JRubyTest
  def initialize
    super
  end
end

class Bar < Java::ComGithubHiroyuki_sato::JRubyTest
  def initialize(msg=nil)
    super()
  end
end

class Boo < Java::ComGithubHiroyuki_sato::JRubyTest
  def initialize(msg=nil)
    super
  end
end

b = Foo.new
puts b.hello()
puts "-------------"

b = Bar.new
puts b.hello()
puts "-------------"

b = Boo.new
puts b.hello()
puts "-------------"
```

```
load "test2.rb"
no args
default
-------------
no args
default
-------------
null

-------------
=> true
```

**Comment by enebo** [comment]
@hiroyuki-sato I think this is perhaps the most confusing feature of Ruby.  super without parens in implementations is referred to as zsuper.  zsuper as you have shown will just pass any arguments passed to the original method to super.  If you put parens after super then you are controlling which parameters you pass.

Here is a fun one:

```ruby
def foo(a=1, b=2)
  b = 3
  super
end

foo
```

The important bit to take away in this example is the zsuper is translated into super(a, b) which will end up being super(1, 3).  So the actual variable is what is referenced by zsuper and not the values passed into foo.

**Comment by hiroyuki-sato** [comment]
Helo, @enebo. Thank you for your comment!
I understood that It's a Ruby feature, not JRuby specific feature.
