### ISSUE TITLE
Wrong number of arguments error raised when calling java functional interface method with a block

### ISSUE THREAD

**Issue by robbavey** [jruby/jruby#7246]
When attempting to call a method accepting a Java functional interface as parameter, this sometimes fail in `Jruby-9.3.4.0` (and `jruby-9.3.0.0` with a `ArgumentError: wrong number of arguments (given 0, expected 1)` raised.

```
➜  jruby ruby --version
jruby 9.3.4.0 (2.6.8) 2022-03-23 eff48c1ebf OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +jit [x86_64-darwin]
➜  jruby JRUBY_OPTS="-Xcompile.invokedynamic=true" ruby -e 'a = java.util.ArrayList.new;a.add("1");a.add("2");a.forEach{|d|b = java.util.ArrayList.new;b.add("3");b.forEach{|e| puts e}}'
3
ArgumentError: wrong number of arguments (given 0, expected 1)
  <main> at -e:1
  <main> at -e:1
```

This did not happen with `jruby-9.2.x`:

```
➜  jruby ruby --version                                  
jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +jit [darwin-x86_64]
➜  jruby JRUBY_OPTS="-Xcompile.invokedynamic=true" ruby -e 'a = java.util.ArrayList.new;a.add("1");a.add("2");a.forEach{|d|b = java.util.ArrayList.new;b.add("3");b.forEach{|e| puts e}}'
3
3
```

It only appears to occur when `compile.invokedynamic` is set, if the first array list only has a single value, and if the "inner" array list is present.

**Comment by kares** [comment]
this will obviously concern any Java method with a functional interface being implemented with a block.
the `forEach` nesting is not a concern, which could be demonstrated by this simplified reproducer:
`jruby -Xcompile.invokedynamic -e '2.times { java.util.ArrayList.new([1]).forEach { |e| p e } }'`

**Comment by headius** [comment]
I think this is the problematic line:

https://github.com/jruby/jruby/blob/b12e5a6fc2cd4140469215fe87e479cf050ee5a7/core/src/main/java/org/jruby/ir/targets/indy/Bootstrap.java#L694

To optimize argument passing a bit more, this logic drops the block when the target method does not need it. But in this case, with a Java receiver, it does not consider that there may be an interface that assumes the block.

So this is another place to skip specialized binding when the receiver is a Java method. We will reoptimize all Java paths in the next major version.
