### ISSUE TITLE
Undefined constants when including a module that has been prepended

### ISSUE THREAD

**Issue by tannalynn** [jruby/jruby#7256]
**Environment Information**
 - `jruby 9.3.4.0 (2.6.8) 2022-03-23 eff48c1ebf Java HotSpot(TM) 64-Bit Server VM 14.0.1+7 on 14.0.1+7 [x86_64-darwin]`
- `Darwin  21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64`

**Expected Behavior**
When a module defines a constant (and has been prepended) is included in a class, accessing that constant through the class should be able to grab the value of the constant.
I tested this behavior on several versions of ruby between 2.3.8 up to 3.1.1, and CRuby is consistently able to use the constant without errors.

Running this snippet of code reproduces the issue.

```
module PrependTest
  def foo
    nil
  end
end

module Foobar
  prepend PrependTest
  TESTCONSTANT = "bar"
  def foo
    nil
  end
end

class Bar
  include Foobar
  def test
    nil
  end
end

Foobar::TESTCONSTANT # no error
Bar::TESTCONSTANT # error
```

**Actual Behavior**
When a module that has a constant defined, and has been prepended, is included in a class, `NameError: uninitialized constant` is thrown when accessing that constant through the class.
Using jruby to run the code snippet above results in 
```
NameError: uninitialized constant Bar::TESTCONSTANT
  const_missing at org/jruby/RubyModule.java:3948
         <main> at ./ruby_test_const.rb:23
```

**Comment by nonlandi** [comment]
We could also reproduce this issue with `jruby-9.2.20.1`

**Comment by headius** [comment]
Good find, thank you. We will look into it.

**Comment by kares** [comment]
already fixed in JRuby 9.3.7.0 but for now I marked this for 9.2.22.0 (as there's been some discussion this might be considered)
... assuming the backport would be easy.

**Comment by headius** [comment]
JRuby 9.2.22.0 becomes less likely to happen with each passing day. We have stopped pushing new Docker images for 9.2.x and there's very little demand for additional maintenance releases along that line.

We might consider just pushing release bits for a JRuby 9.2.22.0, but only if JRuby users do the footwork to pull together new backport pull requests. Our focus will be on mainaining 9.3 and 9.4.

**Comment by enebo** [comment]
If someone finds another 9.2 release extremely important then please reopen this issue and we can discuss this but we are not planning on any more 9.2 releases.
