### ISSUE TITLE
v9.3.6 incompatible with v9.3.4

### ISSUE THREAD

**Issue by kedar-joshi** [jruby/jruby#7261]
Upgrading JRuby to v9.3.6 from v9.3.4 results in following exception with ASCII doctor -

```
Execution generate-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:2.2.1:process
-asciidoc failed: An API incompatibility was encountered while executing org.asciidoctor:asciidoctor-maven-plugin:2.2.1:process-asciidoc: java.lang.NoSuchMethodError: 'void org.jruby.gen.org$jruby$RubyModule$ModuleKernelMethods$
POPULATOR.populateMethod(org.jruby.internal.runtime.methods.JavaMethod, int, java.lang.String, boolean, boolean, java.lang.Class, java.lang.String, java.lang.Class, java.lang.Class[])'
```

**Environment Information**
  
Provide at least:
* JRuby version : **v9.3.6**
* Operating system and platform : **Windows 10 x64**

**Expected Behavior**

Bugfix releases should not break binary compatibility.

**Actual Behavior**

Upgrading to v9.3.6 from v9.3.4 breaks compatibility.

**Comment by pzygielo** [comment]
I was about to report the same just now.

**Comment by headius** [comment]
There are only two ways I could see this happening.

The first would be a bad build, which would never have gotten past verification before release. This particular method is run at every boot and we would never be able to start up without it.

The second would be a version conflict in the asciidoctor Maven plugin causing it to use a mix of old and new JRuby classes.

If a download of the JRuby distribution tarball or one of the maven artifacts does not exhibit this error on startup then it must be a version conflict of some sort.

**Comment by pzygielo** [comment]
> The second would be a version conflict in the asciidoctor Maven plugin causing it to use a mix of old and new JRuby classes.

I'm not yet sure where it is coming from (there is version conflict 9.3.6.0 vs 9.2.20.1 for `jruby-core` indeed), but adding following, with the same version as `jruby-complete`:
```diff
             <plugin>
                 <groupId>org.asciidoctor</groupId>
                 <artifactId>asciidoctor-maven-plugin</artifactId>
                 <dependencies>
+                    <dependency>
+                        <groupId>org.jruby</groupId>
+                        <artifactId>jruby-core</artifactId>
+                        <version>${jruby.version}</version>
+                    </dependency>
                     <dependency>
                         <groupId>org.jruby</groupId>
                         <artifactId>jruby-complete</artifactId>
                         <version>${jruby.version}</version>
                     </dependency>
```
helps in my case.

**Comment by pzygielo** [comment]
Moreover - only switching from `jruby-complete` to `jruby` works even better.
<sup>How did dependency to `jruby-complete` instead of `jruby` find the way to my project??? But it was plugin setup on my side to blame, I belive.</sup>

**Comment by headius** [comment]
@pzygielo So you believe it is working for you with the right dependency in pom?

@kedar-joshi Have you been able to investigate this, or look at @pzygielo's solution? I am pretty sure this is a version conflict somewhere in your build.

**Comment by pzygielo** [comment]
> @pzygielo So you believe it is working for you with the right dependency in pom?

Yes, it is, thank you!

**Comment by kedar-joshi** [comment]
> @kedar-joshi Have you been able to investigate this

Yes. Apparently **asciidoctor-maven-plugin** switched from using **jruby-complete** to **jruby** dependency since commit https://github.com/asciidoctor/asciidoctor-maven-plugin/commit/53d2cffb. However, [examples](https://github.com/asciidoctor/asciidoctor-maven-examples/blob/187c376da6606e744781b04d7187c4aebc56dc7a/asciidoctor-pdf-example/pom.xml#L37) still use **jruby-complete** dependency. This means dependency management method suggested in examples is actually cause dependency conflict.

As suggested by @pzygielo, using **jruby** dependency instead **jruby-complete** works.

**Comment by headius** [comment]
Good news then! Thank you all for confirming!
