### ISSUE TITLE
simple timeout script does not work

### ISSUE THREAD

**Issue by k77ch7** [jruby/jruby#7279]
**Environment Information**
  
Provide at least:
* JRuby version
```
jruby 9.4.0.0-SNAPSHOT (3.1.0) 2022-07-31 d56b25a38b OpenJDK 64-Bit Server VM 11.0.15+0 on 11.0.15+0 +jit [arm64-darwin]
```

* Operating system and platform (e.g. `uname -a`)
```
Darwin Mac-mini 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
```

* script from test/jruby/test_timeout.rb
```ruby
require "timeout"

n = 10000000
Timeout.timeout(0.1) { for i in 0..n do; (i + i % (i+1)) % (i + 10) ; end }

```

**Expected Behavior** ;mri 3.1.2
```
timeout_sample.rb:4:in `block (2 levels) in <main>': execution expired (Timeout::Error)
        from timeout_sample.rb:4:in `each'
        from timeout_sample.rb:4:in `block in <main>'
        from /Users/kiichi/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/timeout.rb:123:in `timeout'
        from timeout_sample.rb:4:in `<main>'
```

**Actual Behavior** ;JRuby head
Timeout::Error does not appear

If you add `puts "finish"` to script last line, Timeout::Error appears.
```ruby
require "timeout"

n = 10000000
Timeout.timeout(0.1) { for i in 0..n do; (i + i % (i+1)) % (i + 10) ; end }
puts "finish"
```

```
Timeout::Error: execution expired
   write at org/jruby/RubyIO.java:1533
   write at org/jruby/RubyIO.java:1466
   write at org/jruby/RubyIO.java:2807
    puts at org/jruby/RubyIO.java:2650
    puts at org/jruby/RubyKernel.java:603
  <main> at timeout_sample.rb:5
```

I believe green in GHA will increase when this is solved.

**Comment by headius** [comment]
It seems like the error is being created and set into `$!` but never raised. This could be a bug in the new implementation of timeout (the pure-Ruby version added in 0.3.0 based on Rubinius's version).

**Comment by headius** [comment]
I think this is a simpler matter... the Range logic for `each` does not check for thread events, so this particular script does not check for an asynchronous exception. Adding IO anywhere in the loop or after the timeout does finally see the asynchronous exception.

This is fixable by modifying the Range `each` loops to check for thread events after each iteration. That will have some performance impact, but I don't think it is avoidable.

**Comment by headius** [comment]
I pushed a fix that adds thread polls to all the loop forms reachable from `Range#each`, but this might be overkill. The duck-typed paths, for example, do additional calls like `succ` that should trigger thread polling in other ways.

**Comment by headius** [comment]
Thanks again for your help!
