### ISSUE TITLE
Oddity with the jruby parser: it warns me about "warning: found = in conditional, should be =="

### ISSUE THREAD

**Issue by rubyFeedback** [jruby/jruby#7317]
Today I am playing around with jruby + swing, trying to make the default GUI easier to work
with. I did so with ruby-gtk3 before.

Anyway.

I was surprised that jruby complained about the following code - I condensed this onto a 
single line:

    elsif (result = `md5sum bogus 2>&1`) and !result.include?('command not found')

The warning jruby showed me was this:

    /home/Programs/Jruby/9.3.6.0/lib/ruby/2.6/site_ruby/rbt/cookbooks/sanitize_cookbook/misc.rb:2289:
    warning: found = in conditional, should be ==

So ... my ruby knowledge may be incomplete. But if I understand my own code correctly
then I first assign to a local variable result, and then I test on the result of it via the
!result.include?() part. So this is fine ruby, yes? Nothing wrong there. Why does the
jruby parser complain about it, and specifically tell me "it should be == instead? I
think that recommendation by jruby is actually wrong. Either way it should not try
to lecture me and tell me what ielse should be used anyway really, even more so
when the code as it is works fine. The regular ruby parser does not complain about
it.

I don't know the internals of jruby, so I can not recommend how to change this
behaviour but I would change it. I understand the rationale that you want to 
prevent accidental use of = when people really meant ==, but it is not always
a true claim that is made here. Perhaps the parser should check in the AST 
(or whatever else is used) if the variable is used in the very same conditional
check, and if so then use a use case that fits to this here. Anyway it is not
a problem, it is just a warning, but IMO the warning is wrong/incorrect. I
report this just in case someone wants to have a look at. I could also be 
wrong but if so then you have to explain why that code is wrong, because I
think it is perfectly ok. (I could initialize result = before the if/else clause,
but I wanted to be succinct and I needed it only on that particular 
elsif line).

**Comment by enebo** [comment]
Interestingly we have the same code as MRI but we have a bug in our isStaticContent implementation.  The pattern this is meant for is:

```ruby
if value = true 
end
```

It actually will do this for lots of types hashes/arrays/true/nil/false.  Your code is creating `` which is a DXStr.  This apparently is not a literal type so it will not warn.  The parser will only do this on literals used in assignments in if's so I guess most people who do assignments in conditionals will never see this warning:

```ruby
if true
elsif (result = {a: 1}) and !result.include?('command not found')
end
```
