### ISSUE TITLE
IRB completion causes error

### ISSUE THREAD

**Issue by ccutrer** [jruby/jruby#7323]
Newer version of IRB have an autocomplete feature (I.e. 1.4.1). Unfortunately, if you use this under JRuby, it quickly explodes, because they use ObjectSpace to find all Modules that are active, and look at their instance_methods. But Java::JavaPackage instances are modules, but they go to great pains to remove almost all methods to make java-like access to packages possible. Including instance_methods. I'm not sure of the best approach to fixing this. I've solved it in pure Ruby in my irbrc, but it would probably be best implemented in Java in JRuby proper -- which wouldn't have the disadvantage of some of the gymnastics I have to do to locate and call the correct module and methods. I even went so far as to look up known java packages so that the completions might actually be useful.

My code:

```ruby
# this callback will be called; but has been removed; don't explode it
java.class.define_singleton_method(:method_added) { |_| nil }

java.class.define_singleton_method(:instance_methods) { |_| [] }

# this is not the right module, but we still want to use it for namespacing
# purposes
module Java
  module JavaPackage
    symbol_methods = %w[? !].freeze
    comparison_methods = %w[< = >].freeze
    INHERITED_INSTANCE_METHODS = (%i[
      class
      superclass
      singleton_class
      object_id
      name
      const_set
      singleton_method_added
      singleton_method_undefined
      singleton_method_removed
      define_singleton_method
    ] + java.__methods__.select do |m|
          m = m.to_s
          symbol_methods.include?(m[-1]) || comparison_methods.include?(m[0]) || m.start_with?("__")
        end).freeze
    INSTANCE_METHODS = %i[
      package_name
      to_s
      inspect
      const_missing
      const_get
      respond_to?
      respond_to_missing?
      method_missing
      available?
      sealed?
    ].freeze

    # can't call class_eval directly, so rebind to call it on the correct instance
    Module.instance_method(:class_eval).bind(java.class).call do
      def instance_methods(*args)
        return method_missing(:instance_methods, *args) unless args.length == 1

        @instance_methods ||= (::Kernel.java.lang.Package.packages
            .map(&:name)
            .select { |p| p.start_with?("#{package_name}.") && p != package_name }
            .map { |p| p[(package_name.length + 1)..].split(".").first.to_sym }
            .uniq + INSTANCE_METHODS).freeze
        return @instance_methods if args.first == false

        @inherited_instance_methods ||= (@instance_methods + INHERITED_INSTANCE_METHODS).freeze # rubocop:disable Naming/MemoizedInstanceVariableName
      end
    end
  end
end
```

**Comment by byteit101** [comment]
FWIW I initially noticed this nearly a year ago and after some consultation with @headius filed it over at the IRB repo as https://github.com/ruby/irb/issues/295 Though I suppose it's good to have an issue in both places

**Comment by ccutrer** [comment]
I initially was going to go for a fix in IRB, but decided that jruby was violating the interface for Module, so the fix should go here. That said IRB is still doing uncommon things (using ObjectSpace to find things), and it shouldn't crash the entire process if an autocomplete lookup throws an error. So yeah, +1 having it in both places

**Comment by headius** [comment]
The JavaPackage modules definitely violate a lot of Ruby standards by removing those methods, but we have been reluctant to replace them with something more compliant. The primary concern for me has been that we might make some unusual packages inaccessible using the syntactic sugar of module traversal, but since it is still possible to access such classes and packages through other mechanisms (like string-based `java_import` calls or `Class.forName`) it may be less of a worry than I imagine.

I would encourage you to convert your hack into a PR, either re-adding the missing methods or avoiding their removal. JavaPackage modules should probably be traversable as normal modules, and we are clearly breaking that. If your changes can be made without breaking other behavior or making some classes/packages inaccessible, I'd be find merging it.
