### ISSUE TITLE
Issue with use of ActiveMQ library with jRuby 9.3.0 and higher

### ISSUE THREAD

**Issue by redconfetti** [jruby/jruby#7337]
**Environment Information**

* Mac OS 12.5.1 - Darwin Kernel Version 21.6.0
* jRuby 9.3.0.0 or above, installed via RBenv / Ruby-Build (provided via Homebrew package manager)
* JVM_OPTS - `\-server \-verbose:gc \-Xmn500m \-Xms3000m \-Xmx3000m \-XX:+CMSParallelRemarkEnabled \-XX:+CMSScavengeBeforeRemark \-XX:+PrintGCCause \-XX:+PrintGCDateStamps \-XX:+PrintGCDetails \-XX:+ScavengeBeforeFullGC \-XX:+UseCMSInitiatingOccupancyOnly \-XX:+UseCodeCacheFlushing \-XX:CMSInitiatingOccupancyFraction=70 \-XX:ReservedCodeCacheSize=256m`
* JRUBY_OPTS - `--dev -X-C -Xnative.verbose=true -J-Xms900m -J-Xmx2048m --headless -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-XX:+CMSClassUnloadingEnabled -J-Djava.net.preferIPv4Stack=true -J-Djruby.openssl.x509.lookup.cache=8 -J-Djruby.thread.pool.enabled=true`
* Using [jruby-activemq](https://github.com/sis-berkeley-edu/jruby-activemq), which is just a wrapper that loads [Apache ActiveMQ v5.13.0 Java libraries](https://github.com/sis-berkeley-edu/jruby-activemq/blob/master/lib/activemq.rb#L14,L24)
* I even tried an [updated version of our fork](https://github.com/sis-berkeley-edu/jruby-activemq/blob/activemq-5.17.1/lib/activemq.rb#L14,L21) for this gem to use ActiveMQ v5.17.1, and this didn't resolve the issue.

**Expected Behavior**

Testing this using a pure-jRuby script copied into different directories with a different Ruby version specified in the .ruby-version file (recognized by RBenv), even though we're attempting to use this under Rails 6.1.4.7.

```ruby
#!/usr/bin/env ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'jruby-activemq', '~> 5.13.0', git: 'https://github.com/sis-berkeley-edu/jruby-activemq.git'
end

require 'activemq'
puts Java::JavaxJms::Session.AUTO_ACKNOWLEDGE
```

Under jRuby-9.2.21 I get the following output, with "1" being the value of the constant being referenced:

```bash
$ ./main.rb
Successfully loaded native POSIX impl.
1
```

**Actual Behavior**

I get identical results for jRuby v9.3.0.0, v9.3.4.0, and v9.3.7.0. I assume this occurs in all versions of v.9.3.

```bash
$ ./main.rb 
Successfully loaded native POSIX impl.
./main.rb:14:in `<main>': undefined method `AUTO_ACKNOWLEDGE' for Java::JavaxJms::Session:Module (NoMethodError)
```

**Comment by evaniainbrooks** [comment]
`Java::JavaxJms::Session::AUTO_ACKNOWLEDGE` prints the expected value of 1

It is also an error on MRI to reference a constant on a module in the manner presented above (Module.CONSTANT)

**Comment by redconfetti** [comment]
Thanks @evaniainbrooks. I don't know why I missed questioning the syntax of our call to that constant. Likely because it had been in place for so long, and [this example article does the same](https://medium.com/@gauravingalkar/a-simple-ruby-producer-and-consumer-using-activemq-66459d9b94e7).
