### ISSUE TITLE
StringIO ignores external encoding on Windows

### ISSUE THREAD

**Issue by jsvd** [jruby/jruby#7367]
This happens on JRuby 9.3.8.0 on Windows 2022 Datacenter and Java 17.
I can't seem to reproduce on Mac or Linux.

**Expected Behavior**

It's expected that new StringIO objects will respect the defined Encoding after it changes.

**Actual Behavior**

```ruby
puts RUBY_DESCRIPTION
require 'stringio'
puts Encoding.default_external
puts StringIO.new.external_encoding
ENV["test"] = ""
Encoding.default_external = Encoding::UTF_8
puts StringIO.new.external_encoding
```

```
PS C:\> .\jruby-9.3.8.0\bin\jruby C:\logstash-8.4.0\test.rb
jruby 9.3.8.0 (2.6.8) 2022-09-13 98d69c9461 OpenJDK 64-Bit Server VM 17.0.4+8 on 17.0.4+8 +jit [x86_64-mswin32]
IBM437
IBM437
IBM437
```

While on JRuby 9.2 we can see that the change is respected for new StringIO objects:

```
PS C:\> .\jruby-9.2.21.0\bin\jruby C:\logstash-8.4.0\test.rb
jruby 9.2.21.0 (2.5.8) 2022-06-27 49e5080a7c OpenJDK 64-Bit Server VM 17.0.4+8 on 17.0.4+8 +jit [mswin32-x86_64]
Windows-1252
Windows-1252
UTF-8
```

This came from minimizing a reproduction in Logstash, and in within Logstash removing forced jit (threshold=0) the issue went away (but would probably return later once the threshold was hit).

**Comment by enebo** [comment]
@jsvd Ignore the last question.  I just tried on windows.  So JIT somehow is interacting with ENV set and not picking up default external.  This is super weird :)

**Comment by jsvd** [comment]
> This is super weird :)

haha right? took me a long time to reduce the issue to that script. have fun 😅

**Comment by enebo** [comment]
@jsvd If I force_encoding of the "" to the ENV it will work.  It is like that string somehow makes default_external for StringIO think it is the same as that string.  Our ENV code does not seem to do anything related to this but with the JIT?  HAHA.

**Comment by headius** [comment]
I think @enebo is confirming this, but I did find a likely cause: updating an ENV value duplicates and modifies the incoming string to have an encoding matching either the filesystem encoding (for PATH) or the locale encoding. Unfortunately the way it does this duping duplicates the RubyString object, but not the ByteList it contains. If that ByteList is shared with other RubyString in the system, they will also see the encoding change.

The short-term fix is to make ENV properly duplicate the ByteList before proceeding to set the environment value. The long-term fix would be to introduce a truly immutable ByteList type so that when we *know* we should not be modifying it, we'll get an error.

**Comment by headius** [comment]
Oh and in this case, the shared ByteList is the global blank ByteList, so all default blank strings will now have this new encoding. I'm surprised we did not see this sooner, but on most *nix systems the default locale and filesystem encodings will be UTF-8, the Ruby default.

**Comment by jsvd** [comment]
Btw, this issue came from a Logstash user on windows upgrading Logstash and seeing non ascii characters failing to be index to Elasticsearch.
This happened because log entries were serialized to json and pushed to a String IO object.
because the contents of the StringIO object weren’t UTF8 encoded we saw rejections from ES.

All this to say that the issue doesn’t seem limited to empty strings (if I understood your explanation correctly).
I’m afk right now but I can try confirming it tomorrow

**Comment by headius** [comment]
In this case it was more egregious because the blank string's ByteList is shared with the entire JRuby runtime, but it could also affect non-blank strings in ENV on a local basis (i.e. if you set a non-blank value and later use a literal version of that value it may see the encoding update).
