### ISSUE TITLE
Update jopenssl in jruby-complete 

### ISSUE THREAD

**Issue by apurtell** [jruby/jruby#7398]
jruby-complete 9.3.8.0 embeds a version of jruby-openssl at ./META-INF/jruby.home/lib/ruby/stdlib/jopenssl/ that is subject to [jruby-openssl#263](https://github.com/jruby/jruby-openssl/pull/263) .

Upgrade to 0.14.1 or later.

(The Sonatype tools report this as sonatype-2022-4124.)

**Comment by kares** [comment]
0.14.1 was never released (there were just pre-releases) - the underlying problem was not resolved.

if this is due https://github.com/jruby/jruby/issues/7399 than please see https://github.com/jruby/jruby/pull/7385 which upgraded JRuby-OpenSSL to 0.14.0 (for JRuby 9.3.9)

**Comment by apurtell** [comment]
Thanks. I don't think this is exactly invalid, but, sure duplicate. The problem that Sonatype's vulnerability assessment tooling reports will be fixed when jruby-openssl 0.14.1 is released and integrated into jruby-complete, or so their knowledge base claims. I apologize for relaying second hand information. It should be them imho to be in touch with you.

**Comment by kares** [comment]
okay, thanks for clarifying - I believe we can close this than. 
the issue was resolved at https://github.com/jruby/jruby/pull/7385 (and is a duplicate of https://github.com/jruby/jruby/issues/7335)

**Comment by apurtell** [comment]
Sorry to trouble you but our vulnerability assessment tooling is showing that 9.3.9.0 has not fixed the issue. Asking for confirmation this issue has really been addressed and this is a false positive.

Issue
sonatype-2022-4124

Severity
Sonatype CVSS 3: 8.6
CVE CVSS 2.0: 0.0

Weakness
Sonatype CWE: [120](https://cwe.mitre.org/data/definitions/120.html)

Source
Sonatype Data Research

Root Cause
jruby-openssl-0.4.gem : ( , 0.14.1.cr1)

Advisories
Project: https://github.com/jruby/jruby-openssl/pull/263

CVSS Details
Sonatype CVSS 3: 8.6
CVSS Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:L/A:L

**Comment by enebo** [comment]
@apurtell This tool is showing a vulnerability (possibly) in a PR which was never in a released version.  The code in question is not in the release being used by 9.3.9.0 and it also is not on master which would be destined to be the next version of jruby-openssl.
