### ISSUE TITLE
Update bouncycastle in jruby-complete

### ISSUE THREAD

**Issue by apurtell** [jruby/jruby#7399]
jruby-complete 9.3.8.0 embeds a version of bouncycastle at ./META-INF/jruby.home/lib/ruby/stdlib/org/bouncycastle/ that is subject to  https://github.com/bcgit/bc-java/issues/925 .

> Bouncy Castle contains a weak key-hash message authentication code (HMAC) that is only 16 bits long which can result in hash collisions. This is due to an error within the BKS version 1 keystore (BKS-V1) files and could lead to an attacker being able to affect the integrity of these files.

Upgrade to 1.70 or later.

**Comment by kares** [comment]
for JRuby 9.3.9 BC was already been upgraded to 1.71 (in https://github.com/jruby/jruby/pull/7385)
