### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7474]
This issue is for post-9.4 work to support Rails 7. A basic scaffolded app works with sqlite3, but releases need to be made of that and the other adapters.

* [x] Update arjdbc CI to reflect jruby-head and Rails 7.
* [x] Update sqlite3 to reflect API changes in Rails 7
* [x] Update pg to reflect API changes in Rails 7
* [x] Update mysql to reflect API changes in Rails 7
* [x] Rails unit test pass (beyond activerecord handled by driver updates in arjdbc)(this will likely get expanded out)

See #7175

**Comment by rootcfg** [comment]
cab-wsm-0075083:yaro_drag_drop dolgashov-ds$ java -jar yaro_drag_drop.war -S rails s -b 0.0.0.0 -p 3001
2023-03-22T10:51:55.792+03:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED' to enable.
uri:classloader:/gems/zip-2.0.2/lib/zip.rb:1: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
uri:classloader:/gems/zip-2.0.2/lib/zip.rb:1: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
uri:classloader:/gems/zip-2.0.2/lib/zip.rb:1: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
uri:classloader:/gems/zip-2.0.2/lib/zip.rb:1: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
uri:classloader:/gems/zip-2.0.2/lib/zip.rb:1: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
uri:classloader:/gems/zip-2.0.2/lib/zip.rb:1: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
uri:classloader:/gems/zip-2.0.2/lib/zip.rb:1: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
uri:classloader:/gems/zip-2.0.2/lib/zip.rb:1: warning: parentheses after method name is interpreted as an argument list, not a decomposed argument
=> Booting Puma
=> Rails 7.0.4.3 application starting in production 
=> Run `bin/rails server --help` for more startup options
Exiting
ERROR: org.jruby.exceptions.StandardError: (InvalidFile) Unable to parse import map from /private/var/folders/d3/ws8nq82j3g7cx0587kh8syk9mgl52p/T/jruby6396508928035145458extract/config/importmap.rb: undefined method `pin' for main:Object
Did you mean?  print

**Comment by enebo** [comment]
@rootcfg I am able to run rails from command-line including scaffolding out a simple app.  I have not tried warbler but I wonder if this has anything to do with the config it creates?

The zip warns are extremely likely us overwarning on something in zips source.  The actual line number is bogus so it would be nice to isolate that.

**Comment by Tim-Blokdijk** [comment]
Thanks for getting PostgreSQL to work with Rails 7.

**Comment by enebo** [comment]
There are still issues with AR-JDBC but those can be addressed with individual issues on that project.  Closing this as the broad strokes are done.
