### ISSUE TITLE
`StringIO#initialize` does not accept an `encoding:` keyword argument

### ISSUE THREAD

**Issue by postmodern** [jruby/jruby#7478]
`StringIO#initialize` does not appear to accept an `encoding:` keyword argument, unlike on CRuby 3.1.0.

```ruby
StringIO.new(encoding: Encoding::ASCII_8BIT)
```

**Environment Information**
  
* `jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 17.0.5+8 on 17.0.5+8 +jit [x86_64-linux]`
* `Linux dev 6.0.9-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Nov 16 17:50:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Expected Behavior**

```
#<StringIO: ...>
```

**Actual Behavior**

```
org/jruby/ext/stringio/StringIO.java:146:in `initialize': no implicit conversion of Hash into String (TypeError)                                     
        from org/jruby/RubyClass.java:931:in `new'        
        from org/jruby/RubyIO.java:866:in `new'           
        from org/jruby/ext/stringio/StringIO.java:115:in `new'
        from (irb):2:in `evaluate'                        
        from org/jruby/RubyKernel.java:1143:in `eval'     
        from org/jruby/RubyKernel.java:1586:in `loop'     
        from org/jruby/RubyKernel.java:1292:in `catch'    
        from org/jruby/RubyKernel.java:1292:in `catch'    
        from /opt/rubies/jruby-9.4.0.0/lib/ruby/gems/shared/gems/irb-1.4.1/exe/irb:11:in `<main>'                                                    
        from org/jruby/RubyKernel.java:1091:in `load'     
        from /opt/rubies/jruby-9.4.0.0/bin/irb:23:in `<main>'
```

**Comment by enebo** [comment]
This is going to be difficult to fix in the sense that StringIO is now in the stringio gem.

Problems:
  1. we need to limit this to 9.4+ since < 9.3 does not support ```keywords``` annotation (this may not be a big deal).
  2. we plan on changing the design of keywords during 9.4 and this means we may nee conditional code.

The decoupling of this as a gem means n point release support and this will really limit our ability to change how keywords works.

**Comment by headius** [comment]
I took a quick look at this and basic support shouldn't be too hard. Pull off the keyword hash, get the encoding out, and use it to create the backing string (I think). A better fix would align the logic we use with what's in CRuby, using the io_extract_modeenc logic that the other IO types use to set up in and out encodings.

We could also get something in immediately that ignores the encoding.

**Comment by headius** [comment]
I have started work on this in https://github.com/ruby/stringio/pull/45 but more remains. There are no tests for this behavior in the stringio repository. There might be in the CRuby repository, or in ruby/spec. The current patch at least accepts the keyword, but additional changes are needed to actually use it during IO operations.

The work here is entirely in StringIO so we can either close this or keep punting until the work is complete.
