### ISSUE TITLE
Cannot call `SubClass#initialize_copy` with an object created from the super class

### ISSUE THREAD

**Issue by postmodern** [jruby/jruby#7480]
Ran into this weird edge-case. If I sub-class a class, initialize a new instance of it, then call `initialize_copy` but with another object that was created from the super-class, I get an exception. This appears to be allowed on CRuby 3.1.0.

```ruby
class BaseClass
end

class SubClass < BaseClass
end

obj = SubClass.new
obj.send(:initialize_copy,BaseClass.new)
p obj

```

**Environment Information**
  
* `jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 17.0.5+8 on 17.0.5+8 +jit [x86_64-linux]`

**Expected Behavior**

```
#<SubClass: ...>
```

**Actual Behavior**

```
TypeError: initialize_copy should take same class object
  initialize_copy at org/jruby/RubyKernel.java:2121
           <main> at test_jruby_initialize_copy.rb:8
... 3 levels...
```

**Comment by headius** [comment]
This is pretty weird. Did you run into this in real code? It seems wrong to be able to `initialize_copy` with a different class, even if it is a superclass.

**Comment by headius** [comment]
I just ran your script through Ruby 3.1 and it does not seem to be allowed:

```
$ (chruby 3.1 ; ruby blah.rb)
blah.rb:8:in `initialize_copy': initialize_copy should take same class object (TypeError)
	from blah.rb:8:in `<main>'
```

I also confirmed on CRuby master that they reject the other object if its class is not the same as self's class.

**Comment by postmodern** [comment]
@headius this was sort of my hack to allow converting existing `OpenSSL::X509::Certificate` objects into sub-classed `OpenSSL::X509::Certificate` objects that have additional methods. I guess calling `initialize_copy` with a sub-class object works because the `OpenSSL` classes are actually implemented as C extensions, so it's kind of an OpenSSL-specific hack.
https://github.com/ronin-rb/ronin-support/blob/f147b92cd559fb8cd782d18fb9fdc17046cde67c/lib/ronin/support/crypto/cert.rb#L491-L514

I can close this and try to come up with a better way.

**Comment by headius** [comment]
@postmodern I suspect that the OpenSSL classes you got this to work with have their own custom `initialize_copy` that is more forgiving, probably allowing similar types' data to get copied in.
