### ISSUE TITLE
Possible regression in JRuby v9.4.0.0

### ISSUE THREAD

**Issue by floehopper** [jruby/jruby#7492]
**Environment Information**

* JRuby version string for scenario where Mocha tests pass: `jruby 9.3.9.0 (2.6.8) 2022-10-24 537cd1f8bc OpenJDK 64-Bit Server VM 25.352-b08 on 1.8.0_352-b08 +jit [x86_64-linux]`
* JRuby version string for scenario where some Mocha tests fail: `jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 25.352-b08 on 1.8.0_352-b08 +jit [x86_64-linux]`
* [Mocha gem](https://github.com/freerange/mocha) test suite running on CircleCI: [passing build](https://app.circleci.com/pipelines/github/freerange/mocha/328/workflows/7ed24069-fc38-43d8-aa73-4ec18755ee7e/jobs/4469); [failing build](https://app.circleci.com/pipelines/github/freerange/mocha/333/workflows/2b7aced7-652a-4e55-8ddd-b024f664d85b/jobs/4548)

**Expected Behavior**

The Mocha test suite passes.

**Actual Behavior**

A number of [tests relating to keyword arguments](https://github.com/freerange/mocha/blob/26b106a540ad57cd73401461451aa2711c541e9d/test/acceptance/keyword_argument_matching_test.rb) fail in the Mocha test suite...

```
  1) Failure:
KeywordArgumentMatchingTest#test_should_match_hash_parameter_with_keyword_args [/root/project/test/acceptance/keyword_argument_matching_test.rb:32]:
Test failed unexpectedly with message: [#<MinitestResult::Failure:0x36c54a56 @failure=#<Minitest::Assertion: Expected "Expectation defined at /root/project/test/acceptance/keyword_argument_matching_test.rb:22:in `block in test_me' expected keyword arguments (:key => 42), but received positional hash ({:key => 42}). These will stop matching when strict keyword argument matching is enabled. See the documentation for Mocha::Configuration#strict_keyword_argument_matching=." to include "Expectation defined at /root/project/test/acceptance/keyword_argument_matching_test.rb:22:in `block in test_should_match_hash_parameter_with_keyword_args' expected keyword arguments (:key => 42)".>>]

  2) Failure:
KeywordArgumentMatchingTest#test_should_match_hash_parameter_with_splatted_keyword_args [/root/project/test/acceptance/keyword_argument_matching_test.rb:62]:
Test failed unexpectedly with message: [#<MinitestResult::Failure:0x15fc442 @failure=#<Minitest::Assertion: Expected "Expectation defined at /root/project/test/acceptance/keyword_argument_matching_test.rb:52:in `block in test_me' expected keyword arguments (:key => 42), but received positional hash ({:key => 42}). These will stop matching when strict keyword argument matching is enabled. See the documentation for Mocha::Configuration#strict_keyword_argument_matching=." to include "Expectation defined at /root/project/test/acceptance/keyword_argument_matching_test.rb:52:in `block in test_should_match_hash_parameter_with_splatted_keyword_args' expected keyword arguments (:key => 42)".>>]

  3) Failure:
KeywordArgumentMatchingTest#test_should_match_positional_and_keyword_args_with_last_positional_hash [/root/project/test/acceptance/keyword_argument_matching_test.rb:110]:
Test failed unexpectedly with message: [#<MinitestResult::Failure:0x11ce2e22 @failure=#<Minitest::Assertion: Expected "Expectation defined at /root/project/test/acceptance/keyword_argument_matching_test.rb:100:in `block in test_me' expected positional hash ({:key => 42}), but received keyword arguments (:key => 42). These will stop matching when strict keyword argument matching is enabled. See the documentation for Mocha::Configuration#strict_keyword_argument_matching=." to include "Expectation defined at /root/project/test/acceptance/keyword_argument_matching_test.rb:100:in `block in test_should_match_positional_and_keyword_args_with_last_positional_hash' expected positional hash ({:key => 42})".>>]

  4) Failure:
KeywordArgumentMatchingTest#test_should_match_last_positional_hash_with_keyword_args [/root/project/test/acceptance/keyword_argument_matching_test.rb:140]:
Test failed unexpectedly with message: [#<MinitestResult::Failure:0x6f95cd51 @failure=#<Minitest::Assertion: Expected "Expectation defined at /root/project/test/acceptance/keyword_argument_matching_test.rb:130:in `block in test_me' expected keyword arguments (:key => 42), but received positional hash ({:key => 42}). These will stop matching when strict keyword argument matching is enabled. See the documentation for Mocha::Configuration#strict_keyword_argument_matching=." to include "Expectation defined at /root/project/test/acceptance/keyword_argument_matching_test.rb:130:in `block in test_should_match_last_positional_hash_with_keyword_args' expected keyword arguments (:key => 42)".>>]
```

I'm pretty confident these were passing before the JRuby version bump from v9.3.9.0 -> v9.4.0.0. I haven't had time to work out whether something is wrong with the Mocha implementation, but I wanted to give you an early heads-up that something might be amiss with JRuby.

**Comment by enebo** [comment]
I can see this failing locally in mocha tests.  Triaging.

**Comment by floehopper** [comment]
@enebo Thank you - let me know in https://github.com/freerange/mocha/issues/591 if you think the problem lies with Mocha.

**Comment by enebo** [comment]
@floehopper Ruby 3.1 runs so I think it is us.  My first check was to make sure the RUBY27PLUS thing was correct and it seems to be.

**Comment by enebo** [comment]
Good news and bad news.  The good news is this is not a keyword arguments bug.  The bad news is the error string is picking up the wrong method name.  So mocha is working but we are doing something differently reflectively to grab the proper method name.  Getting closer to a root cause.

**Comment by floehopper** [comment]
@enebo

Is there any update on this...?

I've just run the Mocha tests that were failing using `jruby-dev` installed via `asdf` which reports its version as `jruby 9.4.1.0-SNAPSHOT (3.1.0) 2022-12-17 1d9723771b OpenJDK 64-Bit Server VM 19.0.1 on 19.0.1 +jit [arm64-darwin]` and they now pass!

However, they still failed in [the Mocha CircleCI build earlier today](https://app.circleci.com/pipelines/github/freerange/mocha/340/workflows/6caf8f1c-b2b2-4e64-a438-96b84582ecc5/jobs/4625) which reports its Ruby version as `jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 25.352-b08 on 1.8.0_352-b08 +jit [x86_64-linux]`.

After a quick look, I can't obviously see a JRuby commit which might have fixed this. Do you know what's going on?

Is there anything I can do to help?

**Comment by floehopper** [comment]
@enebo Thanks for looking into it. In case it helps, I've belatedly noticed that the thing that's changed in the stack trace is the method name which is now being picked up from [`TestRunner#run_as_test`](https://github.com/freerange/mocha/blob/e242033ff9e1e054ad3efeaa8ca79058aa442f5a/test/test_runner.rb#L7), which dynamically defines a method `test_me` in [`TestRunner#run_as_tests`](https://github.com/freerange/mocha/blob/e242033ff9e1e054ad3efeaa8ca79058aa442f5a/test/test_runner.rb#L17). 

Perhaps what's unusual here is that the block used to define the method is in a different source file (i.e. `test/acceptance/keyword_argument_matching_test.rb`) than the one where the call to `Module#define_method` appears (i.e. `test/test_runner.rb`)...?

**Comment by enebo** [comment]
Update 

I have not been having a lot of luck reducing this.  It started to fail in 2d100bb543da6d4a19a1f3c7ea2e3bebf66eed9f.  This is a massive commit of MRIs stdlib changes along with what gems are being pulled in as default gems.  This likely is something which is changing how it is doing something which is because Ruby 2.7+ is doing something different (that we are not).  Just backing off whatever is here will make these error messages work in mocha but likely break newer behavior.

This is just an educated guess though.

In trying to figure this out by looking at the code.  The code takes a block defined in the test method.  It uses that block to define a method 'test_me' in a new type which extends Mocha::UnitTest.  It then runs this method via minitest by performing 'run' on an instance of this new type.  The backtraces generated deviates in that MRI will use the original test methods name while we will use test_me.  What confuses me here is it literally is running the block as a method called test_me.  Why would the backtrace show the containing method name for the block and not the actual method it represents?

**Comment by floehopper** [comment]
@enebo Thanks for the update. I agree that if anything it seems as if the new JRuby behaviour is "more correct" than the old JRuby behaviour and the current MRI Ruby behaviour. Unless you disagree, I suggest the following:

1. I close this JRuby issue.
2. I work around the discrepancy in the Mocha tests.
3. I open a bug report against MRI Ruby hopefully with a simpler example.

Let me know what you think.

**Comment by enebo** [comment]
@floehopper At this point I think I have to figure it out enough to reduce this before I can say anything more.  We did work up to a point and I need some clarity on that.  JRuby itself generally has to match CRuby or we just continue to get compatibility errors so this will get fixed even if it doesn't make sense (but it may lead to a bug report to ruby-lang as well).

**Comment by enebo** [comment]
Ok...progress has been made!

define_method appears to use the location of where the proc was defined:

```ruby
class Real
end

def make_method_with(&block)
  Real.class_eval do |cls|
    cls.define_method(:bad_name, &block)
  end
  cls = Class.new do |cls|
    cls.define_method(:bad_name, &block)
  end
  begin
    cls.new.bad_name
  rescue ArgumentError
    puts $!.backtrace
  end
  begin 
    Real.new.bad_name
  rescue ArgumentError
    puts $!.backtrace
  end
end


def original
  make_method_with do
    puts "In method_with"
    raise ArgumentError.new("eheeheheh")
  end
end


$a = proc do
  puts "In method_with"
  raise ArgumentError.new("eheeheheh")
end

class AnotherReal
  define_method(:bad_name, &$a)
end

begin 
  AnotherReal.new.bad_name
rescue ArgumentError
  puts $!.backtrace
end

original
```

It is quite mysterious that I bisected to the above commit but I see something pretty concrete we are doing differently.

**Comment by floehopper** [comment]
Great sleuthing! 😄

**Comment by enebo** [comment]
Interestingly if I run this with JRuby 9.3.9.0 we do get the same output as Ruby 3.1 so it does appear to be a regression.  It looks like my bisect was wrong somehow.

**Comment by enebo** [comment]
I guess I find this behavior regardless of how old it is strange and not intuitive.  Wouldn't you want the backtrace to contain the define_method name somwhere in the backtrace rather than the method/location the proc was originally defined in (note: 99% of the time you will not be confused since you typically define_method where the proc is made so the name will be right next to it in the source albeit likely as a variable)?  

It does seem useful for mocha in this case but, to me, logically I would expect a method invocation to contain the actual method name being invoked in the backtrace.

@floehopper not your problem...just adding a posterity note :)

**Comment by floehopper** [comment]
> Wouldn't you want the backtrace to contain the define_method name somwhere in the backtrace rather than the method/location the proc was originally defined in

Yes, I think you are right. 👍

**Comment by floehopper** [comment]
@enebo Many thanks for getting to the bottom of this - much appreciated! 👍
