### ISSUE TITLE
prepend `Kernel` or `Object` is broken on Jruby 9.2

### ISSUE THREAD

**Issue by hurricup** [jruby/jruby#7496]
One of our recent CI test uncovered inconsistency on how jruby handles Kernel prepending.

Test sample (for Linux):
```rb
module PrependPatcher
  private def exec(*args)
    puts RUBY_VERSION
    puts "Ancestors: #{self.class.ancestors}"
    puts "Super method: #{method(:exec).super_method}"
    puts 'Patcher proxy method'
    super
  end
end

Kernel.prepend PrependPatcher
Object.prepend PrependPatcher
Object.new.__send__('exec', 'echo patcher test')
```

# 3.1 (working as expected)

## Jruby 9.4
```
3.1.0
Ancestors: [PrependPatcher, Object, PrependPatcher, #<Module:0x125f16b2>, BasicObject]
Super method: #<Method: #<Class:0x79195c22>(PrependPatcher)#exec(*args) /home/hurricup/Projects/untitled1/test.rb:13>
Patcher proxy method
3.1.0
Ancestors: [PrependPatcher, Object, PrependPatcher, #<Module:0x125f16b2>, BasicObject]
Super method: #<Method: #<Class:0x79195c22>(PrependPatcher)#exec(*args) /home/hurricup/Projects/untitled1/test.rb:13>
Patcher proxy method
patcher test
```
This is more or less expected, except we have `#<Module:0x125f16b2>` instead of a `Kernel`, but works as expected and both `Object` and `Kernel` are patched.

## Ruby 3.1.3
```
3.1.3
Ancestors: [PrependPatcher, Object, PrependPatcher, Kernel, BasicObject]
Super method: #<Method: PrependPatcher#exec(*args) /home/hurricup/Projects/untitled1/test.rb:13>
Patcher proxy method
3.1.3
Ancestors: [PrependPatcher, Object, PrependPatcher, Kernel, BasicObject]
Super method: #<Method: PrependPatcher#exec(*args) /home/hurricup/Projects/untitled1/test.rb:13>
Patcher proxy method
patcher test
```
Same here.

# 2.6 (working consistently)
## Jruby 9.3.9
```
2.6.8
Ancestors: [PrependPatcher, Object, Kernel, BasicObject]
Super method: #<Method: Object(Kernel)#exec>
Patcher proxy method
patcher test
```
Okay, Kernel patch is missing, but this is consistent with MRI, including missing `Kernel` patch

## Ruby 2.6.10
```
2.6.10
Ancestors: [PrependPatcher, Object, Kernel, BasicObject]
Super method: #<Method: Kernel#exec>
Patcher proxy method
patcher test
```

# 2.5 (not working)
## Jruby 9.2.21
```
2.5.8
Ancestors: [PrependPatcher, Object, Kernel, BasicObject]
Super method: #<Method: Object(PrependPatcher)#exec>
Patcher proxy method
2.5.8
Ancestors: [PrependPatcher, Object, Kernel, BasicObject]
Super method: #<Method: Object(PrependPatcher)#exec>
Patcher proxy method
NoMethodError: super: no superclass method `exec' for #<Object:0x38cfecf3>
    exec at /home/hurricup/Projects/untitled1/test.rb:18
    exec at /home/hurricup/Projects/untitled1/test.rb:18
  <main> at /home/hurricup/Projects/untitled1/test.rb:24
```
Ancestry shows us that only `Object` was patched, but we have 2 invocations, meaning `Kernel` was kinda patched as well, but not really. Or resolve messes up when calling `super`

## Ruby 2.5.9
```
2.5.9
Ancestors: [PrependPatcher, Object, Kernel, BasicObject]
Super method: #<Method: Kernel#exec>
Patcher proxy method
patcher test
```
Kernel is not patched, object  patched and works as expected.

**Comment by kares** [comment]
so the report is specifically for JRuby 9.2 which hasn't had much releases.
just out of curiosity, since you tested all later versions, is there anything blocking you from upgrading to 9.3?

**Comment by hurricup** [comment]
@kares I'm working on RubyMine and we have integration tests vs different versions of rubies. Some time ago we disabled 9.2 tests because of flaky failures (#7508). But recently I wanted to re-run all tests, including recently added ones in 9.2 and found this one. 

Still we have users who can't even upgrade their minor version of jruby for some reason. Like this one https://youtrack.jetbrains.com/issue/RUBY-30587/

**Comment by headius** [comment]
Officially, JRuby 9.2 is EOL with the release of 9.4. We have sometimes worked with the community to gather fixes and push post-EOL updates when there's a critical bug, but at present we have no plans to work on any 9.2 updates.

@hurricup In the issue you linked, a user says they cannot upgrade past JRuby 9.2.8 because, among other reasons, there's no Alpine Linux Docker image for 9.2.9+. I do not know what image this user is using, but we took over maintenance of the "official' JRuby image last year. At that time I do not believe it had an Alpine image either.

We are willing to discuss how to support users stuck on legacy versions, but there's only so much we can do. JRuby 9.2.8 is now over three years old and there have been **13** 9.2.x releases since then.

**Comment by enebo** [comment]
If people want to have a discussion about the need for us to continue or make one more 9.2 release they can re-open this but I am closing it because we are not planning on another 9.2 release
