### ISSUE TITLE
Ocassional `bundle install` failures on Jruby 9.2

### ISSUE THREAD

**Issue by hurricup** [jruby/jruby#7508]
Our CI runs tests in the very same docker image and from time to time it fails. (probably related to #6790)

Image: `docker pull rubymine/test_environment:rvm-single-ssh-jruby`

[error1.log](https://github.com/jruby/jruby/files/10139239/error1.log)
[error2.log](https://github.com/jruby/jruby/files/10139240/error2.log)

**Comment by kares** [comment]
this is a known issue with JRuby 9.2, if I recall correctly due https://github.com/jruby/jruby/issues/3656 (sample reproducer https://github.com/jruby/jruby/issues/6293)

while it won't fix on 9.2 but the good news is 9.3 has the fix and the problem should not manifest on JRuby >= 9.3.0.0

**Comment by hurricup** [comment]
Is there anything I can do on my side to avoid this in 9.2?

**Comment by kares** [comment]
> Is there anything I can do on my side to avoid this in 9.2?

not anything easy that isn't ugly, you could try newer RubyGems where there might be less auto-loading, not sure.
maybe pre-loading the [autoload-ed constants](https://github.com/rubygems/rubygems/blob/v3.2.33/lib/rubygems.rb#L1305-L1322) eagerly (on a single thread), but other libraries might bump into the issue as well.

**Comment by headius** [comment]
@hurricup Is there a reason you cannot upgrade to 9.3 or 9.4? We are no longer maintainined 9.2.

**Comment by hurricup** [comment]
this is CI for RubyMine, so we are testing with various ruby implementations. But atm we testing with only last major version of jruby because of different flaky failures.
