### ISSUE TITLE
The `:binmode` keyword argument isn't applied on `Tempfile` in JRuby 9.4

### ISSUE THREAD

**Issue by janko** [jruby/jruby#7539]
**Environment Information**
  
```sh
$ jruby -v
jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 17.0.2+0 on 17.0.2+0 +jit [arm64-darwin]
``` 
```sh
$ uname -a
Darwin Jankos-MacBook-Air.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64
```

**Expected Behavior**

I expected the following to open the `Tempfile` in binary mode, as is the behavior on Ruby 3.1:

```rb
require "tempfile"

tempfile = Tempfile.new("bla.rb", binmode: true)
p tempfile.binmode?
```

**Actual Behavior**

However, on JRuby 9.4 the tempfile indicates that it's not in binary mode:

```
false
```

**Comment by enebo** [comment]
Simple fix but one which I think should get hit by multiple IO consumers (Tempfile is an IO).
