### ISSUE TITLE
specs for pack/unpack with `j` and `J` formats failing on 32-bit platforms

### ISSUE THREAD

**Issue by jcharaoui** [jruby/jruby#7542]
On Debian with Java 17, the specs defined in `spec/ruby/core/array/pack/j_spec.rb` and `spec/ruby/core/string/unpack/j_spec.rb` produce many failures when run on 32-bit platforms such as `i386`, `armel` and `armhf`.

A full log of the failures on `i386` may be found here: http://sprunge.us/Q7zY2h

According to [this commit](https://github.com/jruby/jruby/commit/1053fa62e2210ece8964b5986a563a09fc1608aa), it's likely that these failures are to be expected given the current implementation.

**Comment by headius** [comment]
Yeah very likely expected. JRuby, being on the JVM, behaves like it is a 64-bit platform. I will look into the failures, though, and see if it would make sense for us to emulate 32-bit here.

**Comment by headius** [comment]
I've pushed logic to switch to 32-bit packing for `J` and `j` when the host platform is 32-bit. I don't have a way to test locally, but forcing mspec and JRuby into 32-bit mode seems to pass those 32-bit specs.

**Comment by headius** [comment]
Fixed by #7581.
