### ISSUE TITLE
 org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.

### ISSUE THREAD

**Issue by donv** [jruby/jruby#7543]
**Environment Information**
  
jruby 9.3.9.0 (2.6.8) 2022-10-24 537cd1f8bc OpenJDK 64-Bit Server VM 17.0.5+8-LTS on 17.0.5+8-LTS +jit [x86_64-darwin]
Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64

**Expected Behavior**

Using Psych::Parser to parse a large yaml file succeeds.

**Actual Behavior**

Using JRuby 9.3.9.0 parsing a large yaml file results in an exception:

```
 org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
```

Reverting to jruby-9.3.8.0 works.

**Comment by chadlwilson** [comment]
This is due to https://github.com/jruby/jruby/pull/7388 and the 3MB code point limit now honored in SnakeYaml `1.32` ( https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes )

Without looking at the specifics, suspect this might require https://github.com/ruby/psych/issues/579 to workaround by setting
https://javadoc.io/static/org.yaml/snakeyaml/1.32/org/yaml/snakeyaml/LoaderOptions.html#setCodePointLimit-int-

**Comment by donv** [comment]
Yeah, this looks right.

Any way to set the limit before https://github.com/ruby/psych/issues/579 is done?

**Comment by chadlwilson** [comment]
Apart from some hardcore runtime bytecode manipulation, I don't think so. Sadly the `LoaderOptions` defaults appear [hard coded](https://bitbucket.org/snakeyaml/snakeyaml/src/d9b0f480b1a63aca4678da7ab1915fcfc7d2a856/src/main/java/org/yaml/snakeyaml/LoaderOptions.java#lines-39) and without any external way to change the default values JVM-wide (e.g static default holders, system properties).

**Comment by headius** [comment]
I have added some of these methods in ruby/psych#613. This is a unilateral exposure of these properties only in the JRuby version, so we should try to work with the maintainers of the C extension and see if we can have the same API for both.

**Comment by headius** [comment]
I've requested review for my changes in https://github.com/ruby/psych/pull/613. I would also like to release psych 5.1 to incorporate the new SnakeYAML Engine in https://github.com/ruby/psych/pull/612, so this is a good time to do it.

**Comment by chadlwilson** [comment]
Looks like ability to control this was merged in https://github.com/ruby/psych/pull/613, released in Psych `5.1.0` which is part of JRuby `9.4.1.0` in https://github.com/jruby/jruby/pull/7626 so if that is all that is required on JRuby side, we might be able to update the milestone here (currently `9.4.2.0` and close this unless it needs backport)?

Also not sure if it needs some docs somewhere to show how to override them in normal use cases.

**Comment by headius** [comment]
Oops, yup, this one should have been resolved as of 9.4.1.

**Comment by headius** [comment]
There are no docs for the new features and no tests. Perhaps you could come up with some? I must admit I do not know exactly what YAML constructs the various settings apply to.

**Comment by chadlwilson** [comment]
The irony is that my/our use case of JRuby actually doesn't rely on YAML parsing, Psych or SnakeYAML at all - it's just that we use `jruby-complete` and I like reducing noise for the community from CVEs. Some other things I work on have direct SnakeYAML exposure so was familiar with some of the noise/risks in the area and interested in the overlap with JRuby world.

I wonder if @donv has something on the test side.

Where do you suggest the docs would sit? Within Psych? Jruby itself somewhere?

**Comment by donv** [comment]
Hi!

Documenting the usage here since I could not find it anywhere else yet.

```ruby
@parser = Psych::Parser.new
@parser.code_point_limit = 20_000_000
```

I have switched to JRuby 9.4.1.0 in development and it seems to work fine.

**Comment by headius** [comment]
@donv thanks for confirming!

**Comment by headius** [comment]
@chadlwilson Well that is a good question. There is no logic in rdoc to generate documentation from the Java extension, and any way we don't have the same feature in the C extension so putting it in the general psych docs would not work anyway.

@hsbt @tenderlove How should we handle this? Maybe we can collaborate to get these same config options supported in the C extension?
