### ISSUE TITLE
1 << (2**40) returns 1 on JRuby

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#7554]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc): `jruby 9.4.1.0-SNAPSHOT (3.1.0) 2023-01-05 006cf2b9c4 OpenJDK 64-Bit Server VM 17.0.5+8 on 17.0.5+8 +jit [x86_64-linux]`
* Operating system and platform (e.g. `uname -a`): Linux

**Expected Behavior**

MRI and TruffleRuby:
```
$ ruby -e 'p(1 << (2**40))'
-e: failed to allocate memory (NoMemoryError)
$ ruby -e 'p(1 << (2**64))'
-e: failed to allocate memory (NoMemoryError)
```

**Actual Behavior**

JRuby:
```
$ ruby -e 'p(1 << (2**40))'               
1
$ ruby -e 'p(1 << (2**64))'
RangeError: bignum too big to convert into `long'
      << at org/jruby/RubyBignum.java:912
      << at org/jruby/RubyFixnum.java:1285
  <main> at -e:1
... 4 levels...
```

Related: https://bugs.ruby-lang.org/issues/18518

**Comment by eregon** [comment]
The RangeError is fine IMO, returning 1 OTOH that's clearly incorrect mathematically.

**Comment by headius** [comment]
This appears to date back to a change from 2008, to allow out-of-range right shifts to work:

https://github.com/jruby/jruby/commit/bf0e373b712fb47e5eee4de9bb111bf6e4301f41

The blind cast to int allows long left shifts to proceed but only using the lower 4 bytes. We should error before this.

**Comment by headius** [comment]
The fix is trivial: check for out of range (probably > 32-bit integer max) before proceeding to cast it to int and do the shift.

However the specs for this do not appear to be canon and the linked issue has no conversation about appropriate behavior. The specs are marked as `ruby_bug` but then go on to expect `NoMemoryError`, codifying that behavior. It's not clear whether this should be allowed to fall back on a memory error or if it should be a `RangeError` (the latter makes more sense to me).

**Comment by eregon** [comment]
I think either exception class is acceptable, it's fine to adapt to specs to accept both, or even change to RangeError only if CRuby agrees to that change (I'd suggest to accept both for now).

I agree RangeError is nicer and more expected.
Initially I thought had a fast check and for some reason chose a NoMemoryError there (the result won't fit in memory so fair enough), but it seems the NoMemoryError on CRuby master is just a regular OOM.

**Comment by eregon** [comment]
> the linked issue has no conversation about appropriate behavior.

There is plenty of suggestions there but no agreement yet. I think it's helpful if you can share your opinion there too.

**Comment by headius** [comment]
I've implemented the current possibly-flawed behavior (using NoMemoryError) in #7558. The errors can all flip to RangeError easily enough.
