### ISSUE TITLE
Process#spawn should call #to_io on non-IO file descriptor objects

### ISSUE THREAD

**Issue by jcouball** [jruby/jruby#7565]
**Expected Behavior**

When an object is passed as the value to a `Process#spawn` redirection option AND that object isn't a Symbol, Array, Integer, or an IO object AND that object responds to `#to_io`, then `Process#spawn` should call `#to_io` on that object to get the file descriptor.

**Actual Behavior**

For JRuby-9.3.9.0 and previous versions on Windows and Linux and JRuby-9.4.0.0 on windows only, `Process#spawn` does not call the object's `#to_io` method. For JRuby-9.4.0.0 on Windows, I think this might be related to #7515.

The MRI implementation has this behavior since 2.0.0. I have created the project [jcouball/convert_to_fd_test](https://github.com/jcouball/convert_to_fd_test) to illustrate this. The project contains [RSpec tests](https://github.com/jcouball/convert_to_fd_test/blob/main/spec/test_spec.rb) that test this scenario and uses Github Actions to run these tests on different versions of MRI and JRuby. The results of running these tests on different Rubies and different platforms can be found [here](https://github.com/jcouball/convert_to_fd_test/actions/runs/3863246136).

**Environment**

* The incorrect behavior is observable using JRuby-9.3.9.0 (on Linux and Windows) and JRuby-9.4.0.0 (Windows only)
* Works as expected in JRuby-9.4.0.0 on Linux.

**Comment by headius** [comment]
This likely works on 9.4/Linux because we use a different spawn library there: https://github.com/byteit101/subspawn

It may be worth us switching 9.3 to use this library, but I believe if you install it and require `subspawn/replace-builtin.rb` it will replace our spawn with the working one.

**Comment by byteit101** [comment]
`require 'subspawn/replace'` is the public API, but I don't think we would be using subspawn by default?

**Comment by headius** [comment]
@byteit101 Yeah you're right... perhaps this was patched in 9.4. I'll figure it out.

**Comment by byteit101** [comment]
Either way I need to validate that subspawn does this too

**Comment by headius** [comment]
JRuby was patched... a trivial fix from @enebo: e38db716a2c393b2f1fefec3ea315da64206e0d6

I will copy this to 9.3 branch and it will go out in the next release.

**Comment by headius** [comment]
Fixed by e38db716a2c393b2f1fefec3ea315da64206e0d6 on master and 0e0cb48fc4 on 9.3.

**Comment by headius** [comment]
And we probably should add some specs for this if they don't already exist.

**Comment by byteit101** [comment]
I fixed SubSpawn to call `#to_io` and copied a slightly modified version of @jcouball 's rspec tests to SubSpawn. It still may be a good idea to copy an unmodified version of them to JRuby itself.
