### ISSUE TITLE
SecureRandom.random_number is always 0

### ISSUE THREAD

**Issue by duritong** [jruby/jruby#7586]
```ruby
require 'securerandom'

arr = []
(1..100).each do |i|
  r = SecureRandom.random_number(10)
  puts "#{i}: #{r}"
  arr << r
end

puts arr.uniq

# there might still be the one case in the
# universe where we would have a 100times the
# same number. But it's probably fine as an
# indication...
exit (arr.uniq.length > 1 ? 0 : 1)
```

Always returns 0.

According to @headius 

>  It appears to be a bug in some very old code used to generate a random int or long by calling bytes on the self object, but it does not handle the bit math properly to produce the final value. This logic was not in use for SecureRandom until we moved to the securerandom gem, which depends on these callbacks to work properly.

See https://github.com/ruby/setup-ruby/issues/448 & https://github.com/duritong/trocla/issues/75 for more background

**Comment by headius** [comment]
Back into this today, so we can include it in 9.4.1.0.
