### ISSUE TITLE
instance_eval, module_eval, class_eval cannot yield to block

### ISSUE THREAD

**Issue by ryannevell** [jruby/jruby#7598]
When `instance_eval`, `module_eval`, or `class_eval` is called with a string containing "yield", it results in a `LocalJumpError: yield called out of block` exception. This behavior differs from CRuby, as well as `Kernel#eval`.

**Environment Information**
```  
jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f OpenJDK 64-Bit Server VM 17.0.4+8-LTS on 17.0.4+8-LTS +jit [x86_64-darwin]
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-darwin21]
Darwin --- 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64
```

**Test Case**

```
o = Object.new

def o.kernel_eval
  eval('yield')
end

def o.inst_eval
  instance_eval('yield')
end

o.kernel_eval { puts 'Always works' }
o.inst_eval { puts 'Works only in CRuby' }
```

**Expected Behavior**
In both versions of CRuby tested (details above), the result is:
```
Always works
Works only in CRuby
```

**Actual Behavior**

In JRuby, the 2nd call fails:
```
Always works
LocalJumpError: yield called out of block
         (eval) at (eval):1
  instance_eval at org/jruby/RubyBasicObject.java:2511
      inst_eval at test1.rb:8
         <main> at test1.rb:12
... 5 levels...
```

**Comment by enebo** [comment]
This also does not work in 9.3 (Ruby 2.6).  I tested back to Ruby 2.5.x and it works.  We probably have never passed this.

**Comment by enebo** [comment]
Not sure this will make 9.3.10.0 or 9.3.11.0 but it may make 9.4.1.0.

**Comment by headius** [comment]
This is the fix:

```diff
diff --git a/core/src/main/java/org/jruby/runtime/ThreadContext.java b/core/src/main/java/org/jruby/runtime/ThreadContext.java
index 5708fd2685..df67cad843 100644
--- a/core/src/main/java/org/jruby/runtime/ThreadContext.java
+++ b/core/src/main/java/org/jruby/runtime/ThreadContext.java
@@ -489,7 +489,7 @@ public final class ThreadContext {
 
     public void pushEvalSimpleFrame(IRubyObject executeObject) {
         Frame frame = getCurrentFrame();
-        pushCallFrame(frame.getKlazz(), frame.getName(), executeObject, Block.NULL_BLOCK);
+        pushCallFrame(frame.getKlazz(), frame.getName(), executeObject, frame.getBlock());
     }
 
     private void pushCallFrame(RubyModule clazz, String name,
```

I have not tested to see if it impacts any other tests. This logic is primarily used by instance_eval and similar.

**Comment by headius** [comment]
Fixed by #7605.

**Comment by headius** [comment]
@ryannevell Perhaps you could submit a PR to JRuby or ruby/spec with some spec additions? See spec/ruby/core/basicobject/instance_eval_spec.rb and spec/ruby/core/module/module_eval_spec.rb

**Comment by ryannevell** [comment]
Thanks so much for the fix, @headius. I'll consider making the spec additions. Unfortunately, my company's legal team needs to review and approve any open-source software contributions, so it could be months before that goes through, if at all.

**Comment by headius** [comment]
@ryannevell No problem. I will mark this with "test needed"  label so we can find it later.
