### ISSUE TITLE
JSON.pretty_generate generates wrong format json output to MRI for at least an empty hash version 9.4.0.0

### ISSUE THREAD

**Issue by tqtu** [jruby/jruby#7609]
Code:
```
require 'json'
puts "With empty hash"
puts JSON.pretty_generate({})
puts "With empty hash in child"
puts JSON.pretty_generate({"empty": {}})
```
Output:   jruby -v hello.rb 
```
jruby 9.4.0.0 (3.1.0) 2022-11-23 95c0ec159f Java HotSpot(TM) 64-Bit Server VM 25.202-b08 on 1.8.0_202-b08 +jit [x86_64-darwin]
With empty hash
{
}
With empty hash in child
{
  "empty": {
}
}
```

**Comment by headius** [comment]
Is it just the indentation you're concerned about? That appears to be the only difference:

```
[] jruby $ jruby hello.rb
With empty hash
{
}
With empty hash in child
{
  "empty": {
}
}
[] jruby $ chruby 3.1    
[] jruby $ ruby hello.rb 
With empty hash
{
}
With empty hash in child
{
  "empty": {
  }
}
```

**Comment by tqtu** [comment]
Yes, It is just about indentation of end "}" . 
With jruby 9.4.0.0 the end "}" of empty block is start at the first of new line. 
Do you have a solution or adding library to fix ?

**Comment by headius** [comment]
It does not seem to be a regression. Most likely answer is a bug in the json library for JRuby.

@tqtu Could you re-file this with https://github.com/flori/json and @ me please? I'll probably be the one fixing it over there anyway.

**Comment by headius** [comment]
Closing as invalid; problem is almost certainly in the json library. We'll fix it there.

**Comment by tqtu** [comment]
The issue in JSON was created. [JSON 515](https://github.com/flori/json/issues/515)
