### ISSUE TITLE
New duplicate warn message in Net::*

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#7613]
If I run rails or something use net/protocol.rb I will see:

```text
/home/enebo/work/release/release/jruby-9.3.10.0/lib/ruby/stdlib/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/enebo/work/release/release/jruby-9.3.10.0/lib/ruby/stdlib/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/enebo/work/release/release/jruby-9.3.10.0/lib/ruby/stdlib/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
```

Warnings should not be there.

**Comment by ahorek** [comment]
net/xxx libraries weren't gemified in 9.3. Older CRuby versions have the same issue...

see https://github.com/mikel/mail/commit/d9d8dcc6bae1774a033ad488cea6217db3a3ebf3 and https://github.com/ruby/net-imap/issues/16#issuecomment-803086765

**Comment by enebo** [comment]
@ahorek  hmm so we have it in core but if someone uses a gem dep they will get it again.  We may be stuck with these warns on anything which pulls in net outside of us.   If this is the case we could conditionalize these constants in the net lib but I think people will not like that idea.

**Comment by ahorek** [comment]
is there the same warning with
```gem 'mail', '2.8.1.rc2'``` ?
that version should include the fix.

or does it come from a different gem?

**Comment by enebo** [comment]
@ahorek yeah.  I don't know wrt to your question but I should figure out when they are first defined in 9.3.  I was seeing this starting up Rails commands so a lot of stuff gets required.

**Comment by headius** [comment]
It sounds like there's no fixing this without diverging on the net/* code we ship, and equivalent CRuby versions have the same issue.
