### ISSUE TITLE
RUBY_REVISION is a short sha, not the full sha like on other Rubies

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#7628]
```
$ ruby -ve 'puts RUBY_REVISION'             
jruby 9.4.1.0-SNAPSHOT (3.1.0) 2023-01-05 006cf2b9c4 OpenJDK 64-Bit Server VM 17.0.5+8 on 17.0.5+8 +jit [x86_64-linux]
006cf2b9c4

Compared to:
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
1a6b16756e0ba6b95ab71a441357ed5484e33498

truffleruby 23.0.0-dev-f9113553, like ruby 3.1.3, GraalVM CE Native [x86_64-linux]
f9113553823106072f9979b72ccaae9a7e372119
```

This notably causes https://github.com/actions/checkout to think it's a branch name and not a commit sha, which made https://github.com/eregon/rubyspec-stats/actions/runs/4106699958/jobs/7085256582 fail.

**Comment by headius** [comment]
I'm pretty sure JRuby was actually the first Ruby impl to put the git SHA in RUBY_REVISION, since we migrated to git earlier than CRuby. I guess when they switched they followed our lead but using the whole SHA hash.

Trivial fix on the way.

**Comment by eregon** [comment]
Thanks!
