### ISSUE TITLE
9.4.1.0: Wrong number of arguments with kwargs when subclassing a java class 

### ISSUE THREAD

**Issue by jimtng** [jruby/jruby#7637]
This failed in `9.4.1.0`, but worked in `9.4.0.0`

```ruby
class A < java.util.ArrayList
  def initialize(foo: nil)
    super()
  end
end

class B < A
  def initialize
    super(foo: nil)
  end
end

B.new
```

It says `(ArgumentError) wrong number of arguments (given 1, expected 0)`

**Comment by enebo** [comment]
A quick note on scope: if ArrayList is replaced by normal Ruby class this error goes away.  This is very likely something to do with how we process this initialize (we process the IR in a special way when we extend a real java type)
