### ISSUE TITLE
Array#fill not compliant with MRI 

### ISSUE THREAD

**Issue by klobuczek** [jruby/jruby#7648]
**Expected Behavior**
```
2.6.4 :001 > [:foo].fill(nil,2,0)
 => [:foo, nil]
```
```
3.1.3 :001 > [:foo].fill(nil,2,0)
 => [:foo, nil]
```

**Actual Behavior**
```
jruby-9.3.9.0 :001 > [:foo].fill(nil,2,0)
 => [:foo]
```
```
jruby-9.4.1.0 :006 > [:foo].fill(nil,2,0)
 => [:foo]
```

**Comment by headius** [comment]
This is fixed by @k77ch7 but wow what a weird case! Did you run into this in real code?

**Comment by klobuczek** [comment]
@headius yes I did here https://github.com/neo4jrb/activegraph/blob/master/lib/active_graph/node/scope.rb#L80
Tried to refactor:
```query_params.fill(nil, query_params.length..proc.arity - 1)```
to simpler
```query_params.fill(nil, proc.arity, 0)```
