### ISSUE TITLE
Regression: Class variables in top level methods broken compared to MRI & 9.3

### ISSUE THREAD

**Issue by byteit101** [jruby/jruby#7656]
**Environment Information**
  
JRuby 9.4.0.0

**Expected Behavior**

```
~/code/jrubyfx(master ✗) irb
3.0.0 :001 > module Kernel; def testk(i=nil); if i.nil?; return @@foob; else @@foob = i; end; end; end
 => :testk 
3.0.0 :002 > testk 9
 => 9 
3.0.0 :003 > testk
 => 9 
3.0.0 :004 > 
````

**Actual Behavior**
```
~/code/jrubyfx(master ✗) irb                  
jruby-9.4.0.0 :001 > module Kernel; def testk(i=nil); if i.nil?; return @@foob; else @@foob = i; end; end; end
 => :testk 
jruby-9.4.0.0 :002 > testk 9
(irb):1:in `testk': class variable access from toplevel (RuntimeError)
	from (irb):2:in `evaluate'
	from org/jruby/RubyKernel.java:1143:in `eval'
	from org/jruby/RubyKernel.java:1586:in `loop'
	from org/jruby/RubyKernel.java:1292:in `catch'
	from org/jruby/RubyKernel.java:1292:in `catch'
	from /home/byteit101/.rvm/rubies/jruby-9.4.0.0/lib/ruby/gems/shared/gems/irb-1.4.1/exe/irb:11:in `<main>'
	from org/jruby/RubyKernel.java:1091:in `load'
	from /home/byteit101/.rvm/rubies/jruby-9.4.0.0/bin/irb:23:in `<main>'
	from org/jruby/RubyKernel.java:1143:in `eval'
	from /home/byteit101/.rvm/gems/jruby-9.4.0.0/bin/jruby_executable_hooks:22:in `<main>'
jruby-9.4.0.0 :003 > 
```

I noticed this because it affects [JRubyFX's Kernel extensions](https://github.com/jruby/jrubyfx/blob/master/lib/jrubyfx/controller.rb#L23). A workaround seems to be to replace cvar usage with `Kernel.class_variable_get(:@@...)`

**Comment by enebo** [comment]
The cause of this is lack of lexical check vs object identity check:

```java
    private static void errorIfTopSelf(ThreadContext context, IRubyObject self, String message) {
        if (context.runtime.getTopSelf() == self) throw context.runtime.newRuntimeError(message);
    }
```

@@foob just happens to being put onto top self so we trigger the error.   I think I can examine staticscope for this check.  Now that I looked at this I am wondering is @@foob in all top scopes is broken or only in the presence of the top being the true root scope (like load within an anonymous module).    I think true root.

**Comment by enebo** [comment]
Hmm significant issue discovered...JITed methods seem to not work in some cases.

**Comment by enebo** [comment]
staticScope is reified from a field and it does not record all scopes down.  I could record if current scope is a top-level scope and replace class/ivar accesses with direct raises?  A lot of work for error messaing.
