### ISSUE TITLE
Unnecessary rewriting of environment variables

### ISSUE THREAD

**Issue by xRandomGuy** [jruby/jruby#767]
Unnecessary rewriting of environment variables - they are written again after reading.

Causing #765

**Comment by rtyler** [comment]
@xRandomGuy I'm trying to understand and come up with a reproduction case for this issue. Do you have a code snippet of what you see failing?

**Comment by enebo** [comment]
No feedback for 3 years.  Reopen if you can provide some more info on this issue.
