### ISSUE TITLE
jruby-9.4.1.0 issues warning about duplicated keys

### ISSUE THREAD

**Issue by klobuczek** [jruby/jruby#7672]
Only jruby-9.4.1.0 issues this warning:
```
>> def m(a:); a; end
=> :m
>> h = { a: 1 }
=> {:a=>1}
>> m(a: 2, **h)
(irb):3: warning: key :a is duplicated and overwritten on line 3
=> 1
```
No other ruby including 9.3.10.0 issues this warning. It became an issue when our logs were filled up with those warnings. 
Note that if `h` is inlined as a literal `**{ a: 1 }` all rubies issue the warning.

See as well: https://github.com/dry-rb/dry-types/pull/454

**Comment by enebo** [comment]
@klobuczek yeah something wrong with our duplicate key warning.  **h and the explicit ```a: 2``` is complaining and it shouldn't.  Thanks for the simple reproduction.

**Comment by enebo** [comment]
Spent some time and my first attempt solves the reported issue but this issue ended up being a bit larger than I thought.  hashes with explicit rest hashes should warn on duplicates:

```ruby
{a: 1, **{a: 2, b: 3, c: 1}, c: 3}
```

This should complain about :a and :c getting duplicated.

```ruby
h = {a: 2, b: 3, c: 1}
{a: 1, **h, c: 3}
```

When the splat refers to  a variable (not literal hash) it will not do duplication check.  So this rule is not
special between hashes using ```**``` and keyword arg calls using ```**```.  It is merely the presence of
how literal the ```**``` is.  Also found in dry tests (changed a bit):

```ruby
hash_schema = {age: 1}
p schema({
           **hash_schema,
           age: 2
         })
```

In this case it is passing a hash (not kwargs) and it is not checking for duplicates.  I am nearly there but
I will continue looking tomorrow.  The hash building code is a bit more complicated than I would like to 
admit :smile:

**Comment by enebo** [comment]
I am asking a question about how to specify a spec which is not supposed to raise a warning and I plan on adding some specs to clarify the difference between using **var and **{} for warnings.  This is fixed and dry-types passes all spec save one where we still fully qualify a path name they expect to be relative (we have an issue open for this already but I do not see it on a quick search).
