### ISSUE TITLE
ruby2_keywords should not warn when using ...

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#7676]
We warn:

```ruby
def array(...)
end
ruby2_keywords :array
```

```text
../snippets/warn6.rb:3: warning: Skipping set of ruby2_keywords flag for array (method accepts keywords or method does not accept argument splat)
```

**Comment by enebo** [comment]
Note: ... decomposes into (*, **, &) and we see the ** and think, "whelp ... we have kwrest better warn".

**Comment by jimtng** [comment]
I just noticed this error on jruby 9.4.8.0, but it might've been there all this time unnoticed.

This is the code that it's complaining about:

```
        klass.class_eval <<~RUBY, __FILE__, __LINE__ + 1
                ruby2_keywords def #{command}(*args, &block)   # ruby2_keywords def on(*args, &block)
                  command(#{value}, *args, &block)             #   command(ON, *args, &block)
                end                                            # end
        end 
```

**Comment by enebo** [comment]
@jimtng I am not seeing this.  I made your script a fully runnable one:

```ruby
class Klass
  def command(*args)
    p args
  end
end
  
command = "on"
value = :ON

Klass.class_eval <<~RUBY, __FILE__, __LINE__ + 1
  ruby2_keywords def #{command}(*args, &block)   # ruby2_keywords def on(*args, &block)
    command(:#{value}, *args, &block)             #   command(ON, *args, &block)
  end                                            # end
RUBY

Klass.new.on
```

There must be a little more to this?

**Comment by headius** [comment]
@jimtng Double check you can reproduce this and open a new issue please. This one was specifically about the `...` form and if you're right about your code it's a different argument structure (`*args`).

**Comment by headius** [comment]
FYI I was also unable to reproduce with @enebo's script on either 9.4.7.0 or 9.4.2.0 (the release before this issue's fix).

**Comment by jimtng** [comment]
@enebo @headius I've opened #8319
