### ISSUE TITLE
java_send on private subclass fails

### ISSUE THREAD

**Issue by byteit101** [jruby/jruby#769]
Original bug: https://github.com/jruby/jrubyfx/issues/39

    #<TypeError: illegal access on 'addListener': Class org.jruby.javasupport.JavaMethod can not access a member of class javafx.beans.property.ReadOnlyListWrapper$ReadOnlyPropertyImpl with modifiers "public">
    org/jruby/java/proxies/JavaProxy.java:347:in `java_send'

the JRubyFX code calls `ro_property_impl_object.java_send :addListener, [ChangeListener], block`
replacing that with `ro_property_impl_object.addListener block` works as expected but warns about it picking one (as expected as there is addListener(ChangeListener) and addListener(invalidationListener))

I have discovered that ReadOnlyPropertyImpl is private and this seems to be the problem

Test cases in original bug. Also manifests itself in Netbeans JRuby 1.7.3 built-in sometimes. not sure how thats related

**Comment by kares** [comment]
added specs with `java_send` against a package / private class https://github.com/jruby/jruby/commit/48c3e583917718113671823fcf4d1e1ae6355c10 ... all seems well (on **1.7.20**)
