### ISSUE TITLE
Update `irb` to version `1.4.2+`

### ISSUE THREAD

**Issue by andsel** [jruby/jruby#7690]
With the commit https://github.com/ruby/irb/commit/54c8df06ff9e161012f89d19a4e3aa2e0e37e1b0 `irb` project removed the inclusion of `rdoc` module, proposed with https://github.com/ruby/irb/pull/393.

The version that ship this commit is the [`1.4.2`](https://github.com/ruby/irb/compare/v1.4.1...v1.4.2).

**Comment by headius** [comment]
This seems pretty benign. +1
