### ISSUE TITLE
Incompatibility with SnakeYAML 2.0

### ISSUE THREAD

**Issue by sschuberth** [jruby/jruby#7703]
Using JRuby 9.4.0.0 in [ORT](https://github.com/oss-review-toolkit/ort), the upgrade of another dependency that itself depends on SnakeYAML [triggers](https://github.com/oss-review-toolkit/ort/actions/runs/4309890762/jobs/7517826748#step:5:711):

> org.jruby.exceptions.LoadError: (LoadError) bad SnakeYAML version 2.0, required 1.21 or higher; check your CLASSPATH for a conflicting jar

That obviously sounds like a bug in the version comparison, as 2.0 *is* higher than 1.21. However, I was unable to find the code in this repo that triggers the exception.

FYI, [here](https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes) are the release note for SnakeYAML 2.0.

**Comment by sschuberth** [comment]
Ah, that check actually [comes from the psych gem](https://github.com/ruby/psych/pull/429/files). The bogus check [was removed by now](https://github.com/ruby/psych/commit/e93e44a627d781960847493a49405e014deb29b8), and the change should be included in [psych version 5.10](https://github.com/ruby/psych/releases/tag/v5.1.0).

**Comment by sschuberth** [comment]
The planned upgrade to psych 5.10 seems to be covered by https://github.com/jruby/jruby/pull/7600.

**Comment by sschuberth** [comment]
Upgrading to JRuby 9.4.1.0 resolves this for me, sorry for the noise.

**Comment by sschuberth** [comment]
> Upgrading to JRuby 9.4.1.0 resolves this for me, sorry for the noise.

For the record, unfortunately AsciidoctorJ seems to be incompatible with JRuby 9.4.1.0 as I'm [running into](https://github.com/oss-review-toolkit/ort/actions/runs/4311764665/jobs/7521570467#step:5:639) `java.lang.NoSuchFieldError: STRIO_READABLE`.

**Comment by kares** [comment]
> AsciidoctorJ seems to be incompatible with JRuby 9.4.1.0 

as fas as I understand Asciidoctor embeds JRuby, I am not sure "running with a different JRuby" is smt officially supported.
from the trace you got it does seem like 2 versions of jruby (runtime) classes got mixed up ...
