### ISSUE TITLE
Dead code in Enumerator

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7710]
Due to the removal of 2- and 3-arity forms of Enumerator#initialize, we now have a lot of dead code in RubyEnumerator.

It appears these forms were deprecated in https://github.com/ruby/ruby/commit/c73b6bd7ebd01133538c645566944132dbde4d13 and eventually removed in https://github.com/ruby/ruby/commit/fa356a798aefc20725467d4fad02df8325d63e71.

There's a lot of logic here that can be deleted, spanning the Java and Ruby parts of Enumerator.

Discovered while working on the fix for #7708.

**Comment by HyunPark21** [comment]
Hi, my name is Hyun Park and I want to work on this issue. Can you assign me to contribute to this problem?

**Comment by yykuk2003** [comment]
Hi could you please give me an authorization to make a PR for this issue?

**Comment by headius** [comment]
You don't need authorization to create a PR. Are you having some trouble?

**Comment by headius** [comment]
There's actually not as much to do here as I thought. The logic that accepts `methodArgs` is still in use internally so none of that logic can go away.
