### ISSUE TITLE
`Dir.home` is no longer compatible with CRuby after JRuby 9.3

### ISSUE THREAD

**Issue by h-r-k-matsumoto** [jruby/jruby#7735]
**Environment Information**

JRuby version:
jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 25.362-b09 on 1.8.0_362-b09 +jit [x86_64-linux]

Operating system and platform:
Linux 96d20f512b68 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

I use docker images `jruby:9.4` and `jruby:9.3`

**Expected Behavior**

`Dir.home` with nil returns home directory of current user.
I expect JRuby to be the same behavior.

```bash
$ docker run -it --rm ruby:3.2
irb(main):001:0> Dir.home nil
=> "/root"
irb(main):002:0>
```
https://ruby-doc.org/3.2.1/Dir.html#method-c-home

**Actual Behavior**

After JRuby 9.3, Dir.home returns an error if user is nil.

```bash
$ docker run -it --rm jruby:9.4
irb(main):001:0> Dir.home nil
org/jruby/RubyDir.java:635:in `home': no implicit conversion of nil into String (TypeError)
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1143:in `eval'
	from org/jruby/RubyKernel.java:1586:in `loop'
	from org/jruby/RubyKernel.java:1292:in `catch'
	from org/jruby/RubyKernel.java:1292:in `catch'
	from /opt/jruby/lib/ruby/gems/shared/gems/irb-1.4.2/exe/irb:11:in `<main>'
	from org/jruby/RubyKernel.java:1091:in `load'
	from /opt/jruby/bin/irb:23:in `<main>'
irb(main):002:0>
```

**Comment by h-r-k-matsumoto** [comment]
This changes impact codes such as below.
https://github.com/fakefs/fakefs/blob/v2.4.0/lib/fakefs/dir.rb#L156-L158

**Comment by headius** [comment]
Reproduced. It seems like we check for a null/nil home dir for the zero-argument form but not for the one-argument form.

https://github.com/jruby/jruby/blob/071b1788681cab7969a3b1a76dae1ef40d120e62/core/src/main/java/org/jruby/RubyDir.java#L1153-L1170
