### ISSUE TITLE
Running JRuby 9.4 and Puma with SSL

### ISSUE THREAD

**Issue by treviateo** [jruby/jruby#7736]
Hi All,

I am trying to run JRuby 9.4.2.0 with ruby 3.1 and puma 5.6.5 with SSL. 

**System Configuration:**
JRuby: 9.4.2.0
Puma: 5.6.5
Open JDK: 1.8.0_322

I downloaded the sample keystore from _https://github.com/puma/puma/blob/429d17bca11f8d22dcc1434c9f6ac826a06fa836/examples/puma/keystore.jks_, password blahblah. And converted it to PKCS12 format.

The keystore looks ok as following:
<img width="530" alt="keystore" src="https://user-images.githubusercontent.com/129143940/228134030-c784608d-629a-49a7-bed8-2f9ced5d6b55.png">

When running JRuby with Puma and SSL binding as following:
**C:\jruby-9.4.2.0\bin\jruby.exe C:\[path_to_puma]\bin\puma -b "ssl://127.0.0.1:9292?keystore=C:\.ssl\keystore&keystore-pass=blahblah&verify_mode=none" -q -p 9191**

the server starts up ok as following:
<img width="332" alt="console1" src="https://user-images.githubusercontent.com/129143940/228134199-1afa6bd9-0557-4b70-88f5-6c60e7d4f20c.png">
<img width="412" alt="console2" src="https://user-images.githubusercontent.com/129143940/228134228-c81137e4-ace2-4db9-92ea-9243d755967b.png">

However when trying to curl (_curl https://localhost:9292 -v_), it failed as following:
<img width="308" alt="curl" src="https://user-images.githubusercontent.com/129143940/228134375-1d6f2de6-fed5-4c10-a955-34a08154aa94.png">

And on the server console, this error keep popping up everytime the curl command is entered:
**Error reached top of thread-pool: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer; (Java::JavaLang::NoSuchMethodError)**
<img width="854" alt="error" src="https://user-images.githubusercontent.com/129143940/228141841-55408a8b-3fb0-49b8-81c5-4bb6f24a9763.png">

Does anyone have a hunch about this and could help with this issue? Thank you.

**Comment by ahorek** [comment]
it's a known incompatibility with binaries compiled on a newer Java, see https://github.com/jruby/jruby/pull/5499

but this has to be fixed in the Puma repo https://github.com/puma/puma/blob/master/ext/puma_http11/org/jruby/puma/MiniSSL.java#L76

for now, the easiest workaround is upgrading the Java version to 9+ if you can...

**Comment by treviateo** [comment]
Hi @ahorek, thank you for your response.

I have tried with open JDK Amazon Corretto 11.0.18 as following:
<img width="332" alt="jdk" src="https://user-images.githubusercontent.com/129143940/228377010-188973c9-740e-46fc-9be0-acc36617a17f.png">
But still encountered the same issue.

For JRuby 9.4.2, I installed from the windows executable file (https://s3.amazonaws.com/jruby.org/downloads/9.4.2.0/jruby_windows_x64_9_4_2_0.exe). Just wonder whether this executable file is compiled with which version of Java? Or does it matter? 

Thank you.

**Comment by ahorek** [comment]
does `jruby -v` also print java 11?

either way, it's a bug and the fix should be trivial. I'm not sure if 5.6.x is still supported, it could take some time for a new release...

**Comment by treviateo** [comment]
Hi @ahorek,

It seems jruby -v print out java 1.8 as following:

**jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 25.322-b06 on 1.8.0_322-b06 +jit [x86_64-mswin32]**

Tried with Puma 6.1.1 and encountered the same issue. May i know which version of Puma is good to try ?

Thank you.

**Comment by ahorek** [comment]
could you test https://github.com/puma/puma/pull/3109 ?

```gem "puma", git: "https://github.com/ahorek/puma.git", branch: "java8"```

**Comment by treviateo** [comment]
Hi @ahorek,

Try to run bundle install after adding **gem 'puma', git: 'https://github.com/ahorek/puma.git', branch: 'java8'** and encountered the attached error: 
[puma_build_error.txt](https://github.com/jruby/jruby/files/11095127/puma_build_error.txt)

Did i miss anything? Thank you.

**Comment by ahorek** [comment]
ahh, Puma doesn't support building the JRuby version directly from the git repo. Never mind, here's a manual build:
https://github.com/ahorek/puma/blob/build/puma-6.1.1-java.gem

```gem install puma-6.1.1-java.gem```

**Comment by treviateo** [comment]
Hi @ahorek,

Adding this line on Gemfile:
gem 'puma', source: 'https://github.com/ahorek/puma/blob/build/puma-6.1.1-java.gem'

and bundle install run ok with Gemfile.lock looks as this:
GEM
  remote: https://github.com/ahorek/puma/blob/build/puma-6.1.1-java.gem/
  specs:
    puma (6.1.1-java)
      nio4r (~> 2.0)

Puma output on startup:
<img width="299" alt="puma6 1 1" src="https://user-images.githubusercontent.com/129143940/228393353-2c0ce1f8-6bf1-4666-9b36-53c540e073d1.png">
<img width="416" alt="ssl" src="https://user-images.githubusercontent.com/129143940/228393977-62a7102c-b0d1-4fa6-9f23-3a8e35870ada.png">
However still encounter the same issue on _curl https://127.0.0.1:9292 -v_
Error reached top of thread-pool: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer; (Java::JavaLang::NoSuchMethodError)
<img width="477" alt="error_puma_6 1 1" src="https://user-images.githubusercontent.com/129143940/228393738-9454dc90-387a-40d2-ba6c-52c0b4c3c69b.png">

Thank you.

**Comment by ahorek** [comment]
ok, but it's a different place, maybe there's another gem with the same issue? (not clear where it comes from without a proper backtrace)

I suspect it could be nio4j, basically the same story:
https://github.com/socketry/nio4r/blob/main/ext/nio4r/org/nio4r/ByteBuffer.java#L59
https://github.com/socketry/nio4r/blob/main/rakelib/extension.rake#L7

**Comment by ahorek** [comment]
@treviateo both puma & nio4j were released with compatibility fixes. Could you test it again if you still getting the same error?

**Comment by ahorek** [comment]
we need a more verbose backtrace. What gem is using the bytebuffer and where. It could also be some piece of code in JRuby itself. I'll see if I can simulate the issue tomorrow.

**Comment by ahorek** [comment]
fixed by https://github.com/jruby/jruby/pull/7742
