### ISSUE TITLE
Failure to load FFI gives an outdated message

### ISSUE THREAD

**Issue by enebo** [jruby/jruby#7760]
FFIService.  I would just change this but I feel there is an opportunity to give a more informative reason why it could not load:

```java
        RubyModule ffi = runtime.defineModule("FFI");
        try {
            Factory.getInstance().init(runtime, ffi);
        } catch (Exception e) {
            throw runtime.newLoadError("Could not load FFI Provider: " + e.getLocalizedMessage()
                    + " See http://jira.codehaus.org/browse/JRUBY-4583");
        }
```

**Comment by headius** [comment]
I found a wayback of the original bug, which is mostly talking about needing binaries built for new platforms:

https://web.archive.org/web/20150520231349/http://jira.codehaus.org/browse/JRUBY-4583

Why did it fail for you? We could direct it to a wiki page about why the FFI subsystem might not be able to load, perhaps.

**Comment by enebo** [comment]
@headius we had a recent bug and they reported it with that error message.

**Comment by enebo** [comment]
This is not complicated but I don't know of a good error message.
