### ISSUE TITLE
Output unreliable from spawned processes

### ISSUE THREAD

**Issue by dmarcotte** [jruby/jruby#779]
(This is probably a known issue, but I didn't see a issue for it.  I wanted to document it here so that I can refer to in the tags I'm going to add to the specs it affects.)

There seems to be a race to capture the output of spawned processes in the tests.  The race is lost much more often on Linux, but can also manifest itself on Mac.

Looking at the code, it smells like this might be due to how the `output_to_fd` matcher works in combination with [the known race conditions which also lead to the inappropriate echild errors](http://jira.codehaus.org/issues/?jql=status%20in%20%28Open%2C%20Reopened%29%20AND%20text%20~%20%22echild%22).  Haven't been able to prove that yet though...

Anyhow, here's a summary of how exactly this manifests in the tests:

Here's a case from Travis where the output goes to the test's stdout rather than being consumed by the test
(from [this log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/7496278/log.txt)).  Note how the `foo` the test is outputting is appended to the test output (`element to a Stringfoo`) rather than being received by the test matcher, which gets `""`:
```
[java] Kernel#spawn with a command array
[java] - does not subject the arguments to shell expansion
[java] - preserves whitespace in passed arguments
[java] - calls #to_str to convert the first element to a String
[java] - calls #to_str to convert the second element to a Stringfoo
[java]  (FAILED - 1)
    ---SNIP---
[java] 1)
[java] Kernel#spawn with a command array calls #to_str to convert the second element to a String FAILED
[java] Expected (STDOUT): "foo\n"
[java]           but got: ""
```

Alternatively, there are also cases where a previous test's output is still around to be consumed by the next test (from [this log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/7569314/log.txt)).  Note how the directory listing which is the output of `subjects the specified command to shell expansion` (which passed) interferes with the `foo` that `calls #to_str to convert the argument to a String` is trying to validate:

```
[java] Process.spawn with a single argument
[java] - subjects the specified command to shell expansion
[java] - calls #to_str to convert the argument to a String (FAILED - 1)
    ---SNIP---
[java] 1)
[java] Process.spawn with a single argument calls #to_str to convert the argument to a String FAILED
[java] Expected (STDOUT): "foo\n"
[java]          but got: "COPYING LEGAL LICENSE.RUBY README.md Rakefile antlib bench bin build build.xml build_lib cext default.build.properties docs docs.iml findbugs.xml gems install ivy jruby-common.iml jruby-complete.iml jruby-core.iml jruby-dist.iml jruby-rake-plugin.iml jruby-stdlib.iml jruby.bnd.template jruby.iml lib man.iml maven nbproject netbeans-ant.xml pom.xml rakelib rubyspec_temp samples shared.iml spec spi src test tool\nfoo\n"
```

Hopefully that isn't too verbose and helps a bit... a pull tagging specs which are susceptible to this is on its way.

**Comment by matthewbloch** [comment]
This bug (thanks JDK) is the reason Redmine's SCM integration breaks when running under JRuby - http://www.redmine.org/boards/1/topics/38861 . @headius has written about this before but I'm not sure there's much that can help since he wrote http://blog.headius.com/2013/06/the-pain-of-broken-subprocess.html

**Comment by jsvd** [comment]
Hit the issue on elasticsearch/logstash again using jruby 1.7.{17,19}. 
9.0.0.0pre1 is not affected, from what I tested using @colinsurprenant' script above.

**Comment by headius** [comment]
JRuby 9000 has completely rewritten process-spawning logic to match MRI (direct ports in many cases, but using posix_spawn). I would be surprised if it's not considerably more reliable now since we're routing around the JDK's nonsense.

Going to optimistically call this fixed in 9k.
