### ISSUE TITLE
Small documentation issues regarding java options

### ISSUE THREAD

**Issue by mrckzgl** [jruby/jruby#7818]
# Wiki issue

In https://github.com/jruby/jruby/wiki/JRuby-Java-Options-Files and https://github.com/jruby/jruby/wiki/ConfiguringJRuby is mentioned to use `-J<option>` to pass options to the JVM. However, the example in the second url is `-J-Xmx2G` which would translate to the generic case as `-J-<option>`. Is that a bug in the docs, or are both valid `-J-Xmx2G` and `-JXmx2G`?  In the latter case it would also be nice to be fully documented.

EDIT: Ah sorry, realize how that is meant now. `<option>` includes the `-`. This is needed, as there are options which include two minuses. So this is not an issue anymore I guess. Except, it would be nice to include the example in the first wiki url too, or even explicitly specify that `<option>` includes all minuses? The other issues below, however, are independent thereof and still existing.

# Command line help issues

Using `jruby 9.4.1.0 (3.1.0) 2023-02-07 237d5fa5f4 Java HotSpot(TM) 64-Bit Server VM 15.0.2+7-27 on 15.0.2+7-27 +jit [x86_64-linux]` there are a few minor issues with the `--help` output:

```
-J[java option]                                     pass an option on to the JVM (e.g. -J-Xmx512m)/nuse --properties to 
                                                       JRuby properties run 'java -help' for a list of other Java options
```
is `/n` meant to be a line break `\n` ? But still, further `use --properties to JRuby properties run 'java -help' for a list of other Java options` is no proper gramatically correct sentence. Seems these are two sentences. But even then, the first is no correct sentence (`use --properties to JRuby properties`).

```
--properties                                        List all configuration Java properties (prepend "jruby." when 
                                                       directly to Java)
```
`(prepend "jruby." when directly to Java)` does not make sense / is no proper sentence. But I would probably omit that bracket here, as it only makes sense in combination with the output of `--properties`.

Looking at `--properties` reveals another little inconsistency:

```
# Specify them by passing -X<property>=<value>
#   or if passing directly to Java, -Djruby.<property>=<value>
```
Is it really `-Djruby.<property>=<value>`? That would contradict `(prepend "jruby." when directly to Java)` and also `-D` is not listed as command line option via `--help` at all. Is it possible that `-Xjruby.<property>=<value>` is meant?

Last but not least one substantive question in this regard: What is the difference of specifying a java option via `-X<property>=<value>` vs. `-[D/X]jruby.<property>=<value>` ?

**Comment by headius** [comment]
> `<option>` includes the -

I don't think there's anything else to do here. Both pages refer to `-J<option>` and the "ConfiguringJRuby" page includes examples. If you have some suggested text for the "JRuby Java Options Files" page, let us know!

> is /n meant to be a line break

Looks like this was a change from when we manually formatted the help lines to a new pageable formatter in #7458. I will modify it to use semicolons so as not to interfere with the paging output.

> (prepend "jruby." when directly to Java) does not make sense

The `-Xfoo.bar` format is just a shortcut for `-J-Djruby.foo.bar`. I will clean up the text a bit to make this clearer.
