### ISSUE TITLE
JRuby 1.7.4 Regression, Failing to find installed gems from bin commands

### ISSUE THREAD

**Issue by zdennis** [jruby/jruby#782]
The following works with JRuby 1.7.3 but fails with JRuby 1.7.4:
- create a Gemfile with "warbler" in it
- execute: `bundle install --path vendor`
- execute: `vendor/jruby/1.9/bin/warble`

Expected output (with JRuby 1.7.3): 

```
warble aborted!
No executable script found
```

Actual output (with JRuby 1.7.4):

```
Gem::LoadError: Could not find warbler (>= 0) amongst [bouncy-castle-java-1.5.0147, 
bundler-1.3.5, jruby-launcher-1.0.16-java, jruby-openssl-0.8.8, rake-10.0.4, rake-10.0.3, 
rubygems-bundler-1.1.1, rvm-1.11.3.8]
to_specs at /Users/zdennis/.rvm/rubies/jruby-1.7.4/lib/ruby/shared/rubygems/dependency.rb:247
to_spec at /Users/zdennis/.rvm/rubies/jruby-1.7.4/lib/ruby/shared/rubygems/dependency.rb:256
   gem at /Users/zdennis/.rvm/rubies/jruby-1.7.4/lib/ruby/shared/rubygems.rb:1231
(root) at vendor/jruby/1.9/bin/warble:22
```

**Comment by aplatypus** [comment]
I keep seeing this message on JRuby 9.0 ...

     WARN: Unresolved specs during Gem::Specification.reset

These GEM-s are already installed, the whole is very confusing.

      WARN: Unresolved specs during Gem::Specification.reset:
           json (>= 1.7.7, ~> 1.7)
           minitest (~> 5.1)
     WARN: Clearing out unresolved specs.
     Please report a bug if this causes problems.
                   run  bundle update from "."
     Fetching gem metadata from http://rubygems.org/........
     Fetching version metadata from http://rubygems.org/...
     Fetching dependency metadata from http://rubygems.org/..
     Resolving dependencies...
     Using i18n 0.7.0
      . . .

**Comment by kares** [comment]
this is issue should no longer be relevant -> if so please confirm it still mis-behaving using latest JRuby 1.7
