### ISSUE TITLE
FFI Support for aarch64-windows

### ISSUE THREAD

**Issue by ntkme** [jruby/jruby#7843]
I've submitted PRs for adding FFI support on aarch64-windows:

- https://github.com/jnr/jffi/pull/144
- https://github.com/jnr/jnr-ffi/pull/330
- https://github.com/ffi/ffi/pull/1035

JRuby will need to update its dependencies once the PRs are merged and new releases are cut.

**Comment by headius** [comment]
Finally circling back to this, sorry for delays!

**Comment by headius** [comment]
I have merged the jnr-ffi PR and posted a jffi binary for you to verify. We'll also want to update our copy of the ffi gem so we can pull in your changes there.

**Comment by ntkme** [comment]
Thanks for merging the PRs. I tested the JRuby nightly from yesterday and indeed the only patch I needed was the type definition in ffi gem.

**Comment by headius** [comment]
Thank you for confirming! I have pinged @larskanis on your FFI PR about getting those changes released.

**Comment by ntkme** [comment]
FFI gem has a new release. I submitted a PR to update jruby: https://github.com/jruby/jruby/pull/7941
