### ISSUE TITLE
Wrong interpretation of multi-expression when clause

### ISSUE THREAD

**Issue by Confusion** [jruby/jruby#7848]
**Environment Information**
* jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 17.0.7+7-Ubuntu-0ubuntu122.04.2 on 17.0.7+7-Ubuntu-0ubuntu122.04.2 +jit [x86_64-linux]
* Linux photon 5.15.0-74-generic Ubuntu SMP

**Expected Behavior**
Given a `foo.rb` with contents
```ruby
case
when (x = 1; false) then puts 'unexpected_result'
else raise
end
```
Ruby 3.1.3 results in the expected
```
$ ruby foo.rb
foo.rb:3:in `<main>': unhandled exception
```

**Actual Behavior**
JRuby 9.4.3.0 results in
```
$ ruby foo.rb
unexpected_result
```

**Notes**
* The result of the compound `when` clause seems to be `1`, or at least something truthy, instead of `false`. However, any change to the expression, such as adding a `.tap` to print the result of the parenthesized expression, changes the result.
* This is with both Racc 1.6.0 and 1.7.1; it doesn't seem to be a parsing error.
* This also happens if you put the code in a function, class, etc. It's not some 'top-level' peculiarity.

**Comment by enebo** [comment]
9.3 also behaves this way which is not too surprising.  Depending on how similar IR when code is this will likely also get backported.
