### ISSUE TITLE
org.jruby.RubyLoadError getCause returns itself

### ISSUE THREAD

**Issue by cstamas** [jruby/jruby#7861]
Seems some JRuby exceptions are (misusing) Throwable.getCause, by returning "this" instead null. Throwable.getCause should return some other instance, or null, never this. Moreover, this really smells like some method override in some Throwable that does not do like all throwables do:

```
public synchronized Throwable getCause() {
    return (cause==this ? null : cause);
}
```

For original report, see this:
https://issues.apache.org/jira/browse/MNG-7846

**Comment by abelsromero** [comment]
We did some digging from the other issue opened https://github.com/asciidoctor/asciidoctorj/issues/1231#issuecomment-1643564402 and suspect the source could be https://github.com/jruby/jruby/blob/73d3c1e3b5d0b6f5b774e32c30303a8d2bddb3c6/core/src/main/java/org/jruby/RubyException.java#L411-L413
