### ISSUE TITLE
Potential copyleft effect of GPL licensed file 

### ISSUE THREAD

**Issue by rahulmohang** [jruby/jruby#7874]
Hi, 

The file, https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/parser/JavaSignatureParser.y is licensed only under the GPL. 

Do you think that the copyleft effect of GPL is going to affect the rest of the program, thereby making the multiple license option irrelevant? 

I think that it may not be the case, but asking just to be sure.

**Comment by enebo** [comment]
My understanding is unless the input is copied "enough" to the output that is generated then the output is not subject to the inputs license (akin to a tool vs code).   If we were concerned enough about this we could move all "body" code from the productions into another file but most of the file is not the input.

**Comment by rahulmohang** [comment]
The following statement suggests that the file itself is licensed under the GPL:

" * The output this tool generates is subject to our tri-license (GPL,LGPL,
 * and EPL), but this source file itself is released only under the terms
 * of the GPL."

Usually, when such files are used, they may have a license statement for an exception - like the GPL with bison exception.

**Comment by headius** [comment]
The grammar is GPL, that is clear.

Our parser generator, a modified version of Jay, is derived from Berkeley yacc, and I believe it is also BSD-licensed, so there's no problem there.

Some content is copied from the grammar to the java source, but it's nearly all structural in nature. The grammar is 627 lines and the java is 1304 lines, and the diff between them shows that nearly all code from the grammar has been replaced by generated code from Jay.

https://gist.github.com/headius/8619372bf8b363b9aa8e415893655f70

In fact, the only sections of copied code that aren't just brace characters are the package definition, the imports, a singleton object declaration, and a few lines defining a parser entry point method... a total of **seven** non-whitespace lines.

I would say that does not qualify as copying "enough" in the spirit of the GPL and the resulting parser is not encumbered whatsoever.

If the inclusion of the .y file is a concern, we could simply remove it from the build, but it is not used at runtime and does not link with any other code.

**Comment by rahulmohang** [comment]
Thank you for the response.
