### ISSUE TITLE
(master) frozen string errors with `--debug`

### ISSUE THREAD

**Issue by flavorjones** [jruby/jruby#7924]
**Environment Information**

Using jruby HEAD:

```
$ bin/jruby -v
jruby 9.4.4.0-SNAPSHOT (3.1.4) 2023-06-18 656f9d6570 OpenJDK 64-Bit Server VM 11.0.20.1+1-post-Ubuntu-0ubuntu122.04 on 11.0.20.1+1-post-Ubuntu-0ubuntu122.04 [x86_64-linux]

$ uname -a
Linux juno 6.2.0-1011-lowlatency #11~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 16:22:57 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Reproduction**

File `foo.rb`:

```ruby
# frozen_string_literal: true

puts RUBY_DESCRIPTION

s = +"hello"
puts s.frozen?
s.force_encoding(::Encoding::ASCII_8BIT)
```

When run with `bin/jruby foo.rb`:

```
jruby 9.4.4.0-SNAPSHOT (3.1.4) 2023-06-18 656f9d6570 OpenJDK 64-Bit Server VM 11.0.20.1+1-post-Ubuntu-0ubuntu122.04 on 11.0.20.1+1-post-Ubuntu-0ubuntu122.04 [x86_64-linux]
false
```

When run with `bin/jruby --debug foo.rb`

```
jruby 9.4.4.0-SNAPSHOT (3.1.4) 2023-06-18 656f9d6570 OpenJDK 64-Bit Server VM 11.0.20.1+1-post-Ubuntu-0ubuntu122.04 on 11.0.20.1+1-post-Ubuntu-0ubuntu122.04 [x86_64-linux]
false
FrozenError: can't modify frozen String, created at foo.rb:5
  force_encoding at org/jruby/RubyString.java:6663
  force_encoding at org/jruby/RubyString.java:6659
          <main> at foo.rb:7
```

This error does not occur with jruby-9.4.2.0.

This was discovered by upstream nokogiri integration testing: https://github.com/sparklemotion/nokogiri/actions/runs/6076083505/job/16483500598

**Comment by flavorjones** [comment]
I bisected, this behavior changed with 11418c39 /cc @headius

**Comment by headius** [comment]
Ahh good catch. The logic for `+@` likely needs to be updated to check frozenness correctly. Interesting that this was not caught by any tests or specs but perhaps we exclude one that does.

**Comment by headius** [comment]
Yeah oversight on my part... I overrode the RubyString.frozenCheck behavior, but did not actually mark the DebugFrozenString object as frozen itself.
