### ISSUE TITLE
File.chown throws "SystemCallError:Unknown error (SystemCallError)" at Windows11 on Arm64

### ISSUE THREAD

**Issue by rammpeter** [jruby/jruby#7937]
**Environment Information**
- jRuby 9.4.3.0
- Windows 11 preview on Arm64  build 25915.1000 rs_prerelease

**Expected Behavior**
`File.chown(0, 0, 'C:/....');` on existing writable file should not throw exception like it does on other OS including Windows 10 on x86_64 

**Actual Behavior**
Executing
```
File.chown(0, 0, 'C:/.....');
```
for an existing file or dir throws the exception `SystemCallError: Unknown error (SystemCallError) - No message available`.

Reproduced by running ` java -jar jruby-core-9.4.3.0-complete.jar` and typing the command `File.chown(0, 0, 'C:/.....');`.

The original problem occurred because a  RubyOnRails app running in jRuby failed on Windows 11 at ARM64 CPU at call of File.chown.
See also: https://github.com/rails/rails/issues/49295

**Comment by headius** [comment]
JRuby 9.4.3.0 does not have native support for Windows/AArch64... but good news, JRuby 9.4.4.0 will!

See #7843 

We're hoping to ship 9.4.4.0 in the next week or two. Perhaps you could try a nightly build and see if it works for you?

**Comment by headius** [comment]
Going to hope this is fixed by the new aarch64 FFI backend.
