### ISSUE TITLE
fnmatch not matching glob syntax in 9.3.8 but it did in 9.2.20.1

### ISSUE THREAD

**Issue by shivanesabharwal** [jruby/jruby#7942]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc):
```
jruby 9.3.8.0 (2.6.8) 2022-09-28 ffffffffff OpenJDK 64-Bit Server VM 11.0.15+0-adhoc..source on 11.0.15+0-adhoc..source +jit [x86_64-linux]

```
* Operating system and platform (e.g. `uname -a`)

```
Linux 6.3.11-1rodete2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.11-1rodete2 (2023-08-24) x86_64 GNU/Linux
```

**Expected Behavior**

On Jruby 9.2.20.1 in an irb session:
```
File.fnmatch?('employees2*.view*l', 'employees2.view.lkml', File::FNM_PATHNAME)
=> true
```

**Actual Behavior**
I expected this to continue returning true. However after upgrade to 9.3.8.0 we see:
```
File.fnmatch?('employees2*.view*l', 'employees2.view.lkml', File::FNM_PATHNAME)
=> false
```

**Comment by headius** [comment]
I see a few minor changes in `fnmatch` recently, but nothing that should cause this sort of change.

Perhaps you can try to bisect it?

**Comment by shivanesabharwal** [comment]
Interestingly, when I check out the tag associated with JRuby 9.3.8.0, I am unable to reproduce the issue.

The only difference I can see is the value for `RUBY_VERSION` in the `irb` session.

in the JRuby repo:
```
shivane@shivanes:~/jruby$ irb
irb(main):001:0> RUBY_VERSION
=> "3.1.2"
```

In my project:
```
irb(main):002:0> RUBY_VERSION
=> "2.6.8"
```

I'm not sure I understand the relationship between the JRuby version and the Ruby version. Do you have any pointers here?

**Comment by shivanesabharwal** [comment]
I thought the `jruby` package fixes the ruby version used but that doesn't seem to be the case. Also running into issues building the jruby jar locally, which is preventing me from git bisecting on my clone of this repo. I don't have much else in the way of contributing.

**Comment by ahorek** [comment]
it's this change https://github.com/jruby/jruby/pull/6231 + a dirty fix https://github.com/jruby/jruby/pull/7947 :)

> Interestingly, when I check out the tag associated with JRuby 9.3.8.0, I am unable to reproduce the issue.
> The only difference I can see is the value for RUBY_VERSION in the irb session.

Make sure you aren't testing system Ruby... JRuby binaries are in the "bin" folder. Try it with `./bin/jruby -S irb`

**Comment by headius** [comment]
@ahorek for the win! The fix is dirty mostly because we can't `goto` as in C. I'll add some comments or try to refactor slightly to make it more obvious why we have this code twice.

**Comment by headius** [comment]
@shivanesabharwal We backport fixes on request, or if users provide a PR that speeds up the process. Perhaps you could try to make a PR for the jruby-9.3 branch based on the patch @ahorek submitted?

**Comment by shivanesabharwal** [comment]
looks like @ahorek beat me to it. Thanks! Will look out for merge.
