### ISSUE TITLE
Deployment failing after upgrading version from 9.3.6.0 to 9.3.9.0

### ISSUE THREAD

**Issue by TripToKasol** [jruby/jruby#7963]
We have recently upgraded the version from 9.3.6.0 to 9.3.9.0 and the deployment has started failing causing the server to not come up. Build is completing successfully. GLIBC version is 2.26. Not sure why this minor version upgrade is failing the deployment. Any dependency update or something is required with this change? Can anyone please help.

**Comment by headius** [comment]
Can you provide more details on how it is failing? Do you have error messages you can share?

**Comment by headius** [comment]
If you can provide more info I would be happy to help!
