### ISSUE TITLE
Build, test failures when build directory contains special characters

### ISSUE THREAD

**Issue by jcharaoui** [jruby/jruby#7983]
On Debian, the build directory names often contain the package name with the version number appended. That version number may contain a `+` character, which has special meaning in a regular expression or URI.

When building JRuby in a directory whose tree contains a plus sign (`+`), bad things happen:

- The rubygem bin stubs are not copied in the right directory:

```
--- gem racc-1.6.0 ---                                                                                    
copy gem content to /jruby+ds/lib/ruby/stdlib                                                             
 copying: /jruby+ds/lib/target/rubygems/gems/racc-1.6.0-java/lib/racc to /jruby+ds/lib/ruby/stdlib        
 copying: /jruby+ds/lib/target/rubygems/gems/racc-1.6.0-java/lib/racc.rb to /jruby+ds/lib/ruby/stdlib                                                                                                                
copy executable /jruby+ds/lib/target/rubygems/bin/racc to /jruby+ds/bin                                                                                                                                              
copy racc to /jruby+ds/lib/ruby/gems/shared/gems/jruby+ds/lib/target/rubygems/gems/racc-1.6.0-java/bin/racc                                                                                                          
copy to specifications/default: racc-1.6.0-java.gemspec
```
This can be fixed in `lib/pom.rb` by replacing `source.sub( /#{gems}/, '')` with `source.sub( gems, '')`

- `JarResourceTest#testCreateJarResourceWithSpaceCharInPath` fails

This can be worked around by replacing `+` with `%2b` in the resource path.

**Comment by jcharaoui** [comment]
I haven't investigated other special characters which are legal in a path name, but might be interpreted by other parts of the build and test process, so the issue description isn't comprehensive by any means.

**Comment by headius** [comment]
I believe it would break on any regex character in the path, like how Windows throws "Program Files (x86)" at us.

I was unable to reproduce it with a simple `a+b` in the path, but perhaps it requires more to really break it:

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.643 s
[INFO] Finished at: 2023-10-26T01:07:10-05:00
[INFO] ------------------------------------------------------------------------
[] jruby $ pwd
/Users/headius/work/jruby/a+b/jruby
```

The easy fix should be to `Regexp.quote(gems)`. I'll push a PR with that and we can see how it works for you.

**Comment by jcharaoui** [comment]
> I was unable to reproduce it with a simple a+b in the path, but perhaps it requires more to really break it:

Oh the build doesn't *noisily* break, but if you look in the resulting jar's GEM_HOME, you'll see how the directory tree is broken. The build log at the `install_gems` execute step of jruby-stdlib would also give an indication of the issue.
