### ISSUE TITLE
Update Maven stack with 9.4.5.0

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7987]
With the removal of the FilenoUtil warning in #7970 we should update the Maven/Ruby stack with JRuby 9.4.5.0, so that builds using that stack will not generate these warnings (which are hard to work around and most people won't bother).

This is not really a 9.4.5.0 but but marking as such so we remember to update maven stack once 9.4.5.0 is released.

**Comment by headius** [comment]
jruby-maven-plugins 3.0.2 and mavengem 2.0.2 have been released to central. Polyglot PR to update both and JRuby is here: https://github.com/takari/polyglot-maven/pull/273

**Comment by cstamas** [comment]
polyglot 0.5.0 released

**Comment by headius** [comment]
@cstamas Thank you!
