### ISSUE TITLE
New MRI test failures on less common architectures

### ISSUE THREAD

**Issue by jcharaoui** [jruby/jruby#8005]
Since JRuby 9.4, it seems many MRI tests now fail on architectures other than i386 and amd64.

For example, running `mri-core` on `s390x` yields dozen of errors such as this:

```
  1) Failure:
TestThread#test_thread_value_in_trap [/tmp/autopkgtest.pNZ426/autopkgtest_tmp/test/mri/ruby/test_thread.rb:1013]:
assert_separately failed with error message
pid 85599 exit 0
| failed to load native console support: native console only supported on i386, x86_64 and powerpc64
| /usr/share/jruby/lib/ruby/stdlib/io/console/ffi/stty_console.rb:78: warning: assigned but unused variable - ypixel
| /usr/share/jruby/lib/ruby/stdlib/io/console/ffi/stty_console.rb:78: warning: assigned but unused variable - xpixel
| failed to load stty console support: native console only supported on i386, x86_64 and powerpc64
| io/console not supported; tty will not be manipulated
```

A full test run log on `s390x` can be found at https://gitlab.torproject.org/lavamind/jruby-ci/-/jobs/402329/raw

This appears to be related to the fact that `assert_separately()` now relies on `io/console`, which itself has limited support for other architectures.

**Comment by headius** [comment]
You're right; testing across those other platforms is very weak right now. We need some help figuring out how to improve that. I believe we had another issue filed with some pointers to using free build farms to do external testing of JRuby on unusual platforms.

**Comment by headius** [comment]
@jcharaoui I merged ruby/io-console#56 so once we get a release of that it should help.

**Comment by jcharaoui** [comment]
Thank you, it will surely help indeed. But there are many other architectures Debian runs tests on: `mips64el`, `riscv64`, `sparc64`, and several 32-bit architectures as well. Maybe there's a better was than using an "allow-list"?

**Comment by headius** [comment]
@jcharaoui Yeah I was thinking the same thing; perhaps we should just open it up and only block off when we know we can't support something? @ahorek what do you think?

**Comment by ahorek** [comment]
is there any counter-example where we know it's broken? since more and more code depends on a working console, I think we can optimistically assume it works on all Linux platforms even if we haven't tested them.

**Comment by headius** [comment]
I'm making a change in io-console that will just *warn* if the platform is not one we have tested on. It will still work on other platforms, and if they work we can expand this list to silence the warning.

That and other fixes will land in https://github.com/ruby/io-console/pull/59.
