### ISSUE TITLE
Methods that appear to be Fixnum operators optimize poorly (in indy) when they are not

### ISSUE THREAD

**Issue by headius** [jruby/jruby#803]
In the current indy logic for binding calls that appear to be operations against a fixnum, we only have a fast, inlinable path for the success case. If it turns out the operation is not performed against a fixnum, we follow a slower, non-inlinable path.

Calls that appear to be fixnum operators are of the form <expr> <operator> <literal fixnum>, as in the following examples:

```
a = b + 1
a = b * 1
a = b << 8
```

In cases like these, we will optimize the call to go straight into the versions of these methods on RubyFixnum that receive long rather than IRubyObject for the second operand. The guard is a simple "instanceof RubyFixnum" check.

If the guard fails, we permanently fall back to a version that mimics the old CachingCallSite, actively checking the cache entry for validity each time. This logic is much slower than standard indy dispatch and does not allow the target method to inline.

This comes into play in the Benchmarks Game "pidigits" code, since fixnums eventually roll over into bignums and the operators start failing. There are likely many other cases out there where a literal fixnum is added, subtracted, etc with a float, rational, bignum, or other value, or appended into an array.

**Comment by enebo** [comment]
This is a valid issue but between Graal and IR work this is not really specifically an indy issue.  Or at least it overlaps with other avenues of optimization now.
