### ISSUE TITLE
Defunct jruby@ruby-lang.org mailing list?

### ISSUE THREAD

**Issue by jlmuir** [jruby/jruby#8032]
I don't think I have permissions to edit the wiki, so I'm reporting here an issue with the [MailingLists](https://github.com/jruby/jruby/wiki/MailingLists) wiki page, which says that there's a `jruby@ruby-lang.org` mailing list maintained alongside MRI's lists, but that does not seem to be the case since the "mailman web interface" and the archives of the JRuby mailing list after July 7, 2015, links are broken (HTTP 404).  And if I check the MRI [Mailing Lists page](https://www.ruby-lang.org/en/community/mailing-lists/) or the [Mailman page](https://ml.ruby-lang.org/mailman3/postorius/lists/), there seems to be no mention of a JRuby mailing list.

**Comment by jlmuir** [comment]
BTW, if it is decided to remove that wiki page, there's also a "Mailing Lists" link to it in [The JRuby Community](https://www.jruby.org/community) that you'd also want to remove.

**Comment by headius** [comment]
Yeah, I've been trying to find out who runs the mailing list server to get us listed and accessible again. So far I have not figured out who that person is. I will try to escalate this.

**Comment by enebo** [comment]
@headius since google groups is set up we may as well continue using it.  Seemingly I am the only one who does :)  It almost makes me wonder if we should have one at all or just open up discussions in github?

**Comment by headius** [comment]
We do have discussions working on GitHub right now. I'm not a big fan of the interface, but people have been using it occasionally.

I think we just stick with the group but perhaps update all links to it and then send out an FYI announcement about the new location.

**Comment by headius** [comment]
After some discussion we're going to just run with the Google Group set up by @hsbt. We are still trying to locate the JRuby mailing list archives from ruby-lang.org so we can make them available somewhere.

I have updated the wiki with this new information.

**Comment by jlmuir** [comment]
Thanks!  I just checked the updated [MailingLists](https://github.com/jruby/jruby/wiki/MailingLists) wiki page, and unfortunately, when I click on the https://groups.google.com/u/0/a/ruby-lang.org/g/jruby URL, I get the following error message: "You don't have permission to access this content."  See the screenshot below.  Is that expected?  If so, I would suggest updating the MailingLists wiki page to explain what a user needs to do in order to view that mailing list.

<img width="781" alt="jruby-google-groups-no-permission" src="https://github.com/jruby/jruby/assets/959381/fb013a96-06a5-4947-8b96-4314bbb157f7">

**Comment by hsbt** [comment]
It's known issue. I'm investigating it now.

**Comment by hsbt** [comment]
<img width="643" alt="Screenshot 2024-01-10 at 14 00 09" src="https://github.com/jruby/jruby/assets/12301/c5ba6410-e0a5-46f6-ac3f-e46132d225aa">

I update configuration. Can you confirm again? I could access top page of JRuby mailing-list and show join button for that.

**Comment by jlmuir** [comment]
Yes, I confirm that I can access it now, and I can click on a message and view it.  If I sign into a Google account and access the same page, then there is a "Join group" button next to the "jruby" group label.  Thanks!

**Comment by hsbt** [comment]
Thank you confirming it. Sorry to inconvenient experience while long time.

**Comment by headius** [comment]
Thanks for your help @hsbt.

**Comment by enebo** [comment]
@hsbt Thank you

**Comment by hsbt** [comment]
Note: I added admin permission of JRuby mailing-list to @headius and @enebo.

**Comment by headius** [comment]
> Note: I added admin permission of JRuby mailing-list to @headius and @enebo.

Excellent, thank you!
