### ISSUE TITLE
Implement `Exception.to_tty?`

### ISSUE THREAD

**Issue by ntkme** [jruby/jruby#8033]
**Environment Information**
  
```
jruby 9.4.5.0 (3.1.4) 2023-11-02 1abae2700f OpenJDK 64-Bit Server VM 17.0.4+8-LTS on 17.0.4+8-LTS +jit [arm64-darwin]
```

**Expected Behavior**

`Exception.to_tty?` should work and behave similar to `$stderr.tty?`.

**Actual Behavior**

```
NoMethodError: undefined method `to_tty?' for Exception:Class
```

**Comment by ntkme** [comment]
This method existed since Ruby 2.5: https://ruby-doc.org/core-2.5.1/Exception.html#method-c-to_tty-3F

**Comment by headius** [comment]
Wow, this one really flew under the radar. Looks like in our repo (which includes ruby/spec, ruby/ruby test suite and more) there's only one place this is exercised:

https://github.com/jruby/jruby/blob/70aa695888ab3ee4057124f50d85b1209c29d264/spec/ruby/core/exception/full_message_spec.rb#L167

I don't think this would be difficult to implement, but for now the following workaround should be fine in most cases:

```ruby
def Exception.to_tty?
  $stderr.tty?
end
```

I'm guessing the magic behavior this is missing is when exceptions are getting routed somewhere other than `$stderr`, but we can figure out the right behavior and add specs for it.

It would be a great way for you to contribute :-) You can implement it in Ruby in core/src/main/ruby if you like.

**Comment by enebo** [comment]
@ntkme did you run into this using a ruby gem?

**Comment by ntkme** [comment]
Not really. I was trying to override `full_message(highlight: bool, order: [:top or :bottom]) → string` on a subclass of `StandardError`, and I to determine the default value of highlight myself in order to behave the same as the parent class.

I saw a sample at https://github.com/ruby/dev-meeting-log/blob/master/2022/DevMeeting-2022-01-13.md?plain=1#L292-L307

``` ruby
def full_message(highlight: Exception.to_tty?, **)
```

I tried this in CI and it worked for both MRI and truffleruby, but it failed on jruby. - That's how I found this.

**Comment by ntkme** [comment]
Here is the MRI implementation:

https://github.com/ruby/ruby/blob/5809b75019dd3a253bb0e45c37bbf0cca0400911/error.c#L1497-L1507

Here is the truffleruby implementation:

https://github.com/oracle/truffleruby/blob/070598d468848fae29f6ffcebf64c4348239c5d4/src/main/ruby/truffleruby/core/exception.rb#L107-L113

**Comment by ntkme** [comment]
Yeah, I just checked both MRI and truffleruby, it does the following:
1. Check if `$stderr` is still the original value
2. Check if the original value has closed (looks like MRI does not check this, but truffleruby does)
3. Check if the original value is tty or not

So a pure ruby fallback would be:

```
def Exception.to_tty?
  $stderr == STDERR && STDERR.tty?
end
```

**Comment by ntkme** [comment]
@headius @enebo Another thing is that jruby's default value for `highlight` in `full_message` behave differently than MRI or truffleruby. It's probably good to fix it at the same time.

**Comment by enebo** [comment]
@ntkme not to burden you but if you have the time adding these (highlight and to_tty?) to ruby/spec or MRI test suite would be a great help.  We will add them otherwise when we implement them.

**Comment by ntkme** [comment]
It turns out that `public static String printFullMessage` would parse `highlight` or `order` options if provided, but the internal `private static String printBacktraceMRI` supports neither of the two options. Changing the `highlight` default to match MRI actually does nothing until the options are implemented.

**Comment by enebo** [comment]
@ntkme  Could you open up a second issue about printBacktraceMRI?  It appears someone did most of what is needed already but it is not hooked up so anything can use it.  Thanks for looking into this.  This will be a bit more work than to_tty? but it mostly looks like changing some signatures and refactoring a bit.  We should be able to fix this.

**Comment by ntkme** [comment]
@enebo https://github.com/jruby/jruby/pull/8040
