### ISSUE TITLE
Ruby code can't access generated accessor methods on a record

### ISSUE THREAD

**Issue by kzvi** [jruby/jruby#8036]
**Environment Information**

- `jruby 9.4.4.0 (3.1.4) 2023-10-18 9c9bfd3dc7 OpenJDK 64-Bit Server VM 19.0.2+7 on 19.0.2+7 +jit [x86_64-darwin]`
- macOS 13.6.1

**Expected Behavior**

Contents of `Thing.java`:

```
public class Thing {
    public static R get() {
        return new R(1, 2);
    }

    record R(int a, int b) {}
}
```

Contents of `test.rb`:

```
java_import 'Thing'

p Thing.get().a
```

Running

```
javac Thing.java
jruby test.rb
```

should print `1`

**Actual Behavior**

```
NoMethodError: undefined method `a' for #<Java::Default::Thing::R:0x2baac4a7>
  <main> at test.rb:3
```

**Comment by kzvi** [comment]
This [documentation](https://docs.oracle.com/en/java/javase/17/language/records.html#GUID-6699E26F-4A9B-4393-A08B-1E47D4B2D263) says:

> A record class declares the following members automatically:
> 
> - For each component in the header, the following two members:
>     - A private final field with the same name and declared type as the record component. This field is sometimes referred to as a component field.
>     - A public accessor method with the same name and type of the component; in the Rectangle record class example, these methods are Rectangle::length() and Rectangle::width().
> - A canonical constructor whose signature is the same as the header. This constructor assigns each argument from the new expression that instantiates the record class to the corresponding component field.
> - Implementations of the equals and hashCode methods, which specify that two record classes are equal if they are of the same type and contain equal component values.
> - An implementation of the toString method that includes the string representation of all the record class's components, with their names.

So I think that jruby should just treat it as a regular class and not have any special behavior for records, and allow access to the methods listed above, specifically:

- ability to call each generated accessor method (1 per member)
- ability to call constructor by `.new(...)`
- ability to call `equals` and `hashCode` and `toString`

That documentation above gives an example of how a record declaration is expanded:

```
record Rectangle(double length, double width) { }
```

turns into

```
public final class Rectangle {
    private final double length;
    private final double width;

    public Rectangle(double length, double width) {
        this.length = length;
        this.width = width;
    }

    double length() { return this.length; }
    double width()  { return this.width; }

    // Implementation of equals() and hashCode(), which specify
    // that two record objects are equal if they
    // are of the same type and contain equal field values.
    public boolean equals...
    public int hashCode...

    // An implementation of toString() that returns a string
    // representation of all the record class's fields,
    // including their names.
    public String toString() {...}
}
```

so I think that jruby should simply treat the record the same as if the class was written out explicitly that way.

The fact that the jruby code doesn't automatically do this already suggests that the java compiler doesn't *actually* just expand the record declaration as oracle claims it does. I don't know anything about JVM so I can't really comment on how this might be implemented, but the link above has a suggestive paragraph at the bottom:

> The class `java.lang.Class` has two methods related to record classes:
>
> - `RecordComponent[] getRecordComponents()`: Returns an array of java.lang.reflect.RecordComponent objects, which correspond to the record class's components.
> - `boolean isRecord()`: Similar to `isEnum()` except that it returns true if the class was declared as a record class.

so the jruby method dispatch code probably simply needs to make use of those 2 methods.

**Comment by headius** [comment]
The .class layout looks pretty straightforward:

```
$ javap -private Rectangle 
Compiled from "Rectangle.java"
final class Rectangle extends java.lang.Record {
  private final double length;
  private final double width;
  Rectangle(double, double);
  public final java.lang.String toString();
  public final int hashCode();
  public final boolean equals(java.lang.Object);
  public double length();
  public double width();
}
```

I'm not sure why we would not "just work". This is not an unusual structure, other than not having "get" prefixes on the accessors.

**Comment by headius** [comment]
So I am running on 21 and it seems to work ok for me, if I take just your `Rectangle` and add `public`:

```
[] jruby $ cat Rectangle.java 
public record Rectangle(double length, double width) { }
[] jruby $ jruby -e 'java_import "Rectangle"; p Rectangle.new(1, 2).width'
2.0
```

If I run with something closer to your example, it does fail. I believe the issue is that your record is default visibility, so it can't be accessed outside the package. Your call to `get` works because it is public, but it returns a package-visible type and we can't call any of those methods.

```
[] jruby $ javap -private Blah\$Rectangle
Compiled from "Blah.java"
final class Blah$Rectangle extends java.lang.Record {
  private final double length;
  private final double width;
  Blah$Rectangle(double, double);
  public final java.lang.String toString();
  public final int hashCode();
  public final boolean equals(java.lang.Object);
  public double length();
  public double width();
}
```

I don't think Java would be able to call these methods either. If you make it public it should just work.

**Comment by kzvi** [comment]
Oh... I didn't even realize it was possible to make a record type public. Thanks for the info.
