### ISSUE TITLE
A bit confusing error: "FrozenError: can't modify frozen NilClass"

### ISSUE THREAD

**Issue by rubyFeedback** [jruby/jruby#8054]
I am currently working on my two gems swing_paradise and universal_widgets. The goal is
to fully support jruby + SWING eventually, via some kind of DSL such as:

    button {
    }

A bit similar to what Andy does via glimmer, but not as sophisticated. I am more interested
to see how I can use traditional OOP build up for GUIs, including commandline stuff (eventually,
e. g. the terminal and so forth) as well as web-related stuff (e. g. HTML/CSS also has **button**).
One code base to unify them all! One ring to bind them and in the darkness ... eat some ice cream! \o/

Anyway. As I am extending the code right now, I ran into this odd error message:

    Warning: not (yet?) supported toolkit: jruby
    FrozenError: can't modify frozen NilClass
                      set_font at     /home/Programs/Jruby/9.4.5.0/lib/ruby/3.1/site_ruby/universal_widgets/base_module/base_module.rb:911
      create_the_main_textview at read_and_display_from_a_locally_existing_file_example.rb:165
               create_the_skeleton at read_and_display_from_a_locally_existing_file_example.rb:103
                     run_super at     /home/Programs/Jruby/9.4.5.0/lib/ruby/3.1/site_ruby/universal_widgets/base_module/base_module.rb:980
                           run at read_and_display_from_a_locally_existing_file_example.rb:138
                    initialize at read_and_display_from_a_locally_existing_file_example.rb:65
                           new at org/jruby/RubyClass.java:904
                        <main> at read_and_display_from_a_locally_existing_file_example.rb:240
    
The first line is from my own gem, but the second line is from jruby I believe:

    FrozenError: can't modify frozen NilClass

This is a bit weird though. I believe ruby MRI does not have this error.

I believe MRI does not have a frozen nil class ever.

Now, I am totally fine if jruby does things differently. I get that you focus on the java
ecosystem also, so this may not be ruby 1:1. But, even then, I find the idea of a nil
class to ever be frozen a bit awkward, even more so when an error message can happen.

Is that really needed? It may be that I made some user error, but that a nil object
can ever be frozen, is super-odd to me, having used MRI for a long time. Perhaps
I have not seen this in MRI so far, so I can not say for certain, but I find this rather
strange.

Anyway - this is NOT an issue request to change anything in jruby here, actually.
I am more interested in the use case and rationale.

If someone has time, perhaps an answer could be given here, and then this
could be added to the FAQ entry for jruby at:

https://github.com/jruby/jruby/wiki/FAQs

I checked for "frozen" but did not find anything, so perhaps this could be added
to FAQ if anyone has time (and also knows the reason why nil objects can
be frozen in jruby, which confused me. Now that I know about this, I will
probably not be confused, although I am curious how this may arise in
code. I don't think I have ever seen that in MRI so far.)

**Comment by enebo** [comment]
As weird as it seems this is what C Ruby does issue this FrozenError as well:

```text
mri31 -e 'p nil.instance_variable_set("@foo", 1)'
-e:1:in `instance_variable_set': can't modify frozen NilClass: nil (FrozenError)
```

There is a mild difference here that there is an extra `: nil` which I will look into adding but we do properly mark nil and it's class the same as C Ruby:

```ruby
p nil.class.frozen?  # false
p nil.frozen?            # true
```

fwiw I do find the error confusing as well.  In an ideal world the error would be `can't modify frozen nil`.

**Comment by headius** [comment]
The wording here is confusing but not new. It uses the class name for the message, as in "can't modify frozen String", but the class for `nil` is `NilClass` which makes it seem like it's trying to modify nil's class and not the nil object itself.

The missing part of the error is due to us not inspecting the target object when raising the error, as in CRuby. The following patch would fix it but I'm unsure if it's the proper (or only) place to update.

```diff
diff --git a/core/src/main/java/org/jruby/Ruby.java b/core/src/main/java/org/jruby/Ruby.java
index 43a8910d1c..b778c44b8c 100644
--- a/core/src/main/java/org/jruby/Ruby.java
+++ b/core/src/main/java/org/jruby/Ruby.java
@@ -4188,7 +4188,7 @@ public final class Ruby implements Constantizable {
     }
 
     public RaiseException newFrozenError(IRubyObject receiver) {
-        return RubyFrozenError.newFrozenError(getCurrentContext(), newString("can't modify frozen " + receiver.getType()), receiver)
+        return RubyFrozenError.newFrozenError(getCurrentContext(), newString("can't modify frozen " + receiver.getType() + ": " + receiver.inspect()), receiver)
                 .toThrowable();
     }
 
```

**Comment by headius** [comment]
I see at least two places in CRuby where this message is constructed.

The first is in `rb_class_modify_check`: https://github.com/ruby/ruby/blob/be1bbd5b7d40ad863ab35097765d3754726bbd54/eval.c#L471

The second, which seems to be the path used by `instance_variable_set` frozen checking, is this chunk of code that creates and raises a frozen error using the class of the object and its inspected value: https://github.com/ruby/ruby/blob/903b0931a116691386e71fa30fb1698bbd785853/error.c#L3783-L3814

My patch above is insufficient to cover the recursive inspect case but it's on the right track.
