### ISSUE TITLE
Roadmap on JRuby wiki is badly outdated

### ISSUE THREAD

**Issue by vyznev** [jruby/jruby#8068]
When Googling for "jruby 9.3 support end date", one of the top results was https://github.com/jruby/jruby/wiki/Roadmap, which says:

> * [JRuby 9.2](http://jruby.org/2018/05/24/jruby-9-2-0-0) Ruby 2.5 compatible, currently supported version

That looks _just a little_ out of date. Please update that page.

**Comment by ikaronen-relex** [comment]
(Oops, I accidentally submitted this from my non-work account. Oh well, it's not like actually makes any difference.)

**Comment by headius** [comment]
Ha, yes... quite old.

**Comment by headius** [comment]
I did a quick pass and removed 1.6 and 1.7 and updated the list of 9000 releases

**Comment by headius** [comment]
It could certainly use more information about schedules and plans, but I'll call this fixed for now.
