### ISSUE TITLE
Kernel.exec cannot launch two .bat files separated by &&

### ISSUE THREAD

**Issue by mdeb** [jruby/jruby#809]
Given that Java 1.7.0_21 is installed, when running the system command, a command having the && operator to run another command, it gives the following error, "&& was unexpected at this time".

So for example:

C:\test.bat && C:\test.bat

"&& was unexpected at this time".

I reinstalled Java 1.7.0_11 and the problem was solved.

**Comment by olleolleolle** [comment]
Does this gist represents the issue?
https://gist.github.com/olleolleolle/751fb332954c59dc895735f7f6d420b9

I ran that like this: `java -jar jruby-complete-1.7.27.jar -Srake runbatch` - and it ran both commands.

(`tbattwo.bat` is run inside a new shell. That's what `cmd \c start` does, I take it.)

**Comment by headius** [comment]
@olleolleolle So maybe this is no longer an issue? It has been sitting on the shelf for a long time.

**Comment by olleolleolle** [comment]
@headius For me, with the situation above, it worked.

I think it's fair to close this issue.
