### ISSUE TITLE
Please fix the broken link in GettingStarted on the wiki

### ISSUE THREAD

**Issue by sontixyou** [jruby/jruby#8115]
**Problem**
I found [JRuby Downloads page] link broken in GettingStarted#installing-binaries.
https://github.com/jruby/jruby/wiki/GettingStarted#installing-binaries

I am not authorized to edit the wiki, so I would like to ask someone who is authorized to edit the wiki to do so.

**Expected Behavior**

I think the [JRuby Downloads page] correct URL is
https://www.jruby.org/download

**Actual Behavior**

http://jruby.org/download

**Comment by enebo** [comment]
@sontixyou Thanks.  I corrected the link.
