### ISSUE TITLE
Possible Keyword Argument Regression in 9.4.6.0

### ISSUE THREAD

**Issue by jeremyevans** [jruby/jruby#8119]
First, I'd like to apologize that I do not have a simple reproducer for this issue.  However, as this appears to be a regression from 9.4.5.0, and the 9.4.6.0 changelog lists keyword related work. I'm guessing it is related to those changes.

**Environment Information**

Passes on:
`jruby 9.4.5.0 (3.1.4) 2023-11-02 1abae2700f OpenJDK 64-Bit Server VM 17.0.9+9-1 on 17.0.9+9-1 +jit [x86_64-OpenBSD]`

Fails on:
`jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 17.0.9+9-1 on 17.0.9+9-1 +jit [x86_64-OpenBSD]`

Operating System: OpenBSD/amd64

I tried but could not reproduce the issue on Windows.  It passed for both:

```
jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 20.0.1+9-29 on 20.0.1+9-29 +jit [x86_64-mswin32]
jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 20.0.1+9-29 on 20.0.1+9-29 +jit [x86_64-mswin32]
```

However, the failure is test-order dependent (the reason a specific seed is specified below), and it's possible the same seed that triggers the issue on OpenBSD does not trigger it on Windows.  Or potentially it is JVM related, and affects JVM 17 but not JVM 20.  

Reproducer (on 9.4.6.0):

```
git clone  --depth 100 https://github.com/jeremyevans/sequel.git
cd sequel
git checkout 17f0509c29561691fb908292b9d9e48ab3d19fcc
jruby -S gem install minitest-global_expectations minitest-hooks
SEED=43714 jruby -vw spec/model_spec.rb
```

**Expected Behavior**

Passes, as on JRuby 9.4.5.0:

```
jruby 9.4.5.0 (3.1.4) 2023-11-02 1abae2700f OpenJDK 64-Bit Server VM 17.0.9+9-1 on 17.0.9+9-1 +jit [x86_64-OpenBSD]
Run options: --seed 43714

# Running:

..............................................................................................................................................................................................................................................................
..............................................................................................................................................................................................................................................................
..............................................................................................................................................................................................................................................................
..............................................................................................................................................................................................................................................................
..............................................................................................................................................................................................................................................................
........................................................................................................................................................................................................

Finished in 16.150142s, 91.0209 runs/s, 239.6264 assertions/s.

1470 runs, 3870 assertions, 0 failures, 0 errors, 0 skips
```

**Actual Behavior**

Fails on JRuby 9.4.6.0:

```
jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 17.0.9+9-1 on 17.0.9+9-1 +jit [x86_64-OpenBSD]
Run options: --seed 43714

# Running:

..............................................................................................................................................................................................................................................................
................................................................................................................E.........E.............................E.....................................................................................................
..............................................................................................................................................................................................................................................................
..............................................................................................................................................................................................................................................................
..............................................................................................................................................................................................................................................................
........................................................................................................................................................................................................

Finished in 16.422840s, 89.5095 runs/s, 235.4647 assertions/s.

  1) Error:
Sequel::Model::one_to_many#test_0068_should support a :remover option that accepts keywords:
ArgumentError: wrong number of arguments (given 2, expected 1)
    (eval):1:in `block in test_0068_should support a :remover option that accepts keywords'
    /sequel/lib/sequel/model/associations.rb:2785:in `remove_associated_object'
    /sequel/lib/sequel/model/associations.rb:2086:in `block in def_association_instance_methods'
    /sequel/spec/model/associations_spec.rb:2153:in `block in <main>'

  2) Error:
Sequel::Model::one_to_many#test_0064_should support an :adder option that accepts keywords:
ArgumentError: wrong number of arguments (given 2, expected 1)
    (eval):1:in `block in test_0064_should support an :adder option that accepts keywords'
    /sequel/lib/sequel/model/associations.rb:2614:in `add_associated_object'
    /sequel/lib/sequel/model/associations.rb:2081:in `block in def_association_instance_methods'
    /sequel/spec/model/associations_spec.rb:2108:in `block in <main>'

  3) Error:
Sequel::Model::one_to_many#test_0073_should support a :clearer option that supports keywords:
ArgumentError: wrong number of arguments (given 1, expected 0)
    (eval):1:in `block in test_0073_should support a :clearer option that supports keywords'
    /sequel/lib/sequel/model/associations.rb:2762:in `remove_all_associated_objects'
    /sequel/lib/sequel/model/associations.rb:2091:in `block in def_association_instance_methods'
    /sequel/spec/model/associations_spec.rb:2204:in `block in <main>'

1470 runs, 3867 assertions, 0 failures, 3 errors, 0 skips
```

The three failing specs all run through code that uses `ruby2_keywords` on a method defined by `define_method`, and it appears the `ruby2_keywords` call is not respected, as it attempts to pass the keywords as positional arguments.

**Comment by enebo** [comment]
Ah so sad...We even run sequel in our CI.  We will fix it.

**Comment by headius** [comment]
These are showing up in CI now.

**Comment by headius** [comment]
The unusual dependence on the seed and test sequence is not surprising; kwargs are currently implemented by flipping bits on and off when making a call and entering a method, so if some place is not flipping right it could show its effects in an apparently random way.

We may need to add in a better way to track the flipping so we can see where it is mismatched.

**Comment by enebo** [comment]
For my machine I need another seed to see this:  ```SEED=1566 jruby -vw spec/model_spec.rb```.  Going to dip my toes into this.

**Comment by enebo** [comment]
Some notes with no enlightenment.  This uses a lot of `send`.  It will send for ruby2_keywords and for define_method.  The 3 tests which fail very intertestingly is 3 different methods having the same problem and they are all defined using eval.  If I print out methods when things work the same methods are there and defined by eval.  Not surprising at all but the fact this is only happening to methods made inside an eval block feels like something...

The main reasons for this type of error tend to be:
  1. passing through a native (Java) ruby method which forwards its arguments and we strip the keyword state
  2. we have valid keyword state through dispatch or calling a native method but some dyncall happens which then strips keyword state
  3. we JIT a method and it has exact arity but we are missing kwarg processing logic.

No clues yet.

**Comment by enebo** [comment]
I am ruling out `eval` as an issue.  If I just make the proc as-is in the spec for all three failures they still fail with the same error.

**Comment by enebo** [comment]
This is a JIT problem.  It cannot repro in interp and if I reduce the JIT threshold way down it happens consistently.  The seed ends up making the difference as in the wrong order it must not make something JIT.  Still enigmatic but reduced in scope more.

**Comment by headius** [comment]
Some discussion on Matrix led us to think this is related to the sequence of events with these proc-based methods.

* The methods are defined from a proc defined in a different file(I believe... some trouble tracking down exactly where) using `define_method`.
* The method is set to `ruby2_keywords` which should update the IRScope associated with the proc to also accept keyword arguments in the ruby2 style.
* It's possible that either this proc has already jitted by the time it fails (if it is redefined repeatedly, as during testing, this could be the case) or otherwise is not honoring the `ruby2_keywords` by the time it is eventually called.

**Comment by headius** [comment]
This took a while to narrow down but our suspicions are confirmed. The issue is that the proc used for the `define_method` and `ruby2_keywords` delegation has already been JIT compiled by JRuby as a non-`ruby2_keywords` method, so the flag doesn't get set successfully. When that method gets called with ruby2-style keywords, it unmarks their keyword flag and passes them on, which causes them to fail in a subsequent call to the non-`ruby2_keywords` remover proc.

Whew!

Here's the code and command line that reproduces:

```
$ ruby -e "class X; def bar(a, foo: nil); end; define_method :x, proc {|a, *args| bar(a, *args) }; send :ruby2_keywords, :x; end; X.new.x(1, foo: 1)"
ArgumentError: wrong number of arguments (given 2, expected 1)
```

We `send` ruby2_keywords here because JRuby rejects JIT for scopes that call it directly... exactly because of this sort of case. But in this case, the proc comes from another method (`def_association_instance_methods`) that JITs independently, so there's no way to detect that it will eventually become `ruby2_keywords`.

**Comment by headius** [comment]
We have some ideas for how to fix this, but they are not trivial.

* Recompile the proc when it is set to `ruby2_keywords`. There's no affordance currently for recompiling scopes after they have jitted.
* Compile both forms (ruby3 and ruby2 keyword handling) for any proc that JITs and select the right one at call time. This would double the amount of JIT code for all procs even though only one path would ever really be used.

**Comment by headius** [comment]
Another idea for fixing it:

* Compile blocks with an additional parameter for the runtime-changeable `ruby2_keywords` flag and branch in the args logic. It will add overhead to block argument processing (for restarg forms) but perhaps not enough to be a concern right now.

**Comment by headius** [comment]
Best option for now is to partially undo the optimization I did in #8095, so I've pushed #8207 to do that.
