### ISSUE TITLE
Prepending a module to a subclass changes it representation in the superclass#subclasses array

### ISSUE THREAD

**Issue by nagaroni** [jruby/jruby#8121]
If we prepend a module to a class B that inherit from A, and then call A.subclasses the returned value does not return the correct class representation.

**Environment Information**
 
* jruby 9.4.5.0 (3.1.4) 2023-11-02 1abae2700f OpenJDK 64-Bit Server VM 25.402-b06 on 1.8.0_402-b06 +jit [x86_64-linux]
* Operational System (docker): Linux f01595e3f50e 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 x86_64 x86_64 GNU/Linux

**Expected Behavior**

We shouldn't change the class representation in the Class#subclasses when a module is prepended

**Actual Behavior**

![image](https://github.com/jruby/jruby/assets/6962371/0455c759-fc92-4d54-b1cc-51ca4c4af468)

**Comment by headius** [comment]
Looks like it's not skipping the internal class for the prepend.

**Comment by headius** [comment]
```
$ jruby -e 'class A; end; class B < A; end; module C; end; p A.subclasses; B.prepend(C); p A.subclasses'
[B]
[B]
```

Fix coming.
