### ISSUE TITLE
Concurrently requiring a file from multiple threads may "succeed" even if the file raises an error

### ISSUE THREAD

**Issue by ikaronen-relex** [jruby/jruby#8155]
Here's some rather unexpected JRuby behavior I recently noticed. It also diverges from the behavior observed on CRuby. I would consider this a bug:

1. Create a file named `nope.rb` in the `$LOAD_PATH` with the following code:

    ```ruby
    sleep 0.1
    raise LoadError.new("nope")
    ```

2. Run the following code:

   ```ruby
   threads = 5.times.map do
     Thread.new do
       require 'nope'
       "wtf"
     rescue LoadError => e
       e.message
     end
   end
   puts threads.map(&:value).inspect
   ```

**Output on CRuby 3.2.2 (expected):** `["nope", "nope", "nope", "nope", "nope"]`

**Output on JRuby 9.4.5.0:** `["nope", "wtf", "wtf", "wtf", "wtf"]`

The behavior is repeatable, even without restarting ruby. Also the JRuby behavior is the same with or without Rails and Zeitwerk loaded.

----

Ps. I originally discovered this behavior while trying to investigate a bug that sometimes broke session handling in Rails 7.1.3.2, causing a new session to be created on every request. I finally traced the problem to [the following code](https://github.com/rails/rails/blob/v7.1.3.2/activesupport/lib/active_support/messages/serializer_with_fallback.rb#L129-L140) in the `ActiveSupport::Messages::SerializerWithFallback::MessagePackWithFallback` class:

```ruby
          def dumped?(dumped)
            available? && ActiveSupport::MessagePack.signature?(dumped)
          end

          private
            def available?
              return @available if defined?(@available)
              silence_warnings { require "active_support/message_pack" }
              @available = true
            rescue LoadError
              @available = false
            end
```

When multiple request threads execute this code concurrently, it's possible for the class to end up in a state where `@available` is true even though the `ActiveSupport::MessagePack` class has _not_ been successfully loaded (because the msgpack gem it depends on is not available). This causes the `dumped?` method to raise a NameError, which is silently caught in `ActionDispatch::Cookies::SerializedCookieJars#parse` and interpreted as a parsing failure.

We're working around this ActiveSupport issue by calling the problematic method during application startup to set the `@available` flag before any requests can get in and trigger this race condition. However, the unexpected behavior of `require` on JRuby still seems like a bug that ought to be fixed.

**Comment by enebo** [comment]
LOL.  I did not realized LoadError effectively makes it forever requireable:

```text
jruby -I. -e 'begin; p require "nope"; rescue LoadError => e; p e; end; begin; p require "nope"; rescue LoadError => e; p e; end; begin; p require "nope"; `rescue` LoadError => e; p e; end; begin; p require "nope"; rescue LoadError => e; p e; end'
#<LoadError: nope>
#<LoadError: nope>
#<LoadError: nope>
#<LoadError: nope>
```

So yeah definitely something involving threading and concurrent loads is not working out.

**Comment by kares** [comment]
While this weird, this is actually a regression.
JRuby 9.2 behaves as CRuby, up till 9.3.3 the behavior matched, the issue started happening (in 9.3.4.0) likely due: https://github.com/jruby/jruby/commit/822f6ffb98086ece41f1c091e832cad39b11bece
