### ISSUE TITLE
Incorrect case tree selection when comparing Symbols during compiled Ruby code execution

### ISSUE THREAD

**Issue by jbaiza** [jruby/jruby#8157]
**Environment Information**
  
* JRuby versions 9.4.3.0 till 9.4.6.0 with empty JRUBY_OPTS
* MacOS Sonoma 14.4 (23E214) with Apple M3 Max, also tried on debian Docker container:
```
Linux 3560b4ae4eac 6.5.11-linuxkit #1 SMP PREEMPT Wed Dec  6 17:08:31 UTC 2023 x86_64 GNU/Linux
```
* Java versions:
  * OpenJDK Runtime Environment (Zulu 8.74.0.17-CA-macos-aarch64) (build 1.8.0_392-b08)
  * OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)

Other relevant info you may wish to add:
* Plain JRuby without any gems

**Expected Behavior**

Use following files:
* `test.rb`:
```
class ExampleClass
  def initialize
    case :abc
    when :abc
      puts "Correct"
    else
      puts "Incorrect"
    end
  end
end

ExampleClass.new
```
* `test1.rb`:
```
load 'test.class'
```

Compile `test.rb` file using `jrubyc test.rb`.

Executing both files (`test.rb` and `test1.rb`) the same output should be displayed - `Correct`.

**Actual Behavior**

When the ruby file is executed using `jruby test.rb`, the output `Correct` is displayed.
When the compilled class via `test1.rb` file is executed using `jruby test1.rb`, the output is `Incorrect`.

During our testing we found that on different computers, the symbol count did matter. On some it worked with just `:a`, on some the error occurs only with `:abc`.

Using the `git-bisect` I have identified, that this behaviour started in commit https://github.com/jruby/jruby/commit/95ec1814dd1f8a3f515a3a4c1ce499ef11ce32d0.

**Comment by enebo** [comment]
*Problem Description*

What a roller coaster figuring this out was.  In the end it is very simple to say what is wrong and perhaps less simple to say how to fix it.

The base problem is the optimization constructs a jump table using the RubySymbol's id value.  This id effectively ends up being a value given out when adding a symbol to the internal symbol table.  This value is safe to use in the same runtime for the same run.

How we compile Ruby source is we dump our internal instructions into a byte[] in the .class file.  The b_switch instruction just dumps out its contents...including the table of symbol ids from the runtime which generated the .class file.  That will not be the same runtime which loads the .class file so the runtime will be different. 

So why does it work or not work in some cases?  The calculation of the id for b_switch uses the new symbol table and the table is made up of ids from an older symbol table.   In some cases, you just get lucky.

*Solution*

An obvious answer would be that for types this can be optimized instr is made we need to also save those original values into the instruction.  When we serialize we throw out the jump table values and instead save the original values.  Then when we deserialize we regenerate the jump table from those values.

This is a little more complicated in that we have to examine the type and use the same logic to generate the integers as we did when we originally made the instr.
