### ISSUE TITLE
Warnings emitted by requiring 'ostruct'

### ISSUE THREAD

**Issue by PragTob** [jruby/jruby#8200]
:wave: Hello my friends! Long time no see, some might say the not seeing level is over 9000 ;)

## Environment

```
tobi@qiqi:~/github/simplecov(ci-madness)$ jruby -v
jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 11.0.22+7-post-Ubuntu-0ubuntu222.04.1 on 11.0.22+7-post-Ubuntu-0ubuntu222.04.1 +jit [x86_64-linux]
tobi@qiqi:~/github/simplecov(ci-madness)$ uname -a
Linux qiqi 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

## Behaviour

Just requiring open struct yields the following warnings with warnings turned on

```
tobi@qiqi:~/github/simplecov(ci-madness)$ cat wtwas.rb 
require 'ostruct'
tobi@qiqi:~/github/simplecov(ci-madness)$ jruby -w wtwas.rb 
/home/tobi/.asdf/installs/ruby/jruby-9.4.6.0/lib/ruby/stdlib/ostruct.rb:466: warning: OpenStruct#public_send accesses caller method's state and should not be aliased
/home/tobi/.asdf/installs/ruby/jruby-9.4.6.0/lib/ruby/stdlib/ostruct.rb:466: warning: OpenStruct#method accesses caller method's state and should not be aliased
```

**Expected Behavior**

No warnings :)

## More context

FWIW the simplecov CI is failing because of this, I'll work around it for now somehow. We have a test that just makes sure we don't emit warnings.

Cheers, and thanks for all your work :green_heart:

**Comment by headius** [comment]
Further clarification of why we warn: In order to optimize method bodies by eliminating extra frame and scope information, we gather a list of all method names known to access the caller's frame or scope. When one of these methods gets aliased, that becomes a method name that also needs caller access, and any code already compiled to call that new name may not have the right context set up. So we warn to indicate these methods may not behave like the user expects.

**Comment by headius** [comment]
I pushed #8206 with a new sort of fix: eagerly add all frame-aware names with an additional bang-suffixed version in expectation that this will be an ongoing problem with ostruct.

This could probably be reduced to just Kernel, Object, and BasicObject names but that is a messier fix.

**Comment by PragTob** [comment]
Thanks for all the work as always Charlie! :green_heart: 

![IMG_20220705_184557](https://github.com/jruby/jruby/assets/606517/31ce9409-6442-4586-b697-abadb79b4cca)
