### ISSUE TITLE
X509Cert.set_serial breaks for Certificate SerialNumbers with MSB=1

### ISSUE THREAD

**Issue by sclasen** [jruby/jruby#823]
This was posted 2 years ago on the jruby-ossl repo, but that looks like the wrong place

See https://github.com/jruby/jruby-ossl/issues/7

```
 Java::JavaLang::IllegalArgumentException:
       serial number must be a positive integer
     # org.bouncycastle.x509.X509V3CertificateGenerator.setSerialNumber(Unknown Source)
     # org.jruby.ext.openssl.X509Cert.set_serial(X509Cert.java:304)
     # org.jruby.ext.openssl.X509Cert.initialize(X509Cert.java:167)
```

**Comment by delwaterman** [comment]
seeing this in `jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.74-b02 on 1.8.0_74-b02 +jit [darwin-x86_64]`
