### ISSUE TITLE
org.jruby.javasupport.ext.JavaLang.Number#define emits "method redefined" warnings in verbose mode

### ISSUE THREAD

**Issue by ikaronen-relex** [jruby/jruby#8244]
In seems that the `proxy.defineAlias` calls at https://github.com/jruby/jruby/blob/9.4.6.0/core/src/main/java/org/jruby/javasupport/ext/JavaLang.java#L359 generate warnings in verbose mode, presumably because methods with the same name have already been defined by `proxy.defineAnnotatedMethods` just before.

This can be easily demonstrated with `jruby -S irb`:

```ruby
irb(main):001> $VERBOSE = true
=> true
irb(main):002> java.lang.Integer
(irb):2: warning: method redefined; discarding old to_int
(irb):2: warning: method redefined; discarding old to_f
=> Java::JavaLang::Integer
```

Presumably one of the redundant sets of definitions should be removed.

Tested on jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 21.0.2+13-LTS on 21.0.2+13-LTS +jit [arm64-darwin]. The code hasn't changed in 9.4.7.0 or master, however.

**Comment by ikaronen-relex** [comment]
It looks like aliasing `to_int` to `longValue` also breaks it for Java BigIntegers:

```ruby
irb(main):003> java.math.BigInteger.new("12345678901234567890").to_i
=> 12345678901234567890
irb(main):004> java.math.BigInteger.new("12345678901234567890").to_int
=> -6101065172474983726
```

Given this, I think these aliases should probably just be removed. I'll make a PR tomorrow.

**Comment by enebo** [comment]
Thanks @ikaronen-relex ... It would seem the aliases probably preceded the @JRubyMethod definitions and no one noticed after the real methods were added?

**Comment by headius** [comment]
> It would seem the aliases probably preceded the @JRubyMethod definitions

Yeah this is a good theory. At some point @kares moved most of the Ruby-based definitions of JI logic in Java, and I'm sure the aliases just got doubled up. Nice to get rid of those warnings! 👍
