### ISSUE TITLE
JRuby parses "mixed" IPv6 address as IPv4

### ISSUE THREAD

**Issue by mhashizume** [jruby/jruby#8248]
**Environment Information**
  
* JRuby 9.4.7.0 (jruby 9.4.7.0 (3.1.4) 2024-04-29 597ff08ac1 OpenJDK 64-Bit Server VM 25.412-b08 on 1.8.0_412-b08 +jit [arm64-darwin])
* macOS 14.4.1

I've observed the same behavior on Ubuntu 22.04.4 with the same version of JRuby.

**Expected Behavior**

IPv6 addresses can mix the formatting of IPv6 and IPv4 in one address (e.g. ::ffff:192.0.2.128), as defined in [RFC4291:](https://www.rfc-editor.org/rfc/rfc4291#section-2.2)

>  An alternative form that is sometimes more convenient when dealing
>  with a mixed environment of IPv4 and IPv6 nodes is
>  x:x:x:x:x:x:d.d.d.d, where the 'x's are the hexadecimal values of
>  the six high-order 16-bit pieces of the address, and the 'd's are
>  the decimal values of the four low-order 8-bit pieces of the
>  address (standard IPv4 representation).  Examples:
> 
>   0:0:0:0:0:0:13.1.68.3
> 
>   0:0:0:0:0:FFFF:129.144.52.38
> 
>  or in compressed form:
> 
>  ::13.1.68.3
> 
>  ::FFFF:129.144.52.38

MRI 3.1.5 correctly parses these types of IPv6 addresses:

```
$ ruby -v
ruby 3.1.5p252 (2024-04-23 revision 1945f8dc0e) [arm64-darwin23]
$ irb -r socket
irb(main):001:0> IPSocket.getaddress('::ffff:192.0.2.128')
=> "::ffff:192.0.2.128"
```

**Actual Behavior**

JRuby 9.4.7.0 incorrectly parses the same address as an IPv4 address:

```
$ ruby -v
jruby 9.4.7.0 (3.1.4) 2024-04-29 597ff08ac1 OpenJDK 64-Bit Server VM 25.412-b08 on 1.8.0_412-b08 +jit [arm64-darwin]
$ irb -r socket
irb(main):001:0> IPSocket.getaddress('::ffff:192.0.2.128')
=> "192.0.2.128"
```

Note that when JRuby drops the hex characters and `::` syntax at the start of the address.

This can have knock-on effects for things like `Addrinfo`:

```
irb(main):002:0> Addrinfo.new(['AF_INET6', 0, nil, '::ffff:192.0.2.128'], :INET6)
org/jruby/ext/socket/Addrinfo.java:139:in `initialize': getaddrinfo: Address family for hostname not supported (SocketError)
```

**Comment by headius** [comment]
Interesting. We are not doing anything special here. The address string is passed to the JDK class InetAddress to be resolved:

https://github.com/jruby/jruby/blob/783f50fa2ee4d67e3e474159b95e7119f3583bf6/core/src/main/java/org/jruby/ext/socket/SocketUtils.java#L505

If I avoid the Ruby bindings altogether and just call the JDK API it produces the following (Java 21):

```
$ jruby -e 'x = java.net.InetAddress.get_by_name("::ffff:192.0.2.128"); puts x.class; puts x.to_s'
Java::JavaNet::Inet4Address
/192.0.2.128
```

In fact, it does this even if I call against `Inet6Address`, so JDK seems to be preferring IPv4 addresses for this form.

**Comment by headius** [comment]
There is a note on the documentation for `Inet6Address#format` that might explain this behavior:

https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/net/Inet6Address.html#special-ipv6-address-heading

> These classes can take an IPv4-mapped address as input, both in byte array and text representation. However, it will be converted into an IPv4 address.

**Comment by headius** [comment]
> This can have knock-on effects for things like Addrinfo

We have a somewhat partial implementation of `Addrinfo` so there may be a separate fix that can be applied there.

**Comment by headius** [comment]
The `Addrinfo` error appears to be explicitly in the code; we check if the requested family was `INET6` and the resulting address was `Inet4Address` and raise an error.

Modifying that code to instead create an Inet6Address under these circumstances avoids the error (since I removed the error, but I'm not sure what other effects it might have. Perhaps you can try with this code and see if it gets you past the issue?


```diff
diff --git a/core/src/main/java/org/jruby/ext/socket/Addrinfo.java b/core/src/main/java/org/jruby/ext/socket/Addrinfo.java
index a22ffe384b..e21f50f9b2 100644
--- a/core/src/main/java/org/jruby/ext/socket/Addrinfo.java
+++ b/core/src/main/java/org/jruby/ext/socket/Addrinfo.java
@@ -271,7 +271,8 @@ public class Addrinfo extends RubyObject {
                     this.socketAddress = new InetSocketAddress(inetAddress, _port);
 
                     if (af == AF_INET6 && getInetAddress() instanceof Inet4Address) {
-                        throw sockerr(runtime, "getaddrinfo: Address family for hostname not supported");
+                        Inet4Address inet4Address = (Inet4Address) getInetAddress();
+                        this.socketAddress = new InetSocketAddress(Inet6Address.getByAddress(inet4Address.getAddress()), _port);
                     }
 
                     if (SocketType.values().length <= socketType) {
```

**Comment by headius** [comment]
Heh ok, well it doesn't actually change it to being an `Inet6Address` so it's actually no better than just using the `Inet4Address` as is.

So the question is whether we should be raising a hard error here. I could obviously see problems if the address were an `Inet6Address` and we requested an `INET4` address, but the other way around should be compatible, no?

**Comment by mhashizume** [comment]
Thanks for addressing this in `IPSocket#getaddress` in 9.4.8.0. However, it looks like this is still an issue for `Addrinfo#getaddrinfo`:

```
$ ruby -v
jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 25.422-b05 on 1.8.0_422-b05 +jit [arm64-darwin]
$ irb -r socket
Exception `LoadError' at /Users/michael.hashizume/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/io/console/bsd_console.rb:6 - native console on MacOS only supported on i386, x86_64
irb(main):001> Addrinfo.new(['AF_INET6', 0, nil, '::ffff:192.0.2.128'], :INET6)
org/jruby/ext/socket/Addrinfo.java:139:in `initialize': getaddrinfo: Address family for hostname not supported (SocketError)
	from org/jruby/RubyClass.java:935:in `new'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1274:in `eval'
	from org/jruby/RubyKernel.java:1722:in `loop'
	from org/jruby/RubyKernel.java:1423:in `catch'
	from /Users/michael.hashizume/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/irb-1.13.2/exe/irb:9:in `<main>'
	from org/jruby/RubyKernel.java:1220:in `load'
	from /Users/michael.hashizume/.rbenv/versions/jruby-9.4.8.0/bin/irb:25:in `<main>'
```

It does seem like JRuby is still interpreting these types of addresses as IPv4 in this context. When I change from INET6 to INET, JRuby parses it as an IPv4 address and produces no errors:

```
irb(main):002> Addrinfo.new(['AF_INET6', 0, nil, '::ffff:192.0.2.128'], :INET)
=> #<Addrinfo: 192.0.2.128>
```

And more common IPv6 address types (like link-local) seem fine:

```
irb(main):003> Addrinfo.new(['AF_INET6', 0, nil, 'fe80::7086:7dff:fe4b:9f87'], :INET6)
=> #<Addrinfo: fe80::7086:7dff:fe4b:9f87>
irb(main):004>
```

Should I re-open this issue or create a new one?

**Comment by headius** [comment]
@mhashizume Since we fixed the original report, please file a new issue. It's probably going to be a similar easy fix.
