### ISSUE TITLE
IO.popen does not return value of the provided block

### ISSUE THREAD

**Issue by dub357** [jruby/jruby#8278]
According to the Ruby docs, if a block is provided to `IO.popen`, the value returned from the block becomes the value returned from the `popen` method.  In JRuby, this is never true and the IO object itself is always returned.  CRuby/MRI returns the value of the block as expected.

**Environment Information**

- jruby 9.4.7.0 (3.1.4) 2024-04-29 597ff08ac1 Java HotSpot(TM) 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 +jit [x86_64-mswin32]
- windows 10 enterprise

**Expected Behavior**

```
jruby-9.4.7.0\bin>.\jruby.exe -e "puts IO.popen('echo test')"
test
```

**Actual Behavior**

```
jruby-9.4.7.0\bin>.\jruby.exe -e "puts IO.popen('echo test')"
#<IO:0x1b11171f>
```

**Comment by JesseChavez** [comment]
I have not tested in windows yet but I don't see this issue in my workstation:

My environment:
```
jessec@akuma:~$
(bash)> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
jessec@akuma:~$
(bash)> uname -a
Linux akuma 6.5.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 26 11:23:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
jessec@akuma:~$
```


Results:
```
jessec@akuma:~$
(bash)> chruby
   jruby-9.3.10.0
   jruby-9.4.1.0
   jruby-9.4.2.0
   jruby-9.4.3.0
 * jruby-9.4.7.0
   ruby-2.5.8
   ruby-2.6.8
   ruby-2.7.7
   ruby-3.1.0
   ruby-3.1.4
jessec@akuma:~$
(bash)> ruby -v
jruby 9.4.7.0 (3.1.4) 2024-04-29 597ff08ac1 OpenJDK 64-Bit Server VM 11.0.22+7-post-Ubuntu-0ubuntu223.10.1 on 11.0.22+7-post-Ubuntu-0ubuntu223.10.1 +jit [x86_64-linux]
jessec@akuma:~$
(bash)> ruby -e "puts IO.popen('echo test')"
#<IO:0x566c1e71>
jessec@akuma:~$
```

**Comment by dub357** [comment]
> I have not tested in windows yet but I don't see this issue in my workstation:
> 
> My environment:
> 
> ```
> jessec@akuma:~$
> (bash)> lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 23.10
> Release:	23.10
> Codename:	mantic
> jessec@akuma:~$
> (bash)> uname -a
> Linux akuma 6.5.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 26 11:23:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
> jessec@akuma:~$
> ```
> 
> Results:
> 
> ```
> jessec@akuma:~$
> (bash)> chruby
>    jruby-9.3.10.0
>    jruby-9.4.1.0
>    jruby-9.4.2.0
>    jruby-9.4.3.0
>  * jruby-9.4.7.0
>    ruby-2.5.8
>    ruby-2.6.8
>    ruby-2.7.7
>    ruby-3.1.0
>    ruby-3.1.4
> jessec@akuma:~$
> (bash)> ruby -v
> jruby 9.4.7.0 (3.1.4) 2024-04-29 597ff08ac1 OpenJDK 64-Bit Server VM 11.0.22+7-post-Ubuntu-0ubuntu223.10.1 on 11.0.22+7-post-Ubuntu-0ubuntu223.10.1 +jit [x86_64-linux]
> jessec@akuma:~$
> (bash)> ruby -e "puts IO.popen('echo test')"
> #<IO:0x566c1e71>
> jessec@akuma:~$
> ```

The expected behavior is that the word “test” is output

**Comment by JesseChavez** [comment]
I mean it behaves like CRuby 3.1.4

```
jessec@akuma:~$
(bash)> chruby
   jruby-9.3.10.0
   jruby-9.4.1.0
   jruby-9.4.2.0
   jruby-9.4.3.0
   jruby-9.4.7.0
   ruby-2.5.8
   ruby-2.6.8
   ruby-2.7.7
   ruby-3.1.0
 * ruby-3.1.4
jessec@akuma:~$
(bash)> ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]
jessec@akuma:~$
(bash)> ruby -e "puts IO.popen('echo test')"
#<IO:0x00007239741e9c48>
jessec@akuma:~$
```

**Comment by dub357** [comment]
Interesting … I tested on CRuby and got the expected output. I’ll have to check the version when I get back home

**Comment by JesseChavez** [comment]
Just for the record, I see no issues in windows as well, It behaves like CRuby 3.1.4


results:
```
D:\Workbench\jrubies>java -jar jruby-complete-9.4.7.0.jar -e "puts IO.popen('echo test')"
#<IO:0x684372d0>

D:\Workbench\jrubies>

Environment:
```
D:\Workbench\jrubies>systeminfo

Host Name:                 TEST-VM-
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Server
OS Build Type:             Multiprocessor Free
Registered Owner:          Oracle BMCS
Registered Organization:   Oracle.com
Product ID:                00429-70000-00000-AA900
Original Install Date:     5/1/2023, 11:50:40 PM
System Boot Time:          5/31/2024, 11:07:56 PM
System Manufacturer:       QEMU
System Model:              Standard PC (i440FX + PIIX, 1996)
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 1 Stepping 1 AuthenticAMD ~2545 Mhz
                           
```

**Comment by dub357** [comment]
Ok - I just checked and it appears that the version of CRuby thats installed on our Linux box is a bit old 2.0.0

```
> ruby -v
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
> ruby -e "puts IO.popen('echo test', &:read)"
test
```

Maybe this is a regression in CRuby as well...like I said, the docs state that the `popen` method should return the value returned from the block when a block is supplied...

**Comment by headius** [comment]
This should be easy to fix if someone wants to give it a shot. The logic for yielding and returning is here:

https://github.com/jruby/jruby/blob/e7001424e77cee927891553ed0917606d8592185/core/src/main/java/org/jruby/RubyIO.java#L4557-L4563

The `ensureYieldClose` method does return the block's result, so it should be simple to return that instead of the IO object.
