### ISSUE TITLE
File#flock problems

### ISSUE THREAD

**Issue by minad** [jruby/jruby#828]
See

https://github.com/minad/rubyspec/blob/concurrency-test/core/file/flock_spec.rb

The following concurrency tests fail:
- blocks if trying to lock an exclusively locked file
- locks concurrent access

Try also the following snippet which fails:

``` ruby
equire 'fileutils'

def increment(name, amount = 1)
  ::File.open(name, ::File::RDWR | ::File::CREAT) do |f|
    Thread.pass until f.flock(::File::LOCK_EX)
    amount += f.read.to_i
    f.truncate(0)
    f.pos = 0
    f.write(amount.to_s)
    amount
  end
end

def increment_thread
  Thread.new do
    100.times do |i|
      100.times do |j|
        increment("data/counter#{j}")
        Thread.pass if rand(1000) >= 995
      end
    end
  end
end

FileUtils.mkdir('data')

100.times do |j|
  File.open("data/counter#{j}", 'w') {|f| f.write('0') }
end

a = increment_thread
b = increment_thread
c = increment_thread
a.join
b.join
c.join

100.times do |j|
  raise if File.read("data/counter#{j}") != 300.to_s
end

FileUtils.rm_rf('data')
```

**Comment by sheldonh** [comment]
> truncate is done after writing the updated value. After truncate the lock seems to be gone.

@minad Do you remember how you found this trick? It's great! It makes `flock` deliver the dream: process-inherited locks that work on NFS!
