### ISSUE TITLE
Adding additional platforms removes existing ones.

### ISSUE THREAD

**Issue by skunkworker** [jruby/jruby#8287]
**Environment Information**
  
`jruby-9.4.7.0 @ jdk21`
`cruby-3.1.5`
`macOS 14.5`
`bundler 2.5.11`

**Expected Behavior**

1. I start with the following `PLATFORMS` section in my Gemfile.
```
PLATFORMS
   arm64-darwin-22
   arm64-darwin-23
   universal-java-17
   x86_64-linux
```

When I run
```
bundle lock --add-platform arm64-darwin-22 arm64-darwin-23 x86_64-linux universal-java-17 universal-java-21
```
I expect just the `universal-java-21` platform to be added to the Gemfile.lock.

**Actual Behavior**

The darwin 22, 23 and x86_64_linux platforms are removed, only leaving the `universal-java-17,21` platforms.

```
PLATFORMS
-  arm64-darwin-22
-  arm64-darwin-23
   universal-java-17
-  x86_64-linux
+  universal-java-21
```

Comparison with CRuby 3.1.5
When I run the same command under cruby 3.1.5 and bundler 2.5.11. The correct missing platform  `universal-java-21` is added properly:

```
PLATFORMS
   arm64-darwin-22
   arm64-darwin-23
   universal-java-17
+  universal-java-21
   x86_64-linux
```

**Comment by skunkworker** [comment]
Is this an issue I should open up in https://github.com/rubygems/rubygems? Or is it most likely jruby at fault?

**Comment by headius** [comment]
Let's close this and reopen if it turns out there's something to fix in JRuby itself.
