### ISSUE TITLE
Linkage errors from java_import are lazy

### ISSUE THREAD

**Issue by headius** [jruby/jruby#8299]
As of JRuby 9.3.0.0, linkage errors that would occur during `java_import` have become lazy, happening only after the import upon the first use of the class.

Using a modified version of the case from #799, the `blah.Blah` class can be `java_import`ed without error, but eventually fails due to the missing `blah.Foo` class:

```
$ (chruby jruby-9.3.14.0 ; jruby -e 'java_import "blah.Blah"')
$ (chruby jruby-9.3.14.0 ; jruby -e 'java_import "blah.Blah"; Blah.new')
Unhandled Java exception: java.lang.NoClassDefFoundError: blah/Foo
java.lang.NoClassDefFoundError: blah/Foo
               <clinit> at blah/Blah.java:5
```

I think this was probably a simple mistake in the porting of `java_import` from Ruby to Java in #6661 at the following line, which defers class initialization for this path:

https://github.com/jruby/jruby/commit/5a8ef9fea5333abae43c9917676b1df75e7aa22a#diff-cabfd925021b0b615287200ad6cf2469755af74bf4dfd560ea31161b22fda59eR116

We probably should fix this to eagerly initialize `java_import` classes so that linkage errors show up sooner.

**Comment by headius** [comment]
@kares You did that `java_import` port PR... did you intend to disable class initialization?

**Comment by kares** [comment]
Was thinking about having lazy imports, but I do not think they should be lazy by default. Changing this makes sense, IMHO (even if JRuby does not implement lazy imports).

**Comment by headius** [comment]
@kares Ok I will push a PR to switch that to eager class initialization in 10 and then we can call this and #799 resolved.
