### ISSUE TITLE
Link directly towards the primary blog, from the main website

### ISSUE THREAD

**Issue by rubyFeedback** [jruby/jruby#8313]
I recently read https://blog.jruby.org/, from a reddit link. I did not know there was a blog.

I then checked on the main website:

https://www.jruby.org/

I found a link towards blog.jruby.org, but I had to go to:

1) https://www.jruby.org/community

and then

2) https://www.jruby.org/blogs

And then there was a link there, towards https://blog.jruby.org/.

That structure is ok for average visitors, I assume, but I also have to say I would have
never found it without the reddit link.

I would thus like to propose to linking towards that blog directly, from the main website.
Not sure where to place it, perhaps right to the "Community" entry on top.

(Also, if someone changes the homepage, perhaps consider removing "RECENT TWEETS",
as there is no content there, ever since Musk changed twitter to x - seems it kind of 
died. There is not really a big point in making available something about news, when
there is no news to be shown. It just wastes space on the screen.)

**Comment by headius** [comment]
You know I thought about this just the other day and didn't get back to it to put a link up. You're right, blog should be prominent on the header links.

**Comment by headius** [comment]
We will also look into fixing or removing the RECENT TWEETS, perhaps replacing with "recent toots" since we usually cross-post to Mastodon as well.

**Comment by enebo** [comment]
https://gitlab.com/idotj/mastodon-embed-timeline

**Comment by headius** [comment]
I also replaced tweets with toots using the link @enebo provided, but the formatting still seems a little wonky. Not sure what's wrong... we could use some help here!
