### ISSUE TITLE
valid_encoding? returns true after a string is modified with invalid encoding

### ISSUE THREAD

**Issue by haberman** [jruby/jruby#8316]
**Environment Information**

```
$ ruby --version
jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 OpenJDK 64-Bit Server VM 22+-google-release-sts-632706408 on 22+-google-release-sts-632706408 +jit [linux-x86_64]
$ uname -a
Linux <hostname> 6.6.15-2rodete2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.15-2rodete2 (2024-03-19) x86_64 GNU/Linux
```

**Expected Behavior**

Test case:

```ruby
puts "\x80".valid_encoding?

str = " "
str[0] = "\x80"
puts str.valid_encoding?
```

CRuby output:

```
false
false
```

This makes sense, because in the second case the string is mutated such that it is no longer valid UTF-8.

**Actual Behavior**

JRuby output:

```
false
true
```

**Comment by enebo** [comment]
Wow.  At first when you reported using JRuby 9.2 I just assumed we had fixed it in the last 4 years but it appears to still be broken.  We will be fixing this but it will be on JRuby 9.4.x and newer.

**Comment by headius** [comment]
We must not be invalidating the code range when injecting an invalid string.

**Comment by enebo** [comment]
We have this reasonable CR logic which will determine that it is invalid but then when we come back:

```java
if (cr != CR_BROKEN) source.setCodeRange(cr);
```

In this case we are going from CR_7BIT to CR_BROKEN so it should mark it as such...but why was this if added in the first place?

**Comment by haberman** [comment]
Thanks for the quick fix!
