### ISSUE TITLE
sleep sometimes seems to be a no-op

### ISSUE THREAD

**Issue by ioquatix** [jruby/jruby#8320]
See the discussion here: <https://github.com/oracle/truffleruby/issues/2716>

**Comment by headius** [comment]
Thank you! Fix should be fairly simple, just use JDK sleep methods that have nanosecond precision and track time spent in nanoseconds.

**Comment by headius** [comment]
Doesn't appear any specs were written for this when it was fixed in TR so we should add some.

**Comment by jpcamara** [comment]
I'll give this a go!

**Comment by headius** [comment]
@jpcamara Excellent! Start with RubyKernel.java in the sleep method and you can see how we get milliseconds from the incoming value and pass it through. Just need to do nanoseconds instead and build some new versions of that call path.

**Comment by jpcamara** [comment]
Here's my first stab at it: https://github.com/jruby/jruby/pull/8332

**Comment by headius** [comment]
Fixed by #8332.

**Comment by ioquatix** [comment]
Nice!!
