### ISSUE TITLE
IPv4-mapped IPv6 addresses cause Addrinfo to error

### ISSUE THREAD

**Issue by mhashizume** [jruby/jruby#8325]
**Environment Information**
  
- jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 25.422-b05 on 1.8.0_422-b05 +jit [arm64-darwin]
- macOS 14.5 

**Expected Behavior**

I reported a similar bug in https://github.com/jruby/jruby/issues/8248

An IPv6 address can be formatted to represent an IPv4 address (as defined in [RFC 4291](https://www.rfc-editor.org/rfc/rfc4291#section-2.2)) such as ::ffff:192.0.2.128.

MRI allows you to create Addrinfo objects using these types of addresses:

```
$ ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin23]
$ irb -r socket
irb(main):001> Addrinfo.new(['AF_INET6', 0, nil, '::ffff:192.0.2.128'], :INET6)
=> #<Addrinfo: ::ffff:192.0.2.128>
```

**Actual Behavior**

JRuby 9.4.8.0 errors when attempting to create a new Addrinfo object using these types of IPv6 addresses:

```
$ ruby -v
jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 25.422-b05 on 1.8.0_422-b05 +jit [arm64-darwin]
$ irb -r socket
Exception `LoadError' at /Users/michael.hashizume/.rbenv/versions/jruby-9.4.8.0/lib/ruby/stdlib/io/console/bsd_console.rb:6 - native console on MacOS only supported on i386, x86_64
irb(main):001> Addrinfo.new(['AF_INET6', 0, nil, '::ffff:192.0.2.128'], :INET6)
org/jruby/ext/socket/Addrinfo.java:139:in `initialize': getaddrinfo: Address family for hostname not supported (SocketError)
	from org/jruby/RubyClass.java:935:in `new'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1274:in `eval'
	from org/jruby/RubyKernel.java:1722:in `loop'
	from org/jruby/RubyKernel.java:1423:in `catch'
	from /Users/michael.hashizume/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/irb-1.13.2/exe/irb:9:in `<main>'
	from org/jruby/RubyKernel.java:1220:in `load'
	from /Users/michael.hashizume/.rbenv/versions/jruby-9.4.8.0/bin/irb:25:in `<main>'
```

It does seem like JRuby interprets these types of addresses as IPv4. When I change from INET6 to INET, JRuby parses it as an IPv4 address and produces no errors:

```
irb(main):002> Addrinfo.new(['AF_INET6', 0, nil, '::ffff:192.0.2.128'], :INET)
=> #<Addrinfo: 192.0.2.128>
```

And more common IPv6 address types (like link-local) seem fine:

```
irb(main):003> Addrinfo.new(['AF_INET6', 0, nil, 'fe80::7086:7dff:fe4b:9f87'], :INET6)
=> #<Addrinfo: fe80::7086:7dff:fe4b:9f87>
irb(main):004>
```

**Comment by headius** [comment]
Would a fix similar to #8294 work here? cc @mullermp @enebo

**Comment by enebo** [comment]
The background on this is we use Java socket implementation and it does make these ipv4.  Without totally going fully native for all sockets we play games in objects like AddrInfo to remember that this was specified using ipv6 syntax and we pretend it is in Ruby (while it is still v4 in Java).

**Comment by enebo** [comment]
@mhashizume I am curious if you run into more issues or not.  This hopefully will still work for networking but display itself as ipv6 in Ruby.

I did not add specs and there is a huge hole in coverage.  I simply do not have the time right now.  If anyone wants to add specs spec/ruby/library/socket/addrinfo (which is a synced clone of the ruby/spec project which is another place to submit a PR) I would happily review and land.

**Comment by mhashizume** [comment]
Thanks @enebo , I'll let you know if we run into any other issues.
