### ISSUE TITLE
ARM64 macOS errors?

### ISSUE THREAD

**Issue by MSP-Greg** [jruby/jruby#8340]
In Puma's CI I thought I'd check if JRuby CI would run on the GitHub Actions arm64 macOS runners.  Consistent failures (different message error) on the same two tests, which involve restarting Puma.

We have intermittent failures using 'macos-13 jruby', but the tests that fail on arm64 often pass on the x64 jobs.

Error info is below, similar issue opened in Puma, see https://github.com/puma/puma/issues/3446

Any ideas?

GHA job: macos-14 jruby
```text
jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 21.0.4+7-LTS on 21.0.4+7-LTS +jit [arm64-darwin]
SyntaxError: /Users/runner/.rubies/jruby-9.4.8.0/bin/jruby:1: invalid multibyte char (UTF-8)
```

GHA job: macos-14 jruby-head
```text
jruby 9.4.9.0-SNAPSHOT (3.1.4) 2024-08-12 52b51d5bb8 OpenJDK 64-Bit Server VM 21.0.4+7-LTS on 21.0.4+7-LTS +jit [arm64-darwin]
SyntaxError: /Users/runner/.rubies/jruby-head/bin/jruby:8: syntax error, unexpected local variable or method
if command -v local >/dev/null; then
              ^~~~~
```

**Comment by headius** [comment]
And you only see these errors on aarch64? That is very peculiar; the parsing logic for Ruby code should work the same on any hardware platform. I suspect this is related to something else in the environment outside of the hardware architecture.

**Comment by headius** [comment]
I commented on the puma issue; this appears to be something peculiar happening with those runs where the JRuby launcher executables (a shell script or native binary) are being executed as though they are Ruby scripts, leading to these syntax errors. It is unrelated to aarch64, but I can't say why it's happening without more context.
