### ISSUE TITLE
`Pathname#glob`  with a non-existant path raises `ENOENT`

### ISSUE THREAD

**Issue by Earlopain** [jruby/jruby#8358]
**Environment Information**
  
* jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 17.0.12+7 on 17.0.12+7 +jit [x86_64-linux]
* Linux DESKTOP-PC 6.10.10-arch1-1 `#1` SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux

**Expected Behavior**
```rb
Pathname.new("/i_dont_exist").glob("*.gemspec")
=> []
```

**Actual Behavior**
```rb
Pathname.new("/i_dont_exist").glob("*.gemspec")
org/jruby/RubyFile.java:983:in `realpath': No such file or directory - /i_dont_exist (Errno::ENOENT)
        from org/jruby/ext/pathname/RubyPathname.java:343:in `glob'
        from (irb):24:in `evaluate'
        from org/jruby/RubyKernel.java:1274:in `eval'
        from org/jruby/RubyKernel.java:1722:in `loop'
        from org/jruby/RubyKernel.java:1423:in `catch'
        from org/jruby/RubyKernel.java:1423:in `catch'
        from /home/earlopain/.rbenv/versions/jruby-9.4.8.0/lib/ruby/gems/shared/gems/irb-1.4.2/exe/irb:11:in `<main>'
        from org/jruby/RubyKernel.java:1220:in `load'
        from /home/earlopain/.rbenv/versions/jruby-9.4.8.0/bin/irb:25:in `<main>'
```

I think the problem is that it ends up calling realpath here: https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/pathname/RubyPathname.java#L343-L343

**Additional Information**

When using `Pathname::glob` it seems to handle it correctly:

```rb
Pathname.glob("/i_dont_exist/*.gemspec")
=> []
```

**Comment by headius** [comment]
The `realpath` call appears to have been introduced by @nomadium in https://github.com/jruby/jruby/pull/5105 to get more Pathname tests passing. I don't see an equivalent call in CRuby.

@nomadium Maybe you remember why that line was needed to pass tests? Forcing it to find a real path makes this logic fail if the path does not actually exist on filesystem.

**Comment by headius** [comment]
Equivalent line in CRuby is here: https://github.com/ruby/ruby/blob/91bb6afa75c2c469aa80dfc988ddc95acbfe75c8/ext/pathname/pathname.c#L1125

This calls `get_strpath` which just retrieves the path string from the Pathname object. It does not call `File.realpath`.

**Comment by headius** [comment]
I pushed https://github.com/jruby/jruby/pull/8361 to see what fails without the `realpath` call.

**Comment by headius** [comment]
Does not appear to be any significant failures resulting from that change. I'll rerun the ones that failed to make sure, but they don't appear to be related.

**Comment by headius** [comment]
It is unclear why @nomadium added the `realpath` call in their PR, but removing it does not cause any regression in CI. I've merged the PR and this should be ok now.

**Comment by Earlopain** [comment]
Cool, thanks for the fix! Didn't imagine it would be _that_ simple.

**Comment by headius** [comment]
Yes, sometimes you throw a dart and hit the bullseye! Thank you for the report and extra footwork!
