### ISSUE TITLE
Kernel.system hangs if sub process spawns child

### ISSUE THREAD

**Issue by halfnelson** [jruby/jruby#838]
Calling kernel.system with a command that spawns any other process causes the system call to not return until that spawned process is ended. Same as bug http://jira.codehaus.org/browse/JRUBY-4470. 

File: testsystem.rb

``` ruby
system('start notepad')
puts "done"
```

MRI

```
> ruby testsystem.rb
done

>
```

JRuby

```
> ruby testsystem.rb
[HANG]
```

I tracked the problem down to an assumption in ShellLauncher that when a process is closed all handles to stdin/out will be closed, but in this case the sub process inherits handles (on windows anyway) and even though the process is complete (process.waitFor does not block) the runPidAndWait will sit waiting for the stream pumps to rejoin the main thread.

I have patched the function to make it work properly here https://github.com/halfnelson/jruby/commit/33114bc8bf1a63a6fafbb0685c88fd6f6e79fc11

I still need to forcibly stop the input thread. That is another bug. I will file separately.

How do I go about writing a unit test for this, since the failure case means the code never returns? Spawn the request in another thread and add a timeout? Downside of that is it makes unit tests slower.

**Comment by kares** [comment]
works on Linux ... maybe this was a Windows specific issue on JRuby 1.7.x (EOL) 
... someone should give JRuby 9K a spin and report back if its still relevant

**Comment by MSNexploder** [comment]
Just checked, #system still blocks on 9.1.9.0 + Windows 7 (x64).

**Comment by Marcofeli** [comment]
Hi, actually I'm working with JRuby 1.7.27 on Ubuntu 16.04 and it seems to have the same issue.

**Comment by headius** [comment]
@Marcofeli I'm guessing you would not have this problem on JRuby 9.2.x, since in 9k we reimplemented process management (for POSIX systems) using true native process functions.

The rest of this issue is valid still, but duplicates many other issues that all have the same cause: we do not have native process management on JRuby yet. See also #4964 and others.
