### ISSUE TITLE
trouble loading java class from jar

### ISSUE THREAD

**Issue by homanchou** [jruby/jruby#840]
I'm having trouble wrapping the amazon-merchant-web-service-java-sdk in jruby.

The java sdk, jar and source, can be found at: https://developer.amazonservices.com/doc/bde/feeds/v20090901/java.html/182-0022359-5036344 (click the yellow download button in upper right)

I am able to instantiate some classes ....

    require 'java'
    require 'lib/MaWSJavaClientLibrary-1.1.jar'

    module MWS
      include_package 'com.amazonaws.mws'
      include_package 'com.amazonaws.mws.model'
    end

    config = MWS::MarketplaceWebServiceConfig.new  #this works!!

... but not others

    client = MWS::MarketplaceWebServiceClient.new  #this does NOT work!!!
    NameError: MarketplaceWebServiceClient not found in packages com.amazonaws.mws, com.amazonaws.mws.model; last error: cannot load Java class com.amazonaws.mws.model.MarketplaceWebServiceClient
    const_missing at file:/Users/...

Why is it not found?

**Comment by kares** [comment]
original issue is fine and the error message is improved, opened a new one for `iface.new` at #3275
