### ISSUE TITLE
Threads which have blocked Fibers are not killable

### ISSUE THREAD

**Issue by halorgium** [jruby/jruby#841]
It seems that a `Thread` which is running a `Fiber` and that `Fiber` is blocked on a `Queue#pop` is unkillable via `Thread#kill`. 

[repro](https://gist.github.com/halorgium/b9533251e1ce5b81fcc9)

@headius mentioned that it should be possible to kill the `Thread`'s current `Fiber`. 
@dbussink wrote a rubyspec for this recently. rubinius/rubinius@9efac8a101d2ecd185b34b0577aeb536ec7e7616

/cc @tarcieri rubinius/rubinius#2392

**Comment by MSNexploder** [comment]
Repro works just as expected on JRuby 9.1.2.0

**Comment by enebo** [comment]
Confirmed this is working in 9.x and 1.7.x is EOL.  Resolving against a release so it shows up.
