### ISSUE TITLE
[Possible bug] Can not start jruby-swing applications since 9.4.9.0 - or rather, the window auto-closes almost instantly

### ISSUE THREAD

**Issue by rubyFeedback** [jruby/jruby#8416]
So, the following is a standalone hello-world example in jruby-swing:

    #!/usr/bin/ruby -w
    # Encoding: UTF-8
    # frozen_string_literal: true
    # ============================================================================ #
    # === HelloWorldExample  
    # ============================================================================ #
    java_import javax.swing.JFrame
    java_import javax.swing.JLabel
    java_import javax.swing.JPanel
    java_import java.awt.Font

    class HelloWorldExample < JFrame # === HelloWorldExample

      alias e puts

      # ========================================================================== #
      # === initialize
      # ========================================================================== #
      def initialize
        run
      end

      # ========================================================================== #
      # === run
      # ========================================================================== #
      def run

        frame = JFrame.new("HelloWorldExample")
        frame.setDefaultCloseOperation(JFrame::EXIT_ON_CLOSE)

        panel = JPanel.new
        label = JLabel.new("Hello World")

        panel.add(label)
        frame.add(panel)
    
        frame.pack
        frame.setSize(1400, 1000)
        frame.setVisible(true) 
      end

    end

    HelloWorldExample.new

I am using:

    jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 17.0.7+7-jvmci-22.3-b18 on 17.0.7+7-jvmci-22.3-b18 +jit [x86_64-linux]

It works fine.

When I switch to 

    jruby 9.4.9.0 (3.1.4) 2024-11-04 547c6b150e OpenJDK 64-Bit Server VM 17.0.7+7-jvmci-22.3-b18 on 17.0.7+7-jvmci-22.3-b18 [x86_64-linux]

though, a window shows up, but then immediately closes, without any
further notification as to why it closed. Nothing is printed on the
terminal after that window closes.

I have not investigated this further (for now I'll revert to 9.4.8.0,
which is mostly the same anyway) but I believe that no matter the
underlying reason, it should not instantly auto-close without any notice.
After all jruby 9.4.8.0 shows a different behaviour, and I can interact with
the window that is displayed, whereas on jruby 9.4.9.0 I can not do
anything since it auto-closes at once - all with the same code shown above.

**Comment by headius** [comment]
Confirmed on MacOS.

**Comment by headius** [comment]
The problem manifests a bit differently for me: no window is displayed and the process terminates soon after I start seeing log messages on the console.

**Comment by headius** [comment]
Ok, I'm not sure this is a bug per se.

The behavior on 9.4.9.0 appears to be that the main script exits, which shuts down JRuby and the process terminates. Adding a blocking call like `sleep` or `gets` to the script keeps it running and allows the window to display.

On 9.4.8.0 the main script exits but the process does not terminate.

The 9.4.9.0 behavior is actually what I would *expect* to happen, but I have no explanation yet for why it does not do that in 9.4.8.0. It is as if some thread started by the Swing subsystem is now a daemon thread and does not keep the process alive.

I'll review changes in 9.4.9.0 to see why this changed, but you should not expect the process to be usable after the main script exits; it will shut down key subsystems in JRuby and no longer be fully-functional even if the process does not terminate.

**Comment by headius** [comment]
@enebo I have not found any changes that would explain why a Swing app now terminates (as I expect) when the main script exits. I confirmed it continues to run back to 9.4.6.0.

**Comment by headius** [comment]
Thread dump of 9.4.8.0 after the script exits shows that the main thread has indeed terminated, but other non-JRuby threads continue to keep the process alive.

```
2024-11-18 08:42:09
Full thread dump OpenJDK 64-Bit Server VM (25.362-b09 mixed mode):

"DestroyJavaVM" #17 prio=5 os_prio=31 tid=0x000000014038e800 nid=0x2203 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"AWT-EventQueue-0" #16 prio=6 os_prio=31 tid=0x000000011bbe2000 nid=0x10703 waiting on condition [0x000000016ec3e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076afa8ef8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
	at java.awt.EventQueue.getNextEvent(EventQueue.java:554)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:187)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

"Java2D Disposer" #15 daemon prio=10 os_prio=31 tid=0x000000011baf4800 nid=0xca0b in Object.wait() [0x000000016ea32000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076b02e058> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x000000076b02e058> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:750)

"Java2D Queue Flusher" #14 daemon prio=10 os_prio=31 tid=0x0000000150326800 nid=0xe613 in Object.wait() [0x000000016e826000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076afbd948> (a sun.java2d.opengl.OGLRenderQueue$QueueFlusher)
	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:203)
	- locked <0x000000076afbd948> (a sun.java2d.opengl.OGLRenderQueue$QueueFlusher)

"AWT-Shutdown" #13 prio=5 os_prio=31 tid=0x000000011c074000 nid=0xa30f in Object.wait() [0x000000016e502000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000076ad7b438> (a java.lang.Object)
	at java.lang.Object.wait(Object.java:502)
	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
	- locked <0x000000076ad7b438> (a java.lang.Object)
	at java.lang.Thread.run(Thread.java:750)

"AppKit Thread" #12 daemon prio=5 os_prio=31 tid=0x00000001585f9800 nid=0x103 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x0000000140025000 nid=0x5503 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x0000000158020000 nid=0x4a03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x0000000158017000 nid=0x4803 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x0000000158016800 nid=0x4c03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00000001588a1800 nid=0x4e03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x000000015889f800 nid=0x4603 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x0000000158866800 nid=0x3203 in Object.wait() [0x000000016d38a000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0009d58> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000006c0009d58> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:188)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x0000000158863800 nid=0x3603 in Object.wait() [0x000000016d17e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0011a48> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c0011a48> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=31 tid=0x000000015885d000 nid=0x3703 runnable 

"ParGC Thread#0" os_prio=31 tid=0x000000015880f000 nid=0x2707 runnable 

"ParGC Thread#1" os_prio=31 tid=0x000000015881b000 nid=0x3f03 runnable 

"ParGC Thread#2" os_prio=31 tid=0x000000015881b800 nid=0x2b03 runnable 

"ParGC Thread#3" os_prio=31 tid=0x000000015881c800 nid=0x3d03 runnable 

"ParGC Thread#4" os_prio=31 tid=0x000000015881d000 nid=0x3c03 runnable 

"ParGC Thread#5" os_prio=31 tid=0x000000015881e000 nid=0x2e03 runnable 

"ParGC Thread#6" os_prio=31 tid=0x000000015881e800 nid=0x3903 runnable 

"ParGC Thread#7" os_prio=31 tid=0x000000015881f800 nid=0x3003 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x000000014002b000 nid=0x7e03 waiting on condition 
```

**Comment by acrocool** [comment]
main_frame = MainFrame.new

sleep(1) while main_frame.is_visible

**Comment by enebo** [comment]
@headius We changed something with some typs of threads not preventing the runtime from shutting down.  Swing main thread *I think* is a daemon thread.

**Comment by headius** [comment]
@enebo I'll review commits and see if I can figure out what changed in 9.4.9.0.
