### ISSUE TITLE
Time#nsec rounding is happening at a place we don't want.

### ISSUE THREAD

**Issue by BanzaiMan** [jruby/jruby#843]
As reported in http://markmail.org/search/?q=jruby-user#query:jruby-user%20order%3Adate-backward+page:1+mid:3kk6wvustmpzyd2n+state:results

```
t1=Time.utc(2013,6,30,14,56,14,263031.604)
t2=Time.utc(2013,6,30,14,56,14,263031.605)
t1 == t2 # should be false
```

**Comment by kares** [comment]
still a valid issue (t1 == t2 holds in 9.1.7.0)

**Comment by headius** [comment]
@kares Are you planning to work on this since you tagged it for 9.1.8.0?

**Comment by headius** [comment]
I'm clearing the target on this one since it has been an outstanding issue for a long time. We welcome someone picking this up and trying to fix it.

**Comment by kares** [comment]
@headius will take a stub at this old timer. wanted to get a few ones in, which you already looked into. thx
