### ISSUE TITLE
remove_const does not cause module instance variables to get garbage collected

### ISSUE THREAD

**Issue by betelgeuse** [jruby/jruby#859]
Given the following ruby code:

``` ruby
module Foo
  def self.bar
    @m = Mine.new
  end
end

class Mine
end

Foo.bar
m = Mine.new
puts 'Should have two now. Press enter'
gets
m = nil
puts 'Should have one now. Press enter'
gets
Object.send(:remove_const, :Foo)
puts 'Should have zero now. Press enter'
gets
Foo.bar
```

When I run this with:

```
$ jruby -J-Djruby.reify.classes=true -J-Dcompile.mode=OFF foo.rb 
Should have two now. Press enter

Should have one now. Press enter

Should have zero now. Press enter

NameError: uninitialized constant Foo
  const_missing at org/jruby/RubyModule.java:2631
         (root) at foo.rb:21
```

Then I should see the expected number of Mine objects in visual vm.

Setting m to nil causes jvisualvm to deincrement the count but remove_const still keeps the @m instance variable live.

```
jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.7.0_21-b12 [darwin-x86_64]
```

**Comment by enebo** [comment]
I see no remotely near term solution for this and at most we would reduce holding references but not completely eliminate this issue.  On top of this we now also have temps in IR and this has similar behavior.   I think this should be closed as we have no concrete plans to address it.
