### ISSUE TITLE
Argument list too long pushing site

### ISSUE THREAD

**Issue by headius** [jruby/jruby#879]
@jendave @mkristian Got a new one for ya :-)

I managed to get all the way to the publish phase, and then it blows up because it tries to add so many files to git that the git command can't handle it:

[ERROR] Failed to add new files to SCM: The git-add command failed. /bin/sh: /usr/local/bin/git: Argument list too long

So...I'm stuck again.

**Comment by rtyler** [comment]
Uh, Mr @headius is this still a valid issue? :)

**Comment by enebo** [comment]
We are no longer publishing our site the same way as we use github pages now.  Assuming this bug is actually about publishing our website.
