### ISSUE TITLE
ARGF is missing lots of 1.9+ io-related methods

### ISSUE THREAD

**Issue by jrochkind** [jruby/jruby#891]
I am expanding this since I am just going to add many new methods which are missing from ARGF today: [:argv, :to_write_io, :lines, :readpartial, :read_nonblock, :getbyte, :readbyte, :write, :print, :putc, :puts, :printf, :inplace_mode, :inplace_mode=, :external_encoding, :internal_encoding, :set_encoding].  If I cannot do them all I will make sub-issues for these.

Original issue text:

[core ARGF is supposed to have a #set_encoding method](http://www.ruby-doc.org/core-1.9.3/ARGF.html#method-i-set_encoding)

It does in MRI 1.9.3. 

It does not in jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.6.0_51-b11-457-11M4509 [darwin-x86_64]

    $ ARGF.set_encoding("UTF-8")
    NoMethodError: undefined method `set_encoding' for #<Object:0x307a140f>

**Comment by kares** [comment]
`set_encoding` and others is available in latest 1.7 + there's even more goodies in 9K these days :)
