### ISSUE TITLE
Performance improvements for transcoding

### ISSUE THREAD

**Issue by headius** [jruby/jruby#900]
We did a lot of work for 1.7.5 to improve compatibility of transcoding, but as a result many transcoding paths are much less efficient. We MUST do a pass over this code before 1.7.5 release to avoid massively impacting performance of e.g. transcoded IO operations.

**Comment by rtyler** [comment]
@headius surely this is closeable now right?

**Comment by headius** [comment]
@rtyler Yup.

9k rewrote transcoding entirely to be like MRI (a port, basically), so any further perf issues are new issues.
