### ISSUE TITLE
__method__ does not return valid symbol when Non-ASCII method

### ISSUE THREAD

**Issue by headius** [jruby/jruby#914]
Originally reported as http://jira.codehaus.org/browse/JRUBY-6055.

Kernel#_method_ does not return valid symbol when Non-ASCII method call.

Reproduction: https://gist.github.com/headius/6076504

**Comment by enebo** [comment]
Extracting out of the gist:

```ruby
# -*- mode: ruby; coding: utf-8 -*-

def こんにちは
  unless __method__ == :'こんにちは'
    raise "%s is not equals to %s" % [__method__, :'こんにちは']
  end
end

こんにちは
```

We have several other issues related to us not properly storing the encoding of mbc symbol names (and method table is String values).

**Comment by headius** [comment]
Very likely to be fixed by identifier work @enebo is doing.

**Comment by headius** [comment]
Fixed by @enebo's symbol/identifier work.
