### ISSUE TITLE
Allow Java arrays to be serialized forth and back from DRb

### ISSUE THREAD

**Issue by rosenfeld** [jruby/jruby#918]
If you get a byte array (as returned by 'string'.to_java_bytes, for instance) as a result of a remote call using DRb you'll get an error if you try to use it as a parameter for another remote call.

Please, see full discussion with examples here:

http://comments.gmane.org/gmane.comp.lang.jruby.devel/11615

**Comment by headius** [comment]
Unfortunately the original discussion is 404. Since this bug many things have improved in marshaling and serializing Java and Ruby objects together, so it's possible this works fine now. If not, and it's still a concern, please open a new issue.
