### ISSUE TITLE
Importing static inner class does not work as expected

### ISSUE THREAD

**Issue by ftomassetti** [jruby/jruby#933]
I tried to access a static inner class:

```ruby
require 'the_right_jar.jar'
import 'path.to.Outer'
```

`Outer.inner` or `Outer::Inner` give me an exception (undefined method or undefined constant 'Inner'

However I can import the class using `JavaUtilities.get_proxy_class('path.to.Outer$Inner')`

**Comment by kares** [comment]
sorry for the very late response, but if I was to guess `Inner` was not a public class/interface and this is how it works in JRuby. but since in Ruby there's really no such thing as "private" I'll open another issue for having `Outer::Inner` feature working similar to a `private_constant` ...
