### ISSUE TITLE
Implement UNIXServer and UNIXSocket.for_fd

### ISSUE THREAD

**Issue by headius** [jruby/jruby#940]
Since UNIXServer and UNIXSocket use a real fd and jnr-enxio, they could both support for_fd without too much effort.

One minor issue that would need to be fixed is that there's no way to create a UNIXSocket from jnr/jnr-unixsocket with a given fd; it handles creating the fd in its factory methods and does not expose the fd-receiving constructor.

**Comment by kares** [comment]
done at https://github.com/jruby/jruby/pull/3494
