### ISSUE TITLE
.jrubyrc file not supporting `cext.enabled=true`

### ISSUE THREAD

**Issue by jwoertink** [jruby/jruby#953]
My default JRuby uses 1.9.3 mode. I added a `.jrubyrc` file to my project containing

``` text
compat.version=2.0
cext.enabled=true
```

Then I was able to do `ruby -v` and see it was in 2.0.0 mode. This verified that the .jrubyrc file was being read. I tried to install the ox gem, and got

``` text
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /Users/jeremy/.rvm/rubies/jruby-1.7.4/bin/jruby extconf.rb 
NotImplementedError: C extension support is not enabled. Pass -Xcext.enabled=true to JRuby or set JRUBY_OPTS or modify .jrubyrc to enable.
```

I tried closing my terminal, and re-opening, but still got the error. After I did `export JRUBY_OPTS=-Xcext.enabled=true` I was able to bundle the gem. So it seems the .jrubyrc file just ignored that option. 

My system:
jruby 1.7.4 (2.0.0) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.6.0_51-b11-457-11M4509 [darwin-x86_64]
OSX 10.8.4

**Comment by rbotafogo** [comment]
This is an old thread, but I´m having trouble with .jrubyrc.  I´ve put it in my home directory and it doesn´t seem to change anything.  I actually want to change the java heap size. 

Thanks

**Comment by headius** [comment]
@rbotafogo Please open a new issue if you're having problems with .jrubyrc on a current version of JRuby.
