### ISSUE TITLE
Equality test fails between Java class and JRuby class

### ISSUE THREAD

**Issue by tagomoris** [jruby/jruby#956]
I think that class object from java code such like `return Long.class;` should pass with equality test in jruby code.

Test below fails on jruby-1.7.4.

``` ruby
java_class_object = MyClass.java_implemented_method #=> java.lang.Long
ruby_class_object = java.lang.Long #=> Java::JavaLang::Long

expect(java_class_object).to eql(ruby_class_object) # fails!
expect(java_class_object).to eql(ruby_class_object.java_class) # success
```

I think that first test should success.

**Comment by rtyler** [comment]
FWIW this still exists in 9k.


**Dope.java**
```java
public class Dope {
    public static Class give_me_java_long() {
        return Long.class;
    }
}
```

```
[1] pry(main)> java_import 'Dope'
=> [Java::Default::Dope]
[2] pry(main)> Dope.give_me_java_long
=> class java.lang.Long
[3] pry(main)> Dope.give_me_java_long == java.lang.Long
=> false
[4] pry(main)> 
```

```
java_import 'Dope'
Dope.give_me_java_long == java.lang.Long
```

**Comment by headius** [comment]
JRuby is fairly up front about how we build a second proxy class hierarchy to wrap the Java class hierarchy. I don't believe we should fix this.

As a workaround, when you know you'll have a `java.lang.Class` in hand, you can compare using `java_class`:

```
[] ~/projects/jruby $ jruby -e 'p java.lang.Class.forName("java.lang.Long").eql?(java::lang::Long)'
false

[] ~/projects/jruby $ jruby -e 'p java.lang.Class.forName("java.lang.Long").eql?(java::lang::Long.java_class)'
true
```

Note that this is not unlike Java, in which the `java.lang.Class` instance doesn't provide any of the "class-level" fields and static methods. The object you get back is a reflective mirror of the logical class.
