### ISSUE TITLE
java_import does not define top-level global when called from class method

### ISSUE THREAD

**Issue by jrochkind** [jruby/jruby#975]
`jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on Java HotSpot(TM) 64-Bit Server VM 1.6.0_51-b11-457-11M4509 [darwin-x86_64]`

From the [wiki](https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby), 

>    java_import java.lang.System
>    ...
> After this point, the "System" constant will be available in the global name space (i.e. available to any script).

However, this does not work when calling `java_import` from inside a class method. 

``` ruby
class Util
  def self.import_stuff
     java_import java.lang.System
  end
end

Util.import_stuff

System   #=> NameError: uninitialized constant System
::System #=> NameError: uninitialized constant System 
Util::System # There it is! => Java::JavaLang::System

# It does _normally_ create top-level globals....
java_import java.lang.System
::System # => Java::JavaLang::System
```

Is this a bug? Or is it somehow as designed? It would be convenient to be able to import java classes to top-level methods in utility methods like that. Oddly, it _does_ seem to work if you do the `java_import` in an actual ordinary instance method, just not a class method. 

I suppose I could do my own stuff to somewhat confusingly dynamically set
the top level ::System constant to Util::System as a workaround, but it gets to be kind of confusing.

**Comment by rtyler** [comment]
FWIW this confusing behavior still applies to JRuby 9k

```
[1] pry(main)> module MyPackage ; end
=> nil
[2] pry(main)> 
[3] pry(main)> class MyPackage::Util
[3] pry(main)*   def import_stuff    
[3] pry(main)*     java_import java.lang.System         
[3] pry(main)*   end      
[3] pry(main)* end  
=> :import_stuff
[4] pry(main)> 
[5] pry(main)> MyPackage::Util.new.import_stuff
=> [Java::JavaLang::System]
[6] pry(main)> ::System
=> Java::JavaLang::System
[7] pry(main)> System
=> Java::JavaLang::System
```

```
[1] pry(main)> class Util
[1] pry(main)*   def self.import_stuff  
[1] pry(main)*     java_import java.lang.System     
[1] pry(main)*   end    
[1] pry(main)* end  
=> :import_stuff
[2] pry(main)> 
[3] pry(main)> Util.import_stuff
=> [Java::JavaLang::System]
[4] pry(main)> 
[5] pry(main)> System
NameError: uninitialized constant System
from org/jruby/RubyModule.java:3144:in `const_missing'
[6] pry(main)> 
```

**Comment by enebo** [comment]
wiki had been edited since this was opened and I added an additional paragraph about using java_import from within methods (and also recommending people do not do it).
