### ISSUE TITLE
Fix test profile

### ISSUE THREAD

**Issue by BanzaiMan** [jruby/jruby#978]
It has been a while since we moved to maven, but the main 'test-extended' target that Travis runs have never been completely fixed.

This is the last successful build with the old 'ant' way (`ant test-extended`): https://travis-ci.org/jruby/jruby/jobs/8438749

And this is the first failure with the new 'mvn' way (`mvn -q -Ptest test`): https://travis-ci.org/jruby/jruby/jobs/8685411

Not exactly sure how the things changed and broke, but these should be fixed.

**Comment by jvbreen1** [comment]
@BanzaiMan is this an intermittent issue? I can't seem to reproduce:

Running org.jruby.embed.ScriptingContainerTest
Tests run: 84, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.954 sec - in org.jruby.embed.ScriptingContainerTest
Running org.jruby.embed.ReaderInputStreamTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.079 sec - in org.jruby.embed.ReaderInputStreamTest

**Comment by kares** [comment]
@jvbreen1 feel free to fire up a PR where you revert the changes against a green master and we'll see :)

**Comment by jvbreen1** [comment]
@kares I'm not sure I understand. I thought the issue was fixed. Are you suggesting I revert the change in order to reproduce the issue and thus verify the fix?

**Comment by headius** [comment]
Fixed long ago, before 9k release.
