### ISSUE TITLE
Certificates generated using jruby-openssl have a bad value for Authority Key Identifier, CRL Distribution Points and Authority Information Access

### ISSUE THREAD

**Issue by johnae** [jruby/jruby#994]
when using "openssl x509 -text -in /path/to/generated.crt" I get this value for the identifier:

```
X509v3 Authority Key Identifier: 
            0...PW.....z.`@..D^.(.D.
```

If I use MRI to generate the certificate this value looks like this:

```
X509v3 Authority Key Identifier: 
            keyid:F2:80:1A:04:C3:D7:43:79:DB:54:F5:98:7B:05:72:37:92:76:03:F1
```

I've looked through the code for this but I am unable to determine the reason though I'm neither a java expert nor an expert on jruby internals.

**Comment by kares** [comment]
this particular issue has been fixed along the way, let us know if its still an issue.

**Comment by ahmet2mir** [comment]
@kares I still had the issue.

When running this code (create a slef signed cert with crl)

```ruby
require 'openssl'

key = OpenSSL::PKey::RSA.new(4096)

subject = "/C=FR/ST=IDF/L=PARIS/O=Company/CN=myhost.example"

cert = OpenSSL::X509::Certificate.new
cert.subject = cert.issuer = OpenSSL::X509::Name.parse(subject)

cert.not_before = Time.now
cert.not_after = Time.now + 365*24*60*60
cert.public_key = key.public_key
cert.serial = 0x0
cert.version = 2

ef = OpenSSL::X509::ExtensionFactory.new
ef.subject_certificate = ef.issuer_certificate = cert

cert.add_extension ef.create_extension('basicConstraints', 'CA:FALSE', true)
cert.add_extension ef.create_extension('keyUsage', 'keyEncipherment,dataEncipherment,digitalSignature')
cert.add_extension ef.create_extension('subjectKeyIdentifier', 'hash')
cert.add_extension ef.create_extension('authorityKeyIdentifier', 'keyid:always,issuer:always')
cert.add_extension ef.create_extension('crlDistributionPoints', "URI:http://example.com")

cert.sign key, OpenSSL::Digest::SHA256.new

File.open("/tmp/cert.pem", "w"){ |f| f.write cert.to_pem }

puts cert.to_text
```

`cert.to_text` returns 

```
X509v3 CRL Distribution Points: 
    URI:http://example.com
```

where `openssl x509 -noout -text -in /tmp/cert.pem` returns

```
X509v3 CRL Distribution Points: 
    ..URI:http://example.com
```

So unittests validate the cert.to_text output and pass, there is something (like an extra bit) added in to_pem or to_text ignore this.

**Comment by kares** [comment]
@ahmet2mir `to_text` details might not be 100% accurate, are the other parts problematic for you?
in any case, please open a new issue with details instead of commenting on a closed one. thanks.
